<?php
/**
 * Englische Fassung der Tutorials (app/Admin/tutorials.php) – gleiche Kurznamen, gleiche Reihenfolge der Listen.
 * Nutzt HelpController (Verwaltung auf Englisch), tutorials:export (Produkt-Website) und das Dashboard.
 * 'steps' = englische Untertitel der Videos (tools/tutorials/flows.mjs, t.step(de, en)) – Klartext ohne HTML;
 * 'manual' = nur die Bezeichnungen, in derselben Reihenfolge wie die Handbuch-Links des deutschen Eintrags.
 * Fehlt ein Feld, bleibt der deutsche Text.
 */
return [
    'tracks' => [
        'redaktion' => ['title' => 'Editors', 'lead' => 'Maintaining text, images, events and requests – everyday work shown in a few minutes.', 'for' => 'For everyone who maintains content'],
        'admin' => ['title' => 'Running a website', 'lead' => 'Users and roles, central details, design, custom data tables, accessible videos, interfaces and search engines.', 'for' => 'For website admins'],
        'agentur' => ['title' => 'Agencies & network', 'lead' => 'Running several websites: network overview, new websites, feature sets, shared content, AI, deploy and kits.', 'for' => 'For agencies and network administration'],
    ],
    'levels' => ['Einstieg' => 'Beginner', 'Grundlagen' => 'Basics', 'Fortgeschritten' => 'Advanced'],

    'tutorials' => [
        'r-ueberblick' => [
            'title' => 'Signing in & finding your way',
            'summary' => 'Sign in, sidebar with area colours, favourites ☆, search with ⌘K and help & support.',
            'goal' => 'You sign in, find your way around the dashboard, save frequently used places as favourites and find everything via search.',
            'prerequisites' => ['Your own account (email address and password) – provided by your administrator.'],
            'steps' => [
                'Open the admin area: your website address + /admin.',
                'Enter your email address and password, then “Anmelden” (sign in).',
                'The dashboard: key figures and “Was ist zu tun?” (what to do) – what needs attention today.',
                'Top left below the name: magnifier = search, speech bubble = assistant, ↗ = view website.',
                'The menu is on the left – e.g. “Daten” (data) for events, team or posts.',
                'Every area has its own colour. “Zurück zu …” (back to) at the top leads to the main menu.',
                'Need it often? Click the star ☆ next to the heading to add a favourite.',
                'The favourite now appears at the top of the sidebar – for your account only.',
                'Find anything: the magnifier or ⌘K (Windows: Ctrl+K) opens search – everywhere in the admin.',
                'Results: pages, entries, media, settings – or ask the assistant. Arrow keys select, ↵ opens.',
                'Bottom left, “Hilfe & Support” (help & support): manual, tutorials, assistant and “Problem melden” (report a problem).',
            ],
            'tips' => ['<b>Sign in with a passkey</b> (below the form): no password, just fingerprint, face or device PIN – set it up in your own account under <b>Passkeys</b>, if the website allows passkeys.', 'Rename favourites with <b>Bearbeiten</b> (edit) in the sidebar or reorder them (drag, or <kbd>Alt</kbd>+<kbd>↑</kbd>/<kbd>↓</kbd>).', 'On a smartphone the ☰ icon at the top left opens the menu, the magnifier at the top right opens search.'],
            'pitfalls' => ['After 8 wrong passwords, sign-in is locked for 15 minutes.', 'If a menu item is missing, your role does not have that permission – this is intended.'],
            'manual' => ['Signing in & account', 'Overview'],
        ],
        'r-uebersicht' => [
            'title' => 'The new dashboard',
            'summary' => 'Key figures, “what to do”, statistics without tracking, recently edited – and customising the dashboard.',
            'goal' => 'After signing in you see at a glance what needs doing, and you arrange the dashboard the way you work.',
            'prerequisites' => ['An admin account. Which cards appear depends on the permissions of your role.'],
            'steps' => [
                'After signing in: the dashboard. At the top a greeting, the date and quick actions for your role.',
                'Key figures as dials: pages online, entries, media, submitted – with a 30-day trend.',
                '“Was ist zu tun?” (what to do) – tasks by urgency, each with an explanation and a direct link.',
                'Statistics without visitor tracking: activity of the last 30 days – also as a table.',
                '“Zuletzt bearbeitet” (recently edited): continue where you or the team left off.',
                '“Hilfe & Einstieg” (help & getting started): ask KLXM Ai, tutorials for your role and what’s new.',
                '“Übersicht anpassen” (customise): move, hide or collapse cards – per account.',
                '“Standard wiederherstellen” (restore default) brings back the original layout. “Fertig” (done) closes.',
            ],
            'tips' => ['Cards can also be moved without a mouse: in customise mode with the arrow buttons.', 'The figures come from this website only – there is no visitor tracking and no cookies for it.'],
            'pitfalls' => ['If a card is missing, your role lacks the permission – or it is hidden (<b>Übersicht anpassen</b> shows hidden cards again).'],
            'manual' => ['The dashboard'],
        ],
        'r-seite-bearbeiten' => [
            'title' => 'Editing & publishing a page',
            'summary' => 'Change things right on the website: blocks, formatting bar, draft, preview, publish.',
            'goal' => 'You change text on a page right on the website, save a draft, check the preview and put the change live.',
            'prerequisites' => ['Permission “edit pages”; to publish, also “publish pages”.'],
            'steps' => [
                'Open the page on the website. Only signed-in editors see the dark bar at the top.',
                'In the middle of the bar, switch from “Ansehen” (view) to “Bearbeiten” (edit).',
                'In edit mode every block shows a frame, its name and “Bearbeiten” (edit).',
                'Click short texts with a dashed frame and type over them.',
                'Body text: select a word – the formatting bar appears – e.g. “Fett” (bold).',
                '“Bearbeiten” on a block opens all its fields on the right – links, images, variants.',
                'The preview on the left updates right away. Esc closes the sidebar.',
                '“Speichern” (⌘S) saves a draft – visitors still see the old version.',
                'Menu “⋯” › “Vorschau” (preview) shows the page without editing frames.',
                'Back to “Bearbeiten” – then “Veröffentlichen” (publish) and confirm: now the change is live.',
                'The arrow next to “Veröffentlichen” offers “Entwurf verwerfen …” (discard draft); earlier states under page settings › versions.',
            ],
            'tips' => ['<b>+</b> to the left of a block inserts a new block, ↑ ↓ move it.', 'Menu <b>⋯</b> › <b>Kompakt</b> (compact) collapses all blocks into slim rows – ideal for reordering.'],
            'pitfalls' => ['Saved is not published: visitors only see changes after <b>Veröffentlichen</b> (publish).', 'Centrally maintained details (e.g. phone) are changed under “Website”, not in the text.'],
            'manual' => ['Editing content', 'All blocks'],
            'mobileText' => 'Below 768 px, <b>Abbrechen</b> (cancel), <b>Speichern</b> (save) and <b>Veröffentlichen</b> (publish) sit in a bar at the bottom; the website menu is hidden in edit mode. Tapping text in a block shows its bar with <b>Bearbeiten</b> – the fields open above the bottom bar, <b>Fertig</b> (done) closes them.',
        ],
        'r-bild-hochladen' => [
            'title' => 'Uploading an image with alt text',
            'summary' => 'Drag & drop, pasting with ⌘V and checking the AI suggestion for the alt text.',
            'goal' => 'You upload images to the media library – with an image description (alt text) that helps screen-reader users and search engines.',
            'prerequisites' => ['Permission “upload and edit files”.', 'For the AI suggestion: AI switched on for the website.'],
            'steps' => [
                'Open “Medien”. All images, PDFs and videos of the website live here.',
                'Simply drag an image from your computer into the media library …',
                'Alt text is required: what does the image show? (for screen readers and search engines)',
                '“Alt-Text vorschlagen”: the AI describes the image – this takes a moment.',
                'Check the suggestion! “Hochladen” stays locked until you click “Geprüft ✓” or edit the text.',
                'Second way: copy a screenshot or image and paste it with ⌘V (Ctrl+V).',
                'Done: the images are in the library and can be chosen in any block.',
            ],
            'tips' => ['Purely decorative images: tick <b>dekorativ (ohne Aussage)</b> (decorative) instead of writing alt text.', 'Up to 50 MB per file; images are generated automatically in suitable sizes as WebP/AVIF.'],
            'pitfalls' => ['Alt texts describe the content, not “image of …”. No names of patients or clients without consent.'],
            'manual' => ['Images & files'],
        ],
        'r-videos' => [
            'title' => 'Optimising and trimming videos',
            'summary' => 'Video tools: analysis with a score, optimise for the web, trim, choose a poster – in the background.',
            'goal' => 'You make the videos in the media library load quickly, trim clips and set a suitable preview image.',
            'prerequisites' => ['The Video tools extension on this website and the permission “optimise and trim videos, set posters”.', 'For optimising and trimming: ffmpeg on the server (otherwise only analysis and posters from the browser).'],
            'steps' => [
                'Media › Videos: the video tools check every video and make it fit for the web.',
                'On the right under “Video-Werkzeuge” (video tools): score, codec, resolution, bitrate and recommendations.',
                '“Für Web optimieren …” (optimise for web): choose a preset – e.g. Web 720p – as a new version or replacing the original.',
                'The job runs in the background on the server – you may close the browser.',
                '“Schneiden …” (trim): set start and end (keys I and O), test the range, add the clip.',
                'Lossless (fast) or precise – captions are trimmed to match.',
                '“Poster …”: choose a still frame – video blocks show it before playback.',
                '“Alle Video-Aufträge” (all video jobs): progress, result and log – also cancel and retry.',
            ],
            'tips' => ['Right-clicking a video in the media library offers the same tools.', 'In the sidebar under <b>Prüfen</b> (check): “videos not optimised” and “videos without poster” with a bulk action.'],
            'pitfalls' => ['<b>Original ersetzen</b> (replace original) keeps the ID and all uses but overwrites the file – if in doubt, create a new version first.', 'Lossless trimming starts at the keyframe before the chosen start – choose <b>Präzise</b> (precise) for frame-accurate cuts.'],
            'manual' => ['Media'],
        ],
        'r-termin-anlegen' => [
            'title' => 'Creating a recurring event',
            'summary' => 'Create an entry (weekly series) and change it right on its detail page.',
            'goal' => 'You create a recurring event and later correct it right on its page on the website.',
            'prerequisites' => ['A table “Termine” (events) – or another table with a calendar.', 'Permission “create and edit entries”.'],
            'steps' => [
                'Data › Termine: all events are listed here. “+ Termin” creates a new one.',
                'Choose start and end – date and time.',
                'Repeat: e.g. “wöchentlich” (weekly) – then choose the weekday and when the series ends.',
                '“Speichern” – the event appears in the list, the calendar and on the website.',
                'Open it on the website: while signed in you can change the event right on its detail page.',
                'Switch to “Bearbeiten” (edit) at the top, then click texts with a dashed frame and type.',
                '“Speichern” (save) – published entries are then visible to everyone right away.',
                'Menu “⋯” › “Alle Felder bearbeiten” (edit all fields) opens every field on the right – including date and repetition.',
                'Change something and click “Speichern” at the bottom – or close if everything is fine.',
            ],
            'tips' => ['<b>Ausnahmen (fällt aus am)</b> (exceptions) removes single dates from a series, e.g. on public holidays.', 'The calendar view (Data › Termine › Kalender) creates an event on a day directly with <b>+</b>.'],
            'pitfalls' => ['Entries have no separate draft: saving a published entry changes it immediately. Choose <b>Als Entwurf</b> (as draft) first if you want to work in peace.'],
            'manual' => ['Events and repetitions', 'Your own data'],
        ],
        'r-anfragen' => [
            'title' => 'Reading requests in the inbox',
            'summary' => 'Decrypt encrypted online requests, read them and set their status.',
            'goal' => 'You read incoming online requests (e.g. prescription or callback requests) and mark who takes care of them.',
            'prerequisites' => ['Permission “read online requests”.', 'The secret key (e.g. in your password manager).'],
            'steps' => [
                'New online requests are counted next to “Anfragen” in the menu.',
                'Choose the inbox at the top, e.g. prescription requests. Contents are stored encrypted.',
                'Paste the secret key from your password manager and click “Entschlüsseln” (decrypt).',
                'The details are now readable – only in this view; after reloading they are locked again.',
                '“Drucken” (print) and “Kopieren” (copy) help to transfer it into your management system.',
                'Set the status: “In Bearbeitung” (in progress) or “Als erledigt markieren” (done). “Zuweisen” shows who takes care.',
                'Completed requests are deleted automatically after the configured period.',
            ],
            'tips' => ['For privacy reasons the “new request” email contains no content – you can only read it here.'],
            'pitfalls' => ['Without the key, requests cannot be read – it is never stored on the server. Never send it by email.'],
            'manual' => ['Online requests'],
        ],
        'r-support' => [
            'title' => 'Reporting a problem & knowledge base',
            'summary' => 'Send a report with technical details and look things up yourself in the knowledge base.',
            'goal' => 'You report a problem so that support can reproduce it quickly – or you find the solution yourself.',
            'prerequisites' => ['Permission “report problems” (default for all roles).'],
            'steps' => [
                'Something doesn’t work? Bottom left “Hilfe & Support” › “Problem melden” (report a problem) – on every admin page.',
                'Pick the type (question, bug, wish) and briefly describe what happened.',
                'Matching knowledge-base articles appear on the right – maybe one helps right away.',
                'Technical details (browser, page, version) are attached automatically. Then “Meldung senden” (send).',
                'The support team replies here and by email. “Hilfe & Support” counts new replies.',
                'Look it up yourself: Support › Wissensdatenbank (knowledge base) – with search.',
                'Below every article: “Hilfreich?” (helpful?) – this is how the knowledge base improves.',
            ],
            'tips' => ['Copy a screenshot and paste it into the description with <kbd>⌘</kbd>/<kbd>Ctrl</kbd>+<kbd>V</kbd>.', 'Use <b>Dringend</b> (urgent) only if the website is down or forms do not arrive.'],
            'manual' => ['Help & support'],
        ],
        'r-ki-texte' => [
            'title' => 'KLXM Ai: improving & translating text',
            'summary' => 'Check AI suggestions, apply or discard them – and create translations as drafts.',
            'goal' => 'You have a text improved and an entry translated – and check every suggestion before it is saved.',
            'prerequisites' => ['Permission “use AI features” and AI switched on (Grundeinstellungen › KI).', 'For translations: a second language.'],
            'steps' => [
                'Every text field has “✦ KI”: click into the text, then choose “✦ KI” in the formatting bar.',
                '“Verbessern” (improve), “Kürzen” (shorten), “Einfacher” (simpler) … or a free prompt. Selected text = only that part.',
                'A suggestion, not autopilot: check the preview and “Änderungen” (changes), then “Übernehmen” (apply) or “Verwerfen” (discard).',
                'It goes into the draft – it only goes live with “Veröffentlichen” (publish).',
                'Translate: KLXM Ai › Übersetzen shows what is still missing in other languages (here a website with English).',
                '“Übersetzung anlegen” (create translation) creates a draft in the other language.',
                '“✦ Aus Deutsch übersetzen” (translate from German): pick texts, then “Vorschläge erzeugen” (generate suggestions).',
                'Check every translation and edit if needed – only ticked items are applied.',
                'Save as a draft and have it checked – people publish, not the AI.',
            ],
            'tips' => ['The AI does not invent facts: missing details appear as <code>[bitte ergänzen: …]</code> (please add) – such pages cannot be published.', 'Tone and style are set by the administrators under Grundeinstellungen › KI (notes, glossary).'],
            'pitfalls' => ['Always proofread technical terms, names, numbers and times – especially in translations.', 'Do not copy confidential data (e.g. from requests) into the free prompt.'],
            'manual' => ['KLXM Ai: writing, translating, reviewing'],
        ],
        'a-benutzer-rollen' => [
            'title' => 'Users & roles, requiring 2FA',
            'summary' => 'Compose your own role, create an account and require a second factor (app or passkey) per role.',
            'goal' => 'Everyone gets their own account with exactly the permissions they need – secured with two-factor sign-in.',
            'prerequisites' => ['Permission “users and roles” (default: administrators).'],
            'steps' => [
                'Administration › Benutzer & Rollen (users & roles): everyone gets their own account.',
                'First a suitable role: “+ Neue Rolle” (new role), enter a name and tick the permissions.',
                'Whatever is not ticked stays hidden for the role – e.g. no “Veröffentlichen” (publish).',
                '“Neuen Benutzer anlegen” (new user): name, email, initial password (hand over in person) and role.',
                '“Anmeldung & Sicherheit” (sign-in & security): allowed methods – authenticator app, passkeys, passwordless sign-in.',
                'Choose the second factor per role – e.g. Redaktion (editors): “verlangt (App oder Passkey)” (required).',
                '“Übergangsfrist” (grace period): 0 days = set up at the next sign-in. Then “Speichern” (save).',
                'Those affected set up an app or passkey at their next sign-in. Network accounts always use 2FA.',
            ],
            'tips' => ['Permissions for data tables and requests can be restricted per table (“selected tables only”).', 'Lost your phone? Sign in with a recovery code, or reset 2FA on the command line (<code>user:2fa-reset</code>).'],
            'pitfalls' => ['Do not share accounts – the log attributes changes to people.', 'The “Administration” role always has all permissions and cannot be restricted.'],
            'manual' => ['Signing in & account', 'Roles, permissions & two-factor (technical)'],
        ],
        'a-website-daten' => [
            'title' => 'Website details & multiple languages',
            'summary' => 'Maintain central details with a preview, translations and the website’s languages.',
            'goal' => 'You maintain name, contact and opening hours in one place and manage further languages.',
            'prerequisites' => ['Permission “change website”; for languages “basic settings” and the multilingual feature.'],
            'steps' => [
                'Website data: name, address, phone, opening hours – maintained once, shown everywhere.',
                '“Vorschau” (preview) shows on the right where the value appears on the website.',
                '“Speichern” (save) – these values apply immediately, without publishing.',
                'Second language: “EN English” at the top – translate only the texts; phone & address apply to all.',
                'Which languages exist is set under Grundeinstellungen › Sprachen (languages).',
                'The first active language is the default; every further one gets a prefix like /en/.',
                'Translate pages and entries: in the page list or with “✦ Aus Deutsch übersetzen” (AI).',
            ],
            'tips' => ['<b>Texte mit KI aus Deutsch übersetzen</b> (translate texts from German with AI) fills the translations under “Website” as a suggestion.', 'Empty translation fields show the text of the default language.'],
            'pitfalls' => ['Details under “Website” apply immediately – there is no draft here.'],
            'manual' => ['Website', 'Languages & translation (technical)'],
        ],
        'a-design' => [
            'title' => 'Design: style editor, presets, navigation',
            'summary' => 'Try presets, colours with contrast checks, navigation – with a live preview.',
            'goal' => 'You adjust colours, fonts and navigation – checked for accessibility and without changing the kit.',
            'prerequisites' => ['Permission “design (style editor)” and the design feature.'],
            'steps' => [
                'Administration › Design: colours, fonts and shapes of the kit for this website.',
                'Presets fill the form with a matching set – the preview on the right shows it right away.',
                'Every colour with a contrast check (AA/AAA) – for light and dark mode.',
                'Tabs “Typografie”, “Navigation”, “Kopfbereich: Suche & Aktionen” (header: search & actions) – fonts, menu, search field and button at the top.',
                'Check the preview: pick a page, switch to “Mobil” (mobile) and “Dunkel” (dark).',
                '“Speichern” puts the design online, “Verlauf” (history) restores earlier versions. Here: “Verwerfen” (discard).',
            ],
            'tips' => ['Which pages appear in the menu is controlled in the page list (“Menü” switch) or via sections with an anchor (“show in main navigation”).', '<b>Export</b>/<b>Import</b> transfer a design to another website with the same kit.'],
            'pitfalls' => ['Fix red contrast values before saving – otherwise text is hard to read (WCAG).'],
            'manual' => ['Design: colours, shapes, fonts', 'Changing the menu'],
        ],
        'a-datentabelle' => [
            'title' => 'Creating a data table',
            'summary' => 'Fields, icon picker, conditions, form, search – and then the calendar.',
            'goal' => 'You build your own table (here “courses”) with detail pages, conditional fields, a visitor form and a calendar.',
            'prerequisites' => ['Permission “change tables and fields” and the feature “create tables and fields yourself”.'],
            'steps' => [
                'Data › “+ Neue Tabelle” (new table): your own content such as courses, products or jobs.',
                'Choose an icon: search, e.g. “Schule” (school) – shown in the menu and lists.',
                'Add fields: choose the type below and name it – date, yes/no, link …',
                'Conditions: show “Link zum Raum” only when “Online-Kurs” = yes.',
                'On the right: detail-page address, public form and website search.',
                '“Tabelle anlegen” (create table) – it then appears in the menu on the left, ready to use.',
                'Calendar: in “Felder & Einstellungen” (fields & settings) tick “Als Kalender nutzen” and choose the “Beginn” field.',
                'Now the table has a calendar view, repetitions and an iCal subscription.',
            ],
            'tips' => ['Templates on the data page (news, team, events …) save time.', 'With AI: <b>✦ Felder vorschlagen</b> (suggest fields) or KLXM Ai › table generator.'],
            'pitfalls' => ['The <b>short name</b> cannot be changed later (database, API).', 'Calendar fields can only be chosen after creating the table – new fields are not selectable there before saving.', 'For confidential details (health data), create an encrypted <b>inbox</b> instead of a content table (type of table).'],
            'manual' => ['Your own data', 'Conditions', 'Form for visitors'],
        ],
        'a-quellen' => [
            'title' => 'Connecting external sources',
            'summary' => 'Fetch RSS, JSON, XML or OpenImmo regularly and show it as entries of a data table.',
            'goal' => 'You bring content from an external source into a data table – with field mapping, preview and schedule.',
            'prerequisites' => ['Permission “manage external sources” and the external sources feature (switched on by the network/agency).', 'The address of the source (URL) or a file, e.g. an OpenImmo ZIP from estate-agent software.'],
            'steps' => [
                'Data › Externe Quellen (external sources): RSS feeds, JSON APIs, XML and OpenImmo as entries of a data table.',
                'Visitors never load anything from the source: list, detail page, search and API come from your own table.',
                'Templates to start with: RSS/Atom, OpenImmo, JSON API or XML with XPath.',
                'The example “Immobilien” (real estate) reads an OpenImmo file from estate-agent software.',
                'Source: name, format and address – or upload the file on the right. Credentials are stored encrypted.',
                'Fetching: schedule, cache and what happens to entries missing from the source.',
                'Mapping: every table field gets a path in the source – with a conversion, e.g. number or date.',
                '“Vorschau & Test” (preview & test) shows the first entries as they would arrive in the table – without saving.',
                'On the right: status, “Jetzt abrufen” (fetch now) and the log of recent fetches.',
                'Imported entries are in “Immobilien” – read-only, because the source maintains them.',
            ],
            'tips' => ['The template can create the matching data table with its detail page right away (<b>Tabelle … anlegen</b>).', 'Images from the source end up in the media library – re-encoded and without EXIF (collection “Quelle: …”).'],
            'pitfalls' => ['Do not edit entries from a source by hand – the next fetch overwrites them. Put your own additions in separate fields or tables.', 'Clarify usage rights: content from third-party feeds must not be published automatically.'],
            'manual' => ['External sources', 'External sources (technical)'],
        ],
        'a-untertitel' => [
            'title' => 'Captions & transcripts for videos',
            'summary' => 'Write or upload captions, review and publish them, and turn them into a transcript.',
            'goal' => 'Your videos become accessible: captions in the player and a transcript below the video (WCAG 1.2).',
            'prerequisites' => ['A video in the media library.', 'Permission “upload and edit files”; for AI transcription, AI switched on (speech → text).'],
            'steps' => [
                'Accessibility: videos need captions, audio needs a transcript. Media › Videos.',
                'On the right under “Untertitel & Transkript”: upload (.vtt/.srt), write new ones or transcribe with AI.',
                'Play the video and at the right moment choose “+ Untertitel an aktueller Zeit” – type the text.',
                'Easy to read: at most 2 lines of 42 characters. Adjust times with ⇤ ⇥.',
                'Only “Geprüft – veröffentlichen” (checked – publish) shows the captions on the website. Always check AI drafts!',
                'Published: the video leaves “Videos ohne Untertitel” (videos without captions). Under “Videos” the track shows as “veröffentlicht” (published).',
                'Transcript: “+ Transkript” – or take the text over from the captions.',
                'On the website the captions show in the player, plus “Transkript anzeigen” (show transcript) below the video.',
                '“Mit KI transkribieren” (e.g. whisper.cpp on the server) creates a draft for review.',
            ],
            'tips' => ['Keyboard in the editor: <kbd>Alt</kbd>+<kbd>Enter</kbd> new caption, <kbd>Alt</kbd>+<kbd>P</kbd> play/pause.', 'Sounds in square brackets, e.g. [music]; speaker changes with “–”.'],
            'pitfalls' => ['Automatic transcripts contain errors in names, technical terms and numbers – watch them in full and correct them.'],
            'manual' => ['Captions & transcripts', 'Media, pools & captions (technical)'],
        ],
        'a-api-freigabe' => [
            'title' => 'API tokens & “Submitted” (approval)',
            'summary' => 'Create tokens for AI assistants (MCP) and the REST API – changes only after approval.',
            'goal' => 'An AI assistant may make suggestions, but a person decides: you review every change under “Submitted”.',
            'prerequisites' => ['Permissions “API & MCP” and “review submitted changes”.'],
            'steps' => [
                'API & MCP: access for automations and AI assistants such as Claude.',
                '“Änderungen: Zur Freigabe” (for approval) – a person checks every change before it goes live.',
                'The token is shown only once – copy it to your password manager right away (blurred here).',
                'When the assistant now changes something, it lands in KLXM Ai › Eingereicht (submitted).',
                'Check the origin (token, channel) and before/after – then “Übernehmen” (apply) or “Ablehnen” (reject).',
                'Every submission stays logged. Tokens can be switched or revoked at any time.',
            ],
            'tips' => ['“Read only” is enough for reports and checks.', 'Optional: “valid until” limits a token in time.'],
            'pitfalls' => ['Never put tokens in emails, tickets or code repositories – treat them like passwords.', 'Existing tokens stay on “apply directly” until you switch them.'],
            'manual' => ['AI assistants via MCP & approval', 'Review queue “Submitted” (technical)', 'MCP server (technical)'],
        ],
        'a-seo' => [
            'title' => 'SEO overview',
            'summary' => 'Find missing or duplicate descriptions and apply reviewed AI suggestions.',
            'goal' => 'All pages and entries have a suitable description for search engines.',
            'prerequisites' => ['Permissions “use AI features” and “create pages, … page settings”.'],
            'steps' => [
                'KLXM Ai › SEO overview: where are search-engine descriptions missing – or duplicated?',
                'Select rows – here only “Datenschutz” (privacy) – and click “Vorschläge für Auswahl erzeugen” (generate suggestions).',
                'Read the suggestion and edit if needed (counter: ideally up to 160 characters). Only ticked rows are applied.',
                'The description is now in the page settings – where the “SEO-Check” also checks headings and images.',
            ],
            'tips' => ['Good descriptions name the offer, the place and the benefit in one sentence.'],
            'pitfalls' => ['Duplicate descriptions (“same description as …”) weaken both pages in search results.'],
            'manual' => ['KLXM Ai: SEO'],
        ],
        'a-consent' => [
            'title' => 'Cookie consent with the Consent Kit',
            'summary' => 'Cookie-free out of the box – and when services are needed after all: consent with templates, design and a log.',
            'goal' => 'You embed services that need consent (e.g. statistics, videos) so that they only load after approval.',
            'prerequisites' => ['The Consent Kit extension on this website (agency/network) and the permission for cookie consent.'],
            'steps' => [
                'Cookie consent (Consent Kit extension): without services that need consent there is no notice – cookie-free out of the box.',
                'Services: e.g. statistics (Matomo) or external media (YouTube) – switchable per domain.',
                '“Dienst hinzufügen” (add service): templates with provider, purpose, cookies and privacy link.',
                'Design: colours come from the website design. Preview as box, bar or dialog – light and dark.',
                'On the website: the notice appears until visitors decide. “Alle ablehnen” (reject all) is as easy as “Alle akzeptieren” (accept all).',
                '“Einstellungen” (settings) shows every service with purpose and storage period – selectable one by one.',
                'Rejected content shows a placeholder: the video only loads from the provider after a click.',
                'Every decision is logged anonymously; visitors can change it at any time via “Cookie-Einstellungen” (cookie settings).',
            ],
            'tips' => ['The privacy policy and legal notice are linked in the notice – create both pages first.', 'Landing pages with their own domain have their own column: switch services on or off per domain.'],
            'pitfalls' => ['Always add new services (e.g. a map or video provider) here first – otherwise they load without consent.', 'If a service changes significantly, the notice asks again – this is intended.'],
            'manual' => ['Cookie consent', 'Cookie consent (technical)'],
        ],
        'n-netzwerk' => [
            'title' => 'Network dashboard & opening a website',
            'summary' => 'All websites at a glance, search, filter and open them via SSO.',
            'goal' => 'You keep track of all websites of the installation and switch into a website without signing in again.',
            'prerequisites' => ['A network account (role “network administration”) with two-factor sign-in set up, signed in on the main website.'],
            'steps' => [
                'Network › all websites: status, requests, approvals, storage and backups at a glance.',
                'Search and filter: “Mit Hinweisen” (with warnings), “Wartung” (maintenance), “Nicht live” (not live).',
                '“Öffnen” (open) signs you in to that website’s admin with a one-time token (SSO) – no second password.',
                'There you work with agency rights; “Website wechseln” (switch website) in the sidebar leads to the next one.',
                'Below: network accounts (always with two-factor sign-in), new website, shared resources, log.',
                'Disabling a network account ends its sessions on all websites immediately.',
            ],
            'tips' => ['The figures are cached – <b>Aktualisieren</b> (refresh) fetches the current state.'],
            'pitfalls' => ['The SSO token is valid for 60 seconds, can be used once and is bound to the browser, the account and the target website.'],
            'manual' => ['Network administration (technical)', 'Multiple websites (technical)'],
        ],
        'n-website-anlegen' => [
            'title' => 'Creating a new website',
            'summary' => 'Short name, domains and kit – in the interface or with site:create.',
            'goal' => 'You create another website with its own database, media, users and keys.',
            'prerequisites' => ['A network account on the main website.', 'The domain points to the same folder in your hosting (document root <code>httpdocs/public</code>).'],
            'steps' => [
                'Network › “Neue Website” (new website): short name, domains and kit – like “site:create” on the command line.',
                'Created: its own configuration with its own keys. The next steps are shown in the box.',
                'Point the domain to the same folder (httpdocs/public) in your hosting – the first request creates everything.',
                'Then “Öffnen” (open) – or create the first local account via /admin/setup with the setup token (blurred here).',
            ],
            'tips' => ['Feature set, kit options and AI are then in <code>config/sites/{shortname}.php</code>.'],
            'pitfalls' => ['<code>config/sites/*.php</code> contains keys – do not put it under version control; on deploy it lives in the <code>shared/</code> folder.'],
            'manual' => ['Multiple websites (technical)', 'Command line'],
        ],
        'n-funktionen' => [
            'title' => 'Packages & features per project',
            'summary' => 'Presets full / content / minimal, individual features, blocks and integrators.',
            'goal' => 'Every website gets exactly the feature set the project calls for – controlled by the agency, not the client.',
            'prerequisites' => ['Access to the installation’s configuration (SFTP/SSH or deploy).'],
            'steps' => [
                'Every website has a feature set: preset “full”, “content” or “minimal” plus individual switches.',
                'The agency sets it in config/sites/{website}.php – customers cannot change it.',
                'In every website, Grundeinstellungen › Systeminfo shows what is switched on or off there.',
                'Disabled features lock menus, permissions, API and MCP – even for the website’s own admins.',
                'All switches and examples: technical documentation › features & extensions.',
            ],
            'tips' => ['Network accounts and integrators always see everything – use a normal account to test the client’s view.'],
            'pitfalls' => ['Locked block types stay editable in existing pages but cannot be inserted again.'],
            'manual' => ['Features & extensions (technical)'],
        ],
        'n-geteilt' => [
            'title' => 'Shared media & shared data',
            'summary' => 'Media pools (e.g. brand images) and an association’s tables for its member clubs.',
            'goal' => 'Several websites use common images and data – maintained in one place.',
            'prerequisites' => ['A network account or administration of the main website.'],
            'steps' => [
                'Grundeinstellungen › Geteilte Medien (shared media): central libraries (e.g. logos, brand images) for several websites.',
                '“Neuen Pool anlegen” (new pool): name, short name and the websites allowed to use it.',
                'Per pool: “Genutzt von” (used by) and “Pflegen dürfen” (may maintain) – everyone else only uses the files.',
                'In the media library: right-click a file › “In … verschieben (geteilt)” (move to shared) – existing uses are kept.',
                'Switch between “Diese Website” (this website) and the pool at the top – the file now lives there for every website of the pool.',
                'Shared data: one website (e.g. the association) owns the table, members (clubs) see and add entries.',
                'At the club the association’s entries appear in the same table – read-only, its own stay editable.',
                'Backup commands: pool:backup and shared:backup (see technical documentation › shared data tables).',
            ],
            'tips' => ['Sharing existing files: right-click in the media library › “In … verschieben (geteilt)” (move to shared) – existing uses stay valid.'],
            'pitfalls' => ['Changes in pools and shared tables take effect immediately on all participating websites.', '<code>sync-content.sh</code> does not transfer pools and shared tables.'],
            'manual' => ['Shared data tables (technical)', 'Media & pools (technical)', 'Shared tables (manual)'],
        ],
        'n-ki' => [
            'title' => 'Setting up AI (Ollama, whisper.cpp, privacy)',
            'summary' => 'Capabilities per website, the installation’s provider, testing the connection, privacy.',
            'goal' => 'The AI features run – preferably on your own server – and every website only uses what is enabled.',
            'prerequisites' => ['Feature “ai” in the feature set.', 'An AI provider: Ollama (own server), whisper.cpp for captions or an external service with a data processing agreement.'],
            'steps' => [
                'Grundeinstellungen › KI: switch on per website and choose capabilities – text, images, search, captions.',
                'A daily limit, notes on audience and style, and a glossary steer the assistant.',
                '“Fähigkeiten” (capabilities): provider and model are set by the agency in the configuration – e.g. Ollama and whisper.cpp.',
                '“Bleibt auf dem Server” (stays on the server): with local models content never leaves your premises. External services are marked.',
                'Configuration and commands (ai:test, search:index) are in the technical documentation › KLXM Ai.',
            ],
            'tips' => ['The permissions “use AI features” and “review submitted changes” are granted per role.'],
            'pitfalls' => ['Name external providers (OpenAI, Mistral …) in the privacy policy and sign a data processing agreement.', 'API keys belong in the configuration only – never in kits or the repository.'],
            'manual' => ['KLXM Ai: AI service & features (technical)', 'Website search (technical)'],
        ],
        'n-staging-deploy' => [
            'title' => 'Staging & deploy',
            'summary' => 'What the interface shows – and the commands for releases, rollback and content.',
            'goal' => 'Code reaches the server tested and with a backup; staging gets a copy of the live content when needed.',
            'prerequisites' => ['SSH access or CI (GitHub Actions) and target files <code>deploy/targets/{target}.env</code>.'],
            'steps' => [
                'Staging is a separate installation with a copy of the live content. The network shows what is not live.',
                'Before interventions: “Wartung ▾” – backup now, maintenance mode, clear page cache.',
                'Health check for deploys: /health answers without secrets (ok, version, environment).',
                'Deploy on the command line: deploy/deploy.sh staging or production – with backup, migrate, health and rollback.',
            ],
            'tips' => ['Staging (<code>\'environment\' => \'staging\'</code>) keeps search engines out, shows a notice bar and redirects emails.'],
            'pitfalls' => ['Schema changes run against the live database before switching – they must be additive.'],
            'manual' => ['Staging & deploy (technical)', 'Operations: cron jobs, backups, updates'],
        ],
        'n-theme' => [
            'title' => 'Your own kit: design tokens & export',
            'summary' => 'Design tokens in the style editor, export – and when your own kit makes sense.',
            'goal' => 'You know when the style editor is enough and when your own kit makes sense – and how to create it.',
            'prerequisites' => ['For your own kits: Node/pnpm for the build (local only), access to the <code>kits/</code> folder.'],
            'steps' => [
                'Every value in the style editor is a design token (CSS variable) from the kit – theme.php → “design”.',
                '“Export” saves the values as a file – e.g. to take them into your own kit or another website.',
                'Own project = own kit: “kit:create” copies the start kit – the core stays updatable.',
                'Structure, tokens, blocks and presets are described in the technical documentation › kits & design.',
            ],
            'tips' => ['Tutorials for your kit: <code>kits/{name}/docs/tutorials.php</code> extends the tutorials page; record your own videos with <code>node tools/tutorials/record.mjs</code>.', 'Step by step with the start kit: tutorial “Your own kit with the start kit”.'],
            'pitfalls' => ['Never use kit names in the core – project-specific things belong in the kit.'],
            'manual' => ['Kits & design (technical)', 'Build & development (technical)'],
        ],
        'n-kit-starter' => [
            'title' => 'Your own kit with the start kit',
            'summary' => 'kit:create copies the start kit “starter” – then adjust, build, test.',
            'goal' => 'You create your own kit for a project, based on the smallest complete kit, and know which steps follow.',
            'prerequisites' => ['Access to the command line and the <code>kits/</code> folder (locally or on the server).', 'Node/pnpm for the build (local only).'],
            'steps' => [
                'Your own kit for a project: “kit:create” copies the start kit and renames everything.',
                'The output lists the new folders and the next steps: adjust, build, test, check.',
                'The start kit is the smallest complete kit: six example blocks, light and dark, one accent colour.',
                'You set colours, fonts and navigation under Design as usual – the values are design tokens of the kit.',
                'theme.php is divided into sections § 1–11. The guide: technical documentation › kits & design.',
            ],
            'tips' => ['<code>kit:create name --from=basis</code> uses another kit as the template.', 'Check the home-page budget: CSS &lt; 30 KB, JS &lt; 8 KB (start kit ≈ 15.7 KB / 0.4 KB).'],
            'pitfalls' => ['Rebuild after changes to <code>assets/</code> – <code>public/kits/{name}/</code> only contains the built files.', 'Do not change the start kit itself – it is the template for <code>kit:create</code> and is replaced by updates.'],
            'manual' => ['Developing your own kit (technical)', 'Kits & design (technical)', 'Command line'],
        ],
    ],
];
