<?php
/**
 * Tutorials für „Handbuch & Hilfe › Tutorials“ (HelpController::tutorials/tutorial, Ansichten help/tutorials.php und help/tutorial.php).
 *
 * Aufbau:
 *   'tracks'    => [schlüssel => ['title', 'icon', 'lead', 'for']]                       Zielgruppen in dieser Reihenfolge
 *   'tutorials' => [kurzname => [
 *       'track', 'title', 'icon' (Core\Icons), 'level' (Einstieg | Grundlagen | Fortgeschritten), 'summary',
 *       'goal', 'prerequisites' [...], 'steps' [...] (HTML erlaubt, UI-Beschriftungen in <b>), 'tips' [...], 'pitfalls' [...],
 *       'commands' (optional, Text für einen Codeblock), 'manual' [[Bezeichnung, Pfad], …],
 *       'video' (Standard = Kurzname; false = ohne Video), 'mobile' (Kurzname der Smartphone-Aufnahme),
 *       'mobileText' (optional, HTML: Text neben dem Smartphone-Video, sonst der allgemeine Hinweis), 'feature' (Core\Features)
 *   ]]
 * Englisch: app/Admin/tutorials.en.php (gleiche Kurznamen). Die Schritte sind zugleich das Transkript der Videos (Untertitel Deutsch/Englisch = Schritte).
 * Videos: NICHT im CMS – sie liegen auf der Produkt-Website (config 'docs_url', Standard https://studio.klxm.de/tutorials/{kurzname}),
 * aufgenommen mit tools/tutorials/record.mjs (gleiche Kurznamen, Ausgabe TUT_OUT) und von dort mit php bin/console tutorials:export beschrieben.
 *
 * Agenturen ergänzen oder ersetzen Tutorials im Theme: kits/{name}/docs/tutorials.php gibt dasselbe Format zurück
 * (gleicher Kurzname = ersetzen, false = entfernen; eigene Videos mit 'video' => '/kits/{name}/tutorials/datei' ohne Endung).
 */
return [
    'tracks' => [
        'redaktion' => [
            'title' => 'Redaktion',
            'icon' => 'pencil-simple',
            'lead' => 'Texte, Bilder, Termine und Anfragen pflegen – die tägliche Arbeit in wenigen Minuten gezeigt.',
            'for' => 'Für alle, die Inhalte pflegen',
        ],
        'admin' => [
            'title' => 'Administration einer Website',
            'icon' => 'gear-six',
            'lead' => 'Benutzer und Rollen, zentrale Angaben, Design, eigene Datentabellen, Barrierefreiheit von Videos, Schnittstellen und Suchmaschinen.',
            'for' => 'Für Admins einer Website',
        ],
        'agentur' => [
            'title' => 'Agenturen & Netzwerk',
            'icon' => 'buildings',
            'lead' => 'Mehrere Websites betreiben: Netzwerk-Übersicht, neue Websites, Funktionsumfang, geteilte Inhalte, KI, Deploy und Kits.',
            'for' => 'Für Agenturen und Netzwerk-Administration',
        ],
    ],

    'tutorials' => [

        /* ================================================================ Redaktion */

        'r-ueberblick' => [
            'track' => 'redaktion', 'title' => 'Anmelden & Überblick', 'icon' => 'squares-four', 'level' => 'Einstieg',
            'summary' => 'Anmelden, Seitenleiste mit Bereichsfarben, Favoriten ☆, Suche mit ⌘K und Hilfe & Support.',
            'goal' => 'Sie melden sich an, finden sich in der Übersicht zurecht, merken sich oft gebrauchte Stellen als Favorit und finden alles über die Suche.',
            'prerequisites' => ['Ein eigenes Konto (E-Mail-Adresse und Passwort) – bekommen Sie von der Administration.'],
            'steps' => [
                'Die Verwaltung öffnen: Adresse der Website + <code>/admin</code>.',
                '<b>E-Mail-Adresse</b> und <b>Passwort</b> eingeben, dann <b>Anmelden</b>.',
                'Die <b>Übersicht</b>: Kennzahlen und <b>Was ist zu tun?</b> – was heute ansteht.',
                'Oben links unter dem Namen: Lupe = <b>Suche</b>, Sprechblase = <b>Assistent</b>, <b>↗</b> = <b>Website ansehen</b>.',
                'Links steht das Menü – z. B. <b>Daten</b> für Termine, Team oder Beiträge.',
                'Jeder Bereich hat eine eigene Farbe. <b>Zurück zu …</b> oben führt ins Hauptmenü.',
                'Oft gebraucht? Mit dem Stern <b>☆</b> neben der Überschrift als Favorit merken.',
                'Der Favorit steht jetzt oben in der Seitenleiste unter <b>Favoriten</b> – nur für Ihr Konto.',
                'Alles finden: die Lupe oder <kbd>⌘</kbd> <kbd>K</kbd> (Windows: <kbd>Strg</kbd> <kbd>K</kbd>) öffnet die Suche – überall in der Verwaltung.',
                'Treffer: Seiten, Einträge, Medien, Einstellungen – oder den Assistenten fragen. Pfeiltasten wählen, <kbd>↵</kbd> öffnet.',
                'Unten links <b>Hilfe &amp; Support</b>: Handbuch, Tutorials, Assistent und <b>Problem melden</b>.',
            ],
            'tips' => ['<b>Mit Passkey anmelden</b> (unter dem Formular): ohne Passwort per Fingerabdruck, Gesicht oder Geräte-PIN – einrichten im eigenen Konto unter <b>Passkeys</b>, sofern die Website Passkeys erlaubt.', 'Favoriten benennen Sie mit <b>Bearbeiten</b> in der Seitenleiste um oder sortieren sie (ziehen oder <kbd>Alt</kbd>+<kbd>↑</kbd>/<kbd>↓</kbd>).', 'Auf dem Smartphone öffnet das Symbol ☰ oben links das Menü, die Lupe oben rechts die Suche.'],
            'pitfalls' => ['Nach 8 falschen Passworteingaben ist die Anmeldung 15 Minuten gesperrt.', 'Fehlt ein Menüpunkt, hat Ihre Rolle das Recht dafür nicht – das ist so gewollt.'],
            'manual' => [['Anmelden & Konto', '/admin/hilfe#anmelden'], ['Überblick', '/admin/hilfe#start']],
            'mobile' => 'r-ueberblick-mobil',
        ],

        'r-uebersicht' => [
            'track' => 'redaktion', 'title' => 'Die neue Übersicht', 'icon' => 'gauge', 'level' => 'Einstieg',
            'summary' => 'Kennzahlen, „Was ist zu tun?“, Statistik ohne Tracking, Zuletzt bearbeitet – und die Übersicht anpassen.',
            'goal' => 'Sie sehen nach der Anmeldung auf einen Blick, was ansteht, und richten sich die Übersicht so ein, wie Sie arbeiten.',
            'prerequisites' => ['Ein Konto für die Verwaltung. Welche Karten erscheinen, hängt von den Rechten Ihrer Rolle ab.'],
            'steps' => [
                'Nach der Anmeldung: die <b>Übersicht</b>. Oben Begrüßung, Datum und Schnellaktionen für Ihre Rolle.',
                '<b>Kennzahlen</b> als Rundinstrumente: Seiten online, Einträge, Medien, Eingereicht – mit Trend über 30 Tage.',
                '<b>Was ist zu tun?</b> – Aufgaben nach Dringlichkeit, jede mit Erklärung und direktem Link.',
                'Statistik ohne Besucher-Tracking: <b>Aktivität</b> der letzten 30 Tage – auch als Tabelle.',
                '<b>Zuletzt bearbeitet</b>: weiterarbeiten, wo Sie oder das Team aufgehört haben.',
                '<b>Hilfe &amp; Einstieg</b>: KLXM AI fragen, Tutorials für Ihre Rolle und was neu ist.',
                '<b>Übersicht anpassen</b>: Karten verschieben, ausblenden oder zuklappen – je Konto.',
                '<b>Standard wiederherstellen</b> bringt die ursprüngliche Anordnung zurück. <b>Fertig</b> schließt.',
            ],
            'tips' => ['Karten lassen sich auch ohne Maus verschieben: im Anpassen-Modus mit den Pfeil-Knöpfen.', 'Die Zahlen stammen nur aus dieser Website – es gibt kein Besucher-Tracking und keine Cookies dafür.'],
            'pitfalls' => ['Fehlt eine Karte, hat Ihre Rolle das Recht dafür nicht – oder sie ist ausgeblendet (<b>Übersicht anpassen</b> zeigt ausgeblendete Karten wieder).'],
            'manual' => [['Die Übersicht', '/admin/hilfe#uebersicht']],
        ],

        'r-seite-bearbeiten' => [
            'track' => 'redaktion', 'title' => 'Seite bearbeiten & veröffentlichen', 'icon' => 'pencil-simple', 'level' => 'Einstieg',
            'summary' => 'Direkt auf der Website ändern: Blöcke, Formatleiste, Entwurf, Vorschau, Veröffentlichen.',
            'goal' => 'Sie ändern Texte einer Seite direkt auf der Website, sichern einen Entwurf, prüfen die Vorschau und stellen die Änderung online.',
            'prerequisites' => ['Recht „Seiten bearbeiten“; zum Veröffentlichen zusätzlich „Seiten veröffentlichen“.'],
            'steps' => [
                'Seite auf der Website öffnen. Die dunkle Leiste oben sehen nur angemeldete Personen.',
                'Oben in der Mitte von <b>Ansehen</b> auf <b>Bearbeiten</b> umschalten.',
                'Im Bearbeitungsmodus hat jeder Block einen Rahmen, seinen Namen und <b>Bearbeiten</b>.',
                'Kurze Texte mit gestricheltem Rahmen direkt anklicken und überschreiben.',
                'Fließtext: Wort markieren – die Formatierungsleiste erscheint – z. B. <b>Fett</b> (B).',
                '<b>Bearbeiten</b> am Block öffnet rechts alle Felder – Links, Bilder, Varianten.',
                'Die Vorschau links aktualisiert sich sofort. <kbd>Esc</kbd> schließt die Seitenleiste.',
                '<b>Speichern</b> (<kbd>⌘</kbd>/<kbd>Strg</kbd>+<kbd>S</kbd>) sichert einen Entwurf – Besucher sehen noch den alten Stand.',
                'Menü <b>⋯</b> › <b>Vorschau</b> zeigt die Seite ohne Bearbeitungsrahmen.',
                'Zurück auf <b>Bearbeiten</b> – dann <b>Veröffentlichen</b> und bestätigen: Jetzt ist die Änderung online.',
                'Der Pfeil neben <b>Veröffentlichen</b> bietet <b>Entwurf verwerfen …</b>; frühere Stände unter <b>Seiteneinstellungen › Versionen</b>.',
            ],
            'tips' => ['<b>+</b> links am Block fügt einen neuen Block ein, ↑ ↓ verschieben ihn.', 'Menü <b>⋯</b> › <b>Kompakt</b> klappt alle Blöcke zu schmalen Zeilen zusammen – ideal zum Umsortieren.'],
            'pitfalls' => ['Gespeichert ist nicht veröffentlicht: Besucher sehen Änderungen erst nach <b>Veröffentlichen</b>.', 'Zentral gepflegte Angaben (z. B. Telefon) ändern Sie unter „Website“, nicht im Text.'],
            'manual' => [['Inhalte bearbeiten', '/admin/hilfe#bearbeiten'], ['Alle Blöcke', '/admin/hilfe#bloecke']],
            'mobile' => 'r-seite-bearbeiten-mobil',
            'mobileText' => 'Unter 768 px stehen <b>Abbrechen</b>, <b>Speichern</b> und <b>Veröffentlichen</b> in einer Leiste unten; das Menü der Website ist im Bearbeitungsmodus ausgeblendet. Text im Block antippen zeigt seine Leiste mit <b>Bearbeiten</b> – die Felder öffnen sich über der unteren Leiste, <b>Fertig</b> schließt sie.',
        ],

        'r-bild-hochladen' => [
            'track' => 'redaktion', 'title' => 'Bild hochladen mit Alt-Text', 'icon' => 'image', 'level' => 'Einstieg', 'feature' => 'media',
            'summary' => 'Drag & Drop, Einfügen mit ⌘V und den KI-Vorschlag für den Alt-Text prüfen.',
            'goal' => 'Sie laden Bilder in die Mediathek – mit einer Bildbeschreibung (Alt-Text), die Menschen mit Screenreader und Suchmaschinen hilft.',
            'prerequisites' => ['Recht „Dateien hochladen und bearbeiten“.', 'Für den KI-Vorschlag: KI auf der Website eingeschaltet.'],
            'steps' => [
                '<b>Medien</b> öffnen. Hier liegen alle Bilder, PDFs und Videos der Website.',
                'Bild vom Computer einfach in die Mediathek ziehen …',
                'Alt-Text ist Pflicht: Was ist auf dem Bild zu sehen? (für Screenreader und Suchmaschinen)',
                '<b>✦ Alt-Text vorschlagen</b>: Die KI beschreibt das Bild – das dauert einen Moment.',
                'Vorschlag prüfen! <b>Hochladen</b> bleibt gesperrt, bis Sie <b>Geprüft ✓</b> klicken oder den Text ändern.',
                'Zweiter Weg: Bildschirmfoto oder Bild kopieren und mit <kbd>⌘</kbd>/<kbd>Strg</kbd>+<kbd>V</kbd> einfügen – Alt-Text eintippen, <b>Hochladen</b>.',
                'Fertig: Die Bilder stehen in der Mediathek und lassen sich in jedem Block auswählen.',
            ],
            'tips' => ['Rein dekorative Bilder: <b>dekorativ (ohne Aussage)</b> ankreuzen statt Alt-Text.', 'Bis 50 MB je Datei; Bilder werden automatisch in passenden Größen als WebP/AVIF erzeugt.'],
            'pitfalls' => ['Alt-Texte beschreiben den Inhalt, nicht „Bild von …“. Personen nur mit ihrer Einwilligung namentlich nennen.'],
            'manual' => [['Bilder & Dateien', '/admin/hilfe#medien']],
        ],

        'r-videos' => [
            'track' => 'redaktion', 'title' => 'Videos optimieren und schneiden', 'icon' => 'video-camera', 'level' => 'Grundlagen', 'feature' => 'video.tools',
            'summary' => 'Video-Werkzeuge: Analyse mit Punktzahl, fürs Web optimieren, schneiden, Poster wählen – im Hintergrund.',
            'goal' => 'Sie machen Videos der Mediathek schnell ladbar, schneiden Ausschnitte und setzen ein passendes Vorschaubild.',
            'prerequisites' => ['Erweiterung Video-Werkzeuge auf dieser Website und das Recht „Videos optimieren, schneiden und Poster setzen“.', 'Für Optimieren und Schneiden: ffmpeg auf dem Server (sonst nur Analyse und Poster aus dem Browser).'],
            'steps' => [
                '<b>Medien › Videos</b>: Die Video-Werkzeuge prüfen jedes Video und machen es fit fürs Web.',
                'Rechts unter <b>Video-Werkzeuge</b>: Punktzahl, Codec, Auflösung, Bitrate und Empfehlungen.',
                '<b>Für Web optimieren …</b>: Preset wählen – z. B. <b>Web 720p</b> – als neue Version oder anstelle des Originals.',
                'Der Auftrag läuft im Hintergrund auf dem Server – der Browser darf geschlossen werden.',
                '<b>Schneiden …</b>: Anfang und Ende setzen (Tasten <kbd>I</kbd> und <kbd>O</kbd>), Bereich testen, Ausschnitt hinzufügen.',
                '<b>Verlustfrei (schnell)</b> oder <b>Präzise</b> – Untertitel werden passend mitgeschnitten.',
                '<b>Poster …</b>: ein Standbild wählen – Video-Blöcke zeigen es vor dem Abspielen.',
                '<b>Alle Video-Aufträge</b>: Fortschritt, Ergebnis und Protokoll – auch Abbrechen und Wiederholen.',
            ],
            'tips' => ['Rechtsklick auf ein Video in der Mediathek bietet dieselben Werkzeuge.', 'In der Seitenleiste unter <b>Prüfen</b>: „Videos nicht optimiert“ und „Videos ohne Poster“ mit Sammelaktion.'],
            'pitfalls' => ['<b>Original ersetzen</b> behält ID und Verwendungen, überschreibt aber die Datei – im Zweifel erst als neue Version anlegen.', 'Verlustfreies Schneiden beginnt am Keyframe vor dem gewählten Anfang – für bildgenaue Schnitte <b>Präzise</b> wählen.'],
            'manual' => [['Medien', '/admin/hilfe#medien']],
        ],

        'r-termin-anlegen' => [
            'track' => 'redaktion', 'title' => 'Termin mit Wiederholung anlegen', 'icon' => 'calendar-plus', 'level' => 'Grundlagen', 'feature' => 'calendar',
            'summary' => 'Eintrag anlegen (Serie wöchentlich) und direkt auf der Detailseite ändern.',
            'goal' => 'Sie legen einen wiederkehrenden Termin an und korrigieren ihn später direkt auf seiner Seite der Website.',
            'prerequisites' => ['Eine Tabelle „Termine“ (oder eine andere Tabelle mit Kalender).', 'Recht „Einträge anlegen und bearbeiten“.'],
            'steps' => [
                '<b>Daten › Termine</b>: Hier stehen alle Termine. <b>+ Termin</b> legt einen neuen an.',
                '<b>Titel</b> eintragen, <b>Beginn</b> und <b>Ende</b> wählen – Datum und Uhrzeit.',
                '<b>Wiederholen</b>: z. B. <b>wöchentlich</b> – dann Wochentag und Ende der Serie festlegen (<b>nach 8 Terminen</b>).',
                '<b>Ort</b> ergänzen, dann <b>Speichern</b> – der Termin erscheint in Liste, Kalender und auf der Website.',
                '<b>Ansehen ↗</b> öffnet die Detailseite. Angemeldet lässt sie sich direkt ändern.',
                'Oben auf <b>Bearbeiten</b> umschalten, dann Texte mit gestricheltem Rahmen anklicken und tippen.',
                '<b>Speichern</b> – veröffentlichte Einträge sind danach sofort für alle sichtbar.',
                'Menü <b>⋯</b> › <b>Alle Felder bearbeiten</b> öffnet rechts alle Felder – auch Datum und Wiederholung.',
            ],
            'tips' => ['<b>Ausnahmen (fällt aus am)</b> streicht einzelne Termine einer Serie, z. B. an Feiertagen.', 'Die Kalenderansicht (Daten › Termine › Kalender) legt mit <b>+</b> an einem Tag direkt einen Termin an.'],
            'pitfalls' => ['Einträge haben keinen getrennten Entwurf: Wer einen veröffentlichten Eintrag speichert, ändert ihn sofort. Vorher <b>Als Entwurf</b> wählen, wenn Sie in Ruhe arbeiten wollen.'],
            'manual' => [['Termine und Wiederholungen', '/admin/hilfe#termine'], ['Eigene Daten', '/admin/hilfe#daten']],
        ],

        'r-anfragen' => [
            'track' => 'redaktion', 'title' => 'Anfragen im Posteingang lesen', 'icon' => 'tray', 'level' => 'Grundlagen', 'feature' => 'requests',
            'summary' => 'Verschlüsselte Online-Anfragen entschlüsseln, lesen und den Status setzen.',
            'goal' => 'Sie lesen eingegangene Online-Anfragen (z. B. Rezept- oder Rückrufwünsche) und markieren, wer sich kümmert.',
            'prerequisites' => ['Recht „Online-Anfragen lesen“.', 'Den geheimen Schlüssel (z. B. im Passwortmanager).'],
            'steps' => [
                'Neue Online-Anfragen zeigt die Zahl neben <b>Anfragen</b> im Menü.',
                'Oben den Eingang wählen, z. B. <b>Rezeptanfragen</b>. Die Inhalte sind verschlüsselt gespeichert.',
                'Geheimen Schlüssel aus dem Passwortmanager einfügen und <b>Entschlüsseln</b>.',
                'Jetzt sind die Angaben lesbar – nur in dieser Ansicht, nach dem Neuladen wieder verschlossen.',
                '<b>Drucken</b> und <b>Kopieren</b> helfen beim Übertragen in Ihr Verwaltungssystem.',
                'Status setzen: <b>In Bearbeitung</b> oder <b>Als erledigt markieren</b>. <b>Zuweisen</b> zeigt, wer sich kümmert.',
                'Erledigte Anfragen löscht das System nach der eingestellten Frist automatisch.',
            ],
            'tips' => ['Die E-Mail „Neue Anfrage“ enthält aus Datenschutzgründen keine Inhalte – lesen geht nur hier.'],
            'pitfalls' => ['Ohne Schlüssel sind Anfragen nicht lesbar – er wird nirgends auf dem Server gespeichert. Nie per E-Mail verschicken.'],
            'manual' => [['Online-Anfragen', '/admin/hilfe#anfragen']],
            'mobile' => 'r-anfragen-mobil',
        ],

        'r-support' => [
            'track' => 'redaktion', 'title' => 'Problem melden & Wissensdatenbank', 'icon' => 'lifebuoy', 'level' => 'Einstieg', 'feature' => 'support',
            'summary' => 'Eine Meldung mit technischen Angaben schicken und selbst in der Wissensdatenbank nachschlagen.',
            'goal' => 'Sie melden ein Problem so, dass der Support es schnell nachvollziehen kann – oder finden die Lösung selbst.',
            'prerequisites' => ['Recht „Probleme melden“ (Standard für alle Rollen).'],
            'steps' => [
                'Etwas klappt nicht? Unten links <b>Hilfe &amp; Support › Problem melden</b> – auf jeder Seite der Verwaltung.',
                'Art wählen (<b>Frage</b>, <b>Fehler</b>, <b>Wunsch</b>) und kurz beschreiben, was passiert ist.',
                'Rechts erscheinen schon passende Artikel aus der Wissensdatenbank – vielleicht hilft einer sofort.',
                'Technische Angaben (Browser, Seite, Version) gehen automatisch mit. Dann <b>Meldung senden</b>.',
                'Die Antwort des Support-Teams kommt hier und per E-Mail. Neue Antworten zählt <b>Hilfe &amp; Support</b>.',
                'Selbst nachschlagen: <b>Support › Wissensdatenbank</b> – mit Suche.',
                'Unter jedem Artikel: <b>Hilfreich?</b> – so lernt die Wissensdatenbank dazu.',
            ],
            'tips' => ['Bildschirmfoto kopieren und mit <kbd>⌘</kbd>/<kbd>Strg</kbd>+<kbd>V</kbd> in die Beschreibung einfügen.', '<b>Dringend</b> nur, wenn die Website nicht erreichbar ist oder Formulare nicht ankommen.'],
            'manual' => [['Hilfe & Support', '/admin/hilfe#support']],
        ],

        'r-ki-texte' => [
            'track' => 'redaktion', 'title' => 'KLXM AI: Text verbessern & übersetzen', 'icon' => 'sparkle', 'level' => 'Grundlagen', 'feature' => 'ai',
            'summary' => 'Vorschläge der KI prüfen, übernehmen oder verwerfen – und Übersetzungen als Entwurf anlegen.',
            'goal' => 'Sie lassen einen Text verbessern und einen Eintrag übersetzen – und prüfen jeden Vorschlag, bevor er gespeichert wird.',
            'prerequisites' => ['Recht „KI-Funktionen nutzen“ und eingeschaltete KI (Grundeinstellungen › KI).', 'Für Übersetzungen: eine zweite Sprache.'],
            'steps' => [
                'In jedem Textfeld steht <b>✦ KI</b>: Text anklicken, in der Formatierungsleiste <b>✦ KI</b> wählen.',
                '<b>Verbessern</b>, <b>Kürzen</b>, <b>Einfacher</b> … oder ein <b>Freier Auftrag</b>. Markierter Text = nur dieser Teil.',
                'Ein Vorschlag, kein Automatismus: <b>Vorschau</b> und <b>Änderungen</b> prüfen, dann <b>Übernehmen</b> oder <b>Verwerfen</b>.',
                'Übernommen wird in den Entwurf – online geht es erst mit <b>Veröffentlichen</b>.',
                'Übersetzen: <b>KLXM AI › Übersetzen</b> zeigt, was in anderen Sprachen noch fehlt (im Video eine Website mit Englisch).',
                '<b>Übersetzung anlegen</b> erstellt einen Entwurf in der anderen Sprache.',
                '<b>✦ Aus Deutsch übersetzen</b>: Texte auswählen, <b>Vorschläge erzeugen</b>.',
                'Jede Übersetzung prüfen und bei Bedarf ändern – übernommen wird nur, was angehakt ist (<b>In das Formular übernehmen</b>).',
                'Als <b>Entwurf</b> speichern und prüfen lassen – veröffentlicht wird von Menschen, nicht von der KI.',
            ],
            'tips' => ['Die KI erfindet keine Fakten: Fehlende Angaben erscheinen als <code>[bitte ergänzen: …]</code> – solche Seiten lassen sich nicht veröffentlichen.', 'Ton und Stil steuert die Administration unter Grundeinstellungen › KI (Hinweise, Glossar).'],
            'pitfalls' => ['Fachbegriffe, Namen, Zahlen und Zeiten immer gegenlesen – besonders bei Übersetzungen.', 'Keine vertraulichen Daten (z. B. aus Anfragen) in den freien Auftrag kopieren.'],
            'manual' => [['KLXM AI: schreiben, übersetzen, prüfen', '/admin/hilfe#assistent']],
        ],

        /* ================================================================ Administration */

        'a-benutzer-rollen' => [
            'track' => 'admin', 'title' => 'Benutzer & Rollen, 2FA verlangen', 'icon' => 'users-three', 'level' => 'Grundlagen', 'feature' => 'users',
            'summary' => 'Eigene Rolle zusammenstellen, Konto anlegen und je Rolle einen zweiten Faktor (App oder Passkey) verlangen.',
            'goal' => 'Jede Person bekommt ein eigenes Konto mit genau den Rechten, die sie braucht – abgesichert mit Zwei-Faktor-Anmeldung.',
            'prerequisites' => ['Recht „Benutzer und Rollen“ (Standard: Administration).'],
            'steps' => [
                '<b>Administration › Einstellungen › Benutzer &amp; Rollen</b>: Jede Person bekommt ein eigenes Konto.',
                'Erst eine passende Rolle: <b>+ Neue Rolle</b>, Namen eintragen und Rechte anhaken.',
                'Was nicht angehakt ist, sieht die Rolle nicht – z. B. kein <b>Veröffentlichen</b>. <b>Rolle speichern</b>.',
                '<b>Neuen Benutzer anlegen</b>: Name, E-Mail-Adresse, Startpasswort (persönlich übergeben) und Rolle – <b>Anlegen</b>.',
                '<b>Anmeldung &amp; Sicherheit</b>: erlaubte Verfahren – Authenticator-App, Passkeys, Anmeldung ohne Passwort.',
                'Je Rolle den zweiten Faktor wählen – z. B. Redaktion: <b>verlangt (App oder Passkey)</b> (oder <b>nur Passkey</b>).',
                '<b>Übergangsfrist</b>: 0 Tage = bei der nächsten Anmeldung einrichten. Dann <b>Speichern</b>.',
                'Betroffene richten App oder Passkey bei der nächsten Anmeldung ein. Netzwerk-Konten haben 2FA immer.',
            ],
            'tips' => ['Rechte für Datentabellen und Anfragen lassen sich je Tabelle einschränken („nur ausgewählte Tabellen“).', 'Telefon verloren? Anmeldung mit einem Wiederherstellungscode oder 2FA über die Kommandozeile zurücksetzen (<code>user:2fa-reset</code>).'],
            'pitfalls' => ['Konten nicht teilen – das Protokoll ordnet Änderungen Personen zu.', 'Die Rolle „Administration“ hat immer alle Rechte und lässt sich nicht einschränken.'],
            'manual' => [['Anmelden & Konto', '/admin/hilfe#anmelden'], ['Rollen, Rechte & Zwei-Faktor (Technik)', '/admin/hilfe/technik#rechte']],
        ],

        'a-website-daten' => [
            'track' => 'admin', 'title' => 'Website & Mehrsprachigkeit', 'icon' => 'translate', 'level' => 'Grundlagen',
            'summary' => 'Zentrale Angaben mit Vorschau pflegen, Übersetzungen und Sprachen der Website.',
            'goal' => 'Sie pflegen Name, Kontakt und Öffnungszeiten an einer Stelle und verwalten weitere Sprachen.',
            'prerequisites' => ['Recht „Website ändern“; für Sprachen „Grundeinstellungen“ und die Funktion Mehrsprachigkeit.'],
            'steps' => [
                '<b>Website</b> (je nach Kit z. B. „Praxisdaten“): Name, Adresse, Telefon, Öffnungszeiten – einmal gepflegt, überall auf der Website.',
                '<b>Vorschau</b> zeigt rechts, wo die Angabe auf der Website erscheint.',
                '<b>Speichern</b> – diese Angaben gelten sofort, ohne Veröffentlichen.',
                'Zweite Sprache: oben <b>EN English</b> – hier nur die Texte übersetzen, Telefon &amp; Adresse gelten für alle.',
                'Welche Sprachen es gibt, legen Sie unter <b>Grundeinstellungen › Sprachen</b> fest (<b>+ Sprache hinzufügen</b>).',
                'Die erste aktive Sprache ist Standard; jede weitere bekommt ein Präfix wie <code>/en/</code>.',
                'Seiten und Einträge übersetzen: in der Seitenliste bzw. mit <b>✦ Aus Deutsch übersetzen</b> (KI).',
            ],
            'tips' => ['<b>Texte mit KI aus Deutsch übersetzen</b> füllt die Übersetzungen unter „Website“ als Vorschlag.', 'Leere Übersetzungsfelder zeigen den Text der Standardsprache.'],
            'pitfalls' => ['Angaben unter „Website“ gelten sofort – es gibt hier keinen Entwurf.'],
            'manual' => [['Website', '/admin/hilfe#einstellungen'], ['Sprachen & Übersetzung (Technik)', '/admin/hilfe/technik#sprachen']],
        ],

        'a-design' => [
            'track' => 'admin', 'title' => 'Design: Style-Editor, Vorlagen, Navigation', 'icon' => 'palette', 'level' => 'Grundlagen', 'feature' => 'design',
            'summary' => 'Vorlagen ausprobieren, Farben mit Kontrastprüfung, Navigation – mit Live-Vorschau.',
            'goal' => 'Sie passen Farben, Schrift und Navigation an – barrierefrei geprüft und ohne das Kit zu verändern.',
            'prerequisites' => ['Recht „Design (Style-Editor)“ und die Funktion Design.'],
            'steps' => [
                '<b>Administration › Einstellungen › Design</b>: Farben, Schrift und Formen des Kits für diese Website.',
                '<b>Vorlagen</b> füllen das Formular mit einem stimmigen Satz – die Vorschau rechts zeigt es sofort.',
                'Jede Farbe mit Kontrastprüfung (AA/AAA) – für helle und dunkle Darstellung.',
                'Reiter <b>Typografie</b>, <b>Navigation</b>, <b>Kopfbereich: Suche &amp; Aktionen</b> – Schrift, Menü, Suchfeld und Button oben.',
                'Vorschau prüfen: Seite wählen, <b>Mobil</b> und <b>Dunkel</b> umschalten.',
                '<b>Speichern</b> stellt das Design online, <b>Verlauf</b> holt frühere Stände zurück. Zum Ausprobieren: <b>Verwerfen</b>.',
            ],
            'tips' => ['Welche Seiten im Menü stehen, steuern Sie in der Seitenliste (Schalter „Menü“) bzw. über Abschnitte mit Sprungmarke („In Hauptnavigation anzeigen“).', '<b>Export</b>/<b>Import</b> übertragen ein Design auf eine andere Website mit demselben Kit.'],
            'pitfalls' => ['Rote Kontrastwerte beheben, bevor Sie speichern – sonst sind Texte schlecht lesbar (WCAG).'],
            'manual' => [['Design: Farben, Formen, Schrift', '/admin/hilfe#design'], ['Menü ändern', '/admin/hilfe#menue']],
        ],

        'a-datentabelle' => [
            'track' => 'admin', 'title' => 'Datentabelle anlegen', 'icon' => 'table', 'level' => 'Fortgeschritten', 'feature' => 'data.schema',
            'summary' => 'Felder, Symbol-Auswahl, Bedingungen, Formular, Suche – und danach der Kalender.',
            'goal' => 'Sie bauen eine eigene Tabelle (hier „Kurse“) mit Detailseiten, bedingten Feldern, Besucher-Formular und Kalender.',
            'prerequisites' => ['Recht „Tabellen und Felder ändern“ und die Funktion „Tabellen und Felder selbst anlegen“.'],
            'steps' => [
                '<b>Daten › + Neue Tabelle</b>: eigene Inhalte wie Kurse, Produkte oder Stellen. <b>Name (Mehrzahl)</b> und <b>Einzahl</b> eintragen.',
                '<b>Symbol</b> wählen: suchen, z. B. „Schule“ – erscheint in Menü und Listen.',
                'Felder hinzufügen: unten den Typ wählen (<b>Datum &amp; Uhrzeit</b>, <b>Ja / Nein</b>, <b>Webadresse</b> …) und benennen.',
                '<b>Bedingungen</b>: „Link zum Raum“ nur zeigen, wenn „Online-Kurs“ = <b>Ja</b> (<b>+ Bedingung</b>).',
                'Rechts: <b>Adresse der Detailseiten</b>, <b>Besucher können Einträge anlegen</b> (öffentliches Formular) und <b>In der Website-Suche</b>.',
                '<b>Tabelle anlegen</b> – danach steht sie links im Menü und ist sofort nutzbar.',
                'Kalender: unter <b>Felder &amp; Einstellungen</b> <b>Als Kalender nutzen</b> und das Feld <b>Beginn</b> wählen, <b>Speichern</b>.',
                'Jetzt gibt es Kalenderansicht, Wiederholungen und ein iCal-Abo für diese Tabelle.',
            ],
            'tips' => ['Vorlagen auf der Seite Daten (Aktuelles, Team, Termine …) sparen Zeit.', 'Mit KI: <b>✦ Felder vorschlagen</b> bzw. KLXM AI › Tabellen-Generator.'],
            'pitfalls' => ['Der <b>Kurzname</b> ist später nicht mehr änderbar (Datenbank, API).', 'Kalender-Felder erst nach dem Anlegen wählbar – neue Felder stehen dort vor dem Speichern noch nicht zur Auswahl.', 'Für vertrauliche Angaben (Gesundheitsdaten) statt einer Inhaltstabelle einen verschlüsselten <b>Eingang</b> anlegen (Art der Tabelle).'],
            'manual' => [['Eigene Daten', '/admin/hilfe#daten'], ['Bedingungen', '/admin/hilfe#bedingungen'], ['Formular für Besucher', '/admin/hilfe#formular']],
        ],

        'a-quellen' => [
            'track' => 'admin', 'title' => 'Externe Quellen anbinden', 'icon' => 'plugs-connected', 'level' => 'Fortgeschritten', 'feature' => 'sources',
            'summary' => 'RSS, JSON, XML oder OpenImmo regelmäßig abrufen und als Einträge einer Datentabelle zeigen.',
            'goal' => 'Sie übernehmen Inhalte aus einer externen Quelle in eine Datentabelle – mit Zuordnung der Felder, Vorschau und Zeitplan.',
            'prerequisites' => ['Recht „Externe Quellen verwalten“ und die Funktion Externe Quellen (Netzwerk/Agentur schaltet sie ein).', 'Adresse der Quelle (URL) oder eine Datei, z. B. ein OpenImmo-ZIP aus der Makler-Software.'],
            'steps' => [
                '<b>Daten › Externe Quellen</b>: RSS-Feeds, JSON-APIs, XML und OpenImmo als Einträge einer Datentabelle.',
                'Besucher laden nie etwas von der Quelle: Liste, Detailseite, Suche und API kommen aus der eigenen Tabelle.',
                'Vorlagen für den Start: <b>RSS/Atom</b>, <b>OpenImmo</b>, <b>JSON-API</b> oder <b>XML (XPath)</b>.',
                'Das Beispiel „Immobilien“ liest eine OpenImmo-Datei aus einer Makler-Software.',
                '<b>Quelle</b>: Name, Format und Adresse – oder die Datei rechts hochladen. Anmeldedaten werden verschlüsselt gespeichert.',
                '<b>Abruf</b>: Zeitplan, Zwischenspeicher und was mit Einträgen geschieht, die in der Quelle fehlen.',
                '<b>Zuordnung</b>: Jedes Feld der Tabelle bekommt einen Pfad in der Quelle – mit Umwandlung, z. B. Zahl oder Datum.',
                '<b>Vorschau &amp; Test</b> zeigt die ersten Einträge so, wie sie in der Tabelle ankämen – ohne zu speichern.',
                'Rechts: <b>Stand</b>, <b>Jetzt abrufen</b> und das <b>Protokoll</b> der letzten Abrufe.',
                'Übernommene Einträge stehen in „Immobilien“ – nur lesbar, weil die Quelle sie pflegt.',
            ],
            'commands' => "*/15 * * * * php bin/console sources:sync --all     # Zeitplan zuverlässig per Cronjob",
            'tips' => ['Die Vorlage kann die passende Datentabelle samt Detailseite gleich mit anlegen (<b>Tabelle … anlegen</b>).', 'Bilder aus der Quelle landen – neu kodiert und ohne EXIF – in der Mediathek (Sammlung „Quelle: …“).'],
            'pitfalls' => ['Einträge aus einer Quelle nicht von Hand ändern – der nächste Abruf überschreibt sie. Eigene Ergänzungen in eigene Felder oder Tabellen.', 'Nutzungsrechte klären: Inhalte fremder Feeds dürfen nicht automatisch veröffentlicht werden.'],
            'manual' => [['Externe Quellen', '/admin/hilfe#quellen'], ['Externe Quellen (Technik)', '/admin/hilfe/technik#quellen']],
        ],

        'a-untertitel' => [
            'track' => 'admin', 'title' => 'Untertitel & Transkripte für Videos', 'icon' => 'video-camera', 'level' => 'Grundlagen', 'feature' => 'media.captions',
            'summary' => 'Untertitel schreiben oder hochladen, prüfen, veröffentlichen und daraus das Transkript machen.',
            'goal' => 'Ihre Videos werden barrierefrei: Untertitel im Player und ein Transkript unter dem Video (WCAG 1.2).',
            'prerequisites' => ['Ein Video in der Mediathek.', 'Recht „Dateien hochladen und bearbeiten“; für KI-Transkription eingeschaltete KI (Sprache → Text).'],
            'steps' => [
                'Barrierefreiheit: Videos brauchen Untertitel, Audio ein Transkript. <b>Medien › Videos ohne Untertitel</b>.',
                'Rechts unter <b>Untertitel &amp; Transkript</b>: <b>Hochladen (.vtt/.srt)</b>, <b>Neu schreiben</b> oder <b>Mit KI transkribieren</b>.',
                'Video abspielen und an passender Stelle <b>+ Untertitel an aktueller Zeit</b> – Text eintippen.',
                'Gut lesbar: höchstens 2 Zeilen à 42 Zeichen. Zeiten lassen sich mit ⇤ ⇥ anpassen.',
                'Erst <b>Geprüft – veröffentlichen</b> zeigt die Untertitel auf der Website. KI-Entwürfe immer prüfen!',
                'Veröffentlicht: Das Video verschwindet aus <b>Videos ohne Untertitel</b>. Unter <b>Videos</b> steht die Spur als <b>veröffentlicht</b>.',
                'Transkript: <b>+ Transkript</b> – oder den Text aus den Untertiteln übernehmen.',
                'Auf der Website erscheinen Untertitel im Player und <b>Transkript anzeigen</b> unter dem Video.',
                '<b>Mit KI transkribieren</b> (z. B. whisper.cpp auf dem Server) erzeugt einen Entwurf zur Prüfung.',
            ],
            'tips' => ['Tastatur im Editor: <kbd>Alt</kbd>+<kbd>Enter</kbd> neuer Untertitel, <kbd>Alt</kbd>+<kbd>P</kbd> Abspielen/Pause.', 'Geräusche in eckigen Klammern, z. B. [Musik]; Sprecherwechsel mit „–“.'],
            'pitfalls' => ['Automatische Transkripte enthalten Fehler bei Namen, Fachbegriffen und Zahlen – vollständig ansehen und korrigieren.'],
            'manual' => [['Untertitel & Transkripte', '/admin/hilfe#untertitel'], ['Medien, Pools & Untertitel (Technik)', '/admin/hilfe/technik#medien']],
        ],

        'a-api-freigabe' => [
            'track' => 'admin', 'title' => 'API-Token & „Eingereicht“ (Freigabe)', 'icon' => 'shield-check', 'level' => 'Fortgeschritten', 'feature' => 'review',
            'summary' => 'Token für KI-Assistenten (MCP) und REST-API anlegen – Änderungen erst nach Freigabe.',
            'goal' => 'Ein KI-Assistent darf Vorschläge machen, aber ein Mensch entscheidet: Sie prüfen jede Änderung unter „Eingereicht“.',
            'prerequisites' => ['Recht „API & MCP“ und „Eingereichte Änderungen prüfen“.'],
            'steps' => [
                '<b>API &amp; MCP</b>: Zugänge für Automatisierungen und KI-Assistenten wie Claude. <b>Neuen Token erzeugen</b>: Name, <b>Berechtigung: Lesen und ändern</b>.',
                '<b>Änderungen: Zur Freigabe</b> – ein Mensch prüft jede Änderung, bevor sie online geht. <b>Token erzeugen</b>.',
                'Der Token erscheint nur einmal – sofort in den Passwortmanager kopieren (im Video unkenntlich).',
                'Ändert der Assistent jetzt etwas, landet es unter <b>KLXM AI › Eingereicht</b>.',
                'Herkunft (Token, Kanal) und Vorher/Nachher prüfen – dann <b>Übernehmen</b> oder <b>Ablehnen</b> (mit Begründung).',
                'Jede Einreichung bleibt protokolliert. Tokens lassen sich jederzeit umstellen oder <b>Widerrufen</b>.',
            ],
            'commands' => "# MCP-Server in Claude Code verbinden (Token aus dem Passwortmanager)\nclaude mcp add --transport http klxm-studio https://www.ihre-website.de/mcp \\\n  --header \"Authorization: Bearer cms_IHR_TOKEN\"",
            'tips' => ['„Nur lesen“ genügt für Auswertungen und Prüfungen.', 'Optional: „Gültig bis“ begrenzt einen Token zeitlich.'],
            'pitfalls' => ['Tokens nie in E-Mails, Tickets oder Code-Repositories – sie sind wie Passwörter.', 'Bestehende Tokens bleiben auf „Direkt übernehmen“, bis Sie sie umstellen.'],
            'manual' => [['KI-Assistenten über MCP & Freigabe', '/admin/hilfe#ki'], ['Prüf-Ebene „Eingereicht“ (Technik)', '/admin/hilfe/technik#freigabe'], ['MCP-Server (Technik)', '/admin/hilfe/technik#mcp']],
        ],

        'a-seo' => [
            'track' => 'admin', 'title' => 'SEO-Übersicht', 'icon' => 'magnifying-glass', 'level' => 'Grundlagen', 'feature' => 'ai',
            'summary' => 'Fehlende oder doppelte Beschreibungen finden und KI-Vorschläge geprüft übernehmen.',
            'goal' => 'Alle Seiten und Einträge haben eine passende Beschreibung für Suchmaschinen.',
            'prerequisites' => ['Recht „KI-Funktionen nutzen“ und „Seiten anlegen, … Seiteneinstellungen“.'],
            'steps' => [
                '<b>KLXM AI › SEO-Übersicht</b>: Wo fehlen Angaben für Suchmaschinen – oder sind doppelt?',
                'Zeilen auswählen – hier nur „Datenschutz“ – und <b>✦ Vorschläge für Auswahl erzeugen</b>.',
                'Vorschlag lesen und bei Bedarf ändern (Zähler: ideal bis 160 Zeichen). Nur Angehaktes wird übernommen: <b>Ausgewählte übernehmen</b>.',
                'Die Beschreibung steht jetzt in den <b>Seiteneinstellungen</b> – dort prüft auch der <b>SEO-Check</b> Überschriften und Bilder.',
            ],
            'tips' => ['Gute Beschreibungen nennen Angebot, Ort und Nutzen in einem Satz.'],
            'pitfalls' => ['Doppelte Beschreibungen („Gleiche Beschreibung wie …“) schwächen beide Seiten in Suchergebnissen.'],
            'manual' => [['KLXM AI: SEO', '/admin/hilfe#assistent']],
        ],

        'a-consent' => [
            'track' => 'admin', 'title' => 'Cookie-Einwilligung mit dem Consent Kit', 'icon' => 'cookie', 'level' => 'Grundlagen',
            'summary' => 'Cookiefrei ab Werk – und wenn doch Dienste nötig sind: Einwilligung mit Vorlagen, Design und Protokoll.',
            'goal' => 'Sie binden einwilligungspflichtige Dienste (z. B. Statistik, Videos) so ein, dass sie erst nach Zustimmung laden.',
            'prerequisites' => ['Erweiterung Consent-Kit auf dieser Website (Agentur/Netzwerk) und das Recht für die Cookie-Einwilligung.'],
            'steps' => [
                '<b>Cookie-Einwilligung</b> (Erweiterung Consent Kit): Ohne einwilligungspflichtige Dienste gibt es keinen Hinweis – cookiefrei ab Werk.',
                '<b>Dienste</b>: z. B. Statistik (Matomo) oder externe Medien (YouTube) – je Domain an- und abschaltbar.',
                '<b>Dienst hinzufügen</b>: Vorlagen mit Anbieter, Zweck, Cookies und Datenschutz-Link.',
                '<b>Design</b>: Farben kommen aus dem Design der Website. Vorschau als Box, Leiste oder Dialog – hell und dunkel.',
                'Auf der Website: Der Hinweis erscheint, bis Besucher entscheiden. <b>Alle ablehnen</b> ist so leicht wie <b>Alle akzeptieren</b>.',
                '<b>Einstellungen</b> zeigt jeden Dienst mit Zweck und Speicherdauer – einzeln wählbar.',
                'Abgelehnte Inhalte zeigen einen Platzhalter: erst nach Klick lädt das Video vom Anbieter.',
                'Jede Entscheidung steht anonym im <b>Protokoll</b>; Besucher ändern sie jederzeit über <b>Datenschutz-Einstellungen</b>.',
            ],
            'tips' => ['Datenschutzerklärung und Impressum sind im Hinweis verlinkt – beide Seiten zuerst anlegen.', 'Landingpages mit eigener Domain haben eine eigene Spalte: Dienste je Domain an- oder abschalten.'],
            'pitfalls' => ['Neue Dienste (z. B. ein Karten- oder Video-Anbieter) immer zuerst hier eintragen – sonst laden sie ohne Einwilligung.', 'Ändert sich ein Dienst wesentlich, fragt der Hinweis erneut – das ist gewollt.'],
            'manual' => [['Cookie-Einwilligung', '/admin/hilfe#cookies'], ['Cookie-Einwilligung (Technik)', '/admin/hilfe/technik#consent']],
        ],

        /* ================================================================ Agenturen / Netzwerk */

        'n-netzwerk' => [
            'track' => 'agentur', 'title' => 'Netzwerk-Dashboard & Website öffnen', 'icon' => 'network', 'level' => 'Einstieg',
            'summary' => 'Alle Websites im Blick, suchen, filtern und per SSO öffnen.',
            'goal' => 'Sie überblicken alle Websites der Installation und wechseln ohne erneute Anmeldung in eine Website.',
            'prerequisites' => ['Ein Netzwerk-Konto (Rolle „Netzwerk-Administration“) mit eingerichteter Zwei-Faktor-Anmeldung, angemeldet auf der Hauptwebsite.'],
            'steps' => [
                '<b>Netzwerk › Alle Websites</b>: Zustand, Anfragen, Freigaben, Speicher und Sicherung auf einen Blick.',
                'Suchen und filtern: <b>Mit Hinweisen</b>, <b>Wartung</b>, <b>Nicht live</b>.',
                '<b>Öffnen</b> meldet Sie per Einmal-Token (SSO) in der Verwaltung dieser Website an – ohne zweites Passwort.',
                'Dort arbeiten Sie mit den Rechten der Agentur; <b>Website wechseln</b> in der Seitenleiste führt zur nächsten.',
                'Unten: <b>Netzwerk-Administratoren</b> (immer mit Zwei-Faktor-Anmeldung), <b>Neue Website</b>, <b>Geteilte Ressourcen</b>, <b>Protokoll</b>.',
                'Sperren Sie ein Netzwerk-Konto, enden seine Sitzungen auf allen Websites sofort.',
            ],
            'tips' => ['Die Kennzahlen werden zwischengespeichert – <b>Aktualisieren</b> holt den aktuellen Stand.'],
            'pitfalls' => ['Das SSO-Token ist 60 Sekunden gültig, einmal verwendbar und an Browser, Konto und Ziel-Website gebunden.'],
            'manual' => [['Netzwerk-Administration (Technik)', '/admin/hilfe/technik#netzwerk'], ['Mehrere Websites (Technik)', '/admin/hilfe/technik#websites']],
        ],

        'n-website-anlegen' => [
            'track' => 'agentur', 'title' => 'Neue Website anlegen', 'icon' => 'browser', 'level' => 'Grundlagen',
            'summary' => 'Kurzname, Domains und Kit – in der Oberfläche oder mit site:create.',
            'goal' => 'Sie legen eine weitere Website mit eigener Datenbank, eigenen Medien, Benutzern und Schlüsseln an.',
            'prerequisites' => ['Netzwerk-Konto auf der Hauptwebsite.', 'Die Domain zeigt im Hosting auf denselben Ordner (Dokumentstamm <code>httpdocs/public</code>).'],
            'steps' => [
                '<b>Netzwerk › Neue Website</b>: <b>Kurzname</b>, <b>Domains (mit Komma getrennt)</b> und <b>Kit</b> – wie <code>site:create</code> auf der Kommandozeile.',
                '<b>Website anlegen</b>: eigene Konfiguration mit eigenen Schlüsseln. Die nächsten Schritte stehen im Kasten.',
                'Domain im Hosting auf denselben Ordner (<code>httpdocs/public</code>) zeigen lassen – der erste Aufruf legt Datenbank, Medienordner und Startinhalte an.',
                'Dann <b>Öffnen</b> – oder das erste lokale Konto über <code>/admin/setup</code> mit dem Setup-Token (im Video unkenntlich).',
            ],
            'commands' => "php bin/console site:create kunde www.kunde.de,kunde.de basis\nphp bin/console site:list",
            'tips' => ['Funktionsumfang, Kit-Optionen und KI stehen danach in <code>config/sites/{kurzname}.php</code>.'],
            'pitfalls' => ['<code>config/sites/*.php</code> enthält Schlüssel – nicht versionieren, beim Deploy im Ordner <code>shared/</code>.'],
            'manual' => [['Mehrere Websites (Technik)', '/admin/hilfe/technik#websites'], ['Kommandozeile', '/admin/hilfe/technik#cli']],
        ],

        'n-funktionen' => [
            'track' => 'agentur', 'title' => 'Pakete & Funktionen je Projekt', 'icon' => 'sliders-horizontal', 'level' => 'Fortgeschritten',
            'summary' => 'Presets full / content / minimal, einzelne Funktionen, Blöcke und Integratoren.',
            'goal' => 'Jede Website bekommt genau den Funktionsumfang, den das Projekt vorsieht – gesteuert von der Agentur, nicht vom Kunden.',
            'prerequisites' => ['Zugriff auf die Konfiguration der Installation (SFTP/SSH oder Deploy).'],
            'steps' => [
                'Jede Website hat einen Funktionsumfang: Preset <code>full</code>, <code>content</code> oder <code>minimal</code> plus einzelne Schalter.',
                'Die Agentur legt ihn in <code>config/sites/{website}.php</code> fest – die Kundschaft kann ihn nicht ändern.',
                'In jeder Website zeigt <b>Grundeinstellungen › Systeminfo</b>, was dort an- oder abgeschaltet ist.',
                'Abgeschaltete Funktionen sperren Menüs, Rechte, API und MCP – auch für die Administration der Website.',
                'Alle Schalter und Beispiele: <b>Technische Dokumentation › Funktionsumfang &amp; Erweiterungen</b>.',
            ],
            'commands' => "// config/sites/kunde.php (Hauptwebsite: config/config.local.php)\n'preset'      => 'content',                  // full | content | minimal\n'features'    => ['data.schema' => false, 'languages' => true],\n'blocks'      => ['deny' => ['video']],\n'integrators' => ['team@agentur.de'],        // diese Konten sehen immer alles",
            'tips' => ['Netzwerk-Konten und Integratoren sehen immer alles – zum Testen des Kundenblicks ein normales Konto verwenden.'],
            'pitfalls' => ['Gesperrte Blocktypen bleiben in bestehenden Seiten bearbeitbar, lassen sich aber nicht neu einfügen.'],
            'manual' => [['Funktionsumfang & Erweiterungen (Technik)', '/admin/hilfe/technik#funktionen']],
        ],

        'n-geteilt' => [
            'track' => 'agentur', 'title' => 'Geteilte Medien & geteilte Daten', 'icon' => 'share-network', 'level' => 'Fortgeschritten',
            'summary' => 'Medien-Pools (z. B. Markenbilder) und Datentabellen, die mehrere Websites gemeinsam nutzen (z. B. ein Verband und seine Vereine).',
            'goal' => 'Mehrere Websites nutzen gemeinsame Bilder und Daten – gepflegt an einer Stelle.',
            'prerequisites' => ['Netzwerk-Konto oder Administration der Hauptwebsite.'],
            'steps' => [
                '<b>Grundeinstellungen › Geteilte Medien</b>: zentrale Mediatheken (z. B. Logos, Markenbilder) für mehrere Websites.',
                '<b>Neuen Pool anlegen</b>: Name, Kurzname und die Websites, die ihn nutzen dürfen – <b>Anlegen</b>.',
                'Je Pool: <b>Genutzt von</b> (welche Websites) und <b>Pflegen dürfen</b> – alle anderen verwenden die Dateien nur.',
                'In der Mediathek der Website: Datei mit rechter Maustaste › <b>In … verschieben (geteilt)</b> – bisherige Verwendungen bleiben erhalten.',
                'Oben zwischen <b>Diese Website</b> und dem Pool umschalten – dort liegt die Datei jetzt für alle Websites des Pools.',
                'Geteilte Daten: Eine Website besitzt die Tabelle (Eigentümer-Website, z. B. ein Verband), die beteiligten Websites (z. B. seine Vereine) sehen und ergänzen Einträge – <b>Grundeinstellungen › Geteilte Daten</b>.',
                'Auf den beteiligten Websites erscheinen die Einträge der Eigentümer-Website in derselben Tabelle – nur lesbar, eigene bleiben bearbeitbar. Überblick: <b>Netzwerk › Geteilte Ressourcen</b>.',
                'Befehle für Sicherungen: <code>pool:backup</code> und <code>shared:backup</code>.',
            ],
            'commands' => "php bin/console pool:create marke \"Markenbilder\"\nphp bin/console data:share verbandsnews --members=verein-a,verein-b --site=verband\nphp bin/console pool:backup --all\nphp bin/console shared:backup --all",
            'tips' => ['Vorhandene Dateien teilen: in der Mediathek per Rechtsklick „In … verschieben (geteilt)“ – bisherige Verwendungen bleiben gültig.'],
            'pitfalls' => ['Änderungen in Pools und geteilten Tabellen wirken sofort auf allen beteiligten Websites.', '<code>sync-content.sh</code> überträgt Pools und geteilte Tabellen nicht mit.'],
            'manual' => [['Geteilte Datentabellen (Technik)', '/admin/hilfe/technik#geteilt'], ['Medien & Pools (Technik)', '/admin/hilfe/technik#medien'], ['Geteilte Tabellen (Handbuch)', '/admin/hilfe#geteilt']],
        ],

        'n-ki' => [
            'track' => 'agentur', 'title' => 'KI einrichten (Ollama, whisper.cpp, Datenschutz)', 'icon' => 'robot', 'level' => 'Fortgeschritten',
            'summary' => 'Fähigkeiten je Website, Anbieter der Installation, Verbindung testen, Datenschutz.',
            'goal' => 'Die KI-Funktionen laufen – bevorzugt auf dem eigenen Server – und jede Website nutzt nur, was freigeschaltet ist.',
            'prerequisites' => ['Funktion „ai“ im Funktionsumfang.', 'Ein KI-Anbieter: Ollama (eigener Server), whisper.cpp für Untertitel oder ein externer Dienst mit AV-Vertrag.'],
            'steps' => [
                '<b>Grundeinstellungen › KI</b>: je Website einschalten und Fähigkeiten wählen – Texte, Bilder, Suche, Untertitel.',
                '<b>Tageslimit</b>, <b>Hinweise für die KI</b> (Zielgruppe, Anrede, Stil) und ein <b>Glossar</b> steuern den Assistenten.',
                '<b>Fähigkeiten</b>: Anbieter und Modell legt die Agentur in der Konfiguration fest – z. B. Ollama und whisper.cpp.',
                '„bleibt auf dem Server“: Mit lokalen Modellen verlassen Inhalte das Haus nicht. Externe Dienste sind gekennzeichnet. <b>Verbindung testen</b> prüft jede Fähigkeit.',
                'Konfiguration und Befehle (<code>ai:test</code>, <code>search:index</code>) stehen in der <b>Technischen Dokumentation › KLXM AI</b>.',
            ],
            'commands' => "// config/config.local.php (Installation) oder config/sites/{website}.php\n'ai' => [\n    'provider' => 'ollama',\n    'base_url' => 'http://127.0.0.1:11434',\n    'models'   => ['text' => 'gemma3', 'embed' => 'bge-m3', 'vision' => 'gemma3'],\n    'transcribe' => ['backend' => 'whisper_cpp', 'model_path' => '…/ggml-large-v3-turbo-q5_0.bin'],\n],\n\nphp bin/console ai:test --cap=text\nphp bin/console search:index --all",
            'tips' => ['Die Rechte „KI-Funktionen nutzen“ und „Eingereichte Änderungen prüfen“ vergeben Sie je Rolle.'],
            'pitfalls' => ['Externe Anbieter (OpenAI, Mistral …) in der Datenschutzerklärung nennen und einen AV-Vertrag abschließen.', 'API-Schlüssel nur in der Konfiguration, nie in Kits oder im Repository.'],
            'manual' => [['KLXM AI: KI-Dienst & Funktionen (Technik)', '/admin/hilfe/technik#ki'], ['Website-Suche (Technik)', '/admin/hilfe/technik#suche']],
        ],

        'n-staging-deploy' => [
            'track' => 'agentur', 'title' => 'Staging & Deploy', 'icon' => 'terminal-window', 'level' => 'Fortgeschritten',
            'summary' => 'Was die Oberfläche zeigt – und die Befehle für Releases, Rollback und Inhalte.',
            'goal' => 'Code kommt geprüft und mit Sicherung auf den Server; Staging bekommt bei Bedarf eine Kopie der Live-Inhalte.',
            'prerequisites' => ['SSH-Zugang oder CI (GitHub Actions) und Zieldateien <code>deploy/targets/{ziel}.env</code>.'],
            'steps' => [
                'Staging ist eine eigene Installation mit Kopie der Live-Inhalte. <b>Netzwerk</b> zeigt mit <b>Nicht live</b>, was keine Produktion ist.',
                'Vor Eingriffen: <b>Wartung ▾</b> – <b>Sicherung jetzt</b>, <b>Wartungsmodus an</b>, <b>Seiten-Cache leeren</b>.',
                'Gesundheitsprüfung für Deploys: <code>/health</code> antwortet ohne Geheimnisse (<code>ok</code>, Version, Umgebung).',
                'Deploy per Kommandozeile: <code>deploy/deploy.sh staging</code> bzw. <code>production</code> – mit Sicherung, <code>migrate</code>, <code>health</code> und automatischem Rollback.',
            ],
            'commands' => "deploy/deploy.sh staging                 # bauen, hochladen, migrieren, prüfen, umschalten\ndeploy/deploy.sh production              # zusätzlich vorher Sicherung\ndeploy/deploy.sh production --rollback   # vorheriges Release aktivieren\ndeploy/sync-content.sh default           # Datenbank + Medien einer Website: Live → Staging\n\nphp bin/console health --all\nphp bin/console site:backup --all",
            'tips' => ['Staging (<code>\'environment\' => \'staging\'</code>) sperrt Suchmaschinen aus, zeigt eine Hinweisleiste und leitet E-Mails um.'],
            'pitfalls' => ['Schema-Änderungen laufen vor dem Umschalten gegen die Live-Datenbank – sie müssen additiv sein.'],
            'manual' => [['Staging & Deploy (Technik)', '/admin/hilfe/technik#deploy'], ['Betrieb: Cronjobs, Sicherungen, Updates', '/admin/hilfe/technik#betrieb']],
        ],

        'n-theme' => [
            'track' => 'agentur', 'title' => 'Eigenes Kit: Design-Tokens & Export', 'icon' => 'paint-brush', 'level' => 'Fortgeschritten',
            'summary' => 'Design-Tokens im Style-Editor, Export – und wann ein eigenes Kit sinnvoll ist.',
            'goal' => 'Sie wissen, wann der Style-Editor genügt und wann ein eigenes Kit sinnvoll ist – und wie Sie es anlegen.',
            'prerequisites' => ['Für eigene Kits: Node/pnpm für den Build (nur lokal), Zugriff auf den Ordner <code>kits/</code>.'],
            'steps' => [
                'Jeder Wert im Style-Editor ist ein Design-Token (CSS-Variable) aus dem Kit – <code>theme.php → \'design\'</code>.',
                '<b>Export</b> sichert die Werte als Datei – z. B. um sie in ein eigenes Kit oder eine andere Website zu übernehmen.',
                'Eigenes Projekt = eigenes Kit: <code>kit:create</code> kopiert das Start-Kit – der Core bleibt updatefähig.',
                'Aufbau, Tokens, Blöcke und Vorlagen beschreibt die <b>Technische Dokumentation › Kits &amp; Design</b>.',
            ],
            'commands' => "php bin/console kit:create meinprojekt            # Kopie des Start-Kits (--from=basis für eine andere Vorlage)\npnpm --dir tools build                            # Assets des Kits bauen\n# Website auf das Kit umstellen: config/sites/{website}.php → 'kit' => 'meinprojekt'",
            'tips' => ['Tutorials für Ihr Kit: <code>kits/{name}/docs/tutorials.php</code> ergänzt diese Seite; eigene Videos mit <code>node tools/tutorials/record.mjs</code>.', 'Schritt für Schritt mit dem Start-Kit: Tutorial „Eigenes Kit mit dem Start-Kit“.'],
            'pitfalls' => ['Kit-Namen nie im Core verwenden – projektspezifisches gehört ins Kit.'],
            'manual' => [['Kits & Design (Technik)', '/admin/hilfe/technik#kits'], ['Build & Entwicklung (Technik)', '/admin/hilfe/technik#build']],
        ],

        'n-kit-starter' => [
            'track' => 'agentur', 'title' => 'Eigenes Kit mit dem Start-Kit', 'icon' => 'package', 'level' => 'Fortgeschritten',
            'summary' => 'kit:create kopiert das Start-Kit „starter“ – danach anpassen, bauen, testen.',
            'goal' => 'Sie legen für ein Projekt ein eigenes Kit an, das auf dem kleinsten vollständigen Kit aufbaut, und wissen, welche Schritte danach folgen.',
            'prerequisites' => ['Zugriff auf die Kommandozeile und den Ordner <code>kits/</code> (lokal oder auf dem Server).', 'Node/pnpm für den Build (nur lokal).'],
            'steps' => [
                'Eigenes Kit für ein Projekt: <code>kit:create</code> kopiert das Start-Kit und benennt alles um.',
                'Die Ausgabe nennt die neuen Ordner und die nächsten Schritte: anpassen, bauen, testen, prüfen.',
                'Das Start-Kit ist das kleinste vollständige Kit: sechs Beispielblöcke, hell und dunkel, eine Akzentfarbe.',
                'Farben, Schrift und Navigation stellen Sie wie gewohnt unter <b>Design</b> ein – die Werte sind Design-Tokens des Kits.',
                '<code>theme.php</code> ist in Abschnitte § 1–11 gegliedert. Die Anleitung: <b>Technische Dokumentation › Kits &amp; Design</b>.',
            ],
            'commands' => "php bin/console kit:create kanzlei                 # Kopie von kits/starter, Präfix starter_ → kanzlei_\ncd tools && pnpm run build\nphp bin/console site:create kunde www.kunde.de kanzlei\nphp bin/console health --site=kunde\nphp kits/kanzlei/tools/contrast.php",
            'tips' => ['<code>kit:create name --from=basis</code> nimmt ein anderes Kit als Vorlage.', 'Budget der Startseite prüfen: CSS &lt; 30 KB, JS &lt; 8 KB (Start-Kit ≈ 15,7 KB / 0,4 KB).'],
            'pitfalls' => ['Nach Änderungen an <code>assets/</code> neu bauen – <code>public/assets/kits/{name}/</code> enthält nur die gebauten Dateien.', 'Das Start-Kit selbst nicht ändern – es ist die Vorlage für <code>kit:create</code> und wird mit Updates ersetzt.'],
            'manual' => [['Eigenes Kit entwickeln (Technik)', '/admin/hilfe/technik#start-kit'], ['Kits & Design (Technik)', '/admin/hilfe/technik#kits'], ['Kommandozeile', '/admin/hilfe/technik#cli']],
        ],
    ],
];
