<?php
/*
 * Design-Tokens des Themes „fluid“ für den Style-Editor (Verwaltung → Design) – siehe Core\Design.
 *
 * Jeder Token wird eine CSS-Variable (--f-…) oder eine Klasse am <html> (hdr-inline, btn-pill, cards-glass, has-dark …).
 * Typografie und Abstände sind fließend: Schriftgrößen entstehen aus Grundgröße (min/max), Verhältnis der Stufen und
 * Bereich der Bildschirmbreite per clamp() (Utopia-Prinzip) – keine Breakpoints, keine Media-Queries.
 * Voreinstellungen sind mit tools/contrast.php auf WCAG 2.2 AA geprüft (hell und dunkel):
 *   php kits/fluid/tools/contrast.php
 * Standardwerte müssen mit :root in assets/css/_tokens.css übereinstimmen (Voreinstellung „Fluid Standard“).
 */

// Reihenfolge der Farbwerte in den Voreinstellungen
$colorKeys = ['accent', 'accent_strong', 'on_accent', 'highlight', 'ink', 'text', 'muted', 'background', 'surface', 'line', 'dark_section'];

/** Voreinstellung: Farben hell + dunkel (je 11 Werte in obiger Reihenfolge) und übrige Werte */
$preset = function (string $label, string $desc, array $light, array $dark, array $rest) use ($colorKeys): array {
    $values = [];
    foreach ($colorKeys as $i => $k) {
        $values[$k] = $light[$i];
        $values[$k . '@dark'] = $dark[$i];
    }
    return ['label' => $label, 'description' => $desc, 'values' => $values + $rest];
};

$color = fn(string $name, string $label, string $var, string $light, string $dark, ?array $contrast = null, string $help = '') => array_filter([
    'name' => $name, 'label' => $label, 'type' => 'color', 'var' => $var, 'default' => $light, 'dark' => $dark,
    'contrast' => $contrast, 'help' => $help,
], fn($v) => $v !== null && $v !== '');

// Gemeinsame Werte der Voreinstellungen (werden je Vorlage überschrieben)
$base = [
    'font_body' => 'inter', 'font_head' => 'inter', 'font_mono' => 'system-mono', 'label_font' => 'body',
    'fs_min' => 16, 'fs_max' => 18.5, 'ratio' => 1.25, 'vw_min' => 360, 'vw_max' => 1280,
    'heading_weight' => 650, 'heading_tracking' => -2,
    'radius' => 10, 'buttons' => 'solid', 'cards' => 'outlined', 'shadow' => 'soft', 'density' => 'normal', 'space' => 'normal', 'wrap' => 76,
    'secondary_role' => 'sections', 'heading_case' => 'normal', 'emphasis' => 'accent', 'links' => 'underline',
    'images' => 'radius', 'image_fx' => 'none', 'hover' => 'lift', 'icons' => 'soft', 'icon_pos' => 'top', 'dividers' => 'none', 'motion_style' => 'rise',
    'eyebrow' => 'line', 'eyebrow_case' => 'auto', 'header' => 'inline', 'header_sticky' => true, 'header_bg' => 'page', 'nav_style' => 'plain', 'topbar' => 'off',
    'footer' => 'columns', 'footer_bg' => 'surface', 'sections' => 'flush', 'progress' => false, 'totop' => false, 'footer_line' => 'auto', 'footer_line_color' => 'auto', 'footer_line_width' => 'auto', 'header_height' => 'auto', 'nav_parent' => 'split', 'nav_levels' => 'accordion', 'pagebg' => 'plain',
    'logo_size' => 'normal', 'side_width' => 'normal', 'side_tree' => 'branch', 'side_banner' => 'off', 'side_banner_height' => 'normal', 'side_banner_overlay' => 'none', 'palette' => 'brand',
    'motion' => true, 'dark' => true,
];

return [
    'groups' => [
        ['id' => 'farben', 'label' => 'Farben', 'tokens' => [
            $color('accent', 'Akzent', '--f-a', '#4338CA', '#A5B4FC', ['with' => 'background', 'min' => 4.5],
                'Buttons, Links, Symbole und Abschnitte „Akzentfarbe“. Muss auf dem Hintergrund als Linkfarbe lesbar sein.'),
            $color('accent_strong', 'Akzent kräftig', '--f-a-strong', '#3730A3', '#C7D2FE', ['with' => 'background', 'min' => 4.5],
                'Hover-Zustand; hell etwas dunkler als der Akzent, dunkel etwas heller.'),
            $color('on_accent', 'Schrift auf Akzent', '--f-a-on', '#FFFFFF', '#14123A', ['with' => 'accent', 'min' => 4.5],
                'Text auf Buttons und im Abschnitt „Akzentfarbe“.'),
            $color('highlight', 'Hervorhebung (Flächen, Marker)', '--f-a2', '#FDE68A', '#3A3470', ['with' => 'ink', 'min' => 4.5],
                'Hervorgehobene Kacheln, Markierungen, Etiketten und die Betonung „Textmarker“ – Überschriftenfarbe muss darauf lesbar sein.'),
            $color('secondary', 'Zweite Markenfarbe', '--f-b', '#0F766E', '#5EEAD4', ['with' => 'background', 'min' => 3],
                'Für Organisationen mit zwei Markenfarben: Abschnitte „Zweite Markenfarbe“ und – je nach Einstellung unten – Symbole, Dachzeilen-Marken und zweite Buttons.'),
            $color('on_secondary', 'Schrift auf zweiter Markenfarbe', '--f-b-on', '#FFFFFF', '#062B27', ['with' => 'secondary', 'min' => 4.5]),
            $color('ink', 'Überschriften', '--f-ink', '#0B0D17', '#F3F4F8', ['with' => 'background', 'min' => 7]),
            $color('text', 'Fließtext', '--f-text', '#2B2F3A', '#D2D5DE', ['with' => 'background', 'min' => 4.5]),
            $color('muted', 'Nebentext', '--f-muted', '#565C6B', '#9EA3B2', ['with' => 'surface', 'min' => 4.5],
                'Einleitungen, Bildunterschriften, Metadaten – auch auf getönten Flächen lesbar.'),
            $color('background', 'Hintergrund', '--f-bg', '#FFFFFF', '#0B0C14'),
            $color('surface', 'Getönte Fläche', '--f-surface', '#F4F5F8', '#141621', ['with' => 'text', 'min' => 4.5],
                'Abschnitte „Getönt“, Fußbereich, Karten im Stil „Fläche“.'),
            $color('line', 'Linien', '--f-line', '#E2E4EB', '#272B3A', null, 'Trennlinien und Rahmen (dekorativ).'),
            $color('dark_section', 'Dunkle Abschnitte', '--f-dark', '#0E1022', '#1A1D33', ['with' => '#FFFFFF', 'min' => 7, 'dark_with' => '#FFFFFF'],
                'Hintergrund der Abschnitte „Dunkel“ (Schrift weiß). Im dunklen Farbschema etwas heller als der Hintergrund, damit das Band sichtbar bleibt.'),
            // Farbenfroh (palette): drei weitere Farben – mit Akzent und zweiter Markenfarbe fünf, die sich in Karten, Symbolen,
            // Abschnitten und Listen abwechseln. Nur für Grafik (Linien, Symbole, Marker) und als zarte Tönung unter dunkler Schrift.
            ['name' => 'palette', 'label' => 'Farbwirkung', 'type' => 'choice', 'class' => 'pal-{value}', 'default' => 'brand',
                'options' => ['brand' => 'Markenfarben (Akzent, zweite Markenfarbe)', 'colorful' => 'Farbenfroh – fünf Farben im Wechsel'],
                'help' => '„Farbenfroh“: Karten, Symbole, Kennzahlen, Listenpunkte, getönte Abschnitte und die Seitenleiste wechseln zwischen Akzent, zweiter Markenfarbe und den drei Farben unten. Schrift bleibt in Überschriften- und Textfarbe – die Farben tönen nur Flächen, Linien und Symbole.'],
            $color('color3', 'Dritte Farbe (farbenfroh)', '--f-c3', '#B45309', '#FCD34D', ['with' => 'background', 'min' => 3],
                'Nur bei „Farbenfroh“. Für Linien, Symbole und Marker – mindestens 3 : 1 zum Hintergrund.'),
            $color('color4', 'Vierte Farbe (farbenfroh)', '--f-c4', '#BE185D', '#F9A8D4', ['with' => 'background', 'min' => 3]),
            $color('color5', 'Fünfte Farbe (farbenfroh)', '--f-c5', '#0369A1', '#7DD3FC', ['with' => 'background', 'min' => 3]),
            ['name' => 'secondary_role', 'label' => 'Zweite Markenfarbe einsetzen für', 'type' => 'choice', 'class' => 'sec2-{value}', 'default' => 'sections',
                'options' => ['sections' => 'Nur Abschnitte in dieser Farbe', 'details' => 'Auch Symbole und Dachzeilen-Marken', 'buttons' => 'Auch zweite Buttons', 'all' => 'Symbole, Marken und zweite Buttons']],
        ]],
        ['id' => 'typo', 'label' => 'Typografie', 'tokens' => [
            ['name' => 'font_body', 'label' => 'Schrift Fließtext', 'type' => 'font', 'var' => '--f-font', 'default' => 'inter'],
            ['name' => 'font_head', 'label' => 'Schrift Überschriften', 'type' => 'font', 'var' => '--f-font-head', 'default' => 'inter'],
            ['name' => 'font_mono', 'label' => 'Schrift für Code und Kennzeichnungen', 'type' => 'font', 'var' => '--f-font-mono', 'default' => 'system-mono',
                'help' => 'Für Code und – wenn unten gewählt – Dachzeilen, Etiketten und Zahlen. Die Datei lädt nur, wenn sie auf der Seite gebraucht wird.'],
            ['name' => 'label_font', 'label' => 'Dachzeilen und Etiketten', 'type' => 'choice', 'var' => '--f-font-label', 'default' => 'body',
                'options' => ['body' => 'Wie Fließtext', 'head' => 'Wie Überschriften', 'mono' => 'Monospace (technisch)'],
                'values' => ['body' => 'var(--f-font)', 'head' => 'var(--f-font-head)', 'mono' => 'var(--f-font-mono)']],
            ['name' => 'fs_min', 'label' => 'Grundschrift auf kleinen Bildschirmen (px)', 'type' => 'range', 'var' => '--f-fs-min', 'unit' => '',
                'min' => 14, 'max' => 19, 'step' => 0.5, 'default' => 16, 'help' => 'Bezogen auf die Standardgröße des Browsers (16 px); Besucher können weiter zoomen.'],
            ['name' => 'fs_max', 'label' => 'Grundschrift auf großen Bildschirmen (px)', 'type' => 'range', 'var' => '--f-fs-max', 'unit' => '',
                'min' => 15, 'max' => 23, 'step' => 0.5, 'default' => 18.5],
            ['name' => 'ratio', 'label' => 'Verhältnis der Schriftstufen', 'type' => 'range', 'var' => '--f-ratio', 'unit' => '',
                'min' => 1.125, 'max' => 1.6, 'step' => 0.025, 'default' => 1.25,
                'help' => '1,125 = ruhig (Texte, Behörden) · 1,25 = ausgewogen · 1,414 = kräftig · 1,5+ = plakativ (Agentur, Kultur). Auf kleinen Bildschirmen automatisch flacher.'],
            ['name' => 'vw_min', 'label' => 'Fließend ab Bildschirmbreite (px)', 'type' => 'range', 'var' => '--f-vw-min', 'unit' => '',
                'min' => 320, 'max' => 480, 'step' => 10, 'default' => 360, 'help' => 'Unterhalb gelten die kleinen Werte.'],
            ['name' => 'vw_max', 'label' => 'Fließend bis Bildschirmbreite (px)', 'type' => 'range', 'var' => '--f-vw-max', 'unit' => '',
                'min' => 960, 'max' => 1800, 'step' => 20, 'default' => 1280, 'help' => 'Oberhalb gelten die großen Werte.'],
            ['name' => 'heading_weight', 'label' => 'Stärke der Überschriften', 'type' => 'range', 'var' => '--f-hw', 'unit' => '',
                'min' => 300, 'max' => 900, 'step' => 50, 'default' => 650, 'help' => 'Stufenlos bei variablen Schriften (Inter, Bricolage, Fraunces …).'],
            ['name' => 'heading_case', 'label' => 'Schreibweise der Überschriften', 'type' => 'choice', 'class' => 'hcase-{value}', 'default' => 'normal',
                'options' => ['normal' => 'Normal', 'upper' => 'VERSALIEN (z. B. mit schmaler Schrift)', 'smallcaps' => 'Kapitälchen']],
            ['name' => 'emphasis', 'label' => 'Betonung *Wort* in Überschriften', 'type' => 'choice', 'class' => 'em-{value}', 'default' => 'accent',
                'options' => ['accent' => 'Akzentfarbe (bei Serifen kursiv)', 'italic' => 'Kursiv', 'bold' => 'Fett', 'marker' => 'Textmarker (Hervorhebungsfarbe)', 'underline' => 'Unterstrichen in Akzentfarbe', 'gradient' => 'Farbverlauf beider Markenfarben', 'outline' => 'Konturschrift (nur Umriss)']],
            ['name' => 'links', 'label' => 'Links im Fließtext', 'type' => 'choice', 'class' => 'ln-{value}', 'default' => 'underline',
                'options' => ['underline' => 'Unterstrichen', 'accent' => 'Fett in Akzentfarbe, unterstrichen beim Zeigen', 'marker' => 'Getönte Linie, füllt sich beim Zeigen']],
            ['name' => 'heading_tracking', 'label' => 'Laufweite der Überschriften (1/100 em)', 'type' => 'range', 'var' => '--f-track', 'unit' => '',
                'min' => -6, 'max' => 3, 'step' => 0.5, 'default' => -2, 'help' => 'Negativ = enger (große Grotesk-Überschriften), 0 = normal (Serifen).'],
        ]],
        ['id' => 'form', 'label' => 'Form & Raum', 'tokens' => [
            ['name' => 'radius', 'label' => 'Eckenradius', 'type' => 'range', 'var' => '--f-radius', 'unit' => 'px', 'min' => 0, 'max' => 32, 'step' => 1, 'default' => 10],
            ['name' => 'buttons', 'label' => 'Buttons', 'type' => 'choice', 'class' => 'btn-{value}', 'default' => 'solid', 'preview' => 'radius',
                'options' => ['solid' => 'Gefüllt', 'pill' => 'Gefüllt, rund (Pille)', 'outline' => 'Kontur', 'soft' => 'Getönt', 'sharp' => 'Eckig mit Pfeil',
                    'gradient' => 'Farbverlauf mit Leuchten', 'brutal' => 'Neo-Brutalismus (Kontur, harter Schatten)'],
                'values' => ['solid' => '8px', 'pill' => '999px', 'outline' => '8px', 'soft' => '12px', 'sharp' => '0', 'gradient' => '999px', 'brutal' => '6px']],
            ['name' => 'cards', 'label' => 'Karten', 'type' => 'choice', 'class' => 'cards-{value}', 'default' => 'outlined',
                'options' => ['flat' => 'Fläche (ohne Rahmen)', 'outlined' => 'Mit Rahmen', 'elevated' => 'Mit Schatten', 'glass' => 'Glas (durchscheinend)',
                    'tinted' => 'Getönt (Akzent hell)', 'gradient' => 'Verlaufsrahmen (Markenfarben)', 'brutal' => 'Neo-Brutalismus (Kontur, harter Schatten)']],
            ['name' => 'shadow', 'label' => 'Schatten', 'type' => 'choice', 'var' => '--f-shadow', 'default' => 'soft',
                'options' => ['none' => 'Keine', 'soft' => 'Weich', 'crisp' => 'Knapp (grafisch)', 'layered' => 'Tief, mehrschichtig'],
                'values' => [
                    'none' => 'none',
                    'soft' => '0 1px 2px var(--f-sh1),0 12px 32px -12px var(--f-sh2)',
                    'crisp' => '4px 4px 0 var(--f-ink)',
                    'layered' => '0 1px 1px var(--f-sh1),0 4px 8px -2px var(--f-sh1),0 24px 48px -16px var(--f-sh2)',
                ]],
            ['name' => 'density', 'label' => 'Dichte (Innenabstände)', 'type' => 'choice', 'var' => '--f-density', 'default' => 'normal',
                'options' => ['compact' => 'Kompakt', 'normal' => 'Normal', 'relaxed' => 'Luftig'], 'values' => ['compact' => '.8', 'normal' => '1', 'relaxed' => '1.2']],
            ['name' => 'space', 'label' => 'Abstand zwischen Abschnitten', 'type' => 'choice', 'var' => '--f-space', 'default' => 'normal',
                'options' => ['compact' => 'Kompakt', 'normal' => 'Normal', 'airy' => 'Großzügig'], 'values' => ['compact' => '.72', 'normal' => '1', 'airy' => '1.32']],
            ['name' => 'wrap', 'label' => 'Maximale Inhaltsbreite (rem)', 'type' => 'range', 'var' => '--f-wrap', 'unit' => 'rem', 'min' => 56, 'max' => 100, 'step' => 2, 'default' => 76,
                'help' => '1 rem = 16 px. Breite Werte für Bildwelten, schmale für textlastige Websites.'],
            ['name' => 'eyebrow', 'label' => 'Dachzeilen', 'type' => 'choice', 'class' => 'eb-{value}', 'default' => 'line',
                'options' => ['line' => 'Mit Strich', 'pill' => 'Als Etikett', 'dot' => 'Mit Punkt', 'plain' => 'Schlicht']],
            ['name' => 'eyebrow_case', 'label' => 'Schreibweise der Dachzeilen', 'type' => 'choice', 'class' => 'ebc-{value}', 'default' => 'auto',
                'options' => ['auto' => 'Wie der Stil', 'upper' => 'Großbuchstaben (gesperrt)', 'normal' => 'Normal', 'smallcaps' => 'Kapitälchen'],
                'help' => '„Wie der Stil“: Etikett in normaler Schreibweise, die übrigen in Großbuchstaben.'],
            ['name' => 'images', 'label' => 'Ecken der Bilder', 'type' => 'choice', 'class' => 'img-{value}', 'default' => 'radius',
                'options' => ['radius' => 'Wie Eckenradius', 'sharp' => 'Eckig', 'round' => 'Stark gerundet', 'arch' => 'Bogen oben (Torbogen)']],
            ['name' => 'image_fx', 'label' => 'Bildwirkung', 'type' => 'choice', 'class' => 'imgfx-{value}', 'default' => 'none',
                'options' => ['none' => 'Natürlich', 'mono' => 'Schwarzweiß, farbig beim Zeigen', 'tint' => 'In Akzentfarbe getönt, farbig beim Zeigen', 'frame' => 'Versetzter Rahmen in Akzentfarbe']],
            ['name' => 'hover', 'label' => 'Verlinkte Karten beim Zeigen', 'type' => 'choice', 'class' => 'hov-{value}', 'default' => 'lift',
                'options' => ['lift' => 'Leicht anheben', 'glow' => 'Rahmen in Akzentfarbe', 'zoom' => 'Bild zoomt langsam', 'none' => 'Ruhig (nur Mauszeiger)']],
            ['name' => 'icons', 'label' => 'Symbole (z. B. Merkmale)', 'type' => 'choice', 'class' => 'ic-{value}', 'default' => 'soft',
                'options' => ['soft' => 'Getönte Fläche', 'circle' => 'Kreis', 'outline' => 'Kontur', 'plain' => 'Ohne Fläche']],
            ['name' => 'icon_pos', 'label' => 'Anordnung der Symbole', 'type' => 'choice', 'class' => 'icp-{value}', 'default' => 'top',
                'options' => ['top' => 'Über dem Titel', 'inline' => 'In einer Zeile mit dem Titel', 'side' => 'Links neben dem Text']],
            ['name' => 'dividers', 'label' => 'Übergang zwischen Abschnitten', 'type' => 'choice', 'class' => 'div-{value}', 'default' => 'none',
                'options' => ['none' => 'Gerade Kante', 'wave' => 'Welle', 'slant' => 'Schräg', 'curve' => 'Bogen', 'zigzag' => 'Zickzack'],
                'help' => 'Sichtbar, wo zwei Abschnitte mit verschiedenen Hintergründen aufeinandertreffen.'],
        ]],
        ['id' => 'navigation', 'label' => 'Kopf & Fuß', 'tokens' => [
            ['name' => 'header', 'markup' => true, 'label' => 'Kopfbereich', 'type' => 'choice', 'class' => 'hdr-{value}', 'default' => 'inline', 'preview' => 'nav',
                'thumbs' => ['inline' => 'left', 'centered' => 'center', 'split' => 'split', 'floating' => 'floating', 'rail' => 'sidebar', 'sidebar' => 'sidebar', 'minimal' => 'left'],
                'options' => [
                    'inline' => 'Leiste – Logo links, Menü rechts',
                    'centered' => 'Zentriert – Logo über dem Menü',
                    'split' => 'Geteilt – Menü in der Mitte',
                    'floating' => 'Schwebend – abgerundete Leiste',
                    'rail' => 'Seitenleiste – Menü links (breite Fenster)',
                    'sidebar' => 'Seitenleiste mit Menübaum – großes Logo, Unterseiten, Suche, Kontakt',
                    'minimal' => 'Minimal – nur Logo und Menü-Schaltfläche',
                ],
                'help' => 'Das Menü steht in der Leiste, solange es hineinpasst – sonst öffnet eine Menü-Schaltfläche ein Seitenblatt. Ganz ohne feste Bildschirmbreiten.'],
            ['name' => 'logo_size', 'markup' => true, 'label' => 'Größe von Logo bzw. Wortmarke', 'type' => 'choice', 'class' => 'logo-{value}', 'default' => 'normal',
                'options' => ['normal' => 'Normal', 'large' => 'Groß', 'xl' => 'Sehr groß'],
                'help' => 'Gilt für alle Kopfbereiche. In der „Seitenleiste mit Menübaum“ steht das Logo groß oben – auch quadratische oder hohe Logos passen.'],
            ['name' => 'header_height', 'label' => 'Höhe des Kopfbereichs', 'type' => 'choice', 'class' => 'hh-{value}', 'default' => 'auto',
                'options' => ['auto' => 'Normal', 'tall' => 'Hoch – Logo größer', 'xtall' => 'Sehr hoch – Logo groß'],
                'help' => 'Für große Logos. Beim Scrollen und auf schmalen Bildschirmen wird der Kopf mit weichem Übergang wieder normal hoch. Nicht bei den Seitenleisten.'],
            ['name' => 'nav_parent', 'markup' => true, 'label' => 'Menüpunkte mit Unterseiten', 'type' => 'choice', 'class' => 'np-{value}', 'default' => 'split',
                'options' => ['split' => 'Link + Pfeil – der Menüpunkt öffnet seine Seite, der Pfeil die Unterseiten', 'hover' => 'Link + Pfeil, Unterseiten öffnen auch beim Überfahren mit der Maus', 'overview' => 'Klick öffnet die Unterseiten, Eintrag „Übersicht“ führt zur Seite'],
                'help' => 'Gilt für das Menü in der Leiste und im Seitenblatt (Telefon). „Link + Pfeil“ kommt ohne zusätzlichen Eintrag „Übersicht“ aus.'],
            ['name' => 'nav_levels', 'markup' => true, 'label' => 'Dritte Menüebene im Aufklappmenü', 'type' => 'choice', 'class' => 'nv-{value}', 'default' => 'accordion',
                'options' => ['accordion' => 'Akkordeon – Pfeil klappt Unterseiten auf (Standard)', 'slide' => 'Slide – Pfeil schiebt die Unterseiten ins Menü, „‹ zurück“',
                    'indent' => 'Eingerückt – immer sichtbar, mit Linie', 'groups' => 'Gruppiert – zweite Ebene als Zwischenüberschrift, dritte darunter'],
                'help' => 'Wie Unterseiten von Unterseiten im Aufklappmenü der Leiste erscheinen.'],
            ['name' => 'side_width', 'label' => 'Breite der Seitenleiste (Menübaum)', 'type' => 'choice', 'class' => 'sw-{value}', 'default' => 'normal',
                'options' => ['narrow' => 'Schmal', 'normal' => 'Normal', 'wide' => 'Breit (große Logos, lange Menüpunkte)'],
                'help' => 'Nur bei „Seitenleiste mit Menübaum“. Auf schmalen Bildschirmen wird daraus eine Leiste oben mit Menü-Schaltfläche.'],
            ['name' => 'side_banner', 'markup' => true, 'label' => 'Kopfbanner über der Seitenleiste (Menübaum)', 'type' => 'choice', 'class' => 'sb-{value}', 'default' => 'off',
                'options' => ['off' => 'Aus – Logo oben in der Seitenleiste', 'band' => 'Farbband – Logo, Claim und Button auf Farbe bzw. Verlauf', 'image' => 'Bild – Bannerbild in voller Breite, Logo darauf'],
                'help' => 'Nur bei „Seitenleiste mit Menübaum“: ein Kopf über die volle Breite auf jeder Seite, die Seitenleiste beginnt darunter. Farbe: „Hintergrund des Kopfbereichs“. Bild und Claim: Website → Darstellung bzw. Stammdaten. Auf Unterseiten etwas niedriger.'],
            ['name' => 'side_banner_height', 'label' => 'Höhe des Kopfbanners', 'type' => 'choice', 'class' => 'sbh-{value}', 'default' => 'normal',
                'options' => ['normal' => 'Normal', 'tall' => 'Hoch'], 'help' => 'Beim Bannerbild bestimmt das Bild selbst die Höhe (ganz gezeigt, ohne Beschnitt).'],
            ['name' => 'side_banner_overlay', 'label' => 'Bannerbild abdunkeln', 'type' => 'choice', 'class' => 'sbo-{value}', 'default' => 'none',
                'options' => ['none' => 'Nein – Logo und Claim auf heller Fläche', 'soft' => 'Leicht abdunkeln, Schrift weiß', 'strong' => 'Stark abdunkeln, Schrift weiß']],
            ['name' => 'side_tree', 'label' => 'Unterseiten in der Seitenleiste', 'type' => 'choice', 'class' => 'st-{value}', 'default' => 'branch',
                'options' => ['branch' => 'Aktueller Zweig offen, übrige aufklappbar', 'open' => 'Immer alle sichtbar']],
            ['name' => 'header_sticky', 'label' => 'Kopfbereich beim Scrollen sichtbar halten', 'type' => 'bool', 'class' => 'hdr-sticky', 'default' => true],
            ['name' => 'header_bg', 'label' => 'Hintergrund des Kopfbereichs', 'type' => 'choice', 'class' => 'hbg-{value}', 'default' => 'page',
                'options' => ['page' => 'Wie die Seite (leicht durchscheinend)', 'surface' => 'Getönte Fläche', 'accent' => 'Akzentfarbe', 'secondary' => 'Zweite Markenfarbe', 'dark' => 'Dunkel', 'gradient' => 'Zarter Farbverlauf (Markenfarben)']],
            ['name' => 'nav_style', 'label' => 'Menüpunkte', 'type' => 'choice', 'class' => 'nl-{value}', 'default' => 'plain',
                'options' => ['plain' => 'Schlicht (Fläche beim Zeigen)', 'underline' => 'Unterstrichen', 'pill' => 'Pille (aktiver Punkt hinterlegt)', 'caps' => 'Versalien, gesperrt', 'dot' => 'Punkt unter dem aktiven Menüpunkt']],
            ['name' => 'topbar', 'markup' => true, 'label' => 'Infoleiste über dem Kopfbereich', 'type' => 'choice', 'class' => 'meta-{value}', 'default' => 'off',
                'options' => ['off' => 'Aus', 'dark' => 'Dunkel', 'accent' => 'Akzentfarbe', 'secondary' => 'Zweite Markenfarbe', 'surface' => 'Getönt'],
                'help' => 'Telefon, E-Mail und Social Media aus Website → Stammdaten, dazu ein kurzer Text (Website → „Text der Infoleiste“) – z. B. für Verbände, Praxen und Notdienste.'],
            ['name' => 'footer', 'markup' => true, 'label' => 'Fußbereich', 'type' => 'choice', 'class' => 'ft-{value}', 'default' => 'columns',
                'options' => ['columns' => 'Spalten (Kontakt, Seiten, Social)', 'simple' => 'Schlicht in einer Zeile', 'centered' => 'Zentriert (Logo, Seiten, Social untereinander)', 'statement' => 'Großer Schriftzug mit Handlungsaufruf']],
            ['name' => 'footer_bg', 'label' => 'Hintergrund des Fußbereichs', 'type' => 'choice', 'class' => 'fbg-{value}', 'default' => 'surface',
                'options' => ['surface' => 'Getönte Fläche', 'page' => 'Wie die Seite', 'dark' => 'Dunkel', 'accent' => 'Akzentfarbe', 'secondary' => 'Zweite Markenfarbe']],
            ['name' => 'footer_line', 'label' => 'Linie über dem Fußbereich', 'type' => 'choice', 'class' => 'fl-{value}', 'default' => 'auto',
                'options' => ['auto' => 'Wie Farbwirkung (feine Linie, bei „Farbenfroh“ Farbband)', 'none' => 'Keine Linie', 'line' => 'Linie', 'shadow' => 'Linie mit Schatten nach unten',
                    'emboss' => 'Geprägte Linie', 'band' => 'Farbband (Markenfarben im Wechsel)']],
            ['name' => 'footer_line_color', 'label' => 'Farbe der Linie', 'type' => 'choice', 'class' => 'flc-{value}', 'default' => 'auto',
                'options' => ['auto' => 'Linienfarbe', 'accent' => 'Akzentfarbe', 'secondary' => 'Zweite Markenfarbe', 'ink' => 'Schriftfarbe', 'white' => 'Weiß'],
                'help' => 'Für „Linie“ und „Linie mit Schatten“. Das Farbband nutzt die Markenfarben.'],
            ['name' => 'footer_line_width', 'label' => 'Dicke der Linie', 'type' => 'choice', 'class' => 'flw-{value}', 'default' => 'auto',
                'options' => ['auto' => 'Standard', 'w1' => 'Haarlinie (1 px)', 'w2' => '2 px', 'w4' => '4 px', 'w6' => '6 px', 'w10' => '10 px']],
            ['name' => 'pagebg', 'label' => 'Seitenhintergrund', 'type' => 'choice', 'class' => 'pagebg-{value}', 'default' => 'plain',
                'options' => ['plain' => 'Einfarbig', 'grid' => 'Feines Raster', 'dots' => 'Punktraster', 'glow' => 'Sanfter Farbverlauf oben',
                    'aurora' => 'Aurora (weicher Farbschleier)', 'noise' => 'Feine Körnung (Grain)', 'lines' => 'Senkrechte Rasterlinien']],
            ['name' => 'sections', 'label' => 'Farbige Abschnitte', 'type' => 'choice', 'class' => 'secs-{value}', 'default' => 'flush',
                'options' => ['flush' => 'Über die volle Breite', 'inset' => 'Als abgerundete Flächen mit Rand (modern, „Karten-Look“)'],
                'help' => 'Betrifft Abschnitte mit Hintergrund (getönt, Akzent, dunkel …). Abschnittsübergänge (Welle, Schräg) entfallen dabei.'],
            ['name' => 'progress', 'label' => 'Lesefortschritt als Linie oben', 'type' => 'bool', 'class' => 'has-progress', 'default' => false,
                'help' => 'Dünne Linie in Akzentfarbe am oberen Rand, wächst beim Scrollen – ohne Skript, nur in Browsern mit Scroll-Animationen.'],
            ['name' => 'totop', 'markup' => true, 'label' => 'Schaltfläche „Nach oben“', 'type' => 'bool', 'class' => 'has-totop', 'default' => false,
                'help' => 'Erscheint unten rechts, sobald weit genug gescrollt wurde.'],
        ]],
        // Kopfbereich-Aktionen (Core\HeaderActions) – Standard des Kits: Suchfeld in der Leiste + Textlink
        \Core\HeaderActions::designGroup(['ha_cta_style' => 'link', 'ha_search' => 'inline']),
        ['id' => 'modus', 'label' => 'Bewegung & Farbschema', 'tokens' => [
            ['name' => 'motion', 'label' => 'Dezente Animationen beim Scrollen (Einblenden, Laufband)', 'type' => 'bool', 'class' => 'has-motion', 'default' => true,
                'help' => 'Besucher mit „Bewegung reduzieren“ sehen nie Animationen – unabhängig von dieser Einstellung.'],
            ['name' => 'motion_style', 'label' => 'Art des Einblendens', 'type' => 'choice', 'class' => 'mo-{value}', 'default' => 'rise',
                'options' => ['rise' => 'Aufsteigen', 'fade' => 'Nur Blende', 'scale' => 'Leicht wachsen', 'blur' => 'Aus der Unschärfe', 'clip' => 'Aufdecken von unten', 'slide' => 'Seitlich hereingleiten']],
            ['name' => 'dark', 'label' => 'Dunkles Farbschema, wenn im Gerät der Besucher eingestellt', 'type' => 'bool', 'class' => 'has-dark', 'default' => true],
        ]],
    ],

    // Schriften: 'fontsource' = installiert der Schriften-Manager (Core\Fonts, fonts:sync; selbst gehostet, ohne externe Anfragen) – variable Schriften: ein Download für alle Stärken
    'fonts' => [
        'inter' => ['label' => 'Inter (Grotesk, neutral · variabel)', 'stack' => 'Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,sans-serif', 'fontsource' => 'inter'],
        'instrument-sans' => ['label' => 'Instrument Sans (Grotesk, freundlich · variabel)', 'stack' => '"Instrument Sans",ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif', 'fontsource' => 'instrument-sans'],
        'bricolage' => ['label' => 'Bricolage Grotesque (markant, eigenwillig · variabel)', 'stack' => '"Bricolage Grotesque",ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif', 'fontsource' => 'bricolage-grotesque'],
        'dm-sans' => ['label' => 'DM Sans (geometrisch, rund · variabel)', 'stack' => '"DM Sans",ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif', 'fontsource' => 'dm-sans'],
        'space-grotesk' => ['label' => 'Space Grotesk (technisch · variabel)', 'stack' => '"Space Grotesk",ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif', 'fontsource' => 'space-grotesk'],
        'fraunces' => ['label' => 'Fraunces (Serifen, weich, optische Größen · variabel)', 'stack' => 'Fraunces,ui-serif,Georgia,Cambria,serif', 'fontsource' => 'fraunces', 'styles' => ['normal', 'italic'], 'axis' => 'opsz'],
        'newsreader' => ['label' => 'Newsreader (Serifen, sachlich · variabel)', 'stack' => 'Newsreader,ui-serif,Georgia,Cambria,serif', 'fontsource' => 'newsreader', 'styles' => ['normal', 'italic']],
        'instrument-serif' => ['label' => 'Instrument Serif (Display-Serife, nur große Überschriften)', 'stack' => '"Instrument Serif",ui-serif,Georgia,Cambria,serif', 'fontsource' => 'instrument-serif', 'styles' => ['normal', 'italic']],
        'open-sans' => ['label' => 'Open Sans (Grotesk, sehr gut lesbar · variabel)', 'stack' => '"Open Sans",ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,sans-serif', 'fontsource' => 'open-sans', 'styles' => ['normal', 'italic']],
        'source-sans' => ['label' => 'Source Sans 3 (Grotesk, sachlich · variabel)', 'stack' => '"Source Sans 3",ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif', 'fontsource' => 'source-sans-3', 'styles' => ['normal', 'italic']],
        'lato' => ['label' => 'Lato (Grotesk, warm · 300/400/700/900)', 'stack' => 'Lato,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif', 'fontsource' => 'lato', 'styles' => ['normal', 'italic'], 'variable' => false, 'weights' => [300, 400, 700, 900]],
        'roboto' => ['label' => 'Roboto (Grotesk, technisch-neutral · variabel)', 'stack' => 'Roboto,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif', 'fontsource' => 'roboto', 'styles' => ['normal', 'italic']],
        'roboto-condensed' => ['label' => 'Roboto Condensed (schmal, für Überschriften · variabel)', 'stack' => '"Roboto Condensed","Arial Narrow",ui-sans-serif,system-ui,sans-serif', 'fontsource' => 'roboto-condensed', 'styles' => ['normal', 'italic']],
        'pt-sans' => ['label' => 'PT Sans (Grotesk, amtlich · 400/700)', 'stack' => '"PT Sans",ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif', 'fontsource' => 'pt-sans', 'styles' => ['normal', 'italic'], 'variable' => false, 'weights' => [400, 700]],
        'poppins' => ['label' => 'Poppins (geometrisch, rund · 300–800)', 'stack' => 'Poppins,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif', 'fontsource' => 'poppins', 'styles' => ['normal', 'italic'], 'variable' => false, 'weights' => [300, 400, 500, 600, 700, 800]],
        'manrope' => ['label' => 'Manrope (geometrisch, modern · variabel)', 'stack' => 'Manrope,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif', 'fontsource' => 'manrope'],
        'atkinson' => ['label' => 'Atkinson Hyperlegible Next (barrierearm, leicht unterscheidbare Zeichen · variabel)', 'stack' => '"Atkinson Hyperlegible Next","Atkinson Hyperlegible",ui-sans-serif,system-ui,sans-serif', 'fontsource' => 'atkinson-hyperlegible-next', 'styles' => ['normal', 'italic']],
        'nunito' => ['label' => 'Nunito (gerundet, freundlich · variabel)', 'stack' => 'Nunito,ui-rounded,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif', 'fontsource' => 'nunito', 'styles' => ['normal', 'italic']],
        'roboto-slab' => ['label' => 'Roboto Slab (Serifenbetont, robust · variabel)', 'stack' => '"Roboto Slab",ui-serif,Georgia,Cambria,serif', 'fontsource' => 'roboto-slab'],
        'jetbrains-mono' => ['label' => 'JetBrains Mono (Monospace · variabel)', 'stack' => '"JetBrains Mono",ui-monospace,SFMono-Regular,Menlo,Consolas,monospace', 'fontsource' => 'jetbrains-mono'],
        'system' => ['label' => 'Systemschrift (ohne Download)', 'stack' => 'ui-sans-serif,system-ui,-apple-system,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif'],
        'system-mono' => ['label' => 'System-Monospace (ohne Download)', 'stack' => 'ui-monospace,SFMono-Regular,Menlo,Consolas,"Liberation Mono",monospace'],
    ],

    // Neun Vorlagen für unterschiedliche Projekte – alle hell und dunkel AA-geprüft (tools/contrast.php)
    'presets' => [
        'standard' => $preset('Fluid Standard', 'Neutral und klar: Indigo, Inter, ausgewogene Stufen – der Standard des Kits.',
            ['#4338CA', '#3730A3', '#FFFFFF', '#FDE68A', '#0B0D17', '#2B2F3A', '#565C6B', '#FFFFFF', '#F4F5F8', '#E2E4EB', '#0E1022'],
            ['#A5B4FC', '#C7D2FE', '#14123A', '#3A3470', '#F3F4F8', '#D2D5DE', '#9EA3B2', '#0B0C14', '#141621', '#272B3A', '#1A1D33'],
            $base),
        'kanzlei' => $preset('Kanzlei · Nachtblau & Serife', 'Seriös und ruhig: Newsreader-Überschriften, eckige Formen, zentrierter Kopf, flache Stufen.',
            ['#1D3A66', '#142B4D', '#FFFFFF', '#EDE3CC', '#0C1526', '#2A3242', '#565F70', '#FFFFFF', '#F5F4F0', '#E4E1D8', '#0F1F38'],
            ['#9BB8EA', '#BED0F2', '#0B1A33', '#3A3322', '#EEF2F8', '#CFD6E2', '#9AA4B5', '#0A0F18', '#121A27', '#253247', '#18263D'],
            ['font_body' => 'inter', 'font_head' => 'newsreader', 'ratio' => 1.2, 'fs_max' => 18, 'heading_weight' => 500, 'heading_tracking' => -1,
             'radius' => 2, 'buttons' => 'sharp', 'cards' => 'outlined', 'shadow' => 'none', 'space' => 'normal', 'wrap' => 72, 'eyebrow' => 'plain',
             'header' => 'centered', 'footer' => 'columns', 'pagebg' => 'plain'] + $base),
        'handwerk' => $preset('Handwerk · Terrakotta', 'Kräftig und nahbar: Bricolage Grotesque, runde Buttons, schwebender Kopf, Punktraster.',
            ['#A3380F', '#842C0A', '#FFFFFF', '#F6D46B', '#1E140E', '#3A2E25', '#63554A', '#FFFCF7', '#F6EEE3', '#E8DBC9', '#2A1B12'],
            ['#F4A57E', '#F8C3A6', '#2A1206', '#4A3A12', '#F8F1EA', '#E2D6C9', '#B2A291', '#15100C', '#211912', '#3A2D22', '#2B1F17'],
            ['font_body' => 'dm-sans', 'font_head' => 'bricolage', 'ratio' => 1.3, 'heading_weight' => 750, 'heading_tracking' => -3,
             'radius' => 16, 'buttons' => 'pill', 'cards' => 'flat', 'shadow' => 'soft', 'wrap' => 78, 'eyebrow' => 'pill',
             'header' => 'floating', 'footer' => 'statement', 'pagebg' => 'dots'] + $base),
        'praxis' => $preset('Praxis · Salbei', 'Beruhigend und freundlich: Salbeigrün, Instrument Sans, weiche Karten mit Schatten, sanfter Verlauf.',
            ['#2C6A5C', '#215347', '#FFFFFF', '#D5ECDD', '#0E1D19', '#2B3935', '#56655F', '#FFFFFF', '#F2F7F4', '#DEE8E3', '#0F2922'],
            ['#86D1BC', '#A9E0D0', '#06231B', '#1F3D33', '#EEF6F2', '#CCDCD5', '#96AAA2', '#0A110F', '#111B18', '#22322D', '#17302A'],
            ['font_body' => 'instrument-sans', 'font_head' => 'instrument-sans', 'ratio' => 1.2, 'fs_max' => 19, 'heading_weight' => 600, 'heading_tracking' => -1.5,
             'radius' => 20, 'buttons' => 'pill', 'cards' => 'elevated', 'shadow' => 'soft', 'density' => 'relaxed', 'eyebrow' => 'dot',
             'header' => 'inline', 'footer' => 'columns', 'pagebg' => 'glow'] + $base),
        'agentur' => $preset('Agentur · Kontrast', 'Laut und selbstbewusst: sehr große Stufen, Bricolage 800, Violett und Limette, Raster-Hintergrund.',
            ['#5B21D6', '#4A18B3', '#FFFFFF', '#D9F95B', '#0A0A0F', '#26262E', '#55555F', '#FFFFFF', '#F4F3F7', '#E3E1EA', '#120A26'],
            ['#C4AEFF', '#DACDFF', '#1A0B45', '#2F3A0C', '#F6F5FA', '#D6D4DE', '#A09EAB', '#09090D', '#13121A', '#2A2833', '#1E1438'],
            ['font_body' => 'inter', 'font_head' => 'bricolage', 'font_mono' => 'jetbrains-mono', 'label_font' => 'mono', 'ratio' => 1.45, 'fs_max' => 19, 'heading_weight' => 800, 'heading_tracking' => -4.5,
             'radius' => 24, 'buttons' => 'pill', 'cards' => 'outlined', 'shadow' => 'crisp', 'wrap' => 84, 'eyebrow' => 'pill',
             'header' => 'split', 'footer' => 'statement', 'pagebg' => 'grid'] + $base),
        'verein' => $preset('Verein · Frisch', 'Offen und fröhlich: Blau und Sonnengelb, DM Sans fett, Schatten-Karten, Etiketten.',
            ['#0B5CAD', '#084A8C', '#FFFFFF', '#FFD84A', '#0A1626', '#283445', '#566273', '#FFFFFF', '#F2F6FB', '#DCE5F0', '#0A2540'],
            ['#8CC2FF', '#B4D7FF', '#04203F', '#3F3510', '#EEF4FB', '#CFDAE7', '#98A7BA', '#09101A', '#111A26', '#233247', '#152B47'],
            ['font_body' => 'dm-sans', 'font_head' => 'dm-sans', 'ratio' => 1.28, 'heading_weight' => 800, 'heading_tracking' => -2.5,
             'radius' => 14, 'buttons' => 'solid', 'cards' => 'elevated', 'shadow' => 'layered', 'eyebrow' => 'pill',
             'header' => 'inline', 'footer' => 'columns', 'pagebg' => 'plain'] + $base),
        'restaurant' => $preset('Restaurant · Bordeaux & Creme', 'Warm und genussvoll: Fraunces mit optischen Größen, Cremetöne, Kontur-Buttons, zentrierter Kopf.',
            ['#8A1C32', '#6E1627', '#FFFFFF', '#EBCB98', '#26140F', '#3E2A24', '#6A544B', '#FBF6EE', '#F3E9DA', '#E6D6C0', '#2A1113'],
            ['#F0A2B0', '#F6C3CC', '#34060F', '#4A3515', '#F8EEE6', '#E5D5CA', '#B6A195', '#140D0B', '#1F1512', '#382823', '#2E1A1B'],
            ['font_body' => 'instrument-sans', 'font_head' => 'fraunces', 'ratio' => 1.333, 'fs_max' => 19, 'heading_weight' => 450, 'heading_tracking' => -1,
             'radius' => 6, 'buttons' => 'outline', 'cards' => 'flat', 'shadow' => 'none', 'space' => 'airy', 'wrap' => 72, 'eyebrow' => 'plain',
             'header' => 'centered', 'footer' => 'statement', 'pagebg' => 'plain'] + $base),
        'startup' => $preset('Tech-Startup · Nacht', 'Dunkel von Anfang an: Space Grotesk, Monospace-Etiketten, Glas-Karten, Raster und leuchtendes Blau.',
            ['#8BA6FF', '#B0C3FF', '#070A16', '#1E2B5C', '#F4F6FB', '#C9D0DD', '#939CAE', '#0A0C13', '#121622', '#242B3C', '#1B1542'],
            ['#8BA6FF', '#B0C3FF', '#070A16', '#1E2B5C', '#F4F6FB', '#C9D0DD', '#939CAE', '#07090F', '#10131D', '#212838', '#1B1542'],
            ['font_body' => 'inter', 'font_head' => 'space-grotesk', 'font_mono' => 'jetbrains-mono', 'label_font' => 'mono', 'ratio' => 1.333, 'heading_weight' => 600, 'heading_tracking' => -3,
             'radius' => 12, 'buttons' => 'pill', 'cards' => 'glass', 'shadow' => 'layered', 'wrap' => 80, 'eyebrow' => 'dot',
             'header' => 'floating', 'footer' => 'simple', 'pagebg' => 'grid'] + $base),
        'kultur' => $preset('Kultur · Museum', 'Plakativ und reduziert: Instrument Serif in sehr großen Stufen, Signalrot, keine Rundungen, Seitenleiste.',
            ['#C8102E', '#A00D25', '#FFFFFF', '#FF6A3D', '#0A0A0A', '#262626', '#595959', '#FFFFFF', '#F4F4F2', '#E2E2DE', '#111111'],
            ['#FF8A8A', '#FFB0B0', '#2A0508', '#5A1A0C', '#F6F6F4', '#D9D9D6', '#A3A3A0', '#0B0B0B', '#161616', '#2C2C2C', '#1F1F1F'],
            ['font_body' => 'inter', 'font_head' => 'instrument-serif', 'font_mono' => 'jetbrains-mono', 'label_font' => 'mono', 'ratio' => 1.5, 'fs_max' => 18, 'heading_weight' => 400, 'heading_tracking' => -1,
             'radius' => 0, 'buttons' => 'sharp', 'cards' => 'flat', 'shadow' => 'none', 'space' => 'airy', 'wrap' => 88, 'eyebrow' => 'plain',
             'header' => 'rail', 'footer' => 'statement', 'pagebg' => 'plain'] + $base),
        // Projektarten aus KLXM-Kundenprojekten (Sozialträger, Verbände, Gesundheit, Betriebe, Kommunen, Wissensportale)
        'sozial' => $preset('Sozialträger · Zwei Markenfarben', 'Warm und verlässlich: Orange und Grün als Markenfarben, Lato, Textmarker-Betonung, Infoleiste, dunkler Fuß.',
            ['#A93509', '#872A07', '#FFFFFF', '#FDE7C9', '#1C1917', '#3A3430', '#625A54', '#FFFFFF', '#F7F4F1', '#E7E1DB', '#1F2A1A'],
            ['#FDBA74', '#FED7AA', '#3B1406', '#5A3A12', '#F6F2EE', '#D9D2CC', '#A69D96', '#12100E', '#1C1916', '#33302C', '#1E2A1B'],
            ['secondary' => '#3F7D20', 'secondary@dark' => '#86EFAC', 'on_secondary' => '#FFFFFF', 'on_secondary@dark' => '#052E16', 'secondary_role' => 'all',
             'font_body' => 'lato', 'font_head' => 'lato', 'ratio' => 1.22, 'heading_weight' => 700, 'heading_tracking' => -1,
             'radius' => 8, 'buttons' => 'solid', 'cards' => 'elevated', 'shadow' => 'soft', 'eyebrow' => 'line', 'emphasis' => 'marker', 'icons' => 'circle',
             'header' => 'inline', 'nav_style' => 'underline', 'topbar' => 'secondary', 'footer' => 'columns', 'footer_bg' => 'dark', 'pagebg' => 'plain'] + $base),
        'verband' => $preset('Verband · Bordeaux & Versalien', 'Kräftig und organisiert: Roboto Condensed in Versalien, Kopf in Markenfarbe, Infoleiste, schräge Übergänge.',
            ['#880E4F', '#6B0B3E', '#FFFFFF', '#FFE2C6', '#1A1416', '#352C30', '#5E5458', '#FFFFFF', '#F6F2F3', '#E6DDE0', '#2A0A1B'],
            ['#F4A3C8', '#F9C6DC', '#3D0420', '#5A2A12', '#F7F1F3', '#DCD2D6', '#A99BA1', '#120D10', '#1C1519', '#35292F', '#2B0C1D'],
            ['secondary' => '#E8590C', 'secondary@dark' => '#FDBA74', 'on_secondary' => '#1A0A00', 'on_secondary@dark' => '#2A1203', 'secondary_role' => 'details',
             'font_body' => 'roboto', 'font_head' => 'roboto-condensed', 'ratio' => 1.3, 'heading_weight' => 700, 'heading_tracking' => 0, 'heading_case' => 'upper',
             'radius' => 4, 'buttons' => 'solid', 'cards' => 'outlined', 'shadow' => 'none', 'eyebrow' => 'plain', 'dividers' => 'slant',
             'header' => 'inline', 'header_bg' => 'accent', 'nav_style' => 'caps', 'topbar' => 'dark', 'footer' => 'columns', 'footer_bg' => 'dark', 'pagebg' => 'plain'] + $base),
        'gesundheit' => $preset('Gesundheit · Klar & barrierearm', 'Gut lesbar für alle: Atkinson Hyperlegible, größere Grundschrift, ruhige Stufen, runde Bilder, deutliche Links.',
            ['#00618E', '#004E73', '#FFFFFF', '#D7F0FB', '#0B1B24', '#22333D', '#4D5E68', '#FFFFFF', '#F2F7FA', '#D9E6EE', '#0A2A3B'],
            ['#7CC8F0', '#A8DCF6', '#032536', '#13405A', '#EEF6FA', '#CFDFE8', '#97ABB7', '#0A1218', '#111C23', '#22323C', '#0F2B3A'],
            ['secondary' => '#2E7D32', 'secondary@dark' => '#86D98B', 'on_secondary' => '#FFFFFF', 'on_secondary@dark' => '#052E0F', 'secondary_role' => 'details',
             'font_body' => 'atkinson', 'font_head' => 'atkinson', 'fs_min' => 17, 'fs_max' => 19.5, 'ratio' => 1.2, 'heading_weight' => 700, 'heading_tracking' => -0.5,
             'radius' => 12, 'buttons' => 'solid', 'cards' => 'outlined', 'shadow' => 'soft', 'eyebrow' => 'dot', 'emphasis' => 'underline', 'images' => 'round', 'icons' => 'circle', 'icon_pos' => 'side', 'hover' => 'glow',
             'header' => 'inline', 'nav_style' => 'pill', 'topbar' => 'surface', 'footer' => 'columns', 'footer_bg' => 'surface', 'pagebg' => 'plain'] + $base),
        'betrieb' => $preset('Betrieb & Notdienst · Sachlich', 'Klar und robust: Roboto mit Roboto Slab, eckige Formen, dunkler Kopf, Infoleiste für Notdienst und Telefon.',
            ['#B91C1C', '#991B1B', '#FFFFFF', '#FDE68A', '#111827', '#27303D', '#4B5563', '#FFFFFF', '#F3F4F6', '#E5E7EB', '#111827'],
            ['#FCA5A5', '#FECACA', '#450A0A', '#4A3B0C', '#F3F4F6', '#D1D5DB', '#9CA3AF', '#0B0F17', '#131923', '#283040', '#172030'],
            ['secondary' => '#374151', 'secondary@dark' => '#CBD5E1', 'on_secondary' => '#FFFFFF', 'on_secondary@dark' => '#0F172A', 'secondary_role' => 'sections',
             'font_body' => 'roboto', 'font_head' => 'roboto-slab', 'ratio' => 1.25, 'heading_weight' => 700, 'heading_tracking' => -1,
             'radius' => 2, 'buttons' => 'sharp', 'cards' => 'outlined', 'shadow' => 'none', 'eyebrow' => 'line', 'icons' => 'outline', 'icon_pos' => 'inline', 'images' => 'sharp',
             'header' => 'inline', 'header_bg' => 'dark', 'nav_style' => 'caps', 'topbar' => 'accent', 'footer' => 'columns', 'footer_bg' => 'dark', 'pagebg' => 'plain'] + $base),
        'kommune' => $preset('Kommune & Portal · Freundlich', 'Einladend und bunt: Poppins, Violett und Petrol, runde Formen, Wellen zwischen den Abschnitten, zentrierter Fuß.',
            ['#6D28D9', '#5B21B6', '#FFFFFF', '#FDE68A', '#1E1B2E', '#37344A', '#5E5A73', '#FFFFFF', '#F6F4FB', '#E6E2F0', '#24124A'],
            ['#C4B5FD', '#DDD6FE', '#2E1065', '#4A3B0C', '#F5F3FF', '#DAD6EA', '#A6A1BC', '#0F0D18', '#171423', '#2C2840', '#241848'],
            ['secondary' => '#0E7490', 'secondary@dark' => '#67E8F9', 'on_secondary' => '#FFFFFF', 'on_secondary@dark' => '#083344', 'secondary_role' => 'all',
             'font_body' => 'poppins', 'font_head' => 'poppins', 'ratio' => 1.25, 'heading_weight' => 700, 'heading_tracking' => -1.5,
             'radius' => 18, 'buttons' => 'pill', 'cards' => 'elevated', 'shadow' => 'soft', 'eyebrow' => 'pill', 'emphasis' => 'marker', 'images' => 'round', 'icons' => 'circle', 'dividers' => 'wave',
             'header' => 'inline', 'nav_style' => 'pill', 'footer' => 'centered', 'footer_bg' => 'secondary', 'pagebg' => 'plain'] + $base),
        'wissen' => $preset('Wissen & Kampagne · Dunkel', 'Erzählend und atmosphärisch: dunkel von Anfang an, Manrope, Glas-Karten, sanfter Verlauf, Betonung im Farbverlauf.',
            ['#86EFAC', '#BBF7D0', '#052E16', '#14532D', '#F2F5F3', '#CAD3CD', '#93A098', '#0B100D', '#121A15', '#22302A', '#0F1F17'],
            ['#86EFAC', '#BBF7D0', '#052E16', '#14532D', '#F2F5F3', '#CAD3CD', '#93A098', '#090D0B', '#101712', '#1F2B25', '#0F1F17'],
            ['secondary' => '#FBBF24', 'secondary@dark' => '#FBBF24', 'on_secondary' => '#1C1402', 'on_secondary@dark' => '#1C1402', 'secondary_role' => 'details',
             'font_body' => 'source-sans', 'font_head' => 'manrope', 'ratio' => 1.333, 'heading_weight' => 800, 'heading_tracking' => -2.5,
             'radius' => 14, 'buttons' => 'pill', 'cards' => 'glass', 'shadow' => 'layered', 'eyebrow' => 'dot', 'emphasis' => 'gradient', 'motion_style' => 'blur', 'wrap' => 80,
             'header' => 'floating', 'footer' => 'statement', 'footer_bg' => 'page', 'pagebg' => 'glow'] + $base),
        // Netzwerke, Bildung, Verbände mit vielen Mitgliedern: Seitenleiste mit Menübaum, großes Logo, fünf Farben im Wechsel
        'netzwerk' => $preset('Netzwerk & Bildung · Farbenfroh mit Seitenleiste', 'Lebendig und gut sortiert: Kopfbanner mit großem Logo, darunter Seitenleiste mit Menübaum, fünf Farben im Wechsel, Nunito, runde Formen – für Netzwerke, Bildungsträger und Verbände.',
            ['#B23A0B', '#8F2E09', '#FFFFFF', '#FED7AA', '#1C1917', '#3A302A', '#665950', '#FFFBF6', '#FFF1E4', '#F0DFCF', '#2A1A12'],
            ['#FDBA74', '#FED7AA', '#3B1406', '#5A3A12', '#FBF4EE', '#E2D7CE', '#AE9F94', '#14100D', '#1E1814', '#3A2F28', '#2A1D16'],
            ['secondary' => '#15803D', 'secondary@dark' => '#86EFAC', 'on_secondary' => '#FFFFFF', 'on_secondary@dark' => '#052E16', 'secondary_role' => 'sections',
             'color3' => '#7C3AED', 'color3@dark' => '#C4B5FD', 'color4' => '#DB2777', 'color4@dark' => '#F9A8D4', 'color5' => '#2563EB', 'color5@dark' => '#93C5FD',
             'palette' => 'colorful',
             'font_body' => 'nunito', 'font_head' => 'nunito', 'ratio' => 1.25, 'fs_max' => 19, 'heading_weight' => 800, 'heading_tracking' => -1.5,
             'radius' => 18, 'buttons' => 'pill', 'cards' => 'elevated', 'shadow' => 'soft', 'eyebrow' => 'pill', 'emphasis' => 'marker', 'icons' => 'circle', 'wrap' => 72,
             'header' => 'sidebar', 'header_bg' => 'gradient', 'logo_size' => 'xl', 'side_width' => 'normal', 'side_tree' => 'branch', 'side_banner' => 'band', 'side_banner_height' => 'normal', 'nav_style' => 'pill',
             'footer' => 'columns', 'footer_bg' => 'surface', 'pagebg' => 'plain'] + $base),
        // Farben aus „Fluid Standard“ bzw. „Agentur“ (AA-geprüft) – neu sind Formen, Hintergrund und Bewegung
        'aurora' => $preset('Software & Produkt · Aurora', 'Modern und leicht: Manrope, Farbschleier im Hintergrund, Buttons mit Verlauf, Karten mit Verlaufsrahmen, farbige Abschnitte als Flächen, Lesefortschritt.',
            ['#4338CA', '#3730A3', '#FFFFFF', '#FDE68A', '#0B0D17', '#2B2F3A', '#565C6B', '#FFFFFF', '#F4F5F8', '#E2E4EB', '#0E1022'],
            ['#A5B4FC', '#C7D2FE', '#14123A', '#3A3470', '#F3F4F8', '#D2D5DE', '#9EA3B2', '#0B0C14', '#141621', '#272B3A', '#1A1D33'],
            ['secondary' => '#0F766E', 'secondary@dark' => '#5EEAD4', 'on_secondary' => '#FFFFFF', 'on_secondary@dark' => '#042F2E',
             'font_body' => 'manrope', 'font_head' => 'manrope', 'ratio' => 1.3, 'fs_max' => 18, 'heading_weight' => 750, 'heading_tracking' => -3,
             'radius' => 16, 'buttons' => 'gradient', 'cards' => 'gradient', 'shadow' => 'soft', 'eyebrow' => 'pill', 'emphasis' => 'gradient', 'wrap' => 76,
             'hover' => 'zoom', 'nav_style' => 'dot', 'motion_style' => 'clip', 'sections' => 'inset', 'progress' => true, 'totop' => true,
             'header' => 'floating', 'footer' => 'columns', 'footer_line' => 'band', 'footer_line_width' => 'w2', 'pagebg' => 'aurora'] + $base),
        'brutal' => $preset('Studio · Neo-Brutalismus', 'Plakativ und verspielt: Space Grotesk, kräftige Konturen mit harten Schatten, Konturschrift für Betonungen, Körnung, Farbband über dem Fuß.',
            ['#5B21D6', '#4A18B3', '#FFFFFF', '#D9F95B', '#0A0A0F', '#26262E', '#55555F', '#FFFFFF', '#F4F3F7', '#E3E1EA', '#120A26'],
            ['#C4AEFF', '#DACDFF', '#1A0B45', '#2F3A0C', '#F6F5FA', '#D6D4DE', '#A09EAB', '#09090D', '#13121A', '#2A2833', '#1E1438'],
            ['font_body' => 'space-grotesk', 'font_head' => 'space-grotesk', 'font_mono' => 'jetbrains-mono', 'label_font' => 'mono', 'ratio' => 1.4, 'fs_max' => 19, 'heading_weight' => 700, 'heading_tracking' => -2.5,
             'radius' => 6, 'buttons' => 'brutal', 'cards' => 'brutal', 'shadow' => 'crisp', 'eyebrow' => 'pill', 'emphasis' => 'outline', 'wrap' => 80,
             'nav_style' => 'caps', 'motion_style' => 'slide', 'totop' => true,
             'header' => 'inline', 'footer' => 'statement', 'footer_line' => 'band', 'footer_line_width' => 'w6', 'pagebg' => 'noise'] + $base),
    ],

    // Dunkle Werte bei „Dunkles Farbschema“ (Klasse has-dark) und Geräte-Einstellung; Vorschau im Editor setzt is-dark
    'dark' => ['media' => '(prefers-color-scheme: dark)', 'scope' => 'html.has-dark', 'force' => 'is-dark'],

    // Musterseite für die Vorschau im Editor (Showcase, siehe tools/demo.php)
    'sample' => 'showcase',
];
