<?php
/**
 * Kern-Blöcke, die jedes Theme erhält (abschaltbar mit 'core_blocks' => false in theme.php).
 * Ein Theme kann die Ausgabe überschreiben: kits/{name}/blocks/{typ}.php und assets/css/data.css.
 */
return [
    'data_list' => [
        'label' => 'Datenliste', 'icon' => 'list-bullets', 'group' => 'Daten',
        'help' => 'Gibt Einträge einer Datentabelle aus (z. B. Aktuelles, Team, Produkte) – mit Feldauswahl, Filter, Sortierung und Link zur Detailseite.',
        'fields' => [
            ['name' => 'eyebrow', 'label' => 'Dachzeile (optional)', 'type' => 'text', 'width' => 'half'],
            ['name' => 'title', 'label' => 'Überschrift', 'type' => 'text', 'width' => 'half'],
            ['name' => 'intro', 'label' => 'Einleitung (optional)', 'type' => 'textarea', 'rows' => 2, 'max' => 400],
            ['type' => 'heading', 'label' => 'Daten'],
            ['name' => 'table', 'label' => 'Tabelle', 'type' => 'datatable', 'required' => true],
            ['name' => 'fields', 'label' => 'Angezeigte Felder', 'type' => 'datafields',
                'help' => 'Reihenfolge wie in der Tabelle. Das erste Bildfeld wird zum Kartenbild, der Titel zum Link.'],
            ['name' => 'layout', 'label' => 'Darstellung', 'type' => 'select', 'required' => true, 'default' => 'cards', 'width' => 'half',
                'options' => ['cards' => 'Karten', 'list' => 'Liste mit Bild', 'compact' => 'Kompakte Liste', 'table' => 'Tabelle']],
            ['name' => 'columns', 'label' => 'Spalten (Karten)', 'type' => 'select', 'default' => '3', 'width' => 'half', 'required' => true,
                'options' => ['2' => '2', '3' => '3', '4' => '4']],
            ['name' => 'ratio', 'label' => 'Bildformat', 'type' => 'select', 'default' => '16:10', 'width' => 'half', 'required' => true,
                'options' => ['16:9' => '16:9', '16:10' => '16:10', '4:3' => '4:3', '1:1' => '1:1', '3:4' => '3:4']],
            ['name' => 'limit', 'label' => 'Anzahl', 'type' => 'number', 'default' => 6, 'width' => 'half', 'help' => '0 = alle'],
            ...\Core\Data\Clamp::fields(),   // Textlänge, Titel kürzen (Karten und Listen)
            ['type' => 'heading', 'label' => 'Filter & Sortierung'],
            ['name' => 'filter_field', 'label' => 'Nur Einträge, bei denen …', 'type' => 'datafield', 'width' => 'half', 'empty_label' => '– kein Filter –'],
            ['name' => 'filter_op', 'label' => 'Bedingung', 'type' => 'select', 'default' => '=', 'width' => 'half', 'required' => true,
                'options' => ['=' => 'ist gleich', '!=' => 'ist nicht', 'contains' => 'enthält', '>=' => 'ab / größer gleich', '<=' => 'bis / kleiner gleich',
                    'current' => 'verknüpft mit dem aufgerufenen Eintrag', 'same' => 'gleich wie beim aufgerufenen Eintrag']],
            ['name' => 'filter_value', 'label' => 'Wert', 'type' => 'text',
                'help' => 'Datum: JJJJ-MM-TT oder „heute“. Auswahl: Kurzname der Option. Verknüpfung: Name des verknüpften Eintrags. Bei „aufgerufenem Eintrag“ leer lassen (für Detailseiten, z. B. Beiträge einer Person).'],
            ['name' => 'exclude_current', 'label' => 'Aufgerufenen Eintrag ausblenden (z. B. „Weitere Beiträge“)', 'type' => 'bool', 'default' => false],
            ['name' => 'sort_field', 'label' => 'Sortieren nach', 'type' => 'datafield', 'system' => true, 'width' => 'half', 'empty_label' => '– wie in der Tabelle eingestellt –'],
            ['name' => 'sort_dir', 'label' => 'Richtung', 'type' => 'select', 'default' => '', 'width' => 'half',
                'options' => ['' => 'wie eingestellt', 'asc' => 'aufsteigend (A–Z, alt → neu)', 'desc' => 'absteigend (Z–A, neu → alt)']],
            ['name' => 'paginate', 'label' => 'Seitenweise blättern', 'type' => 'bool', 'default' => false],
            ...\Core\Data\Shared::blockFields(true),
            ['type' => 'heading', 'label' => 'Links'],
            ['name' => 'link_detail', 'label' => 'Einträge verlinken (Detailseite)', 'type' => 'bool', 'default' => true],
            ['name' => 'more_label', 'label' => 'Button unter der Liste', 'type' => 'text', 'width' => 'half', 'placeholder' => 'z. B. Alle Beiträge'],
            ['name' => 'more_link', 'label' => 'Button-Link', 'type' => 'link', 'width' => 'half'],
            ['name' => 'empty_text', 'label' => 'Text, wenn nichts da ist', 'type' => 'text', 'default' => 'Zurzeit gibt es hier keine Einträge.'],
            ['name' => 'hide_empty', 'label' => 'Abschnitt ausblenden, wenn nichts da ist', 'type' => 'bool', 'default' => false,
                'help' => 'Ohne Einträge erscheint für Besucher gar nichts – z. B. „Offene Stellen“ auf einer allgemeinen Karriereseite.'],
        ],
    ],
    'data_fields' => [
        'label' => 'Datensatz-Felder', 'icon' => 'table', 'group' => 'Daten',
        'nestable' => true,   // in einer Spalte des Blocks „Layout“ erlaubt (Core\Layout)
        'help' => 'Für Detailseiten-Vorlagen: zeigt Felder des aufgerufenen Eintrags. In allen anderen Blöcken der Vorlage funktionieren zusätzlich Platzhalter wie {{titel}}.',
        'fields' => [
            ['name' => 'table', 'label' => 'Tabelle', 'type' => 'datatable', 'required' => true],
            ['name' => 'fields', 'label' => 'Felder', 'type' => 'datafields'],
            ['name' => 'layout', 'label' => 'Darstellung', 'type' => 'select', 'required' => true, 'default' => 'prose',
                'options' => ['head' => 'Kopf: Titel groß, Datum, Bild', 'prose' => 'Fließtext (Felder untereinander)', 'dl' => 'Steckbrief (Beschriftung: Wert)', 'image' => 'Nur Bild, breit']],
            ['name' => 'show_labels', 'label' => 'Feldnamen anzeigen (bei Fließtext)', 'type' => 'bool', 'default' => false],
            ['name' => 'ratio', 'label' => 'Bildformat', 'type' => 'select', 'default' => '16:9', 'required' => true, 'width' => 'half',
                'options' => ['16:9' => '16:9', '21:9' => '21:9', '4:3' => '4:3', '1:1' => '1:1', '3:4' => '3:4']],
            ['name' => 'back_label', 'label' => 'Zurück-Link (optional)', 'type' => 'text', 'width' => 'half', 'placeholder' => 'z. B. Alle Beiträge'],
            ['name' => 'back_link', 'label' => 'Zurück zu', 'type' => 'link'],
        ],
    ],
    'data_form' => [
        'label' => 'Formular (Datentabelle)', 'icon' => 'clipboard-text', 'group' => 'Daten',
        'nestable' => true,   // in einer Spalte des Blocks „Layout“ erlaubt (Core\Layout)
        'help' => 'Besucher legen über ein Formular einen Eintrag in einer Datentabelle an (z. B. Anmeldungen). Welche Felder, Status und Benachrichtigung stellen Sie bei der Tabelle ein (Felder → Öffentliches Formular). Mehrstufiger Spamschutz, ohne Cookies. Mit einer Eingangs-Tabelle (Anfragen) werden die Angaben Ende-zu-Ende verschlüsselt.',
        'fields' => [
            ['name' => 'eyebrow', 'label' => 'Dachzeile (optional)', 'type' => 'text', 'width' => 'half'],
            ['name' => 'title', 'label' => 'Überschrift', 'type' => 'text', 'width' => 'half'],
            ['name' => 'intro', 'label' => 'Einleitung (optional)', 'type' => 'textarea', 'rows' => 2, 'max' => 400],
            ['type' => 'heading', 'label' => 'Formular'],
            ['name' => 'table', 'label' => 'Tabelle', 'type' => 'datatable', 'required' => true, 'inbox' => true,
                'help' => 'Nur Tabellen mit eingeschaltetem „Öffentliches Formular“ nehmen Einträge an. Eingangs-Tabellen (Anfragen) speichern verschlüsselt.'],
            ['name' => 'submit_label', 'label' => 'Beschriftung des Buttons (optional)', 'type' => 'text', 'width' => 'half', 'placeholder' => 'Absenden'],
            ['name' => 'success_text', 'label' => 'Text nach dem Absenden (optional)', 'type' => 'text', 'width' => 'half',
                'help' => 'Leer = Text aus den Einstellungen der Tabelle.'],
            ['type' => 'heading', 'label' => 'Darstellung'],
            ['name' => 'form_width', 'label' => 'Breite', 'type' => 'select', 'required' => true, 'default' => 'text', 'width' => 'half',
                'options' => ['text' => 'Textbreite (wie Fließtext)', 'normal' => 'Normal', 'full' => 'Volle Breite'],
                'help' => 'Textbreite: in derselben Spalte wie die Fließtexte der Seite. Normal: schmales Formular im Inhaltsbereich. Volle Breite: Felder nutzen den ganzen Inhaltsbereich.'],
            ['name' => 'form_align', 'label' => 'Ausrichtung', 'type' => 'select', 'required' => true, 'default' => 'left', 'width' => 'half',
                'options' => ['left' => 'Linksbündig', 'center' => 'Mittig'],
                'help' => 'Mittig: Überschrift, Einleitung und Button stehen zentriert (bei „Normal“ auch das Formular selbst).'],
        ],
    ],
    // Stellenangebote (Core\Data\Jobs): nur auf der Detailseiten-Vorlage einer Tabelle mit schema.org-Typ „JobPosting“
    'job_facts' => [
        'label' => 'Stelle: Eckdaten', 'icon' => 'briefcase', 'group' => 'Daten',
        'nestable' => true,   // in einer Spalte des Blocks „Layout“ erlaubt (Core\Layout)
        'help' => 'Für die Detailseite eines Stellenangebots: Beschäftigungsart, Arbeitsort, Beginn, Gehalt, Bewerbungsfrist und Ansprechperson auf einen Blick – mit Button „Jetzt bewerben“ zum Formular. Ist die Stelle abgelaufen, steht hier „Diese Stelle ist nicht mehr ausgeschrieben“.',
        'fields' => [
            ['name' => 'title', 'label' => 'Überschrift (optional)', 'type' => 'text', 'width' => 'half', 'placeholder' => 'z. B. Auf einen Blick'],
            ['name' => 'apply_label', 'label' => 'Button zum Formular', 'type' => 'text', 'width' => 'half', 'default' => 'Jetzt bewerben',
                'help' => 'Springt zum Block „Stelle: Bewerbung“ (Sprungmarke „bewerben“). Leer = kein Button.'],
        ],
    ],
    'job_apply' => [
        'label' => 'Stelle: Bewerbung', 'icon' => 'envelope-simple', 'group' => 'Daten',
        'nestable' => true,   // in einer Spalte des Blocks „Layout“ erlaubt (Core\Layout)
        'help' => 'Für die Detailseite eines Stellenangebots: das Bewerbungsformular der Tabelle (Felder & Einstellungen → „Bewerbungsformular“). Das Feld „Stelle“ ist ausgefüllt und gesperrt, der Betreff der E-Mail nennt die Stelle. Bei abgelaufenen Stellen erscheint kein Formular.',
        'fields' => [
            ['name' => 'eyebrow', 'label' => 'Dachzeile (optional)', 'type' => 'text', 'width' => 'half'],
            ['name' => 'title', 'label' => 'Überschrift', 'type' => 'text', 'width' => 'half', 'default' => 'Jetzt bewerben'],
            ['name' => 'intro', 'label' => 'Einleitung (optional)', 'type' => 'textarea', 'rows' => 2, 'max' => 400],
            ['name' => 'submit_label', 'label' => 'Beschriftung des Buttons (optional)', 'type' => 'text', 'width' => 'half', 'placeholder' => 'Bewerbung absenden'],
            ['name' => 'success_text', 'label' => 'Text nach dem Absenden (optional)', 'type' => 'text', 'width' => 'half', 'help' => 'Leer = Text des Eingangs.'],
            ['name' => 'form_width', 'label' => 'Breite', 'type' => 'select', 'required' => true, 'default' => 'text', 'width' => 'half',
                'options' => ['text' => 'Textbreite (wie Fließtext)', 'normal' => 'Normal', 'full' => 'Volle Breite']],
            ['name' => 'form_align', 'label' => 'Ausrichtung', 'type' => 'select', 'required' => true, 'default' => 'left', 'width' => 'half',
                'options' => ['left' => 'Linksbündig', 'center' => 'Mittig']],
        ],
    ],
    'calendar' => [
        'label' => 'Kalender', 'icon' => 'calendar', 'group' => 'Daten',
        'help' => 'Termine einer Kalender-Tabelle als Monatsübersicht oder Terminliste – mit Blättern (auch ohne JavaScript), Wiederholungen und Link zum Abonnieren (iCal).',
        'fields' => [
            ['name' => 'eyebrow', 'label' => 'Dachzeile (optional)', 'type' => 'text', 'width' => 'half'],
            ['name' => 'title', 'label' => 'Überschrift', 'type' => 'text', 'width' => 'half'],
            ['name' => 'intro', 'label' => 'Einleitung (optional)', 'type' => 'textarea', 'rows' => 2, 'max' => 400],
            ['type' => 'heading', 'label' => 'Termine'],
            ['name' => 'table', 'label' => 'Kalender-Tabelle', 'type' => 'datatable', 'required' => true,
                'help' => 'Tabelle mit „Als Kalender nutzen“ (Daten → Tabelle → Felder & Einstellungen).'],
            ['name' => 'view', 'label' => 'Ansicht', 'type' => 'select', 'required' => true, 'default' => 'month', 'width' => 'half',
                'options' => ['month' => 'Monatsübersicht', 'agenda' => 'Terminliste des Monats']],
            ['name' => 'filter_field', 'label' => 'Nur Termine, bei denen …', 'type' => 'datafield', 'width' => 'half', 'empty_label' => '– kein Filter –'],
            ['name' => 'filter_value', 'label' => 'Wert (Kurzname der Auswahl)', 'type' => 'text', 'width' => 'half'],
            ...\Core\Data\Shared::blockFields(),
            ['name' => 'visitor_filter', 'label' => 'Besucher können nach Kategorie filtern', 'type' => 'bool', 'default' => false, 'width' => 'half',
                'help' => 'Links je Kategorie (Kategorie-Feld des Kalenders).'],
            ['name' => 'subscribe', 'label' => '„Abonnieren“-Link zeigen (iCal)', 'type' => 'bool', 'default' => true],
            ['name' => 'link_detail', 'label' => 'Termine verlinken (Detailseite)', 'type' => 'bool', 'default' => true],
            ['name' => 'empty_text', 'label' => 'Text, wenn keine Termine', 'type' => 'text', 'default' => 'In diesem Monat sind keine Termine eingetragen.'],
        ],
    ],
    'upcoming' => [
        'label' => 'Nächste Termine', 'icon' => 'calendar-dots', 'group' => 'Daten',
        'nestable' => true,   // in einer Spalte des Blocks „Layout“ erlaubt (Core\Layout)
        'help' => 'Die nächsten Termine einer Kalender-Tabelle ab heute – Wiederholungen werden einzeln aufgeführt.',
        'fields' => [
            ['name' => 'eyebrow', 'label' => 'Dachzeile (optional)', 'type' => 'text', 'width' => 'half'],
            ['name' => 'title', 'label' => 'Überschrift', 'type' => 'text', 'width' => 'half'],
            ['name' => 'intro', 'label' => 'Einleitung (optional)', 'type' => 'textarea', 'rows' => 2, 'max' => 400],
            ['type' => 'heading', 'label' => 'Termine'],
            ['name' => 'table', 'label' => 'Kalender-Tabelle', 'type' => 'datatable', 'required' => true],
            ['name' => 'limit', 'label' => 'Anzahl', 'type' => 'number', 'default' => 5, 'width' => 'half'],
            ['name' => 'days', 'label' => 'Nur in den nächsten … Tagen', 'type' => 'number', 'default' => 0, 'width' => 'half', 'help' => '0 = ohne Grenze (bis 1 Jahr)'],
            ['name' => 'filter_field', 'label' => 'Nur Termine, bei denen …', 'type' => 'datafield', 'width' => 'half', 'empty_label' => '– kein Filter –'],
            ['name' => 'filter_value', 'label' => 'Wert (Kurzname der Auswahl)', 'type' => 'text', 'width' => 'half'],
            ...\Core\Data\Shared::blockFields(),
            ['name' => 'layout', 'label' => 'Darstellung', 'type' => 'select', 'required' => true, 'default' => 'list', 'width' => 'half',
                'options' => ['list' => 'Liste mit Datum', 'compact' => 'Kompakt']],
            ['name' => 'show_location', 'label' => 'Ort anzeigen', 'type' => 'bool', 'default' => true, 'width' => 'half'],
            ['name' => 'link_detail', 'label' => 'Termine verlinken (Detailseite)', 'type' => 'bool', 'default' => true, 'width' => 'half'],
            ['name' => 'subscribe', 'label' => '„Abonnieren“-Link zeigen (iCal)', 'type' => 'bool', 'default' => false, 'width' => 'half'],
            ['name' => 'more_label', 'label' => 'Button unter der Liste', 'type' => 'text', 'width' => 'half', 'placeholder' => 'z. B. Alle Termine'],
            ['name' => 'more_link', 'label' => 'Button-Link', 'type' => 'link', 'width' => 'half'],
            ['name' => 'empty_text', 'label' => 'Text, wenn keine Termine', 'type' => 'text', 'default' => 'Zurzeit sind keine Termine geplant.'],
        ],
    ],
    'push_subscribe' => [
        'label' => 'Benachrichtigungen abonnieren', 'icon' => 'bell-ringing', 'group' => 'Daten',
        'nestable' => true,   // in einer Spalte des Blocks „Layout“ erlaubt (Core\Layout)
        'help' => 'Besucher abonnieren Push-Mitteilungen – zu neuen Einträgen einer Datentabelle (z. B. Aktuelles) oder zu mehreren Kanälen zur Auswahl. Erst erklären, dann fragt der Browser nach der Erlaubnis – nur nach Klick. Voraussetzung: Funktion „Push-Benachrichtigungen“; Kanäle unter Mitteilungen → Kanäle.',
        'fields' => [
            ['name' => 'channels', 'label' => 'Kanäle zur Auswahl', 'type' => 'multiselect', 'options' => \Core\Push\Channels::options(),
                'help' => 'Mehrere Kanäle: Besucher haken an, was sie möchten, und ändern es später hier. Nichts angehakt = nur die Tabelle unten.'],
            ['name' => 'table', 'label' => 'Tabelle (ein Kanal)', 'type' => 'datatable', 'empty_label' => '– Tabelle der Detailseite –',
                'help' => 'Ohne Kanalauswahl: Abo genau dieser Tabelle. Leer = Tabelle des aufgerufenen Eintrags (Detailseiten-Vorlage).'],
            ['name' => 'title', 'label' => 'Überschrift (optional)', 'type' => 'text', 'max' => 80, 'width' => 'half', 'placeholder' => 'Neue Einträge abonnieren'],
            ['name' => 'button', 'label' => 'Beschriftung des Buttons (optional)', 'type' => 'text', 'max' => 40, 'width' => 'half', 'placeholder' => 'Benachrichtigungen abonnieren'],
            ['name' => 'intro', 'label' => 'Erklärung (optional)', 'type' => 'textarea', 'rows' => 2, 'max' => 400,
                'help' => 'Was abonniert man, wie oft kommt etwas? Leer = Standardtext (ohne Anmeldung, ohne Tracking, jederzeit abbestellbar).'],
            ['name' => 'layout', 'label' => 'Darstellung', 'type' => 'select', 'default' => 'box', 'required' => true, 'width' => 'half',
                'options' => ['box' => 'Kasten mit Überschrift', 'inline' => 'Schlicht (Text und Button)']],
        ],
    ],
    'not_found' => [
        'label' => '404-Vorschläge', 'icon' => 'signpost', 'group' => 'Navigation',
        'help' => 'Für die Seite „Nicht gefunden (404)“ (Seiten → Sonderseiten): Überschrift und Text, „Vielleicht meinten Sie …“ mit ähnlichen Seiten zur aufgerufenen Adresse, Suchfeld und Button zur Startseite. Die Vorschläge erscheinen nur, wenn Besucher eine Adresse aufrufen, die es nicht gibt.',
        'fields' => [
            ['name' => 'eyebrow', 'label' => 'Dachzeile (optional)', 'type' => 'text', 'max' => 60, 'width' => 'half', 'placeholder' => 'z. B. Fehler 404'],
            ['name' => 'title', 'label' => 'Überschrift (optional, Hauptüberschrift der Seite)', 'type' => 'text', 'max' => 90, 'width' => 'half',
                'help' => '*Sternchen* betonen ein Wort wie im Kit.'],
            ['name' => 'intro', 'label' => 'Text (optional)', 'type' => 'textarea', 'rows' => 2, 'max' => 400],
            ...\Core\NotFound::blockFields(),
        ],
    ],
    'map' => [
        'label' => 'Karte', 'icon' => 'map-trifold', 'group' => 'Medien',
        'nestable' => true,   // in einer Spalte des Blocks „Layout“ erlaubt (Core\Layout)
        'help' => 'Interaktive Karte (OpenStreetMap-Daten über den eigenen Server – ohne Einwilligung, ohne Cookies).',
        'fields' => [
            ['name' => 'eyebrow', 'label' => 'Dachzeile (optional)', 'type' => 'text', 'width' => 'half'],
            ['name' => 'title', 'label' => 'Überschrift (optional)', 'type' => 'text', 'width' => 'half'],
            ...\Core\Maps::blockFields(),
        ],
    ],
    'gallery' => [
        'label' => 'Bildergalerie', 'icon' => 'images', 'group' => 'Medien',
        'help' => 'Bilder als Raster, Mosaik oder in Zeilen – einzeln ausgewählt oder automatisch aus einer Sammlung. Ein Klick öffnet das Bild groß (Lightbox). Alt-Texte kommen aus der Mediathek.',
        'fields' => [
            ...\Core\MediaBlocks::headFields(),
            ['type' => 'heading', 'label' => 'Bilder'],
            ['name' => 'source', 'label' => 'Quelle', 'type' => 'select', 'required' => true, 'default' => 'manual', 'width' => 'half',
                'options' => ['manual' => 'Einzelne Bilder auswählen', 'collection' => 'Alle Bilder einer Sammlung']],
            ['name' => 'collection', 'label' => 'Sammlung', 'type' => 'collection', 'width' => 'half',
                'help' => 'Neue Bilder in der Sammlung erscheinen automatisch (Medien → Sammlungen).'],
            ['name' => 'images', 'label' => 'Bilder (bei „Einzelne Bilder“)', 'type' => 'repeater', 'item_label' => 'Bild', 'title_field' => 'caption', 'fields' => [
                ['name' => 'image', 'label' => 'Bild', 'type' => 'media', 'required' => true, 'width' => 'half'],
                ['name' => 'caption', 'label' => 'Bildunterschrift (optional)', 'type' => 'text', 'width' => 'half'],
            ]],
            ['type' => 'heading', 'label' => 'Darstellung'],
            ['name' => 'layout', 'label' => 'Anordnung', 'type' => 'select', 'required' => true, 'default' => 'grid', 'width' => 'half',
                'options' => ['grid' => 'Raster (gleiches Format)', 'masonry' => 'Mosaik (Originalformat, Spalten)', 'justified' => 'Zeilen (Originalformat, bündig)']],
            ['name' => 'columns', 'label' => 'Spalten', 'type' => 'select', 'required' => true, 'default' => '3', 'width' => 'half',
                'options' => ['2' => '2 Spalten', '3' => '3 Spalten', '4' => '4 Spalten', '5' => '5 Spalten'],
                'help' => 'Bei „Zeilen“: Zeilenhöhe (mehr Spalten = kleinere Bilder).'],
            ['name' => 'ratio', 'label' => 'Bildformat (Raster)', 'type' => 'select', 'required' => true, 'default' => '4:3', 'width' => 'half',
                'options' => \Core\MediaBlocks::RATIOS, 'help' => 'Nutzt den in der Mediathek festgelegten Zuschnitt je Format.'],
            ['name' => 'captions', 'label' => 'Bildunterschriften anzeigen', 'type' => 'bool', 'default' => true, 'width' => 'half',
                'help' => 'Bei Sammlungen: Titel des Bildes aus der Mediathek.'],
            ['name' => 'lightbox', 'label' => 'Bilder per Klick groß anzeigen (Lightbox)', 'type' => 'bool', 'default' => true],
        ],
    ],
    'live_gallery' => [
        'label' => 'Live-Galerie', 'icon' => 'broadcast', 'group' => 'Medien', 'live' => true,
        'help' => 'Bilder, die sich bei Besuchern ohne Neuladen aktualisieren – z. B. Fotos von einer Veranstaltung. Aus einer Sammlung: in der Mediathek in die Sammlung hochladen, und sie erscheinen nach wenigen Sekunden. Einzeln ausgewählt: neue Bilder erscheinen, sobald Sie die Seite veröffentlichen. Besucher können die Aktualisierung anhalten.',
        'fields' => [
            ...\Core\MediaBlocks::headFields(),
            ['type' => 'heading', 'label' => 'Bilder'],
            ['name' => 'source', 'label' => 'Quelle', 'type' => 'select', 'required' => true, 'default' => 'collection', 'width' => 'half',
                'options' => ['collection' => 'Alle Bilder einer Sammlung', 'manual' => 'Einzelne Bilder auswählen']],
            ['name' => 'collection', 'label' => 'Sammlung', 'type' => 'collection', 'width' => 'half',
                'help' => 'Medien → Sammlungen. Bilder, die in diese Sammlung kommen (auch beim Hochladen), erscheinen live.'],
            ['name' => 'images', 'label' => 'Bilder (bei „Einzelne Bilder“)', 'type' => 'repeater', 'item_label' => 'Bild', 'title_field' => 'caption',
                'help' => 'Neue Bilder erscheinen bei Besuchern, sobald Sie die Seite veröffentlichen.', 'fields' => [
                ['name' => 'image', 'label' => 'Bild', 'type' => 'media', 'required' => true, 'width' => 'half'],
                ['name' => 'caption', 'label' => 'Bildunterschrift (optional)', 'type' => 'text', 'width' => 'half'],
            ]],
            ['name' => 'order', 'label' => 'Reihenfolge', 'type' => 'select', 'required' => true, 'default' => 'newest', 'width' => 'half',
                'options' => ['newest' => 'Neueste zuerst', 'oldest' => 'Älteste zuerst', 'collection' => 'Wie sortiert (Sammlung bzw. Liste)'],
                'help' => 'Bei einzelnen Bildern gilt das zuletzt hinzugefügte als neuestes.'],
            ['name' => 'limit', 'label' => 'Höchstens', 'type' => 'number', 'default' => 24, 'width' => 'half', 'help' => '0 = alle'],
            ['type' => 'heading', 'label' => 'Darstellung'],
            ['name' => 'layout', 'label' => 'Anordnung', 'type' => 'select', 'required' => true, 'default' => 'grid', 'width' => 'half',
                'options' => ['grid' => 'Raster (gleiches Format)', 'masonry' => 'Mosaik (Originalformat, Spalten)']],
            ['name' => 'columns', 'label' => 'Spalten', 'type' => 'select', 'required' => true, 'default' => '3', 'width' => 'half',
                'options' => ['2' => '2 Spalten', '3' => '3 Spalten', '4' => '4 Spalten', '5' => '5 Spalten']],
            ['name' => 'ratio', 'label' => 'Bildformat (Raster)', 'type' => 'select', 'required' => true, 'default' => '4:3', 'width' => 'half',
                'options' => \Core\MediaBlocks::RATIOS],
            ['name' => 'captions', 'label' => 'Bildtitel anzeigen', 'type' => 'bool', 'default' => false, 'width' => 'half'],
            ['name' => 'lightbox', 'label' => 'Bilder per Klick groß anzeigen (Lightbox)', 'type' => 'bool', 'default' => true],
            ['name' => 'empty_text', 'label' => 'Text, solange die Sammlung leer ist', 'type' => 'text', 'default' => 'Gleich geht es los – die ersten Bilder erscheinen hier automatisch.'],
        ],
    ],
    'live_text' => [
        'label' => 'Live-Text (Ticker)', 'icon' => 'broadcast', 'group' => 'Daten', 'live' => true,
        'help' => 'Meldungen, die sich bei Besuchern ohne Neuladen aktualisieren – als Ticker (neueste oben) oder nur die aktuelle Meldung, z. B. Spielstand, Wartezeit, Ablauf einer Veranstaltung. Direkt hier geschrieben (erscheinen beim Veröffentlichen der Seite) oder aus einer Datentabelle (erscheinen sofort, auch per API/MCP).',
        'fields' => [
            ...\Core\MediaBlocks::headFields(),
            ['type' => 'heading', 'label' => 'Meldungen'],
            ['name' => 'source', 'label' => 'Quelle', 'type' => 'select', 'required' => true, 'default' => 'manual', 'width' => 'half',
                'options' => ['manual' => 'Meldungen hier schreiben', 'table' => 'Aus einer Datentabelle']],
            ['name' => 'items', 'label' => 'Meldungen (bei „hier schreiben“)', 'type' => 'repeater', 'item_label' => 'Meldung', 'title_field' => 'title',
                'help' => 'Neue Meldungen unten anfügen – sie erscheinen bei Besuchern, sobald Sie die Seite veröffentlichen.', 'fields' => [
                ['name' => 'time', 'label' => 'Zeit (optional)', 'type' => 'datetime', 'width' => 'half', 'help' => 'Leer = ohne Zeitangabe.'],
                ['name' => 'title', 'label' => 'Überschrift', 'type' => 'text', 'width' => 'half', 'max' => 160],
                ['name' => 'text', 'label' => 'Text (optional)', 'type' => 'inline'],
            ]],
            ['name' => 'table', 'label' => 'Tabelle (bei „Datentabelle“)', 'type' => 'datatable',
                'help' => 'Titel = Überschrift der Meldung, dazu ein Textfeld. Nur veröffentlichte Einträge erscheinen.'],
            ['name' => 'text_field', 'label' => 'Textfeld (optional)', 'type' => 'datafield', 'empty_label' => '– Beschreibung der Tabelle –'],
            ['name' => 'mode', 'label' => 'Darstellung', 'type' => 'select', 'required' => true, 'default' => 'ticker', 'width' => 'half',
                'options' => ['ticker' => 'Ticker (neueste oben)', 'latest' => 'Nur die aktuelle Meldung (groß)']],
            ['name' => 'limit', 'label' => 'Anzahl (Ticker)', 'type' => 'number', 'default' => 20, 'width' => 'half', 'help' => '0 = alle'],
            ['name' => 'show_time', 'label' => 'Uhrzeit zeigen', 'type' => 'bool', 'default' => true, 'width' => 'half'],
            ['name' => 'link_detail', 'label' => 'Meldungen verlinken (Detailseite)', 'type' => 'bool', 'default' => false, 'width' => 'half'],
            ['name' => 'empty_text', 'label' => 'Text, solange es keine Meldung gibt', 'type' => 'text', 'default' => 'Noch keine Meldungen – diese Seite aktualisiert sich von selbst.'],
        ],
    ],
    'slideshow' => [
        'label' => 'Slider', 'icon' => 'slideshow', 'group' => 'Medien',
        'help' => 'Bilder oder Folien mit Text nacheinander – per Pfeil, Punkt, Tastatur oder Wischen. Automatisches Weiterblättern nur mit Pause-Schaltfläche und nie bei „Bewegung reduzieren“.',
        'fields' => [
            ...\Core\MediaBlocks::headFields(),
            ['type' => 'heading', 'label' => 'Folien'],
            ['name' => 'source', 'label' => 'Quelle', 'type' => 'select', 'required' => true, 'default' => 'manual', 'width' => 'half',
                'options' => ['manual' => 'Folien einzeln anlegen', 'collection' => 'Alle Bilder einer Sammlung']],
            ['name' => 'collection', 'label' => 'Sammlung', 'type' => 'collection', 'width' => 'half'],
            ['name' => 'slides', 'label' => 'Folien (bei „einzeln anlegen“)', 'type' => 'repeater', 'item_label' => 'Folie', 'title_field' => 'title', 'max_items' => 12, 'fields' => [
                ['name' => 'image', 'label' => 'Bild', 'type' => 'media', 'required' => true],
                ['name' => 'eyebrow', 'label' => 'Dachzeile (optional)', 'type' => 'text', 'max' => 60, 'width' => 'half'],
                ['name' => 'title', 'label' => 'Titel (optional)', 'type' => 'text', 'max' => 90, 'width' => 'half'],
                ['name' => 'text', 'label' => 'Text (optional)', 'type' => 'textarea', 'rows' => 2, 'max' => 300],
                ['name' => 'button_label', 'label' => 'Button – Beschriftung', 'type' => 'text', 'max' => 32, 'width' => 'half'],
                ['name' => 'button_link', 'label' => 'Button – Link', 'type' => 'link', 'width' => 'half'],
                ['name' => 'position', 'label' => 'Textposition', 'type' => 'select', 'required' => true, 'default' => 'bottom-left', 'width' => 'half',
                    'options' => ['bottom-left' => 'Unten links', 'bottom-center' => 'Unten mittig', 'center-left' => 'Mitte links', 'center' => 'Mitte', 'top-left' => 'Oben links']],
                ['name' => 'overlay', 'label' => 'Bild hinter dem Text', 'type' => 'select', 'required' => true, 'default' => 'dark', 'width' => 'half',
                    'options' => ['dark' => 'Abdunkeln (helle Schrift)', 'light' => 'Aufhellen (dunkle Schrift)', 'box' => 'Textkasten', 'none' => 'Unverändert']],
            ]],
            ['type' => 'heading', 'label' => 'Darstellung'],
            ['name' => 'height', 'label' => 'Format / Höhe', 'type' => 'select', 'required' => true, 'default' => '16:9', 'width' => 'half',
                'options' => ['16:9' => 'Breitbild 16:9', '21:9' => 'Kino 21:9', '3:2' => 'Querformat 3:2', '4:3' => 'Querformat 4:3', 'screen' => 'Vollbild (Bildschirmhöhe)']],
            ['name' => 'transition', 'label' => 'Übergang', 'type' => 'select', 'required' => true, 'default' => 'slide', 'width' => 'half',
                'options' => ['slide' => 'Schieben', 'fade' => 'Überblenden']],
            ['name' => 'arrows', 'label' => 'Pfeile anzeigen', 'type' => 'bool', 'default' => true, 'width' => 'half'],
            ['name' => 'dots', 'label' => 'Punkte anzeigen', 'type' => 'bool', 'default' => true, 'width' => 'half'],
            ['name' => 'loop', 'label' => 'Endlos (nach der letzten Folie wieder die erste)', 'type' => 'bool', 'default' => true],
            ['name' => 'autoplay', 'label' => 'Automatisch weiterblättern', 'type' => 'bool', 'default' => false, 'width' => 'half',
                'help' => 'Mit Pause-Schaltfläche; stoppt bei Maus/Fokus und bei „Bewegung reduzieren“.'],
            ['name' => 'interval', 'label' => 'Anzeigedauer je Folie', 'type' => 'select', 'required' => true, 'default' => '6', 'width' => 'half',
                'options' => ['4' => '4 Sekunden', '6' => '6 Sekunden', '8' => '8 Sekunden', '10' => '10 Sekunden']],
        ],
    ],
    'stack_cards' => [
        'label' => 'Stapelkarten', 'icon' => 'copy', 'group' => 'Inhalt',
        'help' => 'Karten, die sich beim Scrollen übereinanderschieben. Auf kleinen Bildschirmen und bei „Bewegung reduzieren“ als einfache Liste.',
        'fields' => [
            ...\Core\MediaBlocks::headFields(),
            ['name' => 'cards', 'label' => 'Karten', 'type' => 'repeater', 'item_label' => 'Karte', 'title_field' => 'title', 'max_items' => 8, 'fields' => [
                ['name' => 'eyebrow', 'label' => 'Dachzeile (optional)', 'type' => 'text', 'max' => 60, 'width' => 'half'],
                ['name' => 'title', 'label' => 'Titel', 'type' => 'text', 'max' => 90, 'required' => true, 'width' => 'half'],
                ['name' => 'text', 'label' => 'Text', 'type' => 'textarea', 'rows' => 3, 'max' => 500],
                ['name' => 'image', 'label' => 'Bild (optional)', 'type' => 'media'],
                ['name' => 'link_label', 'label' => 'Link – Beschriftung', 'type' => 'text', 'max' => 32, 'width' => 'half', 'placeholder' => 'z. B. Mehr erfahren'],
                ['name' => 'link', 'label' => 'Link', 'type' => 'link', 'width' => 'half'],
            ]],
            ['name' => 'ratio', 'label' => 'Bildformat', 'type' => 'select', 'required' => true, 'default' => '4:3', 'width' => 'half',
                'options' => \Core\MediaBlocks::RATIOS],
            ['name' => 'image_side', 'label' => 'Bild', 'type' => 'select', 'required' => true, 'default' => 'end', 'width' => 'half',
                'options' => ['end' => 'rechts', 'start' => 'links', 'alternate' => 'abwechselnd']],
        ],
    ],
    'partners' => [
        'label' => 'Partner & Logos', 'icon' => 'handshake', 'group' => 'Medien',
        'help' => 'Logos von Partnern, Kunden oder Förderern – optisch gleich groß, egal ob breiter Schriftzug oder quadratisches Zeichen. Ein Klick auf ein Logo zeigt Kurzinfo und Link. Einzeln gepflegt oder aus einer Datentabelle. Nur Logos verwenden, für die eine Freigabe vorliegt.',
        'fields' => [
            ...\Core\MediaBlocks::headFields(),
            ['type' => 'heading', 'label' => 'Logos'],
            ['name' => 'source', 'label' => 'Quelle', 'type' => 'select', 'required' => true, 'default' => 'manual', 'width' => 'half',
                'options' => ['manual' => 'Logos hier pflegen', 'table' => 'Aus einer Datentabelle']],
            ['name' => 'sort', 'label' => 'Reihenfolge', 'type' => 'select', 'required' => true, 'default' => 'manual', 'width' => 'half',
                'options' => ['manual' => 'Wie angelegt (Liste bzw. Tabelle)', 'name' => 'Name A–Z', 'category' => 'Kategorie, dann Name',
                    'field' => 'Nach Tabellenfeld (unten wählen)', 'random' => 'Zufällig bei jedem Seitenaufruf']],
            ['name' => 'items', 'label' => 'Logos (bei „hier pflegen“)', 'type' => 'repeater', 'item_label' => 'Logo', 'title_field' => 'name', 'max_items' => 60, 'fields' => [
                ['name' => 'logo', 'label' => 'Logo (SVG, PNG oder WebP, möglichst transparent)', 'type' => 'media', 'width' => 'half'],
                ['name' => 'name', 'label' => 'Name', 'type' => 'text', 'required' => true, 'max' => 80, 'width' => 'half',
                    'help' => 'Wird als Alternativtext des Logos und als Überschrift der Details verwendet.'],
                ['name' => 'info', 'label' => 'Kurzinfo (optional)', 'type' => 'inline', 'max' => 400,
                    'help' => 'Ein bis zwei Sätze – erscheinen erst nach einem Klick auf das Logo.'],
                ['name' => 'link', 'label' => 'Link (optional)', 'type' => 'link', 'width' => 'half'],
                ['name' => 'link_label', 'label' => 'Link-Beschriftung (optional)', 'type' => 'text', 'max' => 40, 'width' => 'half', 'placeholder' => 'Website besuchen'],
                ['name' => 'category', 'label' => 'Kategorie (optional)', 'type' => 'text', 'max' => 60, 'width' => 'half', 'placeholder' => 'z. B. Förderer'],
                ['name' => 'scale', 'label' => 'Größe feinjustieren', 'type' => 'select', 'default' => '0', 'required' => true, 'width' => 'half',
                    'options' => ['-1' => 'etwas kleiner', '0' => 'automatisch', '1' => 'etwas größer'],
                    'help' => 'Nur nötig, wenn die Datei viel Rand hat oder das Logo sehr fein ist.'],
                ['name' => 'mono', 'label' => 'Einfarbiges Logo – darf auf dunklem Hintergrund weiß erscheinen', 'type' => 'bool', 'default' => false],
            ]],
            ['type' => 'heading', 'label' => 'Datentabelle (bei „Aus einer Datentabelle“)'],
            ['name' => 'table', 'label' => 'Tabelle', 'type' => 'datatable'],
            ['name' => 'map_logo', 'label' => 'Logo aus Feld', 'type' => 'datafield', 'types' => ['media'], 'width' => 'half', 'empty_label' => '– Bildfeld der Tabelle –'],
            ['name' => 'map_name', 'label' => 'Name aus Feld', 'type' => 'datafield', 'types' => ['_title', 'text'], 'width' => 'half', 'empty_label' => '– Titel des Eintrags –'],
            ['name' => 'map_info', 'label' => 'Kurzinfo aus Feld', 'type' => 'datafield', 'types' => ['richtext', 'textarea', 'text'], 'width' => 'half', 'empty_label' => '– Beschreibung der Tabelle –'],
            ['name' => 'map_link', 'label' => 'Link aus Feld', 'type' => 'datafield', 'types' => ['url', 'link', '_url'], 'width' => 'half', 'empty_label' => '– erstes Link-Feld –'],
            ['name' => 'map_category', 'label' => 'Kategorie aus Feld', 'type' => 'datafield', 'types' => ['select', 'multiselect', 'text', 'relation'], 'width' => 'half', 'empty_label' => '– keine –'],
            ['name' => 'map_mono', 'label' => '„Einfarbig“ aus Feld (Ja/Nein)', 'type' => 'datafield', 'types' => ['bool'], 'width' => 'half', 'empty_label' => '– keines –'],
            ['name' => 'filter_field', 'label' => 'Nur Einträge, bei denen …', 'type' => 'datafield', 'width' => 'half', 'empty_label' => '– kein Filter –',
                'help' => 'Es erscheinen nur veröffentlichte Einträge.'],
            ['name' => 'filter_op', 'label' => 'Bedingung', 'type' => 'select', 'default' => '=', 'width' => 'half', 'required' => true,
                'options' => ['=' => 'ist gleich', '!=' => 'ist nicht', 'contains' => 'enthält']],
            ['name' => 'filter_value', 'label' => 'Wert', 'type' => 'text', 'width' => 'half', 'help' => 'Auswahl: Kurzname der Option, Ja/Nein: 1 oder 0.'],
            ['name' => 'limit', 'label' => 'Höchstens', 'type' => 'number', 'default' => 0, 'width' => 'half', 'help' => '0 = alle'],
            ['name' => 'sort_field', 'label' => 'Sortieren nach (bei „Nach Tabellenfeld“)', 'type' => 'datafield', 'system' => true, 'width' => 'half', 'empty_label' => '– wie in der Tabelle eingestellt –'],
            ['name' => 'sort_dir', 'label' => 'Richtung', 'type' => 'select', 'default' => 'asc', 'required' => true, 'width' => 'half',
                'options' => ['asc' => 'aufsteigend (A–Z, 1–9)', 'desc' => 'absteigend (Z–A, 9–1)']],
            ['type' => 'heading', 'label' => 'Darstellung'],
            ['name' => 'columns', 'label' => 'Spalten (große Bildschirme)', 'type' => 'select', 'required' => true, 'default' => '5', 'width' => 'half',
                'options' => ['3' => '3', '4' => '4', '5' => '5', '6' => '6'], 'help' => 'Auf Tablets 3, auf Smartphones 2 Spalten.'],
            ['name' => 'ratio', 'label' => 'Format der Kachel', 'type' => 'select', 'required' => true, 'default' => '3:2', 'width' => 'half',
                'options' => ['3:2' => 'Querformat 3:2', '1:1' => 'Quadrat 1:1', '2:1' => 'Breit 2:1']],
            ['name' => 'size', 'label' => 'Logogröße', 'type' => 'select', 'required' => true, 'default' => 'm', 'width' => 'half',
                'options' => ['s' => 'Klein (viel Luft)', 'm' => 'Mittel', 'l' => 'Groß']],
            ['name' => 'tile', 'label' => 'Kachel', 'type' => 'select', 'required' => true, 'default' => 'soft', 'width' => 'half',
                'options' => ['soft' => 'Dezente Fläche (passt sich an)', 'light' => 'Immer hell (für farbige Logos auf dunklem Grund)', 'none' => 'Ohne Fläche']],
            ['name' => 'gray', 'label' => 'Graustufen – farbig bei Maus oder Tastaturfokus', 'type' => 'bool', 'default' => false, 'width' => 'half'],
            ['name' => 'invert', 'label' => 'Auf dunklem Hintergrund invertieren', 'type' => 'select', 'required' => true, 'default' => 'marked', 'width' => 'half',
                'options' => ['marked' => 'Nur Logos mit „einfarbig“', 'all' => 'Alle Logos (nur wenn alle einfarbig sind)', 'off' => 'Nie'],
                'help' => 'Auf dunklen Abschnitten und im dunklen Farbschema erscheinen einfarbige Logos weiß. Nicht mit „Kachel: immer hell“.'],
            ['name' => 'group', 'label' => 'Überschrift je Kategorie (bei „Kategorie, dann Name“)', 'type' => 'bool', 'default' => false],
            ['type' => 'heading', 'label' => 'Details'],
            ['name' => 'details', 'label' => 'Kurzinfo und Link zeigen', 'type' => 'select', 'required' => true, 'default' => 'inline',
                'options' => ['inline' => 'Aufklappen unter der Reihe', 'dialog' => 'Dialog', 'off' => 'Keine Details – Logo verlinkt direkt'],
                'help' => 'Kurzinfo und Link erscheinen erst nach einem Klick auf das Logo. Ohne JavaScript stehen alle Angaben als Liste unter den Logos.'],
        ],
    ],
    'dials' => [
        'label' => 'Kennzahlen mit Skala', 'icon' => 'gauge', 'group' => 'Inhalt',
        'help' => 'Bis zu sechs Kennzahlen als Rundinstrument: große Zahl, Bezeichnung und Zusatz. Der farbige Bogen zeigt einen Füllstand, „Zahl von Höchstwert“ oder einen Prozentwert – sonst bleibt die Skala neutral. Nur belegbare Zahlen verwenden.',
        'fields' => [
            ...\Core\MediaBlocks::headFields(),
            ['name' => 'items', 'label' => 'Kennzahlen', 'type' => 'repeater', 'item_label' => 'Kennzahl', 'title_field' => 'value', 'max_items' => 6, 'fields' => [
                ['name' => 'value', 'label' => 'Wert (wird angezeigt)', 'type' => 'text', 'required' => true, 'max' => 12, 'width' => 'half', 'placeholder' => 'z. B. 92 % oder 0,4'],
                ['name' => 'unit', 'label' => 'Einheit (optional)', 'type' => 'text', 'max' => 8, 'width' => 'half', 'placeholder' => 'z. B. s, km, %'],
                ['name' => 'label', 'label' => 'Bezeichnung', 'type' => 'text', 'required' => true, 'max' => 60, 'width' => 'half', 'placeholder' => 'z. B. Weiterempfehlung', 'search' => true],
                ['name' => 'text', 'label' => 'Zusatz (optional)', 'type' => 'text', 'max' => 90, 'width' => 'half', 'placeholder' => 'z. B. Umfrage 2025, 180 Antworten'],
                ['name' => 'level', 'label' => 'Füllstand in % (optional)', 'type' => 'number', 'width' => 'half', 'min' => 0, 'max' => 100,
                    'help' => 'Direkt 0–100. Leer = aus Zahl und Höchstwert bzw. aus einem Prozentwert berechnet.'],
                ['name' => 'number', 'label' => 'Zahl für den Bogen (optional)', 'type' => 'number', 'width' => 'half',
                    'help' => 'Nur nötig, wenn der Wert keine reine Zahl ist (z. B. „12 Jahre“).'],
                ['name' => 'max', 'label' => 'Höchstwert der Skala (optional)', 'type' => 'number', 'width' => 'half',
                    'help' => 'Bogen = Zahl ÷ Höchstwert. Prozentwerte brauchen keinen Höchstwert; ohne Angaben bleibt die Skala neutral.'],
            ]],
            ['type' => 'heading', 'label' => 'Darstellung'],
            ['name' => 'size', 'label' => 'Größe', 'type' => 'select', 'required' => true, 'default' => 'm', 'width' => 'half',
                'options' => ['s' => 'Klein', 'm' => 'Mittel', 'l' => 'Groß']],
            ['name' => 'style', 'label' => 'Skala', 'type' => 'select', 'required' => true, 'default' => 'arc', 'width' => 'half',
                'options' => ['arc' => 'Bogen mit Skalenstrichen', 'ticks' => 'Nur Skalenstriche', 'minimal' => 'Schlichter Ring']],
            ['name' => 'animate', 'label' => 'Beim ersten Erscheinen einmal hochzählen', 'type' => 'bool', 'default' => true,
                'help' => 'Entfällt bei „Bewegung reduzieren“ und ohne JavaScript – dann steht sofort der Endwert da.'],
        ],
    ],
    // Glossar (Funktion „glossary“, Core\Glossary): Übersicht A–Z bzw. aufgerufener Begriff auf der Detailseiten-Vorlage
    'glossary' => [
        'label' => 'Glossar', 'icon' => 'book-open-text', 'group' => 'Daten',
        'help' => 'Fachbegriffe von A bis Z mit Buchstaben und Suchfeld – auf der Detailseiten-Vorlage des Glossars der aufgerufene Begriff. Die Begriffe pflegen Sie unter Glossar bzw. Daten → Glossar.',
        'fields' => [
            ['name' => 'eyebrow', 'label' => 'Dachzeile (optional)', 'type' => 'text', 'width' => 'half'],
            ['name' => 'title', 'label' => 'Überschrift', 'type' => 'text', 'width' => 'half'],
            ['name' => 'intro', 'label' => 'Einleitung (optional)', 'type' => 'textarea', 'rows' => 2, 'max' => 400],
            ['name' => 'view', 'label' => 'Ansicht', 'type' => 'select', 'required' => true, 'default' => 'list',
                'options' => ['list' => 'Übersicht A–Z', 'term' => 'Aufgerufener Begriff (Detailseiten-Vorlage)']],
            ['name' => 'search', 'label' => 'Suchfeld zum Filtern', 'type' => 'bool', 'default' => true, 'width' => 'half'],
            ['name' => 'letters', 'label' => 'Buchstaben-Navigation', 'type' => 'bool', 'default' => true, 'width' => 'half'],
            ['name' => 'category', 'label' => 'Nur Begriffe der Kategorie (optional)', 'type' => 'text', 'width' => 'half'],
            ['name' => 'show_category', 'label' => 'Kategorie anzeigen', 'type' => 'bool', 'default' => true, 'width' => 'half'],
        ],
    ],
];
