<?php /** Handbuch · Abschnitt „Design“ (Style-Editor) – eingebunden in „zentrale Angaben“ (Kern und Kits), entfällt bei eigenem Kapitel „design“ · @var callable $has */ ?>
  <?php if (!$has('design') && \Core\Design::enabled() && \Core\Features::on('design')): ?>
  <h3 id="design">Design: Farben, Formen, Schrift</h3>
  <p>Unter <b>Design</b> (Bereich Administration, nur mit dem Recht „Design (Style-Editor)“) passen Sie Farben, Ecken, Buttons und Schrift der Website an. Wählen Sie eine <b>Vorlage</b> oder ändern Sie einzelne Werte – rechts sehen Sie sofort eine Vorschau (Desktop/Mobil). Achten Sie auf die Kontrast-Hinweise: „zu schwach“ bedeutet, dass Text auf dieser Farbe schlecht lesbar ist; die Reiter zeigen, wo noch Kontrastprobleme bestehen. Online geht die Änderung erst mit <b>Speichern</b>; <b>Verwerfen</b> holt den gespeicherten Stand zurück, <b>Verlauf</b> die letzten zehn Stände, und „Auf Kit-Standard zurücksetzen“ das ursprüngliche Aussehen. Einstellungen lassen sich als Datei exportieren und auf einer anderen Website importieren.</p>
  <?php if (\Core\Features::on('fonts', false)): ?>
  <p><b>Weitere Schriften:</b> Unter <b>Grundeinstellungen › Schriften</b> installiert die Administration Schriften aus dem Google-Fonts-Katalog. Sie werden einmal auf den Server geladen und von Ihrer eigenen Domain ausgeliefert – Besucher haben keinen Kontakt zu Google. Im Design erscheinen sie in jeder Schriftauswahl mit dem Zusatz „(installiert)“ (sofern das Kit das zulässt). Lädt eine Schrift viel (über <?= \Core\Fonts::BUDGET_KB ?> KB), zeigt der Editor einen Hinweis: dann weniger Schnitte oder die variable Fassung installieren. Suche, Vorschau, Auswahl der Gewichte und Zeichensätze, Vorladen und Entfernen: alles auf der Seite <b>Schriften</b>; dort steht auch, wo eine Schrift verwendet wird. Lizenz und Copyright erscheinen automatisch unter <b>Hilfe › Lizenzen &amp; Danksagungen</b>.</p>
  <?php endif; ?>
  <?php endif; ?>
  <?php if (\Core\Design::enabled() && \Core\Features::on('design') && isset(\Core\Design::tokens()['ha_cta_style'])): ?>
  <h3 id="kopfbereich">Kopfbereich: Suche, Aktionen, Kontakt</h3>
  <p>Unter <b>Design › Kopfbereich: Suche &amp; Aktionen</b> legen Sie fest, was rechts im Kopf der Website steht – jedes Kit bringt dafür eigene Voreinstellungen mit, sodass keine zwei Kits gleich aussehen. Die Vorschau rechts zeigt jede Änderung sofort; online geht sie erst mit <b>Speichern</b>.</p>
  <?= $img('header-actions.webp', 'Kopfbereiche mehrerer Kits nebeneinander: Suchfeld mit Textlink, Befehlsfeld mit Newsletter-Link, Status-Chip mit Kontakt-Menü, geteilte Aktion, Glas-Befehlsfeld mit Kontakt-Menü, Kontakt-Chip mit Öffnungsstatus', 'Standards der Kits: Suchfeld + Textlink (fluid), Befehlsfeld „Suchen … ⌘K“ + Newsletter (editorial), Status-Chip + Kontakt-Menü (essenz), geteilte Aktion „Beratung buchen“ (modern), Glas-Befehlsfeld + Kontakt-Menü (glas), „Hofladen geöffnet“ + Textlink (nature); basis setzt „Kontakt“ als Menüpunkt ab.') ?>
  <ul>
    <li><b>Handlungsaufruf – Stil:</b> Es muss nicht immer ein Button sein. <b>Button</b> (gefüllt oder mit Kontur) passt, wenn es EINE starke Handlung gibt („Termin buchen“). Der <b>Menüpunkt</b> setzt die Aktion als letzten Punkt der Navigation ab – mit feiner Trennlinie und Akzent statt Button; gut für ruhige Websites (steht der Punkt schon im Menü, rückt er ans Ende). Das <b>Kontakt-Menü</b> ist ein Symbol mit Aufklappliste aller Kontaktwege: Anrufen (mit Nummer), E-Mail, Kontaktformular, Anfahrt (mit Adresse und Karte), Öffnungszeiten mit „jetzt geöffnet“ – ideal, wenn mehrere Kanäle zählen (Symbol wählbar: Sprechblasen, Telefon, Adressbuch, Headset). Außerdem: Textlink mit Pfeil („Termin anfragen →“), Symbol mit Beschriftung, <b>geteilt</b> (Aktion plus kleine Anruf- oder E-Mail-Taste), <b>Chip mit Statuspunkt</b> oder gar keiner. Die Ecken sind immer leicht abgerundet (8 px); das genaue Aussehen bestimmt das Kit – im Kit „glas“ etwa ein Glaspaneel, in „essenz“ ein Geräte-Paneel.</li>
    <li><b>Handlungsaufruf – Inhalt:</b> „Eigene“ nimmt Beschriftung und Link aus <b>Website › Darstellung</b>. Die Vorgaben <b>Kontakt</b>, <b>Termin</b> und <b>Newsletter</b> suchen ihr Ziel selbst (Seite „kontakt“, „termin“ bzw. „newsletter“ oder der gleichnamige Abschnitt der Startseite); <b>Anrufen</b> und <b>E-Mail</b> verwenden Telefon und E-Mail aus den Stammdaten.</li>
    <li><b>Zweite Aktion:</b> optional ein zweiter, zurückhaltender Link (z. B. Anrufen oder Newsletter); beim Stil „Geteilt“ die kleine Taste neben der Aktion.</li>
    <li><b>Suche im Kopfbereich</b> (nur bei eingeschalteter Website-Suche): Lupe mit Feld darunter, <b>Suchfeld in der Leiste</b> mit Vorschlägen beim Tippen, Lupe, die sich zum Feld <b>aufzieht</b>, <b>Befehlsfeld</b> „Suchen … ⌘K“ oder eine <b>Suchleiste</b> über die ganze Breite unter dem Kopf. Besucher springen mit der Taste <kbd>/</kbd> oder <kbd>⌘</kbd>/<kbd>Strg</kbd>+<kbd>K</kbd> ins Suchfeld; <kbd>Esc</kbd> schließt.</li>
    <li><b>Anordnung:</b> Aktionen rechts, Suche mittig (zwischen Marke und Menü) oder Suche in einer eigenen Zeile unter der Navigation.</li>
    <li><b>Kontakt-Chip:</b> Telefon und/oder E-Mail kompakt im Kopf. Mit <b>Öffnungsstatus</b> zeigt der Chip „Jetzt geöffnet“ bzw. „Zurzeit geschlossen“ – berechnet aus den Öffnungszeiten. Tragen Sie unter <b>Website › Darstellung</b> eine Bezeichnung ein (z. B. „Hofladen“), heißt es „Hofladen geöffnet“.</li>
    <li><b>Sprachumschalter</b> (bei mehreren Sprachen): Kürzel („DE · EN“), Aufklappliste oder Sprachnamen – bewusst ohne Flaggen.</li>
    <li><b>Social-Media-Symbole</b> (Profile aus Website › Social Media) und ein Link <b>„Anmelden“</b> zu einem Mitgliederbereich (Ziel unter Website › Darstellung).</li>
  </ul>
  <p><b>Auf dem Telefon</b> bleibt der Kopf schlank: Suchfelder werden zur Lupe (oder stehen im Menü), Aktionen mit Text wandern ins Menü, Symbol-Aktionen (Anrufen, Kontakt-Chip, Kontakt-Menü) bleiben als Symbol – alle mindestens 44 px groß, ohne seitliches Scrollen. Im Bearbeitungsmodus erscheint der Kopf wie auf der Website, die Tastenkürzel sind dort aus.</p>
  <?= $img('header-actions-design.webp', 'Style-Editor mit dem Reiter „Kopfbereich: Suche & Aktionen“ und der Vorschau', 'Design › Kopfbereich: Suche &amp; Aktionen – links die Optionen, rechts die Vorschau.') ?>
  <?php endif; ?>
