<?php /** Handbuch · Kapitel „Online-Anfragen“ (verschlüsselte Eingänge) */ ?>
  <p class="lead"><?= e(term('requests')) ?> enthalten <?= e(term('requests_data')) ?>. Sie landen in einem <b>Eingang</b> – einer besonderen Tabelle, die alles <b>verschlüsselt</b> speichert. Lesbar sind die Anfragen nur mit dem geheimen <b><?= e(term('key')) ?></b> – selbst der Webhoster kann sie nicht lesen.</p>
  <ol class="doc-steps">
    <li>Sie erhalten eine E-Mail „Neue Anfrage“ – ohne Inhalte, aus Datenschutzgründen. Neue Anfragen zeigt auch die Zahl neben <b>Anfragen</b> im Menü.</li>
    <li><a href="<?= e(url('/admin/requests')) ?>">Anfragen</a> öffnen, oben den Eingang wählen (z. B. Rezepte oder Überweisungen), den <b>geheimen <?= e(term('key')) ?></b> aus dem Passwortmanager einfügen, <b>Entschlüsseln</b>. Die Inhalte sind nur in dieser Ansicht lesbar – nach dem Neuladen wieder verschlossen.</li>
    <li>Status setzen: <b>In Bearbeitung</b> oder <b>Als erledigt markieren</b>. Mit <b>Zuweisen</b> sehen alle, wer sich kümmert. <b>Drucken</b> und <b>Kopieren</b> helfen beim Übertragen in <?= e(term('records_system')) ?>.</li>
    <li>Erledigte Anfragen werden nach der eingestellten Frist (Standard 90 Tage) automatisch gelöscht.</li>
  </ol>
  <p><b>Formularfelder ändern:</b> Daten → Eingang → <b>Felder &amp; Einstellungen</b> (Recht „Tabellen und Felder ändern“, Standard: Administration). Dort stehen auch Titel, Einleitung, Text nach dem Absenden, Benachrichtigung und die Löschfrist. Auf einer Seite fügen Sie ein solches Formular mit dem Block <b>Formular (Datentabelle)</b> ein. Einen neuen Eingang legen Sie unter Daten → <b>Neue Tabelle</b> mit der Vorlage „Anfragen“ an. Eingänge nehmen Dateien nur an, wenn sie per E-Mail zustellen (siehe unten), und erscheinen nie auf der Website, in der Suche oder über Schnittstellen im Klartext.</p>
  <h3 id="anfragen-mail">Anfragen per E-Mail zustellen</h3>
  <p>Manche Praxen und Betriebe möchten Anfragen nicht im System bearbeiten, sondern in ihrer eigenen Lösung – etwa wegen Aufbewahrungspflichten. Dafür gibt es je Eingang die Einstellung <b>Zustellung der Anfragen</b> (Daten → Eingang → <b>Felder &amp; Einstellungen</b>, Recht „Anfragen verwalten“):</p>
  <ul>
    <li><b>Im System (verschlüsselt)</b> – wie bisher, Standard.</li>
    <li><b>Im System und per E-Mail</b> – gespeichert wie bisher und zusätzlich mit vollem Inhalt per E-Mail. Die Löschfrist gilt für die gespeicherte Fassung.</li>
    <li><b>Nur per E-Mail – nicht im System speichern</b> – nur die E-Mail. Auf der Website bleibt nichts vom Inhalt, nur ein Zustellprotokoll (Zeit, Eingang, Status – ohne Namen, Adressen oder Inhalte). Die E-Mail ist dann das einzige Exemplar: bitte archivieren.</li>
  </ul>
  <p>Die E-Mail enthält alle Felder mit Beschriftung, die Eingangszeit, den Formularnamen und die <b>Vorgangsnummer</b>; hochgeladene Dateien kommen als Anhang (bis zur eingestellten Größe). Auf Wunsch kommt eine Datei für den Import in Ihr eigenes System mit (JSON oder XML). Mit einem Auswahlfeld können Sie Anfragen an verschiedene Adressen leiten (z. B. „Rezept“ → rezept@…). „Antworten“ geht direkt an die Person, die angefragt hat, wenn das Formular ein E-Mail-Feld hat. Der Betreff enthält standardmäßig nur Formular und Vorgangsnummer – keine Inhalte.</p>
  <p id="anfragen-dateien"><b>Dateien annehmen (z. B. Lebenslauf bei einer Bewerbung):</b> Mehr als drei Schritte braucht es nicht – (1) ein Feld vom Typ <b>Datei</b> anlegen und dort unter <b>Erlaubte Dateitypen</b> ankreuzen, was erlaubt ist (PDF, Bilder, Word/DOCX, OpenDocument/ODT; Standard PDF und Bilder), (2) unter <b>Felder im Formular</b> das Dateifeld anhaken (neu angelegte Felder sind automatisch dabei), (3) als Zustellung „Im System und per E-Mail“ oder „Nur per E-Mail“ wählen und speichern. Die Datei geht als Anhang mit der E-Mail hinaus (mit S/MIME verschlüsselt) bzw. liegt versiegelt bei der gespeicherten Anfrage – nie in der Mediathek. Die Höchstgröße je Datei stellen Sie bei „Dateien: höchstens (MB je Datei)“ ein (beim Feld auch kleiner). Die Website prüft den Inhalt der Datei, nicht nur die Endung; Word-Dateien mit Makros werden abgelehnt.</p>
  <div class="doc-note doc-note--important"><strong>Gesundheitsdaten: S/MIME verwenden</strong><p>Ohne S/MIME ist eine E-Mail nur auf dem Transportweg verschlüsselt (TLS) und liegt im Postfach lesbar. Hinterlegen Sie das <b>Zertifikat</b> (öffentlicher Teil) Ihres Empfangspostfachs – dann ist jede Anfrage samt Anhängen Ende-zu-Ende verschlüsselt und nur in Ihrem Mailprogramm lesbar. Schritt für Schritt: <a href="<?= e(url('/admin/hilfe#smime')) ?>">S/MIME einrichten</a>. Ohne SMTP mit TLS verschickt die Website keine Inhalte.</p></div>
  <p><b>Nichts geht verloren:</b> Klappt der Versand nicht (kein Empfänger eingetragen, Mailserver nicht erreichbar, Zertifikat abgelaufen …), wird die Anfrage verschlüsselt im System gesichert und erscheint unter <b>Anfragen</b> – mit dem Hinweis „Zustellung fehlgeschlagen – Anfrage verschlüsselt gesichert“ oben auf der Seite. Die Person, die angefragt hat, bekommt nur dann eine Erfolgsmeldung, wenn Versand oder Sicherung geklappt hat.</p>
  <p><b>Vor dem Start:</b> Empfänger eintragen, speichern, <b>Testmail senden</b> – sie enthält erfundene Angaben und den Betreff „[TEST] …“. Mit S/MIME prüfen, ob sie mit Schloss-Symbol ankommt und sich öffnen lässt. Buchungen (Erweiterung) brauchen gespeicherte Einträge: dort gibt es nur „Im System“ oder „Im System und per E-Mail“.</p>
  <p>Wer Anfragen lesen darf, legen Sie unter Benutzer &amp; Rollen fest – auf Wunsch nur für einzelne Eingänge. Jedes Entschlüsseln, Ändern und Löschen wird ohne Inhalte protokolliert (Anfragen → Protokoll, nur Administration).</p>
  <div class="doc-note doc-note--important"><strong>Den <?= e(term('key')) ?> nie verlieren</strong><p>Er wird bei der Einrichtung genau einmal angezeigt und nirgends auf dem Server gespeichert. Ohne ihn sind die Anfragen nicht mehr lesbar.</p></div>
