<?php /** Handbuch · Kapitel „Anmelden & Konto“ (Variablen: siehe help/manual.php) */ ?>
  <ol class="doc-steps">
    <li>Öffnen Sie <code><?= e(absolute_url('/admin')) ?></code> und melden Sie sich mit E-Mail-Adresse und Passwort an – bei eingerichteter Zwei-Faktor-Anmeldung danach mit dem 6-stelligen Code aus Ihrer App oder Ihrem Passkey. Mit Passkey geht es auch ohne Passwort („Mit Passkey anmelden“).</li>
    <li>Oben auf der Website erscheint nun eine dunkle <b>Redaktionsleiste</b> – nur für Sie sichtbar, nicht für Besucher.</li>
    <li>Unter <b>Konto</b> (links unten) ändern Sie Ihre <a href="#anmeldedaten">Anmeldedaten</a> (E-Mail-Adresse und Passwort – mindestens 12 Zeichen, am besten aus einem Passwortmanager), Ihren Namen, die Sprache der Verwaltung, Ihre Favoriten und die Zwei-Faktor-Anmeldung.</li>
  </ol>
  <div class="doc-note doc-note--info"><strong>Rollen</strong><p>Was Sie sehen, hängt von Ihrer Rolle ab. Die Vorlagen: <b>Redaktion</b> pflegt Seiten, <?= e($settingsTitle) ?>, Medien, Einträge und Anfragen und nutzt die KI-Funktionen; <b>Autorin/Autor</b> schreibt Entwürfe, veröffentlicht aber nichts; <b>Anfragen bearbeiten</b> liest nur Anfragen; <b>Administration</b> darf zusätzlich Grundeinstellungen, Design, Benutzer &amp; Rollen, Tabellen-Designer, API &amp; MCP und die Freigabe von Einreichungen. Die Administration kann unter <b>Benutzer &amp; Rollen</b> eigene Rollen zusammenstellen – fehlt ein Menüpunkt oder der Knopf „Veröffentlichen“, ist das so gewollt.</p></div>
  <div class="doc-note doc-note--warn"><strong>Sicherheit</strong><p>Nach 8 falschen Anmeldeversuchen von einem Anschluss ist die Anmeldung dort 15 Minuten gesperrt. Eine Sitzung endet spätestens nach 12 Stunden. Melden Sie sich an gemeinsam genutzten Rechnern immer ab.</p></div>
  <h3 id="passwort-vergessen">Passwort vergessen</h3>
  <ol class="doc-steps">
    <li>Auf der Anmeldeseite neben „Passwort“ <b>Passwort vergessen?</b> wählen und die E-Mail-Adresse Ihres Kontos eingeben.</li>
    <li>Die Seite antwortet immer gleich: „Wenn ein Konto zu dieser Adresse existiert, haben wir Ihnen einen Link geschickt.“ – so erfährt niemand, welche Adressen ein Konto haben.</li>
    <li>In der E-Mail „Passwort zurücksetzen“ <b>Neues Passwort festlegen</b> wählen. Der Link gilt <b>60 Minuten</b> und nur einmal; fordern Sie einen neuen an, gilt nur noch der neueste.</li>
    <li>Das neue Passwort zweimal eingeben (mindestens 12 Zeichen, mit „Anzeigen“ prüfen) und <b>Passwort speichern</b>. Alle Sitzungen Ihres Kontos enden, und Sie erhalten eine Bestätigung per E-Mail.</li>
    <li>Danach wie gewohnt anmelden. Haben Sie die <b>Zwei-Faktor-Anmeldung</b> oder einen Passkey eingerichtet, fragt die Anmeldung nach dem Passwort weiter danach – das Zurücksetzen umgeht den zweiten Faktor nicht. Passkeys bleiben erhalten.</li>
  </ol>
  <p>Melden Sie sich bisher nur mit Passkey an, legen Sie auf diesem Weg zusätzlich ein Passwort fest. Aus Sicherheitsgründen sind höchstens 5 Anfragen je Anschluss in 15 Minuten und 3 E-Mails je Adresse und Stunde möglich. Gesperrte Konten bekommen keine E-Mail.</p>
  <div class="doc-note doc-note--info"><strong>Netzwerk-Konten und fehlender E-Mail-Versand</strong><p>Netzwerk-Konten setzen ihr Passwort auf der Hauptwebsite (Netzwerk-Website) zurück; fordern sie den Link auf einer anderen Website an, führt die E-Mail dorthin. Ist der E-Mail-Versand nicht eingerichtet, sieht die Seite gleich aus, es kommt aber keine E-Mail – das Netzwerk-Protokoll vermerkt eine Warnung. Dann hilft die Administration unter <b>Benutzer &amp; Rollen</b> bzw. auf dem Server <code>php bin/console user:password &lt;email&gt;</code>.</p></div>
  <h3 id="anmeldedaten">Anmeldedaten ändern</h3>
  <p>Unter <b>Konto › Anmeldedaten</b> sehen Sie auf einen Blick, womit Sie sich anmelden: E-Mail-Adresse, ob ein Passwort festgelegt ist, Ihre Passkeys und die Zwei-Faktor-Anmeldung. Bei jeder Änderung erhalten Sie eine E-Mail.</p>
  <ol class="doc-steps">
    <li><b>E-Mail-Adresse ändern</b> aufklappen, die neue Adresse eintragen und mit Ihrem <b>aktuellen Passwort</b> bestätigen. Haben Sie kein Passwort (Anmeldung nur mit Passkey, z. B. nach einer Einladung), bestätigen Sie vorher mit <b>Mit Passkey bestätigen</b> – das gilt 15 Minuten.</li>
    <li>Sie erhalten eine E-Mail an die <b>neue</b> Adresse mit der Schaltfläche <b>Neue Adresse bestätigen</b>. Erst wenn Sie den Link öffnen und dort bestätigen, gilt die neue Adresse. Der Link gilt 24 Stunden und nur einmal; Sie müssen dafür nicht angemeldet sein.</li>
    <li>Gleichzeitig geht ein Hinweis an Ihre <b>bisherige</b> Adresse: „Ihre E-Mail-Adresse soll geändert werden auf …“. Waren Sie das nicht, wählen Sie dort <b>Das war ich nicht – Änderung abbrechen</b>. Dann bleibt alles, wie es ist, und alle Sitzungen Ihres Kontos enden – ändern Sie danach Ihr Passwort.</li>
    <li>Nach der Bestätigung melden Sie sich mit der neuen Adresse an. Ihre Passkeys gelten weiter, andere Sitzungen (z. B. auf einem zweiten Gerät) enden, und beide Adressen erhalten eine Bestätigung.</li>
  </ol>
  <p>Solange die Änderung wartet, steht sie unter <b>Konto › Anmeldedaten</b> mit der neuen Adresse und der Frist. <b>Erneut senden</b> verschickt einen neuen Bestätigungslink (der vorige gilt dann nicht mehr), <b>Abbrechen</b> verwirft die Änderung. Ist die neue Adresse schon bei einem anderen Konto dieser Website im Einsatz, wird nichts geändert.</p>
  <p><b>Passwort ändern</b> bzw. – ohne Passwort – <b>Passwort festlegen</b>: neues Passwort zweimal eingeben, bei einer Änderung zusätzlich das aktuelle. Andere Sitzungen enden, diese bleibt angemeldet. Mit einem Passwort können Sie sich auch dort anmelden, wo Ihr Passkey nicht verfügbar ist. Ihren <b>Namen</b> ändern Sie darunter unter <b>Profil</b>.</p>
  <div class="doc-note doc-note--info"><strong>E-Mail kommt nicht an?</strong><p>Ist der E-Mail-Versand nicht eingerichtet oder läuft die Website als Testumgebung, zeigt die Verwaltung einen deutlichen Hinweis – die Adresse bleibt dann unverändert, denn ohne Bestätigung ändert sich nichts. Bitten Sie in dem Fall die Administration: Sie kann unter <b>Benutzer &amp; Rollen</b> mit <b>E-Mail ändern</b> die Adresse eines Kontos direkt ändern. Beide Adressen erhalten dann einen Hinweis, die Sitzungen des Kontos enden. Auf der Kommandozeile: <code>php bin/console user:email &lt;alt&gt; &lt;neu&gt;</code>.</p></div>
  <div class="doc-note doc-note--info"><strong>Netzwerk-Konten</strong><p>Melden Sie sich mit einem zentralen Netzwerk-Konto an, verwalten Sie Ihre Anmeldedaten in der Netzwerk-Verwaltung – unter <b>Konto</b> führt ein Link dorthin. Eine dort geänderte Adresse gilt danach auf allen Websites.</p></div>
  <h3 id="zwei-faktor">Zwei-Faktor-Anmeldung</h3>
  <ol class="doc-steps">
    <li><b>Konto › Zwei-Faktor-Anmeldung</b> öffnen und den QR-Code mit einer Authenticator-App scannen (z. B. 2FAS, Aegis, Google oder Microsoft Authenticator).</li>
    <li>Den angezeigten 6-stelligen Code eingeben. Danach erscheinen <b>10 Wiederherstellungscodes</b> – ausdrucken oder im Passwortmanager ablegen. Jeder Code gilt einmal; neue Codes erzeugen Sie an derselben Stelle.</li>
    <li>Ab jetzt fragt die Anmeldung nach dem Passwort den Code ab.</li>
  </ol>
  <p>Verlangt die Administration die Zwei-Faktor-Anmeldung für Ihre Rolle (<b>Benutzer &amp; Rollen</b>), führt Sie die nächste Anmeldung direkt zur Einrichtung. Telefon verloren? Melden Sie sich mit einem Wiederherstellungscode an und richten Sie die App neu ein. Sind auch die Codes weg, wenden Sie sich an die Administration Ihrer Website: Sie kann unter <b>Benutzer &amp; Rollen</b> mit „2FA zurücksetzen“ die Zwei-Faktor-Anmeldung Ihres Kontos zurücksetzen – danach melden Sie sich mit Ihrem Passwort an und richten die App neu ein.</p>
  <h3 id="passkeys">Passkeys</h3>
  <p>Ein Passkey ersetzt den Code aus der App – oder, wenn die Administration es erlaubt, sogar das Passwort. Sie bestätigen die Anmeldung mit Fingerabdruck, Gesicht oder der PIN Ihres Geräts. Passkeys sind sicher gegen Phishing: Sie funktionieren nur auf der echten Adresse dieser Website.</p>
  <ol class="doc-steps">
    <li><b>Konto › Passkeys</b> öffnen, optional einen Namen eingeben (z. B. „MacBook Touch ID“) und <b>Passkey hinzufügen</b> wählen. Liegt die Anmeldung länger als 15 Minuten zurück, bestätigen Sie vorher Ihr Passwort.</li>
    <li>Das Gerät fragt nach Fingerabdruck, Gesicht oder PIN:
      <ul>
        <li><b>Mac</b> (Safari oder Chrome): Touch ID bzw. Mac-Passwort; der Passkey liegt im iCloud-Schlüsselbund und steht auch auf iPhone und iPad bereit.</li>
        <li><b>iPhone/iPad</b>: Face ID oder Touch ID; gespeichert im iCloud-Schlüsselbund (Einstellungen › Passwörter).</li>
        <li><b>Android</b>: Fingerabdruck oder Bildschirmsperre; gespeichert im Google Passwortmanager.</li>
        <li><b>Windows</b>: Windows Hello (Gesicht, Fingerabdruck oder PIN).</li>
        <li>Alternativ ein Passwortmanager (z. B. 1Password, Bitwarden) oder ein Sicherheitsschlüssel (z. B. YubiKey) – oder „Anderes Gerät verwenden“ und den QR-Code mit dem Telefon scannen.</li>
      </ul></li>
    <li>Beim ersten Passkey erscheinen <b>10 Wiederherstellungscodes</b> (falls Sie noch keine haben) – sicher aufbewahren.</li>
    <li>Ab jetzt: nach dem Passwort <b>Mit Passkey bestätigen</b> – oder direkt auf der Anmeldeseite <b>Mit Passkey anmelden</b> bzw. den Passkey im Vorschlag des E-Mail-Felds wählen, ganz ohne Passwort.</li>
  </ol>
  <p>Unter <b>Konto › Passkeys</b> sehen Sie, wann jeder Passkey zuletzt verwendet wurde, und können ihn umbenennen oder löschen. Richten Sie am besten zwei ein (z. B. Laptop und Telefon). Sind App-Code und Passkey eingerichtet, fragt die Anmeldung zuerst nach dem zuletzt verwendeten Verfahren; das andere steht darunter zur Wahl.</p>
  <div class="doc-note doc-note--info"><strong>Für die Administration: Anmeldung &amp; Sicherheit</strong><p>Unter <b>Benutzer &amp; Rollen › Anmeldung &amp; Sicherheit</b> legen Sie fest, welche Verfahren erlaubt sind (Authenticator-App, Passkeys, Anmeldung ohne Passwort) und ob eine Rolle einen zweiten Faktor braucht: „freiwillig“, „verlangt (App oder Passkey)“ oder „nur Passkey“. Mit einer <b>Übergangsfrist</b> werden die Konten bis zum Stichtag bei jeder Anmeldung erinnert, danach geht es erst nach der Einrichtung weiter; ohne Frist führt die nächste Anmeldung direkt zur Einrichtung. In der Benutzerliste zeigen „2FA“ und „Passkey ×2“, was eingerichtet ist; „2FA zurücksetzen“ löscht App-Code und alle Passkeys eines Kontos.</p></div>
  <div class="doc-note doc-note--info"><strong>Netzwerk-Administration</strong><p>Betreut eine Agentur mehrere Websites, hat sie zentrale Netzwerk-Konten. Sie erscheinen unter <b>Benutzer &amp; Rollen</b> mit dem Hinweis „Netzwerk“ und lassen sich dort nicht ändern oder löschen. Netzwerk-Konten melden sich immer mit zweitem Faktor an (App-Code oder Passkey; Passkeys gelten je Domain – über „Website wechseln“ ist keiner nötig), sehen in der Seitenleiste „Website wechseln“ und auf der Hauptwebsite die Übersicht aller Websites (siehe <a href="#netzwerk-uebersicht">Netzwerk-Übersicht</a>).</p></div>
  <h3 id="benutzer-rollen">Benutzer &amp; Rollen</h3>
  <p>Die Administration findet unter <b>Einrichtung › System › Benutzer &amp; Rollen</b> links eine Bereichsleiste (auf dem Handy ein Auswahlfeld oben); jeder Bereich ist eine eigene Seite:</p>
  <ul>
    <li><b>Übersicht</b>: Zahlen auf einen Blick – Personen, Konten ohne zweiten Faktor (und wer ihn laut Rolle noch einrichten muss), Passkeys, offene Einladungen mit Ablaufdatum, Personen je Rolle, zuletzt bzw. noch nie angemeldet – und Schnellzugriffe (Person einladen, Neue Rolle).</li>
    <li><b>Personen</b>: alle Konten mit Rolle und letzter Anmeldung. Ein Klick auf eine Person klappt Rolle ändern, E-Mail ändern, Zwei-Faktor zurücksetzen und Löschen auf.</li>
    <li><b>Einladen &amp; Anlegen</b>: Person einladen, Konto mit Startpasswort anlegen, offene Einladungen.</li>
    <li><b>Rollen</b>: eine Karte je Rolle mit ihren Rechten; <b>Rechte bearbeiten</b> öffnet die Rolle mit einem Schalter je Recht, <b>Neue Rolle</b> legt eine eigene an.</li>
    <li><b>Anmeldung &amp; Sicherheit</b>: erlaubte Verfahren, zweiter Faktor je Rolle, Übergangsfrist.</li>
  </ul>
  <h3 id="einladen">Personen einladen</h3>
  <p>Statt ein Konto mit Startpasswort anzulegen, laden Sie neue Kolleginnen und Kollegen unter <b>Benutzer &amp; Rollen › Einladen &amp; Anlegen</b> ein. Die Person legt dann selbst fest, wie sie sich anmeldet – niemand muss ein Passwort weitergeben.</p>
  <ol class="doc-steps">
    <li>E-Mail-Adresse eintragen, optional den Namen, die <b>Rolle</b> und eine kurze persönliche Nachricht (höchstens 500 Zeichen, erscheint als Zitat in der E-Mail). Zur Wahl stehen nur Rollen, die nicht mehr dürfen als Ihre eigene.</li>
    <li><b>Einladung senden</b>: Die Person erhält eine E-Mail „Einladung zu …“ mit der Schaltfläche <b>Einladung annehmen</b>. Der Link gilt 7 Tage und nur einmal.</li>
    <li>Auf der Seite zur Einladung gibt sie ihren Namen ein und erstellt einen <b>Passkey</b> (Fingerabdruck, Gesicht oder Geräte-PIN) und/oder ein <b>Passwort</b> (mindestens 12 Zeichen). Danach ist sie direkt angemeldet. Verlangt ihre Rolle einen zweiten Faktor, führt die Anmeldung wie gewohnt zur Einrichtung – ein Passkey erfüllt ihn bereits.</li>
  </ol>
  <p>Offene Einladungen stehen unter <b>Einladen &amp; Anlegen</b> (und mit Ablaufdatum in der <b>Übersicht</b>) mit „Eingeladen – wartet“, Datum und wer eingeladen hat. <b>Erneut senden</b> verschickt einen neuen Link (der alte gilt dann nicht mehr) und verlängert die Frist; <b>Zurückziehen</b> macht den Link sofort ungültig. Abgelaufene Einladungen bleiben stehen, bis Sie sie erneut senden oder zurückziehen.</p>
  <div class="doc-note doc-note--info"><strong>E-Mail kommt nicht an?</strong><p>Ist der E-Mail-Versand nicht eingerichtet (Grundeinstellungen › E-Mail-Versand) oder läuft die Website als Testumgebung, zeigt die Verwaltung den Einladungslink <b>einmal</b> zum Kopieren an – geben Sie ihn dann selbst weiter. Wer die Einladung nicht rechtzeitig annimmt, sieht einen Hinweis und bittet Sie um eine neue. Auf der Kommandozeile geht dasselbe mit <code>php bin/console user:invite &lt;email&gt; [rolle]</code>.</p></div>
  <h3 id="favoriten">Favoriten</h3>
  <p>Oft gebrauchte Stellen merken Sie sich mit dem <b>Stern <?= icon('star') ?></b> neben der Überschrift jeder Verwaltungsseite – eine Seite im Editor, eine Tabelle, ein einzelner Eintrag, die Kalenderansicht, ein Reiter der <?= e($settingsTitle) ?>, eine geöffnete Datei in der Mediathek oder ein Kapitel dieses Handbuchs. Die Favoriten stehen links oben in der Seitenleiste (auch in Medien und Daten) und in der Suche (<kbd>⌘</kbd> <kbd>K</kbd> / <kbd>Strg</kbd> <kbd>K</kbd>) ganz oben. Mit <b>Bearbeiten</b> benennen Sie sie um, entfernen sie oder ändern die Reihenfolge (ziehen oder <kbd>Alt</kbd>+<kbd>↑</kbd>/<kbd>↓</kbd>); dasselbe geht unter <b>Konto › Favoriten</b>. Favoriten gelten nur für Ihr Konto und diese Website, höchstens 30. Wurde das Ziel inzwischen gelöscht, führt der Favorit ins Leere – dann einfach entfernen.</p>
  <h3 id="akzentfarbe">Akzentfarbe &amp; Darstellung</h3>
  <p>Unter <b>Konto › Darstellung &amp; Sprache</b> wählen Sie Hell, Dunkel oder „wie das System“. Darunter färben Sie mit der <b>Akzentfarbe</b> Schaltflächen, Links, Markierungen und Fokusrahmen der Verwaltung – z. B. Petrol, Grün, Violett, Bordeaux, Orange oder Graphit statt des Standards „KLXM Navy“. Die Vorschau zeigt die Wirkung sofort; erst <b>Akzentfarbe speichern</b> übernimmt sie. Mit <b>Seitenleiste mitfärben</b> erhält auch die dunkle Seitenleiste einen Ton der gewählten Farbe. Die Farbe gilt nur für Ihr Konto – auch in der Werkzeugleiste und den Seitenleisten beim Bearbeiten auf der Website, nicht für Besucher. Einen freien Farbwähler gibt es bewusst nicht: Jede Vorlage ist in Hell und Dunkel auf gut lesbaren Kontrast geprüft.</p>
  <div class="doc-note doc-note--info"><strong>Für die Administration</strong><p>Unter <b>Grundeinstellungen › Website</b> legen Sie fest, welche Akzentfarben zur Wahl stehen („Akzentfarben der Verwaltung“; nichts angehakt = alle), oder schalten die persönlichen Farben ganz ab („Verwaltung immer im Standard“). Wer eine nicht mehr erlaubte Farbe gewählt hatte, sieht wieder den Standard.</p></div>
