<?php /** Handbuch · Kapitel „Anmelden & Konto“ (Variablen: siehe help/manual.php) */ ?>
  <ol class="doc-steps">
    <li>Öffnen Sie <code><?= e(absolute_url('/admin')) ?></code> und melden Sie sich mit E-Mail-Adresse und Passwort an – bei eingerichteter Zwei-Faktor-Anmeldung danach mit dem 6-stelligen Code aus Ihrer App oder Ihrem Passkey. Mit Passkey geht es auch ohne Passwort („Mit Passkey anmelden“).</li>
    <li>Oben auf der Website erscheint nun eine dunkle <b>Redaktionsleiste</b> – nur für Sie sichtbar, nicht für Besucher.</li>
    <li>Unter <b>Konto</b> (links unten) ändern Sie Ihr Passwort (mindestens 12 Zeichen; am besten aus einem Passwortmanager), die Sprache der Verwaltung, Ihre Favoriten und die Zwei-Faktor-Anmeldung.</li>
  </ol>
  <div class="doc-note doc-note--info"><strong>Rollen</strong><p>Was Sie sehen, hängt von Ihrer Rolle ab. Die Vorlagen: <b>Redaktion</b> pflegt Seiten, <?= e($settingsTitle) ?>, Medien, Einträge und Anfragen und nutzt die KI-Funktionen; <b>Autorin/Autor</b> schreibt Entwürfe, veröffentlicht aber nichts; <b>Anfragen bearbeiten</b> liest nur Anfragen; <b>Administration</b> darf zusätzlich Grundeinstellungen, Design, Benutzer &amp; Rollen, Tabellen-Baukasten, API &amp; MCP und die Freigabe von Einreichungen. Die Administration kann unter <b>Benutzer &amp; Rollen</b> eigene Rollen zusammenstellen – fehlt ein Menüpunkt oder der Knopf „Veröffentlichen“, ist das so gewollt.</p></div>
  <div class="doc-note doc-note--warn"><strong>Sicherheit</strong><p>Nach 8 falschen Anmeldeversuchen von einem Anschluss ist die Anmeldung dort 15 Minuten gesperrt. Eine Sitzung endet spätestens nach 12 Stunden. Melden Sie sich an gemeinsam genutzten Rechnern immer ab.</p></div>
  <h3 id="zwei-faktor">Zwei-Faktor-Anmeldung</h3>
  <ol class="doc-steps">
    <li><b>Konto › Zwei-Faktor-Anmeldung</b> öffnen und den QR-Code mit einer Authenticator-App scannen (z. B. 2FAS, Aegis, Google oder Microsoft Authenticator).</li>
    <li>Den angezeigten 6-stelligen Code eingeben. Danach erscheinen <b>10 Wiederherstellungscodes</b> – ausdrucken oder im Passwortmanager ablegen. Jeder Code gilt einmal; neue Codes erzeugen Sie an derselben Stelle.</li>
    <li>Ab jetzt fragt die Anmeldung nach dem Passwort den Code ab.</li>
  </ol>
  <p>Verlangt die Administration die Zwei-Faktor-Anmeldung für Ihre Rolle (<b>Benutzer &amp; Rollen</b>), führt Sie die nächste Anmeldung direkt zur Einrichtung. Telefon verloren? Melden Sie sich mit einem Wiederherstellungscode an und richten Sie die App neu ein. Sind auch die Codes weg, wenden Sie sich an die Administration Ihrer Website: Sie kann unter <b>Benutzer &amp; Rollen</b> mit „2FA zurücksetzen“ die Zwei-Faktor-Anmeldung Ihres Kontos zurücksetzen – danach melden Sie sich mit Ihrem Passwort an und richten die App neu ein.</p>
  <h3 id="passkeys">Passkeys</h3>
  <p>Ein Passkey ersetzt den Code aus der App – oder, wenn die Administration es erlaubt, sogar das Passwort. Sie bestätigen die Anmeldung mit Fingerabdruck, Gesicht oder der PIN Ihres Geräts. Passkeys sind sicher gegen Phishing: Sie funktionieren nur auf der echten Adresse dieser Website.</p>
  <ol class="doc-steps">
    <li><b>Konto › Passkeys</b> öffnen, optional einen Namen eingeben (z. B. „MacBook Touch ID“) und <b>Passkey hinzufügen</b> wählen. Liegt die Anmeldung länger als 15 Minuten zurück, bestätigen Sie vorher Ihr Passwort.</li>
    <li>Das Gerät fragt nach Fingerabdruck, Gesicht oder PIN:
      <ul>
        <li><b>Mac</b> (Safari oder Chrome): Touch ID bzw. Mac-Passwort; der Passkey liegt im iCloud-Schlüsselbund und steht auch auf iPhone und iPad bereit.</li>
        <li><b>iPhone/iPad</b>: Face ID oder Touch ID; gespeichert im iCloud-Schlüsselbund (Einstellungen › Passwörter).</li>
        <li><b>Android</b>: Fingerabdruck oder Bildschirmsperre; gespeichert im Google Passwortmanager.</li>
        <li><b>Windows</b>: Windows Hello (Gesicht, Fingerabdruck oder PIN).</li>
        <li>Alternativ ein Passwortmanager (z. B. 1Password, Bitwarden) oder ein Sicherheitsschlüssel (z. B. YubiKey) – oder „Anderes Gerät verwenden“ und den QR-Code mit dem Telefon scannen.</li>
      </ul></li>
    <li>Beim ersten Passkey erscheinen <b>10 Wiederherstellungscodes</b> (falls Sie noch keine haben) – sicher aufbewahren.</li>
    <li>Ab jetzt: nach dem Passwort <b>Mit Passkey bestätigen</b> – oder direkt auf der Anmeldeseite <b>Mit Passkey anmelden</b> bzw. den Passkey im Vorschlag des E-Mail-Felds wählen, ganz ohne Passwort.</li>
  </ol>
  <p>Unter <b>Konto › Passkeys</b> sehen Sie, wann jeder Passkey zuletzt verwendet wurde, und können ihn umbenennen oder löschen. Richten Sie am besten zwei ein (z. B. Laptop und Telefon). Sind App-Code und Passkey eingerichtet, fragt die Anmeldung zuerst nach dem zuletzt verwendeten Verfahren; das andere steht darunter zur Wahl.</p>
  <div class="doc-note doc-note--info"><strong>Für die Administration: Anmeldung &amp; Sicherheit</strong><p>Unter <b>Benutzer &amp; Rollen › Anmeldung &amp; Sicherheit</b> legen Sie fest, welche Verfahren erlaubt sind (Authenticator-App, Passkeys, Anmeldung ohne Passwort) und ob eine Rolle einen zweiten Faktor braucht: „freiwillig“, „verlangt (App oder Passkey)“ oder „nur Passkey“. Mit einer <b>Übergangsfrist</b> werden die Konten bis zum Stichtag bei jeder Anmeldung erinnert, danach geht es erst nach der Einrichtung weiter; ohne Frist führt die nächste Anmeldung direkt zur Einrichtung. In der Benutzerliste zeigen „2FA“ und „Passkey ×2“, was eingerichtet ist; „2FA zurücksetzen“ löscht App-Code und alle Passkeys eines Kontos.</p></div>
  <div class="doc-note doc-note--info"><strong>Netzwerk-Administration</strong><p>Betreut eine Agentur mehrere Websites, hat sie zentrale Netzwerk-Konten. Sie erscheinen unter <b>Benutzer &amp; Rollen</b> mit dem Hinweis „Netzwerk“ und lassen sich dort nicht ändern oder löschen. Netzwerk-Konten melden sich immer mit zweitem Faktor an (App-Code oder Passkey; Passkeys gelten je Domain – über „Website wechseln“ ist keiner nötig), sehen in der Seitenleiste „Website wechseln“ und auf der Hauptwebsite die Übersicht aller Websites.</p></div>
  <h3 id="favoriten">Favoriten</h3>
  <p>Oft gebrauchte Stellen merken Sie sich mit dem <b>Stern <?= icon('star') ?></b> neben der Überschrift jeder Verwaltungsseite – eine Seite im Editor, eine Tabelle, ein einzelner Eintrag, die Kalenderansicht, ein Reiter der <?= e($settingsTitle) ?>, eine geöffnete Datei in der Mediathek oder ein Kapitel dieses Handbuchs. Die Favoriten stehen links oben in der Seitenleiste (auch in Medien und Daten) und in der Suche (<kbd>⌘</kbd> <kbd>K</kbd> / <kbd>Strg</kbd> <kbd>K</kbd>) ganz oben. Mit <b>Bearbeiten</b> benennen Sie sie um, entfernen sie oder ändern die Reihenfolge (ziehen oder <kbd>Alt</kbd>+<kbd>↑</kbd>/<kbd>↓</kbd>); dasselbe geht unter <b>Konto › Favoriten</b>. Favoriten gelten nur für Ihr Konto und diese Website, höchstens 30. Wurde das Ziel inzwischen gelöscht, führt der Favorit ins Leere – dann einfach entfernen.</p>
  <h3 id="akzentfarbe">Akzentfarbe &amp; Darstellung</h3>
  <p>Unter <b>Konto › Darstellung &amp; Sprache</b> wählen Sie Hell, Dunkel oder „wie das System“. Darunter färben Sie mit der <b>Akzentfarbe</b> Schaltflächen, Links, Markierungen und Fokusrahmen der Verwaltung – z. B. Petrol, Grün, Violett, Bordeaux, Orange oder Graphit statt des Standards „KLXM Navy“. Die Vorschau zeigt die Wirkung sofort; erst <b>Akzentfarbe speichern</b> übernimmt sie. Mit <b>Seitenleiste mitfärben</b> erhält auch die dunkle Seitenleiste einen Ton der gewählten Farbe. Die Farbe gilt nur für Ihr Konto – auch in der Werkzeugleiste und den Seitenleisten beim Bearbeiten auf der Website, nicht für Besucher. Einen freien Farbwähler gibt es bewusst nicht: Jede Vorlage ist in Hell und Dunkel auf gut lesbaren Kontrast geprüft.</p>
  <div class="doc-note doc-note--info"><strong>Für die Administration</strong><p>Unter <b>Grundeinstellungen › Website</b> legen Sie fest, welche Akzentfarben zur Wahl stehen („Akzentfarben der Verwaltung“; nichts angehakt = alle), oder schalten die persönlichen Farben ganz ab („Verwaltung immer im Standard“). Wer eine nicht mehr erlaubte Farbe gewählt hatte, sieht wieder den Standard.</p></div>
