<?php /** Handbuch · Kapitel „Fragen & Probleme“ (Kits hängen eigene Fragen mit mode => after an) · @var callable $anchor */ ?>
  <details><summary>Ich habe gespeichert, aber Besucher sehen die Änderung nicht.</summary><div>Gespeichert wird ein Entwurf. Klicken Sie auf <b>Veröffentlichen</b>. In der Seitenliste zeigt „Änderungen offen“ an, wo noch etwas unveröffentlicht ist.</div></details>
  <details><summary>Wie ändere ich die Links im Menü oben?</summary><div>Seiten erscheinen über den Schalter <b>Menü</b> in der Seitenübersicht, Abschnitte über <b>Abschnitt &amp; Navigation</b> im Editor (Sprungmarke, „In Hauptnavigation anzeigen“, Beschriftung). Details: <a href="#menue">Menü ändern</a>.</div></details>
  <details><summary>Ich möchte alle Änderungen seit der letzten Veröffentlichung verwerfen.</summary><div>Im Editor oben <b>Entwurf verwerfen</b> – oder unter Seiten beim Eintrag mit „Änderungen offen“. Der verworfene Stand bleibt unter Versionen gesichert.</div></details>
  <details><summary>Ich habe versehentlich etwas gelöscht.</summary><div>Seiten → Seite → <b>Versionen</b> → gewünschten Stand <b>Wiederherstellen</b>, prüfen und veröffentlichen.</div></details>
  <details><summary>Die Telefonnummer lässt sich im Text nicht ändern.</summary><div>Sie ist zentral gepflegt: <?= e($settingsTitle) ?> → Stammdaten. So stimmt sie überall.</div></details>
  <details><summary>Das Bild wird unscharf oder abgeschnitten.</summary><div>Größeres Original im richtigen Seitenverhältnis hochladen, Fokuspunkt setzen oder einen eigenen Zuschnitt festlegen (siehe <a href="#<?= e($anchor('medien')) ?>">Bilder &amp; Dateien</a>).</div></details>
  <details><summary>Die Online-Formulare sind verschwunden.</summary><div>Ohne <?= e(term('key')) ?> oder bei ausgeschaltetem Formular werden sie ausgeblendet. Prüfen: Grundeinstellungen → Verschlüsselung und <?= e($settingsTitle) ?>.</div></details>
  <details><summary>Wir bekommen keine E-Mails zu neuen Anfragen.</summary><div>Grundeinstellungen → E-Mail-Versand: Empfänger prüfen und <b>Testnachricht senden</b>. Auch den Spam-Ordner ansehen.</div></details>
  <details><summary>Die Website soll kurz „offline“ sein.</summary><div>Grundeinstellungen → Website → <b>Wartungsmodus</b> (Administration). Besucher sehen einen Hinweis, Angemeldete die normale Seite.</div></details>
  <details><summary>Wie ändere ich die Adresse der Verwaltung (statt /admin)?</summary><div>Grundeinstellungen → <b>Adresse der Verwaltung</b> (Administration; betreuen Sie mehrere Websites in einer Installation, nur die Netzwerk-Administration). Neue Adresse eintragen oder den Vorschlag übernehmen, mit Ihrem Passwort bestätigen – es geht sofort unter der neuen Adresse weiter. Lesezeichen und die App auf dem Homescreen danach neu anlegen; /admin zeigt ohne Anmeldung nur noch „Seite nicht gefunden“. Mit „Zurück zu /admin“ ist es rückgängig gemacht.</div></details>
  <details><summary>Der Code der Zwei-Faktor-Anmeldung wird nicht angenommen.</summary><div>Prüfen Sie, ob die Uhrzeit Ihres Telefons automatisch gestellt ist, und nehmen Sie den nächsten Code – jeder Code gilt nur einmal. Notfalls mit einem Wiederherstellungscode anmelden (siehe <a href="#zwei-faktor">Zwei-Faktor-Anmeldung</a>).</div></details>
  <details><summary>Die KI-Knöpfe fehlen.</summary><div>Die KI ist für die Website nicht eingeschaltet, Ihre Rolle darf „KI-Funktionen nutzen“ nicht, oder das Tageslimit ist erreicht. Die Administration prüft das unter Grundeinstellungen → KI und Benutzer &amp; Rollen.</div></details>
