<?php /** Handbuch · Kapitel „Glossar“ (Core\Glossary; Variablen: siehe help/manual.php) */ ?>
  <p class="lead">Mit dem <b>Glossar</b> erklären Sie Fachbegriffe direkt im Text: Das erste Vorkommen eines Begriffs auf einer Seite bekommt eine gepunktete Unterstreichung. Ein Klick oder Tippen öffnet ein kleines Fenster mit der Kurz-Erklärung und dem Link „Mehr im Glossar“. Dazu gibt es eine Übersicht von A bis Z und für jeden Begriff eine eigene Seite. Die Funktion schaltet die Administration unter <b>Funktionen &amp; Erweiterungen → Glossar</b> ein (Standard: aus).</p>
  <h3>Einrichten</h3>
  <ul>
    <li><b>Wo?</b> Das Glossar hat keinen eigenen Punkt im Hauptmenü mehr: Seine Seite <b>Prüfen &amp; Einstellungen</b> erreichen Sie über <b>Daten → Glossar</b> (Knopf oben bzw. Unterpunkt in der Tabelle) und unter <b>Administration → Einstellungen</b>. Die Adresse <code>/admin/glossar</code> bleibt gleich.</li>
    <li><b>Prüfen &amp; Einstellungen</b> → „Glossar einrichten“: legt die Datentabelle „Glossar“ an, Detailseiten unter <code>/glossar/…</code> und die Übersichtsseite <code>/glossar</code> (als Entwurf – veröffentlichen Sie sie, wenn die ersten Begriffe stehen; im Menü erscheint sie erst, wenn Sie sie dort einhängen).</li>
  </ul>
  <h3>Begriffe pflegen</h3>
  <ul>
    <li><b>Begriff</b> (z. B. „SPF“) und <b>Kurz-Erklärung</b> sind Pflicht. Die Kurz-Erklärung ist Klartext mit höchstens 240 Zeichen – sie erscheint im Fenster. Schreiben Sie so, dass Laien sie verstehen, und in der Ansprache Ihrer Website.</li>
    <li><b>Varianten, Synonyme, Abkürzungen</b>: eine je Zeile, z. B. „Sender Policy Framework“. Abkürzungen mit mehreren Großbuchstaben (SPF, IPv6, MTA-STS) zählen nur in genau dieser Schreibweise, normale Wörter ohne Rücksicht auf Groß- und Kleinschreibung und mit üblichen Endungen („Zertifikat“ findet auch „Zertifikate“). Soll ein Wort nur genau so gelten, setzen Sie es in Anführungszeichen: <code>"Cookie"</code>.</li>
    <li><b>Ausführliche Erklärung</b>, <b>Kategorie</b> und <b>Mehr erfahren</b> (Link zu einer Quelle) sind freiwillig und erscheinen auf der Detailseite.</li>
    <li><b>Status</b>: Nur veröffentlichte Begriffe werden für Besucher markiert. Entwürfe sehen Sie angemeldet auf der Website mit dem Hinweis „Entwurf“ – so prüfen Sie neue Erklärungen im Zusammenhang.</li>
    <li>Bearbeitet wird wie bei jeder Datentabelle (<b>Daten → Glossar</b>). „Begriff schnell hinzufügen“ legt einen Entwurf an; ist die KI eingerichtet, schlägt „Von der KI vorschlagen“ eine Erklärung vor – immer als Entwurf, den Sie prüfen.</li>
  </ul>
  <h3 id="quick-glossar">Quick-Glossar auf der Website</h3>
  <p>Wer Seiten bearbeitet, braucht das Glossar oft mitten im Text. Angemeldet steht dafür in der Werkzeugleiste der Knopf <b>Glossar</b> (Buch-Symbol; auf dem Telefon im Menü „⋯“) – beim <b>Ansehen</b> und beim <b>Bearbeiten</b> (Seite oder Eintrag). Tastenkürzel: <kbd>⌥G</kbd> (Windows: <kbd>Alt</kbd>+<kbd>G</kbd>). Sie brauchen das Recht, Einträge der Tabelle „Glossar“ zu bearbeiten.</p>
  <p><b>Beim Ansehen: jeden Text als Begriff übernehmen.</b> Im Bearbeiten-Modus lassen sich nur die Textfelder markieren. Wechseln Sie für neue Begriffe deshalb zu <b>Ansehen</b>: Markieren Sie irgendein Wort auf der Seite (auch in Kacheln, Listen oder Bereichen, die Sie nicht direkt bearbeiten) und drücken Sie <kbd>⌥G</kbd> – oder klicken Sie den kleinen Knopf <b>Als Glossar-Begriff</b>, der neben der Markierung erscheint. Das Fenster öffnet „Neuer Begriff“ mit dem markierten Text und prüft gleich <b>Gibt es schon?</b> (gleicher Begriff, Variante oder ähnliche Begriffe). Nach dem Anlegen markiert die automatische Markierung den Begriff auf allen Seiten, sobald er veröffentlicht ist – als Entwurf sieht ihn nur die angemeldete Redaktion markiert (mit „Entwurf“). <b>Seite neu laden</b> zeigt die Markierung sofort. Verlinken („Einfügen“) geht nur im Bearbeiten-Modus; beim Ansehen öffnet „Öffnen“ den Begriff in der Verwaltung. Markieren und Kopieren funktionieren wie gewohnt – der Knopf neben der Markierung stört dabei nicht.</p>
  <ul>
    <li><b>Suchen</b>: Tippen Sie einen Begriff, eine Variante oder ein Wort aus der Erklärung. Jeder Treffer zeigt die Kurz-Erklärung. <b>Einfügen</b> setzt einen Link auf den Begriff – um den markierten Text oder, ohne Markierung, als neues Wort an der Schreibmarke. Der Link bleibt gültig, auch wenn der Begriff umbenannt wird (wie in der Linkauswahl). Oben im Fenster steht, wo eingefügt wird.</li>
    <li><b>Neuer Begriff</b>: ist mit dem markierten Text vorbelegt. Begriff und Kurz-Erklärung genügen; Varianten und eine ausführliche Erklärung sind freiwillig. Ohne das Recht „Einträge veröffentlichen“ entsteht ein Entwurf, sonst können Sie gleich veröffentlichen. Danach „Jetzt im Text verlinken“. Gibt es den Begriff schon, sagt das Fenster es und zeigt ihn.</li>
    <li><b>Auf dieser Seite</b>: listet die Begriffe, die die automatische Markierung auf dieser Seite kennzeichnen würde (jeweils das erste Vorkommen, mit Ihren Einstellungen). <b>Zur Stelle</b> springt dorthin und markiert das Wort – „Einfügen“ unter „Suchen“ verlinkt es dann.</li>
    <li><b>Tastatur</b>: Im Suchfeld führt <kbd>↓</kbd> in die Treffer, <kbd>↑</kbd>/<kbd>↓</kbd> wechseln, <kbd>Enter</kbd> fügt ein. Reiter mit <kbd>←</kbd>/<kbd>→</kbd>. <kbd>⌥G</kbd> springt zwischen Fenster und Text, <kbd>Esc</kbd> schließt das Fenster und bringt Sie zurück an die Schreibmarke.</li>
  </ul>
  <p>Eingefügte Links sind normale Änderungen: Speichern bzw. Veröffentlichen wie gewohnt. Links auf Begriffe im Entwurf wirken für Besucher erst, wenn der Begriff veröffentlicht ist.</p>
  <h3>Seite „Prüfen &amp; Einstellungen“</h3>
  <ul>
    <li><b>Hinweise</b>: Varianten, die bei mehreren Begriffen stehen, fehlende oder zu lange Kurz-Erklärungen und Überschneidungen (z. B. „TLS“ in „TLS-RPT“ – dort gilt der längere Begriff).</li>
    <li><b>Vorkommen</b>: auf wie vielen Seiten der Begriff steht (nach dem Text der Website-Suche) – mit Liste der Seiten.</li>
    <li><b>Import &amp; Export</b> als CSV-Datei (Semikolon; erste Zeile <code>begriff;varianten;kurz;erklaerung;kategorie;link;status;lang</code>, <code>lang</code> leer = Hauptsprache). Neue Begriffe werden Entwürfe.</li>
    <li><b>Mehrere Sprachen</b>: Übersetzen Sie einen Begriff wie jeden Eintrag (Daten → Glossar → Eintrag → Übersetzung anlegen). Englische Seiten markieren nur die englischen Begriffe – mit englischen Endungen („data table“ findet auch „data tables“). Für die Übersicht legen Sie die Übersetzung der Seite Glossar an (z. B. <code>/en/glossary</code>); in der Liste trägt jeder übersetzte Begriff das Kürzel seiner Sprache.</li>
  </ul>
  <h3 id="glossar-teilen">Glossar mit anderen Websites teilen</h3>
  <p>Gehören mehrere Websites zur selben Installation (z. B. Hauptwebsite und Projektseite), können sie <b>ein gemeinsames Glossar</b> nutzen. Jede Website pflegt ihre eigenen Begriffe und zeigt zusätzlich die der anderen – markiert im Text, in der Übersicht A–Z, mit Detailseite unter der eigenen Adresse (<code>/glossar/…</code>), im Quick-Glossar und in der Linkauswahl. Eingerichtet wird unter <b>Prüfen &amp; Einstellungen → Mit anderen Websites teilen</b> (Seite <code>/admin/glossar/teilen</code>); das dürfen Personen mit den Rechten „Grundeinstellungen“ und „Geteilte Daten verwalten“.</p>
  <ol class="doc-steps">
    <li><b>Teilen</b> (auf der Website, deren Glossar die Grundlage wird): „Glossar teilen“ und die übrigen Websites zum Beitreten <b>einladen</b>. Ihre Begriffe ziehen in den gemeinsamen Speicher – Adressen und Links bleiben gleich.</li>
    <li><b>Beitreten</b> (auf jeder eingeladenen Website): Die Seite zeigt, wie viele eigene Begriffe es gibt und welche es schon bei den anderen gibt – gleicher Begriff oder gleiche Variante, ohne Rücksicht auf Groß-/Kleinschreibung und Akzente („spf“ = „SPF“, „Ubertragung“ = „Übertragung“). Je Doppel wählen Sie: <b>Vorhandenen Begriff nutzen</b> (Ihr Begriff wird nicht übernommen, Ihre Links zeigen auf den vorhandenen), <b>Eigenen übernehmen, den anderen hier ausblenden</b> oder <b>Beide behalten</b>. Nichts wird stillschweigend doppelt angelegt; Links auf Begriffe in Ihren Seiten werden umgestellt, die bisherige Tabelle bleibt als Sicherung.</li>
    <li><b>Danach</b>: Neue Begriffe gehören der Website, auf der sie entstehen, und erscheinen bei allen. Ändern lässt sich ein Begriff nur auf seiner Website – in der Liste tragen fremde Begriffe „von …“. Einen fremden Begriff, der bei Ihnen nicht passt, blenden Sie mit <b>Ausblenden</b> aus (Recht „Einträge veröffentlichen“); „Wieder zeigen“ unter <b>Teilen verwalten</b>.</li>
    <li><b>Verlassen</b>: Unter „Teilen verwalten → Geteiltes Glossar verlassen“ wird das Glossar wieder ein eigenes Glossar Ihrer Website – mit Ihren Begriffen (gleiche Adressen) und auf Wunsch mit Kopien der fremden Begriffe, die Sie zuletzt gezeigt haben. Die Website, der das Glossar gehört, kann das Teilen erst beenden, wenn keine andere Website mehr beteiligt ist.</li>
  </ol>
  <div class="doc-note"><strong>Suchmaschinen</strong><p>Ein fremder Begriff hat auf Ihrer Website eine Detailseite mit demselben Text wie auf seiner Ursprungs-Website. Standard: Diese Seite nennt per <b>Canonical</b> die Ursprungs-Website als Original und steht nicht in Ihrer Sitemap – so gibt es keinen doppelten Inhalt, Besucher lesen die Erklärung trotzdem bei Ihnen. Umstellen lässt sich das unter <b>Daten → Glossar → Anzeige auf dieser Website</b> („Diese Website“ nur, wenn die Seiten bei Ihnen selbst gefunden werden sollen). Dort können Sie auch einstellen, dass Links auf fremde Begriffe direkt zur Ursprungs-Website führen.</p></div>
  <h3>Wo nicht markiert wird</h3>
  <ul>
    <li>Nie in Links, Buttons, Formularen, Code, Navigation, Kopf- und Fußbereich, großen Überschriften (h1–h3, einstellbar) und auf der eigenen Seite des Begriffs; nie im Bearbeiten-Modus.</li>
    <li><b>Einzelner Abschnitt</b>: im Editor in den Abschnitts-Optionen „Glossar-Begriffe hier nicht markieren“ (z. B. bei Zitaten oder Werbetexten).</li>
    <li><b>Ganze Seiten</b>: unter Daten → Glossar → Prüfen &amp; Einstellungen → „Seiten ausnehmen“ (z. B. <code>/impressum</code> oder <code>/blog/*</code>).</li>
    <li><b>Je Seite oder je Abschnitt</b>: Standard ist das erste Vorkommen je Seite; „je Abschnitt“ markiert in jedem Abschnitt erneut.</li>
  </ul>
  <div class="doc-note doc-note--tip"><strong>Gut zu wissen</strong><p>Auch Inhalte von Erweiterungen werden markiert. Entstehen Inhalte erst im Browser – etwa Ergebnisse eines Prüf-Werkzeugs –, trägt die Administration den Bereich unter Einstellungen → „Dynamische Bereiche“ ein (z. B. <code>.ergebnisse</code>). Für Screenreader ist jeder markierte Begriff eine Schaltfläche, die ihre Erklärung aufklappt; beim Drucken steht die Erklärung in Klammern hinter dem Begriff.</p></div>
