<?php /** Handbuch · Kapitel „KI-Chats: Assistent & Besucher-Chat“ (Core\AI\Assistant, Core\AI\VisitorChat; Variablen: siehe help/manual.php) */ $__brand = \Core\AI\Assist::brand(); ?>
  <p class="lead">Zwei optionale Chats mit KI: der <b>Assistent</b> für Sie in der Verwaltung und – wenn die Website ihn einschaltet – der <b>Besucher-Chat</b> auf der Website. Beide antworten nur aus vorhandenen Texten, nennen ihre Quellen und erfinden nichts.</p>

  <h3>Assistent in der Verwaltung (Redaktion)</h3>
  <ul>
    <li><b>Öffnen:</b> links unten <b>Assistent fragen</b>, in der Suche (<kbd>⌘K</kbd> bzw. <kbd>Strg</kbd>+<kbd>K</kbd>) den Eintrag <b>Assistent fragen: „…“</b>, das Tastenkürzel <kbd>Alt</kbd>+<kbd>Umschalt</kbd>+<kbd>K</kbd> (Mac: <kbd>⌥</kbd><kbd>⇧</kbd><kbd>K</kbd>) oder <b><?= e($__brand) ?> → Assistent</b> (große Ansicht mit gespeicherten Unterhaltungen). Das Fenster öffnet sich rechts; die Verwaltung bleibt daneben bedienbar. <kbd>Esc</kbd> schließt es.</li>
    <li><b>„Wie mache ich …?“</b> Die Antworten stammen aus diesem Handbuch, den Tutorials, der technischen Dokumentation und der Wissensdatenbank. Die kleinen Zahlen im Text (z. B. <b>1</b>) sind Links zu der Stelle, aus der die Aussage stammt. Findet der Assistent nichts Passendes, sagt er das – dann hilft <b>Problem melden</b>.</li>
    <li><b>Aktueller Bildschirm:</b> Mit dem Haken <b>Aktuellen Bildschirm mitsenden</b> weiß der Assistent, wo Sie gerade sind (z. B. welche Seite, welcher Eintrag, welches Bild in der Mediathek) – so versteht er „diese Seite“. Mitgeschickt wird nur, was Sie selbst bearbeiten dürfen.</li>
    <li><b>Aufgaben erledigen lassen:</b> Bitten Sie z. B. „Schlage eine Beschreibung für Suchmaschinen für diese Seite vor“, „Lege eine Seite ‚Urlaubsvertretung‘ als Entwurf an“ oder „Setze den Alt-Text für dieses Bild“. Der Assistent zeigt dann eine <b>Karte</b> mit der geplanten Änderung (bisher/neu). Erst mit <b>Ausführen</b> wird gespeichert – mit <b>Verwerfen</b> passiert nichts.</li>
    <li>Möglich sind nur sichere Aktionen: Seiten und Einträge als Entwurf anlegen oder Texte ändern, Übersetzungen anlegen, Alt-Texte, Titel/Beschreibung einer Seite, Hinweisbalken, Inhalte durchsuchen. Der Assistent <b>löscht nie</b> und <b>veröffentlicht nie</b>. Er darf genau das, was Ihre Rolle darf – fehlt ein Recht, steht das auf der Karte.</li>
    <li>Ist „KI-Übernahmen ebenfalls zur Freigabe“ eingeschaltet (<b><?= e($__brand) ?> → Eingereicht → Einstellungen</b>), heißt der Knopf <b>Zur Freigabe einreichen</b>: Die Änderung wartet dann unter <b>Eingereicht</b> auf die Prüfung.</li>
    <li><b>Verlauf und Datenschutz:</b> Der Verlauf bleibt nur in diesem Browser-Tab. Auf dem Server stehen ohne Ihr Zutun nur Zeit, Anzahl der Fragen und der Bildschirm – keine Inhalte. Mit der <b>Stecknadel</b> speichern Sie eine Unterhaltung (dann auch mit Inhalt); gespeicherte Unterhaltungen finden Sie unter dem Uhr-Symbol und unter <b><?= e($__brand) ?> → Assistent</b>, wo Sie sie auch wieder löschen. Jede Frage zählt zum Tageslimit der KI-Aufrufe.</li>
  </ul>

  <h3>Besucher-Chat auf der Website (Administration)</h3>
  <ul>
    <li>Der Besucher-Chat ist ein Knopf <b>„Fragen?“</b> unten rechts (oder links) auf der Website. Er beantwortet Fragen <b>nur aus den Inhalten dieser Website</b> – Seiten, FAQ, Einträge mit eigener Seite (z. B. Aktuelles, Termine) sowie Kontakt und Öffnungszeiten – und verlinkt die Seiten, aus denen die Antwort stammt. Findet er nichts, sagt er das ehrlich und bietet den Kontakt an (Link „Anfrage senden“, Telefon, E-Mail).</li>
    <li><b>Voraussetzungen:</b> Die Agentur hat die Funktion „KI-Chat für Besucher“ freigegeben, KI für Texte ist eingerichtet und die Website-Suche ist an. Dann erscheint unter <b>Grundeinstellungen → KI</b> der Abschnitt <b>Besucher-Chat</b>.</li>
    <li><b>Einrichten:</b> Begrüßung, bis zu vier vorgeschlagene Fragen, Text und Link für „weiß ich nicht“ (z. B. Ihr Kontaktformular), Link zur Datenschutzerklärung, eigener Datenschutz-Hinweis, Tageslimit, Position des Knopfs und Seiten ohne Chat (z. B. Formularseiten): <b>Seiten auswählen …</b> öffnet den Seitenbaum mit Suche; ein Häkchen wählt eine Seite, <b>+ Unterseiten</b> nimmt alles darunter mit. Gewählte Seiten stehen als Kärtchen mit ihrem Pfad unter dem Feld, „×“ entfernt eine. Zum Schluss <b>Besucher-Chat auf der Website zeigen</b> einschalten und speichern.</li>
    <li><b>Datenschutz zuerst:</b> Unter dem KI-Reiter steht ein <b>Absatz für die Datenschutzerklärung</b> (je nach Anbieter: eigener Server oder KI-Dienst) – übernehmen Sie ihn vor dem Einschalten. Besucher sehen vor der ersten Frage einen Hinweis und starten den Chat erst mit „Verstanden – Chat starten“.</li>
    <li>Der Chat setzt <b>keine Cookies</b>, lädt erst nach dem Klick und speichert <b>keine Fragen oder Antworten</b> – gezählt werden nur die Antworten pro Tag. Gegen Missbrauch gilt je Besucher ein Limit pro Minute und Tag; Versuche, die KI umzuprogrammieren („Ignoriere alle Regeln …“), lehnt der Chat ab. Bitten Sie Ihre Besucher (steht im Hinweis), keine persönlichen oder Gesundheitsdaten einzugeben.</li>
    <li>Die Antworten sind nur so gut wie Ihre Inhalte: Stehen Öffnungszeiten, Leistungen und häufige Fragen auf der Website (z. B. in einem FAQ-Block), findet der Chat sie. Neue Inhalte kennt er, sobald der Suchindex aktualisiert ist (automatisch nach dem Speichern).</li>
  </ul>
