<?php /** Handbuch · Kapitel „Website-Suche“ (Variablen: siehe help/manual.php) */ ?>
  <p class="lead">Besucher finden Inhalte über die <b>Lupe</b> im Kopfbereich bzw. das Suchfeld im Mobilmenü – die Ergebnisse stehen unter <code>/suche</code> (weitere Sprachen: <code>/en/search</code>). Die Suche verzeiht Tippfehler, ignoriert Umlaute und Groß-/Kleinschreibung und schlägt schon beim Tippen passende Seiten und Einträge vor.</p>
  <ul>
    <li><b>Was wird gefunden?</b> Veröffentlichte Seiten (ohne „Nicht in Suchmaschinen“), Einträge von Tabellen mit Detailseite (z. B. Aktuelles, Termine – bei geteilten Daten auch die Einträge anderer Websites, die Ihre Website zeigt), geprüfte Transkripte von Videos und Audio und auf Wunsch PDF-Dokumente der Mediathek (Titel, Beschreibung, Dateiname, Tags). Entwürfe und Anfragen nie.</li>
    <li><b>Aktualisierung:</b> Nach dem Veröffentlichen oder Speichern ist die Änderung spätestens bei der nächsten Suche gefunden – Sie müssen nichts tun.</li>
    <li><b>Einstellungen</b> (Administration): <b>Grundeinstellungen → Suche</b> – Tabellen ausnehmen, PDFs einbeziehen, Gewichtung von Titeln und Überschriften, <b>Synonyme</b> (z. B. „Öffnungszeiten, Sprechzeiten, geöffnet“), semantische Suche, Suchbegriffe ohne Treffer, Index neu aufbauen.</li>
    <li><b>Je Tabelle</b>: <b>Daten → Tabelle → Felder &amp; Einstellungen → Suche</b> – Tabelle an/aus, welche Felder wie stark zählen, Filter (z. B. Kategorie) auf der Ergebnisseite, Kurztext/Bild/Datum im Treffer, nur künftige Termine.</li>
  </ul>
  <div class="doc-note doc-note--tip"><strong>Suchbegriffe ohne Treffer</strong><p>Unter Grundeinstellungen → Suche sehen Sie anonym, wonach Besucher vergeblich gesucht haben. Ergänzen Sie dafür ein Synonym oder legen Sie passende Inhalte an.</p></div>
  <h3>Antwort über den Treffern (KI)</h3>
  <p>Ist KI für Texte eingerichtet, beantwortet die Suche Fragen direkt: Über den Treffern erscheint ein Kasten <b>Antwort</b> – z. B. auf „Was kostet die Teilnahme?“ mit Betrag und den Seiten als Quellen (kleine Nummern verlinken die Belege). Unter <b>Grundeinstellungen → Suche → KI-Antwort über den Treffern</b> wählen Sie: <b>aus</b> (Standard), <b>automatisch bei Fragen</b> (empfohlen – bei bloßen Stichworten erscheint der Knopf „Antwort erzeugen“), <b>immer automatisch</b> oder <b>nur auf Klick</b>. Die KI antwortet nur aus den Inhalten Ihrer Website; findet sie nichts Passendes, sagt sie das und nennt Ihre Kontaktdaten. Antworten zählen zum Tageslimit des Besucher-Chats. Der Chat-Knopf selbst ist dafür nicht nötig.</p>
  <h3>Semantische Suche</h3>
  <p>Ist unter <b>Grundeinstellungen → KI</b> ein Anbieter mit Embedding-Modell eingerichtet, die KI mit „Embeddings (Suche)“ für Ihre Website eingeschaltet und unter <b>Grundeinstellungen → Suche</b> die „Semantische Suche“ aktiviert, findet die Suche auch Inhalte, die dasselbe mit anderen Worten sagen („Wann haben Sie auf?“ → Sprechzeiten). Die Ergebnisse aus Stichwort- und semantischer Suche werden gemischt; ist der KI-Anbieter einmal nicht erreichbar, sucht die Website automatisch nur nach Stichworten weiter.</p>
  <div class="doc-note doc-note--warn"><strong>Datenschutz</strong><p>Läuft die KI bei einem externen Anbieter, gehen die Suchbegriffe der Besucher dorthin (ohne IP-Adresse). Dann gehört ein Hinweis in die Datenschutzerklärung – einen Textvorschlag finden Sie unter Grundeinstellungen → Suche bzw. → KI. Mit einem eigenen Ollama-Server bleibt alles auf Ihrem Server.</p></div>
