/**
 * Build-System (pnpm):
 *   pnpm build         Vendoren kopieren + alle Assets minifizieren
 *   pnpm vendor        nur Vendoren (Editor.js, Drag & Drop, Schriften) kopieren
 *   pnpm watch         Assets bei Änderungen neu bauen
 *
 * Quellen:  resources/{css,js}          → public/assets/{css,js}          (Core: Admin + Editor)
 *           kits/{name}/assets/…        → public/kits/{name}/…            (je Kit; Rückfall themes/{name}/assets)
 * Vendoren: node_modules                → public/assets/vendor              (Core: Editor.js, PDF.js, MapLibre)
 * Symbole:  resources/icons/icons.json    → public/assets/icons/{core,thema}.svg, icons.svg, icons-map.json, catalog.json (Phosphor duotone, tools/icons.mjs)
 * Kits:     kits/{name}/build.mjs       → eigene Vendoren des Kits (z. B. Schriften), Pakete aus
 *           kits/{name}/package.json    (wird bei Bedarf automatisch installiert)
 *           Ältere Kits unter themes/{name}/ werden ebenso gebaut (Ausgabe immer nach public/kits/{name})
 *
 * Auf dem Server wird weder Node noch pnpm benötigt – die gebauten Dateien liegen in /public.
 */
import { build, context } from 'esbuild';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { execSync } from 'node:child_process';
import { icons } from './icons.mjs';

const TOOLS = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(TOOLS, '..');
const PUB = path.join(ROOT, 'public');
const args = process.argv.slice(2);

const nm = (...p) => path.join(TOOLS, 'node_modules', ...p);
const copy = (from, to) => {
  fs.mkdirSync(path.dirname(to), { recursive: true });
  fs.copyFileSync(from, to);
  console.log('  vendor  ' + path.relative(ROOT, to));
};

/**
 * Lizenztexte der Abhängigkeiten, die ein Vendor-Bundle einbettet (z. B. earcut in MapLibre, codex-tooltip in Editor.js):
 * Abhängigkeitsbaum aus node_modules/.pnpm, je Paket Name, Version, Lizenz und LICENSE-Datei → eine Textdatei.
 */
function bundledLicenses(pkg, to) {
  const seen = new Map();
  const walk = (dir) => {
    const pj = JSON.parse(fs.readFileSync(path.join(dir, 'package.json'), 'utf8'));
    for (const dep of Object.keys(pj.dependencies ?? {})) {
      if (dep.startsWith('@types/')) continue;
      // pnpm: Abhängigkeiten liegen als Symlink neben dem echten Paketverzeichnis
      const nmDir = path.join(dir, ...pj.name.split('/').map(() => '..'));
      const d = path.join(nmDir, dep);
      if (!fs.existsSync(path.join(d, 'package.json'))) continue;
      const real = fs.realpathSync(d);
      if (seen.has(real)) continue;
      seen.set(real, JSON.parse(fs.readFileSync(path.join(real, 'package.json'), 'utf8')));
      walk(real);
    }
  };
  walk(fs.realpathSync(nm(pkg)));
  let out = `Third-party components bundled into ${pkg} (generated by tools/build.mjs from node_modules)\n`;
  for (const [dir, pj] of [...seen].sort((a, b) => a[1].name.localeCompare(b[1].name))) {
    const lic = fs.readdirSync(dir).find((f) => /^(LICEN[CS]E|COPYING)/i.test(f));
    out += `\n${'='.repeat(78)}\n${pj.name} ${pj.version} – ${pj.license ?? 'see below'}\n${'='.repeat(78)}\n`;
    out += lic ? fs.readFileSync(path.join(dir, lic), 'utf8').trim() + '\n' : '(no license file in the package; license field: ' + (pj.license ?? '–') + ')\n';
  }
  fs.mkdirSync(path.dirname(to), { recursive: true });
  fs.writeFileSync(to, out);
  console.log('  vendor  ' + path.relative(ROOT, to) + ` (${seen.size} Pakete)`);
}

async function vendors() {
  console.log('Vendoren:');
  const ed = path.join(PUB, 'assets/vendor/editorjs');
  copy(nm('@editorjs/editorjs/dist/editorjs.umd.js'), path.join(ed, 'editorjs.umd.js'));
  copy(nm('@editorjs/editorjs/LICENSE'), path.join(ed, 'LICENSE-editorjs.txt'));
  copy(nm('editorjs-drag-drop/dist/bundle.js'), path.join(ed, 'drag-drop.js'));
  copy(nm('editorjs-drag-drop/LICENSE'), path.join(ed, 'LICENSE-drag-drop.txt'));
  bundledLicenses('@editorjs/editorjs', path.join(ed, 'THIRD-PARTY-LICENSES.txt'));

  // Lato – Schrift der Verwaltung (Core; Themes bringen ihre eigene Schrift mit)
  const lato = path.join(PUB, 'assets/fonts');
  for (const w of [400, 700]) {
    for (const f of [`lato-latin-${w}-normal.woff2`, `lato-latin-ext-${w}-normal.woff2`, `lato-latin-${w}-italic.woff2`]) {
      copy(nm('@fontsource/lato/files', f), path.join(lato, f));
    }
  }
  copy(nm('@fontsource/lato/LICENSE'), path.join(lato, 'OFL-Lato.txt'));

  // MapLibre GL (Karten; lädt Kacheln über den eigenen Proxy /proxy/ofm)
  const ml = path.join(PUB, 'assets/vendor/maplibre');
  for (const f of ['maplibre-gl.mjs', 'maplibre-gl-shared.mjs', 'maplibre-gl-worker.mjs', 'maplibre-gl.css']) {
    copy(nm('maplibre-gl/dist', f), path.join(ml, f));
    // Verweise auf nicht mitgelieferte Source-Maps entfernen (vermeidet 404 in den Entwicklertools)
    const out = path.join(ml, f);
    fs.writeFileSync(out, fs.readFileSync(out, 'utf8').replace(/\n?\/[/*]# sourceMappingURL=\S+(\s*\*\/)?\s*$/, '\n'));
  }
  copy(nm('maplibre-gl/LICENSE.txt'), path.join(ml, 'LICENSE.txt'));
  bundledLicenses('maplibre-gl', path.join(ml, 'THIRD-PARTY-LICENSES.txt'));

  // Mozilla PDF.js (Viewer für PDF-Dateien)
  const pdf = path.join(PUB, 'assets/vendor/pdfjs');
  copy(nm('pdfjs-dist/build/pdf.min.mjs'), path.join(pdf, 'pdf.min.mjs'));
  copy(nm('pdfjs-dist/build/pdf.worker.min.mjs'), path.join(pdf, 'pdf.worker.min.mjs'));
  copy(nm('pdfjs-dist/LICENSE'), path.join(pdf, 'LICENSE.txt'));
  for (const dir of ['cmaps', 'standard_fonts', 'wasm', 'iccs']) {
    if (fs.existsSync(nm('pdfjs-dist', dir))) {
      fs.cpSync(nm('pdfjs-dist', dir), path.join(pdf, dir), { recursive: true });
      console.log('  vendor  ' + path.relative(ROOT, path.join(pdf, dir)) + '/');
    }
  }
  // QuickJS (wasm/quickjs-eval.*): pdfjs-dist liefert keine Lizenzdatei mit – MIT-Texte aus resources/licenses/
  if (fs.existsSync(path.join(pdf, 'wasm/quickjs-eval.wasm'))) copy(path.join(ROOT, 'resources/licenses/LICENSE_QUICKJS.txt'), path.join(pdf, 'wasm/LICENSE_QUICKJS'));
}


/**
 * Kits (Core\Kit): kits/{name} vor dem alten Ordner themes/{name}; gleiche Namen nur einmal. [name, ordner]
 */
function kits() {
  const out = new Map();
  for (const root of ['kits', 'themes']) {
    const base = path.join(ROOT, root);
    if (!fs.existsSync(base)) continue;
    for (const name of fs.readdirSync(base).sort()) {
      const dir = path.join(base, name);
      if (out.has(name) || !fs.statSync(dir).isDirectory()) continue;
      if (fs.existsSync(path.join(dir, 'theme.php')) || fs.existsSync(path.join(dir, 'kit.php'))) out.set(name, dir);
    }
  }
  return [...out];
}

/**
 * Kit-Vendoren: kits/{name}/build.mjs exportiert `vendors(ctx)`.
 * Pakete kommen aus kits/{name}/node_modules (eigene package.json), sonst aus tools/node_modules.
 * ctx = { copy, pkg(...pfad), theme, themeDir, publicDir, root } (Namen theme/themeDir bleiben für bestehende build.mjs)
 */
async function themeVendors() {
  for (const [theme, dir] of kits()) {
    const hook = path.join(dir, 'build.mjs');
    if (!fs.existsSync(hook)) continue;
    // Installieren, wenn node_modules fehlt oder package.json neuer ist (z. B. zusätzliche Schriften)
    const pj = path.join(dir, 'package.json'), marker = path.join(dir, 'node_modules', '.modules.yaml');
    if (fs.existsSync(pj) && (!fs.existsSync(marker) || fs.statSync(pj).mtimeMs > fs.statSync(marker).mtimeMs)) {
      console.log(`  pnpm install (${path.relative(ROOT, dir)})`);
      execSync('pnpm install --silent', { cwd: dir, stdio: 'inherit' });
      if (fs.existsSync(marker)) fs.utimesSync(marker, new Date(), new Date());
    }
    const pkg = (...p) => {
      const own = path.join(dir, 'node_modules', ...p);
      return fs.existsSync(own) ? own : nm(...p);
    };
    console.log(`Kit ${theme}:`);
    const mod = await import(pathToFileURL(hook).href);
    await mod.vendors?.({ copy, pkg, theme, themeDir: dir, publicDir: path.join(PUB, 'kits', theme), root: ROOT });
  }
}

/** Liste der Einstiegspunkte: [quelle, zielordner] */
function entries() {
  const list = [];
  const add = (srcDir, outDir) => {
    for (const kind of ['css', 'js']) {
      const dir = path.join(srcDir, kind);
      if (!fs.existsSync(dir)) continue;
      for (const f of fs.readdirSync(dir)) {
        if (f.startsWith('_') || !(f.endsWith('.' + kind) || (kind === 'js' && f.endsWith('.mjs')))) continue;
        list.push([path.join(dir, f), path.join(outDir, kind)]);
      }
    }
    // Weitere Theme-Assets (Bilder, Icons) 1:1 kopieren
    const img = path.join(srcDir, 'img');
    if (fs.existsSync(img)) fs.cpSync(img, path.join(outDir, 'img'), { recursive: true });
  };
  add(path.join(ROOT, 'resources'), path.join(PUB, 'assets'));
  for (const [theme, dir] of kits()) {
    const src = path.join(dir, 'assets');
    if (fs.existsSync(src)) add(src, path.join(PUB, 'kits', theme));
  }
  // Erweiterungen: extensions/{name}/assets → public/extensions/{name}
  const extDir = path.join(ROOT, 'extensions');
  if (fs.existsSync(extDir)) for (const ext of fs.readdirSync(extDir)) {
    const src = path.join(extDir, ext, 'assets');
    if (fs.existsSync(src)) add(src, path.join(PUB, 'extensions', ext));
  }
  return list;
}

const options = ([src, outdir]) => ({
  entryPoints: [src],
  outdir,
  bundle: true,
  // *.mjs = ES-Modul (z. B. PDF-Viewer, importiert PDF.js zur Laufzeit)
  format: src.endsWith('.mjs') ? 'esm' : 'iife',
  outExtension: src.endsWith('.mjs') ? { '.js': '.mjs' } : {},
  minify: true,
  sourcemap: false,
  target: ['es2020', 'safari15'],
  external: ['/assets/*', '../vendor/*', '../fonts/*'],
  loader: { '.woff2': 'file' },
  legalComments: 'none',
  logLevel: 'warning',
});

async function assets() {
  console.log('Assets:');
  for (const e of entries()) {
    await build(options(e));
    const out = path.join(e[1], path.basename(e[0]));  // gleiche Endung wie die Quelle
    const kb = (fs.statSync(out).size / 1024).toFixed(1);
    console.log(`  ${path.relative(ROOT, e[0]).padEnd(46)} → ${path.relative(ROOT, out)}  (${kb} KB)`);
    if (out === path.join(PUB, 'assets/css/admin.css')) shadowCss(out);
  }
}

/**
 * admin.shadow.css: Verwaltungs-CSS für Shadow DOM (Seitenleiste „Eintrag bearbeiten“ auf der Website, _entry_edit.js).
 * Tokens hängen dort am Host statt an :root; html.adm-ui[data-theme=…] (Hell/Dunkel) → :host(.adm-ui[data-theme=…]).
 */
function shadowCss(file) {
  const css = fs.readFileSync(file, 'utf8')
    .replace(/html\.adm-ui((?:\[[^\]]*\]|:not\([^()]*\))*)/g, ':host(.adm-ui$1)')
    .replace(/:root(?![\w-])/g, ':host');
  fs.writeFileSync(path.join(path.dirname(file), 'admin.shadow.css'), css);
  console.log(`  ${'(abgeleitet)'.padEnd(46)} → public/assets/css/admin.shadow.css`);
}

if (args.includes('--watch')) {
  for (const e of entries()) (await context(options(e))).watch();
  console.log('Watching …');
} else {
  await vendors();
  await themeVendors();
  console.log('Symbole:');
  await icons({ root: ROOT, nm });
  if (!args.includes('--vendor-only')) await assets();
}
