<?php /** Entwicklerhandbuch · Eigene Blöcke (Block-Designer, Core\Blocks) */ ?>
  <p class="lead">Administration und Integratoren bauen unter <b>Verwaltung → Blöcke</b> eigene Blocktypen aus Feldern, einer <b>sicheren Vorlagensprache</b> und <b>begrenztem CSS</b> – ohne PHP, ohne eigenes JavaScript, ohne Deploy. Recht <code>blocks.build</code>, Funktion <code>blocks.custom</code> (Presets <i>content</i>/<i>minimal</i>: aus). Code: <code>app/Blocks/Template.php</code> (Compiler + Interpreter + PHP-Export), <code>Runtime.php</code> (Filter, Escaping, Hülle), <code>Css.php</code> (Begrenzung), <code>Custom.php</code> (Speicher, Freigabe, Integration), Oberfläche <code>BlockController</code>, <code>views/blocks/*</code>, <code>resources/js/_blockbuilder.js</code>.</p>

  <h3>Datenmodell &amp; Integration</h3>
  <table class="doc-table">
    <tr><th>Teil</th><th>Beschreibung</th></tr>
    <tr><td><code>custom_blocks</code></td><td>Je Website: <code>bkey</code>, label, icon, bgroup, description, fields_json, template, css, behaviours, jsonld_json, settings_json, sample_json (Arbeitsstand), <code>status</code> draft | published | withdrawn, <code>version</code>, <code>published_json</code> (freigegebene Fassung inkl. CSS-Datei), updated_by, Zeitstempel. Verlauf: <code>custom_block_versions</code> (letzte 60 je Block).</td></tr>
    <tr><td>Blocktyp</td><td><code>cblk_{schlüssel}</code> – Theme::__construct registriert freigegebene und zurückgezogene Fassungen (Kit-Blöcke gleichen Namens haben Vorrang). Damit gelten Editor.js-Schublade, Seitenleisten-Formular, Vorschau, <code>Features::allowsBlock</code> (<code>blocks</code> → allow/deny), REST <code>/api/v1/block-types</code> und MCP <code>list_block_types</code> (<code>custom: true</code>), Suche (Textfelder) und Medien-Verwendungen automatisch. Schreiben über API/MCP: nur Seiteninhalte mit diesen Typen (über die bestehende Prüf-Ebene); Definitionen selbst sind nur in der Verwaltung änderbar.</td></tr>
    <tr><td>Ausgabe</td><td>Innerhalb der normalen Abschnitts-Hülle des Kits (Tunes, Hintergrund, Anker, Hintergrundbild): <code>&lt;div class="cblk cblk-{schlüssel}[ is-dark]"&gt;&lt;div class="{container_class}"&gt;…&lt;/div&gt;&lt;/div&gt;</code> (Einstellung „Volle Breite“ ohne inneren Container). Fehler beim Rendern: im Bearbeiten-Modus Hinweis, für Besucher leer (Fehlerprotokoll).</td></tr>
    <tr><td>CSS</td><td>Bei der Freigabe: <code>{media}/blocks/cblk-{schlüssel}-{hash}.css</code> (statisch, verkleinert, max. 16 KB); <code>Theme::conditionalCss</code> lädt sie nur auf Seiten mit dem Block (im Bearbeiten-Modus alle). Lightbox-Verhalten zieht <code>media.css</code>/<code>media.mjs</code> des Kerns nach. Keine Inline-Styles (CSP).</td></tr>
    <tr><td>Direktes Bearbeiten</td><td>Steht ein Platzhalter eines Text-/Textarea-Felds allein in einem Element (<code>&lt;h3&gt;{{ item.name }}&lt;/h3&gt;</code>), setzt der Compiler im Bearbeiten-Modus <code>data-edit="items.2.name"</code> (über <code>Block::edit</code>, auch Feldbindung von Detailseiten-Vorlagen). <code>inline</code>- bzw. <code>rich</code>-Felder entsprechend mit Formatierungsleiste (rich nur in Block-Containern wie div). Nicht in <code>&lt;a&gt;</code>.</td></tr>
    <tr><td>JSON-LD</td><td>Optional: FAQ (Liste + Frage/Antwort → <code>FAQPage</code>) oder Einträge eines schema.org-Typs (Service, Product, Person, Event, Place, Organization, Course, CreativeWork) mit Zuordnung name, description, image, url, telephone, email, price (→ Offer), jobTitle, startDate, location – je Block oder je Listeneintrag (<code>ItemList</code>). Werte mit „[“ werden übersprungen.</td></tr>
  </table>

  <h3>Vorlagensprache</h3>
  <table class="doc-table">
    <tr><th>Syntax</th><th>Bedeutung</th></tr>
    <tr><td><code>{{ feld }}</code>, <code>{{ item.name }}</code></td><td>Ausgabe, immer escaped. <code>{{{ … }}}</code> gibt es nicht. Pfade: Feldname, Schleifenvariable, <code>loop.index|index0|first|last|length|revindex</code>, <code>block.id|dom_id|title_id|dark|editing|anchor|background|type</code>. Unbekannte Felder/Unterfelder sind Übersetzungsfehler.</td></tr>
    <tr><td><code>{{ x | filter('arg', 2) }}</code></td><td>Filter (Argumente nur Literale): <code>rich</code>, <code>inline</code> (Sanitizer-Whitelist), <code>plain</code>, <code>upper</code>, <code>lower</code>, <code>trim</code>, <code>date('short|long|weekday|day_month')</code>, <code>default('…')</code> (Text über <code>lt()</code>), <code>truncate(n)</code>, <code>number(dezimalen)</code>, <code>length</code>, <code>image('sizes', '4:3')</code> (<code>Media::picture</code>), <code>zoom(…)</code> (Bild als Lightbox-Link), <code>alt</code>, <code>icon</code>, <code>link</code> (<code>link_href</code>/<code>{theme}_link</code>), <code>tel</code>, <code>file</code>, <code>filename</code>, <code>filesize</code>, <code>lt</code> (nur auf festen Texten: <code>{{ 'Mehr' | lt }}</code>), <code>lines</code> (Zeilen → Liste), <code>nl2br</code>, <code>paragraphs</code>.</td></tr>
    <tr><td><code>{% if a and not b %}…{% elseif x == 'y' %}…{% else %}…{% endif %}</code></td><td>Bedingungen: <code>and</code>, <code>or</code>, <code>not</code>, <code>== != &lt; &gt; &lt;= &gt;=</code>, Klammern; leer/0/false/[] = falsch.</td></tr>
    <tr><td><code>{% for e in liste %}…{% else %}…{% endfor %}</code></td><td>Schleifen über Listen (repeater) oder <code>feld | lines</code>; höchstens 3 ineinander, 200 Einträge je Schleife, 2000 Durchläufe je Block.</td></tr>
    <tr><td><code>{# … #}</code></td><td>Kommentar (HTML-Kommentare werden entfernt).</td></tr>
  </table>
  <p><b>HTML-Prüfung beim Übersetzen:</b> nur erlaubte Elemente (<code><?= e(implode(' ', \Core\Blocks\Template::TAGS)) ?></code>; kein <code>h1</code>, <code>img</code>, <code>svg</code>, <code>script</code>, <code>style</code>, <code>iframe</code>, Formulare), Attribute <code>class id title lang dir hidden role tabindex(0|-1) aria-* data-*</code> plus je Element (<code>a[href hreflang]</code>, <code>details[open name]</code>, <code>time[datetime]</code>, Tabellenzellen …). Keine <code>on…</code>-, <code>style</code>-, <code>target</code>/<code>rel</code>-Attribute (externe Links erhalten <code>target/rel</code> automatisch), reservierte <code>data-cms-*</code>/<code>data-edit*</code>. Tags müssen ausgeglichen sein – auch je Zweig von if/for. Platzhalter nur im Text oder in Attributwerten mit Anführungszeichen; <code>href</code>/<code>cite</code> enthalten genau einen Platzhalter (Ausgabe über sichere Links, sonst „#“) oder eine statisch geprüfte Adresse; <code>class</code>/<code>id</code> erhalten nur <code>[A-Za-z0-9_-]</code>. „&lt;“ direkt vor Platzhaltern ist verboten. Grenzen: 30 000 Zeichen, 8 Ebenen, 3000 Knoten. Fehlermeldungen mit Zeilennummer.</p>

  <h3>CSS-Regeln</h3>
  <ul>
    <li>Selektoren werden zu <code>.cblk-x SELEKTOR</code>; <code>:scope</code> = der Block, <code>:dark</code> = der Block auf dunklem Hintergrund (<code>.cblk-x.is-dark</code>). Verboten: <code>html</code>, <code>body</code>, <code>:root</code>, Nachbar-Selektoren nach <code>:scope</code>, CSS-Nesting.</li>
    <li>Erlaubt: <code>@media</code>, <code>@supports</code>, <code>@container</code>, <code>@keyframes</code> (Name → <code>cblk-x-name</code>, auch in <code>animation</code>). Verboten: <code>@import</code>, <code>@font-face</code>, <code>@layer</code> u. a., <code>url()</code> außer eigene Medien (<code>/media/…</code>, <code>/sites/…/media/…</code>, <code>/pools/…</code>), <code>expression()</code>, <code>behavior</code>, <code>-moz-binding</code>, <code>javascript:</code>, Backslash-Escapes außerhalb von Zeichenketten, <code>position: fixed</code>. Hinweis bei <code>z-index</code> &gt; 10.</li>
    <li>Design-Brücke (vorangestellt): <code>--cb-accent</code>, <code>--cb-on-accent</code>, <code>--cb-surface</code>, <code>--cb-ink</code>, <code>--cb-line</code>, <code>--cb-muted</code>, <code>--cb-radius</code>, <code>--cb-gap</code> – aus den Design-Variablen der Kits (<code>--b-*</code>, <code>--f-*</code>, <code>--e-*</code>, praxis <code>--c-*</code>); ein Kit kann sie mit <code>--cb-theme-accent</code>, <code>--cb-theme-accent-dark</code>, <code>--cb-theme-surface</code>, <code>--cb-theme-line</code>, <code>--cb-theme-muted</code>, <code>--cb-theme-radius</code> gezielt setzen. Auf dunklen Abschnitten gelten helle Werte.</li>
  </ul>

  <h3>Verhalten (ohne eigenes JavaScript)</h3>
  <table class="doc-table">
    <tr><th>Verhalten</th><th>Nutzung</th></tr>
    <tr><td><code>accordion</code></td><td><code>&lt;details&gt;&lt;summary&gt;…&lt;/summary&gt;…&lt;/details&gt;</code>; <code>name="gruppe"</code> = nur eines offen (Ersatz für Tabs). CSS: Zeiger und Fokus-Rahmen.</td></tr>
    <tr><td><code>reel</code></td><td>Klasse <code>cb-reel</code> an einer Liste: Scroll-Snap-Leiste (wischbar); mit <code>tabindex="0" role="region" aria-label="…"</code> per Tastatur scrollbar (Hinweis des Compilers).</td></tr>
    <tr><td><code>lightbox</code></td><td>Bilder mit <code>{{ bild | zoom('sizes', '1:1') }}</code> in einem Element mit <code>data-cms-lightbox</code> – Dialog und <code>media.mjs</code> des Kerns; ohne JavaScript normaler Link zum großen Bild.</td></tr>
  </table>
  <p>Kopieren in die Zwischenablage, Tabs mit Skript und Slider mit Pfeilen sind nicht vorgesehen (Folgeschritt: weitere Kern-Verhalten über <code>data-</code>-Attribute).</p>

  <h3>Export, Import, Bibliothek</h3>
  <ul>
    <li><b>JSON</b> (<code>format: mycms-block</code>): Definition inkl. Beispieldaten; Import legt immer einen Entwurf an (Kurzname bei Kollision mit Suffix).</li>
    <li><b>Netzwerk-Bibliothek</b> <code>storage/blocks/{schlüssel}.json</code>: Kopien für alle Websites (nur Netzwerk-Administration/Integratoren). Keine Live-Verknüpfung – Änderungen erreichen andere Websites erst durch erneutes Übernehmen.</li>
    <li><b>Als Kit-Block exportieren</b> (ZIP): <code>blocks/{schlüssel}.php</code> (aus der Vorlage übersetzter PHP-Renderer über <code>Core\Blocks\Runtime</code> – gleiche Ausgabe wie der Interpreter, geprüft von <code>blocks:selftest</code>), <code>css/cblk-{schlüssel}.css</code>, <code>theme-snippet.php</code> (Eintrag für <code>'blocks'</code> mit <code>'cblk' =&gt; [...]</code> und <code>conditional_css</code>), <code>block.json</code>, <code>README.txt</code>. Blocktyp im Kit: <code>{schlüssel}</code> (ohne <code>cblk_</code>); bestehende Seiten werden nicht umgestellt.</li>
  </ul>

  <h3>KI-Vorschlag</h3>
  <p><code>Generator::proposeBlock()</code> mit <code>Prompts::blockGen()</code> über <code>Assist::call('text')</code> (Kontingent, Protokoll „blockgen“): strikt JSON, danach <code>Custom::normalize()</code> + Compiler; bei Fehlern eine Korrekturrunde mit den Meldungen. Der Vorschlag füllt nur das Formular (Verlauf „KI-Vorschlag“ beim Speichern), wird nie automatisch gespeichert oder freigegeben.</p>

  <h3>Kommandozeile</h3>
  <p><code>php bin/console blocks:list [--site=…]</code> – eigene Blöcke mit Status/Version; <code>php bin/console blocks:selftest</code> – Escaping und XSS (Text, Attribute, Links, Rich-Text, Symbole; DOM-geprüft), Ablehnung unsicherer Vorlagen und CSS, Begrenzung der Selektoren, Gleichheit von Interpreter und Kit-Export.</p>
