<?php /** Entwicklerhandbuch · Chat zwischen Benutzern (Core\Chat) */ ?>
  <p class="lead">Direktnachrichten und Kanäle zwischen den Benutzern der Verwaltung – optional, <b>eine zentrale Datenbank für alle Websites</b> (Muster wie Support und Medien-Pools), live über <b>kurzlebige Server-Sent Events</b>.</p>
  <table class="doc-table">
    <tr><th>Thema</th><th>Umsetzung</th></tr>
    <tr><td>Einschalten</td><td>Funktion <code>chat</code> (<code>Core\Features</code>) – <b>Standard aus</b>. <code>'features' => ['chat' => true|false]</code> in der Website-Konfiguration hat Vorrang; ohne Angabe schaltet die Netzwerk-Administration bzw. ein Integrator den Chat unter <b>Einrichtung › System › Einstellungen der Funktionen → Chat</b> je Website ein (Einstellung <code>sys.userchat_enabled</code>, beim ersten Einschalten entsteht „#redaktion“). Dort auch: Netzwerk-Bereich (<code>meta.network</code>) und Aufbewahrung (<code>meta.retention_days</code>, Vorgabe <code>'chat_retention_days' => 180</code>, 0 = unbegrenzt).</td></tr>
    <tr><td>Rechte</td><td><code>chat.use</code> (Direktnachrichten, Kanäle der Website; einmalig der Rolle „Redaktion“ ergänzt, Merker <code>sys.userchat_roles</code>; „Administration“ hat alle Rechte), <code>chat.manage</code> (Kanäle anlegen/ändern/archivieren, Mitglieder nach Rollen und Personen, fremde Nachrichten in Kanälen entfernen). Netzwerk-Kanäle und -Direktnachrichten nur für <code>Features::integrator()</code> (Netzwerk-Administration + <code>'integrators'</code>), wenn der Netzwerk-Bereich an ist. Ohne Recht: kein Menüpunkt, kein Skript, alle Endpunkte 403.</td></tr>
    <tr><td>Speicher</td><td><code>storage/chat/chat.sqlite</code> (WAL): <code>rooms</code> (kind <code>dm|channel</code>, scope <code>site|network</code>, <code>dm_key</code> = sortierte Personen, <code>access_json</code> = Rollen/Personen), <code>messages</code> (Markdown-lite, <code>links_json</code> = Chip-Schnappschuss, <code>mentions</code>, weiches Löschen <code>deleted_at</code>), <code>reactions</code>, <code>reads</code> (Lesestand je Person und Raum), <code>mentions</code> (E-Mail-Hinweise), <code>files</code>, <code>events</code> (Änderungs-Feed), <code>people</code> (Verzeichnis, E-Mail-Einstellung), <code>meta</code>. Schema nur ergänzend (<code>CREATE … IF NOT EXISTS</code>). Bilder unter <code>storage/chat/files/JJJJ/MM/</code>. In Sicherungen <code>storage/chat/</code> mitnehmen.</td></tr>
    <tr><td>Personen</td><td><code>website:id</code> (z. B. <code>demo:3</code>), Netzwerk-Konten website-übergreifend <code>net:id</code> – dasselbe Konto auf jeder Website. Fremde Websites erscheinen mit ihrer Bezeichnung.</td></tr>
    <tr><td>Nachrichten</td><td><code>Core\Support\Markdown</code> (nie HTML), max. 4000 Zeichen, 30 Nachrichten/Minute je Sitzung. Verwaltungs-Adressen (<code>/admin/pages/{id}</code>, <code>/admin/data/{tabelle}/{id}</code>, <code>/admin/media#m{id}</code>, Support-Meldungen, Wissensartikel, Fragen, Favoriten, sonstige <code>/admin</code>-Bereiche) löst <code>Core\Chat\LinkChips</code> beim Senden zu Titel + Symbol auf (Schnappschuss aus Sicht der sendenden Person; die Zielseite prüft die Rechte selbst). Erwähnungen: „@Vollständiger Name“ von Personen des Raums. Reaktionen aus fester Auswahl (<code>Chat::REACTIONS</code>).</td></tr>
    <tr><td>Bilder</td><td>Wie im Support (<code>Tickets::IMAGE_TYPES</code>, <code>Tickets::reencode</code>): <code>getimagesize</code>, JPEG/PNG/WebP per GD neu kodiert (EXIF/GPS weg), max. 4 × 8 MB, Upload vor dem Senden (<code>POST /admin/api/chat/rooms/{id}/upload</code>), Auslieferung nur über <code>/admin/chat/datei/{id}</code> nach Raum-Prüfung (<code>nosniff</code>, <code>sandbox</code>-CSP). Nicht gesendete Bilder verfallen nach einem Tag.</td></tr>
    <tr><td>Live (SSE)</td><td><code>GET /admin/api/chat/stream</code> (<code>Core\Http\Sse</code>): Anmeldung prüfen, <b><code>session_write_close()</code> vor dem Streamen</b> (sonst blockiert die Sitzungssperre jede weitere Anfrage derselben Person), <code>ignore_user_abort</code>, Ausgabepuffer aus, <code>X-Accel-Buffering: no</code>, <code>Cache-Control: no-transform</code>, 2 KB Polster, <code>retry: 2000</code>. Die Schleife fragt etwa jede Sekunde <code>SELECT … FROM events WHERE id &gt; ? ORDER BY id LIMIT 100</code> (Primärschlüssel), filtert nach sichtbaren Räumen und sendet <code>event: chat</code> mit <code>id:</code>; Lebenszeichen alle 10 s; nach <code>'chat_stream_seconds'</code> (Standard und Maximum 25) sendet sie <code>bye</code> und schließt. <code>EventSource</code> verbindet sich nach 2 s neu und schickt <code>Last-Event-ID</code> – nichts geht verloren (Feed 2 Tage aufbewahrt).</td></tr>
    <tr><td>Abfrage-Modus</td><td>Der PHP-Entwicklungsserver <code>php -S</code> bearbeitet nur eine Anfrage gleichzeitig – ein offener Stream würde die Verwaltung blockieren. <code>Chat::transport()</code> erkennt <code>PHP_SAPI === 'cli-server'</code> (ohne <code>PHP_CLI_SERVER_WORKERS &gt; 1</code>) und liefert <code>poll</code>: der Stream antwortet 409, die Oberfläche fragt <code>GET /admin/api/chat/poll?last_id=</code> alle 3 s ab (ausgeblendeter Tab: 15 s). Erzwingen: <code>'chat_transport' => 'auto'|'sse'|'poll'</code>.</td></tr>
    <tr><td>Chat geschlossen</td><td>Kein Stream. Nur <code>GET /admin/api/chat/unread</code> alle 60 s (sichtbarer Tab oder erlaubte Browser-Hinweise) für den Zähler an „Chat“ und im Fenstertitel. Browser-Hinweise (<code>Notification</code>) erst nach ausdrücklicher Zustimmung (Glocke, <code>localStorage uc-notify</code>).</td></tr>
    <tr><td>Plesk / PHP-FPM</td><td>Jeder offene Stream belegt einen PHP-FPM-Worker für bis zu 25 s. Faustregel: <code>pm.max_children</code> ≥ gleichzeitig geöffnete Chats + 5–10 für normale Anfragen (Beispiel: 15 Personen mit offenem Chat → mindestens 25). Plesk: <i>Websites &amp; Domains → PHP-Einstellungen → FPM</i> (<code>pm = ondemand</code> oder <code>dynamic</code>, <code>pm.max_children</code>); nginx-Proxy puffert dank <code>X-Accel-Buffering: no</code> nicht, <code>proxy_read_timeout</code> (Standard 60 s) reicht. Apache mit <code>mod_deflate</code>: <code>text/event-stream</code> nicht komprimieren. Reicht die Worker-Zahl nicht, <code>'chat_transport' => 'poll'</code> setzen (Abfrage alle 3 s, keine gehaltenen Worker) oder <code>'chat_stream_seconds'</code> senken. SQLite im WAL-Modus: Lesen im Stream blockiert Schreiben nicht.</td></tr>
    <tr><td>E-Mail &amp; Aufbewahrung</td><td>Ungelesene Erwähnungen (älter als 10 min) gehen gebündelt als E-Mail raus – höchstens stündlich je Person, nur mit <code>people.notify_mail</code>, über <code>Core\Mailer</code> (außerhalb der Produktion: <code>mail_redirect</code> bzw. nur Protokoll). Nebenbei bei Chat-Aufrufen (höchstens alle 5 min) und per Cron: <code>php bin/console chat:digest</code> (z. B. alle 15 min) und <code>php bin/console chat:purge [--days=N]</code> (täglich; löscht Nachrichten, Reaktionen, Erwähnungen und Bilder nach der Frist sowie Feed-Einträge nach 2 Tagen).</td></tr>
    <tr><td>Endpunkte</td><td>Seiten <code>/admin/chat</code> (Vollbild, <code>?raum=ID</code>), <code>/admin/chat/einstellungen</code>, <code>POST /admin/chat/kanaele[/{id}[/archivieren]]</code>. JSON (CSRF per <code>X-CSRF-Token</code>): <code>GET state|unread|people|poll|stream|rooms/{id}/messages?before=</code>, <code>POST dm|prefs|rooms/{id}/messages|rooms/{id}/upload|rooms/{id}/read|messages/{id}/edit|delete|react</code> unter <code>/admin/api/chat/</code> (<code>Admin\ChatController</code>).</td></tr>
    <tr><td>Oberfläche</td><td>Eigenes Bundle <code>resources/js/userchat.js</code> + <code>resources/css/userchat.css</code>, nur geladen, wenn <code>Chat::canUse()</code> (<code>Chat::head()</code> in <code>views/layout.php</code>). Schublade rechts (≤ 700 px Vollbild, dann modal mit <code>inert</code>), <code>role="log"</code> für Nachrichten, Aktionsmenü je Nachricht, Kombinationsfelder mit <code>aria-activedescendant</code> für Personen, @Erwähnungen und Verweise; Farben nur über die Tokens der Verwaltung (Dunkelmodus, persönliche Akzentfarbe).</td></tr>
  </table>
