<?php /** Entwicklerhandbuch · Cookie-Einwilligung (Erweiterung extensions/consent_kit, Port von FriendsOfREDAXO/consent_kit, MIT) */ ?>
  <p class="lead">Einwilligungsverwaltung als Erweiterung: Dienste aus 38 Vorlagen, barrierefreie Web Component im Design der Website, 2-Klick-Platzhalter, Google Consent Mode v2, Global Privacy Control, Conversions ohne Code, Protokoll ohne IP/User-Agent. Ohne aktiven einwilligungspflichtigen Dienst bleibt alles wie im Kern: kein Hinweis, kein Skript, kein Cookie, CSP unverändert. Ausführlich: <code>extensions/consent_kit/README.md</code>.</p>
  <table class="doc-table">
    <tr><th>Baustein</th><th>Ort</th></tr>
    <tr><td>Aktivieren</td><td><code>'extensions' =&gt; ['consent_kit']</code> in <code>config/sites/{key}.php</code>; Funktion <code>consent</code> (<code>'features' =&gt; ['consent' =&gt; false]</code> schaltet ab); Recht <code>consent.manage</code>; Verwaltung → <b>Cookie-Einwilligung</b></td></tr>
    <tr><td>Daten (je Website)</td><td><code>consent_services</code> (Code-Felder, items/events/variants/hosts/csp als JSON), <code>consent_revisions</code> (Stand + Schnappschuss je Domain), <code>consent_log</code>; Einstellungen <code>consent.settings</code>, <code>consent.design</code>, <code>consent.epoch</code></td></tr>
    <tr><td>Domains</td><td><code>main</code> und <code>landing:{id}</code> (Core\Landings) – Matrix je Dienst, Varianten je Domain/Sprache, Protokoll und Stand je Domain</td></tr>
    <tr><td>Kern-Schnittstellen</td><td><code>Extension::htmlFilter()</code> (Konfiguration + Skript vor dem Seiten-Cache), <code>Extension::csp()</code> → <code>Extensions::cspSources()</code> → <code>SiteController::csp()</code> (je Anfrage, auch bei Cache-Treffern; nur Hosts, nie Schlüsselwörter), <code>Extension::footerLinks()</code> → <code>footer_links()</code> in den Fußbereichen der Kits</td></tr>
    <tr><td>Helfer</td><td><code>consent_settings_link()</code>, <code>consent_embed($dienst, $html, ['title' =&gt; …, 'ratio' =&gt; '4/3'])</code>, <code>consent_has($dienst)</code>; Block <code>consent_embed</code>; CLI <code>consent:purge [--days=N]</code>, <code>consent:status</code></td></tr>
  </table>

  <h3>CSP ohne Inline-Code</h3>
  <ul>
    <li>Konfiguration als <code>&lt;script type="application/json" id="cms-consent-config"&gt;</code>, Kern <code>consent.js</code> (≈ 4,7 KB, <code>defer</code>, vor den Kit-Skripten); Oberfläche <code>consent-ui.mjs</code> + <code>/consent/style.css</code> (Shadow DOM, per <code>&lt;link&gt;</code>) nur bei Bedarf.</li>
    <li>Inline-<code>&lt;script&gt;</code> der Dienst-Vorlagen und die JS-Felder werden serverseitig in Schritte zerlegt und als <code>/consent/js/{dienst}.{n|a|r|d}.js?l=…&amp;v=…</code> von der eigenen Domain geladen (<code>immutable</code>); externe Skripte behalten ihre Reihenfolge.</li>
    <li>Hosts eines Dienstes (<code>presets/_csp.json</code>, Hosts im Code/in URL-Angaben, „Erweitert“) kommen in <code>script-src</code>/<code>connect-src</code>/<code>img-src</code>/<code>frame-src</code>, wenn der Cookie <code>cms_consent</code> der Anfrage die Einwilligung in die aktuelle Fassung (Fingerabdruck) enthält. Nach einer neuen Einwilligung in einen Dienst mit fremden Hosts lädt die Seite einmal neu.</li>
    <li><code>frame-src</code> enthält die „Domains eingebetteter Inhalte“ aktiver Dienste, damit „Inhalt einmal laden“ ohne Einwilligung funktioniert; geladen wird trotzdem erst nach Klick.</li>
  </ul>

  <h3>Kits</h3>
  <p>Die Video-Skripte der Kits fragen <code>window.cmsConsent?.embed(anbieter)</code> (true/false; <code>null</code> = kein Dienst → bisheriges localStorage-Verhalten), melden „künftig direkt laden“ mit <code>allowEmbed()</code> und laden wartende Videos beim Ereignis <code>cms:consent</code>. Eigene Kits: <code>footer_links()</code> an die Rechtliches-Links hängen oder <code>consent_settings_link()</code> ausgeben. Design: <code>--ck-*</code>-Variablen, abgeleitet aus Core\Design (Tokens <code>background</code>, <code>text</code>, <code>muted</code>, <code>line</code>, <code>accent</code>, <code>on_accent</code>, <code>radius</code> bzw. ähnliche Namen), hell und dunkel; im eigenen Stylesheet überschreibbar (<code>consent-kit, consent-embed { --ck-accent: … }</code>).</p>

  <h3>Protokoll &amp; Speicher</h3>
  <p><code>POST /consent/save</code> (nur same-origin, Rate-Limit mit gehashter IP) protokolliert Einwilligungs-ID, Zeit, Domain, Stand, Entscheidung, Dienste, GPC und Sprache – keine IP, kein User-Agent – und bestätigt den Cookie per <code>Set-Cookie</code>. Cookie <code>cms_consent</code> und sessionStorage <code>cms_consent_dismissed</code> entstehen erst durch eine Handlung der Besucher. GPC „Als Ablehnung werten“ speichert und protokolliert nichts. Aufbewahrung: Einstellung (Standard 1095 Tage) – Cron <code>php bin/console consent:purge --site={key}</code>, zusätzlich täglich nebenbei in der Verwaltung.</p>
  <div class="doc-note"><strong>Grenzen</strong><p>Anbieter-Skripte, die selbst Inline-Code oder Inline-Styles einfügen, funktionieren unter der strengen CSP nur eingeschränkt; <code>&lt;script type="text/plain" data-consent&gt;</code> nur mit <code>data-src</code>. Nicht portiert: Cookie-Scanner, Open Cookie Database, consent_manager-Übernahme, Texte je Sprache im Backend, <code>&lt;oembed&gt;</code>-Umwandlung.</p></div>
