<?php /** Entwicklerhandbuch · Seitenbaum & Datentabellen */ ?>
  <h3>Seitenbaum</h3>
  <p>Seiten haben <code>parent_id</code> und einen zwischengespeicherten <code>path</code> (<code>Pages::rebuildPaths()</code> nach jeder Änderung). Slugs sind je Ebene eindeutig (<code>Pages::slugTaken</code>). <code>Pages::move($id, $parentId, $index, $before, $after)</code> prüft Zyklen und Kollisionen; die Stelle am besten über eine Nachbarseite (<code>$before</code>/<code>$after</code>), denn auf einer Ebene liegen auch Seiten, die der Seitenbaum nicht zeigt (Vorlagen, 404, andere Sprachen). Alte Einzel-Slugs leiten per 301 auf den neuen Pfad weiter.</p>

  <p><b>Seitenvorlagen</b> (<code>Core\PageTemplates</code>): eigene Seiten wie die Sonderseiten – <code>type = 'template'</code>, <code>template_for = '@page'</code> (nie unter eigener Adresse, nicht in Seitenbaum, Menü, Sitemap, Suche, Entwürfe, Linkauswahl). Bearbeiten nur mit <code>system.manage</code> unter <code>/_seitenvorlage/{id}?edit=1</code> (SiteController; Editor-, Einstellungs- und Löschendpunkte prüfen das ebenfalls). Liste in <code>sys.page_templates</code> <code>[{label, page, icon, description, parents}]</code>, <code>parents</code> wie die Seitenauswahl (<code>PagePicker::matches</code>). <code>PageTemplates::create($name, $vonSeite)</code> kopiert eine Seite als neue Vorlage, <code>suggested($parentId)</code> wählt vor, <code>blocks($i)</code> liefert Blöcke mit neuen IDs (auch in Spalten); nicht mehr gelistete Vorlagenseiten löscht <code>save()</code>. Ältere Verweise auf normale Seiten werden einmalig in Vorlagenseiten kopiert. Blöcke kopieren: <code>localStorage</code> <code>cms-block-clip</code> ({type, data, tunes}) im Seiten-Editor; Einfügen mit neuer ID über <code>editor.blocks.insert(…, id)</code> und <code>initialTunes</code>.</p>

  <h3>Datentabellen</h3>
  <p><code>Core\Data\Tables</code> verwaltet die Definition, <code>Core\Data\Entries</code> die Einträge. Beim Speichern einer Definition gleicht <code>Tables::sync()</code> die echte Tabelle mit <b>Doctrine DBAL 4</b> ab: neue Felder → ADD COLUMN, gleiche Feld-ID mit neuem Namen → RENAME COLUMN, entfernte Felder → DROP (nach Bestätigung), Typwechsel → ALTER (auf SQLite baut DBAL die Tabelle neu auf). Tabellen und Felder ändern darf, wer das Recht <code>data.schema</code> hat (Funktion <code>data.schema</code>; Standard: Administration). Weitere Einstellungen je Tabelle (<code>settings_json</code>): <code>kind</code> (<code>content</code> | <code>inbox</code>, nur änderbar, solange die Tabelle leer ist), URL-Basis und Detailseite, <code>list_image</code>, <code>per_page</code> (5–200), <code>workflow</code>, <code>schema_type</code>, <code>calendar</code>, <code>form</code>, <code>search</code>, Übersetzungen; je Feld <code>in_list</code>, <code>searchable</code> (Suche in der Verwaltungsliste), Bedingungen. Vorlagen unter „Neue Tabelle“: Aktuelles, Team, Produkte, Termine, Fragen &amp; Antworten, Anfragen (Eingang; nur mit Funktion <code>requests</code>) und „Leere Tabelle“; KI-Entwürfe liefert der Tabellen-Generator (siehe <a href="#ki"><?= e($aiBrand) ?></a>). Reservierte URL-Basen: admin, api, mcp, anfrage, assets, media, kits, themes, pdf, sw.js, offline, dav, .well-known, formular, vcard.</p>
  <table class="doc-table">
    <tr><th>Feldtyp</th><th>Spalte</th></tr>
    <tr><td>text, select, link, email, tel, url, iban, geo</td><td>VARCHAR(255)</td></tr>
    <tr><td>textarea, richtext, multiselect (JSON), recurrence, group (JSON-Array von Objekten)</td><td>TEXT</td></tr>
    <tr><td>date, time, color</td><td>VARCHAR(10) (sortierbar)</td></tr>
    <tr><td>datetime</td><td>VARCHAR(20) (sortierbar)</td></tr>
    <tr><td>number / bool</td><td>FLOAT / BOOLEAN</td></tr>
    <tr><td>media, file, relation</td><td>INTEGER (+ Index bei relation)</td></tr>
    <tr><td>relations</td><td>eigene Tabelle <code>data_{handle}__{feld}</code> (entry_id, target_id, sort; Primärschlüssel + Index auf target_id)</td></tr>
    <tr><td colspan="2">Systemspalten: id, slug, status, sort, created_at, updated_at, published_at, lang, translation_group; geteilte Tabellen zusätzlich origin_site, suggest.</td></tr>
  </table>
  <pre><code>use Core\Data\{Tables, Entries};
$t = Tables::find('aktuelles');
$rows = Entries::query($t, ['status' =&gt; 'published', 'where' =&gt; [['kategorie', '=', 'impfungen']],
                            'sort' =&gt; 'datum', 'dir' =&gt; 'desc', 'limit' =&gt; 3]);
foreach ($rows as $e) {
    echo Entries::title($t, $e), Entries::url($t, $e), Entries::html($t, $e, 'teaser');
}
[$id, $errors] = Entries::save($t, null, ['titel' =&gt; '…', 'tags' =&gt; [3, 5], 'status' =&gt; 'draft']);</code></pre>
  <h3 id="zweck">Zweck, Assistent und „Einsetzen“</h3>
  <p><b>Zweck</b> (<code>settings.purpose</code>, <code>Core\Data\Purpose</code>): <code>content</code> | <code>mail</code> | <code>inbox</code> | <code>registration</code> | <code>internal</code> | <code>source</code>. Er steuert nur die Oberfläche (Vorlagen im Assistenten, Reihenfolge der Bereiche in „Felder &amp; Einstellungen“ über <code>Purpose::sections()</code>, Vorschlag unter „Einsetzen“) – Speichern, Rechte und Ausgabe hängen weiter an <code>settings.kind</code> (<code>content</code>/<code>inbox</code>). Passung: Eingänge kennen <code>mail</code>, <code>inbox</code>, <code>registration</code>, Inhaltstabellen <code>content</code>, <code>registration</code>, <code>internal</code>, <code>source</code>; bei Eingängen folgt <code>mail ⇄ inbox</code> der Zustellung (<code>inbox.delivery.mode</code>). Fehlt der Zweck (ältere Tabellen), leitet <code>Tables::hydrate</code> ihn beim Lesen ab (<code>Purpose::derive</code>: Eingang → <code>mail</code> bei Zustellung „nur E-Mail“, sonst <code>inbox</code>; Inhaltstabelle mit <code>route</code> → <code>content</code>, ohne Route mit Formular → <code>registration</code>, sonst <code>internal</code>) und setzt <code>purpose_derived</code>; gespeichert wird er erst beim nächsten Speichern (<code>Tables::validate</code> → <code>Purpose::clean</code>). Keine Migration. Abgeleitet „intern“, aber auf Seiten verwendet (z. B. FAQ ohne Detailseiten) → die Einstellungsseite schlägt <code>content</code> vor.</p>
  <p><b>Assistent</b> (<code>/admin/data/new</code>, <code>Core\Data\Wizard</code>, <code>DataController::create/wizard</code>): Zweck → Vorlage (<code>DataController::presets()</code>, je Vorlage <code>purpose</code>; neu: <code>contact</code>, <code>callback</code> mit <code>delivery.mode = mail</code>, <code>registration</code>, <code>internal</code>) → Grundeinstellungen → Anlegen über <code>Tables::validate/create</code>. Zustand in der Sitzung (<code>dt_wizard</code>), alle Schritte als normale POST-Formulare (ohne JavaScript bedienbar; <code>go</code> = <code>next|back|add|up:N|down:N|ai</code>). <code>?expert=1</code> = bisheriger Tabellen-Designer, <code>?preset=…</code> springt zu den Grundeinstellungen. KI-Schritt: <code>AI\Generator::proposeTable</code> + <code>Wizard::guess()</code> (Zweck aus Wortstämmen). „Nur E-Mail“ ist kein neuer Speicherweg, sondern ein Eingang mit Zustellung <code>mail</code> (<code>Core\Data\Delivery</code>): nichts vom Inhalt in der Datenbank, nur <code>inbox_log</code> ohne personenbezogene Daten; scheitert der Versand, wird verschlüsselt gesichert (Löschfrist gilt dafür). Braucht die Funktionen <code>requests</code> + <code>requests.mail</code> und einen öffentlichen Schlüssel.</p>
  <p><b>Bereich „Verschlüsselung“</b> (<code>data/_crypto.php</code>): eine Wahl <code>settings[protection]</code> = <code>none|system|both|mail</code>, die <code>Tables::validate</code> vor allem anderen in <code>settings.kind</code> (<code>content</code> bzw. <code>inbox</code>) und <code>inbox.delivery.mode</code> übersetzt und danach verwirft (nicht gespeichert). Wechsel der Art nur bei leerer, nicht geteilter Tabelle (wie bisher, Fehler <code>settings.kind</code>). Dort auch Stand des Schlüssels (<code>FormCrypto::ready()</code>; fehlt er bei einem Eingang: Hinweis + Warnpunkt am Bereich) und S/MIME (<code>inbox.delivery.smime</code>). Die Moduswahl steht nicht mehr unter „Zustellung“; <code>_delivery.js</code> liest den Modus formularweit aus <code>settings[protection]</code>.</p>
  <p><b>Anmeldung mit Obergrenze</b>: <code>settings.form.max</code> (0 = keine, nur Inhaltstabellen). <code>DataForms::full($t)</code> zählt alle Einträge (auch Entwürfe); dann zeigt <code>render()</code> „ausgebucht“ und <code>submit()</code> lehnt ab.</p>
  <p><b>Einsetzen</b> (<code>/admin/data/{handle}/einsetzen</code>, <code>Core\Data\Placement</code>): <code>blockType()</code> → <code>data_form</code> (Eingänge, <code>mail</code>, <code>inbox</code>, <code>registration</code>), <code>data_list</code> (Inhalte) oder <code>null</code> (intern); <code>page($t, [title, parent (page:ID), menu, publish, template])</code> legt eine Seite mit dem Block an (gleiche Adressprüfungen wie „Neue Seite“, Entwurf außer mit <code>pages.publish</code>), <code>append($t, 'page:ID')</code> hängt den Block an den Entwurf einer Seite; <code>usages($t)</code> findet Blöcke mit <code>data.table</code> (auch in Layout-Spalten) und die Detailseiten-Vorlage. Rechte: Ansehen mit <code>data.schema</code>/<code>data.edit</code>, Seite anlegen mit <code>pages.manage</code>, Einfügen mit <code>pages.edit</code>.</p>
  <p><b>Felder &amp; Einstellungen</b> (<code>views/data/schema.php</code>): Bereiche mit Seitenleiste (<code>.adm-tabs-form--side</code>, <code>data-tabs</code>), Gruppen <code>.set-group/.set-list</code>; alle Feldnamen unverändert (gleicher POST wie zuvor – geprüft durch Speichern über alte und neue Oberfläche), <code>_tab</code> führt nach dem Speichern zurück in den Bereich. Prüfung: <code>php bin/console data:selftest</code> (Zweck-Ableitung und Assistent je Zweck mit vorübergehenden Tabellen).</p>

  <h3 id="bedingungen">Bedingungen je Feld</h3>
  <p>Im Tabellen-Designer unter <b>Feld → Bedingungen</b>; gespeichert in der Felddefinition, bereinigt in <code>Tables::validate</code> (<code>Rules::normalize</code>), ausgewertet zentral in <code>Core\Data\Rules::apply()</code> – aufgerufen von <code>Entries::save()</code> und damit für Verwaltung, REST-API, MCP, CalDAV/CardDAV und die öffentlichen Formulare gleich. Spiegel im Browser: <code>resources/js/_conditions.js</code> (Eintragsformular und Website-Formular).</p>
  <pre><code>'visible_if'  =&gt; ['mode' =&gt; 'all', 'rules' =&gt; [['field' =&gt; 'anrede', 'op' =&gt; '=', 'value' =&gt; 'firma']]],   // mode any = „eine davon“
'required_if' =&gt; ['mode' =&gt; 'all', 'rules' =&gt; [['field' =&gt; 'zahlungsart', 'op' =&gt; '=', 'value' =&gt; 'lastschrift']]],
'compare'     =&gt; [['op' =&gt; '&gt;=', 'field' =&gt; 'beginn', 'message' =&gt; 'Ende muss nach Beginn liegen']],</code></pre>
  <p>Operatoren: <code>= != filled empty contains &gt; &lt;</code> (Zahlen numerisch, sonst Text – ISO-Datum/Uhrzeit sortieren korrekt; Auswahl über den Kurznamen, Mehrfachauswahl „enthält“, Ja/Nein: „1“ bzw. leer). Vergleich (<code>&gt; &gt;= &lt; &lt;= = !=</code>) nur zwischen date, datetime, time, number, text; leere Werte werden nicht verglichen. <b>Ausgeblendete Felder</b> werden beim Speichern geleert und nicht geprüft, ihr Wert zählt für andere Bedingungen als leer (Ketten werden bis zum stabilen Zustand ausgewertet). Verstöße liefern Fehler je Feld – über die API als 422 mit <code>errors</code>.</p>
  <h3 id="gruppen">Wiederholbare Gruppe (<code>group</code>)</h3>
  <p>Feldtyp für Listen gleichartiger Angaben (z. B. mehrere Medikamente je Rezeptanfrage). Definition (bereinigt in <code>Tables::groupDef</code>): <code>fields</code> = Unterfelder (<code>name</code>, <code>label</code>, <code>type</code> aus <code>Tables::GROUP_TYPES</code> = text, textarea, number, select, date, email, tel, bool, iban; <code>required</code>, <code>width</code>, <code>options</code>, optional <code>labels</code>/<code>options_i18n</code>), <code>min</code> (0–20, Standard 1 bei Pflicht, sonst 0), <code>max</code> (1–50, Standard 10), <code>item_label</code>, <code>add_label</code>. Wert: Array von Objekten <code>[{"medikament": "Ibuprofen", "staerke": "400 mg"}, …]</code> – Inhaltstabellen als JSON in einer TEXT-Spalte, Eingänge im verschlüsselten <code>payload</code>.</p>
  <ul>
    <li><b>Prüfung</b> (<code>Fields::sanitize</code>, Typ <code>group</code>): leere Zeilen fallen weg, jede Zeile über <code>Fields::clean</code> je Unterfeld (Pflicht-Unterfelder, Besuchersprache über <code>Fields::$site</code>), dann Anzahl gegen min/max (Fehler, kein stilles Kürzen). Fehlerschlüssel: <code>feld</code> (Anzahl) und <code>feld.position.unterfeld</code> (Position wie gesendet).</li>
    <li><b>Bedingungen</b>: Andere Felder können eine Gruppe nur mit „ist ausgefüllt / ist leer“ (mindestens eine Zeile) prüfen (<code>Rules::normalize</code> erzwingt das); Bedingungen je Unterfeld gibt es nicht.</li>
    <li><b>Verwaltung</b>: Tabellen-Designer mit Unterfeld-Editor (Hinzufügen, ↑ ↓, Entfernen); Eintragsformular wie der Repeater der Einstellungen (einklappbare Karten); Listenspalte „Ibuprofen, Paracetamol +1“ (<code>Entries::groupSummary</code>).</li>
    <li><b>Öffentliche Formulare</b>: <code>DataForms::group()</code> (auch vom Kit „praxis“ mit eigenen Klassen genutzt) – Fieldset mit Legende, je Zeile ein Fieldset „{item_label} {n}“, „+ {add_label}“ und „Entfernen“ (<code>resources/js/_group.js</code>, ≈ 1,2 KB: nummeriert Namen/IDs neu, Fokus in die neue Zeile, Live-Region). Ohne JavaScript: <code>max(min, 3)</code> Zeilen (höchstens max); die über <code>min</code> hinausgehenden stehen in <code>&lt;noscript&gt;</code>.</li>
    <li><b>Ausgabe</b>: <code>Entries::html</code> als Liste (<code>ul.dt-group</code>, erster Wert, dann „Beschriftung: Wert“), <code>Entries::text</code> eine Zeile je Eintrag. Eingang: Anzeige als kleine Tabelle (leere Spalten entfallen), Kopieren als nummerierte Zeilen; alte Einzelwerte (Feld war früher Text) erscheinen weiter als Text. API <code>GET /data</code>: <code>fields[].group</code> mit Unterfeldern, min, max.</li>
  </ul>
  <p>Filter auf Verknüpfungen akzeptieren ID, Slug oder Titel des verknüpften Eintrags. Beim Löschen werden Fremdschlüssel auf <code>NULL</code> gesetzt und n:m-Zeilen entfernt; <code>Entries::backlinks()</code> liefert Rückverweise.</p>

  <h3 id="layout">Abschnitte und Freitext im Formular (<code>section</code>, <code>content</code>)</h3>
  <p>Gestaltungs-Elemente der Definition (<code>Tables::LAYOUT</code>, Spaltentyp <code>layout</code> in <code>Tables::TYPES</code>): Sie stehen in <code>fields_json</code> zwischen den Feldern, haben aber <b>keine Spalte</b> und keinen Wert. Definition (bereinigt in <code>Tables::layoutDef</code>): <code>section</code> – <code>label</code> (Überschrift, Übersetzungen in <code>labels</code>), <code>help</code> (Beschreibung, bis 500 Zeichen), <code>style</code> = <code>heading</code> (Standard) | <code>fieldset</code>; <code>content</code> – <code>text</code> (Rich-Text, <code>Sanitizer::block</code>, nicht leer). <code>required</code>, <code>in_list</code>, <code>searchable</code> sind immer <code>false</code>; Bedingungen gibt es nicht. Kurznamen sind wie bei Feldern eindeutig.</p>
  <ul>
    <li><b>Laden</b>: <code>Tables::find()</code> liefert in <code>$t['fields']</code> nur die <b>Datenfelder</b> – Listen, Filter, Sortierung, Suche, Schnittstelle/MCP, Detailseiten, Feldbindung, Prüfung (<code>Entries::schema</code>), Kalender, Push, Clamp, Verknüpfungen sehen Gestaltung so nie. <code>Tables::allFields($t)</code> gibt alle Elemente in der Reihenfolge des Designers (aus <code>$t['fields_all']</code>; maßgeblich für die Datenfelder bleibt <code>$t['fields']</code>). <code>Tables::isLayout($f)</code>, <code>Tables::dataFields($list)</code>.</li>
    <li><b>Speichern</b>: <code>Tables::validate()</code> gibt in <code>fields</code> alle Elemente zurück (Speicherformat); Einstellungen (Titel-Feld, Kalender, Suche, Push …) und <code>Rules::normalize</code> sehen nur Datenfelder. <code>Tables::sync()</code> überspringt <code>layout</code> – Hinzufügen/Entfernen ändert das Schema nicht; <code>droppedFields()</code> meldet ein Datenfeld, das zum Abschnitt/Freitext wird. Wer eine Definition neu schreibt, nimmt <code>Tables::allFields($t)</code> bzw. <code>Tables::toInput($t)</code>, sonst gehen Abschnitte verloren.</li>
    <li><b>Öffentliches Formular</b>: <code>DataForms::items($t)</code> (Datenfelder wie <code>fields()</code> plus Gestaltung, die immer dabei ist – <code>selected()</code>), <code>DataForms::sections()</code> gliedert: je Abschnitt <code>&lt;fieldset class="dff-sec dff-sec--heading|--fieldset"&gt;&lt;legend class="dff-sec__title"&gt;</code>, Beschreibung <code>p.dff-sec__desc</code> (über <code>aria-describedby</code>), darin ein eigenes <code>.dff-grid</code>; Freitext <code>div.dff-text.prose</code> über <code>rich()</code>. Leere Abschnitte entfallen. Annahme und Prüfung (<code>submit</code>, Zustellung, Bestätigung) nutzen nur <code>fields()</code>. Stile in <code>resources/css/_dataform-layout.css</code> (von Kern und allen Kit-<code>dataform.css</code> importiert); Kits setzen <code>--dff-sec-line</code>, <code>--dff-sec-radius</code>, <code>--dff-sec-bg</code>, <code>--dff-ink</code>, <code>--dff-muted</code>.</li>
    <li><b>Redaktion</b>: <code>Entries::formSchema($t)</code> – Abschnitt als <code>heading</code> (Hilfe darunter), Freitext als <code>heading</code> ohne Beschriftung mit <code>html</code> (Fields rendert <code>div.f-help.f-richnote</code>). Tabellen-Designer: <code>data-show-for</code>/<code>data-hide-for</code> je Typ, Freitext mit der Formatierungsleiste (<code>fields[i][text]</code>); Seitenleiste „Felder bearbeiten“ (<code>SchemaPanel</code>): Abschnitt anlegen, Darstellung, Reihenfolge – der Text eines Freitexts bleibt unverändert.</li>
    <li><b>Selbsttest</b>: <code>Core\Data\LayoutSelfTest</code> in <code>php bin/console data:selftest</code> (keine Spalte, Ausschluss aus Schema/Schnittstelle/Suche, Rundlauf, Rückfrage beim Typwechsel, Formular-HTML, Absenden, Eingabemaske).</li>
  </ul>

  <h3 id="kernbloecke">Kern-Blöcke</h3>
  <p>Definiert in <code>app/Blocks/blocks.php</code>, gerendert von <code>app/Blocks/{typ}.php</code>; jedes Kit bekommt sie (<code>core_blocks =&gt; false</code> schaltet ab), überschreibt sie mit eigenem Renderer und stylt sie mit <code>assets/css/data.css</code>, <code>calendar.css</code>, <code>dataform.css</code>, <code>extra.css</code> (die Kern-CSS unter <code>resources/css</code> lässt sich per <code>@import</code> erweitern). <code>data_list</code>, <code>calendar</code> und <code>upcoming</code> haben zusätzlich <code>eyebrow/title/intro</code> und – bei geteilten Tabellen – <code>source</code>; Filter-Operatoren von <code>data_list</code>: <code>= != contains &gt;= &lt;= current same</code>.</p>
  <table class="doc-table">
    <tr><th>Block</th><th>Daten</th></tr>
    <tr><td><code>data_list</code></td><td>table, fields (<code>tabelle.feld</code>), layout (cards|list|compact|table|directory), columns, ratio, limit, image_fit (''|cover|contain – Klasse <code>dl-img--contain</code>; leer = im Verzeichnis eingepasst), Besucher-Filter: visitor_filter / visitor_filter2 (<code>tabelle.feld</code> eines select-/multiselect-Felds → Schaltflächen <code>.dl-filter .dl-fchip</code> mit <code>aria-current</code>, Parameter <code>?{feld}={option}</code>), visitor_search (<code>?q=</code> → <code>Entries::query(['q' =&gt; …])</code>), az_index (sortiert nach dem Titelfeld, Gruppen <code>.dl-az__head</code> mit Sprungleiste <code>.dl-az</code>; nur ohne paginate, nicht bei table) – serverseitig per GET (Anfragen mit Parametern umgehen den Seiten-Cache), Blättern behält die Auswahl; Etiketten im Verzeichnis <code>.dl-chip.dl-tone-{1…5}</code> nach Position der Option; CSS <code>resources/css/_data-directory.css</code>, paginate (<code>?seite=</code>), filter_field/op/value (op <code>current</code> = verknüpft mit aufgerufenem Eintrag, <code>same</code> = gleicher Wert wie beim aufgerufenen Eintrag), exclude_current, sort_field/dir, link_detail, more_label/more_link, empty_text, text_lines (''|2|3|4|6) und title_lines (''|2|3): Textlänge/Titel kürzen über <code>Core\Data\Clamp</code> – <code>Clamp::text($t, $e, $feld, $d)</code> liefert <code>[Klassen, HTML]</code> (Text-, mehrzeilige und Rich-Text-Felder gekürzt als maskierter reiner Text mit Auszug ≤ Zeilen × 120 Zeichen), <code>Clamp::titleClass($d)</code> die Klassen der Überschrift; CSS <code>.dl-clamp .dl-clamp-{n}</code> (line-clamp, keine Inline-Stile wegen CSP) in <code>resources/css/_data-clamp.css</code> – Kits mit eigenem <code>data.css</code> importieren die Datei. Selbsttest: <code>blocks:selftest</code></td></tr>
    <tr><td><code>data_fields</code></td><td>table, fields, layout (head|prose|dl|image|profile|contact – <code>profile</code>: erstes Bildfeld eingepasst auf Kachel <code>.df-img--contain</code>, Titel als H1, select/multiselect als <code>.dl-chip.dl-tone-*</code>, übrige Felder als Einleitung; <code>contact</code>: Textfelder als <code>&lt;address&gt;</code> (eine 4–5-stellige PLZ steht mit der folgenden Zeile zusammen), tel/email/url/link als Links mit Symbol, geo als Karte), show_labels, ratio, back_label/back_link</td></tr>
    <tr><td><code>data_form</code></td><td>table, eyebrow/title/intro, submit_label, success_text – öffentliches Formular der Tabelle (Inhaltstabellen: Funktion <code>forms.data</code>; Eingangs-Tabellen: Funktion <code>requests</code>, siehe unten)</td></tr>
    <tr><td><code>calendar</code></td><td>table (Kalender-Tabelle), view (month|agenda), filter_field/filter_value, visitor_filter (Links je Kategorie, <code>?kategorie=</code>), subscribe, link_detail, empty_text – blättern mit <code>?monat=JJJJ-MM</code></td></tr>
    <tr><td><code>upcoming</code></td><td>table, limit, days (0 = bis 1 Jahr), filter_field/filter_value, layout (list|compact), show_location, link_detail, subscribe, more_label/more_link, empty_text</td></tr>
    <tr><td><code>map</code></td><td>eyebrow, title, location (site|custom), point (geo), label, address, zoom, height (s|m|l), style, route – siehe <a href="#karten">Karten</a></td></tr>
    <tr><td><code>gallery</code></td><td>eyebrow/title/intro, source (manual|collection), collection, images [image, caption], layout (grid|masonry|justified), columns 2–5, ratio, captions, lightbox</td></tr>
    <tr><td><code>slideshow</code></td><td>eyebrow/title/intro, source, collection, slides (max. 12: image, eyebrow, title, text, button_label/link, position, overlay), height, transition, arrows, dots, loop, autoplay, interval</td></tr>
    <tr><td><code>stack_cards</code></td><td>eyebrow/title/intro, cards (max. 8: eyebrow, title, text, image, link_label, link), ratio, image_side (end|start|alternate)</td></tr>
    <tr><td><code>dials</code></td><td>eyebrow/title/intro, items (max. 6: value, unit, label, text, level 0–100, number, max), size (s|m|l), style (arc|ticks|minimal), animate. Bogen = <code>level</code> ÷ 100, sonst <code>number</code> (oder die Zahl aus <code>value</code>) ÷ <code>max</code>, sonst Prozentwert (<code>value</code> endet auf „%“ oder <code>unit</code> = „%“), sonst neutrale Skala. SVG (270°, <code>pathLength="100"</code>, <code>stroke-dasharray</code> serverseitig) und sichtbare Texte <code>aria-hidden</code>, ein Satz für Screenreader. CSS <code>resources/css/dials.css</code> nur mit dem Block (Kit-Ersatz: <code>css/dials.css</code>); Farben über <code>--dial-accent</code>, <code>--dial-track</code>, <code>--dial-tick</code>, <code>--dial-surface</code>, <code>--dial-line</code>, <code>--dial-ink</code>, <code>--dial-muted</code>, <code>--dial-font</code> (sonst Zuordnung je Kit über <code>.cms-dials--t-{theme}</code>). Hochzählen: <code>js/dials.mjs</code> (&lt; 0,5 KB, nur mit animate, ganze Zahlen; Anfangszustand nur bei <code>@media (scripting:enabled)</code> ohne reduzierte Bewegung). Feldnamen wie <code>stats</code>/dials im Kit „essenz“.</td></tr>
    <tr><td><code>partners</code></td><td>eyebrow/title/intro, source (manual|table), sort (manual|name|category|field|random), items (max. 60: logo, name, info [inline], link, link_label, category, scale -1|0|1, mono), table, map_logo/map_name/map_info/map_link/map_category/map_mono (<code>tabelle.feld</code>, Feldtyp <code>datafield</code> mit <code>'types'</code>; leer = Bildfeld, Titel, Beschreibung, erstes Link-Feld), filter_field/op (= != contains)/value, limit, sort_field/dir, columns 3–6, ratio (3:2|1:1|2:1), size (s|m|l), tile (soft|light|none), gray, invert (marked|all|off), group, details (inline|dialog|off). Logo-Breite flächengleich: <code>Core\Blocks\PartnerLogos::width()</code> → Klasse <code>pl-w-{6–100}</code> (setzt <code>--pl-w</code>). Details: Sprung-Links → <code>&lt;button aria-expanded aria-controls&gt;</code> (<code>js/partners.mjs</code>, ca. 3 KB, nur mit dem Block), ohne JS Liste. CSS <code>resources/css/partners.css</code> nur mit dem Block (Kit-Ersatz: <code>css/partners.css</code>) – siehe <a href="#partner-logos-kit">Kits</a>.</td></tr>
  </table>

  <h3>Detailseiten &amp; Feldbindung</h3>
  <p>Eine Vorlage ist eine Seite mit <code>type = template</code> und <code>template_for = handle</code>. Beim Aufruf von <code>/{url-basis}/{slug}</code> setzt der Router <code>app()-&gt;entry</code> und rendert die Vorlage. Vor dem Rendern jedes Blocks (<code>Theme::bindEntry</code>):</p>
  <ul>
    <li><b>Feldbindungen</b> in <code>data._bind</code>, z. B. <code>{"image": "bild", "title_strong": "_title", "button_link": "_url"}</code>: Der Wert wird passend zum Zieltyp umgewandelt (<code>Entries::bindValue</code>); ohne Datensatz gilt der eingetragene Wert. Welche Quellen zu welchem Typ passen, legt <code>Entries::bindable()</code> fest. Sonderquellen: <code>_title</code>, <code>_url</code>, <code>published_at</code>, <code>_ics</code> (Termin als .ics); im Block „Datensatz-Felder“ zusätzlich <code>_when</code> (Datum, Uhrzeit, Wiederholung) und <code>_origin</code> (Ursprungs-Website geteilter Einträge).</li>
    <li><b>Platzhalter</b> <code>{{feld}}</code> in Textfeldern (HTML-sicher in Rich-Text-Feldern).</li>
  </ul>
  <p>Im Editor übergibt <code>editor.js</code> den Vorschau-Eintrag an <code>/admin/api/preview</code> und <code>/admin/api/block-form</code>; das Formular zeigt dann neben passenden Feldern die Bindungsschalter (<code>Fields::$binding</code>). SEO der Detailseite: <code>Seo::forEntry()</code> (Titel, Beschreibungs-Feld, Bild-Feld, Canonical); Einträge stehen in der Sitemap.</p>

