<?php /** Entwicklerhandbuch · Staging & Deploy */ ?>
  <p class="lead">Code kommt per Release mit atomarem Umschalten und Rollback auf den Server, Inhalte entstehen live. Staging ist eine eigene Installation mit Kopie der Live-Inhalte. Anleitung mit Plesk-Einrichtung: <code>deploy/README.md</code>.</p>
  <pre><code>deploy/deploy.sh staging                 # bauen, hochladen, migrieren, prüfen, umschalten
deploy/deploy.sh production              # zusätzlich vorher Sicherung (Websites, Pools, geteilte Tabellen)
deploy/deploy.sh production --rollback   # vorheriges Release aktivieren (nur Symlink, Datenbank bleibt)
deploy/sync-content.sh default           # Datenbank + Medien einer Website: Live → Staging</code></pre>
  <ol class="doc-steps">
    <li><b>Ziele</b>: <code>deploy/targets/{ziel}.env</code> (aus <code>example.env</code>, nicht versionieren): <code>SSH_TARGET</code> (oder <code>local</code>), <code>BASE</code>, <code>URL</code>; optional <code>PHP</code>, <code>KEEP</code> (Releases, Standard 5), <code>SITES</code> (Standard <code>--all</code>), <code>SSH_OPTS</code>, <code>RSYNC_OPTS</code>, <code>CURL_OPTS</code>, <code>RELOAD_CMD</code> (z. B. FPM neu laden), <code>SKIP_BUILD</code>, <code>SKIP_BACKUP</code>.</li>
    <li><b>Ablauf</b>: Build (Composer ohne Dev-Pakete, pnpm) → Upload nach <code>releases/&lt;zeit&gt;-&lt;rev&gt;</code> → gemeinsame Daten verlinken (<code>shared/</code>: <code>config.local.php</code>, <code>config/sites</code>, <code>storage</code> inkl. <code>pools</code>/<code>shared</code>/<code>support</code>, Medienordner) → bei production Sicherung (<code>site:backup</code>, <code>pool:backup --all</code>, <code>shared:backup --all</code>) → <code>migrate</code> → <code>extensions:publish</code> → <code>health</code> (jeweils für <code>SITES</code>). Erst wenn alles grün ist, wird <code>current</code> atomar umgeschaltet; danach <code>cache:clear --all</code>, optional <code>RELOAD_CMD</code>, Rauchtest auf <code>/health</code> (bei Fehler automatischer Rollback) und Aufräumen auf <code>KEEP</code> Releases. Schlägt migrate/health fehl, wird das neue Release verworfen.</li>
    <li><b>Schema-Änderungen</b> laufen vor dem Umschalten gegen die Live-Datenbank und sind deshalb <b>additiv</b> – so funktioniert auch das vorherige Release nach einem Rollback.</li>
    <li><b>Staging</b>: <code>'environment' =&gt; 'staging'</code> → noindex (Meta, Header, robots.txt), gestreifte Hinweisleiste in der Verwaltung, E-Mails nur an <code>'mail_redirect'</code> (sonst nur protokolliert), optional HTTP-Basic-Schutz <code>'staging_auth'</code> (ausgenommen <code>/api/</code>, <code>/mcp</code>, <code>/health</code>, <code>/dav</code>, <code>/.well-known/</code>). Dasselbe gilt für <code>development</code>.</li>
    <li><b>Inhalte holen</b>: <code>sync-content.sh &lt;site&gt;</code> braucht <code>production.env</code> und <code>staging.env</code>, sichert live (<code>site:backup</code>) und spielt die Sicherung auf Staging ein (<code>site:restore --force</code>, überschreibt auch Konten). Pools und geteilte Tabellen werden nicht übertragen.</li>
    <li><b>CI im Projekt-Repository</b>: Vorlage <code>deploy/github-actions/deploy.yml.example</code> nach <code>.github/workflows/deploy.yml</code> des eigenen Website-Repositorys kopieren – Push auf <code>main</code> → Staging, Production manuell mit Freigabe (GitHub Environments); PHP-Syntaxprüfung, PHP 8.4, Node 22, pnpm 10. Secrets je Umgebung: <code>DEPLOY_SSH_KEY</code>, <code>DEPLOY_KNOWN_HOSTS</code>, <code>DEPLOY_ENV</code> (Inhalt der <code>.env</code>, mindestens <code>SSH_TARGET</code>, <code>BASE</code>, <code>URL</code>). Das KLXM-Studio-Repository selbst deployt nicht: Es prüft nur (<code>.github/workflows/ci.yml</code>) und baut bei Tags <code>v*</code> das Installations-ZIP für GitHub Releases (<code>release.yml</code>).</li>
  </ol>
  <p><code>GET /health</code> liefert <code>{"ok", "version", "environment"}</code> ohne Geheimnisse (HTTP 503 bei Fehlern; geprüft: Datenbank, Schreibrechte). <code>php bin/console health</code> prüft zusätzlich PHP-Version und Erweiterungen, <code>app_key</code>, <code>network_key</code>, Kit-Kompatibilität, geteilte Tabellen, Suchindex und – wenn eingeschaltet – jede KI-Fähigkeit (Exit-Code 1 bei Fehlern).</p>
  <h3 id="migrate-kits">Umstellung <code>themes/</code> → <code>kits/</code> (einmalig)</h3>
  <p>Mit <code>deploy/deploy.sh</code> ist nichts zu tun – jedes Release bringt <code>kits/</code> aus dem Repository mit. Installationen, die Code direkt in den Ordner hochladen (ohne Releases, <code>APP_DIR</code>), stellen nach dem Hochladen des neuen Codes einmal um: <code>deploy/migrate-kits.sh &lt;ziel&gt; [--dry-run] [--no-symlink]</code> (lokal: <code>--local [ordner]</code>). Das Skript sichert <code>themes/</code> und <code>public/themes/</code> nach <code>storage/backups/themes-&lt;zeit&gt;.tar.gz</code>, verschiebt sie nach <code>kits/</code> bzw. <code>public/kits/</code> (nur fehlende Kits, wenn <code>kits/</code> schon existiert), legt Übergangs-Links <code>themes → kits</code> an und führt <code>cache:clear --all</code> und <code>health --all</code> aus. Der Kern braucht die Links nicht (Rückfall in <code>Core\Kit</code>, 301 von <code>/themes/…</code> auf <code>/kits/…</code> in <code>public/index.php</code>); mehrfaches Ausführen ändert nichts.</p>
  <h3 id="migrate-assets">Umstellung <code>public/</code> → <code>/assets/</code> (einmalig)</h3>
  <p>Jeder Ordner ganz oben in <code>public/</code> sperrt die gleichnamige Seitenadresse: Apache und nginx liefern dort den Ordner (301 auf <code>/kits/</code>, danach 403) statt der Seite. Deshalb liegen Code- und Design-Dateien jetzt unter <code>/assets/</code>; ganz oben bleiben nur <code>index.php</code>, <code>assets/</code> und die Upload-Ordner (ihre Adressen stehen in Inhalten). Die zentrale Pfad-API ist <code>Core\PublicPaths</code> (dazu <code>Kit::publicDir()/url()</code>, <code>Extension::asset()/publicDir()</code>, <code>Fonts::dir()/url()</code>).</p>
  <table class="doc-table">
    <tr><th>Früher</th><th>Jetzt</th></tr>
    <tr><td><code>public/kits/{kit}/</code>, <code>public/themes/{kit}/</code></td><td><code>public/assets/kits/{kit}/</code> – Adresse <code>/assets/kits/{kit}/…</code></td></tr>
    <tr><td><code>public/extensions/{name}/</code></td><td><code>public/assets/ext/{name}/</code> (<code>pnpm build</code>, <code>extensions:publish</code>)</td></tr>
    <tr><td><code>public/fonts/</code> (installierte Schriften)</td><td><code>public/assets/fonts/installed/</code> – eigener Unterordner, weil <code>public/assets/fonts/</code> die Kern-Schrift Lato enthält</td></tr>
    <tr><td><code>public/media/</code>, <code>public/pools/</code>, <code>public/sites/</code></td><td>unverändert</td></tr>
  </table>
  <p>Gesperrte Seitenadressen ganz oben (Hauptsprache): <code>admin</code>, <code>api</code>, <code>anfrage</code>, <code>assets</code>, <code>media</code>, <code>pools</code>, <code>sites</code>, <code>sitemap-xml</code>, <code>robots-txt</code>, <code>home</code>, <code>index-php</code> (<code>PublicPaths::RESERVED_SLUGS</code>) – dazu jeder Ordner, der noch in <code>public/</code> liegt. Nach der Umstellung sind <code>/kits</code>, <code>/themes</code>, <code>/extensions</code> und <code>/fonts</code> als Seiten frei.</p>
  <ol class="doc-steps">
    <li><b>Rückfall:</b> Neuer Code auf einem Server mit alten Ordnern läuft ohne Umstellung weiter – liegt ein Kit, eine Erweiterung oder der Schriften-Ordner nur am alten Ort, erzeugt der Kern Adressen dorthin. <code>health</code> meldet die alten Ordner als Hinweis (kein Fehler).</li>
    <li><b>Umstellen</b> (Installationen ohne Releases, nach dem Hochladen des neuen Codes): <code>php bin/console assets:migrate --dry-run</code>, dann <code>php bin/console assets:migrate</code>. Sichert die alten Ordner nach <code>storage/backups/public-assets-&lt;zeit&gt;.tar.gz</code> (außerhalb des Webroots), verschiebt sie, entfernt Übergangs-Links (<code>public/themes → kits</code>), verlinkt geteilte Ordner außerhalb des Webroots neu (z. B. <code>public/fonts → …/shared/public/fonts</code>) und leert den Seiten-Cache. Liegt ein Kit an zwei Orten, gewinnt die neueste Fassung; die andere landet in <code>storage/backups/public-assets-alt-&lt;zeit&gt;/</code>. Zum Schluss listet der Befehl fest eingetragene alte Adressen (<code>/kits/…</code>, <code>/extensions/…</code>) in Kits und Erweiterungen. Mehrfaches Ausführen ändert nichts.</li>
    <li><b>Deploy mit Releases</b> (<code>deploy/deploy.sh</code>): jedes Release bringt <code>public/assets/</code> mit; installierte Schriften bleiben in <code>shared/public/fonts</code> und werden als <code>public/assets/fonts/installed</code> verlinkt. Nichts zu tun.</li>
    <li><b>Alte Adressen</b> in zwischengespeicherten Seiten, Stylesheets oder fremden Verweisen (<code>/kits/…</code>, <code>/themes/…</code>, <code>/extensions/…</code>, <code>/fonts/…</code>) leitet <code>public/index.php</code> mit 301 auf <code>/assets/…</code> um – nur wenn die Datei dort liegt. Eine Seite <code>/kits</code> bleibt dadurch erreichbar. Apache (<code>FallbackResource</code>) braucht keine Regel; nginx: fehlende Dateien müssen an PHP gehen (<code>try_files … /index.php</code>, siehe <a href="#installation">Installation</a> – Cache-Regeln nur noch für <code>/assets/</code>).</li>
    <li><b>Eigene Kits und Erweiterungen:</b> Adressen nie fest eintragen – in CSS relativ (<code>url(../fonts/x.woff2)</code> gilt unverändert), in PHP <code>app()-&gt;theme-&gt;asset()</code>, <code>Kit::url()</code>, <code>$ext-&gt;asset()</code>. Eigene Build-Skripte schreiben nach <code>Kit::publicDir($kit)</code> bzw. <code>public/assets/kits/{kit}</code>.</li>
  </ol>
