<?php /** Entwicklerhandbuch · Bearbeiten auf der Website: Editor, Einträge, Shadow-DOM-Isolation */ ?>
  <p class="lead">Seiten und Einträge werden direkt auf der Website bearbeitet. Für Besucher entsteht dabei <b>kein</b> zusätzliches Markup, Skript oder Stylesheet – alles Folgende wird nur für Angemeldete ausgegeben, der Seiten-Cache bleibt unverändert.</p>
  <h3>Seiten-Editor (<code>?edit=1</code>)</h3>
  <ul>
    <li><b>Grundlage:</b> Editor.js (<code>public/assets/vendor/editorjs</code>) mit editorjs-drag-drop; eigene Oberfläche in <code>resources/js/editor.js</code>, Kit-Partial <code>templates/partials/editor.php</code>. Jeder Block ist ein Editor.js-Block <code>{id, type, data, tunes}</code>; die Vorschau rendert der Server mit dem echten Kit-Renderer.</li>
    <li><b>Endpunkte</b> (CSRF): <code>POST /admin/api/preview</code> (Block-HTML, optional mit Vorschau-Eintrag für Detailseiten), <code>POST /admin/api/block-form</code> (Feldformular aus dem Block-Schema), <code>GET /admin/api/links</code> (Linkauswahl), <code>POST /admin/api/pages/{id}/save</code> (Entwurf bzw. <code>publish</code>, Revision), <code>POST /admin/api/pages/{id}/discard</code>.</li>
    <li><b>Abschnitts-Optionen</b> (<code>Theme::TUNES</code>): background, anchor, visible, showInNav, navLabel, spaceTop, spaceBottom, divider (oben), height (<code>screen</code> = Vollbild), align, bgImage, overlay (dark/light), row (veraltet, nur Darstellung alter Reihen – <a href="<?= e(url('/admin/hilfe/technik#reihen')) ?>">umstellen</a>), noGlossary – Ausgabe über das Partial <code>section</code> bzw. <code>$b-&gt;tune()</code>; Vollbild/Hintergrundbild laden <code>css/sections.css</code>, alte Reihen <code>css/rows.css</code>. Blöcke nebeneinander: Block <a href="<?= e(url('/admin/hilfe/technik#layout')) ?>">„Layout“</a> (<code>css/layout.css</code>).</li>
    <li id="auswahl"><b>Auswählen statt Öffnen:</b> Ein Klick/Tipp in einen Block setzt nur <code>.is-selected</code> (<code>selectBlock()</code>, Erfassungsphase von <code>pointerdown</code> und <code>focusin</code>; Klicks in Werkzeugleiste, Ebene und Eintrags-Seitenleiste ändern die Auswahl nicht) – Block-Leiste und „+ Block einfügen“ bleiben dann auch ohne Hover sichtbar (Touch). Die Seitenleiste öffnet nur: „Bearbeiten“ in der Block-Leiste (Tastatur: <kbd>Tab</kbd> + <kbd>Enter</kbd>), „Inhalte eingeben“ (<code>[data-cms-open]</code> im Hinweis leerer Blöcke), der Block-Tune „Abschnitt &amp; Navigation …“, ein neuer Block ohne <code>[data-edit]</code> und der <a href="#sprung-zum-block">Sprung zu einem Block</a>. Klick auf Inhalte ohne Direktbearbeitung (auch <code>[data-central]</code>) ruft <code>hintEdit()</code>: Hinweis in der Leiste (<code>.cms-block__hint</code>) und kurzes Pulsieren von „Bearbeiten“. <code>[data-edit]</code>, die Knöpfe am Bild (<code>.cms-imgtools</code>, Ebene) und der Stift je Eintrag (<code>[data-entry-edit]</code>, Erfassungsphase) arbeiten unverändert.</li>
    <li id="block-einfuegen"><b>„+ Block einfügen“ unten am Block:</b> Host <code>.cms-block__add</code> im Block (eigenes Shadow DOM, Knopf <code>.cms-addbtn</code>), mittig auf der Unterkante (<code>translate(-50%,50%)</code>; bis 600 px ganz im eigenen Block, damit er die Leiste des nächsten nicht berührt). Sichtbar und klickbar nur bei <code>:hover</code>, <code>.is-selected</code> oder <code>:focus-within</code> des Blocks, sonst <code>pointer-events: none</code>. Die Auswahl (<code>BlockPicker</code>, <code>.cms-addpop</code> in der Ebene, <code>role=dialog</code> mit Suchfeld und <code>role=listbox</code>) listet die einfügbaren Blocktypen wie das „+“ von Editor.js (<code>insertable !== false</code>) und fügt mit <code>editor.blocks.insert(type, {}, undefined, index + 1)</code> nach dem Block ein – beim letzten am Ende. Neuer Block: Fokus auf das erste <code>[data-edit]</code>, ohne solches öffnet sich die Seitenleiste; die Live-Region der Werkzeugleiste meldet das Einfügen.</li>
    <li><b>Bedienung:</b> <kbd>⌘</kbd>/<kbd>Strg</kbd>+<kbd>S</kbd> speichert, <kbd>Alt</kbd>+<kbd>↑</kbd>/<kbd>↓</kbd> verschiebt den Block der offenen Seitenleiste, <kbd>Esc</kbd> schließt sie; Kompaktansicht und eingeklappte Blöcke merkt sich der Browser (localStorage). Inline-Felder (<code>$b-&gt;edit('pfad')</code>) nehmen eingefügten Text ohne Formatierung; Rich-Text-Felder bekommen die Formatierungsleiste (inkl. „✦ KI“, wenn freigeschaltet).</li>
    <li><b>Veröffentlichungssperre:</b> Enthalten Entwurf, Titel oder Beschreibung Platzhalter <code>[bitte ergänzen: …]</code>, wirft <code>Pages::publish()</code> eine Ausnahme (Editor, Seitenliste, REST und MCP melden 422).</li>
    <li id="sprung-zum-block"><b>Sprung zu einem Block:</b> <code>?edit=1#b-{blockId}</code> (oder <code>?edit=1&amp;block={blockId}</code>, auch die Sprungmarke <code>anchor</code> des Abschnitts) klappt den Block auf, scrollt ihn in die Mitte, hebt ihn kurz hervor (<code>.is-target</code>), markiert <code>[Platzhalter]</code> darin über die CSS Custom Highlight API (<code>::highlight(cms-placeholder)</code>, DOM bleibt unverändert) und öffnet ab 1101 px Breite die Felder in der Seitenleiste. Genutzt von der Platzhalter-Liste: <code>Core\Dashboard\Metrics::placeholders($db, $ok, $max, $page)</code> sucht je Block in allen Texten (verschachtelt, ohne HTML) der veröffentlichten Fassung nach <code>Metrics::PLACEHOLDER_RX</code> (Klammer mit Buchstabe am Anfang, auch klein, keine Markdown-Links <code>[Text](url)</code>) und liefert Seite, Block-ID, Blocktyp und Adresse; <code>Metrics::placeholderEditUrl($hit)</code> baut den Sprung. Ansicht <code>app/Admin/views/pages/_placeholders.php</code> in „Was ist zu tun?“ (Recht <code>pages.edit</code>, <code>settings.edit</code> oder Administration) und oben in den Seiteneinstellungen (<code>#platzhalter</code>). „Ist gewollt“: <code>POST /admin/api/dashboard/placeholder-ok</code> (CSRF, bis 1000 Zeichen, Einstellung <code>sys.placeholders_ok</code>).</li>
  </ul>
  <h3 id="werkzeugleiste">Werkzeugleiste (<code>Core\Toolbar</code>)</h3>
  <p>Eine Leiste für alle Kits und Modi: <code>app/Toolbar.php</code> sammelt Rechte, Adressen und Zustand (<code>Toolbar::context()</code>), <code>app/Views/toolbar.php</code> rendert sie, <code>resources/js/_bar.js</code> (Teil von <code>admin.js</code>) steuert Menüs, Status und Modus, das Aussehen liegt in <code>editor.shadow.css</code>. Kits rufen im Partial <code>templates/partials/toolbar.php</code> nur <code>&lt;?= cms_toolbar(get_defined_vars()) ?&gt;</code> auf; fehlt das Partial, rendert <code>Core\Theme::partial()</code> die Leiste trotzdem. Die frühere Eintragsleiste (<code>app/Views/entry-toolbar.php</code>) gibt es nicht mehr; <code>entry_toolbar()</code> bleibt nur für ältere Partials und liefert dieselbe Leiste.</p>
  <ul>
    <li><b>Aufbau:</b> links Marke (→ Verwaltung), Symbol, Art („Seite“, Tabellenname, „Gilt für alle Einträge“), Titel und <b>ein</b> Status-Chip (Veröffentlicht · Entwurf · Geändert – nicht veröffentlicht · Ungespeichert · Live-Fassung; Klick/Enter zeigt die Erklärung). Mitte: Modus-Umschalter. Rechts: Aktionen des Modus, Suche (<kbd>⌘</kbd>/<kbd>Strg</kbd>+<kbd>K</kbd>) und das Menü <b>⋯</b> (Vorschau, Kompakt, Live-Fassung, Entwurf verwerfen, Als Entwurf, Alle Felder bearbeiten, In der Verwaltung öffnen, Seiteneinstellungen, zentrale Angaben, KI, Hilfe).</li>
    <li><b>Arten und Modi:</b> <code>page</code> – Ansehen · Bearbeiten (<code>?edit=1</code>, Seiten-Editor); <code>entry</code> (Detailseite eines Eintrags) – Ansehen · Bearbeiten (Felder direkt im Text, <b>ohne</b> Neuladen) · Vorlage; <code>template</code> (<code>?edit=1</code> auf einer Detailseite) – Vorlagen-Editor mit Auswahl <b>Vorschau mit</b> (anderer Eintrag). Der Umschalter erscheint nur, wenn es mehr als einen erlaubten Modus gibt (<code>pages.edit</code>, <code>data.edit</code>).</li>
    <li><b>Aktionen im Bearbeiten-Modus:</b> <b>Abbrechen</b> · <b>Speichern</b> · <b>Veröffentlichen</b> (Seiten mit veröffentlichter Fassung: geteilter Knopf mit „Entwurf verwerfen …“). Ohne <code>pages.publish</code> bzw. <code>data.publish</code> bleibt nur Speichern. „Speichern“ ist <code>aria-disabled</code>, solange nichts zu sichern ist, und zeigt danach „Gespeichert ✓“; eine Live-Region meldet den Stand.</li>
    <li><b>Abbrechen</b> (auch <kbd>Esc</kbd>, solange kein Dialog, Menü, keine Seitenleiste und kein Eingabefeld den Fokus hat, und der Wechsel zu „Ansehen“): ohne ungespeicherte Änderungen wird der Modus sofort verlassen. Sonst fragt ein Dialog <b>Weiter bearbeiten</b> (Fokus, <kbd>Esc</kbd>) · <b>Speichern &amp; beenden</b> · <b>Verwerfen</b>. Verwerfen betrifft nur ungespeicherte Änderungen im Browser – ein gespeicherter Entwurf bleibt, veröffentlicht wird nichts.</li>
    <li><b>Rückfragen:</b> Veröffentlichen, „Entwurf verwerfen“, „Als Entwurf“ und alle <code>data-confirm</code>-Formulare nutzen den gestalteten Dialog <code>CMSAdmin.bar.ask({ title, body, ok, cancel, danger })</code> (Promise&lt;bool&gt;) statt <code>window.confirm()</code> – auf der Website in der Ebene <code>#cms-layer-host</code>, in der Verwaltung als <code>&lt;dialog&gt;</code> im Dokument. Fokus auf <b>Abbrechen</b>, <kbd>Esc</kbd> = Abbrechen, danach Fokus zurück zum Auslöser. Bei <code>data-confirm</code> trägt der Bestätigen-Knopf die Beschriftung des auslösenden Knopfs (oder <code>data-confirm-ok</code>); ohne JavaScript sendet das Formular direkt.</li>
    <li><b>Wer bearbeitet, meldet sich an:</b> <code>CMSAdmin.bar.use({ dirty(), save(): Promise&lt;bool&gt;, discard(), exit(href), start?() })</code>; Zustand melden mit <code>CMSAdmin.bar.state('dirty' | 'saving' | 'saved' | 'published' | 'error' | 'clean')</code>.</li>
    <li><b>Responsiv:</b> Unter 1024 px wandert der Modus-Umschalter ins Menü <b>⋯</b> (Gruppe „Modus“) und der Status wird zum Punkt (Erklärung weiter per Klick). Unter 800 px scrollt die Leiste mit (nicht klebend). Unter 768 px bleiben oben Marke, Titel, Status, Hauptaktion und <b>⋯</b> (Suche steht dann im Menü); die Aktionen des Bearbeiten-Modus stehen als <b>Leiste unten</b> (Daumenbereich, <code>env(safe-area-inset-bottom)</code>), Menüs klappen dort nach oben auf, Meldungen rücken darüber.</li>
  </ul>
  <h4 id="theme-hook">Kit-Hook für eigene Leisten</h4>
  <p><b>Kopf des Kits:</b> Der Kern erkennt den Kopf selbst (<code>header</code> außerhalb von <code>main</code>/<code>article</code>/<code>section</code>, <code>.site-header</code>, <code>[role=banner]</code>, <code>data-cms-sticky</code>; eigener Kopf ohne diese Merkmale: <code>data-cms-header</code>) und markiert ihn mit <code>data-cms-header</code>. Solange er wirklich klebt oder fest steht (<code>position: sticky/fixed</code>), bekommt er zusätzlich <code>data-cms-pinned</code> und rückt unter die Leiste (<code>top: var(--cms-bar-offset)</code>) – ein Kopf, den das Kit im Bearbeiten nicht kleben lässt (z. B. <code>.is-editing .hdr{position:relative}</code>), bleibt an seinem Platz. Im Bearbeiten liegt der Kopf samt Menüs über den Block-Leisten, „+“ und den Knöpfen am Bild (Z-Skala in <code>resources/css/editor.css</code>); geöffnete Editor.js-Menüs liegen darüber, die Werkzeugleiste ganz oben. Eigene Regeln im Kit: <code>top: var(--cms-toolbar-h, 0)</code> (sichtbare Unterkante der Leiste; <code>--cms-bar-h</code> = ihre Höhe) – ohne Anmeldung gibt es die Variablen nicht, der Rückfallwert gilt. Für Leisten <b>unten</b> (Schnellkontakt, Cookie-Hinweis, „nach oben“) setzt <code>_bar.js</code> am <code>&lt;html&gt;</code>:</p>
  <table class="doc-table">
    <tr><th>Hook</th><th>Bedeutung</th></tr>
    <tr><td><code>html.cms-editing</code></td><td>Ein Bearbeiten-Modus ist aktiv (Seite, Eintrag, Vorlage) – jede Breite.</td></tr>
    <tr><td><code>html.cms-has-actionbar</code></td><td>Zusätzlich steht die Aktionsleiste des Editors unten (&lt; 768 px); <code>body</code> bekommt passenden Abstand unten.</td></tr>
    <tr><td><code>[data-cms-hide-editing]</code></td><td>Konvention: Elemente mit diesem Attribut blendet <code>editor.css</code> aus, solange die Aktionsleiste unten steht. Kostet das Kit kein CSS.</td></tr>
    <tr><td><code>--cms-bottom-bar-h</code></td><td>Höhe der Aktionsleiste unten (sonst <code>0px</code>) – für Kits, die ihre Leiste lieber verschieben: <code>bottom: calc(12px + var(--cms-bottom-bar-h, 0px))</code>.</td></tr>
  </table>
  <p>Beispiel (praxis, <code>templates/layout.php</code>): <code>&lt;div class="bottombar" … data-cms-hide-editing&gt;</code> – „Anrufen / Termin“ verschwindet auf Telefonen, solange bearbeitet wird. Seitenleiste „Block“ und Eintrags-Seitenleiste enden auf Telefonen über der Aktionsleiste (<code>bottom: var(--cms-bottom-bar-h)</code>).</p>
  <p><b>Wichtig für Kits:</b> Im Seiten-Editor (<code>?edit=1</code>) lädt das Layout das Kit-Skript nicht (<code>&lt;?php if (!$editor): ?&gt;</code>), <code>&lt;html&gt;</code> behält also <code>no-js</code> (zusätzlich <code>is-editing</code>). Die No-JS-Fassung der Navigation muss im Editor brauchbar bleiben – eine aufgeklappte Mobilnavigation in einem klebenden Kopf füllt sonst den ganzen Bildschirm. basis blendet sie deshalb unter 960 px mit <code>.is-editing .site-nav{display:none}</code> aus und macht den Kopf nicht klebend.</p>

  <h3 id="eintraege">Einträge auf der Website bearbeiten</h3>
  <p><code>Core\Data\EntryEdit</code> + <code>resources/js/_entry_edit.js</code> (Teil von <code>admin.js</code>). Einträge haben keinen Entwurfsstand neben der veröffentlichten Fassung: „Speichern“ ändert einen veröffentlichten Eintrag sofort, „Als Entwurf“ nimmt ihn offline.</p>
  <ul>
    <li><b>Werkzeugleiste:</b> Auf Detailseiten (außerhalb von <code>?edit=1</code>) ist es dieselbe Leiste (<a href="#werkzeugleiste"><code>Core\Toolbar</code></a>, Art <code>entry</code>): „Bearbeiten“ schaltet die Felder im Text ohne Neuladen frei (<code>html.cms-entry-editing</code>), „Abbrechen“ stellt den gespeicherten Stand wieder her, „Speichern“ sendet nur geänderte Felder (<code>partial: 1</code>). Im Menü <b>⋯</b>: „Alle Felder bearbeiten“ (Seitenleiste), „Als Entwurf speichern“, „Live-Ansicht“, „In der Verwaltung öffnen“. Konfiguration: <code>#cms-entry-config</code> (<code>EntryEdit::config()</code>).</li>
    <li><b>Felder im Text:</b> <code>entry_edit_attr($table, $entry, 'feld', ?$mode)</code> an das Element schreiben, das den Wert enthält – z. B. <code>&lt;h1&lt;?= entry_edit_attr($t, $e, '_title') ?&gt;&gt;</code>. Modi: <code>plain</code> (einzeilig), <code>lines</code> (mehrzeilig, <code>&lt;br&gt;</code>), <code>rich</code> (serverseitig per Whitelist bereinigt); Standard nach Feldtyp, andere Typen nur über die Seitenleiste. Liefert <code>''</code> für Besucher, ohne Recht <code>data.edit</code>, für fremde Einträge geteilter Tabellen und ohne <code>data.publish</code> für veröffentlichte Einträge. Blöcke mit Feldbindung (<code>$b-&gt;edit('feld')</code>) und <code>data_fields</code> markieren automatisch, sofern Quelle und Darstellung verlustfrei passen. Das Element darf keine weiteren Inhalte enthalten.</li>
    <li><b>Datenlisten:</b> <code>\Core\Data\EntryEdit::button($table, $entry)</code> (Stift, Link zur Verwaltung als Rückfall) und <code>::newButton($table)</code>; eigene Listen-Vorlagen können sie ebenso ausgeben. Jedes Element mit <code>data-entry-edit="&lt;Endpunkt&gt;"</code> öffnet die Seitenleiste.</li>
    <li><b>Endpunkte:</b> <code>GET /admin/api/entries/{tabelle}/{id|new}</code> (Formular, gleicher Renderer wie die Verwaltung) und <code>POST …</code> (Formulardaten oder JSON <code>{f: {…}, partial: 1, status}</code>, CSRF per <code>X-CSRF-Token</code>). Gleiche Regeln wie das Formular der Verwaltung; <code>Entries::save</code> leert den Seiten-Cache.</li>
  </ul>
  <h3 id="felder-bearbeiten">Formular-Blöcke: „Felder bearbeiten“</h3>
  <p>Blöcke mit einem Formular aus einer Datentabelle bekommen in der Block-Leiste den Knopf <code>.cms-block__fields</code> („Felder bearbeiten“, schmal nur „Felder“). Welches Blockfeld die Tabelle hält, steht in der Blockdefinition unter <code>'formfields' =&gt; 'feldname'</code>; ohne Angabe nimmt <code>Theme::editorConfig()</code> das erste Feld <code>'type' =&gt; 'datatable', 'inbox' =&gt; true</code> (Kern-Block <code>data_form</code>, <code>contact</code> der Kits, Newsletter-Formular in editorial). Sichtbar nur, wenn eine Tabelle gewählt ist und sie in <code>cfg.formFields</code> steht (<code>fragments/editor.php</code>: Recht <code>data.schema</code>, geteilte Tabellen nur mit <code>Shared::canSchema</code>).</p>
  <ul>
    <li><b>Seitenleiste:</b> <code>resources/js/_form_fields.js</code> (<code>CMSAdmin.formFields.open(endpoint, trigger, {onSaved})</code>), eigenes Shadow DOM <code>#cms-ffpanel-host</code> wie „Eintrag bearbeiten“ (<code>admin.shadow.css</code> + <code>entry-panel.css</code>, Klassen <code>.ff</code>/<code>.dt-field</code> des Tabellen-Designers). HTML vom Server: <code>app/Views/formfields-panel.php</code>. Tastatur: <kbd>Esc</kbd> schließt (mit Rückfrage bei Änderungen) bzw. bricht „Feld entfernen?“ ab, <kbd>Strg</kbd>/<kbd>⌘</kbd>+<kbd>S</kbd> speichert, ↑/↓ verschieben mit Ansage der neuen Position (Live-Region), Fokus kehrt zum Knopf zurück.</li>
    <li><b>Endpunkte:</b> <code>GET|POST /admin/api/formfields/{tabelle}</code> (<code>Admin\FormFieldsController</code>, Recht <code>data.schema</code>, CSRF per <code>X-CSRF-Token</code>; Fehler als JSON <code>{ok: false, error}</code> mit 403/404/419). Eingabe <code>fields[i][id|label|name|type|required|width|help|options|accept|max_mb]</code>, <code>form[enabled|fields|success|submit|uploads|upload_mb]</code>, <code>confirm_drop</code>.</li>
    <li><b>Speichern:</b> <code>Core\Data\SchemaPanel::input()</code> legt die Angaben über <code>Tables::toInput($t)</code> (gespeicherte Definition im Eingabeformat von <code>Tables::validate</code>) – Bedingungen, Übersetzungen, Unterfelder, Liste/Suche, Kalender, Zustellung und S/MIME bleiben unverändert. Geprüft und gespeichert wird über <code>DataController::saveSchema()</code>, denselben Weg wie der Tabellen-Designer (<code>Tables::validate</code>, Rückfrage „Felder wirklich löschen“ über <code>Tables::droppedFields</code>). Neue Felder kommen in eine bestehende Auswahl „Felder im Formular“, umbenannte bleiben ausgewählt. Typen der Leiste: <code>SchemaPanel::types()</code> (Formular-Typen; Eingang ohne Bild, Dateifelder nur bei Zustellung per E-Mail – <code>addTypes()</code>).</li>
    <li><b>Nach dem Speichern</b> ruft <code>onSaved</code> in <code>editor.js</code> <code>loadPreview()</code> für alle Blöcke mit dieser Tabelle – das Formular erscheint ohne Neuladen.</li>
    <li><b>Selbsttest:</b> <code>php bin/console data:selftest</code> – Rundlauf <code>validate(toInput($t), $t) = $t</code> für alle Tabellen, dazu vorübergehende Inhalts- und Eingangstabellen (Reihenfolge, Pflicht, Umbenennen, Dateitypen, Löschen mit Bestätigung, Grenzen des Eingangs). <code>--roundtrip</code> prüft nur den Rundlauf und ändert nichts (auch auf Live-Websites). Erlaubte Abweichungen sind nur die Bereinigungen, die auch der Tabellen-Designer beim Speichern vornimmt (fehlende Einstellungen älterer Tabellen, Übersetzungen in nicht mehr vorhandenen Sprachen).</li>
  </ul>

  <h3 id="notizen">Redaktionsnotizen <code>[# … #]</code> (<code>Core\EditorNotes</code>)</h3>
  <p>Versteckte Hinweise der Redaktion in beliebigen Texten: <code>[#</code> + Leerraum (auch <code>&amp;nbsp;</code>) … <code>#]</code>, mehrzeilig, nicht gierig, auch in Rich Text, verschachtelten Blockdaten und Einträgen. Ausnahmen: in <code>&lt;code&gt;</code>/<code>&lt;pre&gt;</code> und in <code>`Backticks`</code> bleibt die Schreibweise stehen. Kits und Erweiterungen müssen nichts tun – der Kern filtert auf der untersten gemeinsamen Ebene:</p>
  <table class="doc-table">
    <tr><th>Ausgabe</th><th>Wo entfernt</th></tr>
    <tr><td>Blöcke (alle Kits, Kern, Erweiterungen, eigene Blöcke)</td><td><code>Theme::makeBlock()</code> – <code>EditorNotes::stripData()</code> auf die Blockdaten (ohne <code>_fx</code>, <code>_fit</code>, <code>_bind</code>), bevor ein Renderer sie sieht (Kürzungen, Alt-Texte, <code>aria-label</code>, JSON-LD-Daten)</td></tr>
    <tr><td>Ganze Seite inkl. Einträge, Meta-/OG-Angaben, JSON-LD, Daten-Skripte</td><td><code>SiteController::render()</code> → <code>EditorNotes::publicHtml()</code> vor dem Seiten-Cache; <code>previewHtml()</code> (Freigabe, Design-Vorschau, SEO-Prüfung) immer ohne Notizen</td></tr>
    <tr><td>Suchindex (Loupe/Stichwort), Besucher-Chat, Auszüge</td><td><code>Search\Documents::doc()</code> (alle Felder), <code>Search\Text::plain()</code>; der Neuaufbau erzwingt die öffentliche Sicht</td></tr>
    <tr><td>KI-Kontexte</td><td>Assist (über <code>Text::plain</code>/<code>blocksText</code>), Assistent (Seitenkontext), Besucher-Chat (Suchindex)</td></tr>
    <tr><td>Kalender-Abos (.ics)</td><td><code>Data\ICal::text()</code></td></tr>
    <tr><td>API/MCP</td><td>nur öffentliche Lesezugriffe: <code>pageGet(…, published: true)</code>, <code>publicInfo</code>. Entwürfe, Verwaltung, Content-Sync und Sicherungen behalten die Notizen (sie sind Inhalt).</td></tr>
  </table>
  <p><b>Redaktionsansicht:</b> <code>EditorNotes::$show</code> (angemeldet mit <code>pages.edit</code>, nicht <code>?live=1</code>; Editor-Vorschau <code>/admin/api/preview</code>) – dann bleiben die Daten roh und <code>Theme::renderBlock()</code> bzw. die Entwurfsansicht zeigen <code>EditorNotes::decorate()</code>: <code>&lt;span class="cms-note" contenteditable="false" role="note" data-cms-note="…"&gt;</code> (nur im Text, nie in Attributen, Skripten, <code>&lt;title&gt;</code>; Stil in <code>editor.css</code>). <code>editor.js</code> (<code>fieldValue()</code>) und <code>_entry_edit.js</code> schreiben den Hinweis beim Auslesen wieder als <code>[# … #]</code>. Übersicht: <code>Dashboard\Metrics::placeholders()</code> liefert Fundstellen mit <code>kind</code> <code>placeholder</code> | <code>note</code> (Notizen aus dem Entwurf und aus Einträgen, <code>entry</code> = Tabelle); die Netzwerk-Übersicht zählt beide getrennt.</p>
  <p><b>Für Erweiterungen:</b> <code>EditorNotes::strip($textOderHtml)</code>, <code>::stripData($array)</code>, <code>::publicHtml($html)</code>, <code>::has($text)</code>, <code>::find($text)</code> (Liste der Notiztexte), <code>::decorate($html)</code>. Eigene öffentliche Ausgaben außerhalb von Seiten (E-Mails an Gäste, JSON-Endpunkte, Feeds) sollten Texte aus Einträgen mit <code>strip()</code> filtern. CLI: <code>notes:convert [--dry-run]</code> stellt alte Marker um (<code>[bitte ergänzen: …]</code>, <code>[bitte prüfen: …]</code>, <code>[bitte rechtlich prüfen: …]</code>, <code>[bitte ergänzen nach Prüfung: …]</code>, <code>[Platzhalter]</code>, „NEU (bitte prüfen)“; veröffentlichte Fassung und Entwurf an Ort und Stelle, Version „Notizen umgestellt“, kein Veröffentlichen), <code>notes:selftest</code>. Hinweis: Marker <code>[bitte ergänzen: …]</code> des KI-Seiten-Generators sperren weiterhin das Veröffentlichen (<code>Pages::openMarkers</code>); Notizen nicht.</p>
  <h3 id="shadow-dom">Isolation per Shadow DOM</h3>
  <p>Die CMS-Oberfläche auf der Website – Werkzeugleiste, Block-Leisten, Seitenleisten, Dialoge (Mediathek, Zuschnitt, Link, Suche), Formatierungsleiste, KI-Dialoge und Meldungen – lebt in Shadow-DOM-Wurzeln (<code>resources/js/_shadow.js</code>), damit Kit-CSS und Verwaltungs-CSS sich nicht gegenseitig beeinflussen:</p>
  <ul>
    <li>Die Werkzeugleiste rendert <code>Core\Theme::toolbarHost()</code> als Declarative Shadow DOM (<code>.cms-bar-host</code>; jedes Kit-Partial <code>toolbar</code> wird automatisch eingepackt). Dialoge und Menüs hängen in der gemeinsamen Ebene <code>#cms-layer-host</code>, die Eintrags-Seitenleiste in <code>#cms-epanel-host</code> (zusätzlich <code>entry-panel.css</code>).</li>
    <li>Stylesheets per <code>&lt;link&gt;</code>: <code>editor.shadow.css</code> und <code>admin.shadow.css</code> (beim Build aus <code>admin.css</code> abgeleitet: <code>:root</code> → <code>:host</code>, Hell/Dunkel über <code>:host(.adm-ui[data-theme])</code>). <code>admin.css</code> selbst wird nicht in Website-Seiten geladen; <code>editor.css</code> enthält nur, was in der Seite liegen muss (Rahmen, <code>[data-edit]</code>-Markierungen, Editor.js, Platz für Seitenleisten, Host der Werkzeugleiste mit <code>--cms-bar-h</code> für klebende Kit-Köpfe).</li>
    <li>Elemente, die im Kit-DOM bleiben müssen (Stift, „+ Neuer Eintrag“, Hinweiszeile), nutzen eigene Klassen mit <code>all: unset</code>. Eigene Kit-Variablen am besten mit Präfix (z. B. <code>--b-*</code> in basis).</li>
  </ul>
  <h3 id="rich-text">Rich-Text: Formatierungsleiste und Linkauswahl</h3>
  <ul>
    <li><b>Eine Logik für alle Leisten:</b> <code>resources/js/_rte.js</code> (<code>CMSAdmin.Rich</code>: <code>barHtml(mode)</code>, <code>mount(bar, getArea, after)</code>, <code>exec(area, cmd)</code>, <code>state(area, bar)</code>, <code>bindKeys(area, mode)</code>) – Formularfelder <code>.rte</code> (Verwaltung, Block- und Eintrags-Seitenleiste), schwebende Leiste im Seiten-Editor (<code>editor.js</code>) und beim direkten Bearbeiten von Einträgen (<code>_entry_edit.js</code>). Befehle: <code>style:p|t-lead|t-small|t-note|h2|h3|h4|blockquote</code>, <code>color:accent|muted|success|warning|danger|none</code>, <code>mark</code>, <code>superscript</code>, <code>subscript</code>, <code>link</code>, <code>unlink</code>, <code>paragraph</code> (Formatierung entfernen), Listen, <code>indent</code>/<code>outdent</code>, <code>ai</code>. Farben/Marker entstehen über <code>execCommand('foreColor')</code> mit Hilfsfarbe und werden sofort in Klassen umgesetzt – nie <code>style</code>.</li>
    <li><b>Menüs</b> (<code>role="menu"</code>, <code>menuitemradio</code> mit <code>aria-checked</code>): <kbd>↓</kbd>/<kbd>Enter</kbd> öffnet, Pfeile/Pos1/Ende, <kbd>Esc</kbd> zurück; Kürzel <kbd>⌘</kbd>/<kbd>Strg</kbd>+<kbd>B</kbd>/<kbd>I</kbd>/<kbd>K</kbd>, +<kbd>Umschalt</kbd>+<kbd>H</kbd> (Marker), <kbd>Alt</kbd>+<kbd>F10</kbd> (Leiste). Unter 560 px wandern die Listen ins Menü <b>⋯</b>; Menüs öffnen nach oben, wenn unten kein Platz ist.</li>
    <li><b>Kontrast:</b> Auf der Website liest die Leiste <code>--rt-*</code> am bearbeiteten Element (Auflösung über ein Hilfselement in der CMS-Ebene) und vergleicht mit dem Hintergrund (Bilder: keine Prüfung); in Formularen gilt die Palette aus <code>&lt;script type="application/json" id="cms-rich"&gt;</code> (<code>Core\RichText::clientScript()</code>, hell und – falls das Kit ein Dunkelschema hat – dunkel). Unter 4,5:1 zeigt das Farbmenü eine Warnung.</li>
    <li><b>Linkauswahl</b> <code>resources/js/_links.js</code> (<code>CMSAdmin.openLinkPicker({mode: 'rich'|'field', current, value, text})</code> → <code>{href, ref, value, label, kind, newTab, title}</code> | <code>{remove: true}</code> | <code>null</code>; <code>CMSAdmin.pickLink()</code> bleibt kompatibel). Quelle: <code>GET /admin/api/links?format=groups&amp;q=…&amp;page=ID&amp;mode=…</code> (<code>Core\Links::sources()</code>: Anker dieser Seite, Seiten mit Pfad und Sprache, Einträge aller Inhaltstabellen mit Detailseite, Dateien/PDF, Sonderziele des Kits nur für Felder), <code>?describe=Wert</code> (lesbare Anzeige); ohne Parameter wie bisher die flache Liste für <code>&lt;datalist id="cms-links"&gt;</code>. Zuletzt verwendete Ziele: localStorage <code>cms-links-recent</code>.</li>
    <li id="markdown"><b>Markdown</b> <code>resources/js/_markdown.js</code> (<code>CMSAdmin.Markdown</code>): kompakter Umsetzer ohne Fremdbibliothek – <code>toHtml(md, {mode: 'rich'|'inline', headings})</code> → <code>{html, title, images, tables}</code>, <code>sections(md, split)</code> → <code>{parts: [{heading, html}], …}</code>, <code>looksLike(text)</code>, <code>openImport(opts)</code> (Dialog), <code>pasteTip()</code>. Ausgabe nur mit Tags der Whitelist (<code>p</code>, <code>h2</code>–<code>h4</code>, <code>ul</code>/<code>ol</code>/<code>li</code>, <code>ul.check</code>, <code>blockquote</code>, <code>b</code>, <code>i</code>, <code>a</code>, <code>br</code>), aller übrige Text maskiert; gespeichert wird über den normalen Weg (<code>Fields::sanitize</code> → <code>Sanitizer::block/inline</code>). Überschriften relativ: oberste Ebene → <code>h2</code> (ein einzelnes <code>#</code> am Anfang gilt als Titel und wird ebenfalls <code>h2</code>), tiefere → <code>h3</code>/<code>h4</code>. Bilder → Redaktionsnotiz <code>[# Bild: alt – url #]</code> (keine fremden Bilder), Tabellen → Textzeilen + Notiz, <code>`Code`</code> → Text, YAML-Vorspann entfernt (<code>title</code> nur als Hinweis). <b>Einfügen:</b> <code>Rich.bindKeys()</code> wandelt reinen Text um, wenn <code>looksLike()</code> zutrifft (ein starkes Zeichen wie <code>#&nbsp;</code>, <code>[x](url)</code>, <code>**x**</code>, Code-Zaun, Tabelle, Bild – oder zwei schwache: Listenzeilen, <code>&gt;</code>, <code>*x*</code>, <code>`x`</code>) und die Zwischenablage kein formatiertes HTML hat (<code>htmlIsPlain()</code> – Code-Editoren liefern nur div/span/pre); eingefügt per <code>execCommand('insertHTML')</code>, damit <kbd>⌘</kbd>/<kbd>Strg</kbd>+<kbd>Z</kbd> wirkt. Menü „⋯ → Markdown einfügen …“ (<code>Rich.exec(area, 'markdown')</code>). <b>Seiten-Editor:</b> Werkzeugleiste „⋯ → Markdown importieren …“ (<code>[data-editor-md]</code>) fügt Blöcke per <code>editor.blocks.insert()</code> ein – Blocktyp <code>richtext</code>, sonst <code>text</code>, sonst ein einfügbarer Block mit Rich-Text-Feld ohne weitere Pflichtfelder (Feld <code>text</code> bevorzugt); ohne solchen Block ist der Import gesperrt. Ein leerer Startblock desselben Typs wird ersetzt.</li>
    <li><b>Feldtyp <code>link</code></b> (<code>Core\Fields::renderLink()</code>): Eingabe + „Auswählen …“ + Anzeige des Ziels (<code>Links::describe()</code>), auch in Repeatern (neue Einträge: <code>initLinkFields()</code>). Werte: https, mailto, tel, #anker, /pfad, Sonderziele, <code>page:ID[#anker]</code>, <code>entry:{tabelle}:{id}</code>, <code>media:{id}[:viewer]</code> – <code>link_href()</code> löst sie auf, alte Werte bleiben gültig.</li>
  </ul>
