<?php /** Entwicklerhandbuch · Bearbeiten auf der Website: Editor, Einträge, Shadow-DOM-Isolation */ ?>
  <p class="lead">Seiten und Einträge werden direkt auf der Website bearbeitet. Für Besucher entsteht dabei <b>kein</b> zusätzliches Markup, Skript oder Stylesheet – alles Folgende wird nur für Angemeldete ausgegeben, der Seiten-Cache bleibt unverändert.</p>
  <h3>Seiten-Editor (<code>?edit=1</code>)</h3>
  <ul>
    <li><b>Grundlage:</b> Editor.js (<code>public/assets/vendor/editorjs</code>) mit editorjs-drag-drop; eigene Oberfläche in <code>resources/js/editor.js</code>, Kit-Partial <code>templates/partials/editor.php</code>. Jeder Block ist ein Editor.js-Block <code>{id, type, data, tunes}</code>; die Vorschau rendert der Server mit dem echten Kit-Renderer.</li>
    <li><b>Endpunkte</b> (CSRF): <code>POST /admin/api/preview</code> (Block-HTML, optional mit Vorschau-Eintrag für Detailseiten), <code>POST /admin/api/block-form</code> (Feldformular aus dem Block-Schema), <code>GET /admin/api/links</code> (Linkauswahl), <code>POST /admin/api/pages/{id}/save</code> (Entwurf bzw. <code>publish</code>, Revision), <code>POST /admin/api/pages/{id}/discard</code>.</li>
    <li><b>Abschnitts-Optionen</b> (<code>Theme::TUNES</code>): background, anchor, visible, showInNav, navLabel, spaceTop, spaceBottom, divider (oben), height (<code>screen</code> = Vollbild), align, bgImage, overlay (dark/light) – Ausgabe über das Partial <code>section</code> bzw. <code>$b-&gt;tune()</code>; Vollbild/Hintergrundbild laden <code>css/sections.css</code>.</li>
    <li><b>Bedienung:</b> <kbd>⌘</kbd>/<kbd>Strg</kbd>+<kbd>S</kbd> speichert, <kbd>Alt</kbd>+<kbd>↑</kbd>/<kbd>↓</kbd> verschiebt den Block der offenen Seitenleiste, <kbd>Esc</kbd> schließt sie; Kompaktansicht und eingeklappte Blöcke merkt sich der Browser (localStorage). Inline-Felder (<code>$b-&gt;edit('pfad')</code>) nehmen eingefügten Text ohne Formatierung; Rich-Text-Felder bekommen die Formatierungsleiste (inkl. „✦ KI“, wenn freigeschaltet).</li>
    <li><b>Veröffentlichungssperre:</b> Enthalten Entwurf, Titel oder Beschreibung Platzhalter <code>[bitte ergänzen: …]</code>, wirft <code>Pages::publish()</code> eine Ausnahme (Editor, Seitenliste, REST und MCP melden 422).</li>
    <li id="sprung-zum-block"><b>Sprung zu einem Block:</b> <code>?edit=1#b-{blockId}</code> (oder <code>?edit=1&amp;block={blockId}</code>, auch die Sprungmarke <code>anchor</code> des Abschnitts) klappt den Block auf, scrollt ihn in die Mitte, hebt ihn kurz hervor (<code>.is-target</code>), markiert <code>[Platzhalter]</code> darin über die CSS Custom Highlight API (<code>::highlight(cms-placeholder)</code>, DOM bleibt unverändert) und öffnet ab 1101 px Breite die Felder in der Seitenleiste. Genutzt von der Platzhalter-Liste: <code>Core\Dashboard\Metrics::placeholders($db, $ok, $max, $page)</code> sucht je Block in allen Texten (verschachtelt, ohne HTML) der veröffentlichten Fassung nach <code>Metrics::PLACEHOLDER_RX</code> (Klammer mit Buchstabe am Anfang, auch klein, keine Markdown-Links <code>[Text](url)</code>) und liefert Seite, Block-ID, Blocktyp und Adresse; <code>Metrics::placeholderEditUrl($hit)</code> baut den Sprung. Ansicht <code>app/Admin/views/pages/_placeholders.php</code> in „Was ist zu tun?“ (Recht <code>pages.edit</code>, <code>settings.edit</code> oder Administration) und oben in den Seiteneinstellungen (<code>#platzhalter</code>). „Ist gewollt“: <code>POST /admin/api/dashboard/placeholder-ok</code> (CSRF, bis 1000 Zeichen, Einstellung <code>sys.placeholders_ok</code>).</li>
  </ul>
  <h3 id="werkzeugleiste">Werkzeugleiste (<code>Core\Toolbar</code>)</h3>
  <p>Eine Leiste für alle Kits und Modi: <code>app/Toolbar.php</code> sammelt Rechte, Adressen und Zustand (<code>Toolbar::context()</code>), <code>app/Views/toolbar.php</code> rendert sie, <code>resources/js/_bar.js</code> (Teil von <code>admin.js</code>) steuert Menüs, Status und Modus, das Aussehen liegt in <code>editor.shadow.css</code>. Kits rufen im Partial <code>templates/partials/toolbar.php</code> nur <code>&lt;?= cms_toolbar(get_defined_vars()) ?&gt;</code> auf; fehlt das Partial, rendert <code>Core\Theme::partial()</code> die Leiste trotzdem. Die frühere Eintragsleiste (<code>app/Views/entry-toolbar.php</code>) gibt es nicht mehr; <code>entry_toolbar()</code> bleibt nur für ältere Partials und liefert dieselbe Leiste.</p>
  <ul>
    <li><b>Aufbau:</b> links Marke (→ Verwaltung), Symbol, Art („Seite“, Tabellenname, „Gilt für alle Einträge“), Titel und <b>ein</b> Status-Chip (Veröffentlicht · Entwurf · Geändert – nicht veröffentlicht · Ungespeichert · Live-Fassung; Klick/Enter zeigt die Erklärung). Mitte: Modus-Umschalter. Rechts: Aktionen des Modus, Suche (<kbd>⌘</kbd>/<kbd>Strg</kbd>+<kbd>K</kbd>) und das Menü <b>⋯</b> (Vorschau, Kompakt, Live-Fassung, Entwurf verwerfen, Als Entwurf, Alle Felder bearbeiten, In der Verwaltung öffnen, Seiteneinstellungen, zentrale Angaben, KI, Hilfe).</li>
    <li><b>Arten und Modi:</b> <code>page</code> – Ansehen · Bearbeiten (<code>?edit=1</code>, Seiten-Editor); <code>entry</code> (Detailseite eines Eintrags) – Ansehen · Bearbeiten (Felder direkt im Text, <b>ohne</b> Neuladen) · Vorlage; <code>template</code> (<code>?edit=1</code> auf einer Detailseite) – Vorlagen-Editor mit Auswahl <b>Vorschau mit</b> (anderer Eintrag). Der Umschalter erscheint nur, wenn es mehr als einen erlaubten Modus gibt (<code>pages.edit</code>, <code>data.edit</code>).</li>
    <li><b>Aktionen im Bearbeiten-Modus:</b> <b>Abbrechen</b> · <b>Speichern</b> · <b>Veröffentlichen</b> (Seiten mit veröffentlichter Fassung: geteilter Knopf mit „Entwurf verwerfen …“). Ohne <code>pages.publish</code> bzw. <code>data.publish</code> bleibt nur Speichern. „Speichern“ ist <code>aria-disabled</code>, solange nichts zu sichern ist, und zeigt danach „Gespeichert ✓“; eine Live-Region meldet den Stand.</li>
    <li><b>Abbrechen</b> (auch <kbd>Esc</kbd>, solange kein Dialog, Menü, keine Seitenleiste und kein Eingabefeld den Fokus hat, und der Wechsel zu „Ansehen“): ohne ungespeicherte Änderungen wird der Modus sofort verlassen. Sonst fragt ein Dialog <b>Weiter bearbeiten</b> (Fokus, <kbd>Esc</kbd>) · <b>Speichern &amp; beenden</b> · <b>Verwerfen</b>. Verwerfen betrifft nur ungespeicherte Änderungen im Browser – ein gespeicherter Entwurf bleibt, veröffentlicht wird nichts.</li>
    <li><b>Rückfragen:</b> Veröffentlichen, „Entwurf verwerfen“, „Als Entwurf“ und alle <code>data-confirm</code>-Formulare nutzen den gestalteten Dialog <code>CMSAdmin.bar.ask({ title, body, ok, cancel, danger })</code> (Promise&lt;bool&gt;) statt <code>window.confirm()</code> – auf der Website in der Ebene <code>#cms-layer-host</code>, in der Verwaltung als <code>&lt;dialog&gt;</code> im Dokument. Fokus auf <b>Abbrechen</b>, <kbd>Esc</kbd> = Abbrechen, danach Fokus zurück zum Auslöser. Bei <code>data-confirm</code> trägt der Bestätigen-Knopf die Beschriftung des auslösenden Knopfs (oder <code>data-confirm-ok</code>); ohne JavaScript sendet das Formular direkt.</li>
    <li><b>Wer bearbeitet, meldet sich an:</b> <code>CMSAdmin.bar.use({ dirty(), save(): Promise&lt;bool&gt;, discard(), exit(href), start?() })</code>; Zustand melden mit <code>CMSAdmin.bar.state('dirty' | 'saving' | 'saved' | 'published' | 'error' | 'clean')</code>.</li>
    <li><b>Responsiv:</b> Unter 1024 px wandert der Modus-Umschalter ins Menü <b>⋯</b> (Gruppe „Modus“) und der Status wird zum Punkt (Erklärung weiter per Klick). Unter 800 px scrollt die Leiste mit (nicht klebend). Unter 768 px bleiben oben Marke, Titel, Status, Hauptaktion und <b>⋯</b> (Suche steht dann im Menü); die Aktionen des Bearbeiten-Modus stehen als <b>Leiste unten</b> (Daumenbereich, <code>env(safe-area-inset-bottom)</code>), Menüs klappen dort nach oben auf, Meldungen rücken darüber.</li>
  </ul>
  <h4 id="theme-hook">Kit-Hook für eigene Leisten</h4>
  <p>Klebende Kit-Köpfe nutzen <code>top: var(--cms-bar-h)</code> (Höhe der Werkzeugleiste, von <code>_shadow.js</code> gesetzt). Für Leisten <b>unten</b> (Schnellkontakt, Cookie-Hinweis, „nach oben“) setzt <code>_bar.js</code> am <code>&lt;html&gt;</code>:</p>
  <table class="doc-table">
    <tr><th>Hook</th><th>Bedeutung</th></tr>
    <tr><td><code>html.cms-editing</code></td><td>Ein Bearbeiten-Modus ist aktiv (Seite, Eintrag, Vorlage) – jede Breite.</td></tr>
    <tr><td><code>html.cms-has-actionbar</code></td><td>Zusätzlich steht die Aktionsleiste des Editors unten (&lt; 768 px); <code>body</code> bekommt passenden Abstand unten.</td></tr>
    <tr><td><code>[data-cms-hide-editing]</code></td><td>Konvention: Elemente mit diesem Attribut blendet <code>editor.css</code> aus, solange die Aktionsleiste unten steht. Kostet das Kit kein CSS.</td></tr>
    <tr><td><code>--cms-bottom-bar-h</code></td><td>Höhe der Aktionsleiste unten (sonst <code>0px</code>) – für Kits, die ihre Leiste lieber verschieben: <code>bottom: calc(12px + var(--cms-bottom-bar-h, 0px))</code>.</td></tr>
  </table>
  <p>Beispiel (praxis, <code>templates/layout.php</code>): <code>&lt;div class="bottombar" … data-cms-hide-editing&gt;</code> – „Anrufen / Termin“ verschwindet auf Telefonen, solange bearbeitet wird. Seitenleiste „Block“ und Eintrags-Seitenleiste enden auf Telefonen über der Aktionsleiste (<code>bottom: var(--cms-bottom-bar-h)</code>).</p>
  <p><b>Wichtig für Kits:</b> Im Seiten-Editor (<code>?edit=1</code>) lädt das Layout das Kit-Skript nicht (<code>&lt;?php if (!$editor): ?&gt;</code>), <code>&lt;html&gt;</code> behält also <code>no-js</code> (zusätzlich <code>is-editing</code>). Die No-JS-Fassung der Navigation muss im Editor brauchbar bleiben – eine aufgeklappte Mobilnavigation in einem klebenden Kopf füllt sonst den ganzen Bildschirm. basis blendet sie deshalb unter 960 px mit <code>.is-editing .site-nav{display:none}</code> aus und macht den Kopf nicht klebend.</p>

  <h3 id="eintraege">Einträge auf der Website bearbeiten</h3>
  <p><code>Core\Data\EntryEdit</code> + <code>resources/js/_entry_edit.js</code> (Teil von <code>admin.js</code>). Einträge haben keinen Entwurfsstand neben der veröffentlichten Fassung: „Speichern“ ändert einen veröffentlichten Eintrag sofort, „Als Entwurf“ nimmt ihn offline.</p>
  <ul>
    <li><b>Werkzeugleiste:</b> Auf Detailseiten (außerhalb von <code>?edit=1</code>) ist es dieselbe Leiste (<a href="#werkzeugleiste"><code>Core\Toolbar</code></a>, Art <code>entry</code>): „Bearbeiten“ schaltet die Felder im Text ohne Neuladen frei (<code>html.cms-entry-editing</code>), „Abbrechen“ stellt den gespeicherten Stand wieder her, „Speichern“ sendet nur geänderte Felder (<code>partial: 1</code>). Im Menü <b>⋯</b>: „Alle Felder bearbeiten“ (Seitenleiste), „Als Entwurf speichern“, „Live-Ansicht“, „In der Verwaltung öffnen“. Konfiguration: <code>#cms-entry-config</code> (<code>EntryEdit::config()</code>).</li>
    <li><b>Felder im Text:</b> <code>entry_edit_attr($table, $entry, 'feld', ?$mode)</code> an das Element schreiben, das den Wert enthält – z. B. <code>&lt;h1&lt;?= entry_edit_attr($t, $e, '_title') ?&gt;&gt;</code>. Modi: <code>plain</code> (einzeilig), <code>lines</code> (mehrzeilig, <code>&lt;br&gt;</code>), <code>rich</code> (serverseitig per Whitelist bereinigt); Standard nach Feldtyp, andere Typen nur über die Seitenleiste. Liefert <code>''</code> für Besucher, ohne Recht <code>data.edit</code>, für fremde Einträge geteilter Tabellen und ohne <code>data.publish</code> für veröffentlichte Einträge. Blöcke mit Feldbindung (<code>$b-&gt;edit('feld')</code>) und <code>data_fields</code> markieren automatisch, sofern Quelle und Darstellung verlustfrei passen. Das Element darf keine weiteren Inhalte enthalten.</li>
    <li><b>Datenlisten:</b> <code>\Core\Data\EntryEdit::button($table, $entry)</code> (Stift, Link zur Verwaltung als Rückfall) und <code>::newButton($table)</code>; eigene Listen-Vorlagen können sie ebenso ausgeben. Jedes Element mit <code>data-entry-edit="&lt;Endpunkt&gt;"</code> öffnet die Seitenleiste.</li>
    <li><b>Endpunkte:</b> <code>GET /admin/api/entries/{tabelle}/{id|new}</code> (Formular, gleicher Renderer wie die Verwaltung) und <code>POST …</code> (Formulardaten oder JSON <code>{f: {…}, partial: 1, status}</code>, CSRF per <code>X-CSRF-Token</code>). Gleiche Regeln wie das Formular der Verwaltung; <code>Entries::save</code> leert den Seiten-Cache.</li>
  </ul>
  <h3 id="shadow-dom">Isolation per Shadow DOM</h3>
  <p>Die CMS-Oberfläche auf der Website – Werkzeugleiste, Block-Leisten, Seitenleisten, Dialoge (Mediathek, Zuschnitt, Link, Suche), Formatierungsleiste, KI-Dialoge und Meldungen – lebt in Shadow-DOM-Wurzeln (<code>resources/js/_shadow.js</code>), damit Kit-CSS und Verwaltungs-CSS sich nicht gegenseitig beeinflussen:</p>
  <ul>
    <li>Die Werkzeugleiste rendert <code>Core\Theme::toolbarHost()</code> als Declarative Shadow DOM (<code>.cms-bar-host</code>; jedes Kit-Partial <code>toolbar</code> wird automatisch eingepackt). Dialoge und Menüs hängen in der gemeinsamen Ebene <code>#cms-layer-host</code>, die Eintrags-Seitenleiste in <code>#cms-epanel-host</code> (zusätzlich <code>entry-panel.css</code>).</li>
    <li>Stylesheets per <code>&lt;link&gt;</code>: <code>editor.shadow.css</code> und <code>admin.shadow.css</code> (beim Build aus <code>admin.css</code> abgeleitet: <code>:root</code> → <code>:host</code>, Hell/Dunkel über <code>:host(.adm-ui[data-theme])</code>). <code>admin.css</code> selbst wird nicht in Website-Seiten geladen; <code>editor.css</code> enthält nur, was in der Seite liegen muss (Rahmen, <code>[data-edit]</code>-Markierungen, Editor.js, Platz für Seitenleisten, Host der Werkzeugleiste mit <code>--cms-bar-h</code> für klebende Kit-Köpfe).</li>
    <li>Elemente, die im Kit-DOM bleiben müssen (Stift, „+ Neuer Eintrag“, Hinweiszeile), nutzen eigene Klassen mit <code>all: unset</code>. Eigene Kit-Variablen am besten mit Präfix (z. B. <code>--b-*</code> in basis).</li>
  </ul>
  <h3 id="rich-text">Rich-Text: Formatierungsleiste und Linkauswahl</h3>
  <ul>
    <li><b>Eine Logik für alle Leisten:</b> <code>resources/js/_rte.js</code> (<code>CMSAdmin.Rich</code>: <code>barHtml(mode)</code>, <code>mount(bar, getArea, after)</code>, <code>exec(area, cmd)</code>, <code>state(area, bar)</code>, <code>bindKeys(area, mode)</code>) – Formularfelder <code>.rte</code> (Verwaltung, Block- und Eintrags-Seitenleiste), schwebende Leiste im Seiten-Editor (<code>editor.js</code>) und beim direkten Bearbeiten von Einträgen (<code>_entry_edit.js</code>). Befehle: <code>style:p|t-lead|t-small|t-note|h2|h3|h4|blockquote</code>, <code>color:accent|muted|success|warning|danger|none</code>, <code>mark</code>, <code>superscript</code>, <code>subscript</code>, <code>link</code>, <code>unlink</code>, <code>paragraph</code> (Formatierung entfernen), Listen, <code>indent</code>/<code>outdent</code>, <code>ai</code>. Farben/Marker entstehen über <code>execCommand('foreColor')</code> mit Hilfsfarbe und werden sofort in Klassen umgesetzt – nie <code>style</code>.</li>
    <li><b>Menüs</b> (<code>role="menu"</code>, <code>menuitemradio</code> mit <code>aria-checked</code>): <kbd>↓</kbd>/<kbd>Enter</kbd> öffnet, Pfeile/Pos1/Ende, <kbd>Esc</kbd> zurück; Kürzel <kbd>⌘</kbd>/<kbd>Strg</kbd>+<kbd>B</kbd>/<kbd>I</kbd>/<kbd>K</kbd>, +<kbd>Umschalt</kbd>+<kbd>H</kbd> (Marker), <kbd>Alt</kbd>+<kbd>F10</kbd> (Leiste). Unter 560 px wandern die Listen ins Menü <b>⋯</b>; Menüs öffnen nach oben, wenn unten kein Platz ist.</li>
    <li><b>Kontrast:</b> Auf der Website liest die Leiste <code>--rt-*</code> am bearbeiteten Element (Auflösung über ein Hilfselement in der CMS-Ebene) und vergleicht mit dem Hintergrund (Bilder: keine Prüfung); in Formularen gilt die Palette aus <code>&lt;script type="application/json" id="cms-rich"&gt;</code> (<code>Core\RichText::clientScript()</code>, hell und – falls das Kit ein Dunkelschema hat – dunkel). Unter 4,5:1 zeigt das Farbmenü eine Warnung.</li>
    <li><b>Linkauswahl</b> <code>resources/js/_links.js</code> (<code>CMSAdmin.openLinkPicker({mode: 'rich'|'field', current, value, text})</code> → <code>{href, ref, value, label, kind, newTab, title}</code> | <code>{remove: true}</code> | <code>null</code>; <code>CMSAdmin.pickLink()</code> bleibt kompatibel). Quelle: <code>GET /admin/api/links?format=groups&amp;q=…&amp;page=ID&amp;mode=…</code> (<code>Core\Links::sources()</code>: Anker dieser Seite, Seiten mit Pfad und Sprache, Einträge aller Inhaltstabellen mit Detailseite, Dateien/PDF, Sonderziele des Kits nur für Felder), <code>?describe=Wert</code> (lesbare Anzeige); ohne Parameter wie bisher die flache Liste für <code>&lt;datalist id="cms-links"&gt;</code>. Zuletzt verwendete Ziele: localStorage <code>cms-links-recent</code>.</li>
    <li><b>Feldtyp <code>link</code></b> (<code>Core\Fields::renderLink()</code>): Eingabe + „Auswählen …“ + Anzeige des Ziels (<code>Links::describe()</code>), auch in Repeatern (neue Einträge: <code>initLinkFields()</code>). Werte: https, mailto, tel, #anker, /pfad, Sonderziele, <code>page:ID[#anker]</code>, <code>entry:{tabelle}:{id}</code>, <code>media:{id}[:viewer]</code> – <code>link_href()</code> löst sie auf, alte Werte bleiben gültig.</li>
  </ul>
