<?php /** Entwicklerhandbuch · Feldtypen (Core\Fields::TYPES) · @var array $fieldTypes  @var array $fieldInfo */ ?>
  <p>Ein Schema für alles: Blöcke, zentrale Kit-Einstellungen, Grundeinstellungen und öffentliche Formulare. Validierung serverseitig in <code>Core\Fields</code>.</p>
  <table class="doc-table">
    <tr><th>Typ</th><th>Verhalten</th></tr>
    <?php foreach ($fieldTypes as $t): ?><tr><td><code><?= e($t) ?></code></td><td><?= e($fieldInfo[$t] ?? '') ?></td></tr><?php endforeach; ?>
  </table>
  <p><b>Aufklappbare Abschnitte:</b> Eine Überschrift (<code>heading</code>) mit <code>'collapse' =&gt; true</code> (zu) bzw. <code>'open'</code> (offen) fasst alle folgenden Felder bis zur nächsten Überschrift in einem aufklappbaren Abschnitt zusammen (<code>&lt;details class="f-sec"&gt;</code>); <code>'summary'</code> zeigt einen Kurzstand im Kopf. Abschnitte mit Fehlern öffnen sich von selbst. Beispiel: Grundeinstellungen → KI.</p>
  <p><b>Seitenauswahl <code>pages</code>:</b> ersetzt Kästchen-Listen mit Seiten. <code>['name' =&gt; 'sys.chat_exclude', 'type' =&gt; 'pages', 'store' =&gt; 'ids']</code> speichert <code>['12', '40*']</code> – gleiches Format wie die frühere Mehrfachauswahl mit Seiten-IDs, ältere Werte bleiben gültig; <code>\Core\PagePicker::matches($wert, $seite)</code> prüft Seite und Unterseiten. <code>'store' =&gt; 'paths'</code> speichert Pfade je Zeile wie die Glossar-Ausnahmen (<code>/impressum</code>, <code>/leistungen/*</code>, eigene Pfade wie <code>/blog/*</code>). Der Dialog (<code>resources/js/_pages.js</code>, <code>CMSAdmin.openPagesPicker()</code>) lädt den Seitenbaum der Linkauswahl (<code>GET /admin/api/links?format=tree</code>, je Knoten <code>path</code>), filtert ihn per Suche, zeigt „inbegriffen“ unter Seiten mit Unterseiten und läuft auf der Website in der Shadow-DOM-Ebene. Verwendet in: Besucher-Chat („keinen Chat zeigen“), Glossar („Seiten ausnehmen“). Selbsttest: <code>ai:selftest</code>.</p>
  <p>Allgemeine Attribute: <code>name</code>, <code>label</code>, <code>type</code>, <code>required</code>, <code>default</code>, <code>help</code>, <code>placeholder</code>, <code>width</code> (half|full), <code>max</code> (Zeichen), <code>rows</code>, <code>options</code> (+ <code>options_i18n</code>), <code>labels</code> (Beschriftung je Sprache), <code>translate</code> (Einstellungen: übersetzbar ja/nein). In Blockdefinitionen außerdem <code>variants</code> (Liste von Varianten-Schlüsseln): das Feld erscheint in der Seitenleiste nur bei diesen Varianten des Blocks, sein Wert bleibt beim Umschalten erhalten (<code>Core\Fields</code> → <code>.f-vis[data-variants]</code>, <code>resources/js/editor.js</code>). Typspezifisch: <code>fields</code>, <code>item_label</code>, <code>title_field</code>, <code>max_items</code>, <code>preview</code> (repeater); <code>fields</code>, <code>min</code>, <code>max</code>, <code>item_label</code>, <code>add_label</code> (group); <code>mask</code> (iban); <code>transparent</code> (color: <code>true</code> zeigt neben dem Farbwähler „Transparent“ und speichert dann den Wert <code>'transparent'</code> statt <code>#RRGGBB</code> – Ausgabe muss ihn behandeln; genutzt für <code>sys.icon_bg</code>: Browser-Tab/Android-Icons durchsichtig, iPhone- und maskable-Icon weiß hinterlegt); <code>address_fields</code> (geo); <code>inbox</code> (datatable: Eingänge zulassen); <code>system</code>, <code>empty_label</code> (datafield); <code>links</code> (heading).</p>
  <p>Datentabellen verwenden eine Auswahl davon plus Verknüpfungen (<code>relation</code>, <code>relations</code>) – siehe <a href="#daten">Seitenbaum &amp; Datentabellen</a>. Nicht in Datentabellen: inline, page, collection, repeater, secret, heading, icon, datatable/datafield(s).</p>
