<?php /** Entwicklerhandbuch · Formulare & Eingänge */ ?>
  <h3 id="datenformulare">Formulare für Datentabellen</h3>
  <p>Funktion <code>forms.data</code> („Formulare für Datentabellen“, aus bei abgeschalteten Datentabellen). Einstellung je Tabelle (<code>settings.form</code>, Standard aus): Felder (Standard: alle geeigneten; Pflichtfelder immer), Status neuer Einträge (Entwurf = Moderation, oder veröffentlicht), Empfänger der Benachrichtigung (bis zu 5 Adressen), Text nach dem Absenden, Button-Beschriftung, Datei-Uploads (Standard aus, Größe <code>upload_mb</code> 1–10 MB, Standard 5). Eine Datenschutz-Bestätigung (<code>_privacy</code>) gehört zu jedem Datenformular. Geeignet: text, textarea, number, bool, date, datetime, time, select, multiselect, email, tel, color, iban, group (wiederholbare Gruppe) – media/file nur mit Uploads; Verknüpfungen, Rich-Text, Karte, Link/URL und Wiederholung nie. Ein Pflichtfeld eines ungeeigneten Typs verhindert das Einschalten.</p>
  <table class="doc-table">
    <tr><th>Route</th><th>Zweck</th></tr>
    <tr><td><code>GET /formular/{tabelle}/challenge</code></td><td>Token + Proof-of-Work-Aufgabe (JSON, beim ersten Fokus geholt – die Seite selbst bleibt zwischenspeicherbar)</td></tr>
    <tr><td><code>POST /formular/{tabelle}</code></td><td>Einsendung; JSON bei <code>Accept: application/json</code> (200 / 422 mit <code>errors</code>), sonst eigenständige Seite mit Fehlerübersicht (<code>no-store</code>)</td></tr>
    <tr><td><code>GET /formular/{tabelle}</code></td><td>Formularseite mit eingebettetem Token (Rückfall ohne JavaScript)</td></tr>
  </table>
  <p>Ablauf (<code>Core\Data\DataForms::submit</code>): nur Felder des Formulars werden angenommen (status, slug, lang und Medien-IDs nie aus dem Request), Prüfung mit <code>Fields::sanitize</code> in der Sprache der Seite (<code>Fields::$site = true</code>) + <code>Rules::apply</code>, danach <code>SpamGuard::check('data-{tabelle}')</code> (Honeypot, signiertes Zeit-Token mit Mindestzeit/Einmalverwendung, Proof-of-Work, Rate-Limit je IP-Hash und global, Link-/Sperrwortfilter; Bots erhalten eine vorgetäuschte Erfolgsmeldung). Uploads: nur JPG/PNG/WebP (Bildfeld) bzw. zusätzlich PDF (Dateifeld), Größe 1–10 MB (Einstellung), MIME per finfo, Import über <code>Media::import</code> mit Tag <code>formular</code> – <b>Mediendateien sind über ihre Adresse öffentlich</b>. Speichern über <code>Entries::save</code>, Benachrichtigung per <code>Mailer</code> ohne Inhalte (nur „Neuer Eintrag in {Tabelle}“ + Link). Keine Cookies, keine Session. Einträge von Inhaltstabellen werden <b>nicht verschlüsselt</b> gespeichert – für besondere Kategorien personenbezogener Daten eine Eingangs-Tabelle verwenden (siehe nächster Abschnitt). Ausgabe theme-neutral (<code>dff-*</code>, <code>resources/css/dataform.css</code>, Kits: <code>assets/css/dataform.css</code>), Skript <code>resources/js/dataform.js</code> (Bedingungen, Proof-of-Work, Absenden ohne Neuladen, Fehlerübersicht mit Links + Fehler am Feld). Ohne JavaScript sendet das Formular klassisch; ist Proof-of-Work aktiv, weist ein Hinweis auf JavaScript hin.</p>

  <p><b>Eigene Formulare von Erweiterungen</b> auf Basis einer Tabelle (z. B. Buchungskalender): <code>DataForms::render($t, $o)</code> nimmt zusätzlich <code>action</code> (eigene Adresse; das Skript holt das Token unter <code>{action}/challenge</code> – die Erweiterung liefert dort <code>SpamGuard::challenge(DataForms::key($t))</code>), <code>prepend</code> (fertiges HTML vor den Feldern, z. B. eine Terminauswahl; Fehler zeigt das Skript am Element mit <code>data-cf="{name}"</code> und dessen <code>.dff-err</code>), <code>hidden</code> (<code>[name =&gt; wert]</code>), <code>fields_legend</code> (Felder als <code>&lt;fieldset class="dff-set"&gt;</code> mit Überschrift, z. B. „Ihre Angaben“ unter einer eigenen Auswahl; der Hinweis „Felder mit * …“ steht immer oben) und <code>server_message</code> (nach dem Absenden die Meldung des Servers statt des festen Textes). <code>DataForms::submit($t, $post, $files, $ip, $o)</code> nimmt <code>check</code> (<code>fn(array $values): array</code> weitere Fehler nach der Feldprüfung, vor dem Spamschutz), <code>store</code> (<code>fn(array $values): array</code> statt <code>Inbox::store</code> – selbst versiegeln, Rückgabe <code>['id', 'message']</code> oder <code>['error' =&gt; Text]</code>; ohne Feldfehler, damit das Skript ein neues Token holt) und <code>notify =&gt; false</code> (eigene E-Mails statt der Benachrichtigung des Cores). Mit <code>store</code> gilt <code>DataForms::enabled($t, false)</code> – so bleiben Eingänge mit <code>'direct_form' =&gt; false</code> (<a href="#inbox-hooks">Extension::inbox</a>) für <code>/formular/{handle}</code> gesperrt. Nach erfolgreichem Absenden löst <code>dataform.js</code> das Ereignis <code>dff:sent</code> (<code>detail</code> = Antwort) am Formular aus. <code>Core\Mailer::send(…, ['attach' =&gt; [['name' =&gt; 'termin.ics', 'data' =&gt; …, 'type' =&gt; 'text/calendar']]])</code> hängt kleine Dateien an.</p>

  <h3 id="eingang">Eingangs-Tabellen (Anfragen, verschlüsselt)</h3>
  <p><b>Eingangs-Tabellen</b> ersetzen die frühere, getrennte Anfragen-Logik (<code>Core\Forms</code> + Tabelle <code>requests</code>). Eine Eingangs-Tabelle ist eine Datentabelle mit <code>settings.kind = inbox</code> (Vorlage „Anfragen“ beim Anlegen; die Art lässt sich nur ändern, solange die Tabelle leer ist). Code: <code>Core\Data\Inbox</code>, zentrale Prüfung <code>Tables::isInbox()</code>. Funktion <code>requests</code> schaltet Eingänge (Menü, Formulare) ein/aus; <code>forms.data</code> gilt weiter nur für Inhaltstabellen.</p>
  <table class="doc-table">
    <tr><th>Thema</th><th>Umsetzung</th></tr>
    <tr><td>Speicherung</td><td><code>data_{handle}</code> <b>ohne Feldspalten</b> (Doctrine DBAL, <code>Inbox::sync</code>): <code>id, status (neu|in_bearbeitung|erledigt), ref (Vorgangsnummer, zufällig), lang, assignee, legacy, payload, created_at, updated_at</code>. Alle Feldwerte stecken als ein JSON in <code>payload</code>, versiegelt mit <code>FormCrypto::seal</code> (libsodium sealed box) – Klartext erreicht die Datenbank nie; ohne öffentlichen Schlüssel nimmt das Formular nichts an („noch nicht eingerichtet“). Payload v2: <code>{"v":2,"table","submitted_at","lang","values":{feld: wert},"labels":{feld: beschriftung}}</code>. Weil es keine Spalten je Feld gibt, lassen sich Felder jederzeit ändern; entfernte Felder erscheinen beim Lesen mit ihrer gespeicherten Beschriftung.</td></tr>
    <tr><td>Formular</td><td>Block <code>data_form</code> bzw. <code>/formular/{handle}</code> und – für Kit-Formulare – weiterhin <code>/anfrage/{form}</code> + <code>/api/form/{form}</code> (<code>FormController</code>, Kit-Vorlage <code>form-page</code>). Prüfung wie bei allen Datenformularen (<code>Fields::sanitize</code>, <code>Rules::apply</code>, IBAN usw.) <b>vor</b> dem Verschlüsseln, SpamGuard mit Schlüssel <code>data-{handle}</code>, Datenschutz-Checkbox, keine Cookies. Nur die Typen aus <code>DataForms::TYPES</code>; <b>keine Uploads</b> (Gesundheitsdaten dürfen nicht als öffentliche Mediendatei landen). Benachrichtigung ohne Inhalte mit Link <code>/admin/requests?table=…</code>.</td></tr>
    <tr><td>Gesperrt</td><td>Detailseiten/Adresse, <code>data_list</code>, <code>data_fields</code>, <code>calendar</code>, <code>upcoming</code> (nicht wählbar; <code>Tables::findContent</code>), Feldbindung, Verknüpfungen auf Eingänge, Sitemap, Spotlight (nur der Tabellenname als Aktion), strukturierte Daten, CalDAV/CardDAV, Kalender-Einstellung, schema.org-Typ, Status „veröffentlicht“. <code>Entries::*</code> wirft bei Eingangs-Tabellen eine Ausnahme – Zugriff nur über <code>Inbox</code>.</td></tr>
    <tr><td>Lesen</td><td>Verwaltung → <b>Anfragen</b> (<code>InboxController</code>): Reiter je Eingang mit Anzahl „neu“, Statusfilter, Liste nur mit Metadaten. „Entschlüsseln“ schickt den geheimen Schlüssel per POST; er wird nicht gespeichert und entschlüsselt nur die Einträge der aktuellen Seite für diese Antwort. Aktionen: Status, Zuweisen, Löschen, Drucken/Kopieren (nur im Browser). Rechte <code>requests.read</code> / <code>requests.manage</code>, je Rolle auf Tabellen beschränkbar (<code>tables_json</code>).</td></tr>
    <tr><td>Protokoll</td><td>Tabelle <code>inbox_log</code> (table_handle, entry_ids JSON, user_id, action <code>decrypt|status|assign|delete|purge</code>, detail, ip_hash = HMAC, created_at) – nie Inhalte. Anzeige „Anfragen → Protokoll“ (Recht <code>users.manage</code>, letzte 200, Filter Tabelle/Benutzer). Aufbewahrung <code>sys.inbox_log_months</code> (Standard 12, Grundeinstellungen → Spamschutz).</td></tr>
    <tr><td>Aufbewahrung</td><td>Je Eingang <code>settings.inbox.retention_days</code> (Standard 90, 0 = nie): erledigte Anfragen werden nach N Tagen seit der letzten Änderung gelöscht – nebenbei bei ≈ 1 % der Verwaltungsaufrufe (höchstens alle 6 h) und per <code>php bin/console inbox:purge [--all]</code> (z. B. täglich per Cron). Gelöscht wird mit Protokolleintrag (nur Anzahl).</td></tr>
    <tr><td>API / MCP</td><td><code>GET /api/v1/requests</code> (<code>?status=neu|in_bearbeitung|erledigt|alle</code>, <code>?table=</code>, <code>?ciphertext=1</code>) und <code>PATCH /api/v1/requests/{id}</code> (<code>{"status", "table"}</code>; ohne table und mehrdeutiger ID → 409), MCP <code>list_requests</code> / <code>set_request_status</code> (Parameter <code>table</code>). <code>GET /data</code> listet Eingänge mit <code>kind: inbox</code> (Anzahl, Formular-Schema), <code>GET /data/{eingang}</code> nur Metadaten; <code>POST/PATCH/DELETE</code> auf Eingänge → 403.</td></tr>
  </table>
  <p><b>Kit-Formulare</b> (<code>theme.php → forms</code>) sind nur noch die Vorlage: je Formular entsteht beim ersten Start eine Eingangs-Tabelle (<code>'table' => ['handle', 'name', 'singular', 'icon']</code>, Felder aus <code>'fields'</code> = Repeater der Einstellungen oder Liste von Felddefinitionen; Feldnamen bleiben stabil, Übersetzungen <code>feld@en</code> werden übernommen). <code>enabled</code>, <code>mode</code>, <code>external_url</code> bleiben Schalter des Kits (externer Dienst = Link wie bisher). <code>Core\Forms</code> ist nur noch eine Kompatibilitätsschicht für Kit-Vorlagen (Service-Kacheln, <code>form-page</code>, <code>partials/form</code>) und bildet die Eingangs-Tabelle auf die alte API ab.</p>
  <p><b>Umstellung</b> (<code>Inbox::migrate</code>, idempotent): läuft je Website beim ersten Webaufruf nach einem Update und erneut, sobald ein Kit ein neues Formular oder eine neue <code>field_updates</code>-ID mitbringt (Merker <code>sys.inbox_migrated</code> = erledigte Formular-Schlüssel, <code>sys.inbox_legacy_moved</code>) bzw. mit <code>php bin/console migrate</code> oder <code>php bin/console inbox:migrate [--site=…|--all]</code>. Sie legt die Eingänge an, übernimmt die Zeilen der alten Tabelle <code>requests</code> <b>unverändert verschlüsselt</b> (gleicher Schlüssel; Spalte <code>legacy</code> = alte ID, Status und Datum bleiben; Anzeige als Beschriftung/Wert-Paare) und ergänzt Rollen mit Tabellenauswahl, die Anfragen lesen dürfen. Alt-Anfragen ohne passendes Formular landen in <code>anfragen_archiv</code>. Die Tabelle <code>requests</code> bleibt unangetastet und wird nicht mehr benutzt – nach Prüfung entfernbar: <code>DROP TABLE requests;</code> (vorher <code>site:backup</code>).</p>
  <p><b>Feld-Änderungen der Kit-Formulare</b>: <code>theme.php → forms → {key} → field_updates</code> = <code>[['id' =&gt; …, 'replace' =&gt; 'altes_feld', 'field' =&gt; [neue Definition]]]</code>. <code>Inbox::migrate</code> wendet jede ID einmal an (Merker <code>sys.inbox_field_updates</code>; neue Installationen direkt nach dem Anlegen des Eingangs): das alte Feld wird an seiner Stelle ersetzt – nur, wenn es noch existiert und das neue noch fehlt. Alte Anfragen behalten ihren Wert im <code>payload</code> und erscheinen unter der gespeicherten Beschriftung. Beispiel Praxis: <code>medikament</code> (Text) → Gruppe <code>medikamente</code> (medikament, staerke, packung).</p>

