<?php /** Entwicklerhandbuch · Frameworks (Tailwind, UIkit, Bootstrap) in Kits – Referenz: kits/frameworks */ ?>
  <p class="lead">Ein Kit darf mit einem bekannten CSS-Framework gebaut sein. Das mitgelieferte Demo-Kit <b><code>frameworks</code></b> zeigt dieselben Blöcke wahlweise mit <b>Tailwind CSS 4</b> oder <b>UIkit 3</b> – Bearbeiten auf der Website, Werkzeugleiste, Seitenleiste, Link- und Medienauswahl, Glossar, Datenlisten, Formulare, Karte und Video funktionieren mit beiden. Dieses Kapitel erklärt, warum das geht, wie man es richtig aufsetzt und welche Fallstricke die Tests gezeigt haben. Grundlagen zu Layern, Ladereihenfolge und Variablen: <a href="#css-js">CSS &amp; JS</a>.</p>

  <h3 id="fw-warum">Warum es funktioniert</h3>
  <ul>
    <li><b>Die Oberfläche des CMS liegt im Shadow DOM.</b> Werkzeugleiste (<code>.cms-bar-host</code>), Seitenleiste „Block“, Formatierungsleiste, Link- und Medienauswahl, Rückfragen und Meldungen (<code>#cms-layer-host</code>), Block-Leisten und „+ Block einfügen“ haben eigene Schatten-Wurzeln. Selektoren der Seite – auch <code>*</code>, <code>button</code>, <code>[hidden]</code> eines Frameworks – erreichen sie nicht; vererbte Werte (Schrift, Farbe, Zeilenhöhe) setzt <code>:host{all:initial}</code> zurück.</li>
    <li><b>Öffentliche Kern-Bausteine haben Präfixe</b> (<code>dff-</code> Formular, <code>dl-</code>/<code>df-</code> Datenliste und Detailseite, <code>gl-</code>/<code>glx-</code> Glossar, <code>vembed</code> Video, <code>cms-</code> Karte, Partner, Bearbeiten-Stifte) und bringen ihre Regeln selbst mit. Sie werden über Variablen an das Kit angepasst, nicht über Framework-Klassen.</li>
    <li><b>Keine globalen Resets im Kern.</b> <code>editor.css</code> enthält keine Regeln für bloße Elemente des Kits; was in der Seite liegen muss (Rahmen um Blöcke, Stifte, Notizen), ist mit <code>all:unset</code> bzw. doppelter Klasse gegen Framework-Regeln abgesichert.</li>
    <li><b>Das Framework gestaltet nur die Kit-Ebene:</b> Kopf, Fuß, Abschnitte und die Vorlagen der Kit-Blöcke. Was der Kern ausgibt (Formular, Tabelle der Datenliste, Glossar), bekommt Farben und Radius über Variablen in <code>css/site.css</code> des Kits.</li>
    <li><b>CSP:</b> Besucher bekommen <code>style-src 'self'</code> und <code>script-src 'self'</code> (<code>SiteController::csp()</code>). Vorkompiliertes CSS und Skripte vom eigenen Server sind erlaubt; UIkit initialisiert sich über Attribute (<code>uk-navbar</code>, <code>uk-offcanvas</code> …) und setzt Stile per CSSOM – beides CSP-konform. Inline-Skripte, Play-CDNs und <code>style</code>-Attribute im Markup sind es nicht.</li>
  </ul>

  <h3 id="fw-demo">Das Demo-Kit <code>frameworks</code></h3>
  <table class="doc-table">
    <tr><th>Thema</th><th>Umsetzung</th></tr>
    <tr><td>Umschalten</td><td>Design-Token <code>framework</code> (Verwaltung → Design → „Framework“, Klasse <code>fw-tailwind</code> | <code>fw-uikit</code> am <code>&lt;html&gt;</code>). Zum Vergleichen <code>?fw=uikit</code> bzw. <code>?fw=tailwind</code>: gilt nur für die Anfrage (Besucher bekommen kein Cookie; Adressen mit Query-String cached der Kern nicht), angemeldet zusätzlich für die Sitzung, damit Editor-Vorschauen dasselbe Framework rendern; <code>?fw=reset</code> hebt es auf. Code: <code>frameworks_fw()</code>.</td></tr>
    <tr><td>Vorlagen</td><td><code>blocks/{typ}.php</code> wählt nur die Vorlage (<code>include frameworks_view('hero')</code>); das Markup steht in <code>views/tailwind/</code> bzw. <code>views/uikit/</code>. Kopf, Fuß und Abschnitts-Hülle ebenso (<code>templates/partials/*</code> → <code>views/{fw}/header|footer|section.php</code>).</td></tr>
    <tr><td>Laden</td><td><code>templates/layout.php</code> → <code>frameworks_assets()</code>: Framework-CSS → <code>css/site.css</code> (beide: Tokens, Kern-Variablen) → nur UIkit: <code>css/uikit.css</code> (Brücke) → Kern-/Block-CSS → <code>design_head()</code> → <code>editor.css</code> (angemeldet). Skripte mit <code>defer</code>; UIkit-JS lädt auch im Bearbeiten-Modus (Kopf: Aufklappmenü, Offcanvas).</td></tr>
    <tr><td>Blöcke</td><td>Einstieg, Karten (<code>targetEdit</code>), Text + Bild, Text, Aufklappliste (FAQ, JSON-LD), Reiter, Handlungsaufruf mit Dialog, Kontakt (<code>$b-&gt;central()</code>), Video (Kern-Fragment). Datenliste: eigene Ausgabe „Karten“/„Liste“ (<code>blocks/data_list.php</code>, gleiche Abfrage wie der Kern), „Kompakt“/„Tabelle“ bindet den Kern-Block ein. Formular und Karte: Kern.</td></tr>
    <tr><td>Bearbeiten</td><td>Interaktive Teile geben im Editor keine JS-Attribute aus: Aufklapplisten und Reiter stehen offen untereinander, der Dialog als Kasten unter den Buttons, klickbare Karten (<code>::after</code> über der Karte) sind abgeschaltet – so bleibt jeder Text direkt bearbeitbar.</td></tr>
    <tr><td>Testwebsite</td><td><code>site:create frameworks frameworks.localhost:8088,frameworks.localhost frameworks</code>; Startinhalte (fiktive Firma „Beispielwerk“, Seitenbaum, Tabelle „Projekte“ mit Detailseite, Formular „Anfragen“, Glossar, erzeugte Bilder) über <code>seed.php</code>; neu einspielen mit <code>CMS_SITE=frameworks php kits/frameworks/tools/demo.php --force</code>.</td></tr>
  </table>

  <h3 id="fw-tailwind">Tailwind CSS 4 – empfohlenes Setup</h3>
  <ul>
    <li><b>Vorkompilieren, kein Play-CDN.</b> <code>kits/{kit}/package.json</code> mit <code>tailwindcss</code>, <code>@tailwindcss/cli</code> (optional <code>@tailwindcss/typography</code>); <code>kits/{kit}/build.mjs</code> ruft die CLI in <code>vendors()</code> auf (<code>cd tools &amp;&amp; pnpm run build</code> installiert und baut). Ausgabe nach <code>public/assets/kits/{kit}/css/tailwind.css</code> und einchecken – auf dem Server läuft kein Node. Das Play-CDN scheitert an der CSP (Skript von fremdem Host, erzeugte <code>&lt;style&gt;</code>-Elemente) und ist für Produktion nicht gedacht.</li>
    <li><b>Quellen ausdrücklich nennen:</b> <code>@import "tailwindcss/utilities.css" layer(utilities) source(none);</code> und dann <code>@source "../views/tailwind"; @source "../templates"; @source "../blocks"; @source "../functions.php";</code>. Ohne <code>source(none)</code> durchsucht Tailwind den ganzen Kit-Ordner (auch UIkit-Vorlagen, Doku, Startinhalte) und erzeugt unnötige Utilities.</li>
    <li><b>Preflight in <code>@layer base</code> – so lassen.</b> Tailwind 4 legt alles in Layer (<code>theme, base, components, utilities</code>). Ungeschichtetes CSS gewinnt immer gegen Layer – Kern-CSS, <code>editor.css</code> und Editor.js-Stile sind ungeschichtet, also kann Preflight keine Kern-Komponente „kaputt resetten“; die CMS-Oberfläche im Shadow DOM erreicht es ohnehin nicht. Ein zusätzliches Einschränken (Preflight nur unter einem Wrapper) ist nicht nötig. Getestet wurden beide Fassungen (mit und ohne Preflight, Design-Token <code>tw_preflight</code>): beide ohne Konflikt mit dem CMS – aber <b>ohne</b> Preflight fielen zuerst axe-Prüfungen durch, weil Utilities den Reset voraussetzen (Buttons mit Systemgrau als Hintergrund, Zeilenhöhe „normal“ → Links nur 18 px hoch, WCAG 2.5.8). Wer Preflight weglässt, muss mindestens <code>html{line-height:1.5}</code>, den Button-Reset und Abstands-Resets selbst mitbringen (siehe <code>tailwind/app-nopf.css</code>).</li>
    <li><b>Kehrseite der Layer:</b> Eine Utility am Kern-Markup verliert gegen die Kern-Regel. Kern-Bausteine über ihre Variablen anpassen (<code>--dff-*</code>, <code>--dl-*</code>, <code>--gl-*</code>, <code>--cms-map-*</code>) oder eine eigene Ausgabe schreiben (wie <code>blocks/data_list.php</code>). Umgekehrt gewinnt auch die eigene <code>site.css</code> gegen jede Utility – Grundwerte, die Utilities überschreiben sollen (Symbolgröße <code>.ico</code>, Bildformate), gehören dort in <code>@layer base{…}</code> (gleicher Name wie Tailwinds Layer, also darunter).</li>
    <li><b>Kern-Klassen im Markup:</b> Section-Klassen kommen vom Kern (<code>sec</code>, <code>bg-{hintergrund}</code>, <code>pt-/pb-small|none</code>, <code>v-{variante}</code>) und stehen nicht im Quelltext des Kits – gestaltet werden sie in <code>@layer components</code> (immer ausgegeben). Hintergrund-Schlüssel so wählen, dass keine Utility entsteht: <code>plain, tint, band, ink</code> statt <code>white</code>/<code>accent</code> (<code>bg-white</code> ist eine Tailwind-Utility).</li>
    <li><b>Dynamische Klassen:</b> Tailwind findet nur wörtliche Klassennamen. Spaltenzahl der Datenliste als vollständige Namen aus einer PHP-Tabelle (<code>frameworks_cols()</code>), nie <code>"lg:grid-cols-$n"</code>. Werte, die erst die Redaktion wählt und nirgends wörtlich stehen, mit <code>@source inline("aspect-{video,square,[4/3]}")</code> erzeugen (Safelist).</li>
    <li><b>Klassen aus dem Editor:</b> Die Formatierungsleiste schreibt nur den Klassenvertrag (<code>t-lead</code>, <code>t-small</code>, <code>t-note</code>, <code>c-accent</code> … – <a href="#rich-text-stile">Rich-Text-Stile</a>) und Elemente ohne Klassen. Den Vertrag in <code>@layer components</code> definieren; Rich-Text in <code>prose</code> (Typography-Plugin) setzen, sonst sind Listen und Überschriften nach Preflight ungestaltet. Kern-Bausteine ohne Klassen an Überschriften (Datenliste, Formular, Glossar-Übersicht) brauchen Grundwerte für <code>h1–h4</code> in <code>@layer base</code>.</li>
    <li><b>Farben aus dem Style-Editor:</b> <code>@theme inline { --color-accent: var(--fw-accent); }</code> – die Utility verweist auf die Variable, Änderungen im Style-Editor wirken ohne Build.</li>
    <li><b>Dunkelmodus:</b> eigene Variante, die dem Kit-Schalter, der Vorschau und dunklen Abschnitten folgt:
      <pre><code>@custom-variant dark {
  @media (prefers-color-scheme: dark) { &amp;:where(.has-dark, .has-dark *) { @slot; } }
  &amp;:where(.is-dark, .is-dark *, .bg-ink, .bg-ink *) { @slot; }
}</code></pre></li>
    <li><b>Bewegung:</b> Übergänge nur mit <code>motion-safe:</code>.</li>
  </ul>

  <h3 id="fw-uikit">UIkit 3 – empfohlenes Setup</h3>
  <ul>
    <li><b>Mitliefern:</b> <code>uikit.min.css</code>, <code>uikit.min.js</code>, <code>uikit-icons.min.js</code> und <code>LICENSE.md</code> (MIT) per <code>build.mjs</code> aus <code>node_modules/uikit/dist</code> nach <code>public/assets/kits/{kit}/vendor/uikit/</code>; Lizenz in <code>THIRD-PARTY-NOTICES.md</code>. Für Projekte lohnt ein eigener Build aus den Less-/SCSS-Quellen: nur benutzte Komponenten (das volle CSS hat 283 KB, gzip 31 KB) und eigene Farbvariablen.</li>
    <li><b>Reihenfolge:</b> <code>uikit.min.css</code> → <code>css/site.css</code> → Brücke <code>css/uikit.css</code> → Kern-CSS. Skripte im <code>&lt;head&gt;</code> mit <code>defer</code>; UIkit startet über Attribute – kein Init-Code, kein Inline-Skript.</li>
    <li><b>Kopf klebend mit der Werkzeugleiste:</b> <code>uk-sticky</code> am Kopf mit <code>data-cms-sticky</code>, <code>offset</code> bei 0 lassen. <code>editor.css</code> schiebt <code>.uk-sticky</code>/<code>.uk-sticky-fixed</code> um <code>--cms-bar-offset</code> nach unten (mit <code>!important</code>, weil UIkit <code>top</code> per JS setzt) – am Desktop die Leistenhöhe, am Telefon (Leiste scrollt mit) bis 0. Eigene CSS-Köpfe nutzen <code>top:var(--cms-toolbar-h,0)</code>.</li>
    <li><b>Offcanvas und Modal beim Bearbeiten:</b> Der Kern hebt den Kopf des Kits über die Block-Bedienelemente (z-index 2147483050). Geöffnete Framework-Overlays (<code>.uk-offcanvas</code>, <code>.uk-modal</code>, Bootstrap <code>.offcanvas</code>/<code>.modal</code> + Backdrops) stellt <code>editor.css</code> darüber (2147483055) und rückt Seitenmenüs um die sichtbare Leistenhöhe ein – sonst verdeckten Kopf und Leiste den Schließen-Knopf (Befund der Tests am Telefon). Fokusfalle, <kbd>Esc</kbd> und Rückgabe des Fokus übernimmt UIkit; Modals hängt UIkit an <code>&lt;body&gt;</code> – außerhalb von <code>uk-light</code>, also eigene Farben für den Dialog.</li>
    <li><b>Kein Dunkelmodus, feste Farben:</b> UIkit 3 ist mit festen Farben kompiliert. Die Brücke stellt die benutzten Komponenten auf Variablen um (<code>--u-bg</code>, <code>--u-fg</code>, <code>--u-head</code>, <code>--u-card</code> …) und tauscht nur diese für hell/dunkel. Dunkle Abschnitte über das „Inverse“-Konzept: <code>uk-section-secondary uk-light</code> bzw. <code>uk-section-primary uk-light</code>.</li>
    <li><b>Kontrast:</b> UIkits Standard-Grau <code>#999</code> (Navigation, <code>uk-text-meta</code>, Reiter, Unternavigation) hat auf Weiß nur 2,8:1, Link-/Primärblau <code>#1e87f0</code> 3,7:1, <code>uk-light</code> stellt Text auf 70 %/50 % Weiß – alles unter WCAG AA. Die Brücke setzt dunklere Töne bzw. die Akzentfarbe des Kits.</li>
    <li><b>Interaktive Komponenten im Editor:</b> <code>uk-accordion</code>, <code>uk-tab</code>/<code>uk-switcher</code> und <code>uk-modal</code> nur für Besucher ausgeben (<code>is_editing()</code>); im Editor alles offen. Ein Klick zum Bearbeiten klappte sonst den Eintrag zu. Kopf-Komponenten (<code>uk-navbar</code>-Dropdown, <code>uk-offcanvas</code>) bleiben aktiv und funktionieren beim Bearbeiten.</li>
  </ul>

  <h3 id="fw-bootstrap">Bootstrap (kurz, nicht im Demo-Kit)</h3>
  <p>Dieselben Grundsätze – nicht im Demo-Kit und nicht getestet, nur aus dem Aufbau des Kerns abgeleitet: Bootstrap 5 vorkompiliert mitliefern (oder per Sass nur die benötigten Teile bauen), <code>bootstrap.bundle.min.js</code> mit <code>defer</code>; Komponenten starten über <code>data-bs-*</code>-Attribute (CSP-konform). Reboot ist ein globaler Reset ohne Layer, betrifft aber nur Elemente der Seite – die CMS-Oberfläche liegt im Shadow DOM. Klebende Köpfe mit <code>.sticky-top</code>/<code>.fixed-top</code> und <code>.offcanvas</code>/<code>.modal</code> behandelt <code>editor.css</code> wie bei UIkit. Farben über die CSS-Variablen von Bootstrap (<code>--bs-primary</code> …) an die Design-Tokens koppeln; Dunkelmodus mit <code>data-bs-theme="dark"</code> bzw. eigener Media-Query. Kern-Formular: Variablen statt <code>.form-control</code> (das Markup kommt vom Kern), Button über <code>button_class</code> (<code>btn btn-primary</code>).</p>

  <h3 id="fw-fallstricke">Fallstricke und Lösungen aus den Tests</h3>
  <table class="doc-table">
    <tr><th>Befund</th><th>Ursache</th><th>Lösung</th></tr>
    <tr><td>z-index</td><td>Framework-Werte liegen bei 980–1090 (UIkit, Bootstrap) bzw. <code>z-50</code>; der Kern hebt den Kopf beim Bearbeiten auf 2147483050.</td><td>Kit-Werte unter 2000 lassen; die Z-Skala des Kerns steht in <code>editor.css</code> (<a href="#css-js">CSS &amp; JS</a>). Overlays der Frameworks hebt der Kern beim Bearbeiten selbst an.</td></tr>
    <tr><td>Klebender Kopf unter der Leiste</td><td>UIkit setzt <code>top</code> inline.</td><td><code>data-cms-sticky</code> am Kopf; Kern-Regel mit <code>!important</code> für <code>.uk-sticky</code>, <code>.sticky-top</code>, <code>.sticky.top-0</code>; eigene Köpfe <code>top:var(--cms-toolbar-h,0)</code>. Getestet bei 1440 und 390 px.</td></tr>
    <tr><td>Kern-Variablen wirkungslos</td><td>Kern-Stylesheets (<code>data.css</code>, <code>dataform.css</code>) laden nach <code>site.css</code> und setzen dieselben Variablen mit gleicher Spezifität – Kern-Standard gewann, im Dunkelmodus dunkle Tabellenköpfe auf dunklem Grund.</td><td>Variablen mit <code>:root .dl, :root .dff-wrap …</code> setzen. Standardwerte aus <code>currentColor</code> ableiten, dann passen sie hell, dunkel und in dunklen Abschnitten.</td></tr>
    <tr><td>Formularfelder zu breit (UIkit, 390 px)</td><td>UIkit setzt kein globales <code>box-sizing:border-box</code>; <code>width:100%</code> + Innenabstand lief über.</td><td>Kern-Fix: <code>dataform.css</code> setzt <code>box-sizing</code> an den Feldern selbst.</td></tr>
    <tr><td>Preflight und Buttons/Felder</td><td>Preflight macht Buttons transparent, Felder rahmenlos, Listen ohne Punkte, Überschriften normal groß.</td><td>Für Kern-Bausteine kein Problem (eigene, ungeschichtete Regeln). Kit-Vorlagen gestalten Buttons über <code>.btn</code> in <code>@layer components</code>, Rich-Text über <code>prose</code>.</td></tr>
    <tr><td><code>prose</code>-Namensgleichheit</td><td>Kern-Bausteine geben <code>class="prose"</code> aus (Detailseite, Glossar) – das Typography-Plugin gestaltet sie mit, im Dunkelmodus fehlte <code>prose-invert</code>.</td><td>In <code>@layer utilities</code>: <code>.df .prose, .glx .prose { @variant dark { @apply prose-invert; } }</code>.</td></tr>
    <tr><td><code>[hidden]</code></td><td>Kern-Skripte blenden mit dem Attribut <code>hidden</code> aus.</td><td>Unkritisch: Preflight (<code>!important</code>), UIkit (<code>!important</code>) und Bootstrap setzen <code>[hidden]{display:none}</code>. Nie <code>display</code> per Utility an Elemente mit <code>hidden</code> hängen – oder <code>hidden:</code>-Variante nutzen.</td></tr>
    <tr><td>Symbole zu groß / als Block</td><td>Preflight: <code>svg{display:block}</code>; <code>.ico</code>-Regel ohne Layer schlug Utilities wie <code>size-5</code>.</td><td><code>.ico{display:inline-block;width:1em;height:1em}</code> in <code>@layer base</code> der <code>site.css</code>.</td></tr>
    <tr><td>Links nicht unterscheidbar (UIkit)</td><td><code>a{text-decoration:none}</code>; Link im Text des Formulars („Datenschutzhinweise“) nur farbig – axe <code>link-in-text-block</code>.</td><td>Links ohne Klasse in <code>main</code> unterstreichen.</td></tr>
    <tr><td>CSP-Meldung durch UIkit-Symbole</td><td><code>uk-navbar-toggle-icon</code> und <code>uk-accordion-icon</code> enthalten ein <code>&lt;style&gt;</code> im SVG – ohne <code>'unsafe-inline'</code> blockiert.</td><td>Symbole aus <code>uikit-icons</code> (<code>uk-icon="icon: menu"</code>) oder <code>icon()</code> des Kerns.</td></tr>
    <tr><td>Knopf mit Systemgrau (UIkit)</td><td><code>.uk-navbar-toggle</code> als <code>&lt;button&gt;</code> – UIkit setzt dessen Hintergrund nicht zurück (dunkel: #6b6b6b).</td><td><code>background:none;border:0</code> in der Brücke.</td></tr>
    <tr><td>Primär-Button ohne lesbare Schrift (UIkit)</td><td>Eigene Linkfarbe <code>.fw-uikit a</code> (0,1,1) schlug <code>.uk-button-primary</code> (0,1,0).</td><td>Button-Regeln mit derselben Präfix-Klasse schreiben.</td></tr>
    <tr><td>Formular des Kerns</td><td>Markup ohne Framework-Klassen.</td><td>Variablen <code>--dff-*</code>, Button über <code>button_class</code> (<code>btn btn-primary uk-button uk-button-primary</code> – geladen ist immer nur ein Framework). Fehler, Pflichtfelder, Erfolg und Spamschutz bleiben im Kern.</td></tr>
  </table>
  <p><b>Prüfung</b> (Playwright, beide Frameworks, 1440 und 390 px, hell und dunkel): Besucher ohne Konsolenfehler und CSP-Verstöße, axe 0 Verstöße (WCAG 2.2 AA) auf Start, Unterseiten, Datenliste, Detailseite, Kontakt mit Formular und Glossar; Reiter, Aufklappliste, Dialog (Esc), Menüs, Glossar-Bubble, Formular-Fehlermeldungen. Angemeldet: Werkzeugleiste unverändert (Lato 14 px, eigene Farben), Inline-Bearbeitung von Überschrift und Text, Seitenleiste, Link- und Medienauswahl, Kopf klebt unter der Leiste, Aufklappmenü und Offcanvas beim Bearbeiten. Tailwind zusätzlich ohne Preflight.</p>

  <h3 id="fw-eigenes">Eigenes Framework-Kit beginnen</h3>
  <ol>
    <li><code>php bin/console kit:create meinkit --from=frameworks</code> – kopiert das Kit, benennt das Präfix <code>frameworks_</code> → <code>meinkit_</code> um.</li>
    <li>Framework wählen: einen Ordner unter <code>views/</code> behalten, <code>meinkit_fw()</code> fest darauf stellen bzw. das Token <code>framework</code> aus <code>theme.php</code> entfernen; bei Tailwind <code>tailwind/</code>, bei UIkit <code>assets/css/uikit.css</code> und die UIkit-Zeilen in <code>build.mjs</code> behalten, nicht benötigte Pakete aus <code>package.json</code> streichen.</li>
    <li>Bauen: <code>cd tools &amp;&amp; pnpm run build</code> (nur Tailwind: <code>node kits/meinkit/build.mjs</code>). Gebautes CSS und Vendoren einchecken, Lizenzen in <code>THIRD-PARTY-NOTICES.md</code>.</li>
    <li>Testwebsite anlegen (<code>site:create</code>, <code>user:create</code>), Startinhalte aus <code>tools/demo-content.php</code> anpassen, prüfen wie oben (Konsole, CSP, axe, Bearbeiten-Modus).</li>
  </ol>
