<?php /** Entwicklerhandbuch · Prüf-Ebene „Eingereicht“ (Core\Review) */ ?>
  <p class="lead">Transparenz und Kontrolle über automatische Änderungen: Jede Schreibaktion über REST-API, MCP und die KI-Funktionen wird mit Herkunft protokolliert; Zugänge im Modus <b>„Zur Freigabe“</b> ändern nichts, sondern reichen ein. Oberfläche: <a href="<?= e(url('/admin/ai/eingereicht')) ?>"><?= e($aiBrand) ?> → Eingereicht</a> (Recht <code>review.manage</code>, Standard nur Administration; Funktion <code>review</code>).</p>
  <table class="doc-table">
    <tr><th>Teil</th><th>Beschreibung</th></tr>
    <tr><td>Tabelle <code>change_log</code> (je Website)</td><td>Herkunft: <code>channel</code> (api | mcp | ai), <code>token_id</code>/<code>token_name</code>, <code>client</code> (MCP-Client aus <code>initialize → clientInfo</code>, gespeichert in <code>api_tokens.mcp_client</code>, da der Server zustandslos ist), <code>feature</code> (KI: text, translate, seo, alt, pagegen, tablegen), <code>user_id</code> (Token-Benutzer bzw. angemeldete Person), Gegenstand (<code>entity_type</code>: page, entry, media, settings, design, pick, table + <code>entity_id</code>, <code>entity_label</code>), <code>action</code> (Methode von <code>CmsService</code>), <code>summary</code>, <code>diff_json</code>, <code>status</code> applied | pending | rejected, Prüfung (<code>reviewer_id</code>, <code>reviewed_at</code>, <code>reason</code>). Einreichungen speichern zusätzlich <code>payload_json</code> (Methode + normalisierte Argumente, Seiten-Verweise als ID), <code>before_json</code>/<code>after_json</code> und <code>base_hash</code>. Erledigte Zeilen älter als 365 Tage werden gelegentlich gelöscht.</td></tr>
    <tr><td>Ablauf (<code>Core\Review\Queue::run</code>)</td><td>Jede Schreibmethode von <code>CmsService</code> ruft zuerst <code>gate()</code> auf. <b>Direkt</b>: ausführen, Zustand vorher/nachher (<code>Core\Review\Snapshot</code>) vergleichen (<code>Core\Review\Diff</code>, feld- und blockweise), als <code>applied</code> protokollieren. <b>Zur Freigabe</b>: <i>Probelauf</i> in einer Transaktion (Website- und ggf. geteilte Datenbank; verschachtelte Transaktionen als SAVEPOINT) – dieselben Prüfungen wie sonst, Fehler kommen sofort als 422 –, Folgezustand lesen, zurückrollen, Einreichung speichern. Aktionen mit Dateien (Löschen, Zuschnitt, Design) werden nicht ausgeführt, sondern ihr Folgezustand berechnet. Uploads und Anfrage-Status gelten immer sofort.</td></tr>
    <tr><td>Modus je Token</td><td><code>api_tokens.review_mode</code>: <code>direct</code> | <code>review</code>. Neue Tokens mit Schreibrecht: Vorgabe „Zur Freigabe“; bestehende Tokens behalten „Direkt übernehmen“ (umschaltbar unter API &amp; MCP).</td></tr>
    <tr><td>REST-API</td><td>Schreibzugriff eines Freigabe-Tokens → <b>HTTP 202</b> <code>{"data": {"status": "pending_review", "id", "url", "status_url", "summary", "entity", "message"}}</code> (+ <code>Content-Location</code>). Stand: <code>GET /api/v1/changes/{id}</code> → <code>pending_review</code> | <code>applied</code> (<code>note</code>, falls vor dem Übernehmen bearbeitet) | <code>rejected</code> (<code>reason</code>) + Liste der Unterschiede; <code>GET /api/v1/changes?status=…</code> = eigene Einreichungen und protokollierte Änderungen. Ein Token sieht nur seine eigenen.</td></tr>
    <tr><td>MCP</td><td>Schreib-Tools liefern bei Freigabe-Tokens ein normales Ergebnis (kein Fehler) mit <code>structuredContent</code> <code>{status: "pending_review", id, url, …}</code>; die Server-Anweisungen (<code>initialize → instructions</code>) weisen darauf hin. Tool <code>get_change_status</code> (lesend, id oder Liste).</td></tr>
    <tr><td>Freigeben</td><td><code>Queue::approve()</code> spielt die gespeicherte Methode über <code>CmsService</code> ein – Urheber bleibt der Token-Benutzer (Revisionen „API/MCP „Name“: …“), Prüfer steht im Protokoll. <b>Bearbeiten &amp; übernehmen</b>: Textwerte der Einreichung (Einstellungen, Eintragsfelder, Medien-Infos, Seiteneinstellungen) vorher anpassen; Blockänderungen: „Als Entwurf übernehmen &amp; im Editor bearbeiten“ (ohne <code>publish</code>). Sammelaktionen übernehmen/ablehnen; Vorschau einer Seite mit den vorgeschlagenen Blöcken (<code>/admin/ai/eingereicht/{id}/vorschau</code>, nichts wird gespeichert).</td></tr>
    <tr><td>Konflikte</td><td>Geändert seit der Einreichung (Prüfsumme) <i>und</i> dieselben Felder bzw. Blöcke betroffen – oder die Aktion ersetzt alles bzw. veröffentlicht (blocksReplace, restore, discard, Design, <code>publish</code>) → Übernehmen gesperrt, Anzeige der drei Stände (bei Einreichung · jetzt · Vorschlag). „Neu prüfen“ wiederholt den Probelauf auf dem aktuellen Stand und berechnet den Unterschied neu.</td></tr>
    <tr><td>KI (<code>AiController</code>)</td><td>Übernahmen (Text einfügen, Übersetzung, SEO, Alt-Texte, Seiten- und Tabellen-Generator) werden mit <code>Queue::track()</code> protokolliert (Kanal ai). Einstellung <code>sys.review_ai</code> („KI-Übernahmen ebenfalls zur Freigabe“, Standard aus): Text, Übersetzung, SEO und Alt-Texte laufen dann über <code>CmsService::forAi()</code> als Einreichung; die Generatoren legen weiterhin direkt unveröffentlichte Entwürfe an, geteilte Medien-Pools werden direkt gespeichert.</td></tr>
    <tr><td>Hinweise</td><td>Zähler im Menü (am Menüpunkt „<?= e($aiBrand) ?>“ bzw. „Eingereicht“), in der KI-Übersicht und in der Netzwerk-Übersicht (<code>review_pending</code> je Website). E-Mail an alle Konten mit <code>review.manage</code> bei neuen Einreichungen (<code>sys.review_notify</code>, höchstens alle 15 Minuten; <code>mail_redirect</code> gilt).</td></tr>
    <tr><td>Entwürfe (<code>Core\Review\Drafts</code>)</td><td>Verwaltung → <a href="<?= e(url('/admin/entwuerfe')) ?>">Entwürfe</a> (<code>DraftController</code>, Rechte wie Seiten- und Datenverwaltung: <code>pages.edit</code>/<code>pages.publish</code>, <code>data.edit</code>/<code>data.publish</code>/<code>data.delete</code> je Tabelle): Seiten mit Status ≠ <code>published</code> sowie veröffentlichte Seiten, deren <code>content_draft</code> sich blockweise von <code>content_published</code> unterscheidet (<code>Drafts::pageChanged()</code>, der Zeitstempel von Editor.js zählt nicht), und Einträge eigener Tabellen (nicht geteilt) mit <code>status = draft</code>. Herkunft aus dem Vermerk der letzten Revision („Content-Sync (…)“, „API/MCP/KI „Token“: …“, Seiten-Generator) bzw. der letzten übernommenen Zeile in <code>change_log</code>. Unterschiede über <code>Diff::compute()</code> (live ↔ Entwurf) und dieselbe Darstellung wie hier (<code>review/_diff.php</code>). Veröffentlichen: <code>Pages::publish()</code> bzw. <code>Entries::setStatus()</code>; Verwerfen: <code>Pages::discardDraft()</code> (Entwurf bleibt Revision) bzw. Eintrag löschen mit JSON-Sicherung in <code>draft_discards</code> (90 Tage, „Wiederherstellen“ als Entwurf). Notiz/zuständige Person je Schlüssel (<code>page:ID</code>, <code>entry:tabelle:ID</code>) in <code>draft_notes</code>. Weitere Quellen (z. B. offene Einreichungen als <code>change:ID</code>) liefern Einträge im selben Format (<code>Drafts::item()</code>). Zähler im Menü: <code>Drafts::count()</code>.</td></tr>
  </table>
