<?php /** Entwicklerhandbuch · Funktionsumfang & Erweiterungen (inkl. CalDAV/CardDAV) */ ?>
  <p class="lead">Je Website ist festgelegt, welche Funktionen und Erweiterungen laufen – per Konfiguration (Agentur, hat Vorrang) oder in der Verwaltung unter <b>Administration → Funktionen &amp; Erweiterungen</b> (Haupt-Admin). Grundsatz: nur einschalten, was die Website wirklich braucht.</p>
  <pre><code>// config/sites/kunde.php (Hauptwebsite: config/config.local.php)
'preset'      =&gt; 'content',                         // full (Standard) | content | minimal
'features'    =&gt; ['data.schema' =&gt; false, 'languages' =&gt; true],
'blocks'      =&gt; ['deny' =&gt; ['video']],             // oder 'allow' =&gt; [...] als Positivliste
'extensions'  =&gt; ['dav'],
'integrators' =&gt; ['team@agentur.de'],               // diese Konten sehen immer alles</code></pre>
  <table class="doc-table">
    <tr><th>Preset</th><th>Wirkung</th></tr>
    <tr><td><code>full</code></td><td>Alles an (Standard, bisheriges Verhalten).</td></tr>
    <tr><td><code>content</code></td><td>Redaktion pflegt Inhalte; aus: <code>data.schema</code> (Tabellen-Baukasten), <code>data.shared</code>, <code>system</code>, <code>users</code>, <code>api</code>, <code>mcp</code>, <code>theme_switch</code>, <code>design</code>.</td></tr>
    <tr><td><code>minimal</code></td><td>Nur Texte und Bilder bestehender Seiten; zusätzlich aus: <code>pages.structure</code>, <code>data</code> (und damit <code>calendar</code>, <code>forms.data</code>), <code>requests</code>, <code>languages</code>, <code>search</code>, <code>ai</code>.</td></tr>
    <tr><td colspan="2"><code>support</code>, <code>review</code>, <code>media</code>, <code>media.captions</code>, <code>maps</code>, <code>pwa</code> und <code>settings</code> bleiben in jedem Preset an. Integratoren und Netzwerk-Konten sehen immer alles.</td></tr>
  </table>
  <table class="doc-table">
    <tr><th>Funktion</th><th>Bedeutung</th></tr>
    <?php foreach (\Core\Features::catalog() as $__k => $__f): ?><tr><td><code><?= e($__k) ?></code></td><td><?= e(is_array($__f) ? (string) ($__f['label'] ?? $__f[0] ?? '') : (string) $__f) ?></td></tr><?php endforeach; ?>
  </table>
  <p>Eine abgeschaltete Funktion sperrt ihre Rechte für <b>alle</b> Rollen (auch „Administration“) – Navigation, Seiten, Rollen-Editor, API und MCP folgen automatisch. Zugehörige öffentliche Routen antworten mit 404 (z. B. <code>/mcp</code>, <code>/manifest.webmanifest</code>, <code>/sw.js</code>, <code>/proxy/ofm/…</code>, <code>/kalender/….ics</code>, <code>/formular/…</code>, <code>/anfrage/…</code>); bei abgeschalteter API bleiben <code>/api/v1</code>, <code>/api/v1/public</code> und <code>/api/v1/openapi.json</code> erreichbar. Kern-Blöcke hängen an ihrer Funktion (Datenlisten an <code>data</code>, Karte an <code>maps</code>, Kalender an <code>calendar</code>, Formulare an <code>forms.data</code>/<code>requests</code>). Gesperrte Blocktypen bleiben in bestehenden Seiten bearbeitbar, lassen sich aber nicht neu einfügen (Editor, API). Den wirksamen Stand zeigen Funktionen &amp; Erweiterungen, Grundeinstellungen → Systeminfo und <code>features:list</code>. Im Code: <code>Features::on('api')</code>, <code>Features::allowsBlock('video')</code>, <code>Features::integrator()</code>.</p>
  <h3 id="funktionen-ui">Schalten in der Verwaltung, Vorrang und Freigabe</h3>
  <table class="doc-table">
    <tr><th>Thema</th><th>Verhalten</th></tr>
    <tr><td>Seite</td><td><b>Administration → Funktionen &amp; Erweiterungen</b> (<code>/admin/funktionen</code>, <code>FeaturesController</code>): Funktionen gruppiert (<code>Core\FeatureInfo</code>: Inhalte, Daten, Medien, KI, Schnittstellen, Kommunikation, Sicherheit &amp; Betrieb) mit Schalter, Beschreibung, „Was passiert beim Einschalten“ (Rechte aus <code>Features::catalog()</code>, Menü, externe Anfragen, Cron, Website, Daten), Abhängigkeiten (<code>Features::REQUIRES</code>) und Status; darunter die installierten Erweiterungen und die letzten 10 Änderungen.</td></tr>
    <tr><td>Wer</td><td>Recht <code>system.features</code> (Administration hat es über <code>*</code>, weiteren Rollen im Rollen-Editor geben). Netzwerk-Installation (<code>Sites::multi()</code>): das Recht wirkt erst, wenn die Netzwerk-Administration auf der Seite der Website „Freigabe für die Website-Administration“ einschaltet (<code>sys.features_delegate</code>, Standard aus); bis dahin sieht die Website-Administration (<code>system.manage</code>) die Seite nur lesend. Netzwerk-Konten und Integratoren schalten immer (Netzwerk-Übersicht → Wartung → „Funktionen &amp; Erweiterungen“).</td></tr>
    <tr><td>Speicher</td><td>UI-Schalter je Website in <code>sys.features_ui</code> (nur ausdrücklich gesetzte Werte) bzw. für <code>chat</code>/<code>sources</code> deren bisherige Schalter <code>sys.userchat_enabled</code>/<code>sys.sources_enabled</code>; Erweiterungen in <code>sys.extensions_ui</code>.</td></tr>
    <tr><td>Vorrang</td><td>Katalog-Standard (inkl. Standard-AUS) → UI-Schalter → <code>preset</code> → <code>'features'</code> der Konfiguration. Was Preset oder <code>'features'</code> nennen, ist in der Verwaltung gesperrt („per Konfiguration festgelegt (config/sites/{key}.php)“, Tooltip mit Freigabe-Hinweis). Erweiterungen: <code>'extensions' =&gt; ['dav']</code> = an und gesperrt, <code>['dav' =&gt; false]</code> = aus und gesperrt, alle übrigen schaltet die Verwaltung.</td></tr>
    <tr><td>Sicherheit</td><td>Einschalten sicherheitsrelevanter Funktionen (<code>api</code>, <code>mcp</code>, <code>ai</code>, <code>chat.visitor</code>, <code>sources</code>, <code>video.tools</code>, <code>dav</code>) und von Erweiterungen mit <code>'risk'</code> verlangt die Bestätigung des Risiko-Texts und das Passwort (Netzwerk-Konten: Passwort des Netzwerk-Kontos; Ratenbegrenzung wie „Passwort bestätigen“, 5 Versuche/15 min). Der Core hat keinen Passkey-/TOTP-Step-up – daher Passwort. Ausschalten braucht keine Bestätigung (außer Vorsicht-Hinweise bei <code>users</code>, <code>system</code>, <code>data.schema</code>, <code>theme_switch</code>).</td></tr>
    <tr><td>Protokoll</td><td>Tabelle <code>feature_log</code> je Website (Zeit, Konto, Art, Ziel, alt/neu, Detail, IP-Hash; <code>Core\FeatureLog</code>), im Netzwerk zusätzlich <code>network_log</code> (<code>features.*</code>).</td></tr>
    <tr><td>Kommandozeile</td><td><code>features:list</code> (Stand und Quelle), <code>features:release [--dry-run] [--only=features|extensions]</code>: überträgt <code>preset</code>/<code>features</code>/<code>extensions</code> aus <code>config/sites/{key}.php</code> (Einzel-Installation auch <code>config/config.local.php</code>; im Netzwerk nie – gilt für alle Websites; <code>config/config.php</code> nie) in die UI-Schalter, entfernt nur diese Einträge (Tokenizer, Kommentare bleiben), prüft die neue Datei (Syntax, übrige Werte unverändert), legt <code>{datei}.{JJJJMMTT-HHMMSS}.bak</code> an und zeigt ein Diff. Der wirksame Zustand bleibt gleich; Erweiterungen mit <code>'required' =&gt; true</code> bleiben in der Konfiguration. Zurück: Sicherung zurückkopieren.</td></tr>
  </table>

  <h3>Erweiterungen</h3>
  <p>Zusätzliche Funktionen, die nicht jedes Projekt braucht (z. B. CalDAV/CardDAV), kommen als Erweiterung – der Core bleibt schlank. <b>Verteilung per Composer</b> (Versionierung, Abhängigkeiten, private Repositories), projektspezifisches direkt im Ordner:</p>
  <pre><code>extensions/{name}/extension.php          # projektspezifisch
vendor/{hersteller}/{paket}/extension.php  # composer require agentur/mycms-shop  ("type": "mycms-extension")

return [
    'name' =&gt; 'shop', 'label' =&gt; 'Shop', 'version' =&gt; '1.0.0', 'requires' =&gt; '&gt;=1.0.0',
    'boot' =&gt; function (Core\Extension $x) {
        $x-&gt;feature('shop', 'Shop', ['shop.edit']);
        $x-&gt;permissions('Shop', ['shop.edit' =&gt; 'Produkte pflegen']);
        $x-&gt;blocks(['produkte' =&gt; ['label' =&gt; 'Produkte', 'fields' =&gt; [...]]]);   // Renderer: blocks/produkte.php
        $x-&gt;routes(fn($r) =&gt; $r-&gt;get('/warenkorb', fn() =&gt; …));
        $x-&gt;nav('/admin/shop', 'Shop', 'shop', 'shop.edit');
        $x-&gt;migration(1, fn($db) =&gt; $db-&gt;query('CREATE TABLE IF NOT EXISTS …'));
        $x-&gt;command('shop:sync', 'Artikel abgleichen', fn(array $args) =&gt; 0);
        $x-&gt;proxy('lieferant', ['upstream' =&gt; 'https://api.example.org']);
        $x-&gt;htmlFilter(fn(string $html, array $ctx) =&gt; $html);          // Website-HTML ergänzen (vor dem Seiten-Cache)
        $x-&gt;csp(fn() =&gt; ['frame-src' =&gt; ['https://player.example.org']]);  // CSP je Anfrage ergänzen (nur Hosts)
        $x-&gt;footerLinks(fn() =&gt; [['label' =&gt; 'Cookie-Einstellungen', 'href' =&gt; '#cookie-einstellungen']]);
        // Verwaltung, Mediathek, Betrieb
        $x-&gt;feature('shop', 'Shop', ['shop.edit'], false);                 // Funktion Standard AUS ('features' =&gt; ['shop' =&gt; true])
        $x-&gt;adminAssets(fn(string $view) =&gt; $view === 'media' ? ['css/shop.css', 'js/shop.js'] : []);
        $x-&gt;health(fn() =&gt; ['Shop: Lieferant erreichbar' =&gt; true]);        // true | false | null (Warnung)
        $x-&gt;afterAdminResponse(fn() =&gt; $faellig ? fn() =&gt; arbeite() : null);
        $x-&gt;on('media.deleted', fn(array $m) =&gt; …);                        // media.imported, media.replaced, media.deleted
        $x-&gt;mediaChecks(fn() =&gt; ['ohne_preis' =&gt; ['label' =&gt; 'Ohne Preis', 'icon' =&gt; 'tag', 'where' =&gt; "m.tags LIKE '%,produkt,%'"]]);
        $x-&gt;mediaJson(fn(array $m) =&gt; ['preis' =&gt; 12]);                     // Mediathek-API: ext.shop
        $x-&gt;mediaTypes(['video/webm' =&gt; ['ext' =&gt; 'webm', 'magic' =&gt; "\x1A\x45\xDF\xA3", 'label' =&gt; 'WebM']]);
        $x-&gt;mediaPoster(fn(array $m): ?int =&gt; …);                            // Vorschaubild (Bild-ID) für Videos
        $x-&gt;docs('manual', ['shop' =&gt; ['title' =&gt; 'Shop', 'file' =&gt; __DIR__ . '/docs/manual.php', 'after' =&gt; 'medien']]);
        // Seiten: Seitenbaum, Seiteneinstellungen, Werkzeugleiste der Website
        $x-&gt;pageList(fn(array $p) =&gt; ['badges' =&gt; [['label' =&gt; 'Geprüft', 'tone' =&gt; 'ok']], 'actions' =&gt; [['label' =&gt; 'Prüfen …', 'href' =&gt; '/admin/shop/' . $p['id']]]]);
        $x-&gt;pagePanel(fn(array $p) =&gt; '&lt;section class="adm-card"&gt;…&lt;/section&gt;');
        $x-&gt;toolbar(fn(array $bar) =&gt; ['items' =&gt; [['label' =&gt; 'Shop-Daten', 'icon' =&gt; 'tag', 'data' =&gt; ['shop-open' =&gt; '1']]], 'scripts' =&gt; ['js/bar.js']]);
    },
];</code></pre>
  <p><b>Lebenszyklus:</b> Aktiv ist eine Erweiterung auf Websites, die sie unter <code>'extensions'</code> nennen oder unter Funktionen &amp; Erweiterungen aktivieren (<code>Extensions::enabled()</code>). <b>Aktivieren</b> (<code>Extensions::activate()</code>) setzt den Schalter und startet die Erweiterung sofort: <code>boot</code>, offene <code>migration()</code>-Schritte, einmalig je Website der Manifest-Haken <code>'install' =&gt; fn(Database $db)</code> (Merker <code>ext.{name}.installed</code>); scheitert der Start, bleibt sie aus. Eigene Funktionen mit Standard AUS (z. B. <code>video.tools</code>) werden dabei mit eingeschaltet. <b>Deaktivieren</b> ruft optional <code>'deactivate' =&gt; fn()</code> und startet die Erweiterung ab der nächsten Anfrage nicht mehr – Routen, Menü, Rechte, CSP-Quellen, <code>htmlFilter</code>, Befehle und <code>afterAdminResponse</code> entfallen, Tabellen und Einstellungen bleiben. Cron-Befehle, die im Manifest unter <code>'commands'</code> stehen, beenden sich auf Websites ohne die Erweiterung mit Exit-Code 0 und Hinweis. Weitere Manifest-Angaben für die Seite: <code>author</code>, <code>license</code>, <code>homepage</code> (sonst aus <code>composer.json</code>), <code>risk</code> (Risiko-Text → Bestätigung + Passwort), <code>provides</code> (Liste „bringt mit“), <code>requirements</code> (<code>fn(): ['Bezeichnung' =&gt; true|false|null]</code>, läuft auch ohne Aktivierung – z. B. ffmpeg gefunden?), <code>usage</code> (<code>fn(): ?string</code> für „Wird verwendet von …“; Seiten mit Blöcken der Erweiterung zählt der Core selbst), <code>docs</code> (Titel =&gt; Adresse), <code>required</code> (fester Bestandteil, nicht abschaltbar). Andere Websites prüfen: <code>Extensions::enabledForSite($key, $name)</code>.</p>
  <p>Aktiv ist eine Erweiterung nur auf Websites, die sie unter <code>'extensions'</code> nennen bzw. in der Verwaltung aktivieren. Übersetzungen: <code>lang/{locale}.php</code> und <code>lang/site/{lang}.php</code> im Erweiterungsordner. Öffentliche Dateien: <code>assets/</code> (wird mit <code>pnpm build</code> gebaut) bzw. <code>public/</code> (per <code>extensions:publish</code>) → <code>/extensions/{name}/…</code>, im Code <code>$x-&gt;asset('css/shop.css')</code>. Datenbank-Schritte laufen versioniert je Website (<code>migrate</code>). Übersicht: <code>php bin/console extensions:list</code>.</p>
  <p>Routen für alle HTTP-Methoden (z. B. WebDAV): <code>$r-&gt;any('/dav/{path*}', …)</code>. Schreibt eine Bibliothek die Antwort selbst, gibt der Handler <code>Response::alreadySent()</code> zurück (<code>send()</code> gibt dann nichts mehr aus).</p>

  <p>Website-Schnittstellen: <code>htmlFilter</code> bekommt das fertige HTML und <code>$ctx</code> (<code>page</code>, <code>editing</code>, <code>loggedIn</code>, <code>status</code>) und läuft vor dem Seiten-Cache – nichts Besucherspezifisches einfügen. <code>csp</code> läuft bei jeder Antwort (auch Cache-Treffern); <code>Extensions::cspSources()</code> übernimmt nur <code>https://(*.)host</code> für <code>script-src</code>, <code>connect-src</code>, <code>img-src</code>, <code>frame-src</code>, <code>media-src</code>, <code>style-src</code>, <code>font-src</code> – nie <code>'unsafe-inline'</code>, <code>data:</code> oder <code>*</code>. <code>footerLinks</code> erscheinen über <code>footer_links()</code> in der Rechtliches-Zeile der mitgelieferten Kits. Beispiel: <a href="#consent">Cookie-Einwilligung</a>.</p>

  <h4>Haken für Verwaltung, Mediathek und Betrieb</h4>
  <table class="doc-table">
    <tr><th>Haken</th><th>Wirkung</th></tr>
    <tr><td><code>feature($key, $label, $perms, false)</code></td><td>Funktion ist Standard <b>aus</b>, bis die Konfiguration sie mit <code>'features' =&gt; [$key =&gt; true]</code> oder die Verwaltung sie einschaltet (beim Aktivieren der Erweiterung in der Verwaltung automatisch; Integratoren sehen sie immer).</td></tr>
    <tr><td><code>adminAssets(fn($view))</code></td><td>CSS/JS aus <code>{dir}/assets</code> (gebaut nach <code>/extensions/{name}/</code>) in der Verwaltung laden – je Ansicht (<code>media</code>, <code>pages/…</code>). Nur <code>'self'</code>, die CSP bleibt unverändert; Skripte laufen nach <code>admin.js</code>.</td></tr>
    <tr><td><code>health(fn())</code></td><td>Zeilen für <code>php bin/console health</code>: <code>true</code> ✓, <code>false</code> ✗ (Exit-Code 1), <code>null</code> Warnung.</td></tr>
    <tr><td><code>afterAdminResponse(fn())</code></td><td>Billige Prüfung bei jedem Verwaltungsaufruf; gibt sie einen Callable zurück, läuft er nach <code>fastcgi_finish_request()</code> (wie <code>Sources::maybeRun()</code>) – z. B. wartende Hintergrund-Aufträge starten.</td></tr>
    <tr><td><code>on($event, fn)</code></td><td>Ereignisse des Cores: <code>media.imported</code> ($m), <code>media.replaced</code> ($neu, $alt), <code>media.deleted</code> ($m, vor dem Löschen). Fehler einer Erweiterung brechen den Ablauf nicht ab.</td></tr>
    <tr><td><code>mediaChecks(fn())</code></td><td>Filter unter „Prüfen“ in der Mediathek: <code>label</code>, <code>icon</code>, <code>where</code> (SQL-Bedingung auf Alias <code>m</code>, nur feste Werte), <code>params</code>, <code>kind</code>. API-Parameter <code>check={schlüssel}</code>, Anzahl in <code>counts.x_{schlüssel}</code>, Liste in <code>ext_checks</code>. Im Kontext eines geteilten Pools leer zurückgeben, wenn die Bedingung eigene Tabellen nutzt.</td></tr>
    <tr><td><code>mediaJson(fn($m))</code></td><td>Zusatzangaben je Datei in der Mediathek-API unter <code>ext.{name}</code> (für jede Datei der Liste – billig halten, je Anfrage zwischenspeichern).</td></tr>
    <tr><td><code>mediaTypes([...])</code></td><td>Weitere Video-/Audio-Typen für <code>Media::import</code> (Endung fest, Dateianfang <code>magic</code> wird geprüft).</td></tr>
    <tr><td><code>mediaPoster(fn($m))</code></td><td>Vorschaubild für Videos ohne eigenes Poster: <code>Media::posterFor($m)</code> in den Video-Blöcken der Kits (<code>partials/video-embed.php</code>) und in <code>MediaTracks::player</code>.</td></tr>
    <tr><td><code>docs('manual'|'technical', [...])</code></td><td>Kapitel im Handbuch (Format wie <code>themes/{name}/docs/manual.php</code> → <code>chapters</code>) bzw. im Entwicklerhandbuch (<code>title</code>, <code>file</code>, <code>part</code> 0–4, <code>after</code>).</td></tr>
    <tr id="dashboard-hook"><td><code>dashboard(fn($user))</code></td><td>Beiträge zur <b>Übersicht</b> (<code>/admin</code>, <code>Core\Dashboard\Dashboard</code>): <code>tiles</code> = weitere Kacheln unter „Kennzahlen“ (<code>label</code>, <code>value</code>, optional <code>text</code>, <code>level</code> 0–100 für die Skala, <code>trend</code> = <code>['now' =&gt; …, 'prev' =&gt; …, 'label' =&gt; …]</code>, <code>href</code>, <code>hot</code>); <code>cards</code> = eigene Karten (<code>title</code>, <code>icon</code>, <code>size</code> <code>third|half|two-thirds|full</code>, <code>render</code> = <code>fn(): string</code> mit fertigem, selbst escaptem HTML, <code>lazy</code> = nachladen über <code>/admin/api/dashboard/x-{erweiterung}-{schlüssel}</code>, <code>ttl</code> = Sekunden Zwischenspeicher je Website, Standard 300). Rechte prüft die Erweiterung mit <code>can()</code>; leeres Array = nichts. Die Redaktion kann Erweiterungskarten wie alle anderen verschieben, zuklappen und ausblenden. Gedacht z. B. für eine Matomo-Erweiterung (Besuche, Seitenaufrufe) – der Core selbst zählt keine Besucher.</td></tr>
    <tr id="page-hooks"><td><code>pageList(fn($page))</code></td><td><b>Seitenbaum</b> (Verwaltung → Seiten): <code>badges</code> = kurze Hinweise in der Spalte „Status“ (<code>label</code>, optional <code>title</code> als Tooltip, <code>tone</code> <code>ok|warn|info|muted</code>), <code>actions</code> = Einträge im Kontextmenü (<code>label</code>, <code>href</code> – nur Adressen dieser Installation, beginnend mit <code>/</code>). Läuft für jede Seite des Baums: Daten einmal vorab laden, Rechte mit <code>can()</code> prüfen.</td></tr>
    <tr><td><code>pagePanel(fn($page))</code></td><td>Karte in der Seitenleiste der <b>Seiteneinstellungen</b> (<code>/admin/pages/{id}</code>, unter dem KI-Assistenten): fertiges, selbst escaptes HTML, z. B. <code>&lt;section class="adm-card"&gt;</code>. Leerer Text = nichts.</td></tr>
    <tr><td><code>toolbar(fn($bar))</code></td><td><b>Werkzeugleiste der Website</b> (nur angemeldet, <code>Core\Toolbar</code>): <code>items</code> = Einträge im Menü „⋯“ (<code>label</code>, <code>hint</code>, <code>icon</code>, <code>href</code> oder <code>data</code> → <code>data-…</code>-Attribute an einem Button, den ein eigenes Skript in der Schatten-Wurzel der Leiste abfängt), <code>scripts</code> = Skripte aus <code>{dir}/assets</code> (nach der Leiste im Dokument, nur <code>'self'</code>; <code>.mjs</code> als Modul), <code>publishNote</code> = Zusatz im Dialog „Änderungen jetzt veröffentlichen?“. <code>$bar</code> = <code>Toolbar::context()</code> (<code>kind</code>, <code>mode</code>, <code>page</code>, <code>editing</code> …). Eigene Oberflächen auf der Website gehören in ein eigenes Shadow DOM (Kit-CSS wirkt sonst hinein).</td></tr>
    <tr><td><code>SiteController::previewHtml($page, true)</code></td><td>Kein Haken, aber für Erweiterungen gedacht: HTML einer Seite mit dem <b>aktuellen Entwurf</b> im Layout des Kits (ohne Werkzeugleiste, ohne Seiten-Cache, <code>noindex</code>). Header setzt der Aufrufer, z. B. <code>SiteController::csp()</code> und <code>Cache-Control: no-store</code>. Beispiel: Erweiterung „Entwurf teilen &amp; freigeben“ (<code>composer require klxm/studio-freigabe</code>, Quelle <a href="https://github.com/KLXM/studio-freigabe" rel="noopener">github.com/KLXM/studio-freigabe</a>) – nutzt <code>pageList</code>, <code>pagePanel</code>, <code>toolbar</code> und diese Vorschau; ist sie aktiv, bringt sie ein eigenes Kapitel in diese Dokumentation mit.</td></tr>
  </table>
  <pre><code>$x-&gt;dashboard(fn(array $user) =&gt; can('stats.view') ? [
    'tiles' =&gt; [['key' =&gt; 'visits', 'label' =&gt; 'Besuche', 'value' =&gt; number_format($n, 0, ',', '.'), 'text' =&gt; 'letzte 30 Tage',
                 'trend' =&gt; ['now' =&gt; $n, 'prev' =&gt; $vorher, 'label' =&gt; 'Besuche'], 'href' =&gt; '/admin/statistik']],
    'cards' =&gt; ['besucher' =&gt; ['title' =&gt; 'Besucher', 'icon' =&gt; 'chart-line-up', 'size' =&gt; 'half', 'lazy' =&gt; true, 'ttl' =&gt; 600,
                 'render' =&gt; fn() =&gt; '&lt;p&gt;' . e($text) . '&lt;/p&gt;']],
] : []);</code></pre>
  <p><b>Mediathek im Browser:</b> <code>window.CMSMedia.extend({ name, loaded(finder, data), badge(m, finder), panel(finder, m, ui), multi(finder, items, el, ui), summary(finder, el, ui), menu(finder, ids, one), quickLook(finder, m, dialog) })</code> – Haken für Liste, Vorschau im Raster, Informationen rechts (eine Datei, Mehrfachauswahl, ohne Auswahl), Kontextmenü und Quick Look. <code>CMSMedia.ui</code> liefert <code>t</code>, <code>ico</code>, <code>ask</code>, <code>esc</code>, <code>http</code> (CSRF, Pool), <code>toast</code>, <code>box</code>, <code>inBox</code>, <code>base</code>. Erweiterungs-Skripte laden nach <code>admin.js</code>; <code>extend()</code> zeichnet bereits geöffnete Mediatheken neu.</p>
  <p><b>Composer:</b> Paket-Typ <code>mycms-extension</code>; der geplante Name <code>klxm-studio-extension</code> wird schon erkannt (Einstieg <code>extra.klxm-studio.entry</code> bzw. <code>extra.mycms.entry</code>). <code>extensions:publish</code> kopiert <code>public/</code> – fehlt er und ist noch nichts veröffentlicht, <code>assets/</code> unverändert. Übersetzungen prüfen: <code>php bin/console i18n:missing en --extension={name}</code>. Beispiel: <a href="#video-tools">Video-Werkzeuge</a>.</p>

  <h3 id="dav">CalDAV/CardDAV (Erweiterung <code>dav</code>)</h3>
  <p>Mit sabre/dav 4.7: Kalender-Tabellen als CalDAV-Kalender, beliebige Tabellen als CardDAV-Adressbuch. Aktivieren mit <code>'extensions' =&gt; ['dav']</code>; Funktion <code>dav</code>, Recht <code>dav.use</code> (Administration hat es; anderen Rollen im Rollen-Editor geben). Verwaltung → „Kalender &amp; Kontakte in Apps“: eigene <b>App-Passwörter</b> (Hash, einmalig sichtbar, „Lesen und ändern“ oder „Nur lesen“, widerrufbar) und – mit <code>data.schema</code> – Einstellungen je Tabelle (bereitstellen, Status neuer Einträge, Verhalten beim Löschen, vCard-Zuordnung).</p>
  <ul>
    <li><b>Adressen:</b> <code><?= e(absolute_url('/dav/')) ?></code> (Discovery: <code>/.well-known/caldav</code>, <code>/.well-known/carddav</code>). Benutzername = E-Mail, Passwort = App-Passwort (HTTP Basic, nur über HTTPS betreiben; 20 Fehlversuche/15 min je IP).</li>
    <li><b>Rechte:</b> sichtbar sind nur Tabellen mit <code>data.edit</code> für die Rolle (Tabellen-Einschränkung der Rolle gilt); schreibgeschützt bei „Nur lesen“. Neue Einträge erhalten den je Tabelle eingestellten Status; ohne <code>data.publish</code> werden sie Entwurf, wenn die Tabelle den Freigabe-Workflow nutzt. Fremde Einträge geteilter Tabellen sind schreibgeschützt. Löschen in der App: Standard <b>Entwurf</b> (Eintrag bleibt im CMS, verschwindet aus der App, erscheint wieder, sobald er veröffentlicht wird); „endgültig löschen“ nur mit <code>data.delete</code>.</li>
    <li><b>CalDAV:</b> VEVENT ↔ Eintrag der Standardsprache (Entwürfe sichtbar als STATUS:TENTATIVE): SUMMARY, DTSTART/DTEND/ganztägig, RRULE/EXDATE, DESCRIPTION (Text; unveränderter Text behält die Formatierung im CMS), LOCATION/GEO, CATEGORIES, URL (nur lesen). Tabelle <code>dav_objects</code> (Tabelle, Eintrag, URI, UID, Rohdaten) hält alles Übrige (Erinnerungen, Teilnehmer, X-Eigenschaften) – ETag = Hash der Ausgabe, ändert sich mit jeder Änderung im CMS.</li>
    <li><b>CardDAV:</b> vCard 3.0; FN bzw. N (Nachname/Vorname), ORG, TITLE, ADR, URL, NOTE, BDAY, PHOTO (Bild → eingebettetes JPEG), CATEGORIES; EMAIL/TEL aus allen Feldern dieses Typs (Feldname „mobil/handy“ → CELL, „fax“ → FAX, „privat“ → HOME). <b>Alle übrigen Felder als <code>X-MYCMS-{FELD}</code></b> (z. B. <code>X-MYCMS-FACHGEBIET</code>, Ja/Nein als 1/0, Mehrfachauswahl kommagetrennt) – in beide Richtungen.</li>
    <li><b>Einrichten:</b> Apple (macOS/iOS): Einstellungen → Kalender/Kontakte → Accounts → Andere → CalDAV-/CardDAV-Account, „Manuell“, Server = Domain. Thunderbird: Kalender „Im Netzwerk“ bzw. „CardDAV-Adressbuch“ mit der Adresse oben. DAVx⁵: „Mit URL und Benutzername anmelden“.</li>
    <li><b>Grenzen:</b> Kalender/Adressbücher werden nur im CMS angelegt, umbenannt oder gelöscht (MKCALENDAR → 403, Umbenennen aus der App wird ignoriert). Nur VEVENT (keine Aufgaben). Geänderte Einzeltermine (RECURRENCE-ID) bleiben nur in den Rohdaten (Apps zeigen sie, CMS-Kalender nicht). Regeln außerhalb DAILY–YEARLY bleiben nur in den Rohdaten. Ganztägig ohne Feld „ganztägig“ wird 00:00 Uhr. Mehr E-Mail-Adressen/Telefonnummern als passende Felder, Fotos aus Apps und Ländernamen ohne Feld werden nicht übernommen. Übersetzungen von Einträgen werden nicht abgeglichen (nur Standardsprache). Keine sync-collection (Clients nutzen ctag/ETag).</li>
  </ul>
  <p>Kern-Änderungen dafür: <code>Router::any()</code>, <code>Response::alreadySent()</code>, Staging-Passwortschutz überspringt <code>/dav</code> und <code>/.well-known</code>. Details: <code>extensions/dav/README.md</code>. CLI: <code>php bin/console dav:password &lt;e-mail&gt; [name] [read|write]</code>.</p>
