<?php /** Entwicklerhandbuch · Geteilte Datentabellen */ ?>
  <p>Eine Datentabelle für mehrere Websites einer Installation (z. B. Verband + Vereine). Speicher: <code>storage/shared/{key}/share.json</code> (Bezeichnung, <code>owner</code>, <code>members</code>, <code>members_see_members</code>, <code>auto</code> = automatische Übernahme {enabled, sites, where}, <code>sites_info</code> = Name/Adresse/Detailseiten je Website) und <code>share.sqlite</code> mit Registereintrag (<code>data_tables</code>), der echten Tabelle <code>data_{key}</code> (zusätzlich <code>origin_site</code>, <code>suggest</code>), Verknüpfungstabellen und <code>share_picks</code> (<code>pick_site, pick_entry, pick_state</code> = visible | featured | hidden | rejected, <code>pick_at, pick_by</code>). Der Schlüssel ist der Kurzname; Kollisionen mit lokalen Tabellen (Kurzname, URL-Basis) der beteiligten Websites werden beim Anlegen und beim Hinzufügen von Mitgliedern abgewiesen.</p>
  <ul class="doc-list">
    <li><b>Datenbank-Kontext:</b> <code>Tables::db($t)</code> / <code>Tables::conn($t)</code> liefern Website- bzw. Share-Datenbank; <code>Entries</code> und <code>Tables::sync()</code> arbeiten ausschließlich darüber. Geteilte Tabellen erscheinen in <code>Tables::all()/content()</code> der Mitglieder mit <code>$t['shared']</code> (key, owner, members, members_see_members) und einer stabilen ID ≥ 100 000 000 (<code>Shared::tableId()</code>). Eingangs-Tabellen sind nie teilbar.</li>
    <li><b>Rechte:</b> Felder ändert nur die Eigentümer-Website (<code>data.schema</code>) oder ein Integrator (<code>Shared::canSchema()</code>); jede Website ändert/löscht nur Einträge mit <code>origin_site</code> = eigene Website (zentral in <code>Entries::save/delete/setStatus/reorder</code>, Verwaltung und API antworten mit 403). Anlegen und Mitglieder: Recht <code>data.shared.manage</code> (Funktion <code>data.shared</code>, in den Presets <code>content</code>/<code>minimal</code> aus). Übernehmen/Ablehnen/Hervorheben/Ausblenden: <code>data.publish</code>.</li>
    <li><b>Quellen:</b> <code>Entries::query($t, ['source' =&gt; …])</code> mit <code>site</code> (Standard: eigene + Einstellungen der Website <code>settings['shared.{key}']</code> = owner, members off|all|selected, sites, where, link_origin, detail_page_id), <code>own</code>, <code>owner</code>, <code>members</code>, <code>own_owner</code>, <code>all</code>, <code>featured</code>; zusätzlich <code>suggested</code>, <code>pick</code>, <code>origin</code>, <code>featured_first</code>. Fremde Einträge immer nur veröffentlicht; ausgeblendete/abgelehnte nie in <code>site</code>. Eigentümer-Website: übernommene Vorschläge (<code>visible|featured</code>) + automatische Übernahme nach <code>auto</code>. Zeilen tragen <code>origin_site</code>, <code>suggest</code>, <code>_pick</code>.</li>
    <li><b>Ausgabe:</b> Detailseiten fremder Einträge unter der eigenen URL-Basis (<code>bySlug(…, 'site')</code>) mit Canonical auf die Ursprungs-Website (<code>Entries::absUrl()</code>, <code>Shared::originUrl()</code> – nur wenn diese Detailseiten hat); <code>Entries::href()</code> verlinkt auf Wunsch direkt dorthin. JSON-LD: <code>organizer</code>/<code>publisher</code>/<code>author</code> = Organisation der Ursprungs-Website (<code>StructuredData::orgOf()</code>). Sitemap nur eigene Einträge, iCal/CalDAV mit den gewählten Quellen (UID mit Host der Eigentümer-Website), Feld <code>_origin</code> = Name der Ursprungs-Website. Jede Änderung leert die Seiten-Caches aller Beteiligten (<code>PageCache::clearSite()</code>).</li>
    <li><b>Medien:</b> Bild-/Dateifelder speichern IDs im automatisch angelegten Pool <code>data-{key}</code> (alle Beteiligten nutzen ihn). Beim Speichern wandert eine eigene Datei per <code>Media::shareToPool()</code> in den Pool, Dateien anderer Pools werden kopiert; beim Lesen liefert <code>MediaPools::mirror()</code> die Verweis-ID der jeweiligen Website.</li>
    <li><b>Verknüpfungen</b> nur zu geteilten Tabellen derselben Eigentümer-Website. Ein gemeinsames Schema, keine Zusatzfelder je Website; Detailseiten-Vorlage je Website.</li>
    <li><b>Kommandozeile:</b> <code>data:share &lt;handle&gt; --members=a,b [--see-members] [--merge] --site=&lt;eigentümer&gt;</code> (lokale Tabelle samt Einträgen verschieben; IDs bleiben, Bilder in den Pool, lokale Tabelle bleibt als <code>zz_unshared_…</code>; <code>--merge</code> führt in eine bestehende geteilte Tabelle zusammen und schreibt Verweise lokaler Tabellen um), <code>data:unshare &lt;handle&gt; [--all-entries]</code>, <code>shared:list</code>, <code>shared:backup [key|--all]</code>, <code>shared:restore &lt;datei&gt; --force</code>. <code>migrate --all</code> legt Share-Datenbanken an bzw. gleicht Spalten additiv ab, <code>health --all</code> prüft sie. Beim Deploy liegt <code>storage/shared</code> in <code>shared/</code>.</li>
    <li><b>API/MCP:</b> <code>GET /data/{t}?source=…</code>, <code>/data/{t}/occurrences?source=…</code>, <code>GET /data/{t}/suggestions?state=pending</code>, <code>POST /data/{t}/picks</code> {ids, state}; MCP <code>list_entries</code>/<code>list_occurrences</code> mit <code>source</code>, <code>list_suggestions</code>, <code>set_pick</code>. Schreiben nur eigene Einträge (<code>suggest</code> setzt „vorschlagen“).</li>
  </ul>

