<?php /** Entwicklerhandbuch · Glossar (Core\Glossary) */ ?>
  <p class="lead">Fachbegriffe als gewöhnliche Datentabelle; der Kern markiert das erste Vorkommen auf jeder Seite im fertigen HTML (vor dem Seiten-Cache) und liefert Übersicht, Detailseiten, JSON-LD und Suchindex. Funktion <code>glossary</code> (Standard <b>aus</b>, setzt <code>data</code> voraus), Verwaltung → <b>Daten → Glossar → Prüfen &amp; Einstellungen</b> bzw. <b>Einstellungen → Glossar</b> (Einstellungsseite der Tabelle, <code>Core\AdminPages</code>; Recht <code>data.edit</code> auf die Tabelle, Einrichten/Einstellungen <code>data.schema</code>).</p>
  <table class="doc-table">
    <tr><th>Baustein</th><th>Ort</th></tr>
    <tr><td>Daten</td><td>Tabelle <code>glossar</code>: <code>begriff</code>*, <code>varianten</code> (Zeilen bzw. Komma/Semikolon), <code>kurz</code>* (Klartext ≤ 240), <code>erklaerung</code> (Rich Text), <code>kategorie</code>, <code>link</code> (url), Status. Route <code>glossar</code>, Detailvorlage <code>_vorlage-glossar</code> (Block <code>glossary</code>, Ansicht <code>term</code>), schema.org-Typ „keiner“ (der Block liefert <code>DefinedTerm</code> bzw. <code>DefinedTermSet</code>).</td></tr>
    <tr><td>Quick-Glossar</td><td>Werkzeug auf der Website – beim Bearbeiten und mit <code>'view' =&gt; true</code> auch beim Ansehen (dort jeder Text markierbar, schwebender Knopf <code>chip</code> „Als Glossar-Begriff“, kein Einfügen; Daten <code>editUrl</code> für den Wechsel in den Bearbeiten-Modus) (<code>Core\Glossary\QuickTool</code>, angemeldet wie eine Erweiterung über <code>Core\FrontendTools</code>, Modul <code>resources/js/quick-glossary.mjs</code>). Endpunkte <code>GET /admin/api/glossar/suche?q=&amp;lang=</code>, <code>POST /admin/api/glossar/begriff</code> (<code>term, short, variants, long, publish, lang</code> → Entwurf ohne <code>data.publish</code>, 409 bei Doppel), <code>POST /admin/api/glossar/seite</code> (<code>html, lang, path, self</code> → Treffer des Annotators mit <code>match</code>). Alle: Funktion an, Tabelle da, <code>data.edit</code> auf <code>glossar</code>, CSRF bei POST. Siehe <a href="#erweiterungen">Erweiterungen: Seiten, Werkzeuge &amp; Ereignisse</a>.</td></tr>
    <tr><td>Code</td><td><code>Core\Glossary\Glossary</code> (Einstellungen, Begriffe, <code>page()</code>, <code>install()</code>, Prüfungen, Vorkommen, CSV, KI-Vorschlag), <code>…\Annotator</code> (Markierung ohne DOM-Bibliothek), <code>…\Console</code>, <code>…\SelfTest</code>, <code>Admin\GlossaryController</code>, Block <code>app/Blocks/glossary.php</code></td></tr>
    <tr><td>Website</td><td><code>resources/css/glossary.css</code> (Begriffe/Fenster, ≈ 1,4 KB gz), <code>glossary-list.css</code> (Block), <code>resources/js/glossary.js</code> (≈ 1,2 KB gz), <code>glossary-live.mjs</code> (nur mit dynamischen Bereichen), <code>GET /_glossary.json?lang=</code> (veröffentlichte Begriffe, 5 min öffentlich cachebar)</td></tr>
    <tr><td>Sprachen</td><td>Begriffe sind Einträge je Sprache (Übersetzung über <code>Entries::translate</code>, gleiche <code>translation_group</code>). <code>Glossary::terms()</code> liefert die Begriffe der aktuellen Sprache, <code>page()</code> übergibt <code>lang</code> an den Annotator (Wortendungen), <code>/_glossary.json</code> enthält <code>lang</code>. Übersicht: Übersetzung der Seite aus <code>page_id</code> – ohne (veröffentlichte) Übersetzung kein Link. Detailseiten <code>/{sprache}/glossar/{slug}</code>; JSON-LD mit <code>inLanguage</code>. <code>checks()</code> und <code>occurrences()</code> je Sprache; CSV-Spalte <code>lang</code>.</td></tr>
    <tr><td>Einstellungen</td><td><code>sys.glossary</code>: <code>mode</code> (page|section|off), <code>headings</code> (h1…hN nicht markieren, Standard 3), <code>exclude</code> (Pfade, <code>/x/*</code>), <code>live</code> (Selektoren), <code>page_id</code> (Übersicht)</td></tr>
  </table>

  <h3>Markieren</h3>
  <ul>
    <li><b>Wann:</b> <code>SiteController::render()</code> nach Erweiterungs-Filtern und Redaktionsnotizen, vor <code>PageCache::put</code> – also einmal je gecachter Seite. Seiten außerhalb von <code>render()</code> (eigene Routen von Erweiterungen) über <code>respond()</code>; <code>Glossary::$done</code> verhindert doppelte Arbeit, ein Cache-Treffer setzt es. Nie im Bearbeiten-Modus, nicht für Status ≠ 200, nicht auf der Suchseite. Angemeldet mit <code>data.edit</code>: auch Entwürfe (Hinweis „Entwurf“, ohne Cache).</li>
    <li><b>Wo:</b> nur <code>&lt;body&gt;</code>, gibt es ein <code>&lt;main&gt;</code>, nur darin. Rohtext-Bereiche (script, style, pre, code, textarea, template, svg, select, iframe, Kommentare) bleiben unberührt; übersprungen werden a, button, label, summary, legend, kbd, samp, var, abbr, dfn, nav, time, Überschriften bis <code>headings</code>, header/footer außerhalb von main/article/section/aside, <code>[hidden]</code>, <code>[inert]</code>, <code>[contenteditable]</code>, <code>[aria-hidden=true]</code>, interaktive Rollen, Klassen <code>sr-only</code>, <code>visually-hidden</code>, <code>cms-note</code> … und alles unter <code>[data-glossary="off"]</code> (Abschnitts-Option <code>noGlossary</code> setzt das am Abschnitt, der Block „Glossar“ an der Übersicht).</li>
    <li><b>Treffer:</b> ein regulärer Ausdruck für alle Varianten, längste zuerst, Begriffs-ID als <code>(*MARK)</code>. Wortgrenzen per Unicode (<code>\p{L}\p{N}</code>), nicht in Adressen/Zuweisungen (<code>. @ / : = &amp;</code> davor bzw. <code>.x</code> danach). Abkürzungen (≥ 2 Großbuchstaben in einem Wort, oder klein→groß) genau, sonst <code>(?i)</code>; Endungen nach dem letzten Wort: Abkürzung <code>s</code>, Wort ab 4 Zeichen <code>e|en|n|s|es|er|ern</code> (Englisch, Option <code>lang</code>: <code>s|es</code>, Konsonant + <code>y</code> → <code>ies</code>). <code>"…"</code> = genau, ohne Endung. Leerraum in Varianten passt auch auf <code>&amp;nbsp;</code>. Je Begriff das erste Vorkommen je Seite bzw. je <code>section</code>/<code>article</code>; schon vorhandene Markierungen (<code>.gl[data-gl]</code>) zählen mit – zweimal anwenden ändert nichts.</li>
    <li><b>Laufzeit:</b> ≈ 20 ms für 580 KB HTML und 316 Begriffe (<code>glossary:selftest --bench</code>); danach liefert der Seiten-Cache.</li>
    <li><b>Dynamische Bereiche:</b> Elemente mit <code>data-glossary="live"</code> oder den Selektoren aus <code>live</code> beobachtet <code>glossary-live.mjs</code> (MutationObserver); beim ersten Inhalt lädt es <code>/_glossary.json</code> und markiert mit denselben Regeln (je Bereich das erste Vorkommen, nur DOM-Methoden). So bekommen z. B. die Ergebnisse von KLXM Check Erklärungen, ohne die Erweiterung zu ändern.</li>
  </ul>

  <h3>Markup und Barrierefreiheit</h3>
  <pre><code>&lt;span class="gl" data-gl="spf"&gt;&lt;button type="button" class="gl-term" popovertarget="gl-1" aria-expanded="false" aria-controls="gl-1"&gt;SPF&lt;/button&gt;
&lt;span class="gl-pop" id="gl-1" popover&gt;&lt;span class="gl-pop__head"&gt;&lt;span class="gl-pop__t"&gt;SPF&lt;/span&gt;&lt;button … popovertargetaction="hide" aria-label="Erklärung schließen"&gt;×&lt;/button&gt;&lt;/span&gt;
&lt;span class="gl-pop__d"&gt;…&lt;/span&gt;&lt;a class="gl-pop__more" href="/glossar/spf"&gt;Mehr im Glossar →&lt;/a&gt;&lt;/span&gt;&lt;/span&gt;</code></pre>
  <ul>
    <li><b>Muster „Toggletip“/Disclosure</b> statt <code>role="tooltip"</code>: Das Fenster enthält einen Link, Tooltips dürfen keine bedienbaren Inhalte haben und erscheinen nur bei Hover/Fokus. Der Begriff ist eine Schaltfläche mit <code>aria-expanded</code>/<code>aria-controls</code>; die Erklärung folgt im DOM direkt danach (Screenreader lesen sie nach dem Aufklappen als Nächstes). Kein <code>aria-describedby</code> – sonst würde die Erklärung bei jedem Fokus zusätzlich vorgelesen. Geschlossene Fenster sind ausgeblendet und stören das normale Lesen nicht.</li>
    <li><b>Bedienung:</b> Enter/Leertaste öffnen und schließen, Tab führt ins Fenster (Schließen, Link), Esc und Klick daneben schließen (Popover-API, Fokus zurück zum Begriff). Ohne Popover-API übernimmt <code>glossary.js</code> dasselbe (Klasse <code>is-open</code>). Ohne JavaScript öffnet das Fenster in aktuellen Browsern trotzdem (deklaratives <code>popovertarget</code>).</li>
    <li><b>Darstellung:</b> gepunktete Unterstreichung, Schrift und Farbe des Textes – kein Verschieben (CLS 0). Fenster in der obersten Ebene, am Begriff ausgerichtet (unten oder darüber), auf schmalen Bildschirmen als Blatt unten (der Begriff bleibt sichtbar). Animation nur ohne „Bewegung reduzieren“; <code>forced-colors</code> beachtet. Druck: Erklärung in Klammern hinter dem Begriff.</li>
    <li><b>CSP:</b> nur externe Dateien, kein Inline-Code; Positionen per CSSOM.</li>
  </ul>

  <h3>Kits</h3>
  <p>Ohne Anpassung: Akzent aus den Link-Farben der Kern-Kits (<code>--b-link</code>, <code>--m-link</code> …), Fläche und Text des Fensters aus der Textfarbe abgeleitet (hell/dunkel automatisch, relative Farbsyntax mit Rückfall <code>Canvas</code>). Variablen: <code>--gl-accent</code>, <code>--gl-line</code>, <code>--gl-bg</code>, <code>--gl-text</code>, <code>--gl-border</code>, <code>--gl-radius</code>, <code>--gl-shadow</code>, <code>--gl-width</code>, <code>--gl-font</code>, <code>--gl-pop-accent</code>. Ergänzungen in <code>kits/{kit}/assets/css/glossary.css</code> (wird nach dem Kern geladen); den Block überschreibt <code>kits/{kit}/blocks/glossary.php</code>.</p>

  <h3>Suche, KI, Schnittstellen</h3>
  <ul>
    <li>Veröffentlichte Begriffe haben Detailseiten und landen damit automatisch im Suchindex (<code>TableSearch</code>: Begriff hoch, Varianten/Erklärungen normal) – und so auch im Besucher-Chat, der aus dem Index antwortet.</li>
    <li>„Vorkommen“ zählt in den Texten von <code>Search\Documents::build()</code> (Seiten und Einträge anderer Tabellen), 10 Minuten zwischengespeichert (<code>storage/…/cache/glossary-occurrences.json</code>).</li>
    <li>KI (optional, Funktion <code>ai</code>): „Von der KI vorschlagen“ ruft <code>Assist::call('text', …)</code> mit festem Auftrag (≤ 220 Zeichen, Sie-Form, sachlich) – Ergebnis immer als Entwurf.</li>
    <li>API/MCP: wie jede Datentabelle (<code>/api/v1/data/glossar</code>).</li>
  </ul>

  <h3 id="glossar-geteilt">Geteiltes Glossar (mehrere Websites einer Installation)</h3>
  <p><code>Core\Glossary\Sharing</code> baut auf den <a href="#geteilt">geteilten Datentabellen</a> auf – kein eigener Mechanismus: Schlüssel = Kurzname <code>glossar</code>, Speicher <code>storage/shared/glossar/</code>, Herkunft je Begriff <code>origin_site</code>, Ausblenden je Website über <code>share_picks</code> (<code>hidden</code>).</p>
  <ul class="doc-list">
    <li><b>Teilen</b> (<code>share()</code>, Eigentümer): <code>Shared::shareLocal('glossar')</code> – IDs bleiben, <code>entry:glossar:{id}</code> wirkt weiter; dazu <code>members_see_members</code> und automatische Übernahme ohne Regeln (alle sehen alles) sowie Einladungen (<code>share.json</code> → <code>invited</code>).</li>
    <li><b>Beitreten</b> (<code>plan()</code>, <code>join($choices)</code>, nur eingeladene Website): Doppel = gleiche Vergleichsform (<code>Sharing::norm()</code>: klein, ohne Akzente/Umlaute, ß → ss, ohne Leer-/Satzzeichen) von Begriff oder Variante, je Sprache, gegen die veröffentlichten Begriffe der übrigen Beteiligten. Je Doppel <code>existing</code> (nicht übernehmen; <code>shareLocal(…, $skip)</code> bildet die alte ID auf den vorhandenen Begriff ab), <code>mine</code> (übernehmen, den anderen per Pick ausblenden) oder <code>both</code>. Übernahme mit <code>shareLocal(…, merge: true)</code> als Mitglied (neue IDs, Slug-Kollisionen → <code>-2</code>, im Protokoll); <code>rewriteRefs()</code> stellt <code>entry:glossar:{alt}</code> in <code>pages.content_draft/content_published</code>, <code>revisions.blocks_json</code> und den Textfeldern der eigenen Begriffe um. Danach <code>shared.glossar</code> = owner an, members „all“, und <code>install()</code> (Detailvorlage/Übersicht, falls fehlend).</li>
    <li><b>Lesen:</b> unverändert über <code>Glossary::terms()</code> → <code>Entries::query(…, source „site“)</code>: eigene Begriffe (auch Entwürfe) + veröffentlichte der übrigen, ohne ausgeblendete. Damit lesen Markierung (<code>page()</code>, Annotator), Block „Glossar“ (A–Z, Begriff), <code>/_glossary.json</code>, Quick-Glossar (Suche, „Auf dieser Seite“, Doppelprüfung jetzt mit <code>Sharing::norm()</code>), Prüfungen und Linkauswahl das gemeinsame Glossar. <code>term()</code> liefert zusätzlich <code>foreign</code>/<code>origin</code>; der Quick-Glossar zeigt „von {Website}“. Detailseiten fremder Begriffe: <code>bySlug(…, 'site')</code> unter <code>/glossar/{slug}</code> jeder Website, Canonical nach <code>shared.glossar.canonical</code> (s. u.), <code>link_origin</code> verlinkt direkt zur Ursprungs-Website.</li>
    <li><b>Cache:</b> <code>terms()</code> je Anfrage; markiert wird vor dem Seiten-Cache. Jede Änderung eines Begriffs leert die Seiten-Caches aller Beteiligten (<code>Entries::changed()</code> → <code>Shared::clearCaches()</code>), Ausblenden nur den eigenen. Beitreten/Verlassen leeren alle.</li>
    <li><b>Verlassen</b> (<code>leave()</code>): Mitglied → <code>Shared::leave()</code> (eigene Tabelle mit gleichen IDs, eigene Begriffe + optional Kopien der zuletzt gezeigten fremden; eigene verlassen den Speicher, Sicherung <code>storage/shared/glossar/left/</code>). Eigentümer → <code>Shared::unshare()</code>, erst ohne Mitglieder.</li>
    <li><b>Rechte:</b> Teilen/Einladen/Beitreten/Verlassen: <code>system.manage</code> + <code>Shared::canManage()</code> (<code>data.shared.manage</code> bzw. Integrator); Ausblenden: <code>data.publish</code> auf <code>glossar</code>; Ändern nur eigene Begriffe (<code>Entries::save</code>), wie bei jeder geteilten Tabelle. Routen <code>GET|POST /admin/glossar/teilen</code> (<code>do</code> = share|invite|join|leave), <code>POST /admin/glossar/ausblenden</code>.</li>
  </ul>

  <h3>Kommandozeile</h3>
  <pre><code>php bin/console glossary:install [--publish] [--enable] [--dry-run]   # Tabelle, Detailseiten, Übersicht /glossar
php bin/console glossary:import begriffe.csv [--overwrite] [--dry-run]
php bin/console glossary:export [--out=glossar.csv]
php bin/console glossary:check                                        # doppelte Varianten, Überschneidungen, fehlende Texte
php bin/console glossary:selftest [--bench]                           # Regeln, Ausnahmen, Escaping, Laufzeit, Doppel-Erkennung
php bin/console glossary:share [--invite=neo] --site=default          # teilen (wird Eigentümerin), einladen
php bin/console glossary:invite neo,partner --site=default            # Einladungen setzen
php bin/console glossary:join --plan --site=neo                       # Doppel anzeigen
php bin/console glossary:join [--choice=existing|mine|both] --site=neo # beitreten
php bin/console glossary:leave [--no-copies] --site=neo               # verlassen bzw. (Eigentümer) Teilen beenden
php bin/console glossary:sharetest --sandbox                          # Ende-zu-Ende mit zwei Websites – NUR in einer Wegwerf-Kopie</code></pre>
