<?php /** Entwicklerhandbuch · Kalender, iCal & CalDAV */ ?>
  <p>Funktion <code>calendar</code> (Standard: an; setzt <code>data</code> voraus). Eine Tabelle wird im Baukasten mit <b>„Als Kalender nutzen“</b> zum Kalender; die Zuordnung steht in <code>settings.calendar</code>: <code>enabled</code>, <code>start</code> (date|datetime, Pflicht), <code>end</code> (date|datetime), <code>all_day</code> (bool), <code>recurrence</code>, <code>location</code> (text|textarea|geo), <code>description</code> (text|textarea|richtext), <code>category</code> (select|multiselect), <code>duration</code> (Minuten ohne Ende, Standard 60, 0–10080), <code>feed</code> (öffentlicher iCal-Feed, Standard an). Die Vorlage „Termine“ im Baukasten bringt Beginn, Ende, Ganztägig, Wiederholung und Ort mit.</p>
  <ul>
    <li><b>Wiederholungen</b> (<code>Core\Data\Calendar</code>, rlanvin/php-rrule): <code>Calendar::occurrences($t, $von, $bis, ['status' =&gt; 'published', 'where' =&gt; …, 'limit' =&gt; 500])</code> liefert sortierte Vorkommen <code>{entry, start, end (exklusiv), all_day, recurring}</code> in der Zeitzone der Website (Uhrzeit bleibt über Sommer-/Winterzeit gleich), Ausnahmen (EXDATE) berücksichtigt, Sprache wie <code>Entries::query</code>. Schutz: max. <?= \Core\Data\Calendar::MAX_OCCURRENCES ?> Vorkommen je Aufruf, <?= \Core\Data\Calendar::MAX_PER_ENTRY ?> je Eintrag, COUNT ≤ <?= \Core\Data\Calendar::MAX_COUNT ?>, nur DAILY–YEARLY. <code>Calendar::upcoming($t, 5, 30)</code>, <code>Calendar::when($o)</code>, <code>Calendar::describe($rrule)</code> („Wöchentlich am Montag, bis zum 31.12.2026“).</li>
    <li><b>Gespeichert</b> wird die RRULE ohne Präfix, Ausnahmen in einer zweiten Zeile: <code>FREQ=WEEKLY;BYDAY=MO;UNTIL=20261026T225959Z⏎EXDATE:2026-10-12</code>. UNTIL als Datum wird zum Tagesende (Ortszeit) in UTC normalisiert. Ganztägige Termine: Ende einschließlich (Eingabe), intern exklusiv.</li>
    <li><b>iCal</b> (<code>Core\Data\ICal</code>): <code>GET /kalender/{tabelle}.ics</code> (Feed, nur veröffentlichte Einträge, <code>?lang=en</code>) und <code>GET /kalender/{tabelle}/{slug}.ics</code> (einzelner Termin). RFC 5545 mit VTIMEZONE, stabiler UID <code>{tabelle}-{id}@{host}</code>, DTSTAMP/LAST-MODIFIED, SUMMARY, DESCRIPTION (reiner Text), LOCATION bzw. GEO, CATEGORIES (Auswahltexte), URL (Detailseite), RRULE/EXDATE; Zeilen gefaltet (75 Oktetts), Texte maskiert; Feed mit <code>X-WR-CALNAME</code>, <code>REFRESH-INTERVAL</code>/<code>X-PUBLISHED-TTL</code> PT6H, höchstens 2000 Einträge; ganztägige Termine <code>TRANSP:TRANSPARENT</code>. Abgeschaltet oder ohne Feed (auch für einzelne Termine): 404.</li>
    <li><b>Verwaltung:</b> Einträge einer Kalender-Tabelle mit Umschalter „Liste | Kalender“ (<code>?view=list|calendar</code>, je Tabelle in der Sitzung gemerkt): Monatsraster mit allen Vorkommen (<code>?monat=JJJJ-MM</code>, ohne JavaScript), Status- und Sprachfilter gelten, Entwürfe markiert, Serien öffnen den Serien-Eintrag, Klick auf einen Tag → <code>/new?start=JJJJ-MM-TT</code> (Datum-Uhrzeit-Felder mit 09:00 vorbelegt). Schmale Bildschirme: Terminliste.</li>
    <li><b>Detailseiten:</b> Quelle <code>_when</code> (Datum, Uhrzeit, Wiederholung) im Block „Datensatz-Felder“; Linkfelder können an <code>_ics</code> (Termin als .ics) gebunden werden.</li>
    <li><b>API/MCP:</b> <code>GET /api/v1/data/{tabelle}/occurrences?from=&amp;to=</code> bzw. Tool <code>list_occurrences</code>; <code>GET /data</code> nennt die Kalender-Zuordnung. Ungültige Werte (<code>datetime</code>, <code>recurrence</code>) → 422.</li>
    <li><b>Darstellung:</b> <code>resources/css/calendar.css</code> (nur bei Kalender-Blöcken geladen), Variablen <code>--cal-accent</code>, <code>--cal-accent-ink</code>, <code>--cal-line</code>, <code>--cal-surface</code>, <code>--cal-ev-bg</code>, <code>--cal-today-bg</code> …; Kits liefern <code>assets/css/calendar.css</code> (Import + Variablen), siehe praxis/basis.</li>
  </ul>
  <p><b>Kalender-Apps:</b> Mit der Erweiterung <code>dav</code> werden Kalender-Tabellen als CalDAV-Kalender (und beliebige Tabellen als CardDAV-Adressbuch) mit Apple Kalender, Thunderbird oder DAVx⁵ abgeglichen – siehe <a href="#dav">CalDAV/CardDAV</a>.</p>
