<?php /** Entwicklerhandbuch · KLXM AI: KI-Dienst, Funktionen, Transkription, Prompts */ ?>
  <p class="lead"><b><?= e($aiBrand) ?></b> (Menüname aus <code>'ai_brand'</code>) bündelt alle KI-Funktionen: einen allgemeinen KI-Dienst <code>Core\AI\Ai</code> auf Basis von <b>Symfony AI</b> (Funktion <code>ai</code>, Recht <code>ai.use</code>), die Helfer der Redaktion (<code>Core\AI\Assist</code>), Seiten- und Tabellen-Generator, Untertitel per Transkription und die semantische Suche. Alle Ergebnisse sind Vorschläge; gespeichert wird erst nach menschlicher Prüfung.</p>
  <table class="doc-table">
    <tr><th>Fähigkeit (<code>Ai::CAPS</code>)</th><th>Wofür</th><th>Schalter je Website</th></tr>
    <tr><td><code>text</code></td><td>Texte, Übersetzung, SEO, Teaser, Generatoren, Support-Antworten, Untertitel-Übersetzung</td><td><code>sys.ai_text</code></td></tr>
    <tr><td><code>embed</code></td><td>Embeddings für die semantische Suche und die Wissensdatenbank</td><td><code>sys.ai_embed</code></td></tr>
    <tr><td><code>vision</code></td><td>Alt-Texte, Titel und Tags für Bilder</td><td><code>sys.ai_vision</code></td></tr>
    <tr><td><code>transcribe</code></td><td>Sprache → Text für Untertitel und Transkripte</td><td><code>sys.ai_transcribe</code></td></tr>
  </table>
  <p>Alle Schalter wirken nur, wenn <code>sys.ai_enabled</code> für die Website an ist (Standard: aus). Einrichtung unter <b>Grundeinstellungen → KI</b>: Die Administration schaltet je Website ein und aus, legt ein Tageslimit (<code>sys.ai_daily_cap</code>, Standard 200 Text- und Bildaufrufe, 0 = unbegrenzt), Hinweise an die KI (<code>sys.ai_notes</code>) und ein Glossar (<code>sys.ai_glossary</code>) fest und sieht die Nutzung der letzten 30 Tage (mit Kostenschätzung aus <code>prices</code> und Minuten Audio). <b>Verbindungen</b> (benannte Profile: Art, Adresse, Schlüssel, Region, Zeitlimit, Pfade für whisper.cpp) und <b>Verwendung</b> (je Zweck Verbindung + Modell + optional Ersatz-Verbindung) dürfen nur Agentur/Netzwerk-Administration ändern; sie liegen in <code>storage/ai/config.json</code>. Werte aus <code>config.local.php</code> bzw. <code>config/sites/{key}.php</code> haben Vorrang und sind je Verbindung bzw. Zuordnung gesperrt. Jeder Zweck hat „Verbindung testen“ (Probe an das Modell, CLI: <code>ai:test</code>), jede Verbindung „Verbindung prüfen“ und „Modelle anzeigen“ (siehe unten).</p>
  <table class="doc-table">
    <tr><th>Anbieter (<code>provider</code>)</th><th>Hinweise</th></tr>
    <tr><td><code>ollama</code></td><td>Eigener Server (Standard <code>http://127.0.0.1:11434</code>), nichts verlässt die Infrastruktur. Empfehlung der Oberfläche: <code>gemma3</code> für Text und Bilder, <code>bge-m3</code> (mehrsprachig) oder <code>nomic-embed-text</code> für die Suche. „Thinking“ ist abgeschaltet (<code>think</code>).</td></tr>
    <tr><td><code>mistral</code></td><td>Mistral AI (EU): Standardmodelle <code>mistral-small-latest</code>, <code>mistral-embed</code>, <code>pixtral-12b-latest</code>.</td></tr>
    <tr><td><code>openai</code></td><td>OpenAI mit <code>region =&gt; 'EU'</code> für EU-Datenresidenz; Standard <code>gpt-4o-mini</code>, <code>text-embedding-3-small</code>.</td></tr>
    <tr><td><code>generic</code></td><td>Beliebiger OpenAI-kompatibler Server bzw. EU-Anbieter (z. B. vLLM, LM Studio, IONOS, Scaleway, STACKIT).</td></tr>
    <tr><td><code>fake</code></td><td>Nur für Tests: gekennzeichnete Antworten „[Test-KI] …“.</td></tr>
  </table>
  <h3 id="ki-api">KI-Dienst <code>Core\AI\Ai</code></h3>
  <table class="doc-table">
    <tr><th>Aufruf</th><th>Beschreibung</th></tr>
    <tr><td><code>Ai::enabled(string $cap = 'text'): bool</code></td><td>Funktion <code>ai</code> an, Anbieter + Modell für <code>text</code>|<code>embed</code>|<code>vision</code>|<code>transcribe</code> konfiguriert, KI und Fähigkeit auf der Website eingeschaltet (Grundeinstellungen → KI). Das Recht prüft der Aufrufer: <code>can('ai.use')</code> (Standard: Redaktion, Administration).</td></tr>
    <tr><td><code>Ai::chat(string|array $messages, array $o = []): array</code></td><td>Text erzeugen. <code>$messages</code>: Anweisung oder <code>[['role' =&gt; 'system'|'user'|'assistant', 'content' =&gt; …]]</code>. <code>$o</code>: <code>system</code>, <code>max_tokens</code> (800), <code>temperature</code> (0.3), <code>model</code>, <code>timeout</code> (s, Standard <code>text_timeout</code> = 60), <code>think</code> (Ollama, aus), <code>json</code> (strukturierte Antwort; Ollama <code>format: json</code>). Rückgabe <code>{text, model, provider, tokens_in, tokens_out, ms}</code>.</td></tr>
    <tr><td><code>Ai::complete(string $prompt, string $system = '', array $o = []): string</code></td><td>Kurzform von <code>chat()</code>, liefert nur den Text – z. B. Meta-Beschreibung, Übersetzung, Slug-Vorschlag.</td></tr>
    <tr><td><code>Ai::vision(int|string $image, string $prompt, array $o = []): array</code></td><td>Bild (Medien-ID oder Pfad) + Anweisung → Text, z. B. Alt-Text. Gesendet wird nie das Original: vorhandene WebP-Größe 800–1024 px oder per GD verkleinertes JPEG (max. 1024 px, <code>Ai::imageForVision()</code>). Rückgabe wie <code>chat()</code>.</td></tr>
    <tr><td><code>Ai::embed(array $texts, string $kind = 'document', array $o = []): array</code></td><td>Vektoren (<code>kind</code>: <code>document</code>|<code>query</code>). Für die Suche intern: <code>Ai::embedder()</code> (Schnittstelle <code>Core\AI\Embedder</code>, <code>PlatformEmbedder</code> über den Symfony-<code>Vectorizer</code>, <code>FakeEmbedder</code> für Tests).</td></tr>
    <tr><td><code>Ai::test(string $cap, ?array $cfg = null): array</code></td><td>Verbindung prüfen (unabhängig vom Website-Schalter): <code>{ok, provider, model, endpoint, external, dims|text, ms, error}</code>. Oberfläche: „Verbindung testen“, CLI <code>ai:test</code>.</td></tr>
    <tr><td><code>Ai::config()</code>, <code>Ai::capability($cap)</code>, <code>Ai::usage($days)</code>, <code>Ai::siteSettings()</code></td><td>Wirksame Konfiguration, Angaben je Fähigkeit (<code>external</code> = Daten verlassen den Server), Nutzungszähler, Schalter der Website.</td></tr>
    <tr><td>Fehler</td><td><code>Core\AI\AiException</code> – Meldung ohne Schlüssel/Inhalte, für die Oberfläche geeignet (KI aus, kein Modell, Zeitüberschreitung, Anbieterfehler, Pause nach Fehler). Aufrufer zeigen sie an und bieten den manuellen Weg an.</td></tr>
  </table>
  <h3 id="ki-profile">Verbindungen und Verwendung (<code>Core\AI\Profiles</code>)</h3>
  <p>Format 2 der Konfiguration: beliebig viele <b>Verbindungen</b> (<code>profiles</code>) und je <b>Zweck</b> eine Zuordnung (<code>assign</code>). Zwecke: <code>text</code> (Texte &amp; Redaktion: Assistent, KI-Vorschläge), <code>chat</code> (Besucher-Chat; leer = wie <code>text</code>), <code>embed</code> (Suche, Wissensdatenbank), <code>vision</code> (Alt-Texte), <code>transcribe</code> (Untertitel). Arten: <code>ollama</code>, <code>mistral</code>, <code>openai</code>, <code>anthropic</code> (über die OpenAI-kompatible Schnittstelle, ohne Embeddings), <code>generic</code> (OpenAI-kompatibel, Adresse ohne <code>/v1</code>), <code>whisper_cpp</code> (nur Sprache → Text), <code>fake</code> (Tests). Welche Art welchen Zweck kann: <code>Profiles::SUPPORTS</code>.</p>
  <pre><code>'ai' =&gt; [
    'profiles' =&gt; [
        'ollama_buero' =&gt; ['label' =&gt; 'Ollama Büro', 'type' =&gt; 'ollama', 'base_url' =&gt; 'http://10.0.0.5:11434', 'api_key' =&gt; ''],   // Token optional
        'mistral_eu'   =&gt; ['label' =&gt; 'Mistral EU', 'type' =&gt; 'mistral', 'api_key' =&gt; '…', 'timeout' =&gt; 60],
        'whisper'      =&gt; ['label' =&gt; 'whisper.cpp', 'type' =&gt; 'whisper_cpp', 'model_path' =&gt; 'storage/ai/models/ggml-large-v3-turbo-q5_0.bin', 'threads' =&gt; 4],
    ],
    'assign' =&gt; [
        'text'   =&gt; ['profile' =&gt; 'ollama_buero', 'model' =&gt; 'gemma3', 'fallback' =&gt; 'mistral_eu', 'fallback_model' =&gt; 'mistral-small-latest'],
        'chat'   =&gt; ['profile' =&gt; 'mistral_eu', 'model' =&gt; 'mistral-small-latest'],
        'embed'  =&gt; ['profile' =&gt; 'ollama_buero', 'model' =&gt; 'bge-m3'],
        'vision' =&gt; ['profile' =&gt; 'ollama_buero', 'model' =&gt; 'gemma3'],
        'transcribe' =&gt; ['profile' =&gt; 'whisper', 'language' =&gt; 'auto'],
    ],
],</code></pre>
  <ul>
    <li><b>Altes Format bleibt gültig:</b> <code>provider</code>, <code>base_url</code>, <code>api_key</code>, <code>region</code>, <code>models</code>, <code>providers</code> je Fähigkeit und <code>transcribe</code> wandelt <code>Profiles::upgrade()</code> beim Lesen um – der Anbieter wird zur Verbindung <code>standard</code>, alle Zwecke zeigen darauf (andere Anbieter je Fähigkeit: <code>standard_{cap}</code>, whisper.cpp: <code>whisper</code>). Jede Ebene wird einzeln umgewandelt; eine Datei mit nur <code>'models' =&gt; ['text' =&gt; …]</code> ändert nur das Modell. Gespeichert wird immer Format 2.</li>
    <li><b>Sperren:</b> <code>Profiles::locks(Ai::fileLayer())</code> – was <code>config.local.php</code> bzw. <code>config/sites/{key}.php</code> setzt, ist in der Oberfläche je Feld gesperrt. Verbindungen gelten für die Installation; eine Website kann Zuordnungen in ihrer Datei überschreiben.</li>
    <li><b>Auflösen:</b> <code>Ai::for('vision')</code> bzw. <code>Ai::capability($zweck)</code> liefert Verbindung, Modell, Zeitlimit, Ersatz; <code>Ai::platformFor($zweck)</code> die Symfony-AI-Platform. <code>Ai::config()</code> enthält weiter <code>provider</code>, <code>models[cap]</code>, <code>providers[cap]</code> (jetzt auch <code>chat</code>) – bestehende Aufrufer laufen unverändert. Der Besucher-Chat ruft <code>Ai::stream(…, ['use' =&gt; 'chat'])</code>.</li>
    <li><b>Ersatz-Verbindung:</b> antwortet die erste Verbindung nicht (Fehler oder Pause nach Fehler), versucht <code>chat()</code>/<code>vision()</code>/<code>stream()</code> einmal die Ersatz-Verbindung (Streaming nur, solange noch nichts ausgegeben wurde). Nicht für Embeddings – Vektoren verschiedener Modelle passen nicht zusammen.</li>
    <li><b>Embedding-Modell ändern:</b> Der Suchindex merkt sich das Modell je Vektor (<code>Core\Search\Indexer</code>) und rechnet beim nächsten Abgleich alles neu; die Oberfläche weist vor und nach dem Speichern darauf hin.</li>
  </ul>
  <h3 id="ki-probe">Verbindung prüfen und Modelle anzeigen (<code>Core\AI\Probe</code>)</h3>
  <table class="doc-table">
    <tr><th>Art</th><th>Prüfen</th><th>Modelle</th></tr>
    <tr><td>Ollama</td><td><code>GET /api/version</code> (Version), <code>GET /api/tags</code> (Token als <code>Authorization: Bearer</code>, z. B. hinter einem Proxy)</td><td><code>/api/tags</code>: Größe, Parameter, Quantisierung, Familie; <code>POST /api/show</code> parallel für Kontextlänge und Fähigkeiten (höchstens 40 Modelle, 3 s je Anfrage)</td></tr>
    <tr><td>OpenAI, Mistral, OpenAI-kompatibel</td><td><code>GET /v1/models</code></td><td>Liste; Mistral mit Fähigkeiten (Chat, Bilder, Audio) und Kontextlänge, sonst Eignung nach Namen</td></tr>
    <tr><td>Anthropic</td><td><code>GET /v1/models</code> (<code>x-api-key</code>, <code>anthropic-version</code>)</td><td>Liste bzw. kuratierte Modelle, wenn der Dienst keine liefert</td></tr>
    <tr><td>whisper.cpp</td><td>Programme, Modell und ffmpeg auf dem Server</td><td><code>storage/ai/models/ggml-*.bin</code></td></tr>
  </table>
  <p>Ergebnis <code>status</code>: <code>ok</code> (mit Dauer, Version, Anzahl Modelle) · <code>auth</code> (401/403) · <code>unreachable</code> · <code>wrong_type</code> (antwortet, ist aber kein Dienst dieser Art) · <code>blocked</code> · <code>error</code>. Route <code>POST /admin/system/ai/provider</code> mit <code>op</code> = <code>check</code> | <code>models</code> (JSON, Recht <code>system.manage</code>, CSRF, 20 je Minute und Person; ungespeicherte Werte aus dem Dialog nur für die Agentur) bzw. <code>profile</code> | <code>delete</code> | <code>assign</code> (Formulare, nur Agentur). Ausgehende Anfragen: nur die Adresse der Verbindung (<code>GuardedHttpClient</code>), aufgelöste IP festgehalten, keine Weiterleitungen, 8 s, Antwort ≤ 4 MB; Link-local-/Metadaten-Adressen nie, eigenes Netz nur für Ollama und OpenAI-kompatibel (ausdrücklich eingetragen), http nur im eigenen Netz. Schlüssel stehen nie in Antworten, Seiten oder Protokollen; das letzte Prüfergebnis je Verbindung (Statuspunkt) liegt ohne Schlüssel in <code>storage/ai/checks.json</code>. Selbsttest <code>ai:selftest</code> mit vorgefertigten Antworten (Symfony <code>MockHttpClient</code>, kein Netz).</p>
  <p>Weitere Werte in Dateien (Vorrang vor der Oberfläche; Reihenfolge <code>storage/ai/config.json</code> ← <code>config.local.php</code> ← <code>config/sites/{key}.php</code>). <code>prices</code>, <code>kb</code> und <code>batch</code> gibt es nur hier; das alte Format sieht so aus:</p>
  <pre><code>'ai' =&gt; [
    'provider' =&gt; 'ollama',                     // ollama | mistral | openai | generic | fake (Tests)
    'base_url' =&gt; 'http://127.0.0.1:11434',
    'api_key'  =&gt; '',                           // mistral / openai / generic
    'region'   =&gt; 'EU',                         // openai: EU-Datenresidenz
    'models'   =&gt; ['text' =&gt; 'gemma3', 'embed' =&gt; 'bge-m3', 'vision' =&gt; 'gemma3'],   // Ollama-Standard für embed: nomic-embed-text
    'providers'=&gt; ['vision' =&gt; ['provider' =&gt; 'mistral', 'api_key' =&gt; '…', 'model' =&gt; 'pixtral-12b-latest']],
    'timeout' =&gt; 2.5, 'text_timeout' =&gt; 60, 'index_timeout' =&gt; 60, 'batch' =&gt; 32,   // Suche · Texte · Indexieren · Embeddings je Aufruf
    'transcribe' =&gt; ['backend' =&gt; 'whisper_cpp', 'model_path' =&gt; '…/ggml-large-v3-turbo-q5_0.bin', 'threads' =&gt; 4, 'timeout' =&gt; 3600],
    // 'enabled' =&gt; false,                        // KI der Installation abschalten
    'prices'  =&gt; ['gpt-4o-mini' =&gt; [0.15, 0.60]],   // USD je 1 Mio. Tokens (Kostenschätzung)
    'kb'      =&gt; true,                             // Wissensdatenbank semantisch (nur Installation)
],</code></pre>
  <p>Beispiel für eine neue Funktion (Controller der Verwaltung):</p>
  <pre><code>if (!can('ai.use') || !Ai::enabled('text')) throw new HttpException(403);
try {
    $desc = Ai::complete("Meta-Beschreibung (max. 155 Zeichen) für:\n" . $plainText,
        'Du bist SEO-Redakteur. Antworte nur mit dem Text, Sprache: ' . Lang::current() . '.', ['max_tokens' =&gt; 120]);
    $alt  = Ai::vision($mediaId, 'Kurzer, sachlicher Alt-Text (max. 120 Zeichen) auf Deutsch.')['text'];
} catch (AiException $e) { /* Meldung anzeigen, Feld bleibt leer */ }</code></pre>
  <div class="doc-note doc-note--info"><strong>Kleine lokale Modelle (Ollama)</strong><p>Für Besucher-Chat und Assistent auf einem Rechner ohne große Grafikkarte bewährt: <code>qwen3:4b-instruct</code> (≈ 2,5 GB, gutes Deutsch, 1–3 s je Antwort) mit <code>nomic-embed-text</code> für die Suche. <b>Nicht</b> die reinen „Denk“-Varianten (z. B. <code>qwen3:4b</code> in neueren Ollama-Versionen): Sie schreiben ihre Überlegungen trotz <code>think: false</code> in die Antwort. Ältere Kleinmodelle wie <code>qwen</code> (1.5) folgen den Anweisungen mit Quellen nicht zuverlässig. Prüfen: <code>php bin/console ai:test --cap=text</code>, Suche: <code>search:query "…"</code>.</p></div>
  <div class="doc-note doc-note--warn"><strong>Datenschutz</strong><p>Inhalte gehen nur an den Anbieter, wenn eine Funktion sie sendet; <code>Ai::capability($cap)['external']</code> sagt, ob sie den Server verlassen (Anbieter nicht auf localhost/privatem Netz). Externe Anbieter nur per https (http nur für lokale Hosts), für Text, Embeddings und Bilder Hosts per Positivliste (<code>GuardedHttpClient</code>, keine Weiterleitungen); die Transkription nutzt einen HTTP-Client ohne Weiterleitungen. Gezählt werden nur Aufrufe, Tokens, Dauer und Fehler – nie Inhalte; Fehler im Log ohne Anfrageinhalt. Besucher-Suchtexte gehen nur bei eingeschalteter semantischer Suche mit externem Anbieter hinaus (Hinweis auf der Ergebnisseite, Textvorschlag für die Datenschutzerklärung in den Grundeinstellungen). Keine Anfrage speichert Suchtext mit IP; die Zähler „ohne Treffer“ sind anonym, filtern E-Mail-Adressen/Nummern und verfallen (90 Tage bzw. 1 Jahr). Empfehlung: eigener Ollama-Server oder EU-Anbieter mit Auftragsverarbeitungsvertrag.</p></div>
  <h3 id="ki-transkription">Sprache → Text: Transkription (<code>Core\AI\Transcriber</code>, <code>Core\AI\MediaJobs</code>)</h3>
  <p>Ollama hat kein Speech-to-Text-Modell. Die Fähigkeit <code>transcribe</code> (<code>Ai::CAPS</code>, Schalter <code>sys.ai_transcribe</code>) hat daher eigene Wege, eingestellt unter Grundeinstellungen → KI → „Sprache → Text“ (Agentur) bzw. <code>'ai' =&gt; ['transcribe' =&gt; [...]]</code> in <code>config.local.php</code>:</p>
  <table class="doc-table">
    <tr><td><code>whisper_cpp</code> (lokal)</td><td><code>ffmpeg -i datei -vn -ac 1 -ar 16000 -c:a pcm_s16le</code> → <code>whisper-cli -m modell -f audio.wav -l de|auto -t N -ovtt -of … -ml 84 -sow --prompt "Name der Website."</code> (Fortschritt über <code>-pp</code>, Abbruch/Zeitlimit per <code>proc_terminate</code>, keine Shell). Nichts verlässt den Server.</td></tr>
    <tr><td><code>openai</code> (kompatibel)</td><td><code>POST {base_url}/v1/audio/transcriptions</code> (multipart, <code>response_format=verbose_json</code>, <code>timestamp_granularities[]=segment</code>, <code>language</code>; Segmente → Cues, ohne Segmente geschätzte Zeiten mit Hinweis), Tonspur per ffmpeg als MP3 16 kHz mono 32 kbit/s (ohne MP3-Encoder WAV), max. 25 MB (≈ 100 min). OpenAI <code>whisper-1</code>, Mistral <code>voxtral-mini-latest</code> (<code>https://api.mistral.ai</code>), eigene Server (faster-whisper-server/speaches). <b>Extern</b> → Hinweis in der Datenschutzerklärung, AV-Vertrag.</td></tr>
    <tr><td>Aufträge</td><td>Tabelle <code>media_jobs</code> (queued → running → done|failed|canceled, Fortschritt, Sekunden). Die Verwaltung startet losgelöst <code>nohup php bin/console ai:jobs --site=… &amp;</code> (<code>proc_open</code> nötig, PHP-CLI wie bei Sicherungen: <code>php_cli</code>); die Sperre <code>storage/ai/jobs.lock</code> sorgt dafür, dass installationsweit nur <b>ein</b> Auftrag rechnet. Rückfall per Cron: <code>*/5 * * * * php bin/console ai:jobs --all</code>. Von Hand: <code>php bin/console ai:transcribe &lt;medien-id&gt; [--lang=de] [--pool=key]</code>. Protokoll: <code>storage/logs/ai-jobs.log</code>.</td></tr>
    <tr><td>Ergebnis</td><td>Immer ein Entwurf (<code>source=ai</code>, „KI-Transkript – bitte prüfen“) plus Transkript-Entwurf; erst „Geprüft – veröffentlichen“ schreibt die .vtt-Datei. Übersetzen: <code>Ai::chat</code> mit <code>Prompts::translateBatch</code>, je 25 Cues, Zeiten unverändert, zählt zum Tageslimit. Zähler: Aufrufe, Dauer und <b>Sekunden Audio</b> (<code>usage.seconds</code>) – keine Inhalte.</td></tr>
  </table>
  <h4>whisper.cpp auf dem Server einrichten (Plesk)</h4>
  <ol>
    <li><b>Programm:</b> Plesk-Server ohne Paket: per SSH als Systembenutzer bauen – <code>git clone https://github.com/ggml-org/whisper.cpp &amp;&amp; cd whisper.cpp &amp;&amp; cmake -B build -DGGML_NATIVE=ON &amp;&amp; cmake --build build -j --config Release</code> (braucht <code>cmake</code>, <code>g++</code>), dann <code>build/bin/whisper-cli</code> nach <code>httpdocs/storage/ai/bin/</code> kopieren (wird automatisch gefunden). Alternativ Paketquelle (<code>apt install whisper.cpp</code>, Homebrew: <code>brew install whisper-cpp</code>) oder ein statisch gebautes Binary. Unter PHP-FPM muss <code>proc_open</code> erlaubt sein (Plesk → PHP-Einstellungen → <code>disable_functions</code>), und <code>open_basedir</code> muss den Pfad zulassen.</li>
    <li><b>Modell</b> (nicht im Webroot): <code>mkdir -p storage/ai/models &amp;&amp; curl -L -o storage/ai/models/ggml-large-v3-turbo-q5_0.bin https://huggingface.co/ggerganov/whisper.cpp/resolve/main/ggml-large-v3-turbo-q5_0.bin</code> (≈ 547 MB, SHA-256 <code>394221709cd5ad1f40c46e6031ca61bce88931e6e088c188294c6d5a55ffa7e2</code>). Sehr gutes Deutsch, mehrsprachig. Kleinere Server: <code>ggml-medium-q5_0.bin</code> (≈ 515 MB, langsamer) oder <code>ggml-small-q5_1.bin</code> (≈ 180 MB, schwächer). Englisch-only-Modelle (<code>*.en.bin</code>) nicht verwenden.</li>
    <li><b>ffmpeg:</b> meist <code>/usr/bin/ffmpeg</code> (<code>apt install ffmpeg</code>).</li>
    <li><b>CPU-Zeit:</b> large-v3-turbo braucht auf 4 CPU-Kernen grob 0,3–1 × Echtzeit (1 h Video ≈ 20–60 min), mit Apple-Silicon/GPU (Metal/CUDA) nur Sekunden bis wenige Minuten. RAM ≈ 1–2 GB während des Laufs. „Threads“ in den Einstellungen nicht höher als die freien Kerne setzen; Zeitlimit (Standard 3600 s) für lange Videos erhöhen.</li>
    <li>„Verbindung testen“ verarbeitet einen erzeugten Testton (1,5 s) – so sind Programm, Modell und Rechte geprüft. <code>health</code> prüft nur, ob Programme und Modell vorhanden sind.</li>
  </ol>

  <h3 id="ki-assistent">KI-Assistent der Redaktion (<code>Core\AI\Assist</code>)</h3>
  <p>Schreiben, Übersetzen, SEO und Alt-Texte für die Redaktion. <b>Grundsatz:</b> Alles sind Vorschläge – die Endpunkte liefern nur Text, gespeichert wird über die normalen Formulare oder die <code>…-apply</code>-Endpunkte, nachdem ein Mensch geprüft hat. Seiteninhalte nur als Entwurf, nie veröffentlicht. Die KI setzt bei fehlenden Angaben <code>[bitte ergänzen: …]</code>; <code>Assist::warnings()</code> meldet Platzhalter sowie fehlende/neue Zahlen, E-Mail- und Web-Adressen gegenüber dem Original.</p>
  <table class="doc-table">
    <tr><th>Baustein</th><th>Aufgabe</th></tr>
    <tr><td><code>app/AI/Prompts.php</code></td><td><b>Alle Anweisungen an einer Stelle</b> (Grundregeln <code>RULES</code>, Aktionen des Text-Assistenten, Ausgabeformate je Feldart, Übersetzen, SEO, Alt-Text, Teaser, Support, Wissensartikel, Tabellen-Felder). Dazu Seiten- und Tabellen-Generator (<code>pageGen()</code>, <code>tableGen()</code>). Anweisungen sind <b>nicht</b> in der Oberfläche änderbar – Agenturen passen Texte/Regeln hier an; jede Methode liefert <code>system</code>, <code>user</code>, <code>json</code>, <code>max_tokens</code>, <code>temperature</code>. Website-spezifisch ergänzt: Hinweise (<code>sys.ai_notes</code>) und Glossar (<code>sys.ai_glossary</code>: „Begriff“ = nie übersetzen, „Begriff = Übersetzung“ = fest).</td></tr>
    <tr><td><code>app/AI/Assist.php</code></td><td>Aufrufe mit Prüfung von <code>can('ai.use')</code>, <code>Ai::enabled(cap)</code> und Tageslimit (<code>sys.ai_daily_cap</code>, Standard 200 Aufrufe Text + Bild je Website, Transkription zählt nicht; <code>Ai::callsToday()</code>), JSON-Antworten (Ollama <code>format: json</code>), Säubern auf die erlaubten Tags (<code>Sanitizer</code>), verständliche Fehlermeldungen. <code>Assist::client()</code> → <code>&lt;script type="application/json" id="cms-ai"&gt;</code> in Verwaltung und Werkzeugleiste der Website (fehlt ohne Recht/KI → keine Knöpfe).</td></tr>
    <tr><td><code>app/AI/SeoCheck.php</code></td><td>SEO-Check ohne KI: Titel-/Beschreibungslänge (inkl. Titel-Zusatz des Kits), doppelte Titel/Beschreibungen je Sprache, Überschriften der gerenderten Entwurfsfassung (eine H1, keine übersprungenen Ebenen), Bilder ohne Alt-Text (auch je Sprache), Textmenge, Vorschaubild; <code>overview()</code> für die SEO-Übersicht.</td></tr>
    <tr><td><code>resources/js/_ai.js</code> + <code>resources/css/_ai.css</code></td><td>Oberfläche (Teil von <code>admin.js</code>/<code>admin.css</code>, damit auch <code>admin.shadow.css</code>): Dialoge in der Ebene <code>layerBox()</code> (Shadow DOM auf der Website). Einhängepunkte: <code>Rich.barHtml()</code>/<code>Rich.exec('ai')</code> (Knopf „✦ KI“ in jeder Formatierungsleiste), <code>init(scope)</code> (Knopf an Textfeldern, Karten), in <code>_media.js</code> <code>window.CMSAi.uploadSlot/uploadBind/mediaPanel/mediaSummary</code>.</td></tr>
    <tr><td>Seitenfeld <code>meta_title</code></td><td>Optionaler Titel für Suchmaschinen (Seiteneinstellungen); <code>Seo::forPage()</code> nutzt ihn statt des Seitentitels, der Titel-Zusatz bleibt.</td></tr>
  </table>
  <table class="doc-table">
    <tr><th>Endpunkt (CSRF, JSON)</th><th>Zweck · Recht zusätzlich zu <code>ai.use</code></th></tr>
    <tr><td><code>POST /admin/api/ai/text</code></td><td><code>{action: improve|shorten|expand|simple|fix|tone|free, text, format: rich|inline|plain, tone?, instruction?, lang?, page?, entry?}</code> → <code>{text, warnings}</code></td></tr>
    <tr><td><code>POST /admin/api/ai/translate</code></td><td><code>{from, to, items: [{key, text, html}]}</code> → <code>{items: {key: {text, warnings}}}</code> (Stapel als JSON, Rückfall einzeln)</td></tr>
    <tr><td><code>POST /admin/api/ai/seo</code></td><td><code>{page}</code> (<code>pages.manage</code>) oder <code>{entry: {table, id}}</code> (<code>data.edit</code>) → Titel, Beschreibung, Adresse (frei/zulässig geprüft), Fokus, Suchbegriffe, Hinweise</td></tr>
    <tr><td><code>GET /admin/api/ai/seo-check/{id}</code></td><td>SEO-Check einer Seite (ohne KI, nur <code>pages.manage</code>)</td></tr>
    <tr><td><code>POST /admin/api/ai/seo-apply</code></td><td>Geprüfte Beschreibungen aus der SEO-Übersicht (<code>/admin/ai/seo</code>) speichern (nur <code>pages.manage</code>/<code>data.edit</code> je Zeile)</td></tr>
    <tr><td><code>GET|POST /admin/api/ai/page-translate/{id}</code></td><td>Übersetzbare Texte (Standardsprache ↔ diese Übersetzung, Blöcke per ID) bzw. geprüfte Texte in den <b>Entwurf</b> schreiben (<code>pages.edit</code>, Version „KI-Übersetzung übernommen“)</td></tr>
    <tr><td><code>POST /admin/api/ai/alt</code></td><td><code>{media, pool?}</code> oder <code>{image: data:-URL}</code> (vor dem Hochladen, im Browser auf 1024 px verkleinert, nur temporär) → <code>{alt: {lang: …}, title, tags, decorative}</code> (<code>media.upload</code>)</td></tr>
    <tr><td><code>POST /admin/api/ai/alt-apply</code></td><td>Geprüfte Alt-Texte speichern (<code>media.upload</code>, Fähigkeit <code>vision</code>); Pool-Dateien nur mit <code>MediaPools::canEdit()</code></td></tr>
    <tr><td><code>POST /admin/api/ai/summary</code> · <code>support-reply</code> · <code>kb-polish</code> · <code>schema</code></td><td>Teaser eines Eintrags (<code>data.edit</code>) · Antwortvorschlag / Wissensartikel (Support-Team) · Feldvorschlag (<code>data.schema</code>)</td></tr>
  </table>
  <h3 id="ki-bereich">Der Bereich <code>/admin/ai</code></h3>
  <p>Menüpunkt mit Funktion <code>ai</code>, Recht <code>ai.use</code> und eingeschalteter Text- oder Bild-Fähigkeit; mit <code>system.manage</code> auch ohne Einrichtung (mit Erklärung). Ist der Bereich verborgen, erscheint „Eingereicht“ als eigener Menüpunkt. Bereichsnavigation (<code>views/ai/_nav.php</code>, Drill-down):</p>
  <table class="doc-table">
    <tr><th>Route</th><th>Inhalt · Voraussetzung</th></tr>
    <tr><td><code>/admin/ai</code></td><td>Übersicht: Status, Kontingent, offene Aufgaben</td></tr>
    <tr><td><code>/admin/ai/texte</code></td><td>Freier Schreib-Assistent (<code>GET page-fields/{id}</code>, <code>POST page-insert</code> → Entwurf) · Fähigkeit text</td></tr>
    <tr><td><code>/admin/ai/uebersetzen</code></td><td>Fehlende Übersetzungen je Sprache (<code>Center::translationGaps()</code>), „Anlegen &amp; übersetzen“ · text + mehrsprachig</td></tr>
    <tr><td><code>/admin/ai/seo</code></td><td>SEO-Übersicht (<code>SeoCheck::overview()</code>) · <code>pages.manage</code>; <code>/admin/seo</code> leitet dorthin um</td></tr>
    <tr><td><code>/admin/ai/alt-texte</code></td><td>Bilder ohne Alt-Text · <code>media.upload</code></td></tr>
    <tr><td><code>/admin/ai/untertitel</code></td><td>Videos ohne Untertitel, Audio ohne Transkript, offene Entwürfe, Aufträge · <code>media.upload</code> + <code>media.captions</code></td></tr>
    <tr><td><code>/admin/ai/seiten</code></td><td>Seiten-Generator (<code>Core\AI\Generator</code>; <code>POST page-propose|page-create</code>, angelegt über <code>Pages::create</code> als Entwurf) · text + <code>pages.manage</code></td></tr>
    <tr><td><code>/admin/ai/tabellen</code></td><td>Tabellen-Generator (<code>POST table-propose|table-create</code>; nie Gruppen, Verknüpfungen nur zu vorhandenen Inhaltstabellen, <code>kind=content</code> mit Workflow, bis zu 3 Beispiel-Entwürfe) · text + <code>data.schema</code></td></tr>
    <tr><td><code>/admin/ai/eingereicht</code></td><td>Prüf-Ebene (siehe <a href="#freigabe">Eingereicht</a>) · <code>review</code> + <code>review.manage</code></td></tr>
    <tr><td><code>/admin/ai/verlauf</code></td><td>Eigene KI-Vorschläge: <code>{storage}/ai/events.sqlite</code> (Zeit, Person, Bereich, Ziel, Status, Modell, Dauer – keine Inhalte, 90 Tage; Übernahmen meldet <code>POST /admin/api/ai/applied</code>)</td></tr>
    <tr><td><code>/admin/ai/einstellungen</code></td><td>Überblick (nur lesend) mit Verweis auf Grundeinstellungen → KI</td></tr>
  </table>
  <p><b>Veröffentlichungssperre:</b> <code>Pages::publish()</code> wirft eine <code>RuntimeException</code>, solange Entwurf, Titel oder Beschreibung <code>[bitte ergänzen: …]</code> enthalten (<code>Pages::openMarkers()</code>; Editor, Seitenliste, Seiteneinstellungen, REST/MCP melden 422). Weitere Endpunkte: <code>GET /admin/api/ai/status</code>; Untertitel über <code>/admin/api/media/{id}/transcribe</code>, <code>…/tracks/{tid}/translate</code>, <code>…/transcript</code>, <code>/admin/api/media-jobs</code> (+ <code>/{jid}/cancel</code>); Einstellungen über <code>/admin/system/ai/test</code> und <code>/admin/system/ai/provider</code>.</p>
  <p>Fehler: HTTP 403 (kein Recht/KI aus), 422 mit <code>{ok: false, error}</code> (Anbieter nicht erreichbar, Zeitüberschreitung, Tageslimit). Jede Antwort enthält <code>quota</code> (verbleibende Aufrufe). Der Test-Anbieter <code>fake</code> liefert gekennzeichnete Testantworten („[Test-KI] …“) für Oberflächentests.</p>

