<?php /** Entwicklerhandbuch · Kits & Design (Anker #kits; der alte Anker #themes bleibt als Sprungziel erhalten) */ ?>
  <span id="themes" aria-hidden="true"></span>
  <p class="lead">Ein neues Projekt ist ein neues Kit – der Core bleibt unverändert und updatefähig. Mitgeliefert: <b><code>basis</code></b> (neutrales Business-Kit mit Musterseiten, Startpunkt für neue Projekte: 16 eigene Blöcke, vier Navigationen, sieben Design-Vorlagen, Dunkelmodus, mehrsprachig – siehe <code>kits/basis/README.md</code>) und <b><code>praxis</code></b> (Arztpraxis: 22 Blöcke, Praxisdaten mit Sprechzeiten, Rezept-/Überweisungs-Eingänge, Style-Editor mit drei Vorlagen ohne Dunkelmodus), außerdem u. a. <b><code>nature</code></b> (organisch und erdig für Höfe, Gärtnereien, Naturschutz: Vorlagen für die vier Jahreszeiten, Waldnacht als Dunkelmodus, Saisonzeiten – siehe <code>kits/nature/README.md</code>) und <b><code>modern</code></b> (zeitgemäß und klar: große Grotesk-Typografie, Blockfarbe, Bento-Raster, vier Navigationen, Einstieg als Mosaik oder große Aussage – siehe <code>kits/modern/README.md</code>) und <b><code>glas</code></b> (Glassmorphism mit Lesbarkeit zuerst: Mattglas über Farbfeldern, Aurora im Einstieg, deckend bei „Transparenz reduzieren“ – siehe <code>kits/glas/README.md</code>). Ein Kit ist ein eigenständiges Paket (eigener Ordner, eigene Version, eigene Build-Abhängigkeiten) und kann von mehreren Websites gleichzeitig genutzt werden. Der Core enthält keine Kit-Namen.</p>
  <p>Ein Kit bündelt Design-Tokens, Blöcke, das Formular der zentralen Angaben, Datenlisten, JSON-LD, Startinhalte, Sprachdateien und Logik – es ist die funktionale Grundlage eines Projekts. Der gestalterische Teil darin heißt weiterhin <b>Design</b> (Menü „Design“, Style-Editor).</p>
  <div class="doc-note doc-note--info"><strong>Ordner kits/, Namen im Code bleiben</strong><p>Kits liegen unter <code>kits/{name}/</code>, ihre gebauten Assets unter <code>public/assets/kits/{name}/</code>. Alle Pfade liefert <code>Core\Kit</code> (<code>Kit::dir($name)</code>, <code>Kit::publicDir($name)</code>, <code>Kit::url($name, $pfad)</code>, <code>Kit::all()</code>, <code>Kit::fragment($name)</code>) – nirgends <code>ROOT . '/kits/'</code> fest verdrahten. Öffentliche Adresse: <code>/assets/kits/{name}/…</code> – nie fest eintragen; in CSS relative Pfade (<code>url(../fonts/x.woff2)</code>), in PHP <code>Kit::url()</code> bzw. <code>app()-&gt;theme-&gt;asset()</code>. <b>Rückfall:</b> Kits unter dem alten Ordner <code>themes/{name}/</code> (ältere Installationen, Kits von Dritten) und Assets unter <code>public/kits/{name}/</code> bzw. <code>public/themes/{name}/</code> werden weiter erkannt (Server noch nicht umgestellt); alte Adressen <code>/kits/…</code> und <code>/themes/…</code> leitet <code>public/index.php</code> mit 301 auf <code>/assets/kits/…</code> um. Umstellung bestehender Server: <a href="#deploy">Staging &amp; Deploy</a> → <code>php bin/console assets:migrate</code>.</p><p><b>Unverändert (Kompatibilität):</b> Datei <code>theme.php</code>, Klasse <code>Core\Theme</code>, <code>app()-&gt;theme</code>, Einstellung <code>sys.theme</code>, Konfiguration <code>'theme'</code>/<code>'themes'</code>, API-/MCP-Felder <code>theme</code>, Befehle <code>theme:*</code>, Helfer <code>theme_asset()</code> – gespeicherte Daten, Erweiterungen und Kits von Dritten laufen so ohne Anpassung weiter. <b>Aliase:</b> <code>kit.php</code> statt <code>theme.php</code>, <code>'kit'</code>/<code>'kits'</code> in <code>config/sites/{key}.php</code> bzw. <code>config.local.php</code>, <code>app()-&gt;kit</code>, <code>kit:list</code>, <code>kit:create</code>, <code>fragment()</code>.</p></div>
  <pre><code>kits/{name}/
├── theme.php         label, version, requires (Core-Version, z. B. '>=1.0.0'), backgrounds, blocks, settings, forms (Vorlage für Eingangs-Tabellen), seo, jsonld, conditional_css, frame_hosts,
│                     link_keywords, image_ratios, app, core_blocks, container_class, button_class
├── functions.php     Kit-Helfer (Präfix = Kit-Name)
├── seed.php          Startinhalte: settings, pages[blocks], page_refs, after (callable für weitere Inhalte)
├── design.php        optional: Design-Tokens (oder inline unter theme.php → design)
├── docs/manual.php   optional: Kapitel für das Handbuch der Redaktion (siehe unten)
├── guide/*.md        optional: Hinweise zu diesem Projekt für die Redaktion (Markdown, siehe unten)
├── lang/             {locale}.php (Verwaltung) · site/{lang}.php (feste Website-Texte, lt())
├── templates/        layout.php · error.php · maintenance.php · offline.php (PWA) · form-page.php (optional, /anfrage/{form})
│                     search.php (optional) · partials/ (header, footer, section … – Kit-eigene Teile)
├── fragments/        optional: eigene Fassungen überschreibbarer Kern-Fragmente (brand.php, langswitch.php, hours.php …)
├── blocks/{type}.php Renderer: $b (Core\Block), $d (Daten inkl. Defaults)
├── assets/           css/ js/ img/  →  pnpm build  →  public/assets/kits/{name}/
├── build.mjs         optional: vendors(ctx) kopiert Kit-Vendoren (z. B. Schriften) beim pnpm build
├── package.json      optional: npm-Pakete nur für dieses Kit (installiert tools/build.mjs automatisch)
└── fonts/            serverseitige Dateien aus build.mjs (z. B. TTF für den Icon-Generator, nicht öffentlich)</code></pre>
  <h3 id="fragmente">Kern-Fragmente – <code>app/Views/fragments</code> (<code>Core\Fragments</code>)</h3>
  <p>Kits sind eigenständige Projekte ohne Eltern/Kind-Vererbung und ohne Abhängigkeiten untereinander; der Kern ist der Werkzeugkasten darunter. Zentrale Bausteine liegen deshalb <b>einmal</b> im Kern – wie REDAXO-Fragmente – statt als Kopie in jedem Kit. Aufruf wie bisher: <code>$theme-&gt;partial('brand', ['href' =&gt; url('/')])</code> oder <code>fragment('brand', […])</code>.</p>
  <table class="doc-table">
    <tr><th>Art</th><th>Fragmente</th><th>Regel</th></tr>
    <tr><td><b>Nur Kern</b></td><td><code>video-embed</code> (2-Klick-Video: Erkennung und Vorschaubild über <code>Core\Embeds</code>, Hinweistext, Link zur Datenschutzerklärung, „künftig direkt laden“, „Auf … ansehen“, Schaltfläche „{Anbieter}-Video laden“, Skript <code>resources/js/embed.js</code> mit <code>window.cmsConsent</code> und Ereignis <code>cms:consent</code>), <code>editor</code>, <code>toolbar</code></td><td>Kits liefern sie nicht aus und können sie nicht ersetzen – eine Kit-Datei gleichen Namens wird ignoriert (Entwicklermodus: HTML-Kommentar „WARNUNG“, Protokoll, Hinweis in <code>health</code>). Gestaltung nur per CSS: <code>.vembed</code> (+ <code>.r-16-9</code>/<code>.r-4-3</code>/<code>.r-21-9</code>, <code>.is-loaded</code>, <code>.vembed--empty</code>), <code>.vembed__poster</code>, <code>.vembed__gate</code>, <code>.vembed__info</code>, <code>.vembed__title</code>, <code>.vembed__text</code>, <code>.vembed__row</code>, <code>.vembed__remember</code>, <code>.vembed__ext</code>, <code>.vembed__play</code>, <code>.vembed__icon</code>, <code>.vembed__frame</code>, <code>.vembed__revoke</code> und Design-Tokens. Hinweis, Datenschutz-Link und Reihenfolge (Hinweis vor der Schaltfläche) sind im Markup fest. Damit nichts abgeschnitten wird: Seitenverhältnis nur als Mindesthöhe – <code>.vembed[data-embed]:not(.is-loaded){display:flex;flex-direction:column;overflow:clip}</code>, <code>.vembed__gate{position:relative;flex:1 0 auto}</code>.</td></tr>
    <tr><td><b>Überschreibbar</b></td><td><code>brand</code>, <code>langswitch</code>, <code>hours</code>, <code>legal</code>, <code>cookie-settings</code>, <code>breadcrumb</code>, <code>pagination</code>, <code>search-form</code>, <code>header-actions</code></td><td>Der Kern liefert eine barrierearme, CSP-sichere Standardfassung (nur zentrale Helfer: <code>org_name()</code>, <code>legal_links()</code>, <code>privacy_url()</code>, <code>footer_links()</code>, <code>consent_settings_link()</code>); ein Kit ersetzt sie <b>vollständig</b> durch eine gleichnamige Datei.</td></tr>
  </table>
  <p><b>Suchreihenfolge</b> (erster Treffer gewinnt): <code>project/overrides/kits/{kit}/fragments/{name}.php</code> (Anpassung des Projekts, von Updates nie angefasst) → <code>kits/{kit}/fragments/{name}.php</code> → <code>kits/{kit}/templates/partials/{name}.php</code> (bisheriger Ort, gilt weiter) → <code>app/Views/fragments/{name}.php</code>. Kit-eigene Teile (<code>header</code>, <code>footer</code>, <code>section</code> …) laufen über denselben Weg. <code>Kit::fragment('brand')</code> liefert die Datei, <code>Core\Fragments::find()</code> zusätzlich die Ebene.</p>
  <p><b>Optionen statt Kopien:</b> <code>theme.php → 'fragments' =&gt; ['video-embed' =&gt; [...], 'brand' =&gt; [...]]</code> – im Fragment als <code>$options</code>. <code>video-embed</code>: <code>ratio_class</code> (Präfix der Format-Klasse, Standard <code>r-</code>), <code>notice</code> (<code>short</code> | <code>detailed</code> mit Hinweis auf Verarbeitung außerhalb der EU), <code>title</code> (Videotitel über dem Hinweis), <code>empty</code> (<code>box</code> | <code>placeholder</code> „[Video folgt]“ | <code>none</code>), <code>play_class</code>, <code>play_icon</code>, <code>icon_size</code>, <code>poster_crop</code>. <code>brand</code>: <code>mark</code> (<code>monogram</code> | <code>dot</code> | <code>empty</code> | <code>none</code>), <code>logo_width</code>. <code>langswitch</code>: <code>role_list</code>.</p>
  <p><b>Überschriebene Kern-Fragmente überwachen:</b> Bringt ein Kit (oder das Projekt) eine eigene Fassung mit, merkt sich der Kern beim ersten Sehen die Prüfsumme des Originals (<code>storage/fragments.json</code>). Ändert sich das Original später (Update), meldet die Übersicht unter „Technik &amp; Betrieb“ und <code>php bin/console health</code> einen Hinweis – dann die eigene Fassung mit dem neuen Original vergleichen und mit <code>php bin/console fragments:list --accept</code> bestätigen. <code>fragments:list [--all]</code> zeigt je Fragment die Herkunft (Projekt, Kit, Kern). <b>Entwicklermodus</b> (<code>'debug' =&gt; true</code>): jedes Fragment steht zwischen <code>&lt;!-- fragment {name}: {Ebene} ({datei}) --&gt;</code> und <code>&lt;!-- /fragment {name} --&gt;</code>.</p>
  <h3 id="kit-check">Überschreibungen prüfen – <code>kit:check</code></h3>
  <p>Kits dürfen Kern-Blöcke (<code>kits/{kit}/blocks/data_list.php</code> …) und Kern-Fragmente überschreiben. Damit nach Core-Updates nichts still veraltet, prüft <code>php bin/console kit:check [--kit=name|--all] [--strict] [-v]</code> nur anhand der Quellen:</p>
  <ul>
    <li><b>verwaiste Block-Vorlagen</b> – Datei in <code>blocks/</code> ohne Block dieses Namens (Kit, Kern, Layout, aktive Erweiterung): wird nie gerendert;</li>
    <li><b>Kern-Block mit geändertem Vertrag</b> – die Kit-Fassung liest Angaben (<code>$d['…']</code>, <code>$b-&gt;data['…']</code>, <code>$b-&gt;edit('…')</code>), die der Kern-Block weder als Feld kennt noch selbst liest; mit <code>-v</code> zusätzlich Felder, die nur die Kern-Fassung liest (neu hinzugekommen?);</li>
    <li><b>Kern-Fragmente</b> mit geändertem Original (wie <code>fragments:list</code>).</li>
  </ul>
  <p><code>--strict</code> beendet mit Exit-Code 1, sobald es Hinweise gibt (z. B. in der CI eines Kit-Repositorys).</p>

  <h3 id="layout">Block „Layout“ (Spalten) – <code>Core\Layout</code>, <code>css/layout.css</code></h3>
  <p>Kern-Block <code>layout</code> (jedes Kit, abschalten mit <code>theme.php → 'layout' =&gt; false</code>): ein Abschnitt mit Raster und Blöcken je Spalte. Die Abschnitts-Optionen (Hintergrund, Anker, Navigation, Abstände, Trennlinie, Vollbild, Hintergrundbild) gelten für das ganze Layout. Daten:</p>
  <pre><code>{ "preset": "2-1", "valign": "top|center|bottom|stretch", "gap": "small|normal|large", "stack": "default|tablet", "reverse": false,
  "columns": [
    { "blocks": [ { "id": "a1", "type": "richtext", "data": { … } } ] },
    { "blocks": [ { "id": "a2", "type": "cta", "data": { "variant": "box", … },
                    "tunes": { "section": { "background": "dark", "anchor": "stellen", "visible": true } } } ] }
  ] }</code></pre>
  <ul>
    <li><b>Raster</b> (<code>Layout::PRESETS</code>): <code>1-1</code> ½+½, <code>2-1</code> ⅔+⅓, <code>1-2</code> ⅓+⅔, <code>1-1-1</code> ⅓×3, <code>1-1-1-1</code> ¼×4, <code>1-3</code> ¼+¾, <code>3-1</code> ¾+¼. Die Spaltenzahl folgt dem Raster (<code>Layout::fitColumns()</code>): fehlende Spalten leer, überzählige werden in die letzte Spalte zusammengeführt – nie Inhalt verwerfen.</li>
    <li><b>Verschachtelbar</b> (<code>Theme::nestable($typ, $variante)</code>, <code>nestableVariants()</code>): Block-Definition <code>'nestable' =&gt; true</code> oder eine Liste erlaubter Varianten (<code>['box']</code>); in einer Spalte gilt dann nur diese Variante (Speichern setzt sie, die Seitenleiste bietet nur sie an). Nie: <code>layout</code> selbst (kein Layout im Layout), Blöcke mit <code>'raw' =&gt; true</code>. Markiert ein Kit keinen eigenen Block, gelten <code>Layout::DEFAULT_NESTABLE</code> (richtext, text, quote, faq, downloads, notice). Kern: <code>data_form</code>, <code>data_fields</code>, <code>job_facts</code>, <code>job_apply</code>, <code>upcoming</code>, <code>map</code>. Mitgeliefert markiert: praxis (richtext, text_columns nur „kompakt“, quote nur „eingerückt“, notice, cta nur „Box“, downloads, accordion, video, job, map), basis (richtext, quote, faq, cta „Box“, video „Breit“, downloads, map), starter (text, faq, video, downloads).</li>
    <li><b>Prüfung beim Speichern</b> (<code>Pages::sanitizeBlocks()</code>, rekursiv): Kinder mit Feld-Schema wie Blöcke, nicht verschachtelbare werden verworfen und in <code>Pages::$rejected</code> gemeldet (REST/MCP: Fehler 422), Block-IDs der ganzen Seite eindeutig, Optionen eines Kinds nur <code>anchor</code>, <code>visible</code>, <code>background</code> (<code>''</code> = wie das Layout; ein anderer Hintergrund macht das Kind zur Karte).</li>
    <li><b>Ausgabe</b> (<code>app/Blocks/layout.php</code> → <code>Layout::render()</code>): Partial <code>section</code> des Kits, darin
      <code>&lt;div class="wrap lay-grid lay-grid--2-1 lay-v-top lay-gap-normal"&gt;</code>, je Spalte <code>&lt;div class="lay-col lay-col--w2"&gt;</code>, je Kind <code>&lt;div class="lay-item sec--{typ} v-{variante}"&gt;</code> mit dem Inhalt <b>ohne eigenen Abschnitt</b> (<code>Theme::renderInner()</code>); Karte: <code>sec lay-item--card bg-{name}</code>, Sprungmarke als <code>id</code> am Kind. In der Block-Vorlage: <code>$b-&gt;nested()</code> bzw. <code>$b-&gt;inRow()</code> (z. B. h3 statt h2), <code>$b-&gt;parent</code> = Layout-Block; <code>$b-&gt;edit('text')</code> liefert im Layout den vollen Pfad <code>columns.{s}.blocks.{n}.data.text</code> (<code>$b-&gt;editPrefix</code>). Klasse des Containers: <code>theme.php → 'layout' =&gt; ['wrap' =&gt; 'container']</code> (Standard wie <code>rows.wrap</code> bzw. <code>wrap</code>).</li>
    <li><b>Seitenweite Auswertung</b> (<code>Layout::flatten()</code>: Blöcke einschließlich Kinder): Stylesheets/Skripte je Typ (<code>conditional_css</code>), Suchindex, Sprungmarken (<code>Pages::anchors</code>), Mediennutzung, SEO-Prüfung, Rechtstext-Dialog. JSON-LD (<code>'jsonld'</code>), Redaktionsnotizen und Glossar wirken auf Kinder wie auf Blöcke. Formulare (<code>data_form</code>) senden an <code>/formular/{tabelle}</code> – unabhängig von der Lage des Blocks. Block-bezogene API-Aufrufe (<code>update_block</code> …) adressieren das Layout als Ganzes (<code>data.columns</code>).</li>
    <li><b>CSS</b> <code>css/layout.css</code> (Kern, nur mit Layout auf der Seite; Kit-Datei gleichen Namens ersetzt sie). Flexbox ohne Media Query – Spalten stehen unter <code>--lay-stack</code> (Breite des Inhaltsbereichs, Standard 700px ≈ Fenster &lt; 768 px) bzw. <code>--lay-stack-tablet</code> (940px ≈ &lt; 1024 px, Option „Schon auf Tablets“) untereinander. Weitere Variablen: <code>--lay-gap-s</code>, <code>--lay-gap</code>, <code>--lay-gap-l</code>, <code>--lay-item-gap</code> (Blöcke in einer Spalte), <code>--lay-card-pad</code>, <code>--lay-card-radius</code>. Die <code>.wrap</code> der Block-Vorlagen verliert in der Spalte Höchstbreite und Seitenrand. Beispiel praxis: <code>.lay-grid{--lay-stack:1000px;--lay-card-radius:24px}</code>, Box ohne zweite Fläche in einer Karte (<code>:not(.lay-item--card)&gt;.wrap&gt;.cta-box</code>).</li>
    <li><b>Editor</b> (<code>editor.js</code>): Vorschau des ganzen Layouts vom Server (wie auf der Website, gleiche Stapel-Grenze); <code>decorateLayout()</code> setzt je Kind eine Leiste in den Fluss der Spalte (Shadow DOM: ↑ ↓ ← →, Bearbeiten, Löschen mit Rückfrage) und „+ Block in diese Spalte“ (Auswahl nur mit <code>nestable</code>). „Bearbeiten“ öffnet die Felder des Kinds in der Seitenleiste (<code>ChildRef</code>, Formular mit <code>nested</code> → nur erlaubte Varianten; Optionen „In der Spalte“). Raster ändern: Spaltenaufteilung übernimmt der Editor vom Server.</li>
  </ul>
  <h3 id="reihen">Alte Reihen (Tune <code>row</code>) umstellen – <code>layout:migrate-rows</code></h3>
  <p>Die frühere Abschnitts-Option „Neben den vorigen Block stellen“ (Tune <code>row</code>: <code>auto</code>, <code>1-2</code>, <code>1-3</code>, <code>2-3</code>, <code>1-4</code>, <code>3-4</code>) ist im Editor abgeschafft. Bestehende Inhalte stellt <code>Theme::renderRow()</code> mit <code>css/rows.css</code> weiter dar (Variablen <code>--row-*</code>, <code>theme.php → 'rows'</code>), bis sie umgestellt sind:</p>
  <pre><code>php bin/console layout:migrate-rows [--site=…] [--dry-run]</code></pre>
  <ul>
    <li>Je Gruppe „Block + folgende Blöcke mit <code>row</code>“: alle verschachtelbar und höchstens 4 → <b>ein</b> Layout-Block mit dem nächstliegenden Raster (<code>Layout::closestPreset()</code> über die bisherigen Anteile, z. B. ⅔ + ⅓) und den Abschnitts-Optionen des ersten Blocks; spätere Blöcke behalten Sprungmarke/Sichtbarkeit, ein anderer Hintergrund wird zur Karte. Sonst (z. B. „Bild breit“ neben „Leistungen“): Option <code>row</code> entfernen – die Blöcke stehen wieder untereinander – und melden. Option ohne Wirkung (erster Block) wird ebenfalls entfernt.</li>
    <li>Veröffentlichte Fassung und offener Entwurf werden getrennt umgestellt (gleiche Fassungen bleiben gleich), Version „Reihen in Layout umgewandelt“, Seiten-Cache geleert. Wiederholbar: ohne <code>row</code> ändert sich nichts.</li>
    <li>Kit-Befehle für Inhalts-Umstellungen: <code>kits/{kit}/console.php</code> gibt <code>['name' =&gt; ['Beschreibung', fn(array $args): int]]</code> zurück (<code>Core\Kit::commands()</code>, z. B. praxis <code>praxis:migrate-team</code> – erzeugt jetzt direkt ein Layout ⅔ + ⅓).</li>
  </ul>

  <h3>Weitere Kit-Optionen</h3>
  <table class="doc-table">
    <tr><th>Schlüssel</th><th>Wirkung</th></tr>
    <tr><td><code>image_ratios</code></td><td>Bildformate, für die in der Mediathek eigene Zuschnitte möglich sind, z. B. <code>['16:9' =&gt; 'Querformat', '1:1' =&gt; 'Quadrat']</code>. Blöcke übergeben das Format: <code>img($id, $sizes, ['ratio' =&gt; '4:3'])</code>.</td></tr>
    <tr><td><code>project</code></td><td>Branchenspezifisches, damit der Core neutral bleibt: <code>terms</code> (sichtbare Begriffe wie „Praxisschlüssel“ statt „Schlüssel“, „Praxis“ statt „Organisation“; für geteilte Datentabellen <code>shared_owner</code>, <code>shared_from_owner</code>, <code>shared_from_members</code> – neutral „Eigentümer-Website“, „Von der Eigentümer-Website“, „Von Partner-Websites“, ein Verbands-Kit z. B. „Verband“, „Vom Verband“, „Von Vereinen“), <code>name_setting</code>, <code>setup_checks</code>, <code>dashboard_hint</code>, <code>public_info</code> (Funktion), <code>hours</code> (aktiviert Öffnungszeiten in API/MCP), <code>notice</code> (Hinweisbalken; der Core ergänzt Zeitraum und Darstellung – im Layout <code>notice_on()</code>, <code>notice_open('topnote')</code>, <code>notice_late('topnote')</code> vor <code>&lt;/body&gt;</code>, siehe <code>Core\Notice</code>), <code>link_labels</code>, <code>search_keywords</code>, <code>mcp.instructions</code>/<code>mcp.prompts</code>. Helfer: <code>project('hours.label')</code>, <code>term('key')</code>, <code>site_name()</code>.</td></tr>
    <tr><td><code>jsonld</code> / strukturierte Daten</td><td>Der Core gibt je Seite einen schema.org-<code>@graph</code> aus: Organisation (Funktion aus <code>theme.php → 'jsonld'</code>, vollständig auf der Startseite, sonst als Verweis <code>#org</code>, mit Geo-Koordinaten der Karte), <code>WebSite</code>, <code>WebPage</code>, <code>BreadcrumbList</code>. Blöcke deklarieren ihre Daten in der Blockdefinition, z. B. <code>'jsonld' =&gt; ['type' =&gt; 'faq', 'items' =&gt; 'items', 'question' =&gt; 'q', 'answer' =&gt; 'a']</code> (FAQPage) oder <code>['type' =&gt; 'video', 'url' =&gt; 'video_url', 'poster' =&gt; 'poster', 'name' =&gt; 'title']</code> (VideoObject, nur mit Vorschaubild) – oder eine Funktion <code>fn(Block $b): ?array</code>. Kern-Blöcke: Datenliste → <code>ItemList</code>, Kalender/Nächste Termine → <code>Event</code>. Detailseiten: Typ je Datentabelle („Strukturierte Daten“: NewsArticle, Article, BlogPosting, Event, Person, Product, Service, Place, Organization) – Felder werden nach Typ/Namen zugeordnet (Datum, Autor über Verknüpfung, Schlagworte, Funktion, E-Mail/Telefon, Preis/Verfügbarkeit, Adresse/Geo). Platzhalter in [Klammern] werden nicht ausgegeben. Code: <code>Core\StructuredData</code>.</td></tr>
    <tr><td>Vorschau in den Einstellungen</td><td>Das Einstellungsformular zeigt auf Wunsch rechts die echte Startseite mit den <b>ungespeicherten</b> Werten (<code>POST /admin/api/settings-preview</code>, Werte nur im Speicher über <code>Settings::override()</code>; Desktop/Mobil; je Sprache). Listenfelder mit <code>'preview' =&gt; true</code> erhalten je Eintrag „Vorschau dieses Eintrags“; das Kit liest den gewünschten Eintrag mit <code>preview_focus('feldname')</code> (Index) und zeigt ihn zuerst – Beispiel: praxis <code>blocks/hero.php</code>. Listeneinträge sind einklappbar und zeigen eine Kurzinfo (Auswahl, Aktiv/Inaktiv, Zeitraum, Bild).</td></tr>
    <tr><td><code>docs/manual.php</code></td><td>Kapitel für das Handbuch der Redaktion. Die Datei gibt ein Array zurück: <code>hero</code> (Kopf), <code>chapters</code> (Kern-Kapitel ersetzen, mit <code>mode</code> <code>before</code>/<code>after</code> ergänzen, mit <code>false</code> entfernen oder neue Kapitel mit <code>after</code> einfügen – jeweils <code>file</code> = PHP-Teilansicht in <code>docs/manual/</code>), <code>blocks</code> (Texte für „Alle Blöcke“), <code>vars</code> (z. B. <code>blocks_page</code>, <code>image_sizes</code>, <code>mcp_examples</code>) und <code>figures =&gt; false</code>. Die Kern-Kapitel liegen in <code>app/Admin/views/help/manual/</code>; Nummern und Inhaltsverzeichnis entstehen automatisch. Beispiele: praxis und basis. Eine ältere, vollständige Ansicht (kein Array) wird weiterhin statt des Kern-Handbuchs gezeigt.</td></tr>
    <tr><td><code>app</code></td><td>Vorgaben für den Icon-Generator (<code>defaults</code>: icon_text, icon_bg, icon_fg, icon_dot) und <code>info</code> = Name einer Funktion, die Name, Kurzname, Beschreibung und Kurzbefehle fürs Manifest liefert.</td></tr>
    <tr><td><code>fonts</code></td><td>Hausschrift des Kits: <code>preload</code> (Pfade relativ zu <code>public/assets/kits/{name}</code>; auch für den Offline-Speicher der App), <code>icon</code> (TTF relativ zu <code>kits/{name}</code> für den Icon-Generator; ohne Angabe: fette Systemschrift). Die Verwaltung nutzt die Schrift Lato aus dem Core.</td></tr>
    <tr><td><code>proxy</code></td><td>Weitere externe Quellen für den zentralen Proxy, z. B. <code>'wetter' =&gt; ['upstream' =&gt; 'https://api.example.org', 'allow' =&gt; '^v1/', 'ttl' =&gt; 600]</code> – siehe Kapitel „Karten &amp; Proxy“.</td></tr>
    <tr><td><code>project.map</code></td><td>Welche Einstellungen die Karte speisen: <code>location</code> (Feld vom Typ <code>geo</code>), <code>label</code>, <code>address</code> (Liste), <code>route</code> (eigener Routenlink), <code>click</code> (Vorgabe Zwei-Klick: Karte erst nach Klick auf „Karte anzeigen“ mit Hinweis und Link zur Datenschutzerklärung; Grundeinstellungen → Karten <code>sys.map_click</code> geht vor).</td></tr>
    <tr><td><code>map_loader</code></td><td><code>'kit'</code>: Im Zwei-Klick-Modus gibt der Kern kein <code>map.mjs</code>-Skript aus, sondern die Adresse in <code>data-cms-map-js</code> – das Kit-Skript importiert das Modul beim Klick auf <code>[data-cms-map-load]</code> und setzt vorher <code>data-go</code> an der Karte (Beispiel: praxis <code>site.js</code>). Standard <code>'core'</code>.</td></tr>
    <tr><td><code>layout</code></td><td>Block „Layout“ (Spalten): <code>false</code> schaltet ihn ab; <code>['wrap' =&gt; 'klasse']</code> = Klasse des Raster-Containers (Standard wie <code>rows.wrap</code> bzw. <code>wrap</code>). Siehe <a href="#layout">Layout</a>.</td></tr>
    <tr><td><code>rows</code></td><td>Nur noch Darstellung alter Reihen (Tune <code>row</code>): <code>false</code> = untereinander; <code>['wrap' =&gt; 'klasse']</code> = Klasse des Reihen-Containers. Umstellen: <a href="#reihen">layout:migrate-rows</a>.</td></tr>
    <tr><td><code>backgrounds</code>, <code>dark_backgrounds</code></td><td>Hintergründe der Abschnitte (Schlüssel → Bezeichnung) und welche davon dunkel sind (helle Schrift, <code>Block</code> setzt die passende Klasse).</td></tr>
    <tr><td><code>project.brand</code></td><td>Zwei Einstellungsfelder, deren Werte oben in der Seitenleiste der Verwaltung als Name der Website stehen (z. B. Wortmarke Zeile 1/2); ohne Angabe der Website-Name.</td></tr>
    <tr><td><code>core_blocks</code></td><td><code>false</code> schaltet alle zehn Kern-Blöcke ab (<code>data_list</code>, <code>data_fields</code>, <code>data_form</code>, <code>calendar</code>, <code>upcoming</code>, <code>map</code>, <code>gallery</code>, <code>slideshow</code>, <code>stack_cards</code>, <code>dials</code>). Einen einzelnen Kern-Block überschreibt ein Kit, indem es denselben Typ in <code>blocks</code> definiert bzw. <code>blocks/{typ}.php</code> mitbringt.</td></tr>
    <tr><td><code>container_class</code>, <code>button_class</code></td><td>CSS-Klassen, die Kern-Blöcke für Inhaltsbreite und Buttons verwenden (Standard: <code>wrap</code>, <code>btn btn--primary</code>).</td></tr>
    <tr><td><code>assets/css/data.css</code></td><td>Überschreibt die neutrale Kern-CSS der Datenblöcke (per <code>@import "../../../../resources/css/data.css";</code> erweiterbar).</td></tr>
    <tr><td><code>templates/mail/invitation.php</code>, <code>invitation.txt.php</code></td><td>Eigene Fassung der E-Mail „Einladung zu {Website}“ (<code>Core\Invites::mail()</code>; Kit vor Core <code>app/Admin/views/mail/</code>). Variablen: <code>$lang</code>, <code>$subject</code>, <code>$site</code>, <code>$siteUrl</code>, <code>$siteHost</code>, <code>$logo</code> (<code>cid:logo</code> oder <code>null</code>), <code>$brand</code>/<code>$brandDark</code> und <code>$onBrand</code>/<code>$onBrandDark</code> (erstes Farb-Token <code>accent</code>, <code>primary</code>, <code>brand</code> oder <code>akzent</code> des Style-Editors, dunkel <code>…@dark</code>; sonst Theme-Farbe der App; Schrift darauf weiß oder fast schwarz nach Kontrast), <code>$inviter</code>, <code>$role</code>, <code>$name</code>, <code>$message</code> (reiner Text), <code>$url</code>, <code>$expires</code>, <code>$passkeys</code>, <code>$passwordless</code>. Alles mit <code>e()</code> ausgeben; Texte über <code>__()</code> (Sprache der Einladung ist gesetzt). Für Outlook Tabellen-Layout beibehalten; lokal prüfen mit <code>'mail_dump' =&gt; true</code> (legt <code>.eml</code> und <code>.html</code> in <code>{storage}/mail</code> ab).</td></tr>
    <tr><td><code>templates/mail/account.php</code>, <code>account.txt.php</code></td><td>Eigene Fassung der E-Mails zu den Anmeldedaten (<code>Core\EmailChange::compose()</code>): neue Adresse bestätigen, Hinweis an die bisherige Adresse („Das war ich nicht“), Adresse vergeben, Adresse geändert, Passwort geändert/festgelegt. Variablen wie bei der Einladung (<code>$lang</code>, <code>$subject</code>, <code>$site</code>, <code>$siteUrl</code>, <code>$siteHost</code>, <code>$logo</code>, <code>$brand</code>…<code>$onBrandDark</code>) sowie <code>$title</code>, <code>$greeting</code>, <code>$paras</code> (Liste), <code>$facts</code> (Bezeichnung → Wert, z. B. Bisher/Neu), <code>$cta</code> (<code>label</code>, <code>url</code>, <code>note</code> oder <code>null</code>), <code>$after</code>, <code>$foot</code>, <code>$danger</code> (Schaltfläche als Warnung). Alles reiner Text – mit <code>e()</code> ausgeben.</td></tr>
    <tr><td><code>Pages::menu()</code></td><td>Menübaum aus Seiten mit „Im Menü“ – das Kit entscheidet über Darstellung (z. B. Aufklappmenü, <code>css/nav.css</code> nur bei Unterseiten).</td></tr>
  </table>
  <h3 id="projekt-hinweise">Hinweise zu diesem Projekt – <code>guide/*.md</code></h3>
  <p>Für projektbezogene Anleitungen, die über das allgemeine Handbuch hinausgehen („Screenshots von Websites im Format 16:10“, „Sondermeldungen so planen“), legt die Agentur Markdown-Dateien in <code>kits/{name}/guide/</code> ab. Gibt es mindestens einen Hinweis, zeigt das Handbuch der Redaktion gleich nach dem Überblick das Kapitel <b>„Hinweise zu diesem Projekt“</b> (mit Namen der Website und des Kits und einem Satz, dass die Hinweise das Handbuch ergänzen); dazu kommen ein Eintrag „Projekt-Hinweise“ in der Übersicht („Neu hier?“) und unter „Hilfe &amp; Support“, Treffer in der Suche (⌘K) und im Hilfe-Index des Assistenten. Ohne Hinweise erscheint nichts davon. Code: <code>Core\Guide</code>.</p>
  <table class="doc-table">
    <tr><th>Thema</th><th>Regel</th></tr>
    <tr><td>Dateien &amp; Reihenfolge</td><td><code>NN-name.md</code>, nur Kleinbuchstaben, Ziffern, <code>-</code> und <code>_</code> (z. B. <code>10-startseite.md</code>, <code>20-sondermeldungen.md</code>); sortiert natürlich nach Dateinamen – die Zahl vorn bestimmt die Reihenfolge. Andere Namen und Dateien über 100 KB werden übergangen.</td></tr>
    <tr><td>Titel</td><td>Die erste Zeile <code># Titel</code> (vor anderem Text); sonst <code>titel:</code> im Kopf, sonst der Dateiname ohne Nummer.</td></tr>
    <tr><td>Kopf (Front Matter, optional)</td><td>Zwischen zwei Zeilen <code>---</code> ganz oben: <code>bereich: medien, daten/arbeiten</code> (Link „Hinweis zum Projekt“ über dem Inhalt dieses Verwaltungsbereichs – <code>uebersicht</code>, <code>seiten</code>, <code>einstellungen</code>, <code>medien</code>, <code>daten</code> bzw. <code>daten/{tabelle}</code>, <code>anfragen</code>, <code>design</code>, <code>bloecke</code>, <code>benutzer</code>, <code>weiterleitungen</code>), <code>block: stage, hero</code> (Link im Formular dieser Blocktypen), <code>titel: …</code>, <code>ausblenden: ja</code>.</td></tr>
    <tr><td>Inhalt</td><td>Markdown-lite wie im Support (<code>Core\Support\Markdown</code>): Absätze, Listen (<code>-</code>, <code>1.</code>), Zwischentitel (<code>##</code> – im Handbuch als kleine Überschrift), <code>**fett**</code>, <code>*kursiv*</code>, <code>`Code`</code>, Code-Blöcke, Links <code>[Text](https://…)</code> oder <code>[Text](/admin/media)</code>. HTML wird nie ausgeführt, Links laufen durch <code>Sanitizer::safeHref</code> (kein <code>javascript:</code>).</td></tr>
    <tr><td>Bilder</td><td>Eine eigene Zeile <code>![Alternativtext](bild.png "Bildunterschrift")</code>; die Datei liegt direkt im <code>guide</code>-Ordner (PNG, JPG, WebP, GIF, AVIF – kein SVG) und wird nur angemeldeten Benutzern ausgeliefert (<code>/admin/hilfe/projekt/bild/{datei}</code>).</td></tr>
    <tr><td>Je Website</td><td>Administration (Recht <code>system.manage</code>) legt unter <b>Handbuch → Projekt-Hinweise</b> (<code>/admin/hilfe/projekt</code>) eigene Hinweise an; sie liegen in <code>{storage}/guide/*.md</code> (<code>storage/sites/{key}/guide/</code>, Website „default“: <code>storage/guide/</code>). Gleicher Dateiname wie im Kit ersetzt den Kit-Hinweis für diese Website („Für diese Website anpassen“), <code>ausblenden: ja</code> blendet ihn aus; „Anpassung entfernen“ stellt das Kit wieder her.</td></tr>
    <tr><td><code>theme.php → 'guide'</code></td><td>Optional: <code>['title' =&gt; 'Hinweise zu diesem Projekt', 'author' =&gt; 'KLXM Crossmedia', 'lead' =&gt; '…', 'dir' =&gt; 'guide']</code> – Kapitelname, Absender im Einleitungssatz, eigener Einleitungssatz, anderer Ordner. <code>'guide' =&gt; false</code> schaltet die Kit-Hinweise ab (die der Website bleiben).</td></tr>
    <tr><td>Prüfen</td><td><code>php bin/console guide:list --site=…</code> (Hinweise mit Herkunft und Bezug) · <code>guide:selftest</code>.</td></tr>
  </table>
  <pre><code>---
bereich: daten/arbeiten
block: data_list
---
# Referenzen pflegen

Bilder im Format **16:10**. Website-Screenshots …

## Schlagworte
- Hashtag ohne #, Leistungen als Filter</code></pre>
  <h3 id="kit-css-js">Die Kit-Seite „CSS &amp; JS“ – <code>docs/css-js.md</code></h3>
  <p>Was der Kern an CSS und JavaScript mitbringt, steht einmal für alle in <a href="#css-js">CSS &amp; JS</a>. Was ein Kit darauf setzt, beschreibt jedes Kit auf <b>einer</b> Seite mit festem Aufbau: <code>kits/{name}/docs/css-js.md</code> (Entwicklerdoku – bewusst nicht unter <code>guide/</code>, denn die Hinweise dort liest die Redaktion im Handbuch).</p>
  <table class="doc-table">
    <tr><th>Abschnitt</th><th>Inhalt</th></tr>
    <tr><td>1. Überblick</td><td>Dateien, die immer laden, Budgets, Build-Befehl</td></tr>
    <tr><td>2. Tokens &amp; Farben</td><td>Präfix der Kit-Variablen, Design-Tokens des Style-Editors, Hell/Dunkel, welche Kern-Variablen (<code>--dl-*</code>, <code>--gl-*</code> …) das Kit setzt</td></tr>
    <tr><td>3. Blöcke → Dateien</td><td>Besonderheiten zur generierten Tabelle (geteilte Dateien, Varianten mit eigener Datei, ersetzte Kern-Stylesheets)</td></tr>
    <tr><td>4. Animationen &amp; Regeln</td><td>Was sich bewegt, Endbild bei „Bewegung reduzieren“, Pausenknopf (WCAG 2.2.2), Verhalten im Bearbeiten-Modus</td></tr>
    <tr><td>5. Overlays, Sheets, Dialoge</td><td>z-index des Kits, Fokus, <kbd>Esc</kbd>, nachgeladene Inhalte</td></tr>
    <tr><td>6. JavaScript &amp; Ereignisse</td><td>Globale Objekte, eigene Ereignisse mit Payload, <code>data-*</code>-Schnittstellen</td></tr>
    <tr><td>7. Sonderfälle</td><td>Abweichungen von den Kern-Regeln mit Begründung</td></tr>
    <tr><td>Anhang (generiert)</td><td>zwischen <code>&lt;!-- docs:assets:start … --&gt;</code> und <code>&lt;!-- docs:assets:end --&gt;</code>: immer geladene Dateien, <code>conditional_css</code>, Blöcke → Renderer/CSS/JS je Variante, Design-Tokens, Variablen je Datei, Bewegung/Barrierefreiheit je Datei (⚠ bei Animation ohne <code>prefers-reduced-motion</code>), Ereignisse, <code>data-*</code></td></tr>
  </table>
  <pre><code>php bin/console docs:assets --kit=meinkit --update        # legt docs/css-js.md mit Vorlage an bzw. erneuert nur den Anhang
php bin/console docs:assets --kit-dir=/pfad/zum/kit --update   # Kit außerhalb von kits/ (z. B. private Kits einer anderen Installation)</code></pre>
  <p>Text außerhalb der Marker bleibt bei jedem Lauf unverändert. Nach Änderungen an <code>theme.php</code>, Block-Dateien oder <code>assets/</code> den Anhang erneuern und im selben Commit mitgeben. Stand der mitgelieferten Kits:</p>
  <table class="doc-table">
    <tr><th>Kit</th><th>Blöcke mit Renderer</th><th>bedingte Dateien</th><th>Seite</th></tr>
    <?php foreach (\Core\Kit::all() as $__kn => $__kd): $__ka = \Core\AssetDocs::kit($__kd); ?>
    <tr><td><code><?= e($__kn) ?></code></td><td><?= count(array_filter($__ka['blocks'], fn($b) => $b['renderer'] !== '')) ?></td><td><?= count($__ka['conditional']) ?></td><td><?= is_file($__kd . '/docs/css-js.md') ? '<code>' . e(\Core\Kit::relative($__kd)) . '/docs/css-js.md</code>' : '–' ?></td></tr>
    <?php endforeach; ?>
  </table>
  <h3 id="design">Design (Style-Editor) – <code>theme.php → 'design'</code></h3>
  <p>Unter <b>Verwaltung → Design</b> ändern Admins Farben, Formen und Schriften, ohne das Kit anzufassen. Das Kit beschreibt, <em>was</em> einstellbar ist; jeder Wert ist eine CSS-Variable (oder eine Klasse am <code>&lt;html&gt;</code>). Werte gelten je Website <b>und</b> je Kit (Einstellung <code>design.{theme}</code>, Verlauf der letzten 10 Stände in <code>design.{theme}.history</code> mit Zeitpunkt und Benutzer). Recht <code>design.edit</code> (Standard: nur Administration), Funktion <code>design</code> im Funktionsumfang.</p>
  <pre><code>'design' => [
    'groups' => [
        ['id' => 'farben', 'label' => 'Farben', 'tokens' => [
            ['name' => 'accent', 'label' => 'Akzent', 'help' => 'Buttons, Links', 'type' => 'color', 'var' => '--accent',
             'default' => '#0F766E', 'dark' => '#2DD4BF',                    // optional eigener Dunkel-Wert (Eingabe „Dunkel“)
             'contrast' => ['with' => 'bg', 'min' => 4.5]],                  // with: Farbe oder Token-Name; optional dark_with
            ['name' => 'bg', 'label' => 'Hintergrund', 'type' => 'color', 'var' => '--bg', 'default' => '#FFFFFF', 'dark' => '#111418'],
        ]],
        ['id' => 'formen', 'label' => 'Formen', 'tokens' => [
            ['name' => 'radius', 'label' => 'Eckenradius', 'type' => 'range', 'var' => '--radius', 'default' => 12, 'min' => 0, 'max' => 32, 'step' => 2, 'unit' => 'px'],
            ['name' => 'buttons', 'label' => 'Buttons', 'type' => 'choice', 'var' => '--r-btn', 'preview' => 'radius', 'default' => 'pill',
             'options' => ['pill' => 'Rund', 'square' => 'Eckig'], 'values' => ['pill' => '999px', 'square' => '4px']],
            ['name' => 'nav', 'label' => 'Navigation', 'type' => 'choice', 'class' => 'nav-{value}', 'preview' => 'nav', 'default' => 'classic',
             'options' => ['classic' => 'Klassisch', 'centered' => 'Zentriert', 'burger' => 'Kompakt'], 'thumbs' => ['classic' => 'left']],
            ['name' => 'sticky', 'label' => 'Kopf mitscrollen', 'type' => 'bool', 'class' => 'has-sticky', 'default' => true],
        ]],
        ['id' => 'schrift', 'label' => 'Schrift', 'tokens' => [
            ['name' => 'font', 'label' => 'Schrift', 'type' => 'font', 'var' => '--font', 'default' => 'inter'],
        ]],
    ],
    'fonts'   => ['inter' => ['label' => 'Inter', 'stack' => 'Inter, system-ui, sans-serif', 'css' => 'css/font-inter.css'], …],
    'presets' => ['petrol' => ['label' => 'Petrol', 'values' => ['accent' => '#0F766E', 'accent@dark' => '#2DD4BF']], …],
    'dark'    => ['media' => '(prefers-color-scheme: dark)', 'scope' => ':root:not(.light)', 'force' => 'data-theme=dark'],
    'sample'  => 'muster',                                                   // optional: Musterseite (Pfad oder Liste von Pfaden) für die Vorschau
],</code></pre>
  <table class="doc-table">
    <tr><th>Typ</th><th>Editor</th><th>Ausgabe</th></tr>
    <tr><td><code>color</code></td><td>Farbwähler + Hex, optional „Dunkel“; Kontrast-Badge (WCAG AA/AAA) bei <code>contrast</code></td><td><code>--var:#RRGGBB</code>; Dunkel-Wert in <code>dark.scope</code> (innerhalb <code>dark.media</code>)</td></tr>
    <tr><td><code>range</code></td><td>Schieberegler + Zahl + Einheit</td><td><code>--var:12px</code> (min/max werden erzwungen)</td></tr>
    <tr><td><code>choice</code></td><td>Segmente; mit <code>preview</code> Karten: <code>radius</code> (Wert als Ecke), <code>color</code>, <code>nav</code> (CSS-Schema: left, center, split, burger, sidebar, floating, transparent, bottom – Zuordnung über <code>thumbs</code> oder gleichnamige Optionen)</td><td><code>values</code> → Variable und/oder <code>class</code> (<code>{value}</code>) am <code>&lt;html&gt;</code></td></tr>
    <tr><td><code>bool</code></td><td>Schalter</td><td><code>class</code> bei an, bzw. Variable 1/0</td></tr>
    <tr><td><code>font</code></td><td>Auswahl mit Schriftprobe (Schrift-CSS wird dafür in der Verwaltung geladen)</td><td>Schrift-Stack als Variable; <code>css</code> der gewählten Schrift wird automatisch eingebunden</td></tr>
  </table>
  <p><b>Im Layout:</b> <code>design_head()</code> nach dem Kit-CSS (bindet die gewählten Schriftdateien und – nur wenn Werte vom Standard abweichen – die erzeugte Datei <code>design/design-{theme}-{hash}.css</code> ein) und <code>design_classes()</code> im <code>class</code>-Attribut von <code>&lt;html&gt;</code>. Einzelwerte liest <code>design('nav')</code>. Die Datei liegt im Medienordner der Website (<code>{media}/design/</code>, Hash = 10 Zeichen SHA-1). Die Standardwerte in <code>theme.php</code> müssen den Werten im Kit-CSS entsprechen – das Kit funktioniert damit auch ohne gespeicherte Werte.</p>
  <p><b>Editor:</b> Reiter je Gruppe, Vorlagen als Karten (füllen nur das Formular), Verwerfen, Kit-Standard, Verlauf (Wiederherstellen lädt einen früheren Stand ins Formular), Export/Import als JSON (<code>{"theme": …, "values": …}</code>, serverseitig über <code>Design::normalize()</code> geprüft; unbekannte Schlüssel werden gemeldet). Live-Vorschau (<code>POST /admin/api/design-preview</code>) rendert Startseite, eine gewählte Seite oder die Musterseite mit <code>Design::override()</code> – <code>design_head()</code> gibt die Variablen dann inline aus. „Dunkel“ in der Vorschau erzwingt die Dunkel-Werte ohne Media-Query und setzt optional <code>dark.force</code> (Klasse bzw. <code>attr=wert</code>) am <code>&lt;html&gt;</code>, damit auch themeeigene Dunkel-Regeln greifen. Speichern leert den Seiten-Cache; die CSS-Datei entsteht beim nächsten Aufruf der Website.</p>
  <p><b>API &amp; MCP:</b> <code>GET /api/v1/design</code> (Definition, Werte, Standardwerte, Kontrastprüfung, Verlauf) und <code>PATCH /api/v1/design</code> mit <code>{"values": {…}}</code>, <code>{"preset": "petrol"}</code> oder <code>{"reset": true}</code> – nur mit write-Token, dessen Benutzer-Rolle <code>design.edit</code> hat (sonst 403); ungültige Werte → 422. MCP: <code>get_design</code>, <code>set_design</code>.</p>
  <p><b>Referenz „basis“:</b> <code>kits/basis/design.php</code> definiert Farben (je hell + dunkel, Kontrastpartner als Token-Namen), die Gruppen Farben, Typografie (Fließtext- und Überschriftenschrift aus sechs selbst gehosteten Familien plus Systemschrift, Grundgröße, Skala, Stärke, Laufweite; <code>build.mjs</code> erzeugt je Familie <code>css/font-{key}.css</code>), Form &amp; Abstände (Radius, <code>btn-*</code>, <code>cards-*</code>, Abschnittsabstand), Navigation (<code>nav-{modern|classic|minimal|extended}</code> wählt Kopf-Partial und <code>css/nav-*.css</code>; Sticky, transparent, Infoleiste, Fußbereich) und Farbschema (<code>has-dark</code>) sowie sieben Voreinstellungen; <code>dark.force</code> = <code>is-dark</code> (<code>css/preview.css</code> wird nur in der Vorschau geladen). Standardwerte stehen identisch in <code>site.css</code> (auch der Dunkel-Block), weil ohne Abweichung keine Design-Datei ausgeliefert wird. Prüfung aller Vorlagen: <code>php kits/basis/tools/contrast.php</code>; Musterseite (<code>'sample' =&gt; ['musterseiten', …]</code>): <code>CMS_SITE=… php kits/basis/tools/demo.php</code>. Kits können über <code>seed.php → 'after' =&gt; callable</code> nach den Startseiten weitere Inhalte anlegen (Seitenbaum, Datentabellen, Medien).</p>
  <h3 id="kopfbereich-aktionen">Kopfbereich-Aktionen – <code>header_actions()</code> gestalten und überschreiben</h3>
  <p><code>Core\HeaderActions</code> liefert Handlungsaufruf (gefüllt, Kontur, Textlink →, Symbol + Text, geteilt, Chip mit Statuspunkt, <b>Kontakt-Menü</b> – Symbol mit <code>&lt;details&gt;</code>-Liste aus Telefon, E-Mail, Kontaktseite, Anfahrt über <code>Core\Maps</code>, Öffnungszeiten, WhatsApp/Signal nur bei vorhandenem Feld –, <b>Menüpunkt</b> – abgesetzt nach der Navigation; <code>HeaderActions::menu($menu)</code> nimmt das gleiche Ziel aus dem Menü –, keiner), zweite Aktion, Suche (Lupe/Popover, Feld mit Vorschlägen, Aufziehen, Befehlsfeld „Suchen … ⌘K“, Suchleiste), Anordnung (rechts, Suche mittig, Suche darunter), Kontakt-Chip mit Öffnungsstatus, Sprachumschalter (Kürzel, Aufklappliste, Namen – ohne Flaggen), Social-Symbole und „Anmelden“. Einrichten im Kit:</p>
  <ul>
    <li><b>design.php:</b> <code>\Core\HeaderActions::designGroup(['ha_cta_style' =&gt; 'link', 'ha_search' =&gt; 'inline'], ['exclude' =&gt; ['ha_status']])</code> als Gruppe – Tokens <code>ha_cta_style</code>, <code>ha_menu_icon</code>, <code>ha_cta</code>, <code>ha_cta2</code>, <code>ha_search</code>, <code>ha_layout</code>, <code>ha_contact</code>, <code>ha_status</code>, <code>ha_lang</code>, <code>ha_social</code>, <code>ha_account</code>; das Kit nennt nur seine Standards (so sieht jedes Kit anders aus).</li>
    <li><b>theme.php:</b> <code>...\Core\HeaderActions::settingsFields()</code> in Website › Darstellung (Felder <code>header_cta_label/link</code>, <code>header_cta2_label/link</code>, <code>header_status_label</code>, <code>header_account_label/link</code>) und <code>'header_actions' =&gt; ['classes' =&gt; ['solid' =&gt; 'btn btn--primary btn--small', 'outline' =&gt; …, 'split' =&gt; …]]</code> – Kit-Klassen je Stil (Markierung <code>.ha-cta--kit</code>); optional <code>'kit_css' =&gt; 'css/header-actions-kit.css'</code> (Kit-Regeln zu den Optionen, laden nur zusammen mit dem Kern-Bündel – hält <code>site.css</code> klein) und <code>'base_css' =&gt; false</code> (schlichte Auswahl „Kit-Button + Lupe“ ohne Kern-Datei; das Kit-CSS enthält dann <code>.ha{display:flex…}</code> und die 8-px-Ecken).</li>
    <li><b>layout.php:</b> <code>&lt;?= header_actions_head() ?&gt;</code> <em>vor</em> dem Kit-CSS. Es bündelt nur die benötigten Teile zu je einer Datei <code>/assets/ha/{hash}.css|js</code> (entsteht beim ersten Aufruf, gleich für alle Websites mit derselben Auswahl; sonst einzelne Dateien): Grundlage <code>header-actions.css</code> (≈ 1,8 KB) plus <code>-link</code>, <code>-chip</code>, <code>-dot</code>, <code>-split</code>, <code>-menu</code>, <code>-navitem</code>, <code>-cta2</code>, <code>-field</code>, <code>-expand</code>, <code>-command</code>, <code>-below</code>, <code>-contact</code>, <code>-extra</code> (je 0,2–1,9 KB); JavaScript <code>header-actions.js</code> (≈ 1 KB, Tastenkürzel – nur mit Suche) plus <code>-status.js</code> (Öffnungsstatus) und <code>-menu.js</code> (Aufklappliste); nie im Bearbeitungsmodus. Typisch 3–5 KB CSS je Kit. <code>header_actions_head(['media' =&gt; '(min-width: 48em)'])</code> hält die Dateien auf Telefonen aus dem kritischen Pfad (Glas-Dock).</li>
    <li><b>Kopf-Template:</b> <code>header_actions('bar', ['compact' =&gt; true, 'lang' =&gt; $langs])</code> in der Leiste, <code>header_actions('center')</code> nach der Marke, <code>header_actions('below', ['wrap' =&gt; 'wrap'])</code> am Ende von <code>&lt;header&gt;</code>, <code>header_actions_lang($langs, 'klasse')</code> für den Umschalter, <code>header_cta()</code> für Menü-Blatt und Fußbereich. <code>compact</code>: unter 30 em wandern Text-Aktionen ins Menü, Symbol-Aktionen bleiben 44 px groß; unter 48 em werden Feld/Aufziehen zur Lupe.</li>
    <li><b>Gestalten:</b> Die Kern-Regeln sind einfache Klassen (<code>.ha</code>, <code>.ha-cta--{stil}</code>, <code>.ha-split</code>, <code>.ha-chip</code>, <code>.ha-dot</code>, <code>.ha-field</code>, <code>.ha-cmd</code>, <code>.ha-below</code>, <code>.ha-center</code>, <code>.ha-lang--dropdown</code>); das Kit setzt die Variablen <code>--ha-accent, --ha-on, --ha-ink, --ha-muted, --ha-line, --ha-bg, --ha-surface, --ha-open, --ha-h, --ha-gap, --ha-field-bg, --ha-anchor</code> und überschreibt mit gleicher Spezifität (lädt danach). Nur die Ecken (8 px, keine Pillen) setzt der Kern fest.</li>
    <li><b>Eigenes Markup:</b> <code>templates/partials/header-actions.php</code> ersetzt <code>app/Views/header-actions.php</code> und bekommt <code>$ha</code> (<code>HeaderActions::model()</code>: <code>cfg</code>, <code>cta</code>, <code>cta2</code>, <code>mini</code>, <code>contact</code>, <code>status</code>, <code>search</code>, <code>social</code>, <code>account</code>), <code>$slot</code> und <code>$opt</code>. <code>HeaderActions::widthRem()</code> schätzt die Breite für Container-Queries (<code>{kit}_nav_fit</code>).</li>
    <li><b>Barrierefreiheit:</b> Suchfelder in <code>&lt;form role="search" aria-label&gt;</code> mit Beschriftung, Vorschläge als ARIA-Combobox mit <code>aria-live</code> (<code>search.js</code>), <kbd>/</kbd> und <kbd>⌘/Strg</kbd>+<kbd>K</kbd> (<code>aria-keyshortcuts</code>; nicht in Eingabefeldern oder Editoren), <kbd>Esc</kbd> schließt Popover bzw. Feld, Statuspunkt mit Textalternative, <code>forced-colors</code> und „Bewegung reduzieren“ berücksichtigt; kein Inline-Skript/-Stil, keine externen Anfragen.</li>
  </ul>
  <h3 id="rich-text-stile">Rich-Text-Stile (Klassenvertrag)</h3>
  <p>Die Formatierungsleiste erzeugt nur diese Klassen und Elemente – <code>Core\Sanitizer</code> lässt genau diese Werte zu und entfernt alles andere (auch <code>style</code>, <code>on…</code>, fremde Klassen). Jedes Kit gestaltet sie selbst:</p>
  <table class="doc-table">
    <tr><th>Markup</th><th>Bedeutung</th><th>Empfehlung</th></tr>
    <tr><td><code>&lt;p class="t-lead"&gt;</code></td><td>Hervorgehoben: Einleitung/Kernaussage, keine Überschrift</td><td>ca. 1,2–1,3 em, Farbe wie Überschriften; zählt in der Suche wie normaler Text</td></tr>
    <tr><td><code>&lt;p class="t-small"&gt;</code></td><td>Klein, Anmerkung</td><td>ca. 0,875 em – nicht kleiner, Lesbarkeit</td></tr>
    <tr><td><code>&lt;p class="t-note"&gt;</code></td><td>Hinweis-Box</td><td>Fläche + Linie links, Kontrast des Textes ≥ 4,5:1 auf der Fläche</td></tr>
    <tr><td><code>&lt;span class="c-accent|c-muted|c-success|c-warning|c-danger"&gt;</code></td><td>Textfarben (max. fünf, keine freien Farben)</td><td>Farbe über <code>--rt-accent</code>, <code>--rt-muted</code>, <code>--rt-success</code>, <code>--rt-warning</code>, <code>--rt-danger</code> setzen – die Leiste liest diese Variablen am bearbeiteten Text und prüft den Kontrast gegen den echten Hintergrund</td></tr>
    <tr><td><code>&lt;mark&gt;</code>, <code>&lt;sup&gt;</code>, <code>&lt;sub&gt;</code></td><td>Textmarker, hoch-/tiefgestellt</td><td>Marker mit dunkler Schrift auf heller Fläche (in allen Farbschemata)</td></tr>
    <tr><td><code>&lt;a href data-link title target="_blank" rel="noopener"&gt;</code></td><td>Link; <code>data-link</code> = stabiler Verweis (<code>page:12</code>, <code>page:12#anker</code>, <code>entry:news:5</code>, <code>media:9[:viewer]</code>)</td><td><code>href</code> wird bei jeder Ausgabe aus <code>data-link</code> neu berechnet (<code>Core\Links</code>)</td></tr>
  </table>
  <ul>
    <li><b>Hell/dunkel und farbige Abschnitte:</b> Die <code>--rt-*</code>-Werte je Kontext setzen – im Dunkelschema und auf dunklen Flächen hellere Varianten (Kern-Vorschlag: <code>#6FD69A</code>, <code>#F2C063</code>, <code>#FF9A8F</code>), hell <code>#1A7240</code>, <code>#8A4B00</code>, <code>#B42318</code> (≥ 4,5:1 auf Weiß und typischen Flächen); auf Akzentflächen blasse Töne oder <code>currentColor</code>. Da <code>var()</code> in Custom Properties am deklarierenden Element aufgelöst wird, die Variablen an jeder Abschnittsklasse neu setzen (z. B. <code>:root,.bg-white,.bg-dark{--rt-accent:var(--link)}</code>).</li>
    <li><b>Laden:</b> am besten in einer bedingten Datei mit dem Pseudo-Typ <code>'@rich'</code> in <code>conditional_css</code> – sie lädt nur, wenn die Seite solche Formatierungen (auch H2–H4 oder Zitat) tatsächlich ausgibt (<code>Core\Sanitizer::styled()</code>), so bleibt das Budget der Startseite unberührt. Beispiele: praxis <code>css/prose.css</code>, basis/editorial <code>css/rich.css</code>, fluid <code>css/prose.css</code>, essenz <code>css/b-prose.css</code>.</li>
    <li><b>Palette in der Verwaltung:</b> <code>Core\RichText::palette()</code> (Design-Token <code>accent_ink</code>/<code>accent</code>, <code>muted</code>, <code>background</code>, sonst Kern-Werte); überschreiben mit <code>theme.php → 'rich_text' =&gt; ['colors' =&gt; ['success' =&gt; ['#hell', '#dunkel']], 'background' =&gt; ['#FFF', '#111'], 'dark' =&gt; true]</code>.</li>
    </ul>
  <h3 id="partner-logos-kit">Kern-Block „Partner &amp; Logos“ gestalten</h3>
  <p>Der Block (<code>partners</code>) kommt aus dem Kern und steht in jedem Kit bereit (<code>app/Blocks/partners.php</code>, Stylesheet <code>resources/css/partners.css</code>, nur auf Seiten mit dem Block). Er nutzt die Farben des Kits über eine Zuordnung je Kit (<code>.cms-partners--t-{kit}</code> → <code>--{präfix}-ink</code>, <code>-text</code>, <code>-muted</code>, <code>-line</code>, <code>-link</code>, <code>-focus</code>, <code>-bg</code>, Radius), sonst <code>currentColor</code>-Mischungen – dadurch folgen Kacheln und Details automatisch dunklen Abschnitten und dem Dunkelschema. Eigene Kits setzen nur die Variablen, z. B. auf <code>:root</code> oder einem Abschnitt:</p>
  <table class="doc-table">
    <tr><th>Variable</th><th>Wirkung</th></tr>
    <tr><td><code>--partners-ink</code>, <code>--partners-text</code>, <code>--partners-muted</code></td><td>Namen/Schriftzüge, Kurzinfo, Kategorie</td></tr>
    <tr><td><code>--partners-line</code>, <code>--partners-tile</code>, <code>--partners-panel</code></td><td>Ränder, Fläche der Kachel („dezent“), Fläche der aufgeklappten Details</td></tr>
    <tr><td><code>--partners-link</code>, <code>--partners-focus</code></td><td>Link in den Details, Fokusrahmen (Kontrast ≥ 3:1 zum Hintergrund)</td></tr>
    <tr><td><code>--partners-bg</code></td><td>Hintergrund des Dialogs (sitzt am Ende von <code>&lt;body&gt;</code>, nutzt also die Seitenfarben)</td></tr>
    <tr><td><code>--partners-radius</code>, <code>--partners-gap</code>, <code>--partners-pad</code></td><td>Eckenradius, Abstand der Kacheln, Innenabstand (Standard 10 % – passt zur Flächenberechnung, besser nicht ändern)</td></tr>
  </table>
  <ul>
    <li><b>Klassen:</b> <code>.cms-partners</code> mit <code>--r-3-2|1-1|2-1</code>, <code>--c3…c6</code>, <code>--tile-soft|light|none</code>, <code>--gray</code>, <code>--invert</code>, <code>--on-dark</code> (dunkler Abschnitt, <code>theme.php → dark_backgrounds</code>; mit JavaScript nach gemessener Helligkeit) und <code>.is-dark-bg</code> (Skript); Teile <code>__grid</code>, <code>__item</code>, <code>__cell</code> (Link, Schaltfläche oder div), <code>__mark.pl-w-{n}</code> (Logo, <code>.is-mono</code> = einfarbig), <code>__word</code> (Name ohne Datei), <code>__cat</code>, <code>__details</code>, <code>__detail</code>, <code>__dlogo</code>, <code>__name</code>, <code>__tag</code>, <code>__info</code>, <code>__link</code>, <code>__slot</code> (Zeile unter der Reihe), <code>__close</code>; Dialog <code>.cms-partners-dialog</code>.</li>
    <li><b>Karte auf dunklem Band:</b> Die Details haben keine eigene helle Fläche, sondern eine <code>currentColor</code>-Tönung – der <code>--k0-*</code>-Trick (Seitenfarben auf hellen Karten zurückholen) ist daher nicht nötig. Wer eine helle Karte möchte, setzt <code>--partners-panel</code> und die Textfarben auf <code>.bg-band .cms-partners</code>.</li>
    <li><b>Ersetzen:</b> <code>public/assets/kits/{kit}/css/partners.css</code> ersetzt das Kern-Stylesheet, <code>kits/{kit}/blocks/partners.php</code> die Ausgabe (Helfer <code>Core\Blocks\PartnerLogos::items()</code> und <code>::width()</code>).</li>
  </ul>
  <h3 id="nicht-gefunden">Seite „Nicht gefunden (404)“ – Startinhalte, Block, Rückfall</h3>
  <p>Die 404-Seite pflegt die Redaktion mit Blöcken (<code>Core\NotFound</code>, Seiten → Sonderseiten). Technisch ist sie eine Seite mit <code>type = 'template'</code> und <code>template_for = '@404'</code> je Sprache (Adresse <code>/404</code>, <code>/en/404</code> – antwortet selbst mit 404; nicht in Menü, Sitemap, Suchindex, Link-Auswahl, <code>Pages::all()</code>). Bei einer 404 bzw. 410 rendert <code>SiteController::error()</code> ihre veröffentlichten Blöcke im normalen Layout (<code>Landings::template()</code>) mit dem Status der Anfrage, <code>Seo::forError()</code> (noindex) und ohne Seiten-Cache; angemeldet mit Werkzeugleiste und Entwurf, <code>?edit=1</code> öffnet den Editor. Ohne veröffentlichte Seite – und immer bei 403/405/419/500 – gilt wie bisher <code>templates/error.php</code>. Das Kit braucht dafür nichts zu tun; die Vorlage bleibt Pflicht.</p>
  <table class="doc-table">
    <tr><th>Baustein</th><th>So nutzt ihn ein Kit</th></tr>
    <tr><td>Startinhalte</td><td><code>theme.php → 'not_found_blocks' =&gt; fn(string $lang): array =&gt; [['type' =&gt; 'hero', 'data' =&gt; […]], …]</code> (oder ein Array) – Blöcke im Editor.js-Format, beim Anlegen durch <code>Pages::sanitizeBlocks()</code> bereinigt; <code>lt()</code> liefert die Texte in der Sprache der neuen Seite. Am besten die Texte aus <code>templates/error.php</code> übernehmen. Ohne Angabe: ein Block „404-Vorschläge“ mit Überschrift, Text, Vorschlägen, Suche und Button.</td></tr>
    <tr><td>Block „404-Vorschläge“ (<code>not_found</code>)</td><td>Kern-Block: Dachzeile, Überschrift (H1), Text, „Vielleicht meinten Sie …“, Suchfeld, Button zur Startseite, zweiter Button. Stylesheet <code>resources/css/notfound.css</code> (Variablen <code>--nf-line</code>, <code>--nf-box</code>, <code>--nf-radius</code>, <code>--nf-link</code>, <code>--nf-gap</code>; ersetzen mit <code>public/assets/kits/{kit}/css/notfound.css</code>), Klassen des Kits über <code>container_class</code>, <code>button_class</code>, <code>button_secondary_class</code>.</td></tr>
    <tr><td>Eigenes Aussehen</td><td><code>kits/{kit}/blocks/not_found.php</code> ersetzt die Ausgabe; eigene Felder mit <code>theme.php → blocks → not_found =&gt; ['fields' =&gt; [… eigene Kopf-Felder, ...\Core\NotFound::blockFields()]]</code>. Helfer: <code>NotFound::boxes($b)</code> (Vorschläge + Suche als Kästen <code>.cms-404__*</code>, im Editor ein Hinweis), <code>NotFound::suggestions(null, 3)</code> (<code>[['title', 'href'], …]</code>), <code>NotFound::path()</code> (aufgerufene Adresse, im Editor <code>null</code>), <code>NotFound::homeUrl()</code>. Beispiel: praxis (Überschrift mit Punkt, Telefonzeile aus den Praxisdaten). Ein eigener Kopf-Block (z. B. großes Bild zur 404) plus überschriebener <code>not_found</code> für Vorschläge und Wege ist ebenso möglich.</td></tr>
    <tr><td>Kommandozeile</td><td><code>php bin/console notfound:create [--lang=en] [--publish] --site=…</code> legt die Seite mit den Startinhalten an (ohne <code>--publish</code> als Entwurf), <code>notfound:selftest</code> prüft Anlegen, Sichtbarkeit, eigene Adresse und Vorschläge (in einer Transaktion, die zurückgerollt wird).</td></tr>
  </table>
  <h3 id="varianten">Block-Varianten: bedingt laden, Felder je Variante, Einstieg mit Werkzeug</h3>
  <ul>
    <li><b><code>conditional_css</code> mit „Typ:Variante“</b> gilt für Stylesheets <i>und</i> Skripte, z. B. <code>'css/hero-x.css' =&gt; ['hero:search', 'hero:form']</code> – die Datei lädt nur auf Seiten mit dieser Variante (<code>SiteController::types()</code>).</li>
    <li><b><code>'uses'</code></b> in der Blockdefinition: <code>'uses' =&gt; ['figures' =&gt; ['dials'], 'dates' =&gt; ['upcoming'], 'form' =&gt; ['data_form'], 'map' =&gt; ['map']]</code> – eine Variante bringt die Stylesheets eines anderen (Kern-)Blocks mit (<code>Core\Theme::withUses()</code>).</li>
    <li><b>Felder je Variante:</b> <code>'variants' =&gt; ['search']</code> am Feld (Kapitel Feldtypen). <b><code>'variant_help'</code></b> <code>=&gt; ['variante' =&gt; 'Wann verwenden …']</code> erscheint im Handbuch der Redaktion (Alle Blöcke → Einstieg).</li>
    <li><b><code>Core\Blocks\Hero</code></b> (<code>app/Blocks/Hero.php</code>): Feld-Voreinstellungen (<code>Hero::fields('search'|'video'|'figures'|'dates'|'form'|'map'|'compare'|'gallery'|'quote'|'cards'|'marquee', [varianten])</code>) und Ausgabe-Teile, die in allen Kits gleich funktionieren müssen: Suchfeld mit Vorschlägen (<code>Search::form('hero', '', ['label', 'placeholder'])</code>), Vorschlags-Chips, Hintergrundvideo (eigene Datei, stumm, Schleife, Pause-Schaltfläche, bei „Bewegung reduzieren“ Standbild, spielt nur sichtbar), Vorher/Nachher (natives <code>input type=range</code>, ohne Skript Bilder nebeneinander), Laufzeile (läuft nur mit Skript, Pause), Kern-Kennzahlen ohne Container (<code>dials.php</code> mit <code>_bare</code>), nächste Termine bzw. neueste Einträge, öffentliches Formular, Karte. Markup-Rahmen und Aussehen liefert das Kit. Skript <code>public/assets/js/hero.mjs</code> (≈ 1,3 KB) bindet der Helfer nur bei Bedarf ein.</li>
</ul>
  <h3>Neues Projekt anlegen</h3>
  <pre><code>php bin/console kit:create kanzlei                  # Kopie des Start-Kits, Präfix starter_* → kanzlei_*
php bin/console kit:create kanzlei --from=basis     # oder eine andere Vorlage (alt: theme:create kanzlei basis)
cd tools && pnpm build                              # Assets + Kit-Vendoren bauen
php bin/console site:create kanzlei www.kanzlei.de kanzlei   # als eigene Website mit eigener Domain
# oder bestehende Website umstellen: Admin → Grundeinstellungen → Aktives Kit</code></pre>
  <h3 id="start-kit">Eigenes Kit entwickeln – mit dem Start-Kit</h3>
  <p>Das Kit <b><code>starter</code></b> ist das kleinste vollständige Kit: sechs kurze Beispielblöcke (<code>hero</code>, <code>text</code>, <code>text_image</code>, <code>cards</code>, <code>cta</code>, <code>faq</code>) plus <code>video</code> und <code>downloads</code> als Hüllen um Kern-Helfer, Design-Tokens mit hell/dunkel und zwei Navigationsvarianten, Systemschrift, eine Akzentfarbe. Jede Möglichkeit eines Kits ist einmal vorhanden und im Code erklärt – <code>theme.php</code> ist in Abschnitte <b>§ 1–11</b> gegliedert. Es ist <code>kit:create</code>s Standardvorlage und steht unter MIT; Ihr eigenes Kit darf eine beliebige Lizenz haben.</p>
  <ol>
    <li><b>Kopie:</b> <code>php bin/console kit:create meinkit</code> – kopiert <code>kits/starter</code> und <code>public/assets/kits/starter</code>, benennt Präfix (<code>starter_</code> → <code>meinkit_</code>), <code>label</code>, <code>description</code>, Paketnamen und Pfade um, setzt <code>version</code> auf 0.1.0 und zeigt die nächsten Schritte.</li>
    <li><b>Bauen:</b> <code>cd tools &amp;&amp; pnpm run build</code>.</li>
    <li><b>Testwebsite:</b> <code>php bin/console site:create meinkit meinkit.localhost meinkit</code> und <code>user:create … admin --site=meinkit</code>; beim ersten Aufruf spielt der Core <code>seed.php</code> ein.</li>
    <li><b>Anpassen:</b> Meta (§ 1), Farben in § 6 <em>und</em> <code>assets/css/_tokens.css</code> (Standardwerte müssen übereinstimmen), Kopf/Fuß (<code>templates/partials/</code>), Blöcke (§ 8 + <code>blocks/</code>), Formular „Website“ (§ 7), Startinhalte (<code>tools/demo-content.php</code>).</li>
    <li><b>Prüfen</b> (Liste unten) und <code>CHANGELOG.md</code>, <code>README.md</code>, <code>LICENSE</code> anpassen.</li>
  </ol>
  <pre><code>kits/starter/
├── theme.php            § 1 Meta · § 2 Abschnitte · § 3 SEO &amp; JSON-LD · § 4 Projekt · § 5 Assets (conditional_css)
│                        § 6 Design-Tokens, Voreinstellungen, Navigationsvarianten · § 7 Website · § 8 Blöcke
│                        § 9 Daten (Listen/Detailseiten) · § 10 Startinhalte · § 11 Sprachen
├── functions.php        Helfer starter_* (Stammdaten, Links, Menü, Abschnittskopf, Buttons, JSON-LD, Manifest)
├── seed.php             settings, pages (→ tools/demo-content.php), page_refs, after
├── blocks/              hero, text, text_image, cards, cta, faq, video, downloads
├── templates/           layout, error, maintenance, offline
│   └── partials/        header (Navigation als popover, Suche, Sprachen), footer (+ footer_links()), section,
│                        (Video-Zwei-Klick, Editor, Werkzeugleiste, Marke, Sprachen: Kern-Fragmente)
├── assets/css/          _tokens.css (Tokens + Rollen, hell/dunkel) · _base.css · site.css (immer)
│                        blocks.css (Beispielblöcke) · core.css (nur Variablen für Kern-Blöcke)
├── assets/js/           site.js (≈ 0,4 KB) – das Video-Skript kommt aus dem Kern (resources/js/embed.js)
├── lang/                en.php (Verwaltung) · site/en.php (Website, lt())
├── tools/               demo-content.php · contrast.php (WCAG aller Voreinstellungen)
├── build.mjs            optionaler Build-Hook (leer, Beispiel für Schriften)
└── composer.json        Stub, Typ „klxm-studio-kit“ – Paket-Installation geplant</code></pre>
  <p><b>Farben über Rollen:</b> Komponenten nutzen nur Rollen (<code>--s-fg</code>, <code>--s-head</code>, <code>--s-link</code>, <code>--s-card</code>, <code>--s-btn-*</code>), die Abschnitte „Akzentfarbe“ und „Dunkel“ stellen sie um. <b>Kern-Blöcke</b> behalten die neutralen Kern-Stylesheets; <code>core.css</code> setzt nur deren Variablen (<code>--dl-*</code>, <code>--dff-*</code>, <code>--cal-*</code>, <code>--dial-*</code>, <code>--cms-map-*</code>, <code>--cms-*</code>). <b>Schrift:</b> Systemschrift; eigene per <code>php bin/console fonts:install Inter</code> (danach im Style-Editor wählbar) oder mit <code>build.mjs</code> im Kit. <b>Paket-Installation</b> (Composer, wie Erweiterungen vom Typ <code>klxm-studio-extension</code>) ist für Kits geplant; bis dahin liegen Kits unter <code>kits/{name}/</code>.</p>
  <p><b>Prüfliste</b></p>
  <ul>
    <li><code>php bin/console health --site=meinkit</code> – u. a. „Kit kompatibel“ (<code>requires</code>)</li>
    <li>Budgets: Ausgabe von <code>pnpm run build</code> – CSS der Startseite &lt; 30 KB, JS &lt; 8 KB (Start-Kit: ≈ 15,7 KB / 0,4 KB)</li>
    <li>Kontrast: <code>php kits/meinkit/tools/contrast.php</code> (alle Voreinstellungen, hell + dunkel) und die Abzeichen im Style-Editor</li>
    <li>Übersetzungen: <code>php bin/console i18n:missing en --site-texts --site=meinkit</code> sowie ohne <code>--site-texts</code></li>
    <li>Lizenzen: <code>node tools/licenses.mjs</code> (z. B. nach Hinzufügen von Schriftpaketen)</li>
    <li>Im Browser: keine Konsolenfehler, keine externen Anfragen, keine Cookies; Tastatur, 200 % Zoom, Kontrastmodus, hell/dunkel, 320 px Breite; eine Testseite mit Datenliste + Detailseite, Formular, Kennzahlen, Karte, Video, Downloads und Suche</li>
  </ul>
  <h3>Block hinzufügen</h3>
  <pre><code>// theme.php → 'blocks'
'faq_short' => [
    'label' => 'Kurz-FAQ', 'icon' => '?', 'group' => 'Inhalt',
    'variants' => ['plain' => 'Schlicht', 'boxed' => 'Mit Rahmen'],
    'fields' => [
        ['name' => 'title_strong', 'label' => 'Überschrift', 'type' => 'text', 'required' => true],
        ['name' => 'items', 'label' => 'Fragen', 'type' => 'repeater', 'fields' => [
            ['name' => 'q', 'label' => 'Frage', 'type' => 'text'],
            ['name' => 'a', 'label' => 'Antwort', 'type' => 'richtext'],
        ]],
    ],
],

// blocks/faq_short.php
&lt;div class="wrap"&gt;
  &lt;h2 id="&lt;?= e($b-&gt;titleId()) ?&gt;"&lt;?= $b-&gt;edit('title_strong') ?&gt;&gt;&lt;?= e($d['title_strong']) ?&gt;&lt;/h2&gt;
  &lt;?php foreach ($d['items'] as $i =&gt; $it): ?&gt;
    &lt;details&gt;&lt;summary&gt;&lt;?= e($it['q']) ?&gt;&lt;/summary&gt;&lt;?= rich($it['a']) ?&gt;&lt;/details&gt;
  &lt;?php endforeach; ?&gt;
&lt;/div&gt;</code></pre>
  <p>Der Block erscheint automatisch im Editor (Feldformular, Live-Vorschau, Abschnitts-Optionen, Drag &amp; Drop), in der REST-API und im MCP-Server.</p>
  <p><b>Skripte im Seiten-Editor (<code>editor_js</code>):</b> Beim Bearbeiten lädt der Editor keine Kit-Skripte. Was dort trotzdem laufen
    soll (Videoschleifen, Animationen), steht in <code>theme.php</code> unter <code>'editor_js' =&gt; ['js/b-loop.js', …]</code> – das Layout gibt es
    über <code>$extraJs</code> aus. Weil der Editor Blöcke nach dem Laden einsetzt und bei Änderungen neu zeichnet, richten diese Skripte
    Blöcke beim Ereignis <code>cms:block-preview</code> ein (<code>e.target</code> = Vorschau des Blocks).</p>
  <p><b>Blockdaten aus Kit-Skripten ändern (<code>CMSEditor.block(node)</code>):</b> liefert für ein Element in einem Block <code>{ type, id, def, get(pfad?), set({ 'pfad.mit.punkten': wert }) }</code> oder <code>null</code>. <code>set()</code> schreibt die Werte in die Blockdaten, markiert die Seite als geändert (Rückgängig/Wiederholen inklusive), frischt eine offene Seitenleiste auf und zeichnet die Vorschau neu (Promise, danach <code>cms:block-preview</code>). Beispiel: Kit „foto“ (<code>js/editor-photos.js</code>) – Fotos und Videos per Drag &amp; Drop hochladen (<code>CMSMedia.Uploader</code>) und an die Liste eines Blocks anhängen, umsortieren, entfernen.</p>
  <p><b>Bedingte Felder (<code>show_if</code>):</b> Ein Feld erscheint nur, wenn andere Felder bestimmte Werte haben – auch in
    Wiederholgruppen (Felder derselben Zeile). <code>'show_if' =&gt; ['kind' =&gt; ['image', '']]</code> (mehrere Felder = alle müssen passen;
    <code>'*'</code> = ausgefüllt, <code>''</code> = leer), <code>'/variant'</code> = Feld des Blocks statt der eigenen Zeile, eine Liste
    <code>[['kind' =&gt; ['image']], ['/variant' =&gt; ['grid']]]</code> = eine Bedingung genügt. Nur Anzeige: ausgeblendete Werte bleiben
    erhalten und werden gespeichert (Datentabellen nutzen <code>visible_if</code>, siehe Daten).</p>
  <h3 id="vcard">Visitenkarte (vCard) – <code>vcard_url()</code>, <code>Core\VCard</code></h3>
  <p>Besucher speichern die Organisation mit einem Klick im Adressbuch (iOS, Android, Outlook, Thunderbird). Immer an, sobald Telefon, E-Mail oder Adresse eingetragen sind – keine eigene Funktion, keine eigene Ablage.</p>
  <table class="doc-table">
    <tr><th>Adresse</th><th>Inhalt</th></tr>
    <tr><td><code>GET /vcard.vcf</code></td><td>Organisation: <code>FN</code>/<code>ORG</code> (<code>org_name()</code>; ohne eingetragenen Namen der Name aus dem JSON-LD des Kits), <code>ADR;TYPE=WORK</code> (Straße, PLZ, Ort, Land), <code>TEL;TYPE=WORK,VOICE</code>, <code>EMAIL;TYPE=INTERNET,WORK</code>, <code>URL</code> (Hauptadresse der Website, auch auf Landing-Domains), <code>GEO</code> (Standort der Karte, <code>Maps::siteLocation()</code>), <code>PHOTO</code> (Logo <code>setting('logo')</code> wie im Fragment <code>brand</code>), <code>NOTE</code> mit den Öffnungszeiten (<code>project.hours</code>, Wochentage zusammengefasst, Bezeichnung aus <code>project('hours.label')</code>), <code>X-ABShowAs:COMPANY</code>, <code>REV</code>. Ohne Telefon, E-Mail und Adresse: 404.</td></tr>
    <tr><td><code>GET /vcard/{tabelle}/{slug}.vcf</code></td><td>Person aus einer Inhaltstabelle mit Schema-Typ <b>Person</b> (Tabellen-Designer „Strukturierte Daten“, z. B. Vorlage „Team“), nur veröffentlichte Einträge: <code>N</code> (letztes Wort = Nachname, vorangestellte „Dr.“/„Prof.“ = Titel), <code>FN</code>, <code>ORG</code>, <code>TITLE</code> (Textfeld „Position/Funktion/Rolle“), <code>TEL</code>, <code>EMAIL</code>, <code>URL</code> (Detailseite), <code>PHOTO</code> (Bildfeld der Tabelle). Feldzuordnung wie bei den strukturierten Daten (<code>StructuredData::field()</code>).</td></tr>
  </table>
  <ul>
    <li><b>Quelle:</b> dieselben zentralen Angaben wie Kontakt-Blöcke, Fußbereich und JSON-LD – <code>project.public_info</code> des Kits (<code>CmsService::publicInfo()</code>), ergänzt um <code>StructuredData::organization()</code> (Adresse mit Land, Logo, Geo). Ein Kit muss dafür nichts tun, solange es <code>public_info</code> bzw. <code>jsonld</code> liefert.</li>
    <li><b>Format:</b> vCard 3.0 (RFC 2426), UTF-8, Zeilenende CRLF, Zeilen nach 75 Oktetts gefaltet (UTF-8-sicher, <code>ICal::fold</code>), Texte maskiert (<code>\\</code> <code>\;</code> <code>\,</code> <code>\n</code>), Redaktionsnotizen <code>[# … #]</code> entfernt. Bilder nur als PNG/JPEG (WebP/GIF werden mit GD umgewandelt), auf <?= \Core\VCard::IMAGE_MAX_SIDE ?> px verkleinert und nur bis <?= (int) (\Core\VCard::IMAGE_MAX_BYTES / 1024) ?> KB eingebettet; SVG nie.</li>
    <li><b>Antwort:</b> <code>Content-Type: text/vcard; charset=utf-8</code>, <code>Content-Disposition: attachment; filename="{name}.vcf"</code> (Name als Dateiname, Umlaute umschrieben), <code>Cache-Control: public, max-age=900</code>, <code>X-Robots-Tag: noindex</code>. Nicht im Seiten-Cache; im Wartungsmodus nur für Angemeldete. <code>?lang=en</code> wählt die Sprache (Öffnungszeiten, übersetzte Einträge).</li>
    <li><b>Im Kit:</b> <code>&lt;?php if ($v = vcard_url()): ?&gt;&lt;a href="&lt;?= e($v) ?&gt;" download&gt;&lt;?= e(lt('Kontakt speichern')) ?&gt;&lt;/a&gt;&lt;?php endif; ?&gt;</code> – auf Detailseiten <code>vcard_entry_url($ctx['table'], $ctx['entry'])</code> mit <code>$ctx = app()-&gt;entry</code>. Beide liefern <code>null</code>, wenn es keine Karte gibt. <code>/vcard</code> ist als Seitenadresse gesperrt (<code>PublicPaths::RESERVED_SLUGS</code>).</li>
    <li><b>Test:</b> <code>php bin/console vcard:selftest</code> (zerlegt die erzeugten Karten wieder).</li>
  </ul>
  <h3>Template-Helfer</h3>
  <table class="doc-table">
    <tr><th>Helfer</th><th>Zweck</th></tr>
    <tr><td><code>e($v)</code></td><td>HTML-Escaping – für jede Ausgabe</td></tr>
    <tr><td><code>rich($html)</code>, <code>inline($html)</code></td><td>Rich-Text über Whitelist ausgeben</td></tr>
    <tr><td><code>setting('key')</code>, <code>filled($v)</code></td><td>Einstellung lesen; „befüllt und kein [Platzhalter]“</td></tr>
    <tr><td><code>url('/pfad')</code>, <code>link_href($link)</code>, <code>tel_href($nr)</code></td><td>URLs (Rewrite-sicher), Link-Felder, Telefon-Links</td></tr>
    <tr><td><code>fmt()-&gt;date($v)</code>, <code>-&gt;relative()</code>, <code>-&gt;number()</code>, <code>-&gt;bytes()</code> …</td><td>Werte formatieren in der Sprache der Seite (<code>Core\Format</code>) – Datum, Zahl, Betrag, Größe, Dauer, Telefon, Host, Auszug; siehe <a href="#format">Format</a>. <code>date_local($v, $stil)</code> und <code>phone_display()</code> bleiben als Kurzformen</td></tr>
    <tr><td><code>paragraphs($text)</code></td><td>Mehrzeiligen Text (ohne HTML) in Absätze <code>&lt;p&gt;</code> mit <code>&lt;br&gt;</code> umwandeln (maskiert)</td></tr>
    <tr><td><code>vcard_url()</code>, <code>vcard_entry_url($table, $entry)</code></td><td>Visitenkarte der Organisation bzw. einer Person (<code>.vcf</code>) oder <code>null</code> – siehe <a href="#vcard">Visitenkarte</a></td></tr>
    <tr><td><code>img($id, $sizes, $opt)</code></td><td><code>&lt;picture&gt;</code> mit AVIF/WebP-srcset, width/height, lazy</td></tr>
    <tr><td><code>theme_asset()</code>, <code>asset()</code></td><td>Asset-URL mit Cache-Busting</td></tr>
    <tr><td><code>$b-&gt;edit('pfad')</code>, <code>$b-&gt;central()</code></td><td>Inline-Editing bzw. Markierung „zentral gepflegt“ (nur im Editor); an den Datensatz gebundene Felder werden als <code>data-bound</code> gekennzeichnet und sind nicht inline bearbeitbar</td></tr>
    <tr><td><code>$b-&gt;targetEdit($link, $titel)</code>, <code>edit_link($ref, $titel)</code></td><td>„✎ Bearbeiten“ für das Ziel einer Karte/Kachel (Seite → Seiten-Editor, Eintrag → Seitenleiste) – nur für die Redaktion mit Recht, sonst leer. Als erstes Kind der Karte ausgeben, z. B. <code>&lt;li class="card"&gt;&lt;?= $b-&gt;targetEdit($it['link'], $it['title']) ?&gt;</code>; nimmt Link-Felder unverändert (<code>page:ID</code>, <code>entry:…</code>, Pfade). Im Editor: Karten-Links mit <code>::after</code> über der ganzen Karte und Hover-Effekte (Anheben, Neigen) unter <code>.is-editing</code> abschalten, damit Texte direkt bearbeitbar bleiben – siehe <a href="<?= e(url('/admin/hilfe/technik')) ?>#ziel-bearbeiten">Ziel bearbeiten</a></td></tr>
    <tr><td><code>app()-&gt;entry</code></td><td>Auf Detailseiten: <code>['table' =&gt; …, 'entry' =&gt; …]</code> des aufgerufenen Datensatzes</td></tr>
    <tr><td><code>$b-&gt;tune('anchor')</code>, <code>$b-&gt;variant()</code>, <code>$b-&gt;titleId()</code></td><td>Abschnitts-Optionen, Variante, ID für aria-labelledby</td></tr>
  </table>
  <h3>Aktuelle Blöcke im Kit „<?= e(app()->theme->label()) ?>“</h3>
  <p><?php foreach ($blocks as $type => $b): ?><code><?= e($type) ?></code> <?php endforeach; ?></p>
