<?php /** Entwicklerhandbuch · Live-Aktualisierung für Besucher (Core\Live) */ ?>
  <p class="lead">Ein zentraler Dienst für Inhalte, die sich bei Besuchern <b>ohne Neuladen</b> aktualisieren – über kurzlebige <b>Server-Sent Events</b>. Kern-Blöcke „Live-Galerie“ und „Live-Text (Ticker)“ nutzen ihn; Kits und Erweiterungen nutzen dieselbe Schnittstelle statt eigener Streams.</p>
  <table class="doc-table">
    <tr><th>Thema</th><th>Umsetzung</th></tr>
    <tr><td>Prinzip</td><td>Kanäle sind Namen mit einer <b>Version</b> (Zeitstempel in ms, steigt immer). Der Stream überträgt nur Versionen, nie Inhalte. Ändert sich eine Version, lädt der Browser den betroffenen Block neu. Versionen liegen als kleine Dateien in <code>{storage}/live/</code> (website-übergreifende Kanäle mit <code>g:</code> in <code>storage/live/</code>) – keine Datenbankabfrage je Sekunde und Besucher.</td></tr>
    <tr><td>Kanäle</td><td><code>data:{tabelle}</code> (automatisch bei Speichern, Status, Löschen, Sortieren – <code>Entries::changed</code>), <code>g:shared:{schlüssel}</code> (geteilte Tabelle, auf allen beteiligten Websites), <code>media:collection:{id}</code> (Hinzufügen, Entfernen, Hochladen in die Sammlung, Löschen), <code>page:{id}</code> (Veröffentlichen, Zurückziehen, Löschen – über <code>Extensions::emit</code>), eigene: <code>ext:{erweiterung}:…</code>.</td></tr>
    <tr><td>PHP</td><td><code>Live::touch('ext:shop:lager')</code> · <code>Live::version($kanal)</code> · <code>Live::attrs([$kanal, …], Live::blockSrc($b))</code> am Element · <code>Live::controls()</code> (Live-Punkt, Anhalten, Statuszeile) · <code>Live::assets()</code> einmal nach dem Element (live.js/live.css, nur wenn nötig, nie im Bearbeiten).</td></tr>
    <tr><td>Markup</td><td>Element mit <code>data-live</code> (signiertes Abo), <code>data-live-v</code> (Version beim Rendern), optional <code>data-live-src</code>. Darin die Liste <code>[data-live-list]</code> mit Einträgen <code>[data-live-id]</code> und <code>[data-live-status]</code> (<code>role="status"</code>). Ein Block, der nachgeladen werden darf, trägt <code>'live' => true</code> in seiner Definition.</td></tr>
    <tr><td>Browser</td><td><code>public/assets/js/live.js</code>: <b>eine</b> <code>EventSource</code> für alle Elemente der Seite (<code>GET /api/live?t=…&amp;t=…</code>, höchstens 20 Abos). Neuere Version → <code>data-live-src</code> holen (<code>GET /api/live/block?p=&amp;b=</code> → <code>{html}</code>, nur veröffentlichte Seiten und Blöcke mit <code>'live' => true</code>), <code>[data-live-list]</code> tauschen, neue <code>data-live-id</code> mit <code>is-live-new</code> markieren und ansagen. Ereignisse am Element: <code>cms:live</code> (jede neue Version, auch ohne <code>data-live-src</code> – für eigenes JavaScript) und <code>cms:live-updated</code> ({added}). Ausgeblendeter Tab: Verbindung nach 30 s zu. Seiten-Cache: die erste Nachricht enthält die aktuellen Versionen – zwischengespeicherte Seiten holen sich den neuen Stand sofort.</td></tr>
    <tr><td>Sicherheit</td><td>Abos sind mit HMAC (<code>app_key</code> + Website) signiert: Besucher können keine beliebigen Kanäle abfragen. Der Stream verrät nur Versionen; Inhalte kommen ausschließlich über den Block-Endpunkt (veröffentlichte Seite). CSP unverändert (<code>connect-src 'self'</code>).</td></tr>
    <tr><td>Barrierefreiheit</td><td>WCAG 2.2.2: „Anhalten“ je Element (<code>[data-live-pause]</code>, <code>aria-pressed</code>); angehaltene Elemente sammeln Änderungen und laden beim Fortsetzen. Neue Einträge werden höflich angesagt (<code>aria-live="polite"</code>), Bewegung nur ohne „Bewegung reduzieren“.</td></tr>
    <tr><td>Betrieb (Plesk/PHP-FPM)</td><td>Jeder offene Stream belegt einen PHP-Worker für höchstens <code>'live_stream_seconds'</code> (5–25, Standard 20), danach verbindet sich der Browser nach 2 s neu (<code>retry</code>). Gleichzeitig höchstens <code>'live_max_streams'</code> (Standard 16) je Installation (Dateisperren in <code>storage/live/slots/</code>); weitere Besucher bekommen sofort die Versionen und fragen nach 15 s erneut – die Website bleibt bedienbar, die Aktualisierung kommt etwas später. Faustregel: <code>pm.max_children</code> ≥ <code>live_max_streams</code> + offene Team-Chats + 10. <code>'live_transport' => 'poll'</code> schaltet Streams ganz ab (Nachfragen alle 8 s); der PHP-Entwicklungsserver nutzt das automatisch (außer mit <code>PHP_CLI_SERVER_WORKERS</code> &gt; 1).</td></tr>
    <tr><td>Prüfen</td><td><code>php bin/console live:selftest</code> (Versionen, Signaturen, Fälschungen, Live-Blöcke).</td></tr>
  </table>
