<?php /** Entwicklerhandbuch · Medien, Pools & Untertitel */ ?>
  <ul>
    <li><b>Upload in Stücken:</b> <code>POST /admin/media/chunk</code> (je 1 MB, Reihenfolge wird geprüft) → <code>/admin/media/finalize</code> (Alt-Text-Pflicht, Import oder Ersetzen per <code>replace_id</code>). Teil-Dateien liegen in <code>storage/uploads</code> und werden nach 24 h entfernt. Limit: <code>media.max_upload_mb</code>.</li>
    <li><b>Dateitypen:</b> JPG, PNG, WebP, GIF, SVG (bereinigt, siehe unten), PDF, MP4, MP3, M4A; <code>Media::kind()</code> = image | pdf | video | audio.</li>
    <li><b>SVG (<code>Core\Svg</code>, Funktion <code>media.svg</code>, Standard an):</b> eigener Bereiniger mit Positivliste auf <code>DOMDocument</code> (keine GPL-Bibliothek; enshrined/svg-sanitize ist GPL-2.0). <code>Media::process()</code> erkennt SVG (<code>Svg::detect</code>: finfo <code>image/svg+xml</code> oder <code>.svg</code> mit XML-Typ), ruft <code>Svg::clean()</code> und speichert nur das Ergebnis als <code>{Y}/{m}/{zufall}.svg</code>; <code>variants_json</code> = <code>{"svg": {in, out, unsafe}}</code> (Meldung <code>Svg::note()</code>, im JSON als <code>note</code>), keine Größen – <code>Media::url()</code> liefert für jede Breite/jedes Format die SVG, <code>picture()</code> ein <code>&lt;img&gt;</code> ohne <code>&lt;source&gt;</code>. Breite/Höhe aus der viewBox. Gilt für Verwaltung, REST, MCP und <code>content:import</code> (alle über <code>Media::import</code>); öffentliche Formulare und Externe Quellen nehmen weiter nur Pixelbilder an.
      <ul>
        <li><b>Einlesen:</b> höchstens 2 MB (<code>Svg::MAX_BYTES</code>), DOCTYPE wird entfernt (nur einfache interne Entities wie Illustrators <code>&amp;ns_svg;</code> werden einmalig eingesetzt; verschachtelte, Parameter- und externe Entities fallen weg), <code>LIBXML_NONET</code> ohne <code>NOENT</code>/<code>DTDLOAD</code>, höchstens 50 000 Knoten, Tiefe 200, <code>&lt;use&gt;</code>-Expansion höchstens 200 000 (use-Bomben, Kreisverweise → abgelehnt).</li>
        <li><b>Abgelehnt:</b> eingebettete Pixelbilder (<code>data:image/png|jpeg|gif|webp|…</code>, auch in CSS) und Schriften (<code>data:font/…</code>, <code>@font-face</code> mit <code>data:</code>) – SVG ist nur für Vektorgrafiken; ohne darstellbares Element nach dem Bereinigen; ohne viewBox und ohne feste width/height; <code>.svgz</code>.</li>
        <li><b>Neuaufbau nach Positivliste:</b> Elemente <code>svg g defs symbol use switch path rect circle ellipse line polyline polygon text tspan textPath linearGradient radialGradient stop clipPath mask pattern marker filter fe* (ohne feImage) title desc style</code>; <code>a</code> wird aufgelöst (Inhalt bleibt). Weg: <code>script</code>, <code>foreignObject</code>, <code>iframe</code>/<code>embed</code>/<code>object</code>, <code>image</code>/<code>feImage</code>, <code>handler</code>/<code>listener</code>, alle SMIL-Animationen (<code>animate*</code>, <code>set</code>, <code>mpath</code>), Metadaten, fremde Namensräume (Inkscape, Sodipodi, Illustrator <code>i:</code>, Sketch, Figma, Serif, RDF), Kommentare, Processing Instructions. Attribute: Darstellung, Geometrie, Verläufe/Filter, <code>id</code>/<code>class</code>, <code>viewBox</code>, <code>preserveAspectRatio</code>, <code>transform</code>, <code>role</code>, <code>aria-*</code>, <code>xml:space</code>/<code>xml:lang</code>; nie <code>on…</code>. <code>href</code>/<code>xlink:href</code> nur als lokales <code>#id</code> auf <code>use textPath linearGradient radialGradient pattern filter</code>. Werte mit <code>javascript:</code>, <code>data:</code>, <code>expression(</code>, <code>-moz-binding</code>, <code>behavior</code> oder <code>url()</code> außer <code>url(#id)</code> fallen weg.</li>
        <li><b>CSS</b> (<code>&lt;style&gt;</code> und <code>style=""</code>): nur bekannte Eigenschaften (SVG-Darstellung, Schrift, Transformation), Selektoren aus harmlosen Zeichen, <code>@media</code>/<code>@supports</code> eine Ebene; <code>@import</code>, <code>@font-face</code>, <code>@charset</code>, <code>@namespace</code>, <code>@keyframes</code>, Backslash-Escapes, <code>&lt; &gt; { } @</code> in Werten → weg.</li>
        <li><b>Optimieren:</b> ungenutzte Definitionen (Verläufe, Clip-Pfade, Masken, Filter, Marker, Symbole; mehrfach, wegen Verweisketten) und ids, leere <code>g</code>/<code>defs</code>, Gruppen ohne Attribute (nicht in <code>switch</code>), Leerraum; Zahlen in <code>d</code> (echter Pfad-Zerleger, Bogen-Flags bleiben), <code>points</code> und Koordinaten auf 3 Nachkommastellen (bei viewBox &lt; 10 mehr). <code>title</code>, <code>desc</code>, <code>aria-*</code> bleiben.</li>
        <li><b>Oberfläche:</b> Upload-Meldung mit Größe vorher/nachher und Anzahl unsicherer Elemente; Vorschau zeigt die SVG; kein Fokuspunkt, keine Zuschnitte (<code>setCrop</code> lehnt ab, <code>data-ratio</code> entfällt), kein Bildeditor (<code>ImageEdit::editable</code>). Alt-Text-Regeln wie bei Bildern. KI-Alt-Text: vor dem Upload im Browser gerastert, danach nur mit Imagick. Kein <code>og:image</code> aus SVG.</li>
        <li><b>App-Icons:</b> GD liest kein SVG – mit Imagick (SVG-Delegate) rastert <code>Svg::rasterize()</code> (Zeitlimit 15 s, ganz eingepasst, transparent), sonst meldet <code>AppIcons::generate()</code> einen Hinweis und die Einstellung zeigt ihn.</li>
        <li><b>Selbsttest:</b> <code>php bin/console svg:selftest [-v] [--dump=ordner]</code> – Schadcode-Proben (Skripte, Ereignisse, <code>javascript:</code>, externe Verweise, <code>foreignObject</code>, <code>@import</code>, CSS-<code>url()</code>, Entity-Bombe, XXE, <code>xml-stylesheet</code>, <code>data:text/html</code>, SMIL, use-Bombe, eingebettete Bilder/Schriften, &gt; 2 MB) und Exporte aus Illustrator, Inkscape, Figma.</li>
      </ul>
    </li>
    <li><b>Bilder:</b> GD kodiert neu (EXIF weg; WebP → JPEG, GIF → PNG), Größen aus <code>media.sizes</code> (480–2400 px) als WebP, AVIF bis 1600 px. Fokuspunkt → Klassen <code>fx{0-100} fy{0-100}</code> (10-%-Raster, CSP-konform ohne Inline-Styles).</li>
    <li><b>Zuschnitte je Format:</b> <code>Media::setCrop($id, '16:9', ['x','y','w','h'])</code> erzeugt eigene Größen; <code>Media::picture()</code> nutzt sie, wenn der Block <code>ratio</code> übergibt.</li>
    <li><b>Bild bearbeiten (zerstörungsfrei):</b> <code>Core\ImageEdit</code>, Spalte <code>media.edit_json</code> = <code>{"ops": {quad, quad_fit, flip_h, flip_v, rot, angle, fill, crop}, "orig": {w, h}, "master": "cache/…-e.jpg"}</code> (additiv per <code>Database::migrate</code>, auch in Pools). Reihenfolge <code>ImageEdit::OPS</code>: EXIF-Ausrichtung (beim Hochladen, alle 8 Werte) → Entzerren → Spiegeln → 90° → freie Drehung (größtes einbeschriebenes Rechteck oder <code>fill</code>) → Zuschnitt → Größen → CSS-Anpassung (<code>ImageFx</code>). <code>Media::setEdit($id, $ops|null)</code> rechnet aus dem unveränderten Original eine bearbeitete Fassung (<code>Media::url($m)</code> ohne Breite zeigt sie, <code>Media::originalUrl()</code> das Original) und neue Größen mit neuem Zufallsnamen (Cache-Busting), leert den Seiten-Cache, setzt Zuschnitte je Format zurück (sie beziehen sich danach auf die bearbeitete Fassung). Entzerren mit Imagick (<code>distortImage</code>, <code>DISTORTION_PERSPECTIVE</code>), sonst GD (eigene Projektion, bilinear, höchstens <code>media.edit_gd_max</code> = 2400 px, Zeitlimit <code>media.edit_timeout</code> = 45 s); Arbeitskopie höchstens <code>media.edit_max</code> = 3200 px und passend zum Speicherlimit. Endpunkt <code>POST /admin/api/media/{id}/edit</code> (<code>{edit}</code>, Pool-Verweise wirken im Pool), Oberfläche <code>resources/js/_imageedit.js</code> (Vorschau im Canvas mit derselben Rechnung). Selbsttest: <code>php bin/console media:selftest</code>. Nicht bearbeitbar: SVG, GIF, Videos (<code>ImageEdit::editable()</code>). Gilt je Datei, nicht je Einbindung.</li>
    <li><b>Ersetzen:</b> <code>Media::replace()</code> (nur gleiche Art) behält ID, Alt-Text, Tags, Sammlungen und Verwendungen; Zuschnitte werden zurückgesetzt, der Fokuspunkt auf Wunsch (Oberfläche: immer).</li>
    <li><b>Galerie, Slideshow, Stapelkarten:</b> <code>Core\MediaBlocks</code> (Kern-Blöcke, Lightbox, <code>public/assets/js/media.mjs</code>); Einbettungen: <code>Core\Embeds</code> holt Vorschaubilder von YouTube/Vimeo serverseitig nach <code>{media}/embeds</code>, Player erst nach Klick (youtube-nocookie bzw. Vimeo mit <code>dnt</code>).</li>
    <li><b>PDF:</b> Viewer <code>/pdf/{id}</code> mit Mozilla PDF.js (lokal, <code>public/assets/vendor/pdfjs</code>), eigene strenge CSP.</li>
    <li><b>Verwendung:</b> <code>Media::usages($id)</code> durchsucht Blöcke und Einstellungen.</li>
    <li><b>Prüf-Filter:</b> <code>Media::all()</code> kennt <code>noalt</code>, <code>missing_lang</code> (Bild ohne Alt-Text in dieser Sprache, <code>json_extract(i18n, '$."en".alt')</code>), <code>notitle</code>, <code>nocaptions</code>, <code>notranscript</code>; <code>Media::counts()</code> liefert die Anzahlen im Kontext Website bzw. Pool. REST <code>GET /api/v1/media?nocaptions=1</code> und MCP <code>list_media</code> nutzen dieselben Filter.</li>
  </ul>

  <h3 id="svg-server">SVG direkt ausliefern: Kopfzeilen am Webserver</h3>
  <p>Auf der Website erscheinen SVGs immer als <code>&lt;img&gt;</code> – dort laufen keine Skripte. Wer eine Datei direkt aufruft (<code>/media/…/x.svg</code>), bekommt sie aber als Dokument. Die Bereinigung ist die erste Sicherung, die Kopfzeilen die zweite:</p>
  <ul>
    <li><b>Apache</b> (auch Plesk „Apache &amp; nginx“, wenn Apache die Dateien ausliefert): Beim ersten SVG-Upload legt <code>Svg::guard()</code> im Medienordner (<code>public/media</code>, <code>public/sites/{website}/media</code>, <code>public/pools/{key}</code>) eine <code>.htaccess</code> an (braucht <code>mod_headers</code> und <code>AllowOverride FileInfo</code>).</li>
    <li><b>nginx</b> (liest keine <code>.htaccess</code>; bei Plesk auch, wenn „Statische Dateien direkt über nginx ausliefern“ an ist) – unter „Zusätzliche nginx-Anweisungen“:
      <pre><code>location ~* ^/(media|sites/[^/]+/media|pools)/.+\.svg$ {
    add_header Content-Security-Policy "<?= e(\Core\Svg::CSP) ?>" always;
    add_header X-Content-Type-Options "nosniff" always;
}</code></pre></li>
    <li>Prüfen: <code>curl -I https://example.org/media/2026/09/….svg</code> muss beide Kopfzeilen zeigen.</li>
  </ul>

  <h3 id="video-vorschau">Vorschaubilder für Videos (<code>Core\VideoThumbs</code>, <code>Core\Ffmpeg</code>)</h3>
  <p>Optional: nur mit ffmpeg + ffprobe auf dem Server. Ohne ffmpeg bleibt alles wie bisher (Platzhalter, kein Poster).</p>
  <table class="doc-table">
    <tr><td>Erkennung</td><td><code>Core\Ffmpeg::bin('ffmpeg'|'ffprobe')</code>, <code>::available()</code>, <code>::exec(array $argv, $timeout, $nice)</code> – <b>per Aufruf</b> (<code>{kandidat} -version</code>, Exit 0 und „ffmpeg version …“), nicht per <code>is_file</code>: so klappt es auch mit <code>open_basedir</code> (Plesk erlaubt meist nur den vhost und <code>/tmp</code>, Programme starten aber). Kandidaten: <code>ffmpeg_path</code>/<code>ffprobe_path</code> (Konfiguration), der Name über <code>PATH</code>, <code>/usr/bin</code>, <code>/usr/local/bin</code>, <code>/opt/homebrew/bin</code>, <code>storage/video/bin</code>; <code>'ffmpeg_search' =&gt; false</code> = nur der konfigurierte Pfad. Ergebnis 1 h in <code>storage/cache/ffmpeg.json</code> (nicht gefunden: 10 min); <code>health</code> und <code>media:thumbs</code> prüfen frisch. Unterprozesse: Argument-Array, keine Shell, stdin als Pipe (nicht <code>/dev/null</code> – das sperrt <code>open_basedir</code>), schlanke Umgebung. Die Erweiterung <code>video_tools</code> und <code>Core\AI\Transcriber</code> nutzen dieselbe Erkennung.</td></tr>
    <tr><td>Standbild</td><td>ffprobe liefert die Dauer; Zeitpunkt ≈ 10 % (mind. 1 s, höchstens 10 s), Filter <code>thumbnail=24</code> wählt das typischste von 24 Bildern; ist es fast schwarz (mittlere Helligkeit &lt; 24), bis zu zwei spätere Versuche (30 %, 60 %). Breite höchstens 1600 px, Größen aus <code>media.sizes</code> als WebP: <code>{Medienordner}/cache/{zufall}-v-{breite}.webp</code>, vermerkt in <code>variants_json['poster']</code> (<code>base</code>, <code>sizes</code>, <code>W</code>, <code>H</code>, <code>at</code>). Neuer Zufallsname je Erzeugung → Dateien unveränderlich (Server: <code>Cache-Control: public, max-age=31536000, immutable</code> für <code>/media/cache/</code> wie bei Bildgrößen). Ersetzen/Löschen der Datei entfernt sie; Pools: Datei und Vermerk liegen im Pool.</td></tr>
    <tr><td>Wann</td><td>Nach Upload/Import/Ersetzen nach der Antwort (<code>VideoThumbs::queue()</code>, <code>fastcgi_finish_request</code>); in der Verwaltung lazy: Raster, Liste, Mehrfachauswahl, Quick Look, Auswahldialog und Felder (<code>Fields::mediaPreview</code>) zeigen einen Platzhalter <code>[data-vthumb]</code>, den ein IntersectionObserver beim Sichtbarwerden anfragt (höchstens 2 Anfragen gleichzeitig): <code>GET /admin/api/media/{id}/thumb</code> (Anmeldung + <code>media.upload</code>, nur Videos der Mediathek bzw. des Pools, keine weiteren Parameter) → <code>{ok, thumb, large}</code> oder <code>{busy}</code> (später erneut). Die Website erzeugt <b>nie</b>: <code>Media::posterFor()</code> nutzt nur vorhandene Bilder.</td></tr>
    <tr><td>Grenzen</td><td>Sperre je Datei, höchstens <code>media.video_thumbs_parallel</code> (Standard 2) gleichzeitig installationsweit (Sperrdateien in <code>storage/cache/video-thumbs</code>), Zeitlimit <code>media.video_thumbs_timeout</code> (Standard 10 s), <code>nice 10</code>, <code>-threads 2</code>. Fehlschlag → Vermerk, neuer Versuch frühestens nach 6 h. Abschalten: <code>'media' =&gt; ['video_thumbs' =&gt; false]</code>.</td></tr>
    <tr><td>Vorrang</td><td><code>Media::posterFor($video)</code>: gewähltes Poster einer Erweiterung (<code>mediaPoster</code>, z. B. video_tools) &gt; automatisches Vorschaubild (Bild-Datensatz ohne ID, <code>_auto_poster</code>; nutzbar mit <code>Media::url()</code>, <code>Media::pictureOf()</code>) &gt; nichts. Ein im Block gewähltes Vorschaubild geht in den Kits ohnehin vor. <code>Media::toJson()</code> liefert für Videos <code>thumb</code>/<code>large</code>, <code>poster</code> (<code>chosen</code>|<code>auto</code>) und – nur solange keins da ist und ffmpeg läuft – <code>thumb_gen</code>.</td></tr>
    <tr><td>CLI</td><td><code>php bin/console media:thumbs [--missing] [--site=…]</code> erzeugt fehlende (auch kürzlich fehlgeschlagene), <code>--all</code> alle neu, <code>--pool=key</code> in einem Pool.</td></tr>
    <tr><td>Plesk</td><td>ffmpeg per Paketverwaltung (<code>apt install ffmpeg</code>, AlmaLinux: EPEL + RPM Fusion) oder statisches Build nach <code>storage/video/bin/</code> (<code>chmod 755</code>). <code>open_basedir</code> muss <code>/usr/bin</code> nicht enthalten. <code>proc_open</code> darf nicht in <code>disable_functions</code> stehen. <code>php bin/console health</code> zeigt „ffmpeg für Video-Vorschaubilder: gefunden/fehlt (optional)“ – nur Warnung. Hintergrund-Arbeiter (KI-Aufträge, video_tools) starten die PHP-Kommandozeile: <code>Stats::phpBinary()</code> prüft per Aufruf (mind. PHP 8.4) statt <code>is_executable</code>; sicherer ist <code>'php_cli' =&gt; '/opt/plesk/php/8.x/bin/php'</code> in <code>config.local.php</code>.</td></tr>
  </table>

  <h3 id="pools">Geteilte Medien (Pools)</h3>
  <p>Zentrale Mediatheken für mehrere Websites, z. B. Markenbilder einer Unternehmensgruppe. <code>php bin/console pool:create marke "Markenbilder"</code> legt <code>storage/pools/marke</code> (Datenbank) und <code>public/pools/marke</code> (Dateien) an; Websites nutzen ihn mit <code>'media_pools' =&gt; ['marke']</code>. In der Mediathek erscheint oben die Umschaltung „Diese Website | Markenbilder“. <b>Pflegen</b> (hochladen, löschen, Alt-Texte, Zuschnitte, Tags, Sammlungen) nur mit dem Recht <code>media.shared</code> („Geteilte Medien pflegen“, z. B. für eine Rolle „Chefredaktion“) <b>und</b> auf einer Website, die für den Pool zum Pflegen freigegeben ist: die Hauptwebsite immer, weitere unter „Pflegen dürfen“ (<code>pool.json → editors</code>), Integratoren überall (<code>MediaPools::canEdit()</code>). So bleibt der Admin einer Kunden-Website (Rolle mit allen Rechten) beim Verwenden; alle anderen sehen den Pool schreibgeschützt und <b>verwenden</b> die Dateien. Eine verwendete Pool-Datei bekommt auf der Website einen Verweis-Eintrag (<code>media.pool_ref</code>, eigene ID) – Blöcke, Felder und Kits funktionieren unverändert, Änderungen im Pool wirken sofort überall. <b>Vorhandene Dateien teilen:</b> In der Mediathek (Rechtsklick bzw. Mehrfachauswahl) „In „Pool“ verschieben (geteilt)“ – Dateien, Alt-Texte, Übersetzungen, Tags, Zuschnitte und Fokus wandern in den Pool, der Eintrag der Website wird zum Verweis; alle bisherigen Verwendungen bleiben gültig, nichts muss neu hochgeladen werden (<code>Media::shareToPool()</code>, Recht <code>media.shared</code>). Verwalten auch in der Oberfläche: <b>Grundeinstellungen → Geteilte Medien</b> (anlegen, umbenennen, Websites zuordnen, leere Pools löschen) – nur auf der Hauptwebsite (<code>network_site</code>) bzw. für Integratoren; die Zuordnung steht in <code>storage/pools/{key}/pool.json</code> und ergänzt <code>'media_pools'</code> aus der Konfiguration. Übersicht: <code>pool:list</code>. Beim Deploy liegt <code>public/pools</code> in <code>shared/</code>.</p>
  <p><b>Dateipfad bei Pool-Verweisen:</b> <code>Media::path($m)</code> liefert den absoluten Pfad der Originaldatei und beachtet <code>_pool</code> aus <code>Media::find()</code> (sonst den Medienordner der Website). Wer eine Datei auf der Platte liest (App-Icons, KI-Aufträge, eigene Erweiterungen), nimmt diese Methode statt <code>Media::dir() . '/' . $m['file']</code> – so entstehen z. B. Favicon und App-Icons auch aus einem Bild eines geteilten Pools.</p>
  <h3 id="untertitel">Untertitel, Kapitel &amp; Transkripte (<code>Core\MediaTracks</code>)</h3>
  <table class="doc-table">
    <tr><td>Daten</td><td>Tabelle <code>media_tracks</code> in der Datenbank der Datei (Website oder Pool – <code>MediaTracks::ctx()</code> folgt <code>pool_ref</code>): <code>kind</code> (subtitles | captions | descriptions | chapters), <code>lang</code>, <code>label</code>, <code>status</code> (draft | published), <code>source</code> (upload | editor | ai | translate), <code>vtt</code> (gesäuberter WebVTT-Inhalt), <code>cues</code>, <code>file</code>, <code>reviewed_by/_at</code>. Transkripte je Sprache in <code>media.transcripts</code> (JSON <code>{"de": {"text", "status", "source", "updated_at"}}</code>). Alles additiv (<code>Database::migrate</code>).</td></tr>
    <tr><td>Dateien</td><td>Nur <b>veröffentlichte</b> Spuren liegen öffentlich: <code>{Medienordner}/tracks/{id}-{lang}-{kind}.vtt</code> (Pools: <code>public/pools/{key}/tracks/</code>), Adresse mit <code>?v=</code>-Kennung. Entwürfe existieren nur in der Datenbank. Löschen der Datei löscht die Spuren; „In Pool verschieben“ nimmt sie mit. Webserver: <code>.vtt</code> als <code>text/vtt</code> ausliefern (nginx/Apache-Standard; sonst <code>AddType text/vtt .vtt</code> bzw. <code>types { text/vtt vtt; }</code>).</td></tr>
    <tr><td>Säubern</td><td><code>MediaTracks::parse()</code> liest WebVTT und SRT (UTF-8/UTF-16/Windows-1252), verwirft NOTE/STYLE/REGION; <code>cleanText()</code> erlaubt nur <code>b i u c v lang ruby rt</code> und Zeitmarken, Cue-Einstellungen nur <code>line position size align</code>; max. 2 MB, 5000 Cues, 500 Zeichen je Cue.</td></tr>
    <tr><td>Ausgabe</td><td><code>MediaTracks::trackTags($m)</code> → <code>&lt;track kind src srclang label default&gt;</code> (default = Sprache der Seite), <code>transcriptHtml($m)</code> → <code>&lt;details class="media-transcript"&gt;</code>, <code>player($m)</code> für Datei-Felder von Einträgen. Genutzt in <code>themes/{praxis,basis}/templates/partials/video-embed.php</code>. Das Hintergrundvideo des Hero ist dekorativ (stumm, <code>aria-hidden</code>) und bekommt keine Spuren. Suche: <code>Search\Documents</code> nimmt veröffentlichte Transkripte von Datei-Feldern (Blöcke und Einträge) in den Text der Seite auf.</td></tr>
    <tr><td>Dekorative Videos</td><td><code>media.decorative</code> gilt auch für Videos (Hintergrund-/Stimmungsvideo ohne Informationsgehalt): Prüf-Filter <code>nocaptions</code> (Mediathek, Übersicht, <code>/admin/ai/untertitel</code>, API/MCP) lässt sie aus. <code>MediaTracks::isDecorative($m)</code>; <code>player($m)</code> gibt dafür <code>decorativeVideo($m)</code> aus: <code>&lt;figure class="media-player media-player--decorative" data-hero-video-box&gt;</code> mit <code>&lt;video data-hero-video muted loop playsinline aria-hidden="true" tabindex="-1"&gt;</code> ohne <code>controls</code> und Spuren, dazu die beschriftete Pause-Schaltfläche <code>.hx-toggle[data-hero-video-toggle]</code> (WCAG 2.2.2, Skript <code>hero.mjs</code>: spielt nur sichtbar und ohne <code>prefers-reduced-motion</code>). <code>player($m, ['controls' =&gt; true])</code> erzwingt den normalen Player. <b>Kits</b> mit eigenem Markup (z. B. <code>partials/video-embed.php</code>) prüfen <code>!empty($m['decorative'])</code> bzw. <code>MediaTracks::isDecorative($m)</code> und geben dann <code>aria-hidden="true" tabindex="-1"</code> aus, lassen <code>controls</code>, <code>&lt;track&gt;</code> und Transkript weg und behalten bei Autoplay über 5 s eine beschriftete Pause-Schaltfläche – am einfachsten <code>MediaTracks::decorativeVideo($m, ['class' =&gt; '…'])</code> verwenden.</td></tr>
    <tr><td>Verwaltung</td><td><code>resources/js/_captions.js</code> (Finder rechts, Editor mit TextTrack-Vorschau ohne <code>blob:</code>), Endpunkte <code>/admin/api/media/{id}/tracks…</code>, <code>/transcript</code>, <code>/transcribe</code>, <code>/admin/api/media-jobs</code> (<code>MediaTrackController</code>). Ändern: <code>media.upload</code> bzw. <code>MediaPools::canEdit()</code>; KI zusätzlich <code>ai.use</code>. Funktion <code>media.captions</code> (Features) schaltet alles ab.</td></tr>
  </table>
