<?php /** Entwicklerhandbuch · Push-Benachrichtigungen (Core\Push) */ ?>
  <p>Funktion <code>push</code> (Standard aus, Kommunikation). Echte Web-Push-Mitteilungen nach <b>RFC 8030</b> (Zustellung), <b>RFC 8291</b> (Nachrichtenverschlüsselung, <code>aes128gcm</code> nach RFC 8188) und <b>RFC 8292</b> (VAPID) – <b>ohne zusätzliche Composer-Abhängigkeit</b>: <code>Core\Push\WebPush</code> nutzt nur PHP <code>openssl</code> (P-256-Schlüssel, ECDH über <code>openssl_pkey_derive</code>, ECDSA/ES256, AES-128-GCM), <code>hash_hkdf</code> und <code>curl_multi</code> (Rückfall: HTTPS-Streams). Der Selbsttest prüft die Verschlüsselung Byte für Byte gegen den Testvektor aus RFC 8291, Anhang A.</p>
  <table class="doc-table">
    <tr><th>Teil</th><th>Wo</th><th>Was</th></tr>
    <tr><td>VAPID-Schlüssel</td><td><code>Core\Push\Keys</code></td><td>Ein P-256-Paar je Installation in <code>config/config.local.php</code> (<code>push_vapid_public</code>, <code>push_vapid_private</code>, Base64url) – nie im Repository, nie in <code>config/sites/*.php</code> (wird dort ignoriert). Entsteht beim Einschalten der Funktion, über Grundeinstellungen → Push-Benachrichtigungen oder <code>push:keys --generate</code>. <code>push:keys --regenerate --force</code> erzeugt ein neues Paar: alle Abos werden ungültig (Fingerabdruck <code>key_fp</code> je Abo), Seiten-Caches werden geleert; die Verwaltung abonniert beim nächsten Besuch still neu, Besucher-Blöcke mit gemerkten Themen ebenso. Kontakt (<code>sub</code>): config <code>push_subject</code> (<code>mailto:</code>/<code>https:</code>), sonst Absender-Adresse der E-Mails, sonst die Website.</td></tr>
    <tr><td>Tabellen je Website</td><td><code>Push::ensureTable</code> (aus <code>Database::migrate</code>)</td><td><code>push_subscriptions</code> (Endpunkt + SHA-256 als eindeutiger Schlüssel, <code>p256dh</code>, <code>auth</code>, <code>key_fp</code>, <code>user_id</code> oder NULL, <code>topics</code> als „,data:aktuelles,“, <code>lang</code>, Gerätebezeichnung ohne Version, <code>failures</code>), <code>push_user_events</code> (Schalter je Person), <code>push_messages</code> (Inhalt, TTL, Urgency, Topic, Zähler), <code>push_queue</code> (eine Zeile je Gerät: queued → sent | failed | gone | expired).</td></tr>
    <tr><td>Versand</td><td><code>Push::process()</code></td><td>Sperre je Website (<code>storage/…/cache/push.lock</code>), Stapel zu 50, 8 gleichzeitig. 201 → gesendet; 404/410 → Abo gelöscht; 429/5xx/keine Verbindung → bis zu 5 Versuche mit wachsendem Abstand bzw. <code>Retry-After</code>; 400/401/403/413 → fehlgeschlagen, nach 5 Fehlversuchen in Folge wird das Abo gelöscht. Abgelaufene TTL → <code>expired</code>. Aufräumen: Zustellungen nach 14 Tagen, Nachrichten nach 90 Tagen, Abos mit altem Schlüssel. Nebenbei: <code>Push::kick()</code> sendet nach der Antwort (<code>fastcgi_finish_request</code>) bis zu 30 Zustellungen in 8 s; zuverlässig per Cron <code>push:send --all</code>.</td></tr>
    <tr><td>Service Worker</td><td><code>resources/sw/push.js</code> → <code>/push-sw.js</code></td><td>Eigener Worker mit Bereich <code>{base}/push-sw/</code> (steuert keine Seiten, speichert nichts) – unabhängig vom Offline-Worker <code>/sw.js</code> der installierten App, an den dieselben Handler angehängt werden. <code>push</code>: Mitteilung mit <code>title</code>, <code>body</code>, <code>icon</code>, <code>tag</code> (gleicher Tag ersetzt), <code>quiet</code> = Pfad der Verwaltung (nicht anzeigen, solange dort ein Fenster sichtbar ist – der Chat zeigt dann seine eigenen Hinweise). <code>notificationclick</code>: offenes Fenster mit derselben Adresse nach vorn, sonst neues Fenster – nur auf dem eigenen Ursprung (fremde Adressen werden auf den eigenen Ursprung umgeschrieben). <code>pushsubscriptionchange</code> → <code>/api/push/renew</code>.</td></tr>
    <tr><td>Öffentliche Schnittstelle</td><td><code>Core\Http\Controllers\PushController</code></td><td><code>POST /api/push/subscribe|unsubscribe|status|renew</code> – nur JSON, nur von der eigenen Website (<code>Origin</code>/<code>Sec-Fetch-Site</code>), signiertes Merkmal der Website (keine Sitzung, keine Cookies), Begrenzung je Anschluss (IP nur als HMAC): 20 neue Abos/h. Endpunkte nur <code>https</code> auf Port 443 bei bekannten Push-Diensten (<code>Push::HOSTS</code>: FCM, Mozilla, Apple, Microsoft; weitere: config <code>push_hosts</code>) – kein SSRF über erfundene Endpunkte. Änderungen am Abo nur mit Endpunkt <b>und</b> Auth-Geheimnis. Themen nur für Tabellen mit Abo.</td></tr>
    <tr><td>Verwaltung</td><td><code>Admin\PushController</code>, <code>account/_push.php</code>, <code>system/_push.php</code>, <code>resources/js/_push.js</code></td><td>Konto → Benachrichtigungen (Gerät, Ereignisse, Geräte, Test), Grundeinstellungen → Push-Benachrichtigungen (Status, Schlüssel anlegen, Test, Datenschutz-Vorschlag). Einmal am Tag frischt jede Verwaltungsseite das Abo des Geräts auf (nur solange es noch zur Person gehört).</td></tr>
  </table>
  <h3>Ereignisse der Verwaltung</h3>
  <p>Kern: <code>requests.new</code> (Recht <code>requests.read</code> je Eingang, ohne Inhalte; aus <code>DataForms::submit</code>, nicht bei <code>notify =&gt; false</code>), <code>forms.entry</code> (<code>data.edit</code>), <code>chat.direct</code>/<code>chat.mention</code> (aus <code>Messages::send</code>; Empfänger dieser Website und Netzwerk-Konten mit Konto auf dieser Website), <code>review.pending</code> (<code>review.manage</code>, aus <code>Review\Queue::run</code>). Inhalte entstehen je Sprache der Empfänger (Callable als Inhalt).</p>
  <pre><code>// Erweiterung: Ereignis anmelden (erscheint unter Konto → Benachrichtigungen bei allen mit dem Recht)
$x-&gt;pushEvent('freigabe.feedback', 'Neues Feedback zu Entwürfen', 'freigabe.view', ['help' =&gt; 'Kommentare von Kunden auf Freigabe-Links']);

// … und senden (Liste von Benutzer-IDs, ein Recht oder ['perm' =&gt; …, 'table' =&gt; …]); wirft nie, 0 = nichts zu tun
\Core\Push\Push::notifyUsers('freigabe.view', fn() =&gt; [
    'title' =&gt; __('Neues Feedback'), 'body' =&gt; $seite['title'], 'url' =&gt; '/admin/freigabe/' . $id, 'tag' =&gt; 'freigabe-' . $id,
], 'freigabe.feedback', ['except' =&gt; $autorId, 'ttl' =&gt; 86400, 'collapse' =&gt; 'freigabe']);

// Thema (Besucher): \Core\Push\Push::notifyTopic('data:aktuelles', [...], 'data.published', ['lang' =&gt; 'en'])</code></pre>
  <p>Inhalt (<code>Push::payload</code>): nur <code>title</code> (120), <code>body</code> (240), <code>url</code> (absolut, Pfade wie <code>/admin/…</code> werden umgesetzt), <code>tag</code>, <code>icon</code> (App-Icon), <code>quiet</code>, <code>lang</code>; ohne HTML und ohne Redaktionsnotizen <code>[# … #]</code>, höchstens 3000 Byte. Grenzen: 30 Nachrichten je Gerät in 10 Minuten, 10 je Thema und Stunde (config <code>push_topic_per_hour</code>).</p>
  <h3>Besucher: Abo neuer Einträge</h3>
  <p>Einstellung je Inhaltstabelle <code>settings.push</code> (<code>Core\Push\Topics</code>): <code>enabled</code>, <code>title</code> (Platzhalter <code>{title} {table} {site} {feldname}</code>), <code>body</code> (Feld, leer = Beschreibungsfeld, <code>-</code> = keiner), <code>filter</code> (<code>field</code>/<code>value</code>, auch Mehrfachauswahl und Ja/Nein). Thema <code>data:{kurzname}</code>. Gesendet wird beim <b>ersten</b> Veröffentlichen (<code>published_at</code> war leer) in <code>Entries::save</code> und <code>Entries::setStatus</code> – nicht beim Abgleich externer Quellen, nicht für geschützte Tabellen ohne öffentliche Freigabe (<code>PageAccess::filterEntries</code>), nur an Abos in der Sprache des Eintrags. Zeitgesteuertes Veröffentlichen kennt der Core nicht. Ausgabe: Block <code>push_subscribe</code> bzw. <code>push_subscribe('aktuelles', ['layout' =&gt; 'inline'])</code> im Kit (<code>Core\Push\Visitor</code>), Stylesheet <code>resources/css/push.css</code> (Variablen <code>--push-bg</code>, <code>--push-line</code>, <code>--push-radius</code>, <code>--push-accent</code>, <code>--push-muted</code>, <code>--push-pad</code>, sonst <code>--kit-*</code>; Kit kann <code>css/push.css</code> mitbringen), Skript <code>resources/js/push.js</code> (Zustand <code>data-state</code>: on, off, busy, denied, error, ios, na). Für alle gleich (Seiten-Cache). iPhone/iPad: nur in der installierten Web-App (Funktion <code>pwa</code>, <code>display: standalone</code>) – der Block zeigt dort einen Hinweis.</p>
  <h3>Umgebung, Betrieb, Datenschutz</h3>
  <ul>
    <li><code>environment</code> <b>staging</b>: keine Nachrichten an Besucher (config <code>push_staging_visitors =&gt; true</code> erlaubt sie); die Redaktion erhält ihre Mitteilungen. Abos aus einer eingespielten Live-Sicherung tragen den Schlüssel-Fingerabdruck der Live-Installation und werden nie beliefert (und beim Aufräumen gelöscht).</li>
    <li>Cron: <code>* * * * * cd /pfad/zur/installation &amp;&amp; php bin/console push:send --all</code> (jede Minute bis alle 5 min). Stand: <code>push:status [--all]</code>, Grundeinstellungen → Push-Benachrichtigungen, <code>health</code> (Hinweis bei liegengebliebener Warteschlange).</li>
    <li>Kommandozeile: <code>push:send</code>, <code>push:status</code>, <code>push:keys [--generate|--regenerate --force]</code>, <code>push:test &lt;email&gt;</code>, <code>push:selftest</code>.</li>
    <li>Datenschutz: gespeichert werden Endpunkt, Schlüssel, Themen, Sprache und eine Gerätebezeichnung ohne Versionsnummern – keine IP-Adresse, keine Cookies. Vorschlag für die Datenschutzerklärung: <code>Push::privacyText()</code> (Grundeinstellungen → Push-Benachrichtigungen).</li>
  </ul>
