<?php /** Entwicklerhandbuch · Rollen, Rechte & Zwei-Faktor */ ?>
  <p>Rollen stehen in der Tabelle <code>roles</code> (<code>rkey</code>, name, description, <code>permissions_json</code>, <code>tables_json</code>, builtin) und werden unter <b>Benutzer &amp; Rollen</b> gepflegt. <code>Permissions::seed()</code> legt fehlende Standardrollen bei jeder Migration an: <b>Administration</b> (<code>admin</code>, <code>*</code>), <b>Netzwerk-Administration</b> (<code>network</code>, <code>*</code>, nur für zentrale Konten, nicht vergebbar), <b>Redaktion</b> (<code>editor</code>), <b>Autorin/Autor</b> (<code>author</code>: Seiten bearbeiten, Medien hochladen, Einträge bearbeiten – nur Entwürfe) und <b>Anfragen bearbeiten</b> (<code>requests</code>). Eine abgeschaltete Funktion (siehe <a href="#funktionen">Funktionsumfang</a>) sperrt ihre Rechte für alle Rollen.</p>
  <table class="doc-table">
    <tr><th>Recht</th><th>Erlaubt</th></tr>
    <?php foreach (\Core\Permissions::catalog() as $group => $items): foreach ($items as $k => $l): ?><tr><td><code><?= e($k) ?></code></td><td><?= e($group) ?> – <?= e($l) ?></td></tr><?php endforeach; endforeach; ?>
  </table>
  <ul>
    <li><b><code>system.features</code></b> („Haupt-Admin“): Funktionen und Erweiterungen der Website unter <b>Administration → Einstellungen → Funktionen &amp; Erweiterungen</b> schalten (<a href="#funktionen">Funktionsumfang</a>). Einzel-Installation: wirkt für jede Rolle, die es hat (Administration über <code>*</code>). Netzwerk-Installation (mehrere Websites): wirkt nur, wenn die Netzwerk-Administration es für die Website freigibt (<code>sys.features_delegate</code>); Netzwerk-Konten und Integratoren dürfen immer.</li>
    <li><b>Datentabellen</b> lassen sich je Rolle einschränken (<code>tables_json</code> = Liste der Kurznamen, <code>NULL</code> = alle); gilt für <code>data.edit/publish/delete</code> und für <code>requests.read/manage</code> (Eingangs-Tabellen – z. B. eine Rolle nur für „Rezeptanfragen“).</li>
    <li>Ohne <code>pages.publish</code> bzw. <code>data.publish</code> wird nur als Entwurf gespeichert; veröffentlichte Einträge bleiben dann unveränderbar.</li>
    <li>Einmalige Ergänzungen bestehender Rollen: <code>support.report</code> für alle und <code>support.answer</code> für die Redaktion (<code>sys.support_roles</code>), <code>ai.use</code> für die Redaktion (<code>sys.ai_roles</code>). <code>review.manage</code> hat standardmäßig nur, wer <code>*</code> hat.</li>
    <li>Im Code: <code>can('pages.publish')</code>, <code>can('data.edit', 'aktuelles')</code>; in Admin-Controllern <code>$this-&gt;auth($r, 'media.delete')</code>. Navigation, Werkzeugleiste, Spotlight, API und MCP blenden aus, was die Rolle nicht darf. Erweiterungen melden eigene Rechte mit <code>$x-&gt;permissions()</code> an.</li>
    <li>API-/MCP-Tokens gehören zu einem Benutzer, haben zusätzlich ihre eigene Stufe (read / write) und werden unter <b>API &amp; MCP</b> vergeben (Recht <code>api.manage</code>).</li>
  </ul>
  <h3 id="zwei-faktor">Zwei-Faktor-Anmeldung</h3>
  <ul>
    <li><code>Core\Totp</code>: RFC 6238 (SHA-1, 6 Stellen, 30 s, ±1 Schritt), eigener Code; QR-Code lokal erzeugt (<code>chillerlan/php-qrcode</code>, SVG als <code>data:</code>-Bild, CSP-tauglich). Geheimnis mit libsodium (secretbox) verschlüsselt, Schlüssel aus dem <code>app_key</code> der Website, zu der das Konto gehört; derselbe Code wird nicht zweimal angenommen (<code>totp_last</code>); 10 Wiederherstellungscodes (80 Bit, nur SHA-256-Hashes, je einmal gültig, neu erzeugbar).</li>
    <li>Einrichtung unter <b>Konto → Zwei-Faktor-Anmeldung</b> (<code>/admin/account/2fa</code>). Pflicht für <code>network</code> und für Rollen, die eine Website unter „Benutzer &amp; Rollen → Anmeldung &amp; Sicherheit“ auf „verlangt“ oder „nur Passkey“ stellt (<code>sys.auth_policy</code>, siehe <a href="#passkeys">Passkeys</a>) – die nächste Anmeldung führt dann zur Einrichtung (bzw. erinnert während einer Übergangsfrist). Kein „Gerät merken“.</li>
    <li>Zurücksetzen (App-Code <em>und</em> alle Passkeys): die Person selbst (Konto); für lokale Konten anderer Personen „2FA zurücksetzen“ in <b>Benutzer &amp; Rollen</b> (Recht <code>users.manage</code>, mit Rückfrage, nicht für das eigene Konto) oder <code>php bin/console user:2fa-reset &lt;email&gt; [--site=key]</code> (<code>Totp::reset()</code>: Geheimnis und Wiederherstellungscodes gelöscht, <code>auth_ver</code> steigt → alle Sitzungen enden; verlangt die Rolle 2FA, wird sie bei der nächsten Anmeldung neu eingerichtet; protokolliert im Netzwerk-Protokoll als <code>user.reset-2fa</code>). Netzwerk-Konten: Netzwerk-Übersicht bzw. <code>network:user --reset-2fa</code> (löscht die Passkeys aller Domains).</li>
  </ul>
  <h3 id="passkeys">Passkeys (WebAuthn)</h3>
  <ul>
    <li><b>Bibliothek:</b> <code>lbuchs/webauthn</code> 2.x (MIT, ohne weitere Abhängigkeiten, braucht <code>ext-openssl</code>) für CBOR/COSE und die Attestierungsformate. Gewählt statt <code>web-auth/webauthn-lib</code> (MIT, zieht Symfony Serializer, PSR-Pakete, CBOR-/COSE-Bibliotheken nach). Die Zeremonie selbst prüft <code>Core\Passkeys</code>: Challenge (32 Byte, Sitzung, 5 min, einmalig, je Zweck <code>reg</code>/<code>login</code>/<code>2fa</code>), <code>type</code>, <b>exakte Herkunft</b> (Schema + Host + Port der Anfrage; die Bibliothek prüft nur ein Domain-Suffix), <code>crossOrigin</code>, RP-ID-Hash, Flags UP/UV, Signatur (ES256/RS256 über OpenSSL, EdDSA über libsodium) und Signaturzähler (kein Rückschritt, sonst abgelehnt).</li>
    <li><b>RP-ID</b> = Host der aufgerufenen Adresse ohne Port – jede Website hat ihre eigene Domain, Passkeys gelten je Domain (auch <code>www.</code> und ohne <code>www.</code> sind verschiedene RP-IDs). Nur unter einem Domainnamen mit HTTPS bzw. <code>localhost</code>/<code>*.localhost</code>; unter einer IP-Adresse (z. B. <code>127.0.0.1</code>) blendet die Verwaltung Passkeys aus.</li>
    <li><b>Registrierung</b> (<b>Konto → Passkeys</b>): <code>POST /admin/account/passkeys/options</code> → <code>navigator.credentials.create()</code> → <code>POST /admin/account/passkeys</code> (JSON, CSRF-Header). <code>residentKey: required</code> (auffindbar – nötig für die Anmeldung ohne Passwort), <code>userVerification: preferred</code>, <code>attestation: none</code>, <code>excludeCredentials</code> (kein zweiter Passkey desselben Authenticators). Benutzerkennung = HMAC aus <code>app_key</code> und Konto (keine E-Mail, keine fortlaufende ID). Hinzufügen und Löschen nur innerhalb von 15 min nach Anmeldung bzw. Passwort-Bestätigung (<code>/admin/account/reauth</code>). Der erste zweite Faktor beendet alle anderen Sitzungen (<code>auth_ver</code>) und erzeugt 10 Wiederherstellungscodes (dieselben wie bei TOTP); Löschen beendet ebenfalls die anderen Sitzungen.</li>
    <li><b>Tabelle <code>user_passkeys</code></b> (in der Datenbank, zu der das Konto gehört): <code>user_id</code>, <code>rp_id</code>, <code>cred_hash</code> (SHA-256 der Kennung, eindeutig), <code>credential_id</code> (base64url), <code>public_key</code> (PEM), <code>sign_count</code>, <code>transports</code>, <code>aaguid</code> (Namensvorschlag für bekannte Anbieter), <code>name</code>, <code>uv</code>, <code>backup</code> (synchronisierbar), <code>created_at</code>, <code>last_used_at</code>. Neue Spalte <code>users.mfa_last</code> (zuletzt verwendeter zweiter Faktor – wird im zweiten Schritt zuerst angeboten).</li>
    <li><b>Zweiter Faktor</b> nach dem Passwort: <code>/admin/login/2fa</code> bietet Passkey (<code>allowCredentials</code> = Passkeys des Kontos für diese Domain, <code>userVerification: preferred</code>) und/oder App-Code an; Wiederherstellungscodes gehen immer. Gleiche Begrenzung wie der Code: 5 Versuche je Anmeldung, 10/15 min je IP, Netzwerk-Konten zusätzlich 10/15 min je Konto.</li>
    <li><b>Ohne Passwort</b>: Anmeldeseite mit „Mit Passkey anmelden“ und Autofill (<code>autocomplete="username webauthn"</code>, <code>mediation: "conditional"</code> – nur mit JavaScript und passkey-fähigem Browser sichtbar). <code>userVerification: required</code>, das UV-Flag wird geprüft und <code>userHandle</code> muss zur Kennung des Kontos passen. Gilt als starke Anmeldung (Besitz + Biometrie/PIN) und erfüllt jede 2FA-Pflicht. Begrenzung wie die Passwort-Anmeldung (8 Fehlversuche/15 min je IP). Gesucht wird zuerst unter den lokalen Konten, dann (andere Websites) unter den Netzwerk-Konten mit Passkey für diese Domain.</li>
    <li><b>Anmelde-Richtlinie</b> (<code>Core\Mfa</code>, <b>Benutzer &amp; Rollen → Anmeldung &amp; Sicherheit</b>, Recht <code>users.manage</code>, Einstellung <code>sys.auth_policy</code>): erlaubte Verfahren (App, Passkeys, ohne Passwort), je Rolle „freiwillig“ / „verlangt (App oder Passkey)“ / „nur Passkey“, Übergangsfrist in Tagen (0 = sofort; sonst einmal je Anmeldung Erinnerung mit „Später erinnern“ bis Fristende, gerechnet ab Aktivierung der Pflicht für die Rolle bzw. Anlage des Kontos). <code>sys.twofa_roles</code> wird mitgepflegt und ohne neue Einstellung weiter gelesen. Eingerichtete Verfahren werden immer abgefragt; ein abgeschaltetes Verfahren wird nicht mehr angeboten, solange ein erlaubtes eingerichtet ist, und erfüllt keine Pflicht. Änderungen stehen im Netzwerk-Protokoll (<code>auth.policy</code>, <code>passkey.add</code>, <code>passkey.remove</code>).</li>
    <li><b>Netzwerk-Konten</b>: Richtlinie der Netzwerk-Website (<code>sys.net_auth</code>, Netzwerk-Übersicht → Netzwerk-Administratoren → „Anmelde-Richtlinie“). Immer starker zweiter Faktor – TOTP oder Passkey, mit „Nur Passkey“ nur Passkey – für die direkte Anmeldung und für <code>/admin/sso</code>. Passkeys liegen in der Netzwerk-Datenbank, eine Zeile je Domain: für die direkte Anmeldung auf einer anderen Website braucht das Konto dort einen eigenen Passkey (hinzufügen unter <b>Konto</b> auf dieser Website); über „Öffnen“ (SSO) ist keiner nötig.</li>
  </ul>
  <h3>Anmeldung &amp; Sitzung</h3>
  <p>Passwörter mit <code>password_hash()</code>, mindestens 12 Zeichen. Anmeldung (Passwort oder Passkey ohne Passwort): 8 Fehlversuche je 15 min und IP (HMAC) je Website. Sitzung: Cookie <code>cms_sess</code> bzw. <code>cms_sess_{key}</code> (HttpOnly, Secure unter HTTPS, SameSite=Lax, strict mode), Leerlauf 8 h, absolut 12 h, neue Session-ID nach der Anmeldung; die Sitzung ist an den Schlüssel der Website gebunden, ein kopiertes Cookie gilt auf keiner anderen Website.</p>
