<?php /** Entwicklerhandbuch · Sicherheit & Datenschutz */ ?>
  <table class="doc-table">
    <tr><th>Thema</th><th>Umsetzung</th></tr>
    <tr><td>Webroot</td><td>Nur <code>public/</code> mit <code>index.php</code> und statischen Dateien. Kein <code>.htaccess</code> nötig; Konfiguration, Datenbanken und Code liegen außerhalb.</td></tr>
    <tr><td>HTTP-Header</td><td>Immer: <code>X-Content-Type-Options: nosniff</code>, <code>Referrer-Policy: strict-origin-when-cross-origin</code>, <code>X-Frame-Options: SAMEORIGIN</code>, <code>Permissions-Policy: camera=(), microphone=(), geolocation=(), interest-cohort=()</code>. HSTS setzt der Webserver (Plesk: „HSTS“).</td></tr>
    <tr><td>CSP Website</td><td><code>default-src 'self'; img-src 'self' data: blob:; font-src 'self'; style-src 'self'; script-src 'self'; connect-src 'self'; worker-src 'self' blob:; frame-src 'self' https://www.youtube-nocookie.com https://player.vimeo.com; media-src 'self'; object-src 'none'; base-uri 'self'; form-action 'self' https:; frame-ancestors 'self'</code> – ohne <code>unsafe-inline</code> für Besucher; <code>frame-src</code> ergänzt um <code>frame_hosts</code> des Kits. Erweiterungen ergänzen einzelne Hosts je Anfrage (<code>Extension::csp()</code>) – z. B. Consent-Kit: Hosts eines Dienstes erst nach Einwilligung, iframe-Hosts aktiver Dienste für den 2-Klick-Platzhalter. Angemeldete erhalten <code>style-src 'self' 'unsafe-inline'</code> (Editor).</td></tr>
    <tr><td>CSP Verwaltung &amp; Sonstiges</td><td>Verwaltung: <code>default-src 'self'; img-src 'self' data: blob:; style-src 'self' 'unsafe-inline'; script-src 'self'; worker-src 'self' blob:; frame-ancestors 'self'; form-action 'self'; base-uri 'self'; object-src 'none'</code>. API/Suchvorschläge: <code>default-src 'none'; frame-ancestors 'none'</code>. PDF-Viewer mit eigener CSP (zusätzlich <code>'wasm-unsafe-eval'</code>), Support-Anhänge mit <code>sandbox</code>.</td></tr>
    <tr><td>Verwaltung</td><td><code>password_hash()</code>, mindestens 12 Zeichen, Login-Rate-Limit, neue Session-ID nach Anmeldung, CSRF-Token (<code>_csrf</code> bzw. Header <code>X-CSRF-Token</code>) auf allen schreibenden Anfragen der Verwaltung, Cookie HttpOnly/Secure/SameSite=Lax, Leerlauf 8 h, absolut 12 h, Rollen und Rechte, Zwei-Faktor-Anmeldung (siehe <a href="#rechte">Rollen &amp; Rechte</a>).</td></tr>
    <tr><td>API/MCP</td><td>Bearer-Tokens (<code>cms_</code> + 48 Hex, nur SHA-256-Hash gespeichert), read/write, Ablaufdatum, Modus „Zur Freigabe“, Rate-Limit, Origin-Prüfung (MCP), keine Cookies, keine Klartext-Inhalte aus Eingängen.</td></tr>
    <tr><td>Besucher</td><td>Ab Werk keine Cookies, keine Tracker, keine CDNs (einwilligungspflichtige Dienste nur über das Consent Kit, siehe Erweiterungen); Schriften lokal. Karten und Video-Vorschaubilder laufen über den eigenen <a href="#karten">Proxy</a> (keine IP-Übertragung an Dritte); YouTube/Vimeo-Player erst nach Klick (youtube-nocookie).</td></tr>
    <tr><td>Uploads</td><td>Positivliste JPG, PNG, WebP, GIF, PDF, MP4, MP3, M4A mit MIME-Prüfung (finfo) und Kopfprüfung für PDF/MP4/MP3/M4A; SVG nur über den eigenen Bereiniger <code>Core\Svg</code> (Positivliste, keine Skripte/Ereignisse/externen Verweise/eingebetteten Bilder, Entity- und use-Bomben abgelehnt; gespeichert wird nur das Ergebnis; abschaltbar per Funktion <code>media.svg</code>; Kopfzeilen für direkt aufgerufene SVGs siehe Medien). Zufallsnamen mit fester Endung; Bilder via GD neu kodiert (JPEG bzw. PNG, EXIF/GPS entfernt, höchstens 60 Megapixel, Original auf 3200 px begrenzt; animierte GIFs verlieren die Animation). Upload in 1-MB-Stücken (<code>/admin/media/chunk</code> → <code>/finalize</code>) unter <code>storage/uploads</code>, verwaiste Teile nach 24 h gelöscht.</td></tr>
    <tr><td>Eingänge (z. B. Art. 9 DSGVO)</td><td>libsodium <code>crypto_box_seal</code> (X25519 + XSalsa20-Poly1305) je Eintrag; nur der öffentliche Schlüssel liegt auf dem Server, der geheime wird zum Lesen eingegeben (POST, nie gespeichert). Keine Feldspalten, keine Uploads, keine Ausgabe auf der Website, API/MCP nur Metadaten. Jedes Entschlüsseln/Ändern/Löschen im Protokoll <code>inbox_log</code> (ohne Inhalte, IP als HMAC). Automatisches Löschen erledigter Anfragen, Benachrichtigung ohne Inhalte. Details: <a href="#formulare">Formulare &amp; Eingänge</a>.</td></tr>
    <tr><td>Formulare für Datentabellen</td><td>Feste Feldliste, Prüfung wie in der Verwaltung, Datenschutz-Bestätigung, Uploads optional mit Typ-/Größenprüfung, Benachrichtigung ohne Inhalte; Inhaltstabellen speichern <b>unverschlüsselt</b> – für Gesundheitsdaten einen Eingang nutzen.</td></tr>
    <tr><td>Spamschutz</td><td>Honeypot · HMAC-signiertes Zeit-Token (Mindestzeit 4 s, gültig 3 h, Einmalverwendung) · optional Proof-of-Work SHA-256 im Browser (<code>sys.spam_pow</code>) · Rate-Limit je IP-Hash (Standard 5/h) und global (60/h) · Link-/Sperrwortfilter · Log <code>{storage}/logs/spam.log</code>. Bots erhalten eine vorgetäuschte Erfolgsmeldung.</td></tr>
    <tr><td>Rich-Text</td><td>DOM-basierte Whitelist (<code>Core\Sanitizer</code>): Tags p, ul/ol/li, h2–h4, blockquote, b, i, a, br, mark, sup, sub, span; Klassen nur <code>t-lead|t-small|t-note</code> (p), <code>c-accent|c-muted|c-success|c-warning|c-danger</code> (span), <code>check</code> (ul); nie <code>style</code>/<code>on…</code>. <code>href</code> nur https/mailto/tel/#/intern, <code>target="_blank"</code> nur mit <code>rel="noopener"</code>, <code>data-link</code> nur als Verweis (<code>page:</code>/<code>entry:</code>/<code>media:</code>), <code>title</code> als Text. Support-Texte als Markdown-lite, nie HTML.</td></tr>
    <tr><td>Datenbank</td><td>Werte ausschließlich über Prepared Statements; Tabellen- und Feldnamen auf <code>[a-z][a-z0-9_]</code> beschränkt; Schema-Änderungen über Doctrine DBAL.</td></tr>
    <tr><td>Geheimnisse</td><td><code>app_key</code>/<code>setup_token</code> je Website, <code>network_key</code> nur in <code>config.local.php</code>; 2FA-Geheimnisse verschlüsselt; KI-Anbieter-Schlüssel in <code>storage/ai/config.json</code> (Dateirechte 0600) oder in der Konfiguration. Das SMTP-Passwort (<code>sys.mail_pass</code>) liegt verschlüsselt in der Datenbank der Website (libsodium secretbox, Schlüssel aus dem <code>app_key</code>, Präfix <code>enc1:</code>; <code>Settings::SECRETS</code>), wird nie an die Oberfläche ausgegeben (Feld „leer = unverändert“) und nur beim Versand entschlüsselt. Ältere Klartext-Werte stellt <code>migrate</code> bzw. das nächste Speichern der Grundeinstellungen um. Eine Sicherung, die auf einer Website mit anderem <code>app_key</code> eingespielt wird, verliert das SMTP-Passwort (neu eintragen).</td></tr>
    <tr><td>KI</td><td>Externe Anbieter nur per https, Hosts per Positivliste ohne Weiterleitungen (<code>GuardedHttpClient</code>); gezählt werden nur Aufrufe, Tokens, Dauer und Fehler – nie Inhalte. Siehe <a href="#ki"><?= e($aiBrand) ?></a>.</td></tr>
  </table>
  <h3>Rate-Limits</h3>
  <div class="doc-scroll"><table class="doc-table">
    <tr><th>Bereich</th><th>Grenze</th></tr>
    <tr><td>API/MCP je Token</td><td><?= \Core\Api\Tokens::RATE_LIMIT ?> Anfragen je <?= \Core\Api\Tokens::RATE_WINDOW / 60 ?> Minuten (HTTP 429)</td></tr>
    <tr><td>Anmeldung</td><td>8 Fehlversuche/15 min je IP; Netzwerk-Konten zusätzlich 10/15 min je Konto; 2FA (Code oder Passkey) 5 Versuche je Anmeldung, 10/15 min je IP; Passkey ohne Passwort zählt wie ein Passwort-Versuch</td></tr>
    <tr><td>Netzwerk-SSO</td><td>30 Tokens/10 min je Konto, 20 Fehlversuche/10 min je IP</td></tr>
    <tr><td>Formulare</td><td>5/h je IP, 60/h gesamt (einstellbar unter Grundeinstellungen → Spamschutz)</td></tr>
    <tr><td>Website-Suche</td><td>60 Ergebnisseiten/min, 20 semantische Suchen/min (danach nur Stichwort), 120 Vorschläge/min je IP</td></tr>
    <tr><td>Proxy (Nachladen beim Anbieter)</td><td>2000 je 10 min je Besucher</td></tr>
    <tr><td>Geokodierung</td><td>1 Anfrage/s (Nominatim-Regeln)</td></tr>
    <tr><td>CalDAV/CardDAV</td><td>20 Fehlversuche/15 min je IP</td></tr>
  </table></div>
  <p>IP-Adressen werden für Rate-Limits nur als HMAC mit dem <code>app_key</code> gespeichert (Tabelle <code>hits</code>, Einträge älter als ein Tag werden aufgeräumt).</p>
