<?php /** Entwicklerhandbuch · Sprachen & Übersetzung */ ?>
  <h3>Oberfläche (i18n)</h3>
  <p>Quelltexte sind Deutsch und dienen als Schlüssel: PHP <code>__('Speichern')</code>, <code>__('{n} Einträge', ['n' =&gt; 3])</code>, JS <code>t('…')</code> (Wörterbuch als JSON im Layout). Übersetzungen in <code>lang/{locale}.php</code>, Kit-Begriffe in <code>kits/{name}/lang/{locale}.php</code>. Sprache je Benutzer (Konto) oder als Standard (Grundeinstellungen). <code>php bin/console i18n:missing en</code> listet fehlende Texte. Die Verwaltung ist vollständig ins Englische übersetzt (<code>lang/en.php</code>); neue Texte müssen dort ergänzt werden, bevor <code>i18n:missing en</code> wieder 0 meldet. Erweiterungen bringen <code>lang/{locale}.php</code> und <code>lang/site/{lang}.php</code> in ihrem Ordner mit.</p>
  <h3>Inhalte (mehrsprachige Websites)</h3>
  <ul>
    <li><b>Sprachen:</b> Grundeinstellungen → Sprachen (<code>sys.languages</code>); die erste aktive ist die Standardsprache ohne Präfix, weitere unter <code>/{code}/…</code>. <code>Core\Lang</code>: <code>all()</code>, <code>default()</code>, <code>current()</code>, <code>prefix()</code>, <code>multi()</code>.</li>
    <li><b>Seiten</b> und <b>Einträge</b> haben <code>lang</code> (NULL = Standard) und <code>translation_group</code>. <code>Pages::translate($id, 'en')</code> bzw. <code>Entries::translate()</code> legen eine verknüpfte Kopie als Entwurf an; <code>translations()</code> liefert alle Fassungen. Seitenbaum und Datenlisten filtern nach der aktuellen Sprache; Detailseiten-Vorlagen können ebenfalls übersetzt werden (Rückfall: Vorlage der Standardsprache).</li>
    <li><b>Ausgabe:</b> <code>&lt;html lang&gt;</code>, <code>hreflang</code> inkl. <code>x-default</code> (<code>$seo['alternates']</code>), Sprachumschalter über <code>language_links()</code>, übersetzbare Einstellungen per Schlüssel <code>feld@en</code> (Rückfall auf den Standardwert).</li>
    <li><b>Zentrale Einstellungen</b> (z. B. Praxis-/Unternehmensdaten): Sprachumschalter über dem Formular. In einer weiteren Sprache erscheinen nur übersetzbare Felder; gespeichert wird als <code>feld@en</code>, leere Felder zeigen den Text der Standardsprache. Übersetzbar sind standardmäßig <code>text</code>, <code>textarea</code>, <code>richtext</code>, <code>inline</code>; mit <code>'translate' =&gt; false|true</code> je Feld abweichend festlegen (z. B. Telefon, Adresse aus; Listen wie Hero-Themen oder Öffnungszeiten an – Listen werden mit der Standardsprache vorbelegt).</li>
    <li><b>Medien:</b> Titel und Alt-Text je Sprache (Spalte <code>i18n</code>, Finder-Seitenleiste und Bearbeiten-Dialog → „Übersetzungen“; API: <code>{"i18n": {"en": {"alt": "…"}}}</code>). <code>Media::alt()</code>/<code>Media::title()</code>/<code>picture()</code> liefern die Sprache der Seite, sonst die Standardsprache. Fehlende Übersetzungen sind markiert.</li>
    <li><b>Datentabellen:</b> Feldbezeichnungen und Auswahltexte je Sprache im Tabellen-Designer („Übersetzungen“); Ausgabe über <code>Tables::label()</code>/<code>Tables::optionLabel()</code>. Einträge selbst werden als eigene Fassung übersetzt.</li>
  </ul>
  <h3>Feste Texte der Website</h3>
  <p>Texte in Templates, Blöcken und Core-Ausgaben (Karten, Datenlisten, Formularmeldungen) laufen über <code>lt('Deutscher Text', ['n' =&gt; 3])</code> – in der Sprache der aufgerufenen Seite. Quellsprache = <code>theme.php → 'source_lang'</code> (Standard <code>de</code>). Übersetzungen: <code>lang/site/{lang}.php</code> (Core) und <code>kits/{name}/lang/site/{lang}.php</code> (Kit, überschreibt). Datumsangaben mit <code>date_local($datum, 'short'|'long'|'weekday'|'day_month')</code>. Telefonnummern mit <code>phone_display($nummer)</code>: in der Standardsprache wie eingegeben, in weiteren Sprachen automatisch international (<code>0211 …</code> → <code>+49 211 …</code>, Landesvorwahl unter Grundeinstellungen → Website); <code>tel_href()</code> erzeugt immer <code>tel:+49…</code>. Fehlende Texte: <code>php bin/console i18n:missing en --site-texts</code>. Formulare antworten in der Sprache der Seite, von der gesendet wurde (auch Prüfmeldungen, <code>Fields::$site</code>).</p>
  <div class="doc-note"><strong>Faustregel</strong><p><code>__()</code> = Verwaltung (Sprache der angemeldeten Person), <code>lt()</code> = Website (Sprache der Seite). Inhalte (Seiten, Einträge, Einstellungen, Medien-Texte) pflegt die Redaktion je Sprache.</p></div>
