<?php /** Entwicklerhandbuch · Stellenangebote & Google for Jobs (Core\Data\Jobs, Core\Data\Templates) */ ?>
  <p>Eine Inhaltstabelle ist eine <b>Stellen-Tabelle</b>, wenn ihr schema.org-Typ <code>JobPosting</code> ist (<code>settings.schema_type</code>, Tabellen-Designer „Strukturierte Daten“). Die Vorlage <code>jobs</code> (Daten → Vorlage „Stellenangebote“, <code>DataController::presets()</code>, Definition <code>Jobs::preset()</code>) bringt die Felder mit festen Namen (<code>Jobs::MAP</code>, einzelne umstellbar über <code>settings.jobs.map</code>):</p>
  <table class="doc-table"><thead><tr><th>Feld</th><th>JobPosting</th></tr></thead><tbody>
    <tr><td><code>titel</code> (Pflicht)</td><td><code>title</code></td></tr>
    <tr><td><code>beschreibung</code><br>(Rich-Text, Pflicht)</td><td><code>description</code> (bereinigtes HTML, leere Absätze entfernt)</td></tr>
    <tr><td><code>veroeffentlicht_am</code><br>(Datum, Pflicht, heute vorbelegt)</td><td><code>datePosted</code> (JJJJ-MM-TT; leer → Veröffentlichung des Eintrags)</td></tr>
    <tr><td><code>gueltig_bis</code> (Datum)</td><td><code>validThrough</code> = Tagesende in der Zeitzone der Website (ISO 8601 mit Offset)</td></tr>
    <tr><td><code>beschaeftigungsart</code><br>(Mehrfachauswahl)</td><td><code>employmentType</code>: vollzeit FULL_TIME, teilzeit/minijob/werkstudium PART_TIME, befristet TEMPORARY, praktikum INTERN, freie_mitarbeit CONTRACTOR, ehrenamt VOLUNTEER, ausbildung/sonstiges OTHER (doppelte zusammengefasst)</td></tr>
    <tr><td><code>strasse</code>, <code>plz</code>, <code>ort</code>,<br><code>bundesland</code>, <code>land</code></td><td><code>jobLocation</code> → Place/PostalAddress; leer = <code>address</code> der Organisation (Kit → <code>jsonld</code>); Land Standard <code>config country</code> (Standard DE)</td></tr>
    <tr><td><code>arbeitsweise</code><br>(vor_ort | hybrid | remote)</td><td>nur <code>remote</code>: <code>jobLocationType: TELECOMMUTE</code> + <code>applicantLocationRequirements</code> (Country = Land); hybrid nur in den Eckdaten</td></tr>
    <tr><td><code>gehalt_von</code>, <code>gehalt_bis</code>,<br><code>gehalt_pro</code> (HOUR … YEAR)</td><td><code>baseSalary</code> MonetaryAmount (Währung <code>config currency</code>, Standard EUR), min/max oder ein Wert; ohne Angabe weggelassen</td></tr>
    <tr><td><code>arbeitgeber</code></td><td><code>hiringOrganization.name</code>; leer = Organisation des Kits (Name, <code>sameAs</code> = Website, <code>logo</code> falls vorhanden)</td></tr>
    <tr><td><code>kennung</code></td><td><code>identifier</code> PropertyValue; leer = <code>{tabelle}-{id}</code></td></tr>
    <tr><td><code>beginn</code>, <code>bild</code>,<br><code>kurzbeschreibung</code>,<br><code>ansprechperson</code>,<br><code>kontakt_e_mail</code>, <code>kontakt_telefon</code></td><td><code>jobStartDate</code>, <code>image</code>; Kurzbeschreibung = Meta-Beschreibung; Kontakt nur auf der Seite</td></tr>
  </tbody></table>
  <ul>
    <li><b>JSON-LD</b>: <code>StructuredData::entryNode()</code> → <code>Jobs::jsonLd()</code> – genau ein JobPosting im <code>@graph</code> der Detailseite (Listen tragen nur ItemList). <code>directApply</code> = true, wenn ein Bewerbungs-Eingang verknüpft ist und Einsendungen annimmt. <code>Jobs::check($node)</code> prüft Pflicht- und Formatvorgaben von Google (title, description ≥ 100 Zeichen ohne Redaktionsnotiz, ISO-Daten, hiringOrganization.name, jobLocation mit addressCountry bzw. TELECOMMUTE + applicantLocationRequirements, employmentType-Werte, baseSalary-Aufbau); die Verwaltung zeigt das Ergebnis im Eintrag („Google for Jobs“).</li>
    <li><b>Ablauf</b>: <code>Jobs::expired()</code> (Gültig bis &lt; heute). Abgelaufen → kein JSON-LD, <code>noindex</code> (<code>Seo::forEntry</code>), Hinweis im Block <code>job_facts</code>, kein Formular. <code>Entries::where()</code> blendet abgelaufene Stellen bei <code>status = published</code> aus (Datenliste, Sitemap, Suche, API) – nicht in der Verwaltung, nicht bei <code>ids</code>, nicht mit <code>'expired' =&gt; true</code>.</li>
    <li><b>Blöcke</b> (Kern, vom Kit überschreibbar, Stile <code>css/jobs.css</code>, Variablen <code>--job-accent</code>, <code>--job-surface</code>, <code>--job-radius</code>, <code>--job-muted</code>, <code>--job-w</code>): <code>job_facts</code> (Eckdaten <code>Jobs::facts()</code>, Button „Jetzt bewerben“ → <code>#bewerben</code>) und <code>job_apply</code> (Formular des Eingangs; lädt die Stile von <code>data_form</code> mit). Die Detailvorlage (<code>Jobs::makeTemplate</code>): Datensatz-Felder (Kopf) · Eckdaten · Datensatz-Felder (Beschreibung) · Bewerbung (Sprungmarke <code>bewerben</code>). Datenliste: bei Stellen-Tabellen Kurzzeile „Vollzeit, Teilzeit · Ort“ (<code>Jobs::summary</code>); neue Block-Option <code>hide_empty</code> für alle Tabellen.</li>
    <li><b>Bewerbung</b>: <code>settings.jobs = {form: Eingang, field: 'stelle', map: {}}</code>. <code>DataForms::render(…, ['locked' =&gt; ['stelle' =&gt; …], 'hidden' =&gt; ['_job' =&gt; 'tabelle:id']])</code>; <code>DataFormController::submit</code> setzt das Feld serverseitig aus <code>_job</code> (<code>Jobs::applyPost</code>, nur veröffentlichte Stellen, nur der verknüpfte Eingang). <code>Delivery::message()</code> hängt die Stelle an den Betreff an, wenn der Betreff <code>{stelle}</code> nicht selbst enthält. Vorlage <code>applications</code> („Bewerbungen“): Stelle, Vorname*, Nachname*, E-Mail*, Telefon, Nachricht, Lebenslauf + Weitere Unterlagen (PDF/DOCX/ODT, nur mit Zustellung per E-Mail; Standard „nur per E-Mail“ an <code>sys.mail_to</code>, ohne Funktion <code>requests.mail</code>: im System, ohne Dateifelder).</li>
    <li><b>Kommandozeile</b> (wiederholbar): <code>data:template jobs [--handle=stellen] [--slug=stellen] [--form=bewerbungen|new|none] [--with-detail-page] [--with-list-page] [--dry-run]</code> (alle Vorlagen, <code>Core\Data\Templates::install</code>) · <code>jobs:from-page &lt;seite&gt; [--title=…] [--slug=…] [--employment=…] [--posted=…] [--dry-run]</code>: alte Stellenseite → Eintrag (Fließtexte → Beschreibung, Überschriften ab H2, Beschäftigungsart aus dem Text, Datum = erste Version der Seite), Formular der Seite → Bewerbungsformular (+ Feld „Stelle“), Links <code>page:ID</code> in Seiten und Einstellungen → <code>entry:tabelle:id</code>, Seite offline + 301 · <code>jobs:selftest</code>.</li>
  </ul>
