<?php /** Entwicklerhandbuch · Support & Wissensdatenbank */ ?>
  <p class="lead">Meldungen der Redaktionen an das Support-Team, Fragen &amp; Antworten und Wissensartikel – <b>eine zentrale Datenbank für alle Websites</b> der Installation (Muster wie die geteilten Medien).</p>
  <table class="doc-table">
    <tr><th>Thema</th><th>Umsetzung</th></tr>
    <tr><td>Speicher</td><td><code>storage/support/support.sqlite</code> (Tabellen <code>issues</code>, <code>issue_posts</code>, <code>files</code>, <code>seen</code>, <code>staff</code>, <code>articles</code>, <code>article_revisions</code>, <code>article_feedback</code>, <code>questions</code>, <code>answers</code>, <code>votes</code>, <code>mail_log</code>, Suchindex <code>search_idx</code>). Wird beim ersten Zugriff angelegt (<code>Core\Support\Support::db()</code>), dabei 5 Startartikel aus dem Handbuch (<code>Core\Support\Seed</code>). Bildschirmfotos unter <code>storage/support/files/JJJJ/MM/</code> (Zufallsnamen, nie im Webroot). In Sicherungen <code>storage/support/</code> mitnehmen.</td></tr>
    <tr><td>Personen</td><td>Benutzer sind je Website getrennt – im Support als <code>website:id</code> gespeichert (z. B. <code>demo:3</code>) mit Name und E-Mail zum Zeitpunkt der Meldung. Redaktionen anderer Websites sehen fremde Namen nicht („Redaktion einer anderen Website“).</td></tr>
    <tr><td>Rechte</td><td><code>support.report</code> (melden, eigene Meldungen, lesen – Standard für alle Rollen), <code>support.answer</code> (Fragen stellen/beantworten – Standard: Redaktion), <code>support.manage</code> (alle Meldungen der eigenen Website sehen und beantworten). <b>Support-Team</b> = <code>Features::integrator()</code> (Agentur/Netzwerk-Administration) oder <code>support.manage</code> auf der Hauptwebsite (<code>network_site</code>): alle Websites, Status, Zuweisung, interne Notizen, Wissensartikel, Moderation. Bestehende Rollen bekommen <code>support.report</code> (und die Redaktion <code>support.answer</code>) einmalig beim ersten Aufruf ergänzt (<code>sys.support_roles</code>).</td></tr>
    <tr><td>Funktion</td><td><code>'features' => ['support' => false]</code> schaltet Support je Website ab. Die Presets <code>content</code> und <code>minimal</code> lassen ihn an, damit die Redaktion immer melden kann.</td></tr>
    <tr><td>Datenschutz</td><td>Kontext (Website, Verwaltungsseite ohne Token-Parameter, Browser, Fenstergröße, CMS-Version, Kit, Rolle, Sprache, Umgebung) wird vor dem Senden vollständig angezeigt und ist abwählbar. Bilder: nur JPEG/PNG/WebP/GIF, max. 5 × 8 MB, <code>getimagesize</code>-Prüfung, JPEG/PNG/WebP per GD neu kodiert (EXIF/GPS entfernt). Auslieferung nur über <code>/admin/support/datei/{id}</code> nach Rechteprüfung (interne Anhänge nur fürs Team), mit <code>nosniff</code> und <code>sandbox</code>-CSP. „Als Wissensartikel veröffentlichen“ erzeugt einen Entwurf ohne Kontext, Namen, E-Mail-Adressen, Telefonnummern, IPs und Website-Adressen – Pflicht: vor dem Speichern lesen. Meldungen löscht das Support-Team endgültig (inkl. Bilder).</td></tr>
    <tr><td>E-Mails</td><td>Über <code>Core\Mailer</code> der Website, auf der gehandelt wird (außerhalb der Produktion: <code>mail_redirect</code> bzw. nur Protokoll). Neue Meldung → Team-Mitglieder mit Benachrichtigung (<code>staff.notify</code>) + <code>'support_notify' => ['…']</code>; Antwort/Status → meldende Person; Antwort der meldenden Person → zuständige Person bzw. Team. Jeder Versuch steht in <code>mail_log</code>.</td></tr>
    <tr><td>Suche</td><td><code>Core\Support\Search</code> ist der einzige Zugang; Standard <code>SqliteSearch</code>: FTS5 mit <code>tokenize = 'unicode61 remove_diacritics 2'</code>, Präfixsuche, bm25 (Titel 10 · Tags 4 · Text 1), Auszüge mit Treffermarken; ohne FTS5 automatisch LIKE. Eigene Verfahren (z. B. semantische Suche mit Symfony AI/Embeddings) implementieren <code>Core\Support\SearchBackend</code> und werden mit <code>Search::use(new …)</code> gesetzt.</td></tr>
    <tr><td>Ungelesen</td><td>Tabelle <code>seen</code> je Person und Meldung gegen <code>public_at</code> (Redaktion) bzw. <code>any_at</code> (Team, inkl. interner Notizen). Zahl in der Navigation: <code>Support::navCount()</code>.</td></tr>
    <tr><td>Kennzahlen</td><td><code>Core\Support\Tickets::stats(?string $site = null)</code> → <code>open</code>, <code>new</code>, <code>urgent</code>, <code>waiting</code>, <code>total</code> (ohne Rechteprüfung – der Aufrufer entscheidet, z. B. Netzwerk-Übersicht).</td></tr>
    <tr><td>Oberfläche</td><td>Routen <code>/admin/support/*</code> (<code>SupportController</code>) inkl. Tag-Verwaltung (<code>/admin/support/tags</code>) und Benachrichtigungs-Einstellung des Teams (<code>POST /admin/support/einstellungen</code> → <code>staff.notify</code>); Sichtbarkeit von Wissensartikeln: alle Websites, ausgewählte Websites, nur Team oder eine Website. Bereichsnavigation per Drill-down (<code>views/support/_nav.php</code>, siehe <a href="#verwaltung">Verwaltungsoberfläche</a>), Reiter in „Handbuch &amp; Hilfe“ (<code>views/support/_helptabs.php</code>), Spotlight-Gruppe „Hilfe &amp; Support“ und Treffer aus Wissensdatenbank/Fragen (<code>Support::spotlight()</code>), JavaScript <code>resources/js/_support.js</code> (Vorschläge beim Schreiben über <code>/admin/api/support/similar</code>, Einfügen von Bildschirmfotos, Stimmen). Markdown-lite (<code>Core\Support\Markdown</code>): Absätze, Listen, <code>###</code>, Code, fett/kursiv, Links über <code>Sanitizer::safeHref</code> – nie HTML.</td></tr>
    <tr><td>API &amp; MCP</td><td><code>GET /api/v1/kb?q=…</code> (Token, lesen): veröffentlichte Artikel, die für diese Website sichtbar sind. MCP-Tools <code>search_knowledge</code> (lesen) und <code>report_issue</code> (Token mit „ändern“, meldet im Namen des Token-Benutzers).</td></tr>
  </table>
