<?php /** Entwicklerhandbuch · Symbole (Phosphor duotone, Core\Icons) */ ?>
  <p class="lead">Einheitliche, zweifarbige Symbole statt Emojis: <b>Phosphor Icons</b> im Stil <b>duotone</b> (MIT-Lizenz, <code>@phosphor-icons/core</code>). Jedes Symbol hat eine Kontur und eine durchscheinende Fläche – beide in <code>currentColor</code>, die Fläche mit geringer Deckkraft. Übersicht für die Redaktion: <a href="<?= e(url('/admin/hilfe/symbole')) ?>">Handbuch &amp; Hilfe → Symbole</a>.</p>
  <table class="doc-table">
    <tr><th>Teil</th><th>Beschreibung</th></tr>
    <tr><td><code>resources/icons/icons.json</code></td><td>Kuratierte Auswahl (<?= count(\Core\Icons::catalog()['icons']) ?> Symbole) in <?= count(\Core\Icons::catalog()['topics']) ?> Themen: <?= e(implode(', ', array_map(fn($t) => $t['de'], \Core\Icons::catalog()['topics']))) ?>. Je Symbol: <code>"phosphor-name": ["Bezeichnung", "English label", "suchbegriffe"]</code>; <code>null</code> = Symbol zusätzlich in diesem Thema zeigen (Bezeichnung und Datei aus dem Thema, in dem es definiert ist). Liste <code>"core"</code>: Symbole der Verwaltung und häufige Bedienelemente, die zusammen mit dem Thema „Bedienung“ ins Kern-Sprite kommen.</td></tr>
    <tr><td><code>tools/icons.mjs</code> (Teil von <code>pnpm run build</code>)</td><td>Erzeugt in <code>public/assets/icons/</code> (Sprites aus <code>&lt;symbol id="i-{name}"&gt;</code>, Pfade auf ganze Einheiten des 256er-Rasters gerundet): <code>core.svg</code> (Kern: „Bedienung“ + <code>core</code>, ≈ 34 KB, gzip ≈ 9 KB), <b>ein Sprite je Thema</b> <code>{thema}.svg</code> (je 3–22 KB, gzip 1–7 KB; jedes Symbol liegt in genau einer Datei), <code>icons-map.json</code> (Symbolname → Datei, z. B. <code>{"car":"transport"}</code>), <code>catalog.json</code> (Themen, Bezeichnungen, Suchbegriffe; englische Tags von Phosphor), <code>icons.svg</code> (alle Symbole ≈ 250 KB – nur noch für Rückwärtskompatibilität eigener Kits) und <code>LICENSE.txt</code>. Unbekannte Namen brechen den Build ab; der Build meldet Größe roh/gzip je Datei.</td></tr>
    <tr><td><code>icon($name, ['class' =&gt; …, 'label' =&gt; …])</code></td><td>PHP-Helfer (<code>Core\Icons::render</code>): <code>&lt;svg class="ico" aria-hidden="true" focusable="false" width="1em" height="1em" fill="currentColor"&gt;&lt;use href="/assets/icons/{datei}.svg?v=…#i-name"/&gt;&lt;/svg&gt;</code> – Datei laut <code>icons-map.json</code> (<code>Icons::sprite($name)</code>); mit <code>label</code>: <code>role="img"</code> + <code>&lt;title&gt;</code>. Nimmt Symbolnamen, Menü-Schlüssel (<code>Icons::NAV</code>, z. B. <code>data</code>) und alte Zeichen (<code>Icons::LEGACY</code>, z. B. ◷ → <code>clock</code>); Unbekanntes erscheint als Text (<code>.ico--glyph</code>).</td></tr>
    <tr><td>JavaScript</td><td><code>resources/js/_icons.js</code>: <code>ico(name, klasse, label)</code> verweist wie PHP auf das Sprite des Themas (Index <code>icons-map.json</code> wird von esbuild ins Bundle übernommen), <code>icoLazy()</code>/<code>lazyIcons()</code> setzen Symbole erst ein, wenn ihre Gruppe sichtbar wird (Symbolauswahl, Übersicht „Symbole“ – der Browser lädt nur die Sprites der angesehenen Themen), <code>loadCatalog()</code> (ein Katalog für die Suche über alle Themen, ≈ 70 KB, gzip ≈ 20 KB, nur beim Öffnen der Auswahl); Basisadresse aus <code>data-icons</code> (an <code>&lt;html&gt;</code> der Verwaltung bzw. an der Werkzeugleiste der Website). Namen löst der Server auf (Feld <code>ico</code> in Favoriten, Spotlight, Seitenleiste „Eintrag“).</td></tr>
    <tr><td>Farbe &amp; Transparenz</td><td>Größe über <code>width/height</code> bzw. <code>font-size</code> (1em), Farbe über <code>color</code>. Deckkraft der Fläche: CSS-Variable <code>--ico-2-opacity</code> (Vorgabe .2; in der dunklen Verwaltung .3) – z. B. <code>.meine-kachel{--ico-2-opacity:.35}</code>. Funktioniert ohne eigenes CSS (Attribute), daher auch in Kits ohne zusätzliche Styles.</td></tr>
    <tr><td>Feldtyp <code>icon</code></td><td><code>['name' =&gt; 'icon', 'label' =&gt; 'Symbol', 'type' =&gt; 'icon']</code> – Symbolauswahl (Suche deutsch/englisch, Themen, Vorschläge, zuletzt verwendet; Tastatur: ↓ ins Raster, Pfeiltasten, Enter, Esc). Im Template: <code>&lt;?= icon($item['icon']) ?&gt;</code>. <code>options</code> erlaubt zusätzliche eigene Werte (z. B. theme-eigene Symbole).</td></tr>
    <tr><td>Datentabellen</td><td>Spalte <code>data_tables.icon</code> enthält den Symbolnamen (REST <code>/tables</code> und MCP <code>list_data_tables</code>: Feld <code>icon</code>). Übernahme alter Zeichen einmalig beim Start bzw. mit <code>php bin/console migrate</code> (<code>Icons::migrateTables()</code>, auch geteilte Tabellen); alte Werte bleiben in der Einstellung <code>sys.icons_legacy</code>.</td></tr>
    <tr><td>Website-Sprite (Besucher)</td><td>Nach dem Rendern einer Besucherseite (Seiten, Einträge, Landingpages, Suche, Fehlerseiten) ersetzt <code>Icons::siteSprite()</code> alle Verweise auf Symbol-Sprites durch <b>ein</b> Sprite der Website: <code>public/assets/icons/sites/{website}.{hash}.svg</code> mit genau den Symbolen, die bisher auf ihren Seiten vorkamen (Liste in <code>storage/…/cache/icons/site.json</code>). Neue Symbole erweitern die Liste → neue Datei (Hash aus Namen + Build), ältere Dateien werden nach zwei Tagen entfernt. Typisch wenige KB, eine Anfrage je Website, im Browser dauerhaft zwischenspeicherbar (Server: <code>Cache-Control: public, max-age=31536000, immutable</code> für <code>/assets/icons/sites/</code> empfohlen). Eingeloggte Personen sehen die Themen-Sprites. Ist der Ordner nicht beschreibbar, bleiben die Themen-Sprites – ohne Fehler. Zurücksetzen: <code>storage/…/cache/icons/</code> löschen.</td></tr>
    <tr><td>Symbolbereiche</td><td>Grundeinstellungen → Website → „Symbolbereiche in der Symbolauswahl“ (<code>sys.icon_topics</code>, Mehrfachauswahl, leer = alle): welche Themen die Symbolauswahl zeigt. „Allgemein“ und „Bedienung“ sind immer dabei (<code>Icons::ALWAYS</code>). In der Auswahl blendet „Weitere Bereiche anzeigen“ die übrigen ein (auch bei Suchtreffern). Übergabe an JavaScript: <code>data-icons-topics</code>. Die Website selbst ist davon unabhängig (Website-Sprite).</td></tr>
    <tr><td>Marken-Logos</td><td>Thema „Social Web“ enthält Logos (Facebook, Instagram, LinkedIn, X, Mastodon, YouTube, WhatsApp …). Die Marken gehören ihren Inhabern; verwenden Sie sie nur, um auf das jeweilige Angebot zu verlinken (z. B. Profil in der Fußzeile), unverändert und ohne den Eindruck einer Partnerschaft (siehe <code>THIRD-PARTY-NOTICES.md</code>).</td></tr>
  </table>
  <h3 id="symbolstil">Symbolstil der Website</h3>
  <p>Grundeinstellungen → <b>Symbolstil auf der Website</b> (<code>sys.symbol_style</code>, <code>Core\Icons::STYLES</code>): Phosphor Duotone (Standard), Linie, Fein, Haarfein, Kräftig, Gefüllt sowie die freien Linien-Sätze <b>Lucide</b> (ISC) und <b>Tabler</b> (MIT). Der Build (<code>tools/icons.mjs</code> → <code>styleSprites()</code>) legt je Stil ein Sprite mit allen Symbolen unter denselben Namen ab: <code>public/assets/icons/styles/{stil}.svg</code>. Lucide/Tabler: Zuordnung Phosphor-Name → eigener Name in <code>resources/icons/sets.json</code> (z. B. <code>magnifying-glass → search</code>); Symbole ohne Gegenstück kommen aus Phosphor „regular“ (gleiche Bildsprache). Linien-Symbole tragen <code>fill="none" stroke="currentColor"</code> am <code>&lt;symbol&gt;</code>.</p>
  <ul>
    <li><b>Besucher:</b> <code>Icons::siteSprite()</code> baut das kleine Website-Sprite aus dem Stil-Sprite (Dateiname mit Stil im Hash, Zustand je Stil in <code>cache/icons/site-{stil}.json</code>).</li>
    <li><b>Angemeldete Redaktion auf der Website</b> und die <b>Vorschau im Editor</b> (<code>/admin/api/preview</code>): <code>Icons::applyStyle()</code> stellt die Verweise auf das volle Stil-Sprite um – die Redaktionsleiste (<code>.cms-bar-host</code>) und die Verwaltung bleiben duotone.</li>
    <li>Kits, die die zweite Ebene nutzen (<code>--ico-2-opacity</code>), verlieren sie bei anderen Stilen – das ist gewollt (einfarbige Sätze).</li>
    <li>Neue Zuordnung ergänzen: Eintrag in <code>sets.json</code> (<code>lucide</code>/<code>tabler</code>) und <code>pnpm run build</code>.</li>
  </ul>
  <h3>Neues Symbol aufnehmen</h3>
  <ol>
    <li>Namen auf <a href="https://phosphoricons.com" rel="noopener">phosphoricons.com</a> suchen (z. B. <code>hand-heart</code>).</li>
    <li>In <code>resources/icons/icons.json</code> im passenden Thema ergänzen: <code>"hand-heart": ["Pflege", "Care", "fürsorge hilfe"]</code>.</li>
    <li><code>cd tools &amp;&amp; pnpm run build</code> – Sprites, Index und Katalog werden neu erzeugt, die Version im Dateinamen-Parameter ändert sich automatisch. Auf die gemeldete Größe achten (Richtwert je Themen-Sprite &lt; 40 KB). Neues Thema: Eintrag in <code>topics</code> mit <code>key</code>, <code>de</code>, <code>en</code> – es entsteht automatisch <code>{key}.svg</code>.</li>
    <li>Nur Namen aus der installierten Version von <code>@phosphor-icons/core</code> (<code>tools/node_modules/@phosphor-icons/core/assets/duotone/</code>) – unbekannte Namen brechen den Build ab.</li>
  </ol>
  <p>Lizenz: Phosphor Icons, MIT, © Phosphor Icons – Hinweis in <code>THIRD-PARTY-NOTICES.md</code> und <code>public/assets/icons/LICENSE.txt</code>.</p>
