<?php /** Entwicklerhandbuch · Tutorials & Videos (Handbuch & Hilfe › Tutorials, Core\Tutorials, tools/tutorials/record.mjs, Produkt-Website) */ ?>
  <p class="lead">Unter <a href="<?= e(url('/admin/hilfe/tutorials')) ?>">Handbuch &amp; Hilfe → Tutorials</a> stehen Anleitungen für drei Zielgruppen (Redaktion, Administration einer Website, Agenturen/Netzwerk) – Ziel, Voraussetzungen, alle Schritte, Tipps und Stolperfallen als <strong>Text</strong> (Deutsch und Englisch, auch offline). Die <strong>Videos</strong> dazu (ohne Ton, Untertitel Deutsch/Englisch) und der Trailer werden <strong>nicht mit dem CMS ausgeliefert</strong>: Sie liegen auf der Produkt-Website <a href="https://studio.klxm.de/tutorials" target="_blank" rel="noopener">studio.klxm.de/tutorials</a>, die selbst mit KLXM Studio läuft.</p>
  <div class="doc-note doc-note--tip"><strong>Wo die Videos liegen – <code>docs_url</code></strong><p><code>config/config.php</code> → <code>'docs_url' =&gt; 'https://studio.klxm.de'</code> (überschreibbar in <code>config.local.php</code> oder je Website in <code>config/sites/{key}.php</code>). Jede Tutorial-Karte, jede Tutorial-Seite und „Hilfe &amp; Einstieg“ auf der Übersicht verlinken auf <code>{docs_url}/tutorials/{kurzname}</code> (englische Verwaltung: <code>{docs_url}/en/tutorials/{kurzname}</code>), der Trailer auf <code>{docs_url}/#trailer</code> – als normaler Link in einem neuen Tab (<code>target="_blank" rel="noopener"</code>). Die Verwaltung bettet nichts ein, lädt nichts vor und stellt keine Anfrage an diese Adresse; auch <code>health</code> prüft sie nicht. Agenturen setzen eine eigene Adresse (White-Label, gleiche Pfade) oder <code>''</code> – dann gibt es keine Links nach außen, die Texte bleiben.</p></div>
  <table class="doc-table">
    <tr><th>Teil</th><th>Beschreibung</th></tr>
    <tr><td><code>app/Admin/tutorials.php</code>, <code>tutorials.en.php</code></td><td>Inhalte als PHP-Array (Englisch: gleiche Kurznamen; Schritte = englische Untertitel): <code>tracks</code> (Zielgruppen) und <code>tutorials</code> (Kurzname → Ziel, Voraussetzungen, Schritte mit den genauen Beschriftungen, Tipps, Stolperfallen, Befehle, Handbuch-Links, Funktion). Die Schritte sind zugleich das Transkript der Videos.</td></tr>
    <tr><td><code>kits/{name}/docs/tutorials.php</code></td><td>Optional, gleiches Format: gleicher Kurzname ersetzt ein Tutorial, <code>false</code> entfernt es, neue Zielgruppen/Tutorials kommen hinzu. Eigene Videos mit <code>'video' =&gt; '/kits/{name}/tutorials/datei'</code> (ohne Endung, unter <code>public/</code>).</td></tr>
    <tr><td><code>Core\Tutorials</code></td><td><code>catalogue()</code> (Kern + Kit, Sprache der Verwaltung, Link <code>web</code> je Kern-Tutorial), <code>videoUrl()</code>, <code>trailerUrl()</code>, <code>docsUrl()</code>, <code>export()</code> für <code>php bin/console tutorials:export [--out=datei.json] [--videos=ordner]</code> – JSON mit Kurzname, Zielgruppe, Stufe, Titel/Zusammenfassung/Ziel DE/EN, Schritten (HTML und Klartext), Tipps, Stolperfallen, Voraussetzungen, Handbuch-Ankern, Dauer und Dateinamen. Standard: <code>tutorials.json</code> im Ordner der Videos.</td></tr>
    <tr><td>Produkt-Website <code>site-tools/tutorials/</code></td><td>Aufnahmen (nicht im CMS): je Video <code>{kurzname}.mp4</code> (H.264, CRF 28, <code>faststart</code>, ohne Tonspur), <code>.webm</code> (VP9, ohne Tonspur), <code>.jpg</code> (Vorschaubild), <code>.de.vtt</code>/<code>.en.vtt</code> (Untertitel) und <code>videos.json</code> (Dauer, Größe, Anzahl Untertitel; oberste Ebene <code>"audio": false</code>). 1280 × 800, Smartphone-Varianten 390 × 844. Eine Videodatei für beide Sprachen. Wird es zu groß, einzelne Abläufe mit <code>noWebm</code> nur als MP4 + VTT ausliefern.</td></tr>
    <tr><td><code>HelpController::tutorials()</code>, <code>::tutorial()</code></td><td>Routen <code>/admin/hilfe/tutorials</code> und <code>/admin/hilfe/tutorials/{kurzname}</code>; empfohlene Zielgruppe nach Rolle (Integratoren/Netzwerk → Agenturen, Rechte wie Benutzer/Grundeinstellungen/Design/Tabellen → Administration, sonst Redaktion) – alle bleiben sichtbar. Kern-Tutorials: Text + Link „Video ansehen ↗“. Kit-Tutorials mit eigenem Video (<code>'video' =&gt; '/kits/{name}/tutorials/datei'</code>, lokal unter <code>public/</code>) werden als <code>&lt;video controls preload="none" poster&gt;</code> mit <code>&lt;track&gt;</code> Deutsch/Englisch eingebettet.</td></tr>
    <tr><td>Produkt-Website</td><td>Eigene KLXM-Studio-Installation (Kit <code>klxm</code>, Erweiterung <code>klxm-site</code>): <code>php bin/console klxm:seed</code> importiert die MP4-Dateien mit Vorschaubild und Untertiteln in die Mediathek (selbst gehostet) und legt aus <code>tutorials.json</code> die Seiten <code>/tutorials</code> und <code>/tutorials/{kurzname}</code> (EN <code>/en/tutorials/…</code>) an – mit Transkript, JSON-LD <code>VideoObject</code>/<code>HowTo</code> und Filter nach Zielgruppe und Stufe. Adressen hängen nur am Kurznamen.</td></tr>
  </table>
  <h3>Videos neu aufnehmen (in die Produkt-Website)</h3>
  <pre><code>node tools/tutorials/record.mjs r-seite-bearbeiten        # Ausgabe: TUT_OUT, Standard ../klxm-studio-website/site-tools/tutorials
TUT_OUT=/pfad/zur/website/site-tools/tutorials node tools/tutorials/record.mjs
php bin/console tutorials:export                          # Katalog → {TUT_OUT}/tutorials.json
cd ../klxm-studio-website &amp;&amp; php bin/console klxm:seed    # Website: Medien + Seiten /tutorials/{kurzname} aktualisieren</code></pre>
  <p>Nach Änderungen an der Oberfläche oder für ein eigenes Kit. Die Abläufe stehen in <code>tools/tutorials/flows.mjs</code> (Playwright, Chromium): anmelden, klicken und tippen mit sichtbarem Mauszeiger und Klick-Markierung, Schritte als Untertitel mit Zeitstempeln aus der Aufnahme, lange Wartezeiten (KI) werden gekürzt, Tokens und Schlüssel im Bild unkenntlich gemacht. Jeder Ablauf räumt angelegte Inhalte wieder ab.</p>
  <h3>Untertitel und Zeitplan (ohne Ton)</h3>
  <ul>
    <li><strong>Schritte = Untertitel:</strong> Jeder Schritt (<code>t.step(de, en)</code>) ist eine Untertitelzeile in beiden Sprachen, Zeitstempel = Zeitpunkt in der Aufnahme. Die Aufnahme wartet die <strong>Lesezeit</strong> ab – etwa 15 Zeichen je Sekunde des längeren Textes, mindestens 2,2 s, höchstens 6 s –, dann folgen die Aktionen des Schritts; der Untertitel bleibt stehen, bis der nächste beginnt. Gekürzte Wartezeiten (<code>t.cut</code>, z. B. KI) werden aus Bild und Zeitstempeln herausgerechnet.</li>
    <li><strong>Keine Tonspur:</strong> Das Bild wird mit <code>-an</code> kodiert; eine Videodatei für beide Sprachen. Mauszeiger, Klick-Kreise, Tastenkürzel und Markierungsrahmen bleiben als Einblendungen im Bild.</li>
    <li><strong>Cookie-Hinweis:</strong> Den Hinweis der Erweiterung Consent-Kit blendet die Aufnahme aus (wie nach einer Entscheidung, ohne Einwilligung oder Protokolleintrag) – nur Abläufe mit <code>consent: true</code> zeigen ihn.</li>
  </ul>
  <h3>Sprecher (optional, Werkzeug für später)</h3>
  <p><code>node tools/tutorials/record.mjs --voice …</code> spricht jeden Schritt zusätzlich mit <a href="https://github.com/OHF-Voice/piper1-gpl">Piper TTS</a> lokal (<code>speech.mjs</code>, <code>narrate.py</code>; Cache in <code>tools/tutorials/.narration/</code>), legt die Sätze an ihren Zeitstempeln in eine Tonspur (−18 LUFS, AAC/Opus 48 kbit/s mono) und schreibt zusätzlich <code>{kurzname}.en.mp4</code> mit englischem Sprecher. Stimmen: Deutsch <code>de_DE-eva_k-x_low</code> (M-AILABS), Englisch <code>en_US-ljspeech-high</code> (LJ Speech); nicht verwendet werden Stimmen mit nur nicht-kommerziell nutzbaren Daten (<code>lessac</code>, <code>ryan</code>, <code>pavoque</code> und davon abgeleitete wie <code>thorsten</code> medium/high). Vor dem Veröffentlichen einer Fassung mit Ton Lizenzen und Sprecher-Nachweis prüfen (THIRD-PARTY-NOTICES.md, Abschnitt 5) – die Hilfeseiten zeigen den Nachweis nur, solange Videos Ton haben.</p>
  <pre><code>pipx install piper-tts                         # einmalig; Piper 1.8 (GPL-3.0, nur Werkzeug – wird nicht ausgeliefert)
sh tools/tutorials/fetch-voices.sh             # Stimmen laden (feste Revision, SHA-256-Prüfung gegen voices/SHA256SUMS)
node tools/tutorials/record.mjs --voice r-seite   # mit Sprecher (Deutsch + Englisch)</code></pre>
  <p>Stimmen und Cache stehen in <code>.gitignore</code> und gehören nicht nach <code>public/</code>.</p>
  <div class="doc-note doc-note--warn"><strong>Keine echten Fotos in den Videos</strong><p>Die Videos werden öffentlich auf der Produkt-Website gezeigt. Abläufe, die Mediathek, Bildfelder, Uploads oder Seiten mit Bildern zeigen, laufen daher auf einer Website mit erzeugten Beispielbildern (Zugang <code>fluid</code>) oder zeigen nur Bereiche ohne Fotos. Hochgeladen werden erzeugte Dateien aus <code>tools/tutorials/samples/</code> (<code>t.file(name)</code>, <code>t.upload(datei, alt)</code>; erzeugt mit ffmpeg <code>gradients</code>/<code>mandelbrot</code>). Nach jeder Aufnahme die Einzelbilder prüfen (z. B. <code>ffmpeg -i video.mp4 -vf "fps=1/3,scale=240:-2,tile=8x5" -frames:v 1 blatt.jpg</code>).</p></div>
  <p>Weitere Werkzeuge: <code>t.signIn(zugang)</code> meldet im Vorbereiten zusätzlich bei einer anderen Website an (die Aufnahme übernimmt die Sitzung), <code>t.as(zugang)</code> liefert <code>post</code>/<code>upload</code>/<code>getJson</code> für diese Website. <code>TUT_OUT=/tmp/probe</code> schreibt einen Probelauf in ein anderes Verzeichnis (samt eigener <code>videos.json</code>). Die Aufnahme meldet einen virtuellen Passkey-Authenticator an (CDP), damit die Anmeldeseite in Headless-Chromium keinen Passkey-Fehler zeigt.</p>
  <pre><code>pnpm --dir tools install                       # einmalig (Playwright ist devDependency)
pnpm --dir tools exec playwright install chromium
cp tools/tutorials/accounts.example.json tools/tutorials/accounts.local.json   # Zugänge einer TESTKOPIE eintragen
pnpm --dir tools tutorials                     # alle Videos
node tools/tutorials/record.mjs r-seite-bearbeiten a-   # einzelne bzw. alle mit Präfix
node tools/tutorials/record.mjs --list         # Übersicht, --raw behält Rohvideos, --headed zeigt den Browser</code></pre>
  <div class="doc-note doc-note--warn"><strong>Nur gegen eine Testkopie</strong><p>Die Aufnahmen legen Seiten, Einträge, Medien, Benutzer und Tokens an und löschen sie danach wieder. Zugänge stehen in <code>accounts.local.json</code> (nicht versionieren) oder in der Datei aus <code>TUT_ACCOUNTS</code>; ffmpeg über <code>FFMPEG</code> bzw. den <code>PATH</code>. Für „Neue Website anlegen“ entfernt die Aufnahme die erzeugte Konfiguration nur, wenn <code>root</code> (Pfad der lokalen Testkopie) angegeben ist.</p></div>
  <h3>Trailer „KLXM Studio im Überblick“</h3>
  <p>Der Produkt-Trailer (Kits, Bearbeiten, Verwalten) auf der Produkt-Website (Startseite, <code>{docs_url}/#trailer</code>; Aufnahme nach <code>TRAILER_OUT</code>, Standard <code>../klxm-studio-website/site-tools/trailer</code>): <code>klxm-studio-trailer.mp4</code> (1920 × 1080, H.264, faststart), <code>.webm</code> (VP9), <code>-720.mp4</code> (1280 × 720), <code>.jpg</code> (Vorschaubild), Untertitel <code>.en.vtt</code>/<code>.de.vtt</code>/<code>.sl.vtt</code> und <code>trailer.json</code> (Dauer, Größen, Sprecher, Schnittliste). <strong>Standard ohne Ton</strong> (<code>"audio": false</code> in <code>tools/trailer/voice.json</code>): ein Untertitel je Satz, Zeiten aus der Lesezeit; <code>--voice-timing</code> übernimmt die Zeiten des Sprechers (gleicher Schnitt wie mit Ton, nur stumm). Mit <code>--voice</code> (oder <code>"audio": true</code>) kommt der <strong>englische Sprecher</strong> dazu – AAC/Opus, keine Musik, Lautheit −16 LUFS; die englischen Untertitel sind genau der gesprochene Text, Deutsch und Slowenisch Übersetzungen. Wortwahl zeitlos und beschreibend (kein „neu“, „jetzt verfügbar“ …). Kapitelkarten „01 Kits · 02 Editing · 03 Managing“, Abspann „Open source · MIT licence“. Das Drehbuch steht in <code>tools/trailer/trailer.mjs</code> (<code>vo: [[en, de, sl], …]</code> je Shot): Titelkarten, Kit-Montage und das Terminal (Content-Sync) sind HTML-Seiten mit lokalen Schriften und den Websites in iframes, Bearbeitung und Verwaltung werden live in der Testkopie aufgenommen (Bildschirmfotos per CDP in 1920 × 1080; Ladezeiten und KI-Wartezeiten werden nicht aufgenommen, Mausbewegungen je Shot mit <code>speed</code> gerafft) und mit <code>xfade</code> überblendet. Die Mindestlänge eines Shots ist seine Sprech- bzw. Lesedauer; ist ein Satz länger als die Aufnahme, hält der Schnitt das letzte Bild.</p>
  <pre><code>TUT_ACCOUNTS=/pfad/zugaenge.json node tools/trailer/trailer.mjs   # alles (ca. 10–15 Min.), Zugänge wie bei den Tutorials: demo, fluid, network
node tools/trailer/trailer.mjs --list            # Shots mit Kurznamen und Sprechertext
node tools/trailer/trailer.mjs --only=theme-,adm-media   # einzelne Shots neu (Präfix genügt), Rest aus tools/trailer/.work/
node tools/trailer/trailer.mjs --only=edit-      # die Bearbeiten-Shots bauen aufeinander auf – nur gemeinsam
node tools/trailer/trailer.mjs --cut             # nur neu schneiden und kodieren (z. B. nach Stimmenwechsel)
node tools/trailer/trailer.mjs --voice-timing    # ohne Ton, Takt vom Sprecher (wie die Fassung mit Ton)
node tools/trailer/trailer.mjs --voice           # mit englischem Sprecher (--silent erzwingt ohne Ton)</code></pre>
  <p><strong>Sprecher (optional, nur lokal, kein Cloud-Dienst):</strong> <code>tools/trailer/voice.mjs</code>; welche Stimme gilt, steht in <em>einer</em> Zeile von <code>tools/trailer/voice.json</code> (<code>"voice"</code>). Vorhanden: <code>chatterbox-cori</code> (Standard – <a href="https://github.com/resemble-ai/chatterbox">Chatterbox Multilingual</a>, Resemble AI, MIT, britisch klingend: Klang aus einer Referenz, die mit der gemeinfreien Piper-Stimme <code>en_GB-cori-high</code> erzeugt wird, <code>tools/tutorials/voices/ref-cori.wav</code>), <code>chatterbox-default</code> (eingebaute Stimme, eher amerikanisch), <code>piper-cori</code> (Piper, en_GB) und <code>say-daniel</code> (macOS). Chatterbox würfelt: je Satz werden Takes erzeugt und mit whisper.cpp gegen den Text geprüft; der erste Take mit ≥ 92 % Übereinstimmung wird in <code>voice.json</code> (<code>picks</code>) gemerkt. Aussprache (nur gesprochen, Untertitel unverändert): <code>tools/trailer/lexicon.en.json</code> – z. B. KLXM → „K-L-X-M“, KLXM AI → „K-L-X-M A-I“, Moers, REDAXO. Hörproben: <code>node tools/trailer/voice.mjs --samples</code> (→ <code>site-tools/trailer-voice-samples/*.m4a</code>). Chatterbox versieht jede Ausgabe mit dem unhörbaren PerTh-Wasserzeichen.</p>
  <pre><code>sh tools/tutorials/fetch-voices.sh                 # Piper-Stimmen (en_GB-cori-high wird bei Bedarf geladen, siehe voice.mjs)
node tools/trailer/voice.mjs --samples            # Hörproben aller Kandidaten
node tools/trailer/voice.mjs --say="KLXM Studio"  # einen Satz mit der gewählten Stimme</code></pre>
  <p><strong>Einbinden:</strong> Auf der Produkt-Website legt <code>klxm:seed</code> (bzw. einmalig <code>php site-tools/trailer-replace.php</code>) die Datei mit den drei Untertitelspuren und Transkripten in die Mediathek; der Player gibt sie als <code>&lt;track kind="subtitles" srclang="…" label="…"&gt;</code> aus, Standardspur = Sprache der Seite (<code>Core\MediaTracks::trackTags</code>). <code>.vtt</code> wird als <code>text/vtt</code> ausgeliefert, die CSP erlaubt <code>media-src 'self'</code>.</p>
  <p><strong>Tutorials ohne Ton (Standard):</strong> Die Tutorial-Videos haben keine Tonspur; <code>"audio": false</code> steht in <code>videos.json</code> (oberste Ebene). Der Trailer hat seit 2026-09-27 einen englischen Sprecher (<code>trailer.json</code> → <code>"audio"</code>). Die Hilfeseiten schreiben dann „ohne Ton, mit Untertiteln“, der Sprecher-Nachweis entfällt. Ältere Aufteilungen funktionieren weiter: stumme Kopien unter <code>silent/</code> werden bei <code>"audio": false</code> bevorzugt, <code>{name}.en.mp4</code> (englischer Sprecher) nur, solange Videos Ton haben. Prüfen: <code>ffprobe -v error -select_streams a -show_entries stream=index -of csv=p=0 datei.mp4</code> gibt nichts aus.</p>
  <div class="doc-note doc-note--warn"><strong>Nichts wird gespeichert – trotzdem nur gegen die Testkopie</strong><p>Die Aufnahme beantwortet alle schreibenden Anfragen selbst (Veröffentlichen, Speichern, Akzentfarbe …) und lässt nur Anmeldung, Vorschauen und KI-Vorschläge durch; KI-Aufrufe erscheinen im KI-Verlauf. Gezeigt werden nur die Demo-Websites (basis/demo, fluid mit erzeugten Bildern und Katzenfotos, editorial, essenz, modern, glas, nature, Landingpage „kampagne“); im Netzwerk-Shot wird der Name der Hauptwebsite unscharf gezeigt. Websites und Domains der Testkopie: <code>TRAILER_SITES='{"editorial":"http://…"}'</code>. Nach dem Aufnehmen in der Produkt-Website <code>php bin/console klxm:seed</code> ausführen – der Trailer wird nicht mit dem CMS ausgeliefert (ca. 50 MB).</p></div>
  <div class="doc-note doc-note--tip"><strong>Abläufe schreiben</strong><p>Werkzeugleiste, Block-Leisten und die Seitenleiste „Block“ liegen im Shadow DOM (<code>resources/js/_shadow.js</code>); Playwright-CSS-Locators durchdringen offene Schatten-Wurzeln. Block-Leisten sind bis zum Überfahren unsichtbar (<code>opacity: 0</code>), zählen für Playwright aber als sichtbar – daher einen bestimmten Block wählen (<code>blockEdit(t, 'Text + Bild')</code>) statt <code>.cms-block__edit:visible</code>, und mit <code>showBlock()</code> unter die klebende Kopfzeile scrollen. Unter macOS bewegt <kbd>End</kbd> in Eingabefeldern nicht die Schreibmarke. Smartphone-Aufnahmen (<code>mobile: true</code>) erscheinen beim Tutorial unter „Auf dem Smartphone“ (<code>'mobile' =&gt; kurzname</code>, Text daneben optional mit <code>'mobileText'</code>); <code>disabled</code> setzt einen Ablauf aus.</p></div>
