<?php /** Entwicklerhandbuch · Verwaltungsoberfläche: Navigation, Mobil, Favoriten, Spotlight, Hilfe */ ?>
  <p class="lead">Die Verwaltung (<code>app/Admin/views/layout.php</code>, <code>resources/js/admin.js</code>, <code>resources/css/admin.css</code>, Schrift Lato, Symbole Phosphor duotone) passt sich Rolle, Funktionsumfang und Bildschirmbreite an. Hell/Dunkel folgt dem Gerät oder der Einstellung im Konto.</p>
  <h3 id="uebersicht">Übersicht (<code>/admin</code>, <code>Core\Dashboard</code>)</h3>
  <p>Die Startseite der Verwaltung besteht aus Karten im 12er-Raster (Tablet 2 Spalten, ≤ 700 px eine Spalte): Begrüßung mit Schnellaktionen (nur, was die Rolle darf), <b>Kennzahlen</b> (Rundinstrumente wie der Block <code>dials</code>, Trend = letzte 30 Tage gegen die 30 Tage davor), <b>Was ist zu tun?</b> (<code>Metrics::todos</code>, nach Dringlichkeit), <b>Hilfe &amp; Einstieg</b>, <b>Zuletzt bearbeitet</b> sowie nachgeladene Statistiken (<code>activity</code>, <code>requests</code>, <code>top</code>, <code>upcoming</code>, <code>search</code>, <code>health</code>). Quellen: <code>pages</code>, <code>revisions</code> (je Seite nur die letzten 20 Stände – ältere Speicherungen fehlen in Aktivität und Rangliste), <code>change_log</code>, <code>media</code> (<code>Media::counts()</code>), <code>created_at</code>/<code>updated_at</code>/<code>status</code> der eigenen Datentabellen, Eingangs-Tabellen (nur Anzahlen), anonyme Such-Zähler „ohne Treffer“ (<code>Core\Search\Stats</code>, nur wenn eingeschaltet). Kein Besucher-Tracking – Besucherzahlen liefert eine Erweiterung über den Haken <a href="#dashboard-hook"><code>dashboard()</code></a>.</p>
  <p>Nachladen: <code>GET /admin/api/dashboard/{karte}</code> → <code>{html}</code> (<code>resources/js/dashboard.js</code>), Daten 5 Minuten je Website und Rolle in <code>storage/…/cache/dashboard/</code>. Ohne JavaScript zeigt <code>/admin?alle=1</code> alles sofort. Anordnung je Konto in <code>users.ui_prefs</code> → <code>{"dash": {"order": […], "hidden": […], "closed": […]}}</code>, geändert über <code>POST /admin/api/dashboard/prefs</code> (<code>do</code> = <code>up|down|hide|show|open|close|order|reset</code>) – mit JavaScript per Fetch, sonst per Formular (<code>/admin?anpassen=1</code>). Sprünge in die Mediathek-Prüfung: <code>/admin/media#check=noalt|missing:en|nocaptions</code>. Die Netzwerk-Übersicht „Alle Websites“ bleibt unter <code>/admin/network</code>.</p>

  <h3 id="navigation-arten">Seitenleiste: Hauptmenü, Administration, Sammelseiten</h3>
  <p>Das Hauptmenü enthält nur Inhalte und echte Werkzeuge; reine Einstellungen von Funktionen und Erweiterungen stehen gesammelt unter <b>Administration → Einstellungen</b> (<code>/admin/einstellungen</code>), Berichte unter <b>Statistiken</b> (<code>/admin/statistiken</code>, nur wenn vorhanden). Gehört eine Einstellungsseite zu einer Datentabelle, erscheint sie zusätzlich in deren Kopf und in der Daten-Navigation. Gesteuert über die Art der Anmeldung (<code>Core\AdminPages</code>, <a href="#erweiterungen-seiten">Verwaltungsseiten: Art und Ort</a>); <code>aria-current</code> markiert bei Seiten einer Sammelseite deren Menüpunkt.</p>
  <h3 id="drill">Drill-down-Navigation</h3>
  <p>Große Bereiche ersetzen die Hauptnavigation der Seitenleiste durch ihre Bereichsnavigation: <b>Daten</b> (<code>views/data/_nav.php</code>), <b>Support</b> (<code>views/support/_nav.php</code>), <b><?= e($aiBrand) ?></b> und „Eingereicht“ (<code>views/ai/_nav.php</code>) serverseitig; die <b>Mediathek</b> clientseitig (<code>_media.js</code>). Ein Controller übergibt dazu <code>$drill</code> (gerendertes <code>_nav.php</code>) und <code>$drillTitle</code>; das Layout setzt <code>body.is-drill</code> und rendert <code>.adm-drill</code> mit „‹ Hauptmenü“ (ohne JavaScript ein Link auf <code>/admin</code>). <code>resources/js/_drill.js</code> (<code>drill({panel, title, label, back, home, box})</code>) schaltet per <code>body.is-drill-nav</code> zwischen Bereichs- und Hauptmenü („Zurück zu …“) und legt bei mehreren Ansichten einer Tabelle (Liste, Kalender, Felder …) auf schmalen Bildschirmen eine Reiterleiste <code>.adm-subtabs</code> über den Inhalt. Favoriten bleiben sichtbar.</p>
  <h3 id="mobil">Mobil &amp; Tablet (≤ 900 px)</h3>
  <ul>
    <li>Klebende, dunkle Kopfleiste <code>.adm-top</code> (56 px): Menü-Knopf, Name der Website + aktueller Bereich, Suche (öffnet Spotlight).</li>
    <li>Die Seitenleiste wird zur Schublade von links (<code>min(320px, 86vw)</code>, <code>resources/js/_drawer.js</code>): <code>role="dialog"</code>, <code>aria-modal</code>, Fokusfalle, <kbd>Esc</kbd>, Rest der Seite <code>inert</code>, Scroll-Sperre; schließt bei Navigation, Absenden, Rückkehr aus dem Browser-Cache und beim Verbreitern. Ohne JavaScript über <code>#adm-side:target</code>. Steuerbar per Ereignis <code>adm:drawer</code>.</li>
    <li>Berührungsziele ≥ 44 px, Safe-Area-Abstände; Tabellen der Benutzer, Tokens und Netzwerk-Konten werden zu Karten; Live-Vorschauen (Einstellungen, Design) öffnen als Vollbild-Blatt. Weitere Umbrüche bei 1100, 760, 700, 600 und 520 px.</li>
  </ul>
  <h3 id="favoriten">Favoriten</h3>
  <p><code>Core\Favorites</code> speichert je Benutzer (also je Website) bis zu 30 Einträge in <code>users.favorites</code> (JSON <code>[{url, title, icon, added}]</code>). Erlaubt sind nur lokale Pfade <code>/admin…</code> mit Query und <code>#hash</code>, für die eine GET-Route der Verwaltung existiert (<code>Router::match()</code>) – ohne Schema/Host, ohne <code>//</code>, nicht <code>/admin/login|logout|setup|api/…</code>; Sitzungsparameter (<code>_csrf</code>, <code>token</code>, <code>next</code> …) werden entfernt, Query sortiert, doppelte Adressen ignoriert. Verschiebt sich ein Anker, stellt <code>migrate</code> gespeicherte Favoriten um – bisher <code>Favorites::migrateBasisAnchors()</code>: im Kit „basis“ einmalig <code>/admin/hilfe#daten</code> → <code>#einstellungen</code> (Grundeinstellungen stehen dort jetzt unter <code>#einstellungen</code>, <code>#daten</code> ist „Eigene Daten“; Merker <code>sys.fav_basis_anchor</code>).</p>
  <table class="doc-table">
    <tr><th>Endpunkt (POST, CSRF)</th><th>Parameter</th></tr>
    <tr><td><code>/admin/api/favorites</code></td><td>hinzufügen: <code>url</code>, <code>title</code>, <code>icon</code> (Menü-Schlüssel wie <code>data</code> oder Tabellensymbol)</td></tr>
    <tr><td><code>/admin/api/favorites/remove</code></td><td><code>url</code></td></tr>
    <tr><td><code>/admin/api/favorites/rename</code></td><td><code>url</code>, <code>title</code> (max. 80 Zeichen)</td></tr>
    <tr><td><code>/admin/api/favorites/reorder</code></td><td><code>order</code> (Liste der URLs) oder <code>url</code> + <code>dir=up|down</code></td></tr>
  </table>
  <p>JSON-Anfragen (<code>X-CSRF-Token</code>) bekommen <code>{ok, error, message, favorites}</code>, Formulare (Konto-Seite, ohne JavaScript) eine Weiterleitung auf <code>back</code>. Oberfläche: <code>resources/js/_favorites.js</code> (Stern neben der H1, Seitenleiste; der Vorschlag für Adresse/Titel/Symbol kommt aus <code>views/layout.php</code>). Module, die den Hash per <code>history.replaceState</code> ändern (Reiter, Mediathek <code>#m123</code>), melden das mit <code>document.dispatchEvent(new Event('adm:location'))</code>.</p>
  <h3 id="spotlight">Spotlight-Suche</h3>
  <p><code>GET /admin/api/search?q=</code> (angemeldet) liefert gruppierte Treffer: Favoriten, Aktionen, Seiten (inkl. Inhalt), Einträge aller Tabellen, Medien, Einstellungsfelder sowie „Hilfe &amp; Support“ (Wissensartikel und beantwortete Fragen, <code>Support::spotlight()</code>). Die Oberfläche (<code>resources/js/_spotlight.js</code>) öffnet mit <kbd>⌘K</kbd>/<kbd>Strg+K</kbd> in Verwaltung, Editor und Werkzeugleiste der Website. Was die Rolle nicht darf, erscheint nicht.</p>
  <h3 id="hilfe">Handbuch &amp; Hilfe</h3>
  <p>Reiter (<code>views/support/_helptabs.php</code>): Handbuch (<code>/admin/hilfe</code>, Kern-Kapitel in <code>views/help/manual/</code>, ergänzt durch <code>kits/{name}/docs/manual.php</code> – siehe <a href="#kits">Kits</a>), Wissensdatenbank und Fragen &amp; Antworten (<a href="#support">Support</a>), Symbole (<code>/admin/hilfe/symbole</code>) und dieses Entwicklerhandbuch (<code>/admin/hilfe/technik</code>, Kapitel in <code>views/help/technical/</code>). REST- und MCP-Referenz, Feldtypen, Rechte und Funktionen werden live aus dem Code erzeugt.</p>
  <h3 id="akzent">Persönliche Akzentfarbe (<code>Core\Accent</code>)</h3>
  <p>Jedes Konto wählt unter <b>Konto</b> eine von sieben kuratierten Vorlagen (<code>navy</code> = Standard, <code>petrol</code>, <code>gruen</code>, <code>violett</code>, <code>bordeaux</code>, <code>orange</code>, <code>graphit</code>) und optional „Seitenleiste mitfärben“. Gespeichert in <code>users.ui_prefs</code> (JSON <code>{"accent":"petrol","side":true}</code>, additive Spalte), ausgegeben serverseitig als <code>&lt;html class="adm-ui" data-accent="petrol" data-side="tint"&gt;</code> (<code>Accent::attrs()</code>; Standard ohne Attribute). Kein freier Farbwähler.</p>
  <ul>
    <li><b>CSS:</b> <code>resources/css/_accent.css</code> (per <code>@import</code> in <code>admin.css</code>) setzt je Vorlage einen vollständigen Token-Satz für Hell, Dunkel (<code>[data-theme=dark]</code> und <code>prefers-color-scheme</code>) und die Seitenleiste: <code>--adm-a</code>, <code>--adm-a-d</code>, <code>--adm-a-ink</code>, <code>--adm-accent-bg</code>, <code>--adm-a-rgb</code> (Fokusringe <code>rgb(var(--adm-a-rgb) / .15)</code>), <code>--adm-hover</code>/<code>--adm-press</code>, <code>--adm-mint</code> (Markierung des aktiven Menüpunkts), <code>--acc-side</code>. Vorrang über Spezifität, nicht über Reihenfolge.</li>
    <li><b>Website (Shadow DOM):</b> Werkzeugleiste (<code>Theme::toolbarHost</code>), Ebene für Dialoge/Block-Seitenleiste (<code>_shadow.js</code> übernimmt <code>data-accent</code>/<code>data-side</code> vom Host der Werkzeugleiste) und „Eintrag bearbeiten“ (<code>EntryEditController</code> → <code>accent</code>, <code>_entry_edit.js</code>) tragen dieselben Attribute; <code>admin.shadow.css</code> übersetzt die Regeln beim Build zu <code>:host(.adm-ui[data-accent=…])</code>, die Leiste selbst steht in <code>editor.shadow.css</code> (<code>--m-ico</code>, mit „mitfärben“ <code>--b-bg</code>).</li>
    <li><b>Kontrast:</b> <code>Accent::PRESETS</code> enthält die Kernfarben; <code>Accent::checks()</code> bzw. <code>php bin/console accent:check</code> prüft je Vorlage 14 Paarungen (Weiß auf Akzent ≥ 4,5:1 hell/dunkel inkl. Hover, Akzent-Text auf Hintergrund/Karte/Akzent-Hintergrund ≥ 4,5:1, Akzent/Fokusring gegen Hintergründe ≥ 3:1, Seitenleiste Text ≥ 4,5:1, Symbole/Markierung ≥ 3:1). Neue Vorlage: Werte in <code>PRESETS</code> und <code>_accent.css</code> ergänzen, <code>accent:check</code> muss bestehen.</li>
    <li><b>Einschränken:</b> <code>sys.admin_accents</code> (erlaubte Vorlagen, leer = alle) und <code>sys.admin_accent_lock</code> (nur Standard) in den Grundeinstellungen › Website. Live-Vorschau im Konto: <code>resources/js/_accent.js</code> (setzt nur die Attribute am <code>&lt;html&gt;</code>).</li>
  </ul>
  <h3 id="anmeldung">Anmeldung &amp; andere Seiten vor der Anmeldung (<code>Core\AuthScreen</code>)</h3>
  <p>Alle Seiten, die ohne Sitzung erscheinen (<code>'user' =&gt; null</code>: Anmelden, Passkey, Zwei-Faktor/Wiederherstellungscode, Einladung, Links aus E-Mails zur Adressänderung, <code>/admin/setup</code>), bekommen in <code>views/layout.php</code> denselben Rahmen: einen ruhig bewegten Farbhimmel (drei weiche Farbflächen, nur <code>transform</code> animiert, reines CSS) hinter einer Karte aus Milchglas, oben App-Icon und Name der Website (<code>views/invite/_brand.php</code>), auf der Anmeldung ein kurzer Gruß zur Tageszeit. Stylesheet <code>resources/css/auth.css</code> (≈ 7,5 KB, gzip ≈ 2 KB), nur auf diesen Seiten geladen.</p>
  <ul>
    <li><b>Tageszeit:</b> serverseitig in der Zeitzone der Website (<code>timezone</code>) als Klasse am <code>&lt;body&gt;</code>: <code>auth--morning</code> (5–10 Uhr, warm und hell), <code>auth--day</code> (11–16, hell), <code>auth--evening</code> (17–21, warm/violett), <code>auth--night</code> (22–4, tiefblau mit ein paar Sternen, immer dunkel über <code>data-theme="dark"</code>), dazu <code>is-weekend</code> (Sa/So). Sonst folgt der Himmel <code>prefers-color-scheme</code>. Kein JavaScript, kein Flackern.</li>
    <li><b>Markenfarbe:</b> Designfarbe der App (<code>AppIcons::appInfo()['theme_color']</code> = <code>sys.pwa_theme</code>, sonst Standard des Kits). <code>AuthScreen::palette()</code> nimmt Farbton und Sättigung (55–85 %) und schreibt sie in eine kleine erzeugte Datei <code>media/auth/auth-&lt;hash&gt;.css</code> (strenge CSP, keine <code>style</code>-Attribute – wie <code>Core\ImageFit</code>). Grau, fast Schwarz/Weiß und KLXM Navy selbst → KLXM-Studio-Palette (Navy 222° + Mint 158°).</li>
    <li><b>CSS-Variablen zum Anpassen</b> (auf <code>.auth-screen</code> bzw. je Tageszeit-Klasse): <code>--auth-h</code>, <code>--auth-h2</code> (Farbtöne), <code>--auth-s</code> (Sättigung), <code>--auth-brand</code>, <code>--auth-bg</code> (Grundverlauf), <code>--auth-c1</code>…<code>--auth-c3</code> (Farbflächen), <code>--auth-o</code> (Deckkraft der Flächen), <code>--auth-speed</code> (Tempo, 1 = normal), <code>--auth-glass</code>, <code>--auth-edge</code>, <code>--auth-shadow</code> (Karte), <code>--auth-dot</code>.</li>
    <li><b>Barrierefreiheit:</b> Text direkt auf dem Himmel in <code>--adm-ink</code>, Karte deckend genug für AA (ohne <code>backdrop-filter</code> und bei <code>prefers-reduced-transparency</code> ganz deckend); <code>prefers-reduced-motion</code> → stiller Verlauf, keine Einblendung; <code>forced-colors</code> → kein Himmel, Systemfarben. Fehlermeldungen sind per <code>aria-describedby</code> mit den Feldern verbunden.</li>
    <li><b>Testen:</b> <code>?tod=morning|day|evening|night</code> (und <code>&amp;weekend=1|0</code>) erzwingt die Tageszeit – nur mit <code>debug</code>, <code>environment</code> ≠ <code>production</code> oder auf <code>localhost</code>/<code>*.localhost</code>.</li>
  </ul>
