<?php /** Handbuch „praxis“ · Kapitel „Online-Anfragen“ (ersetzt das Kern-Kapitel) · @var callable $img */ ?>
  <p class="lead">Rezept- und Überweisungswünsche enthalten Gesundheitsdaten. Sie werden deshalb <b>verschlüsselt</b> gespeichert und sind nur mit dem geheimen <b>Praxisschlüssel</b> lesbar – selbst der Webhoster kann sie nicht lesen.</p>
  <?= $img('anfragen.webp', 'Liste der Online-Anfragen mit entschlüsselter Anfrage', '<b>Anfragen:</b> nach Eingabe des Praxisschlüssels werden die Inhalte angezeigt.') ?>
  <p>Jedes Formular hat einen eigenen <b>Eingang</b>: <b>Rezeptanfragen</b> (Online-Rezept) und <b>Überweisungen</b> (Online-Überweisung). Die Formulare stehen auf der Website in der Kontaktkarte und unter <code>/anfrage/rezept</code> bzw. <code>/anfrage/ueberweisung</code>.</p>
  <ol class="doc-steps">
    <li>Sie erhalten eine E-Mail „Neue Anfrage“ – <b>ohne</b> Inhalte (Datenschutz). Die Zahl neben <b>Anfragen</b> im Menü zeigt, wie viele neu sind.</li>
    <li><a href="<?= e(url('/admin/requests')) ?>">Anfragen</a> öffnen, oben <b>Rezeptanfragen</b> oder <b>Überweisungen</b> wählen, den <b>geheimen Praxisschlüssel</b> aus dem Passwortmanager einfügen, <b>Entschlüsseln</b>. Die Inhalte sind nur in dieser Ansicht sichtbar.</li>
    <li>Status setzen: <b>In Bearbeitung</b>, wenn Sie sich darum kümmern (mit <b>Zuweisen</b> sieht das Team, wer), dann <b>Als erledigt markieren</b>. Mit <b>Drucken</b> oder <b>Kopieren</b> übernehmen Sie die Angaben in das Praxisverwaltungssystem – es entsteht keine Datei auf dem Server.</li>
    <li>Erledigte Anfragen löscht die Website nach 90 Tagen automatisch (einstellbar je Eingang). Sie können auch sofort <b>löschen</b>.</li>
  </ol>
  <h3>Medikamente</h3>
  <p>Im Online-Rezept tragen Patientinnen und Patienten ihre Medikamente in ein <b>mehrzeiliges Textfeld</b> ein – Name, Stärke und Packungsgröße, eine Zeile pro Medikament (seit 29.09.2026; vorher je Medikament eine eigene Zeile mit „+ Weiteres Medikament“). Anfragen aus der Zeit davor zeigen ihre Medikamente nach dem Entschlüsseln weiterhin als kleine Tabelle (Medikament, Stärke / Dosierung, Packungsgröße).</p>
  <h3>Formularfelder ändern</h3>
  <p>Die Felder der Formulare stehen im jeweiligen Eingang: <b>Daten → Rezeptanfragen</b> bzw. <b>Überweisungen → Felder &amp; Einstellungen</b> (Recht „Tabellen und Felder ändern“, Standard: Administration). Dort ändern Sie auch Titel, Einleitung, den Text nach dem Absenden, die Benachrichtigung und die Löschfrist. Ob Rezept und Überweisung angeboten werden – intern oder als Link zu einem externen Dienst –, stellen Sie unter <b>Praxisdaten → Online-Services</b> ein.</p>
  <p>Wer Anfragen lesen darf, legen Sie unter <b>Benutzer &amp; Rollen</b> fest – auf Wunsch nur für einen Eingang (z. B. eine Rolle nur für Rezeptanfragen). Jedes Entschlüsseln, Ändern und Löschen wird ohne Inhalte protokolliert (<b>Anfragen → Protokoll</b>, nur Administration).</p>
  <div class="doc-note doc-note--important"><strong>Den Praxisschlüssel nie verlieren</strong><p>Er wird bei der Einrichtung genau einmal angezeigt und nirgends auf dem Server gespeichert. Ohne ihn sind gespeicherte Anfragen nicht mehr lesbar. Bewahren Sie ihn im Passwortmanager der Praxis auf – nicht per E-Mail versenden.</p></div>
